### ISSUE TITLE
Doesn't build due to missing file

### ISSUE THREAD

**Issue by bc3tech** [Windows-XAML/Template10#10]
Severity    Code    Description Project File    Line
Error       Source file 'C:\Users\Brandon\Projects\Github\Template10\Template10Library\Common\ViewWrapper.cs' could not be found.   Template10Library   C:\Users\Brandon\Projects\Github\Template10\Template10Library\CSC

**Comment by JerryNixon** [comment]
Brandon, I just committed what I think is a working build. Will you check it out? The Services projects and the Experimental project should be UNLOADED ad they are not stable yet.

**Comment by plettb** [comment]
I just tried it and it seems to be building now.  This time, perhaps, the "missing files" issue can be legitimately closed.  :-)

**Comment by bc3tech** [comment]
Updating my fork and giving 'er a run...
