### ISSUE TITLE
Error Handling in Template 10 App

### ISSUE THREAD

**Issue by f-pohl** [Windows-XAML/Template10#1000]
Hello,
what is the recommended way to implement an error handler for an app built with Template10?
I want to ask the user to send an Email to me when the app crashes.

**Comment by Opiumtm** [comment]
I catch most unhandled errors in App event handler, store it in data folder and later give opportunity to view them and send to me via email or copy/paste. Sadly, not all unhandled exceptions are catched properly.

Anyway, I think it's time to look at Application Insights library. It do most work.

**Comment by JerryNixon** [comment]
FYI: Application Insights has been replaced by HockeyApp.
