### ISSUE TITLE
 Programmatic Manipulation of Navigation

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#1008]
I haven't done Frame _BackStack_ manipulation in a while (for such things as skipping a page) and now I needed it, and things don't seem to be as they used to be (or missing something?).

I started off with nav object (inside any window):

```
    var nav = Template10.Common.WindowWrapper.Current().NavigationServices.FirstOrDefault();
```

~~Note: the wiki [refers to the above](https://github.com/Windows-XAML/Template10/wiki/Docs-|-Services#navigationservice) as:~~  
~~without **s** and obviously this needs amending as `NavigationService` has changed to `List<INavigationService>` ??.~~  **The Wiki is now updated.**

Obtaining a frame as:

```
    var frame = nav.Frame;
```

and doing the usual BackStack manipulations, I thought I could see some actions but no luck.

```
    if (frame.CanGoBack) frame.GoBack();                // nope!  Page stays where it is.
    frame.BackStack.Remove(Frame.BackStack.Last());     // nope!  BackStackDepth decrements as expected.
```

Am I missing something, using it the wrong way?

**Comment by JerryNixon** [comment]
I will trust you to update the Wiki for the rest of our benefit. :)

**Comment by dg2k** [comment]
@JerryNixon -- Wiki done!

**Comment by dg2k** [comment]
Sorry folks, all is fine.

I managed to wind myself up by moving code fragments around and inadvertently calling Navigation manipulation code indirectly from where it shouldn't belong -- from **OnNavigatedTo** event handler where navigation is not yet completed -- rather than from **Loaded** event handler (in view) where page navigation is complete.

A small tip from time I've wasted: Just in case you haven't done before things like page skipping with programmatic navigation, you may like to take note of this to save yourself time if you need it.

**Avoid doing programmatic navigation from within Navigation events.**
