### ISSUE TITLE
BackRequested not raised when clicking back button on PageHeader

### ISSUE THREAD

**Issue by IIARROWS** [Windows-XAML/Template10#1015]
This is a follow up of this issue:  #463
The BackRequested is raised only using hardware buttons, I tried with Windows Phone emulator and the back button on my mouse.
It doesn't work clicking the back button on PageHeader on PC.

On 1.1.11

**Comment by mvermef** [comment]
What version is being used

**Comment by IIARROWS** [comment]
My bad, is 1.1.11, updated to its stable version.
But it's not only on stable, it happened on the previous beta too.

**Comment by mvermef** [comment]
I just ran my app on my phone it works just fine with the backbutton.

**Comment by IIARROWS** [comment]
Well, on phone it works because you have only the physical button and that works as I said.
The issue happens only using the software back button on the page header, it directly call the OnNavigationFromAsync without passing through the FrameFacade.BackRequested event.

This is the code:

```
public override async Task OnNavigatedToAsync(object parameter, NavigationMode mode, IDictionary<string, object> state)
{
    NavigationService.FrameFacade.BackRequested += FrameFacade_BackRequested;
    await Task.CompletedTask;
}

public override async Task OnNavigatingFromAsync(NavigatingEventArgs args)
{
    NavigationService.FrameFacade.BackRequested -= FrameFacade_BackRequested;//Unsubscribe
    await Task.CompletedTask;
}

public async void FrameFacade_BackRequested(object sender, HandledEventArgs e)
{
    //My Logic here
}
```

**Comment by mvermef** [comment]
Yeah sorry misread your OP, I will look at it shortly. You are just trying to intercept the back request and add some additional logic..

**Comment by mvermef** [comment]
found 2 items that might affect it...

**Comment by mvermef** [comment]
played around alittle see if I could duplicate and it does appear to be skipping... not sure why.

**Comment by JerryNixon** [comment]
I anyone else getting this behavior? @Windows-XAML/community

**Comment by oadugmore** [comment]
[I noticed this back in February](http://stackoverflow.com/a/35528914/4480347). I can't personally confirm it _still_ exists as I haven't used Template10 in a while (I've been busy with other types of projects).

**Comment by effpath999** [comment]
I'm using version **1.1.10** and have exactly the same code and works very fine, both with the hardware button and with the software one on desktop.

**Comment by IIARROWS** [comment]
I can't check it now, but can you try to update to latest version? You can always switch back if you don't want to update your solution.

**Comment by effpath999** [comment]
@IIARROWS sorry for answering so late, but i didn't have time to check it before today.
So I try to upgrade my project to use Template10 1.1.11 but still my event handler is called correctly.

**Comment by IIARROWS** [comment]
Nothing to be sorry about, thank you for your help...

**Comment by IIARROWS** [comment]
To me it's not close, I still get this behavior...
I just couldn't respond because I was busy.

**Comment by JWH89** [comment]
Hello all,

I request this to be reopened, for me this issue is still there (Template10 V1.1.12). In my app I have to override the default back behavior. And the only way to hit my custom BackRequest event is when the shell back button is disabled.
