### ISSUE TITLE
persist GridView layout question

### ISSUE THREAD

**Issue by dubstylee** [Windows-XAML/Template10#1017]
This isn't necessarily an issue per se, but a question. Template10 saves the window size information when it is closed, so when you re-open the application it is the same place/size as when you closed it.

Does it use the registry for this, or some other configuration file? Is there an easy way to also include the layout of a GridView? I have a GridView on my main page, and I have enabled drag/drop/reorder. I could potentially store the order in my database and load the layout information when starting the application to restore the layout, but I just thought I would check if there is a more simple way?

**Comment by dg2k** [comment]
Apps don't touch the Registry, remember apps are totally compartmentalized -- let alone Registry, they are not even allowed to touch an ordinary user file without user's permission (be it directly or indirectly). Apps reside under a directory `%LOCALAPPDATA%\Packages\<App Unique Long Alphanumeric ID>` where the `<App Unique Long Alphanumeric ID>` looks something like `0a19433d-7830-433e-9a14-78eec6v9c484_8wekyb3d8bbwe`. [Okay- this is for desktop  but something similar for mobile and other platforms]. Under that folder you'll find over half a dozen sub-folders, each storing various types of info, including the Settings folder where your (roaming and non roaming) settings are stored. This is for information only, for curiosity's sake -- you are not gonna touch those folders directly.   Those folders are usable through various API's that UWP provides (for instance, for using a TEMP folder, for creating a Cache folder, create a unique local sub-folder for your app, persist setting and restore for your app, etc).

To use settings API, get to know the **SettingsService** provided by Template10. The Sample projects demonstrate more than you need to get started. In fact, 90% of the work is done for you, it's a matter of just adding properties for your settings and UI in XAML. See for instance how the **AppTheme** setting is implemented for saving and restoring values, then it's kinda doing something similar. You'll be pleasantly surprised how life is made so easy with Template10 Services, SettingsService being one good example for demonstrating the joy of using Template10.

**Comment by dubstylee** [comment]
Thanks for the info - yeah, I have used the SettingsService already to add some new settings. I will look into it some more to achieve what I am hoping to. Specifically, I'll look into the AppTheme setting and see what it is doing. Thanks!
