### ISSUE TITLE
IsDirty flag in the validation sample's ModelBase

### ISSUE THREAD

**Issue by plettb** [Windows-XAML/Template10#1019]
I believe the "IsDirty" property needs to roll up.  So, instead of simply saying "public bool IsDirty { get; }" (line 79), I believe the code should look something like "public bool IsDirty => Properties.Any(p => p.Value.IsDirty);"

I tried to upload this change but seem to be forbidden from pushing changes.  Of course, it's quite possible that I simply don't know Git well enough.

Brad.

**Comment by mvermef** [comment]
create a fork of template10, fix it in your's, submit a Pull Request.  He will evaluate it and either say no or ask for more to be put into the PR.  Once he is satisfied that it's good, he will merge it.

**Comment by JerryNixon** [comment]
Yep.
