### ISSUE TITLE
NullReferenceException in BootStrapper.InternalLaunchAsync

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [Windows-XAML/Template10#1021]
I wonder if it was fixed already, but I got this in production:

1 Template10::Common::BootStrapper::_InternalLaunchAsync_d__53.MoveNext 0x201 
 2 SharedLibrary System::Runtime::ExceptionServices::ExceptionDispatchInfo.Throw 0x21 
 3 SharedLibrary $13_System::Runtime::CompilerServices::AsyncMethodBuilderCore::__c._ThrowAsync_b__9_0 0x1E 
 4 SharedLibrary $13_System::Threading::WinRTSynchronizationContext::Invoker.InvokeCore

**Comment by mvermef** [comment]
Where did you get that, or what did you call?

**Comment by mvermef** [comment]
Only thing I have seen related to dispatcher was related to EFCore.Tools, they are not necessary for release.

**Comment by Viachaslau-Zinkevich** [comment]
@mvermef I've got the issue from Dev center exceptions. I don't call anything :) This is only stacktrace I got from Dev center.

**Comment by JerryNixon** [comment]
@Viachaslau-Zinkevich I am closing this issue because we have so little information. If this were epidemic (everyone was getting it) we'd have something. If you guys get more information, let me know, open a new issue, we'll chase it then. Make sense?
