### ISSUE TITLE
Show a Modal Dialog in OnNavigatingFromAsync - another issue

### ISSUE THREAD

**Issue by kfchengkf** [Windows-XAML/Template10#1022]
I refer to the issue Show a Modal Dialog in OnNavigatingFromAsync  #737

I used the sample code from darenm and was able to achieve the desire result.
However there is an issue that appear when deployed on a windows phone (not on desktop)
When the apps is suspended and then resumed and the hardware back button pressed,
the yes/no dialog show up, but at the same time, the apps quit (not sure if crashed or not).
The yes / no button was not pressed yet.

The dialog that I am using is a MessageDialog.

I am using version 1.1.11 of T10.

Any idea ?

**Comment by JerryNixon** [comment]
There is a major change necessary to the NavService to get this to work. Right now it relies on the eventing of the native Frame. This is okay, but it does not properly defer async operations, and that is the pain point you are seeing. This isn't exactly a NavService rewrite, but it's close. That's what's holding me back. The current service is so freaking stable, a major change is going to be a pain. That's all.

**Comment by kfchengkf** [comment]
Thanks for the explanation.
After testing, it seems that a try catch block around the ShowAsync() call of MessageDialog is enough to prevent the issue from happening.
