### ISSUE TITLE
Back navigation cancel is not working 

### ISSUE THREAD

**Issue by yuri-stepanov** [Windows-XAML/Template10#1023]
Hi, I am trying to prevent user from accidentally leave page using this code.

`public override async Task OnNavigatingFromAsync(NavigatingEventArgs args)`
`{`
    `var defferal = args.GetDeferral();`
    `var confirmNavigation = await DialogManager.ShowConfirmDialog("Discard all changes?");`
    `args.Cancel = !confirmNavigation;`
    `defferal.Complete();`
`}`
But instead it goes back anyway and display confirmation dialog on a new page.

**Comment by darenm** [comment]
Look at: https://github.com/Windows-XAML/Template10/issues/737
