### ISSUE TITLE
In a TestMethod, I am asserting that a PropertyChanged has occured

### ISSUE THREAD

**Issue by jmbezeau** [Windows-XAML/Template10#1025]
I have a class that inherits from BindingBase, I want to assert that a property has been changed using:

target.PropertyChanged += (o, e) => { if (e.PropertyName.Equals(nameof(PictureBrowser.PictureFile))) actual++; };

so that actual is incremented every time the PictureFile property is changed.

When PropertyChanged fires, I get a NullReferenceException. I assume it is due to some uninitialized dispatcher variable. Is there a way to initialize something in my test method?

**Comment by Authfix** [comment]
Hi,

You're right, you have some missing initialization variables. 

If you look at T10 source code, you can see that the framework use a class called WindowWrapper. So in a Unit Test app, this wrapper is not initialized (normal).

In my case, I have rewrite my unit test app class with the following code to avoid this "issue"

``` csharp
[Bindable]
sealed partial class App
{

    /// <summary>
    /// Initialize a default <see cref="App"/>
    /// </summary>
    public App()
    {
        InitializeComponent();
    }

    public override async Task OnInitializeAsync(IActivatedEventArgs args)
    {
        await Task.CompletedTask;
    }

    public override async Task OnStartAsync(BootStrapper.StartKind startKind, IActivatedEventArgs args)
    {
        LaunchActivatedEventArgs e = args as LaunchActivatedEventArgs;

        Microsoft.VisualStudio.TestPlatform.TestExecutor.UnitTestClient.CreateDefaultUI();

        Microsoft.VisualStudio.TestPlatform.TestExecutor.UnitTestClient.Run(e.Arguments);

        await Task.CompletedTask;
    }
}
```

**Comment by jmbezeau** [comment]
Did you completely replace the UnitTestApp.xaml.cs file this App class?  I can't override those two methods since they are not implemented in the base class. I have tried replacing the base class from Application to Template10.Common.BootStrapper and I still didn't have a base class with those two methods.

Thanks for the answer, I am still trying to figure out how to properly do a UWP app.  I develop using TDD, so my ViewModels and Models are working properly, except when called by the XAML binding.

**Comment by jmbezeau** [comment]
I have figured out how to modify the App class and the XAML of the test app. It is working now. 

The UnitTestApp.xaml looks like this:

```
<common:BootStrapper
    x:Class="ImageServer_Test.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:common="using:Template10.Common"
    RequestedTheme="Light">

</common:BootStrapper>
```

The Code behind looks like the provided example, except for the class declaration:

```

    sealed partial class App : Template10.Common.BootStrapper
    {
        InitializeComponent();
    }

    public override async Task OnStartAsync(BootStrapper.StartKind startKind, IActivatedEventArgs args)
    {
        LaunchActivatedEventArgs e = args as LaunchActivatedEventArgs;

        Microsoft.VisualStudio.TestPlatform.TestExecutor.UnitTestClient.CreateDefaultUI();
        Microsoft.VisualStudio.TestPlatform.TestExecutor.UnitTestClient.Run(e.Arguments);

        await Task.CompletedTask;
    }

```
