### ISSUE TITLE
Back Button Wrong Behavior When PageHeader in UserControl

### ISSUE THREAD

**Issue by fradebru** [Windows-XAML/Template10#1031]
I have three pages (Page1, Page2, Page3). I can navigate from Page1 to Page2 to Page3. With the backbutton I can then navigate back in the stack.

Page2 and Page3 contain a UserControl. The UserControl contains the PageHeader. I bind the Frame from the Page to the UserControl (custom dependency property) to the PageHeader.

When I run the app on a desktop (local machine) I see the following behavior:
1. Page1
2. NavigateTo: Page2
3. NavigateTo: Page3
4. BackButton: Page2 (correct)
5. BackButton: Page1 (correct)
6. NavigateTo: Page2
7. NavigateTo: Page3
8. BackButton: Page1 (not correct, should have been Page2)

Same behavior occurs if I omit step 5 and go to Page3 directly. Then the BackButton on Page3 leads me to Page1.

If I run the same app on the mobile emulator, the behavior is as intended.

If I remove the user controls, and put the PageHeaders on the Page directly, also the behavior is as intended.

Any idea what is going wrong here?

Thanks in advance,
Franck

**Comment by JerryNixon** [comment]
No way. Really?
