### ISSUE TITLE
New logo proposal

### ISSUE THREAD

**Issue by mklemarczyk** [Windows-XAML/Template10#1033]
I propose change logo to this one.
![t10](https://cloud.githubusercontent.com/assets/2727261/15798971/3b268712-2a4d-11e6-9373-ce17b6deb0b7.png)

Any suggestions write below.

**Comment by dg2k** [comment]
Isn't this a monumental digression considering that this is a coding community rather than logo design?
I'm also curious -- what's wrong with the existing T10 logo anyway?

Note that T10 is not a product to be promoted with a logo; T10 is a library for developing UWP _products_.

**Comment by mvermef** [comment]
That and Jerry has previously turned this down

**Comment by mklemarczyk** [comment]
So what @dg2k ? Does non-commercial product not deserve for a nice logo?
@mvermef it is open source project.

**Comment by dg2k** [comment]
@mklemarczyk  Needless to say, "nice" is a very subjective word. I sense that you find the existing T10 logo not as _nice_ as the one you're proposing. Personally, it makes no difference to me what logo is used for T10, in as far as it does the job of distinctly identifying T10 where it matters -- in connection with VS extension and NuGet package, which the existing logo does very well. It's distinct and I might add bold (yes, subjective!). If you ask me what you're proposing, it looks to me another Windows family product and in my opinion it loses that distinctiveness in the context of what T10 really _is_.

As I tried to convey in my initial comment, I personally find this issue at best very peripheral but good luck with it.

**Comment by mvermef** [comment]
@mklemarczyk That as in the above statement @dg2k stated. Secondly, I am very well aware it is an open source product.... #712  was the first time not enough?  Guess you didn't want to keep attacking someone with the edited out part about proper english, nice.  

calling the kettle black

>  Does non-commercial product not deserve for a nice logo?

Good luck as well...

**Comment by callummoffat** [comment]
I prefer the current logo, and, even if I didn't, I agree with the other guys in this conversation. If you don't like the logo, submit a PR with your proposed changes, and let the community decide.

**Comment by JerryNixon** [comment]
No plans to change

**Comment by mklemarczyk** [comment]
Anyway I will fork this project.
