### ISSUE TITLE
Unhandled win32 exception after updating from 1.1.10 to 1.1.11

### ISSUE THREAD

**Issue by wleev** [Windows-XAML/Template10#1044]
The moment I update the library to the new 1.1.11 version my application starts throwing a win32 exception on every go. I've tried to debug as much as I can, but I can't seem to produce anything close to a  decipherable stack trace. 

When I enable native debugging:

```
0x40080201 occurred
Message: Exception thrown at 0x76EE1C38 (KernelBase.dll) in Asteria.Ion.exe: 0x40080201: WinRT originate error (parameters: 0x80070057, 0x0000002F, 0x06CFE594).
```

When I debug my unit tests though, something different pops up:

```
EETypeLoadException occurred
Message: Exception thrown at 0x76EE1C38 in Asteria.IonUnitTest.exe: Microsoft C++ exception: EETypeLoadException at memory location 0x0CCEC940.
```

Not sure how to reproduce it except from updating the library. If someone can instruct me how to do some more specific debugging, I'm willing to research it more. For the mean time I'll be returning to v1.1.10.

Update: Thought it might be related to me being on Insider Preview, but after testing on another box it seems like that's not the case.

**Comment by angusbreno** [comment]
Some people in my team is getting this problem too, i'm looking for the cause. Idk if it is Template10 relative issue (but start to happen after the template update).

**Comment by angusbreno** [comment]
Trying find the problem. Question: Your app has a splash screen (from T10) right?

If yes, comment the splashfactory. 

Like this
`//SplashFactory = (e) => new Views.Splash(e);`

Run app.

It worked right?

**Comment by wleev** [comment]
@angusbreno Yeah, that seemed to do the trick. Tried to do some debugging of myself, but couldn't really find an immediate cause myself. Luckily I don't need the extended splash screen at this point. 

Thanks for clearing up that headache.

**Comment by angusbreno** [comment]
I'm passing for this too... I'm looking for the cause, but seens something about how Splash content works inside bootstrapper... 

I'm working on that. 

@JerryNixon did u already see this?

**Comment by arpadbarta** [comment]
Same behaviour here too, Win32 Exception, after commenting out Splash screen disappears...

**Comment by CntPickle** [comment]
I have observed the same, for what it's worth.

**Comment by angusbreno** [comment]
I'm busy with other projects until Monday, I will look into after that day. Btw as workarround comment splash factory.

**Comment by JerryNixon** [comment]
Please copy the splash code-behind (and XAML) from a new project and see if that makes a difference. If for no other reason, just to test a theory.

**Comment by wleev** [comment]
@JerryNixon 
No difference when replaced, still same win32 exception.

**Comment by angusbreno** [comment]
@JerryNixon Just create a new project of template10 and put a splashfactory, the error happens...

What i've found until now it's when the new NavigationService it's created in splash phase the GetDispatcher is comming null...

**Comment by JerryNixon** [comment]
Could you paste your factory code?

**Comment by JerryNixon** [comment]
I want you guys to know, I can't repro this on my side.
1. New project [hamburger]
2. Leave the default splash
3. Ensure OnStartAsync delay of 5 sec
4. Run it

Every single time, the same, good result.

**Comment by angusbreno** [comment]
@JerryNixon what can i do to show the problem? Because it's not possible debug (i've try attach the debugger to process with w32,clr... and nothing)...
SplashFactory is normal believe haha

There is something really strange, "i've found" the problem. 

Guys, if possible make a copy of your project add template10 files as reference, put splash. 
Go to this line:
https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Common/BootStrapper.cs#L656

and comment 
`//CurrentState = States.Splashing;`

It will work right? For me makes no sense.

:alien:

**Comment by JerryNixon** [comment]
@angusbreno could you try a few things?
1.  Using the source (so you can debug) if you step through line by line do you still get this exception? Does stepping through give you any clue what line you are near when it occurs?

![image](https://cloud.githubusercontent.com/assets/1749983/16779755/cc7024ca-4830-11e6-93d0-3bcb8c55f683.png)
1. Could you use the source code, run in debug, and attach a txt file of your debug output so I can look at the execution path of what's happening in Template 10?

![image](https://cloud.githubusercontent.com/assets/1749983/16779733/b3f1be54-4830-11e6-89a3-87425a9d55a2.png)
1. Could you ensure in Exception Settings that you have set to catch all exceptions with the hope that this will cause the execution to stop on a certain line when it occurs.

![image](https://cloud.githubusercontent.com/assets/1749983/16779676/7dec9108-4830-11e6-8ebc-60f82ad75118.png)
1. Could you verify that you see this behavior in a brand new project? Is this only happening in your project or is it happening on your system?

I know this is a lot of little things, but it's a start for us to see if we can figure out the problem. Remember, when you are investigating, we don't need to know the exact line if we can find the line NEAR the problem. Sometimes debugging is a matter of the mind more than Visual Studio :)

Thanks,
Jerry

**Comment by angusbreno** [comment]
1. Yes
2. Sure
3. Yes, catching All the Exceptions
4. Brand new project & my project.

I will do a livecoding about it in a brand new project with the actual codebase ok? https://www.livecoding.tv

I will post here the time, thanks!

**Comment by JerryNixon** [comment]
Let me know.
