### ISSUE TITLE
Bug in PageHeader.SecondaryCommands list

### ISSUE THREAD

**Issue by aannenko** [Windows-XAML/Template10#1047]
Description:
Exception is thrown whenever I try to scroll through the secondary commands' list of the page header.
The exception message is "Layout cycle detected. Layout could not complete."

Steps to reproduce:
1. Create a new app using a hamburger or minimal template
2. Build and launch the app
3. Click a button with three dots on it in the top right corner of the app
4. Hover any item in the list with your mouse pointer and try to scroll in any direction

Result:
![2016-06-10](https://cloud.githubusercontent.com/assets/4640265/15975603/ef5847d0-2f56-11e6-99dc-231dd8abe88b.png)

**Comment by mvermef** [comment]
Version? Do you have any Ellipsis Behaviors in markup?

**Comment by aannenko** [comment]
Plugin version: 1.18
Package version (in the solution): 1.1.10 or 1.1.11
I didn't touch XAML after the application creation.

**Comment by mvermef** [comment]
so no changes bare bones, hamburger application?

**Comment by aannenko** [comment]
That's right.
I have interface scaling set to 125% in Windows Settings. Can this be a reason?

**Comment by mvermef** [comment]
Pc or 2in1, the template will determine screen size and reacts accordingly

**Comment by aannenko** [comment]
PC

**Comment by JerryNixon** [comment]
Could you please review this known issue? Then report.
https://github.com/Windows-XAML/Template10/issues/857

**Comment by aannenko** [comment]
Yes, I've seen it but my case is a bit different: when the app is created, it already has T10 v. 1.1.10 (I can update it to 1.1.11 but it won't change anything) and I  also don't change anything in the app.

**Comment by JerryNixon** [comment]
New question. Are you using a `<Hub />` control?

**Comment by aannenko** [comment]
Hi @JerryNixon ! Hub is not used. Nothing is added to the code the template already has, so it is just a clean template.
Again, here are the steps that I do to reproduce this issue:
- I start my Visual Studio Community 2015;
- I click Create Project link on the start page in Visual Studio;
- I select the Hamburger (Template 10) template and click OK;
- I click F5 to run this newly created project;
- When the application starts, I click the ellipsis button in the top right corner of the app, align the mouse pointer over any element of the menu that has just opened and turn the scroll wheel up or down couple of times.

That's it. After this I get the exception.

I get this exception on my desktop and on a Surface Book. I haven't tried to reproduce it anywhere else.

**Comment by JerryNixon** [comment]
Thanks for reporting this. Well, there's nothing I can do to repro this. Let me ask you another question. Are you using any scale factor? Does your machine read 100%?

![image](https://cloud.githubusercontent.com/assets/1749983/16422484/c27f16fe-3d15-11e6-940c-fc74ddfdd8b7.png)

**Comment by aannenko** [comment]
It's 125% on my desktop computer and 200% on surface book.
I was mentioning it couple of posts earlier.
I'll do a test with 100% scaling and will get back here with results in a moment.

**Comment by aannenko** [comment]
Yes, when the scaling is set to 100% it works just fine. No scroll bar is visible when I try to scroll.

**Comment by aannenko** [comment]
Oh cool, People app is failing too. And the Windows Feedback app does not. It seems when the scaling factor is set to more than 100%, any app will fail if it has more than one secondary command in the command bar.

Sorry then. I should have tested it before posting here.

**Comment by JerryNixon** [comment]
Good. We figured it out. Let me reach out to the control lead.

**Comment by JerryNixon** [comment]
The team says this is fixed in RS1. Let's hope so.
