### ISSUE TITLE
Improvements in SettingsService

### ISSUE THREAD

**Issue by RomeoPavoni** [Windows-XAML/Template10#105]
I'm trying to copy the Minimal project settings management in my application but i see that Settings Interface and Service are in the Minimal project but SettingsHelper is in the Template project.

In my opinion these three items should be together with the interface improved in a same project ready to consume in our personal projects, what do you think about grouping them together like other services? I don't know if moving them in Services breaks something or they can correctly be referenced in the Library

**Comment by JerryNixon** [comment]
Services is special. It is unique to each project. The helper is generic to all projects. The interface is for the service and not the helper. Grouping the service and interface is fine. Grouping with the helper is not. Do you see why?

**Comment by RomeoPavoni** [comment]
The point is when you want to use a Class Library in order to reuse stuff. I'm working in this way in my solutions and i put in a class library models, viewmodels, interfaces and messages and leave in the main project services and views. Due to this approach (of course it could be wrong) i need to split services and interfaces in different projects.

I try to adopt SettingsService from Minimal in my solution and i can copy the interface (adding all the helper methods) into the class library and the service (adding calls to all helper methods) in the main project while helper is referenced as is from Template10 Library, all using MVVM Light with dependency injection.

IT culd be an idea Template10 showing the best practice also for this kind of scenario (with class library), if you agree i could set up a new working Template starting from Minimal, with also all strings localized using MAT inside a PCL

**Comment by JerryNixon** [comment]
Here's ISettingsService today:

``` csharp
namespace Sample.Services.SettingsServices
{
    public interface ISettingsService
    {
        bool UseShellBackButton { get; set; }
        ApplicationTheme AppTheme { get; set; }
        TimeSpan CacheMaxDuration { get; set; }
    }
}
```

Including this interface in a second library project you want to share makes sense to me. Including it in Template10Library does not. The settings properties an app would add/remove would be custom to the app. The helper, on the other hand, that could have an interface. Is that what you mean?

**Comment by JerryNixon** [comment]
I think this is what you mean so I have introduced ISettingsHelper into the library. I will not be updating Nuget for a few days though.
