### ISSUE TITLE
HamburgerMenu: VisualState"CheckedPointerOver" at "NavToggleButtonTemplate" not working

### ISSUE THREAD

**Issue by jp-weber** [Windows-XAML/Template10#1050]
I want implement the the actually Setting-app look from Win10 Redstone, but if I change at "DataTemplate x:Name="NavToggleButtonTemplate":

```
<VisualState x:Name="CheckedPointerOver">
   <VisualState.Setters>
           <Setter Target="ContentPresenter.Foreground" Value="{Binding NavButtonCheckedForeground, ElementName=ThisPage}" />
           <Setter Target="ContentPresenter.Background" Value="{Binding NavButtonCheckedBackground, ElementName=ThisPage}" />
           <Setter Target="Indicator.Visibility" Value="Visible" />
    </VisualState.Setters>
</VisualState>
```

For example the background to hover, the backround of  the checked HamburgerButtonInfo is always the color of NavButtonHoverBackground.

```
<VisualState x:Name="CheckedPointerOver">
   <VisualState.Setters>
           <Setter Target="ContentPresenter.Foreground" Value="{Binding NavButtonCheckedForeground, ElementName=ThisPage}" />
           <Setter Target="ContentPresenter.Background" Value="{Binding NavButtonHoverBackground, ElementName=ThisPage}" />
           <Setter Target="Indicator.Visibility" Value="Visible" />
    </VisualState.Setters>
</VisualState>
```

This would be mean, that "CheckedPointerOver" is always active, when "Checked" is active?
![hovervisualstate](https://cloud.githubusercontent.com/assets/10946850/15984257/0cd5b766-2fc5-11e6-99ee-63980803511a.jpg)

![hovervisualstate2](https://cloud.githubusercontent.com/assets/10946850/15984369/9a92517e-2fc8-11e6-928b-44b9052d6fe9.jpg)

**Comment by dg2k** [comment]
I know you're trying to set the **ContentPresenter** Content control and **Indicator** Rectangle control in `Template10.Controls.HamburgerMenu` UserControl but the above won't do it and not the right approach anyway.

Your `<VisualState.Setters>` look for the `Target` control in the same XAML file which I understand is your Settings.xaml (be it from a Sample project). What info is there for the visual setter to look outside of your XAML and go for `Template10.Controls.HamburgerMenu.UserControl` ?

You cannot directly set **HamburgerMenu** styles with visual setters; that's what `\Styles\Custom.xaml` is for.
- Look into how you can influence the **HamburgerMenu** look by tweaking the styles under different Themes in your `Custom.xaml`.
- The samples show how `\Styles\Custom.xaml` and `Shell.xaml` are all linked up with your `App.xaml`.
- **Treat all sample code as your own code**. Why I'm saying this is, just in case there is a wrong assumption of sample code having a special means or privilege for accessing HamburgerMenu UserContro code (which they don't).

**Comment by jp-weber** [comment]
Thanks for your answer. 

I have tried to change the setter of "NavToggleButtonTemplate", because it was not possible to me in `\Styles\Custom.xaml` to change the background of  "ContentPresenter" if I hover over the checked NavButtonItem.

I have no idea how I can change the background of the item, if I hover, when the VisualState is

```
<VisualState x:Name="CheckedPointerOver">
   <VisualState.Setters>
           <Setter Target="ContentPresenter.Foreground" Value="{Binding NavButtonCheckedForeground, ElementName=ThisPage}" />
           <Setter Target="ContentPresenter.Background" Value="{Binding NavButtonCheckedBackground, ElementName=ThisPage}" />
           <Setter Target="Indicator.Visibility" Value="Visible" />
    </VisualState.Setters>
</VisualState>
```

**Comment by dg2k** [comment]
Have you looked at the [Dynamic Themes](https://github.com/Windows-XAML/Template10/tree/master/Samples/DynamicThemes) sample project? I think you'll find the right pointers there. I know the **Indicator** bar needs some updating for **hover** (currently works for **checked**) but with the custom background color settings etc you'd be 80-90% there.

**Comment by JerryNixon** [comment]
Thanks for looking into this @dg2k

**Comment by JerryNixon** [comment]
We don't support Redstone items yet. I'm sorry.
