### ISSUE TITLE
Forget CallMethodAction and think in terms of InvokeCommandAction?

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#1051]
With relative binding of the form `RelativeSource={RelativeSource FindAncestor ...` missing from UWP, the scope of getting to a _MethodName_ for `CallMethodAction` is very limited to a container such as a  UserControl. In this case you'd bind to the `ElementName` of a container, say UserControl's `x:Name` (see the **Search (and Login)** Sample for an illustration).

If on the otherhand your `CallMethodAction` is in more than one level of container, `CallMethodAction` is useless because there is no binding up an _Ancestoral tree_ as you would in WPF. Lately I wanted to implement a _SearchBox_ with **HamburgerMenu**'s _Literal_ button type in conjunction with **KeyBehavior** to intercept the `Enter key` to execute search as for submit button.

If you want to do the above, the `CallMethodAction` finds itself in the **HamburgerButtonInfo** control, which is in the **HamburgerMenu** UserControl, and which is in your **Views.Shell** Page. And, you'd want your `CallMethodAction`'s method to get to your Views.Shell's codebehind, which to my knowldege is impossible, because you cannot go out beyond the the **Template10.Controls.HamburgerMenu** UserControl to locate the method to execute.

Fortunately **InvokeCommandAction** to the rescue, and it doesn't care about the _Ancestoral tree_ binding that `CallMethodAction` compels you to think about to get to a method. 
#### The CallMethodAction Way:

```
<Core:CallMethodAction MethodName="SearchMethod" TargetObject="{Binding ElementName=UserControlPageName}" />
```
#### The InvokeCommandAction Way:

```
<Core:InvokeCommandAction Command="{x:Bind SearchCommand}" />
```

For `InvokeCommandAction`, you bind to a `DelegateCommand` (as `SearchCommand` in above example) to a view-codebehind page or a view-model page (which btw is a more logical thought process). Your `DelegateCommand` constructor links up with the desired method (the `SearchMethod` under `CallMethodAction` we started with). The only advantage of `CallMethodAction` is the direct link up with a method (without indirect route via `DelegateCommand`)  BUT that only happens in a very limited use case.

Forget all about `CallMethodAction` ?

**Comment by JerryNixon** [comment]
`CallMethodAction` is nothing but a pain in my neck. I have half a mind to write my own and put it in Template 10 just to solve this endless nightmare when I try to use it.
