### ISSUE TITLE
Buil for store issue - Shell does not contain a definition for 'HamburgerButtonInfo_Selected

### ISSUE THREAD

**Issue by realworld666** [Windows-XAML/Template10#1055]
Any ideas why I'm getting this error when building for store. It builds fine otherwise. 

1>C:\Users\davec\Source\Repos\CycleStreetsUniversal\CycleStreetsUniversal\obj\Pages\Shell.xaml(35,98,35,126): error CS1061: 'Shell' does not contain a definition for 'HamburgerButtonInfo_Selected' and no extension method 'HamburgerButtonInfo_Selected' accepting a first argument of type 'Shell' could be found (are you missing a using directive or an assembly reference?)

The xaml is as follows

<t10:HamburgerButtonInfo PageParameter="Map" ClearHistory="True" Tapped="HamburgerButtonInfo_Tapped">

**Comment by genehynson** [comment]
XAML please?

**Comment by mvermef** [comment]
You need to 4 spaces or tilda front and back for inline code to show us the code,  otherwise it gets scrubbed from output

**Comment by realworld666** [comment]
Going to close this. The problem has gone away all by itself. I think it was probably a completely clear build that fixed it but I'm not sure.
