### ISSUE TITLE
How to create nested menu with Template 10

### ISSUE THREAD

**Issue by kanji11** [Windows-XAML/Template10#1057]
I want to use the Hamburger menu from Template 10 and add dynamic sections,

for example

--Mail section (header)

------Inbox

------Sent Items

--Calendar (header)

-----etc..list of headers, for each item, there is a list of clickable items.

Is there a way to bind the primary buttons and add a template for the items?
something like that

For more information check : http://stackoverflow.com/questions/36545559/nested-menu-with-template-10

**Comment by JerryNixon** [comment]
Yes, this is easily possible. It will take a bit for me to write a sample as I am traveling.

**Comment by kanji11** [comment]
Can you please write a sample code for me.Thanks

**Comment by JerryNixon** [comment]
Done. Look @ the MasterDetail sample
