### ISSUE TITLE
NetworkAvailableService

### ISSUE THREAD

**Issue by aline-almeida** [Windows-XAML/Template10#1061]
Hi!
I'm using T10 Nuget package v 1.1.11 and want to use NetworkAvailableService, but it's not available. Is it going to be included?
Anyway, I'd like to set the Action<bool> AvailabilityChanged in NetworkAvailableHelper, but it's not exposed in NetworkAvailableService.
Am I missing something here ?
Thanks,
Aline

**Comment by dg2k** [comment]
I think [Windows.Networking.Connectivity](https://msdn.microsoft.com/library/windows/apps/br207308) namespace should give you everything you need.

**Comment by aline-almeida** [comment]
Hi dg2k!
I know how to get it working, I was just wondering, since the code is available, if it could be reused as it is right now.
Thanks

**Comment by mvermef** [comment]
You would need to grab source for T10.Services, that code isn't part of the nuget package at present.

**Comment by aline-almeida** [comment]
I think the action AvailabilityChanged  from NetworkAvailableHelper should be exposed in NetworkAvailableService to be able to run code when availability changes. Is that right ?

**Comment by mvermef** [comment]
It is available just not in the nuget package..

**Comment by aline-almeida** [comment]
Maybe I didn´t explain myself well....
I've got the code and I know how to change it to make it do what I want (it's already done). I was just wondering if I really need to change the code or is there another way to use it "as is" and still accomplish my goal.
Thanks

**Comment by mvermef** [comment]
You can use it as is

**Comment by aline-almeida** [comment]
Ok, so could you tell me how to set the action to be run when availability changes, using just the INetworkAvailableService interface as is?

**Comment by angusbreno** [comment]
Yes @aline-almeida, today the services project it's not published within nuget package. Yes, it's missing the Event way to handle in service (since the it's supposed to not access Helpers directly)...

For now, we have two options: Make a PR with this service in services folder, or create in our app by ourselves.

I think Jerry already mapped this to a different package but no one knows when he will be able to do this:
https://github.com/Windows-XAML/Template10/issues/678

**Comment by aline-almeida** [comment]
Thank you @angusbreno, I was just checking before making a PR.

**Comment by JerryNixon** [comment]
I would like to see that PR @aline-almeida

**Comment by aline-almeida** [comment]
Done!
