### ISSUE TITLE
XAML file encoding

### ISSUE THREAD

**Issue by LukasNespor** [Windows-XAML/Template10#1064]
All XAML files are ANSI encoded so Czech characters like `ý, á, ě, š` are rendered as wrong character. Every time I create an app from Template 10 template I have to re-save all XAML files to Unicode encoding.

![wrongchar](https://cloud.githubusercontent.com/assets/12233643/16149850/bfb460f8-3493-11e6-8f50-a28eb7ce76e9.PNG)

**Comment by nksato** [comment]
All XAML files in Project Templates (1 Template10Blank.zip, 2 Tempalte10Minimal.zip, 3 Template10Humberger.zip) are ANSI encoded. I use Japanese characters and  got garbage characters using project template. Please re-save all files as Unicode encoding and update "Template 10 Template Pack" ( https://visualstudiogallery.msdn.microsoft.com/60bb885a-44e9-4cbf-a380-270803b3f6e5 ).

**Comment by JerryNixon** [comment]
Look at this
https://github.com/Windows-XAML/Template10/wiki/Document-Encoding
