### ISSUE TITLE
Passing an object to the MainPage from a Page that was accessed through the HamburgerButtonInfo Primary Button

### ISSUE THREAD

**Issue by paulaenterpriseappsuk** [Windows-XAML/Template10#1066]
Hi, how do i pass object from a Page accessed through the HamburgerButtonInfo to the MainPage.
NavigationService.Navigate Doesn't work. it gives Nullreference

**Comment by genehynson** [comment]
I think you're looking for PageParameter? You should be able to bind this attribute to a HamburgerMenu ViewModel and then at your new page, retrieve that parameter in the OnNavigatedTo() method in the respective ViewModel. It's talked about more here: https://github.com/Windows-XAML/Template10/wiki/Docs-%7C-Controls#hamburgermenu

**Comment by JerryNixon** [comment]
Here you go
https://github.com/Windows-XAML/Template10/wiki/Page-Parameters
