### ISSUE TITLE
MasterDetail Sample using another Back button

### ISSUE THREAD

**Issue by ghost** [Windows-XAML/Template10#1068]
I am using the MasterDetail as a guide on how to make that kind of design using Template10. There is just one problem, the sample uses another back button to transition from detail to master and vice versa. Is there a way you can use the built in shell back button? Thank you!

**Comment by mvermef** [comment]
If you look very closely there is no navigation happening.  So answer is no, no way to trigger back to list with built-in button because it is all accomplished with visual states
