### ISSUE TITLE
NavigationService.GoBack() does not have overload to accept NavigationTransitionInfo

### ISSUE THREAD

**Issue by ghost** [Windows-XAML/Template10#1074]
NavigationService.GoBack() does not have overload to accept NavigationTransitionInfo. Is this by design or is it in the pipeline of features? If it is by design, can you explain why you made it this way? And what kind of workaround to do to get the same effect? Thank you!

**Comment by JerryNixon** [comment]
This is an oversight. I look forward to your Pull Request @Rivolvan :) No kidding.

**Comment by JerryNixon** [comment]
I am starting to think this is not an oversight. I am starting to think GoBack() can't support Info.

**Comment by ghost** [comment]
I feel stupid. How do I do a pull request? I am new to this.

**Comment by ghost** [comment]
this is my pull request @JerryNixon  #1085
