### ISSUE TITLE
BottomAppBar is in front of Busy page

### ISSUE THREAD

**Issue by marcinmarkiewicz** [Windows-XAML/Template10#1076]
As in the title... My app has BottomAppbar and I want to do some calculations. When using Busy page from T10 approach (DelegateCommand), I found that BottomAppBar is on the top of my app (busy page is behind app bar)- is it bug?

**Comment by JerryNixon** [comment]
Not a bug. Nothing can be in front of the Bottom/Top app bars. The only work around is to disable them when you show Busy. Or dock the AppBar and don't use Bottom/Top. 

Not saying it's awesome. Just explaining why it's nothing we can fix.

**Comment by JerryNixon** [comment]
Leave a comment

**Comment by marcinmarkiewicz** [comment]
thanx for reply
