### ISSUE TITLE
Template App.Xaml and RequestedTheme

### ISSUE THREAD

**Issue by GFlisch** [Windows-XAML/Template10#1077]
The template with HamburgerMenu generates a App.Xaml file where the Theme is set to Light.

Changing the theme in the settings menu will have no influence when you restart the application due to the Light version set in the xaml file.
Just remove this and all works fine.

**Comment by JerryNixon** [comment]
Good catch. True for all but Blank template.

Hey, why not submit a Pull Request?

**Comment by GFlisch** [comment]
Already fixed in the current branch.
