### ISSUE TITLE
GoToStateAction does not execute when used within BackButtonBehavior

### ISSUE THREAD

**Issue by ghost** [Windows-XAML/Template10#1078]
The BackButtonBehavior executes InvokeCommandAction and other Actions but it won't execute the GoToStateAction. I've checked the code and I set the TargetObject of the GoToStateAction to the Page but still nothing.

`<Behaviors:BackButtonBehavior>
<Core:GoToStateAction StateName="ListVisualState" TargetObject="{Binding ElementName=pageRoot}" />
</Behaviors:BackButtonBehavior>`

**Comment by ghost** [comment]
I noticed that the BackRequested eventhandler of BackButtonBehavior is
`private void BootStrapper_BackRequested(object sender, HandledEventArgs e) 
         { 
             e.Handled = Handled; 
             Interaction.ExecuteActions(sender, Actions, null); 
         } 
`

when `GoToState`is used within a `BackButtonBehavior`, the `TargetObject`that is passed to it is not the object where the `BackButtonBehavior`is attached to but the current `BootStrapper`.
Thus, when examining the GoToState behavior in the XAML behaviors codebase, when the passed object has no attached `VisualStateManager`, it will try to find the nearest parent with a `VisualStateManager` attached to it. But since the BackButtonBehavior is passing a `BootStrapper` object, the `GoToState` will never find a `VisualStateManager`that it can use.

Is my analysis correct @JerryNixon ?

**Comment by JerryNixon** [comment]
Good work solving this for me.
