### ISSUE TITLE
Can not write tests against a project referencing Template10

### ISSUE THREAD

**Issue by msarchet** [Windows-XAML/Template10#1079]
Here are steps to reproduce this issue:

Using the Template10 Project templates, File -> New Project -> Template 10 (Hamburger)

Add a UserControl called Test with a dependency property called Text.

Create a UWP Unit Test Project, add a UITestMethod, that creates a new Test UserControl, that attempts to set the Text property on the control.

Notice that if you attempt to debug or run this test that an exception occurs.

https://gist.github.com/msarchet/a5b39be02337b5e7b517bbe5dd26be9d

That gist contains the code for the aforementioned files.

It appears that this issue occurs when trying to call SetValue on a DependencyProperty.

This problem does not happen when using this same code against a UWP Project, and a UWP Test Project that do not reference Template10.

I can create a repository that has all of the code necessary to show the working and non-working examples of this if necessary.

**Comment by mvermef** [comment]
https://github.com/PrismLibrary/Prism/issues/140, reference jerry's remark near bottom. In other words you can't do ui tests at present. It is not a template10 isolated issue

**Comment by mvermef** [comment]
In other words you can't do ui tests at present.

**Comment by msarchet** [comment]
@mvermef I am able to write tests against a UWP app, that does not reference template 10. I addressed this in my initial comment.

**Comment by mvermef** [comment]
Containing ui?

**Comment by msarchet** [comment]
Yes. I can test a UserControl/View with a dependency property in a a new UWP Application, a Class Library (Universal Windows). If anything in the test project references template10 I am no longer able to run the exact same unit tests (in debug, or not in debug).

**Comment by msarchet** [comment]
https://github.com/msarchet/template10-unittest-repo

This repository should show the issue.

**Comment by JerryNixon** [comment]
Well, I just asked the UWP PM and he said they should work now. The lead for coded UI testing is not in today, so I will ask him tomorrow to validate - might even point him to this thread.

This article confirms that Coded UI Testing for Windows Store is supported.
https://msdn.microsoft.com/en-us/library/dn305948.aspx
 This article infers that Coded UI Testing for UWP is still forthcoming.
https://blogs.msdn.microsoft.com/visualstudioalm/2016/03/10/visual-studio-team-services-testing-tools-roadmap/

**Comment by msarchet** [comment]
Thanks @JerryNixon

Let me know if you need any thing additional to figure this out.

**Comment by JerryNixon** [comment]
You should know, this is very low priority right now. There are many other aspects and features of Template 10 that have my attention. Should you find out what the issue is, let me know ASAP with a new, open issue.
