### ISSUE TITLE
Provide debug symbols

### ISSUE THREAD

**Issue by stefankueng** [Windows-XAML/Template10#1081]
Please provide the debug symbols (pdb files) with each release on NuGet. And the debug symbols should contain the source info so VS can automatically fetch the source files from the repository if needed.
http://docs.nuget.org/Create/Creating-and-Publishing-a-Symbol-Package

Or if they're already published somewhere (haven't found them), then the url should be mentioned somewhere in a wiki page.

**Comment by JerryNixon** [comment]
I agree this would be a good idea. I would like to see it. 

We need to update https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Nuget/Build.cmd. 

I look forward to your Pull Request. Otherwise, no.
Sorry, man, just a matter of daylight.
