### ISSUE TITLE
ChangeTypeConverter issue

### ISSUE THREAD

**Issue by dubstylee** [Windows-XAML/Template10#1083]
I have a simple converter that I use to bind SQLite dates to a `DatePicker` control. I have to convert between `DateTime` and `DateTimeOffset`. I thought that this was the exact reason for a `ChangeTypeConverter`, so I decided to try it instead of my converter.

I declare it like this in my XAML:

```
<converters:ChangeTypeConverter x:Key="DateTimeToDateTimeOffsetConverter" />
```

And then bind my `DatePicker` like so:

```
        <DatePicker Grid.Row="4"
                    Grid.Column="1"
                    Date="{Binding CurrentPayee.DateOpened,
                                   Converter={StaticResource DateTimeToDateTimeOffsetConverter},
                                   Mode=TwoWay}" />
```

If the `DateOpened` is `null` then the `DatePicker` will use the default (today) value. If I try using the `ChangeTypeConverter` when `DateOpened` is not `null` then I get an error about invalid cast from `System.DateTime` to `System.DateTimeOffset`.

I have a converter which works, so it is not a big deal, but I just wanted to clarify, as I thought that the `ChangeTypeConverter` was supposed to be used in situations like this where you just need to change the data type.

**Comment by JerryNixon** [comment]
Does it have to be nullable?

**Comment by JerryNixon** [comment]
There's an example for this in the Converters Sample.

**Comment by dubstylee** [comment]
I suppose it does not have to be nullable. I can have it set the value on a new object to a default value rather than null and see if `DateTime` works better than `DateTime?`.

**Comment by dubstylee** [comment]
It still doesn't work with the `ChangeTypeConverter`, but I didn't realize there is a `DateTimeOffsetConverter` built in to T10. Pretty similar to what I already had, works like a charm!
