### ISSUE TITLE
UniversalWindowsPlatform 5.2, don't use yet..

### ISSUE THREAD

**Issue by mvermef** [Windows-XAML/Template10#1089]
It got pulled from Nuget... It is part of the 1.4 update for UWP

**Comment by Opiumtm** [comment]
Referring to [Nuget specification](https://docs.nuget.org/create/versioning) dependencies in nuget package are of type "this version or newer"

In [nuspec file](https://github.com/Windows-XAML/Template10/blob/542c9af1b29747cedde4f9582ac18bbdfbebdb70/Template10%20%28Library%29/Nuget/Template10Library.nuspec):

``` xml
    <dependencies>
      <dependency id="Microsoft.NETCore.UniversalWindowsPlatform" version="5.1.0" />
      <dependency id="Microsoft.Xaml.Behaviors.Uwp.Managed" version="1.1.0" />
      <dependency id="Newtonsoft.Json" version="8.0.3" />
    </dependencies>
```

As implied in Nuget specification, such a form (without any qualifiers) allow to use dependencies of newer version

> 1.0  = 1.0 ≤ x

**Comment by mvermef** [comment]
not what I was alluding to, more of a hey don't use it or post PR with this update yet... since it was unlisted from nuget for an issue.  Certain other packages use it as a requirement (EF Core e.g.).

https://social.msdn.microsoft.com/Forums/en-US/e766a904-7346-4f76-bad2-852d3b301b0e/known-issue-version-52-of-microsoftnetcoreuniversalwindowsplatform-delisted-all?forum=Win10SDKToolsIssues

**Comment by JerryNixon** [comment]
@mvermef Perhaps a PR would be good. Are you planning one?

**Comment by mvermef** [comment]
Not until corefx team give thumbs up for relisting with updated package
