### ISSUE TITLE
Error while opening the zip'ed project T10Minimal

### ISSUE THREAD

**Issue by Moskus** [Windows-XAML/Template10#109]
![error](https://cloud.githubusercontent.com/assets/320826/9953117/0e9b97aa-5dde-11e5-999a-6be7aa56e58c.png)

**Comment by Moskus** [comment]
I removed these lines from the .csproj file:
    $if$($includeKeyFile$==true)
    <PackageCertificateKeyFile>$projectname$_TemporaryKey.pfx</PackageCertificateKeyFile>
    $endif$
... the project tried to load.

I then got a new error, that 
![error2](https://cloud.githubusercontent.com/assets/320826/9954814/55dc80ee-5dec-11e5-8a23-1eb9e950bfa2.png)

fixing this by changing these lines:
    < TargetPlatformVersion>$targetplatformversion$< /TargetPlatformVersion>
    < TargetPlatformMinVersion>$targetplatformminversion$< /TargetPlatformMinVersion>
to
    < TargetPlatformVersion>10.0.10240.0< /TargetPlatformVersion>
    < TargetPlatformMinVersion>10.0.10240.0< /TargetPlatformMinVersion>
... it finally loads.

I then see 505 errors regarding the string "$safeprojectname$".

.... I get the feeling there is something I should know about these variables. ;)
But what?

**Comment by JerryNixon** [comment]
This will not be relevant once we release the templates (maybe tomorrow)

**Comment by Moskus** [comment]
Fantastic! :)
