### ISSUE TITLE
Get Extended Splashscreen With Circular ProgressBar Around Image in Template 10

### ISSUE THREAD

**Issue by ghost** [Windows-XAML/Template10#1090]
This  question is on SO [Link](http://stackoverflow.com/questions/38018918/get-extended-splashscreen-with-circular-progressbar-around-image).But the answer given is not the complete solution. As my app hangs by that solution so I just used the extendedsplash control in a blank windows uwp app and voila! it worked perfectly but when using template 10 after the splashscreen the app just hangs for 1 min(especially when using hamburger template).So I guess there is some issue with template 10 for this case but I cannot figure out the workaround of this issue. Any help would be appreciated a lot.
And @JerryNixon  or @darenm can you please provide your app sample like the course in mva that would solve this problem completely and would be a helpful to a lot.
Thanks for this awesome template!

**Comment by JerryNixon** [comment]
This is so very simple. Check out https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Controls/RingSegment.cs and pay attention to the StartAngle and EndAngle properties. That's how we did it in the sample. Like 5 lines of code.

**Comment by ghost** [comment]
Thanks for the help @JerryNixon .I added  this in place of progresring  in splash.xaml  
 `<Controls:RingSegment x:Name="progressRing" Radius="300"  StartAngle="0" EndAngle="359"  Stroke="Red" StrokeThickness="10"> </Controls:RingSegment>
`
But still the app hangs after the splashscreen.Even read your article for pieslice(which was great btw) but couldn't get a workaround for this.Any suggestions for what I might be doing wrong?
Thanks in advance.

**Comment by ghost** [comment]
Leave it @JerryNixon  Finally got it done by the ringsegment control . Thanks a lot!
