### ISSUE TITLE
Error using NavigateToPageAction

### ISSUE THREAD

**Issue by marcominerva** [Windows-XAML/Template10#1093]
Hi all!

When I try to navigate to a page using NavigateToPageAction, I obtain the following error:

`Unexpected character encountered while parsing value: W. Path '', line 0, position 0.`

If I navigate to the same page via code, using NavigationService, everything works as expected. The error seems related to Json serialization.

**Comment by JerryNixon** [comment]
Is this the custom Action or the built-in Action. Do you know? 
Post your code and it will show me.

**Comment by marcominerva** [comment]
This is the complete scenario. If I use the Template10 NavToPageAction Behavior:

`<Page
    ...
    xmlns:Interactivity="using:Microsoft.Xaml.Interactivity"
    xmlns:Interactions="using:Microsoft.Xaml.Interactions.Core"    
    xmlns:t10behavoirs="using:Template10.Behaviors"
    ...>`

`<Interactivity:Interaction.Behaviors>
    <Interactions:EventTriggerBehavior EventName="Click">
        <t10behavoirs:NavToPageAction Frame="{x:Bind Frame}" Page="See4Me.Views.SettingsPage"/>
    </Interactions:EventTriggerBehavior>
</Interactivity:Interaction.Behaviors>`

I obtain the same error as reported in #1088.

On the other hand, If a use the Microsoft Xaml Interactivity NavigationToPageAction behavior:

`<Interactivity:Interaction.Behaviors>
    <Interactions:EventTriggerBehavior EventName="Click">
        <Interactions:NavigateToPageAction TargetPage="See4Me.Views.SettingsPage"/>
    </Interactions:EventTriggerBehavior>
</Interactivity:Interaction.Behaviors>`

I get the following error:

`Unexpected character encountered while parsing value: W. Path '', line 0, position 0.`

**Comment by JerryNixon** [comment]
Yep. It was broken. 
Updated docs. https://github.com/Windows-XAML/Template10/wiki/Behaviors-and-Actions#navtopageaction
See sample: https://github.com/Windows-XAML/Template10/blob/master/Samples/MultiplePageHeaders/Views/MainPage.xaml#L83
