### ISSUE TITLE
How to get the content template of HamburgerMenu of Specified Version ?

### ISSUE THREAD

**Issue by lyling** [Windows-XAML/Template10#1096]
I need to change the layout and style of Hamburger Menu. 

How to get the content  template of Specified Version like 1.1.11 from nugget.? 

I have found an hamburgermenu.xaml from "obj" folder, but it can`t contain the "Temaplate" section cause it is an usercontrol.

**Comment by JerryNixon** [comment]
Correct, you cannot retemplate the HamMenu, though you can template the Content and the individual buttons.
