### ISSUE TITLE
HamburgerMenu for only certain pages?

### ISSUE THREAD

**Issue by dubstylee** [Windows-XAML/Template10#1097]
I am working on alternate views for mobile, and rather than having my buttons in the `PageHeader`, I want to implement a `HamburgerMenu` instead. Is it possible to have the `HamburgerMenu` only apply to views in my `DeviceFamily-Mobile` folder?

I guess maybe it would be possible to just have a separate `App.xaml` in that folder? I hadn't thought to try that yet. Has anyone tried using a `HamburgerMenu` that only applies to certain `DeviceFamily`?

**Comment by JerryNixon** [comment]
Sure. Every button has a Visibility property you can set in your visual-state.
