### ISSUE TITLE
Add new T10 Page and ViewModel templates

### ISSUE THREAD

**Issue by MagooChris** [Windows-XAML/Template10#1098]
I don't know if this is even possible for thrid party extensions to do, but it would be really cool if there was a way to add a T10 Page and ViewModel from the Add menu. Kind of like you do when using MVC, you can just right click and say you are adding in a View or Controller.

If that isn't possible, how about just templates from the Add new dialog?

**Comment by JerryNixon** [comment]
Definitely possible. We've thought about it. But what we have is already plenty to maintain. But right-click Add Page would be terrific. Adds Page/Code-Behind/and View-Model. 
1. Views/MyPage.xaml
2. Views/MyPage.xaml.cs
3. ViewModels/MyPageViewModel.cs

The biggest issue is that so many developers do it so differently that it's only going to be relevant to about 50% of the developers. Know what i mean?
