### ISSUE TITLE
DeviceDispositionBehavior issue with actions.

### ISSUE THREAD

**Issue by GFlisch** [Windows-XAML/Template10#1102]
Hi,

In the implementation of the DeviceDispositionBehavior, the attach method calls an Update() method.

```
public class DeviceDispositionBehavior : DependencyObject, IBehavior
{
    public DependencyObject AssociatedObject { get; set; }

    public void Attach(DependencyObject associatedObject)
    {
        AssociatedObject = associatedObject;
        Utils.DeviceUtils.Current().Changed += DeviceDispositionBehavior_Changed;
        Update();
    }
```

The problem is the Update method will call all the actions and the Page is still not loaded. So if you want to use the GotoStateAction for sample, it will not work.

As a solution I have tried to find the Page instance and wait the OnLoaded event to call the Update() method. But I have seen that trying to find a parent via the VisualTreeHelper class doesn't work because the VisualTree is probably not yet built. 

So I don't see how to solve this.

Gilles

**Comment by JerryNixon** [comment]
This is definitely a bug.
