### ISSUE TITLE
Exception while changing Theme

### ISSUE THREAD

**Issue by kanji11** [Windows-XAML/Template10#1105]
Hello,

Following exception occurred while changing theme

"An exception of type 'System.InvalidOperationException' occurred in Template10Library.dll but was not handled in user code
Additional information: Sequence contains no matching element"

Scenario :
Step 1 : Set Visibility=Collapsed of any HamburgerButtonInfo button
Step 2 : try to change theme.

I have also try it in sample project (Hamburger) same error occurred.

**Comment by dg2k** [comment]
You're right.
`if (children.Count == 0) return;` is needed to account for `Visibility=Collapsed` on `HamburgerButtonInfo`.
PR coming up.
