### ISSUE TITLE
Suggestion for extending the function of Literal Button

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#1106]
@JerryNixon - One useful enhancement to T10 is a submenu command implementation -- example --  an Inbox command for accessing related Inbox subcommands, etc. Some thought must have been given to this (or similar ideas) already as the **Literal Button**, so far not in the forefront of the T10 design,  looks a perfect fit for such hierarchical menu commands.

To explain this with a good example, consider the **Outlook Mail** app on Windows 10 Desktop. Tap on the **Folders** command in the left pane and you''ll see a nice flyout panel sliding to the right, revealing related **submenu commands**. This is one of the most beautiful UI I have come across wrt menus. If this feature is added to T10 -- hopefully with minimal effort -- I think it would be a superb enhancement.

Do you think this is feasible?

**Comment by JerryNixon** [comment]
Yes, it is feasible. You are not the first to ask. I will work on a demo.

**Comment by dg2k** [comment]
Great! Thanks for that.

**Comment by JerryNixon** [comment]
Okay, I have pushed the update to MasterDetail sample.

**Comment by JerryNixon** [comment]
This is the demo
![masterdetail](https://cloud.githubusercontent.com/assets/1749983/16787068/a332d834-4856-11e6-96ae-137c1cf68f07.gif)

**Comment by dg2k** [comment]
@JerryNixon -- Wow! Great enhancement based on readily-existing T10 features. Couldn't see the forest for the trees.
