### ISSUE TITLE
HamburgerGridWidth is not the same as the splitview pane

### ISSUE THREAD

**Issue by cmpute** [Windows-XAML/Template10#1110]
![capture](https://cloud.githubusercontent.com/assets/9154441/16731303/ea46f0a0-47a9-11e6-8a27-d2d4294c1a19.png)
as above, in Wide Visual State, the HamburgerGridWidth is not the same as the pane in Hamburger Control

**Comment by JerryNixon** [comment]
I can confirm that the Hamburger template is pixel-perfect. There's something in your app making it change. Not sure where I would guess. Try the template's custom.xaml and change PageHeader.Background to Red. See if it is still off. If so, hmm. We'll wait until we see it that way.

![image](https://cloud.githubusercontent.com/assets/1749983/16787650/0f42986c-485b-11e6-99df-61a99ddff98e.png)

**Comment by cmpute** [comment]
@JerryNixon if you just change HamburgerBackground to a red brush, others remain the origin from hamburger template, the problem still appear. Btw, I'm using a 125% system vision ratio, wondering if that affects.
![cap](https://cloud.githubusercontent.com/assets/9154441/16790968/c8990760-48ec-11e6-9e2b-7cc47c224e81.png)

**Comment by cmpute** [comment]
I've checked that in 100% ratio, the problem **remains**.
Also I turn PageHeader.Background to Red, it's pixel-perfect indeed. So I guess it's related to the hamburger Grid rather than the content Frame
and anyway thanks for helping
