### ISSUE TITLE
Passing parameter in the first NavigationService.Navigate call causes issue

### ISSUE THREAD

**Issue by SamuelLioult** [Windows-XAML/Template10#1111]
It seems that passing parameter in the first call of the Navigate method causes issue: the method is called a second time.
To reproduce issue, in a new Hamburger template project, add a parameter to the Navigate method (in App.xaml.cs in the OnStartAsync method).
Then place a break point in the OnNavigateTo method of the MainPageViewModel.

**Comment by JerryNixon** [comment]
"Causes an issue" come on, dude, you can do better than that. How am I supposed to find the problem with that kind of detail? Anyway, I did what you said; stepped in and didn't find a problem.

I think (actually, I know) this will help you: 
https://github.com/Windows-XAML/Template10/wiki/Page-Parameters

**Comment by SamuelLioult** [comment]
Sorry, I thought I was clear with this:

> the method is called a second time

But, I discover this morning that this appears only when I deploy on my device (Lumia 930) but not when I deploy app on my PC.

Here are all steps to reproduce my issue:
1 - Create a new Hamburger project
2 - Go to the MainPageViewModel and place a breakpoint in the OnNavigatedToAsync (I placed it on line 25)
3 - Run app
4 - Breakpoint is fire only one time and app starts
5 - Now, go to the App.xaml.cs file. In the method named OnStartAsync, replace this line:

`NavigationService.Navigate(typeof(Views.MainPage));`

by:

`NavigationService.Navigate(typeof(Views.MainPage), "some parameter");`

6 - Run your app again
7 - You arrive on your breakpoint, the paremeter value is "some parameter". so press F5 to conitnue
8 - You arrive on your breakpoint for the second time with a null parameter value.

I hope this is clearer for you and I'm sorry again for my first post.
