### ISSUE TITLE
Performance issue with ProfileService

### ISSUE THREAD

**Issue by Opiumtm** [Windows-XAML/Template10#1112]
Found new performance issue (this time reproducing even on x86 desktop!)
Noticeable scrolling freezes starting with this commit https://github.com/Windows-XAML/Template10/commit/ac0235227e82f58cf2705f91db22589dd09abf2d

I actually tested commits from stable nuget package release to latest commit and found exactly when and where new extreme UI freezes (noticeable even on x86 desktop) originated.

To reproduce issue you can navigate from main page to another page, then back to main page (using back button), then to another page again. When you scroll page **after** some navigations, you should notice very noticeable freezes. 

Performance degradation reproduced after some page navigations.

This weird behavior is starting **exactly** with this commit (https://github.com/Windows-XAML/Template10/commit/ac0235227e82f58cf2705f91db22589dd09abf2d)

**Comment by Opiumtm** [comment]
Honestly, I don't understand what is the root cause of this issue. Looking at the commit itself, I can not tell it does anything wrong. It merely add new class. Also, when I deleted this class from branch which is branched from latest commit it doesn't help. But when I compile code from previous commit, there is no extreme performance degradation after some page navigations. When I compile code from this commit and newer - there are dire freezes after some page navigations. Code seems to be broken on exactly this commit. But there is no sane reason. Looks like some overlooked fundamental problem like increased memory consumption and frequent garbage collections (I haven't profiled memory consumption so I can't tell), but this commit doesn't introduce anything which can cause increased memory consumption. It actually doesn't changed anything important. But I clearly and reliably reproduced broken app behavior exactly on this commit. To track this I compiled and tested my app with **every** commit from stable release and found when issue started to appear. It looks crazy and unreasonable. I'm very confused.

**Comment by Opiumtm** [comment]
Also, I noticed longer app startup time with this commit. Sometimes app crashed on standard splash screen (silently close after long wait for splash screen to disappear). Something is fundamentally wrong.

**Comment by Opiumtm** [comment]
@Windows-XAML/community can it be because I'm not updated Shell.xaml/Shell.xaml.cs in my app and otherwise use obsolete one from earlier "Hamburger" project template (from which I originally started my app)? I noticed some changes in Shell.xaml and Shell.xaml.cs in newer versions.

**Comment by angusbreno** [comment]
@Opiumtm I don't know even. this: https://github.com/Windows-XAML/Template10/issues/1044 Is killing me... I could not find the root cause....

**Comment by JerryNixon** [comment]
Leave a comment

**Comment by Opiumtm** [comment]
@JerryNixon ????
