### ISSUE TITLE
WACK - Test Fail for a new template 10 hamburger project

### ISSUE THREAD

**Issue by pradeepdogga** [Windows-XAML/Template10#1115]
I made a new template 10 hamburger project and tried to make a release package without selecting the optimize code box in the build properties. The attached screenshots contain the error . Can anyone help me get through issue ?I  have an app made on template 10 and i am having trouble uploading it to store, i am getting the same error as attached in screenshots. 
I cannot select optimize code because that's causing some of the features in my app to misbehave.

![screenshot 215](https://cloud.githubusercontent.com/assets/19299967/16804850/4f857e78-492b-11e6-8fca-3f95b73ce0d8.png)
![screenshot 214](https://cloud.githubusercontent.com/assets/19299967/16804856/557c7660-492b-11e6-8edd-65c0cec32655.png)

**Comment by dg2k** [comment]
The error is obvious -- AdDuplex ad in your app is causing the problem (API CoCreateInstance in api-ms-win-core-com-l1-1-0.dll) so look for an alternative to `CoCreateInstance` or check if an update is made to the CoCreateInstance API to remedy this problem.

The same problem is logged [here](https://connect.microsoft.com/VisualStudio/feedback/details/2116070/wack-failure-api-cocreateinstance-in-api-ms-win-core-com-l1-1-0-dll-is-not-supported-for-this-application-type) for your info.

**Comment by pradeepdogga** [comment]
Thanks for the reference , but i have no such reference in my app. Attaching a screenshot : 
![screenshot 217](https://cloud.githubusercontent.com/assets/19299967/16806333/b6bfd466-4931-11e6-835d-80cb9023a8b8.png)

**Comment by dg2k** [comment]
That's interesting! The **CoCreateInstance API** has nothing to do with T10 so all I can say is your code somehow refers to the API.
- What you show above doesn't tell the whole story. Expand **References** under your project and look for what are there.
- Just to be certain, clean your solution and make sure that there are no non-obvious remnants;
- Also uninstall unwanted NuGet packages: (1) Tools menu -> Extensions and Updates -> Installed (in left pane) and (2) Right-click on project References -> Select **Manage NuGet Packages ...**  -> Tap on the **Installed** link.

**Comment by pradeepdogga** [comment]
Actually i created a new project and just built it without checking the optimize code option in the build properties. It has zero additional code. Absolutely empty template 10 hamburger project . You can try it by doing the same . (Release configuration and dont select optimize code , make a release package. You can see the same error.)

**Comment by dg2k** [comment]
This is all news to me and never came across this problem.
Are you using the (i) GitHub source code , (ii) NuGet package of T10, or (iii) VS Extension of T10?

**Comment by pradeepdogga** [comment]
VS extension of T10

**Comment by dg2k** [comment]
I've run the WACK with VS extension of T10 (HamburgerMenu template) and got **Passed**. 
I honestly can't guess the source of your problem.

> (Release configuration and dont select optimize code , make a release package. You can see the same error.)

I did for both optimized and non-optimized code and on both occasions it was **Passed**.

**Comment by pradeepdogga** [comment]
I am not able to understand why it is failing in my case. It is just an empty template 10 project , i did'nt add any code. But it is failing in no optimization case. I've to figure out something. Thanks for your concern !

**Comment by JerryNixon** [comment]
Out of scope
