### ISSUE TITLE
Cannot find a Resource with the Name/Key FalseWhenTrueConverter

### ISSUE THREAD

**Issue by janabimustafa** [Windows-XAML/Template10#1122]
Steps to reproduce:
1. Clone repo (master) and open sln in VS
2. Select Hamburger as startup project
3. Run and Deploy Hamburger project
4. Navigate to the settings page

**Comment by dg2k** [comment]
You're right. The `ValueWhenConverter` converter resource with key `FalseWhenTrueConverter` is somehow missing. It used to be in `App.xaml` and must have been inadvertently removed. I put it back in `SettingsPage.xaml` since `SettingsPage` is the only one using this converter. See PR #1124.

**Comment by JerryNixon** [comment]
Good job @dg2k
