### ISSUE TITLE
ProgressRing IsActive should depend on Busy

### ISSUE THREAD

**Issue by janabimustafa** [Windows-XAML/Template10#113]
In the sample projects, I see IsActive is always set to true. This was a problem with 8.x, and according to MSDN:
'In an app compiled for Windows 8, when the ProgressRing is active, the progress animation continues even if its not visible on the screen, such as when it's Visibility is Collapsed. This can keep the UI thread awake, use resources, and impair app performance. When the ProgressRing is not visible, you should disable the animation by setting IsActive to false.'

I am not sure if this still applies for UWP but I can do some tests to find out.

**Comment by JerryNixon** [comment]
Fixed on Monday
