### ISSUE TITLE
Xcopy error when create and run UWP app with Template 10

### ISSUE THREAD

**Issue by WoSea** [Windows-XAML/Template10#1130]
I am having issues with template 10. I have installed Template 10. I then created a new project and choose Blank or Hamburger/Minimal. After that, I followed this [guide](https://github.com/Windows-XAML/Template10/wiki/Welcome-%7C-Blank-Template). But when I run my project, I get the following error:

> "xcopy "C:\Users\phams.nuget\packages\Template10\1.1.11\build\uap10.0....\lib\uap10.0" "C:\Users\phams\Desktop\WindowsApp1\WindowsApp1\obj\x86\Debug\" /e/s/y/q" exited with code 9009."
> (I use Visual Studio 2015 with update 3 on Windows 10)

**Comment by dg2k** [comment]
@WoSea  -- Right-click your project and tap on **Build Events** link to the left, and delete the Pre-build (or Post-build??) event command line.

**Comment by WoSea** [comment]
@dg2k It still do not work :(

**Comment by WoSea** [comment]
**issues solved** I have uninstalled the Template 10 and re-installed it, then F5 & cheers

> Visual studio 2015: 
> TOOLS -> Extensions and Updates... -> Installed, choose Template 10 Template Pack -> **Uninstall**. 
> TOOLS -> Extensions and Updates... ->Online, Ctrl+E & enter "Template 10 Template Pack" ->**Download**. **Restart** your VS and **Create** a project with Template 10. Join!
