### ISSUE TITLE
How to get the page type which NavigationService navigates to?

### ISSUE THREAD

**Issue by ghost** [Windows-XAML/Template10#1133]
From a page A I nagivate to page B. I have overrided OnNavigatedFromAsync() on page A and I'd like to know the page type I'm coming to. Is it possible to know it?

**Comment by dg2k** [comment]
@bbougot 
In view-model `this.NavigationService` is your friend.

In fact, you'd be spoilt for choice.

`var currentPageType = this.NavigationService.CurrentPageType;`

You can even have a peek in Back and Forward navigation -- have a look at `NavigationService.Frame.ForwardStack` and `NavigationService.Frame.BackStack`

Some random code below, just to _whet you appetite_ ;-)

```
string previousPageName = this.NavigationService.Frame.BackStack.FirstOrDefault()?.SourcePageType?.Name;
string forewardPageName = this.NavigationService.Frame.ForwardStack.FirstOrDefault()?.SourcePageType?.Name;
int backStackCount = this.NavigationService.Frame.BackStack.Count;
int foreStackCount = this.NavigationService.Frame.ForwardStack.Count;

var frame = this.NavigationService.Frame;
var thisPage = frame.Content.GetType();
if (frame.CanGoBack) frame.GoBack();
frame.BackStack.Remove(Frame.BackStack.Last()); 
```

**Comment by ghost** [comment]
Thanks for the sample!
However forewardPageName is null in OnNavigatedFromAsync().
I navigate using my Shell (hamburger control) and I have OnNavigatedFromAsync() defined in the page I Navigate from. I would like to know which page I navigate to.

**Comment by dg2k** [comment]
True this is the case if you haven't visited that page already.

Navigate A to B   => forward is null
Navigate back from B to A => now forward is not null at A (because it has the knowledge of B it has visited)

**Comment by ghost** [comment]
Hmm well, that makes sense! Thanks!
