### ISSUE TITLE
Question: Separate page instance per unique parameter

### ISSUE THREAD

**Issue by dannywils** [Windows-XAML/Template10#1136]
I'm trying to have multiple items in my hamburger menu that navigate to the same page type but with a different parameter. This works fine but the same page instance is used and page transitions don't fire when navigating between items of the same type. 

Is it possible to use a separate page instance per unique page parameter and have that cached independently?

**Comment by marcinmarkiewicz** [comment]
Did you try to set NavigationCacheMode to Windows.UI.Xaml.Navigation.NavigationCacheMode.Dissabled in page`s constructor?

**Comment by JerryNixon** [comment]
What do you mean the same page instance is used? When you navigate using the HamMenu a new instance is created every time unless you are using cache. Could you explain?
