### ISSUE TITLE
[Bug] - Exception when trying to change theme in wide view desktop mode

### ISSUE THREAD

**Issue by marcinmarkiewicz** [Windows-XAML/Template10#1137]
I noticed an exception when trying to change theme. This exception is present only when application is running on desktop and in "Wide view" when full HamburgerMenu is visible (icons with contents). When the menu is collapsed everything is fine. 
![ex](https://cloud.githubusercontent.com/assets/17554633/16979193/195d8860-4e60-11e6-943d-5aa4a5c98835.png)

**Comment by dg2k** [comment]
Can you be more specific as to the location of the above code? Project? Sample? 
My guess is it's a `...\.Services.SettingsServices.cs` file but which one and used with which project?

**Comment by marcinmarkiewicz** [comment]
Hi, it`s a hamburger template project and SettingsServices.cs. Exception is thrown only when whole HambrgerMenu is visible (wide visual state)

**Comment by dg2k** [comment]
@marcinmarkiewicz -- I cannot repro this error. Are you sure that this is the original code? My suspicion is that you may have changed something in the **Styles\Custom.xaml** file.

I checked with the latest unmodified  **Hamburger** project and in wide mode as you described and no problem. Compare with the original source code and see if any modifications by you contributed to this error. Double check the **Styles\Custom.xaml** file.

**Comment by marcinmarkiewicz** [comment]
I checked Cusom.xaml - it`s ok. I notticed that this problem exists when I have my own brushes defined in my HamburgerMenu - directly in Shell.xaml, not in Custom.xaml. It has a sense now. RefreshStyles method of SettingsService can not refresh brushes defined my way. Thanks @dg2k
