### ISSUE TITLE
Page resource is stoping view from loading

### ISSUE THREAD

**Issue by raifordb** [Windows-XAML/Template10#1139]
Why is this XAML preventing a page from loading.

   <Page.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="Styles\BigDictionary1.xaml"/>

In designer I get the following error
"Exception: An error occurred while finding the resource dictionary "Styles\BigDictionary1.xaml".

The path is correct.

**Comment by raifordb** [comment]
Sorry Forgot to include the code

```
<Page.Resources>
    <ResourceDictionary>      
        <ResourceDictionary.MergedDictionaries>
            <ResourceDictionary Source="Styles\Dictionary1.xaml"/>
```

**Comment by tibitoth** [comment]
And the BigDictionary's content is correct?

**Comment by dg2k** [comment]
But
`Styles\BigDictionary1.xaml` != `Styles\Dictionary1.xaml`
and perhaps more ...

**Comment by raifordb** [comment]
The error read

"Exception: An error occurred while finding the resource dictionary "Styles\Dictionary1.xaml".

**Comment by dg2k** [comment]
Not sure if it works as `Page.Resources` (never tried `ResourceDictionary` at page level). Check by putting it in `App.xaml`.

**Comment by jp-weber** [comment]
Have you tried to write "/" instead of "\":

```
 <ResourceDictionary Source="/Styles/Dictionary1.xaml"/> 
```

or:

```
<ResourceDictionary Source="ms-appx:///Styles/Dictionary1.xaml"/>
```

?

@dg2k 
It works, I use it since long time:

```
<Page.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary Source="/Styles/Templates.xaml"/>
```

**Comment by dg2k** [comment]
Oh! Is it the \ we overlooked then? Didn't notice that one.

**Comment by raifordb** [comment]
Found the answer!
ms-appx:///Styles/BigDictionary1.xaml

By default the page is looking for the resource in the views folder. If I specify the path as shown above it works.
