### ISSUE TITLE
Suspend and shutdown problem with state

### ISSUE THREAD

**Issue by JurajPupak** [Windows-XAML/Template10#1142]
I'm programming chat app and using your template10. Frist screen is login screen (username, server), second screen is login (password), and after I successfully login I navigate to Content page, which has some subpages, one of them is contact page. Contact page is in SubFrame of main frame - RootFrame-ContentPage->SubFrame-ContactPage. When I click suspend and shutdown in VS2015 and than I run the app again, I want to go back to login screen, but the NavigationService navigates to ContactPage and it crashes, because some objects are not initialized yet. I don't know why the NavigationService tries to navigate on ContactPage. It's kind of magic behind it.
Thank you for help.

**Comment by JerryNixon** [comment]
Is your sub frame associated to a navigation service through NvigationServiceFactory()?

**Comment by JurajPupak** [comment]
This is my code
`App.CurrentSubNavigationService = BootStrapper.Current.NavigationServiceFactory(BootStrapper.BackButton.Ignore,
BootStrapper.ExistingContent.Exclude, frame);
App.CurrentSubNavigationService.Navigate(pageType);`

App.CurrentSubNavigationService is my global variable in App.cs.

**Comment by JurajPupak** [comment]
Is it possible to not save the state automatically? Can I handle it myself? I don't need to save the state because for example: if the user is logged and is in contact list, he closes the app and after some minutes reopens the app, the app should show log in screen not navigate to contact list. Everytime the app is closed (not suspended), the navigation stack must not be saved - we don't need it in our app.

**Comment by JerryNixon** [comment]
Will open a new issue, add Save Load to Nav
