### ISSUE TITLE
Question - How best to use the Validation Library

### ISSUE THREAD

**Issue by Chris-Marassovich** [Windows-XAML/Template10#1145]
Hello,

I love t10!!.
I want to use that lovely Validation library and I am unsure how to use it?  i.e. get it into my project
How do I get that Validation library into my project?
Current project is a UWP app and t10 1.1.11 is installed.

I did see a NuGet package panteam.validation which appears to be the t10 Validation library yet it was missing the ModelBase?
I have tried to bring down the code of t10 and build the DLL for the validation lib and just reference that.  I can build the t10 stuff but when I ref the DLL I get build errors in my project.

I must be missing some simple step or concept here?

Your help and advice will be greatly appreciated.

Cheers
Chris ...

**Comment by mvermef** [comment]
The library works just has to be built with the Library and the Generate Library checkbox has to be checked to work correctly with the Library to prevent duplication with the packages.  I stopped using cause I didn't have time to optimize it for Native which was having some really bad issues when compiled native.  Key response, I don't believe it is an issue now but I haven't checked to make sure its working as expected now.  

Keep in mind that the nuget package doesn't have anything todo with validation yet.

**Comment by JerryNixon** [comment]
We will be adding Template10.Validation to NuGet soon.
