### ISSUE TITLE
Bind TextBox Text propery in AppBarButton.Template control template

### ISSUE THREAD

**Issue by tgiachi** [Windows-XAML/Template10#1146]
Hi I've strange error: 

Build failed is If I bind Value in TextBox with error:

**Xaml Internal Error error WMC9999: Object reference not set to an instance of an object.**

``` xml
 <AppBarButton.Template>
   <ControlTemplate>
      <TextBox x:Name="SearchEditBox" Text="{x:Bind ViewModel.Title}"  x:Uid="ricercaPerCodice" PlaceholderText="Codice"  Width="250" Height="32"  Margin="0,8,0,0" />
     </ControlTemplate>
   </AppBarButton.Template>
```

**Comment by tibitoth** [comment]
Why do you change the control template of the AppBarButton?

**Comment by tgiachi** [comment]
For put TextBox in PageHeader.PrimaryCommands, is wrong ?

**Comment by tibitoth** [comment]
Use PageHeader.Content property instead.

**Comment by tgiachi** [comment]
:+1:  Resolved!
