### ISSUE TITLE
Collapsed PageHeader -> exception on startup

### ISSUE THREAD

**Issue by sebfrie** [Windows-XAML/Template10#1155]
Using the current nuget package, the PageHeader example code breaks on startup:

`System.NullReferenceException: Object reference not set to an instance of an object.
   at Template10.Controls.PageHeader.UpdateSpacingToFitHamburgerMenu()
   at Template10.Controls.PageHeader.PageHeader_Loaded(Object sender, RoutedEventArgs e)`

([Link to code](https://github.com/Windows-XAML/Template10/blob/844673e386ca7af87b5c44ef69163bacbd1e31af/Template10%20%28Library%29/Controls/PageHeader.cs#L58))

After some investigation, I'm quite sure that this is due to the collapsed visibility property of one PageHeader element. Anyone experienced this before?

**Comment by AndrewAtAvenza** [comment]
I had this issue a few days ago and just hadn't gotten around to filing it. If the PageHeader has Visibility = Visibility.Collapsed, I definitely get an exception.

 I was trying to use the PageHeader control as a bar across the bottom, conditionally shown; this kind of nipped that idea in the bud :)

**Comment by sebfrie** [comment]
I realized that this problem was already tracked: #993

**Comment by JerryNixon** [comment]
Closing because duplicate. That being said, if you figure out what is wrong, please share.

**Comment by JerryNixon** [comment]
Nevermind, this is already fixed. I fixed it :) Just not published, yet. I forgot.
