### ISSUE TITLE
PageHeader HeaderBackground and HeaderForeground

### ISSUE THREAD

**Issue by tgiachi** [Windows-XAML/Template10#1158]
Hi!
In https://github.com/Windows-XAML/Template10/wiki/Docs-%7C-Controls#customization show how change PageHeader background but in latest nuGet version isn't avaiable. Why?

``` xml
<Page x:Class="Controls.MainPage"
      xmlns:controls="using:Template10.Controls">

    <controls:PageHeader Frame="{x:Bind Frame}" 
        Text="Main Page" 
        HeaderBackground="Orange" 
        HeaderForeground="Red" />
</Page>
```

**Comment by JerryNixon** [comment]
Please use these properties:

![image](https://cloud.githubusercontent.com/assets/1749983/17460364/5dbcdbfa-5c20-11e6-8e02-3510d2a49fc3.png)
