### ISSUE TITLE
ToastService builds toasts incorrectly

### ISSUE THREAD

**Issue by AndrewAtAvenza** [Windows-XAML/Template10#1159]
I know it's not actually in the current release, but I liked the idea of the ToastService so I downloaded the code and added it manually to my project.

I discovered it wasn't generating the toasts correctly; specifically, there's currently a typo in ToastHelper.AppendTextElementsToNotification(). The second & third if-statements both refer to elements[0] when they should refer to elements[1] & elements[2] respectively. After updating those lines, I get the properly titled toasts.

I'm going to play with the other options and if I find another other problems, I'll post about them too. Just like to see this in the official release

(BTW, Template10 is extremely useful, so thanks for all the hard work!)

**Comment by JerryNixon** [comment]
This service is no longer supported. Please use "NotificationsExtensions.Win10"

See the Tiles sample >> https://github.com/Windows-XAML/Template10/blob/master/Samples/Tiles/project.json
