### ISSUE TITLE
Package validation fails

### ISSUE THREAD

**Issue by youtoofan** [Windows-XAML/Template10#116]
When I run the package validation tool, I get the following error:

Debug configuration test

FAILED
    Debug configuration

```
Error Found: The debug configuration test detected the following errors:
    The binary Template10Library.dll is built in debug mode.
Impact if not fixed: Windows Store doesn’t allow a debug version of an app.
How to fix: Please make sure the app isn’t linking to any debug versions of a framework and it is built with release configuration with optimization enabled. If this is a managed app please make sure you have installed the correct version of .NET framework.
```

**Comment by callummoffat** [comment]
This will be fixed in next Nuget package. Reference solution manually to solve this.

**Comment by JerryNixon** [comment]
Next version is the fix.

**Comment by callummoffat** [comment]
When is this coming out?

_Callum Moffat_
App Developer
Windows 10 Enthusiast

---

Wanna (calculate a) date? Use Advanced Duration Calculator, a free app for
Windows 10!
https://www.microsoft.com/store/apps/9WZDNCRCSFL2?cid=mailsigcampaign
