### ISSUE TITLE
Can't use Connected animation service API

### ISSUE THREAD

**Issue by golkhandani** [Windows-XAML/Template10#1161]
For using ConnectedAnimationService I need to use frame.navigate in code behind
but it cause an error
how can i navigate to other page with Connected animation ?

Frame.Navigate(typeof(FoodDetailPage), _navigatedUri = item.Name); in code behid cause break in app.g.is

**Comment by mvermef** [comment]
```
NavigationService.Navigate(Type, parameter); not working?
```

**Comment by golkhandani** [comment]
Its must handle in Code behind and cant use ViewModelBase and NavigationService
i use this in code behind:
private void lblItemsListView_ItemClick(object sender, ItemClickEventArgs e)
        {
            var container = lblItemsListView.
                ContainerFromItem(e.ClickedItem) 
                as ListViewItem;

            if (container !=null)
            {
                var root = (FrameworkElement)container.ContentTemplateRoot;
                var text = (UIElement)root.FindName("Text");

                ConnectedAnimationService.GetForCurrentView().
                    PrepareToAnimate("Text",text);
            }

            var item = (MyClass)e.ClickedItem;
            Transitions = new TransitionCollection();
            Transitions.Add(new ContentThemeTransition());
            _navigatedUri = item.Name;
            
            if (MyEvent!=null)
            {
                MyEvent(item,EventArgs.Empty);
            }
        }
        public static event EventHandler MyEvent;
and in ViewModel :
public FoodPageViewModel()
        {
            Initialize();
            FoodPage.MyEvent += FoodPage_MyEvent;
        }

        private void FoodPage_MyEvent(object sender,EventArgs e)
        {
            
            NavigationService.Navigate(typeof(FoodDetailPage),sender.ToString());
        }
but I don't know how send item as navigation parameter

**Comment by mvermef** [comment]
>  private void FoodPage_MyEvent(object sender,EventArgs e)
>     {
> 
> ```
>     NavigationService.Navigate(typeof(FoodDetailPage),sender.ToString());
> }
> ```

Behaviors would be another solution to this to be able to pass the parameter, using the Interactions library that is already included in this template.  setup the behaviors to react to the click event sending the ListView SelectedItem property?  I don't believe your event is necessary at all and your overall code would maybe, be 15 lines, which would actually not touch the codebehind but the ViewModel only, since you are passing the Parameter information to the viewmodel using the behavior and the viewmodel knows of the click since the behavior wired it up.

**Comment by mvermef** [comment]
Just realized this is a RS1 item.  I don't think we have anything setup for that yet in Template10, its coming #soon, not that it should prevent you from using it.

**Comment by golkhandani** [comment]
actually it worked but in destination page I just write 
protected override void OnNavigatedTo(NavigationEventArgs e)
        {
            Text.Text = (string)e.Parameter;
            var animation = ConnectedAnimationService.
                GetForCurrentView().GetAnimation("Text");
            if (animation != null)
            {
                Text.Opacity = 1;
                animation.TryStart(Text);

            }
        }
problem is that parameter is an SerializedObject I think using ViewModel for destination page an use NavigateToAsync then bind text to a property can solve problem
I going to try this

**Comment by golkhandani** [comment]
this can used for navigate to destination page 

`public FoodPageViewModel vm =>DataContext as FoodPageViewModel;`
`vm.NavigationService.Navigate(typeof(FoodDetailPage), _navigatedUri);`

but in destination code can't  handle OnNavigateTo method 
in code behind I have this:

`protected override void OnNavigatedTo(NavigationEventArgs e)
        {
            Text.Opacity = 0;
            Text.Text = e.Parameter.ToString();
            var animation = ConnectedAnimationService.
                GetForCurrentView().GetAnimation("Text");
            if (animation != null)
            {
                Text.Opacity = 1;
                animation.TryStart(Text);
            }
        }
`

problem is  e. parameter and can't use ViewModel OnNavigateAsync because it call a view element
i try to set property in destination page ViewModel 

`string _MyProperty = default(string);
public string MyProperty { get { return _MyProperty; } set { Set(ref _MyProperty, value); } }
`

`public override async Task OnNavigatedToAsync(object parameter, NavigationMode mode, IDictionary<string, object> state)
        {
            MyProperty = parameter.ToString();
            await Task.CompletedTask;
        }
`

then bind to element to MyProperty but animation doesn't run

**Comment by JerryNixon** [comment]
From the page's code-behind, you can call this.Frame.GetNavigationService().Navigate(type), right? I am assuming this is not enough. As we are updating the Nav service, we want to enable Connected animations. Please keep explaining.

**Comment by golkhandani** [comment]
I have 2 pages > FoodPage and FoodDetailPage
navigate from FoodPage to FoodDetailPage is fine using 
`this.Frame.GetNavigationService().Navigate(type,parameter)
` 
Or

```
public FoodPageViewModel vm =>DataContext as FoodPageViewModel;
vm.NavigationService().Navigate (type,parameter) 
```

and in FoodDetailPage's code behind I must handle something like this >

```
protected override async void OnNavigatedTo(NavigationEventArgs e)
{
      Text.Opacity = 0;
      Text.Text ="Text";
      Image.Source = "ImageUri";
      var animation = ConnectedAnimationService.
      GetForCurrentView().GetAnimation("Text");
            if (animation != null){
                Image.Visibility = Visibility.Visible;
                Text.Opacity = 1;
                animation.TryStart(Text);}
}
```

I deserialize e >

```
var data = _SerializationService.Deserialize(e.Parameter?.ToString()) as MyData;
```

and it work fine.
Other Property that need to bind to an element set in FoodDetailPageViewModel OnNavigatedToAsync()

but something is broken and really don't know what is that 
you can see the gif files 
I think I can't use ConnectedAnimation in this version and must wait for next version

with template 10 >

![template10](https://cloud.githubusercontent.com/assets/19744568/17462400/a5d65420-5cc0-11e6-9bcb-320ffe94c706.gif)

and exact same code with out template 10 (NavigationService)
![test-exact same code with out template 10](https://cloud.githubusercontent.com/assets/19744568/17462387/5509f11e-5cc0-11e6-9b68-c798e333c86a.gif)

**Comment by JerryNixon** [comment]
One change in the future will no longer require deserialization in page.onnavto
