### ISSUE TITLE
NavButtonBehavior designer error

### ISSUE THREAD

**Issue by devingoble** [Windows-XAML/Template10#1163]
I'm getting the following error in the designer:
`Cannot create instance of type 'Template10.Behaviors.NavButtonBehavior' [Line: 0 Position: 0]`

This is in a fresh file > new project based on the Hamburger Template from the Template Pack add-in version 1.18. I updated to the 1.1.12 preview version of the Nuget package. It works fine on 1.1.11.

Despite the error, the app compiles and runs just fine.

**Comment by JerryNixon** [comment]
Irritating, I know. No idea. Glad it still runs. There's nothing special about your project? Is it Visual Studio 2015 Update 3 or is it Visual Studio 15 Preview?

**Comment by devingoble** [comment]
It's VS2015 Update 3. It's the base Template10 hamburger template. Then I've tried to update the Nuget packages. There's nothing else I've changed. I noticed similar errors in other issues here related to NavButtonBehavior and UWP Behaviors library being somewhat brittle, so I kind of wrote it off to something similar.

**Comment by sebfrie** [comment]
For me, it's VS 2015 Update 3, too. Same way of getting the error. This is reproducible.

**Comment by AuroraDysis** [comment]
+1 for same error

**Comment by pesquera69** [comment]
+1 (VS 2015 Community Update 3) The error is on designing time (xaml), then compiles and run Ok

**Comment by Boti97** [comment]
I'm having the same problem but my app doest even compile. It stops at the global::System.Diagnostics.Debugger.Break(); line. I'm using VS 2017.
