### ISSUE TITLE
Exception with Windows 10 Anniversary 14393

### ISSUE THREAD

**Issue by ghost** [Windows-XAML/Template10#1164]
An exception occurs when NavigationService navigates to a page.
The following exception is thrown: 
**There are no more endpoints available from the endpoint mapper.**

It comes from _pageState?.Clear();_ **line 167** of the NavigationService file (inside NavigateToAsync method).

It may not be related to Template10, but as far as I know... I don't know.

I used Template10 1.1.12-preview-160712

**Comment by JerryNixon** [comment]
The error is `There are no more endpoints available from the endpoint mapper`? Yikes, a new error in AU. Will take a little bit to research. Thanks for reporting it.

**Comment by ghost** [comment]
I can confirm this exception is coming everywhere in many .NET dependencies... Totally not related to Template10.

**Comment by JerryNixon** [comment]
Thank you @bbougot
