### ISSUE TITLE
NavAreaBackground isn't set success of HamburgerMenu controls ?

### ISSUE THREAD

**Issue by xiaoliwe** [Windows-XAML/Template10#1166]
I defined the property of hamburgerMenu in the custom.xaml ,but it has not entered into force after run it . as an alternative to it , directly it to Controls: HamburgerMenu node in the Shell.xaml  . wording it . 
Why isn't setting has no effect in Custom.xaml  ? 

Thanks a lot.

**Comment by cmpute** [comment]
Did you make a reference to the custom.xaml in Shell.xaml or App.xaml? ( Usually by adding ResourceDictionary to ResourceDictionary.MergedDictionaries)
