### ISSUE TITLE
Hamburger Project Template - RequestedTheme Setting is Overwritten on Start

### ISSUE THREAD

**Issue by helmut-steiner** [Windows-XAML/Template10#1167]
Hey there,
Just a minor thing: In the Hamburger project template the RequestedTheme is saved in the settings. It is loaded correctly in App.xaml.cs but is overwritten in App.xaml afterwards.

Solution:
Deleting `RequestedTheme="Light"` in the header of App.xaml solves this problem.

Thanks to all of you (especially Jerry) for your effort and time you put into Template10. It rocks!
Best wishes from Austria,
Helmut

**Comment by sebfrie** [comment]
+1 from a fellow Austrian ;)

**Comment by JerryNixon** [comment]
I look forward to your pull request.
