### ISSUE TITLE
where to initialize data

### ISSUE THREAD

**Issue by JurajPupak** [Windows-XAML/Template10#1168]
I would like to ask, where should I initialize the data or objects like dependency injection objects? In InitiliazeAsync, StartupAsync, or App() constructor? If the app is suspended and resumed, I don't need to initiliaze objects, because they are in memory. I only need it, when the app starts from "nothing"

**Comment by JerryNixon** [comment]
InitializeAsync is the appropriate place. I should add a sample. Good question.

**Comment by JerryNixon** [comment]
Perhaps you would like to submit a simple DI sample?
