### ISSUE TITLE
Can't display degree symbol

### ISSUE THREAD

**Issue by davefxy** [Windows-XAML/Template10#1169]
To recreate this problem : I create a new template 10 hamburger project. I insert the degree symbol '°' `into     <Setter Target="stateTextBox.Text" Value="° Wide Visual State" />.  I` am compiling a Debug x86 app.
The symbol is displayed correctly in the design view. However when I run the app the degree symbol appears as a ? in a triangle. Is there something I should be doing to get the degree symbol to appear correctly?
In my app I am using the symbol in a TextBlock in a ListView ItemTemplate and it appears as above.. If I put the symbol in a textblock outside the template the symbol appears correctly.

**Comment by mvermef** [comment]
Are you using font code? Or actual symbol?

**Comment by davefxy** [comment]
I am inserting the symbol in a textblock string in design mode.

**Comment by mvermef** [comment]
`<textblock Text="&#186;" />`  is the format you should try, you might need to force font type too depending how you are using it.
