### ISSUE TITLE
Non generic DelegateCommand (optional refinement)

### ISSUE THREAD

**Issue by ncarandini** [Windows-XAML/Template10#117]
When using a non generic DelegateCommand, the action is parameterless, so I'd prefer to call:
    HamburgerCommand.Execute();
instead of:
    HamburgerCommand.Execute(null);

This is easily achieved adding =null to the CanExecute and Execute object parameter, and it doesn't hurt with ICommand interface implementation:

public bool CanExecute(object p = null)
...
public void Execute(object p = null)
...

If you think it's a valid proposal, I can make the change and create a pull request.

**Comment by JerryNixon** [comment]
What?

Best regards,
Jerry Nixon

**Comment by ncarandini** [comment]
Hi Jerry, 
here it is:

```
public class DelegateCommand : System.Windows.Input.ICommand
{
...
    [DebuggerStepThrough]
    public bool CanExecute(object p = null)
    {
        try { return _canExecute(); }
        catch { return false; }
    }

    public void Execute(object p = null)
    {
        if (!CanExecute(p))
            return;
        try { _execute(); }
        catch { Debugger.Break(); }
    }
    ...
}
```

see the (object p = null) ?

this allow us to call the DelegateCommand Execute method without using a null parameter, i.e. :

```
HamburgerCommand.Execute();
```

instead of:

```
HamburgerCommand.Execute(null);
```

I know, is just a question of elegance, but in fact we're passing "null" because there is nothing to pass to the action.

This is valid only with non generic DelegateCommand, because when we have a generic command, i.e. :

```
var myCmd = new DelegateCommand<bool>(...);
```

then we surely do need to pass a boolean value to Execute and CanExecute methods, i.e. :

```
myCmd.Execute(aBooleanValue);
```

I just hope you don't think I'm only focused on silly things... :-)

**Comment by JerryNixon** [comment]
Now I get it. Submit a pull request.

Best regards,
Jerry Nixon

Sent from my Windows Phone.
Please forgive typos and brevity.

**Comment by ncarandini** [comment]
Thanks

**Comment by JerryNixon** [comment]
Two years later, I just used this!
