### ISSUE TITLE
App lifecycle and startup events

### ISSUE THREAD

**Issue by JurajPupak** [Windows-XAML/Template10#1170]
I just want to inform you about issue, but maybe it's a bug of VS. When you have backgroundtask with StreamSocketActivity and task is already registered in system, after re-running app from VS, the event OnStartAsync is fired with Running as PreviousExecutionState and event OnInitializeAsync is not fired. It's because backgroundtask is fired with case SocketClosed. This is scenario, when backgroundtask is in-process (Executable is set in Packagemanifest). 
If you run it normally, without VS, so previous state is Terminated/ClosedByUser or NotRunning. Maybe it's normal behaviour, when you run app from VS, who knows :)

EDIT:
I found next issue. The code below is not working if I simulate the state above. NavigationService is null. Anybody knows, why? App() constructor is called and then OnStartAsync() event. 
`NavigationService.Navigate(typeof(ReconnectPage), null, new SuppressNavigationTransitionInfo());`

**Comment by JerryNixon** [comment]
No class property can have a value in the constructor. It is too early. Just an OOP thing.

**Comment by JurajPupak** [comment]
I don't understand. When is NavigationService initialized? When constructor App() is called, it should be already initialized, no?

**Comment by callummoffat** [comment]
NavigationService is initialized by internal BootStrapper methods that are called between the constructor and OnStartAsync(), I believe.

If you want to navigate, do it in OnStartAsync(), not before.

**Comment by callummoffat** [comment]
The BootStrapper extends the default Application class. NavigationService is probably initialized in one of the internal methods which do most of the heavy-lifting. It definitely isn't initialized in the constructor. 

I suspect your initial problem is a platform issue of some kind (either with VS, or with UWP). I don't know for certain.

**Comment by JurajPupak** [comment]
I do it in OnStartAsync. But sometimes the object is null.
