### ISSUE TITLE
New version Microsoft.NETCore.UniversalWindowsPlatform

### ISSUE THREAD

**Issue by mklemarczyk** [Windows-XAML/Template10#1177]
Template10 need to be adjusted to new version of Microsoft.NETCore.UniversalWindowsPlatform (5.2.2).

**Comment by JerryNixon** [comment]
Okay. Could you help me understand why this is a requirement?

**Comment by mvermef** [comment]
For one it is required for Entity Framework Core to function (5.2.2 is the replacement for 5.2, which was missing a few things)..  I believe since T10 is based on 5.1 a down grade would show up in compilation, not sure if it would affect EFC..  Assuming one was to build entire project on 5.22

**Comment by tpspencer** [comment]
Any update on this?  I am starting...or trying to start using EFCore and having lots of issues.  I wonder if this upgrade will fix things?

**Comment by mvermef** [comment]
I would say fork copy and update yourself, it has been working fine for me

**Comment by JerryNixon** [comment]
I will add this to the 1.1.12 backlog now.
