### ISSUE TITLE
Serious issue with suspending and extended time!

### ISSUE THREAD

**Issue by JurajPupak** [Windows-XAML/Template10#1181]
Hi guys,
I found very serious issue in Template10. According Jerry's answer on github, extended execution session is requested every time, when app is going to suspend. But it's not requested! They forgot to call the method **RequestExtensionsAsync()** and they don't subscribe Revoke method, which is very important, mainlly if you await something in suspended method or do any asynchronnous operation, because after resuming in foreground, the app crashes. So you need to release async operation in Revoked event. 
I've already informed  Jerry about this problem via email.
For my purposes I edited the code in Template10.

Btw. you can't create your own ExtendedExecutionSession() object, if you use current version of template10. In doc is: 

> Template 10 cannot extend the 10 second limitation imposed by the platform, so the developer remains responsible to limit the suspend-time operation.

But you can't. Current version of Template10 will not allow you to create extended time.

**Comment by JurajPupak** [comment]
No reaction?

**Comment by JerryNixon** [comment]
It is important that we add a way to disable T10's native extension.

**Comment by JurajPupak** [comment]
How can I do that?

2016-09-10 1:25 GMT+02:00 Jerry Nixon notifications@github.com:

**Comment by JerryNixon** [comment]
You cannot do that until we add it as a feature.

**Comment by JurajPupak** [comment]
But in Bootstrapper class you request extended time. But you are not subscribed to Revoked event, and it is very important to be subscribed on it. (how you handle cases like Resumed or SystemPolicy)?
