### ISSUE TITLE
VisualStateNarrowMinWidth and VisualStateNormalMinWidth properties in PageHeader Control

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#1182]
@JerryNixon - Is there any use for **VisualStateNarrowMinWidth** and **VisualStateNormalMinWidth** properties in the **PageHeader** control? While there is an obvious need for these properties in the **HamburgerMenu** control, so far I see no use in PageHeader unless they are place-holders for something in the future. Any comments?

**Comment by JerryNixon** [comment]
Interesting. Isn't that what moves the PageHeader out of the way when the Hamburger Menu is compact?

**Comment by dg2k** [comment]
Sorry, my mistake! I did Symbol References hunting and nothing came up. I now can see that VisualStateNarrowMinWidth and VisualStateNormalMinWidth are actually used in Custom.xaml. (As an aside, I wish "Find All References" can also detect Symbols in xaml but that's a wish-list for future VS;-).
