### ISSUE TITLE
Template10 support for multiple/secondary views?

### ISSUE THREAD

**Issue by pcolmer** [Windows-XAML/Template10#1187]
I'm trying to understand:
- What support there is currently in Template10 for secondary views?
- What is missing and therefore needs to be filled in by the developer?
- Do secondary views get opened automatically when an app resumes?

I've looked at the MultipleViews sample but it relies on an external MVVM library, and I'm not sure if this means that it isn't possible to do anything "out of the box" with secondary views with just Template 10?

It looks like the core code from the Microsoft universal samples repo for MultipleViews has been incorporated into Template 10 as per read https://github.com/Windows-XAML/Template10/issues/928 but I'm struggling to understand how the Template 10 MultipleViews sample actually works.

Is there anywhere that this is documented, preferably in a way that allows someone to figure out the answers to questions like the ones I've posed at the top?

**Comment by JerryNixon** [comment]
Ouch, that was 200+ comments/commits ago. Let me try to remember myself. I know there is a sample in the Solution. Have you already seen that?

**Comment by JerryNixon** [comment]
Yeah, I double-checked. If you just use OpenAsync() on the NavigationService instead of Navigate it will create a new View and will return to you a manager so you can deal with the view programatically if you need that control. I am not sure if that answers the question, but I think it does. The sample has everything you need - it's just a line of code to accomplish (T10 is pretty handy).

That being said, I would find it a welcome contribution if you would like to edit this Wiki (https://github.com/Windows-XAML/Template10/wiki/Multiple-Views) so developers tomorrow will have the answers you are finding today.

**Comment by pcolmer** [comment]
I'll certainly give editing the Wiki page a try. I'm going to try and put together a new sample app. As I noted earlier, I prefer to use T10 samples that only rely on T10. That way, a developer can build on them in their own direction.

I want to try and tackle:
- Coping with the user closing the main view. From what I've read, the main thread continues to run and it looks like the Microsoft sample app allows a secondary view to become the main view.
- Demonstrating what happens if the app suspends and resumes.
- Demonstrating what happens if a secondary view opens another view. (I'm assuming it is possible!)
- Trying to come up with a solution that I can understand (!) to the problem of two secondary views of the same page that need to look at the same data. For example, if I'm writing a text editor and want to allow the user to open a secondary view so that they can scroll to a different place, how do I grant access to the text being edited? It needs to be an extensible approach - e.g. if this is a multi-file text editor then I could have two views of file A and two views of file B, etc.

More than happy for anyone else to help out. I'm going to put the sample app on GitHub once I've started it so that others can contribute additional aspects of using multiple views.

References:
- https://mtaulty.com/2015/06/11/m_15844/
- https://mtaulty.com/2015/09/16/m_15940/
- https://channel9.msdn.com/Events/Build/2015/3-779/player (I need to re-watch this)
- https://github.com/Windows-XAML/Template10/issues/52 (potentially for the data sharing aspect)

**Comment by pcolmer** [comment]
OK - it didn't take me very long to get stuck!

https://github.com/pcolmer/T10-MultipleViewsSample is what I've created. Really simple stuff. Clicking on the "Open page 2 in new window" button _seems_ definitely causes something to happen because debug gets output but a secondary window doesn't appear.

I'm looking at what the original Microsoft sample does and the main difference is that it does an await on the OpenAsync call but if I modify my method to do that, I get a thread violation.

**Comment by pcolmer** [comment]
@JerryNixon I'm appearing to get stuck on differences between the NuGet version and the GitHub version of Template 10.

I'm using v1.1.11 of Template 10 from NuGet but I'm hitting two problems:
1. A crash that would seem to match that described in https://github.com/Windows-XAML/Template10/pull/1063 and pulled into GitHub on June 28.
2. The signature for OpenAsync doesn't match that used by the Multiple Windows sample that comes with Template 10. In v1.1.11, the signature seems to be:
   
   ```
   Task OpenAsync(Type page, object parameter = null, string title = null, ViewSizePreference size = ViewSizePreference.UseHalf);
   ```

but the signature in the GitHub version of Template10 is:

```
    Task<ViewLifetimeControl> OpenAsync(Type page, object parameter = null, string title = null, ViewSizePreference size = ViewSizePreference.UseHalf);
```

What am I missing/misunderstanding here?

Thanks.

**Comment by mvermef** [comment]
I believe the beta of 1.12 is the release that contains the updated code otherwise, fork or downloads source and compile yourself

**Comment by pcolmer** [comment]
@mvermef Thanks for the clarification. I _can_ compile the source myself but, as I was trying to put some documentation together for the wiki, I wanted to use the NuGet released code so that the documentation can make it really clear as to dependencies.

I can see that the code for the revised OpenAsync has been marked as part of the v1.1.12 milestone, but the bug fix for the thread error hasn't been similarly marked. I'm hoping that is just a meta thing rather than confirmation of what actually is going into a given release.

**Comment by JerryNixon** [comment]
Updating the wiki with 1.1.12 is fine. We'll update NuGet shortly.
