### ISSUE TITLE
ListViewItemPresenter.SelectionCheckMarkVisualEnabled AU issue

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [Windows-XAML/Template10#1190]
Hi,
I noticed in my app that after updating to latest Anniversary Update SDK ListViewItemPresenter.SelectionCheckMarkVisualEnabled=False doesn't work as expected as the check mark is still visible and really annoying as it overlays the content.
I understand it's not T10 issue at all (thank God), but still, may be someone faced it either and have suggestion on solution?
I've posted the question on [msdn](https://social.msdn.microsoft.com/Forums/security/en-US/b0f8ee0e-f565-4510-a98f-f145a5d8a979/uwpxamlc-listviewitempresenterselectioncheckmarkvisualenabledfalse-still-shows-check-mark?forum=wpdevelop) too.

**Comment by JerryNixon** [comment]
I've notified the platform team for you of the issue. If they respond they will respond on the MSDN thread, not here.

**Comment by Viachaslau-Zinkevich** [comment]
@JerryNixon thanks a lot!
