### ISSUE TITLE
Command binding on HamburgerButtonInfo not working

### ISSUE THREAD

**Issue by jonaswikstrom** [Windows-XAML/Template10#1193]
Hello

I'm trying to use MVVM all the way using the HamburgerMenu.

Having a ShellViewModel for the Shell.xaml page and then trying to bind a command  on the HamburgerButtonInfo control to an ICommand on the VM named ConnectCommand like this:

`<Controls:HamburgerButtonInfo ClearHistory="True" ButtonType="Command" Command="{Binding ConnectCommand, Mode=TwoWay}">`

The binding is not working and the BindingExpression message on output says "BindingExpression path error: 'ConnectCommand' property not found on 'Template10.Controls.HamburgerButtonInfo'."

The ButtonType name clearly promotes a "Command" but the documentation on https://github.com/Windows-XAML/Template10/blob/master/Samples/Search/Readme.md says that this gives the possibility to use the Tap event. 

Is a real Command not possible to use here and in that case, why this naming?

**Comment by dg2k** [comment]
Mode=OneWay ??

**Comment by jonaswikstrom** [comment]
Has oc nothing to do with it! TwoWay since the button is NOT read only. This is a connect button and must be grayed out when logged on.

**Comment by dg2k** [comment]
From the error, obviously ConnectCommand property is not found. Where does the property reside? If in view-model I am inclined to use the x:Bind as {x:Bind ViewModel.ConnectCommand, Mode=....} where ViewModel is set to the DataContext (usually in xaml file). An alternative is {Binding ElementName=PageName, Path=ConnectCommand }. Bottomline -- the binding should find where ConnectCommand is. It is also important to check how you defined your command property -- from experience it's easy to get it wrong as it's more than an ordinary property.

Sorry this is simply based on concept as you provided no code to be more specific.

**Comment by mvermef** [comment]
Is the viewmodel defined in xaml as the datacontext or in codebehind as property of the  view and no name on the xaml definition. Somehow your context for the control is kicking back with the binding error

**Comment by JerryNixon** [comment]
That's my bet too. You are using a binding statement that digs into a view-model that is not there. But there's more you should consider here. Are you planning on HamburgerInfo graying out your content for you when you set CanExecute to false? That _is_ how a Command works with a button, but it is _not_ how it works with HamburgerInfo. Instead, you will require a dedicated property in your view-model and bind to it inside your XAML. I hope this makes sense. In the end, HamburgerInfo is not a button.

**Comment by jonaswikstrom** [comment]
Tanks for all the feedback. I will provide more info if I still have the problem after trying a bit more based on your tips.

If HamburgerButtonInfo is not a button, the naming is quite bad 😏

**Comment by dg2k** [comment]
> If HamburgerButtonInfo is not a button, the naming is quite bad

At the risk of being pedantic, the name is actually **Info** to which the 'naming' applies in HamburgerButton**Info**. Consider **HamburgerButton** an adjective describing **Info**.

**Comment by jonaswikstrom** [comment]
"At the risk of being pedantic, the name is actually Info to which the 'naming' applies in HamburgerButtonInfo. Consider HamburgerButton an adjective describing Info."

What we have today is a app with a quite high download rate. We focus hard on MVVM and the app is today built using Caliburn Micro and the conventional SplitView control. Navigation is done there using Buttons! They work like buttons do and Command binding work as Command binding work targeting an ICommand even the CanExecute part of it as it should! 

We are looking if Template10 can do things more straightforward, this is not the case.

**Comment by jonaswikstrom** [comment]
More info:

DataContext is set on page using:
`<Page.DataContext>
        <viewModels:ShellViewModel x:Name="ViewModel" />
    </Page.DataContext>`

A breakpoint in the page constructor confirms DataContext is ShellViewModel

I tested naming the page and then use:
`Command="{Binding ElementName=TestPage, Path=DataContext.ConnectCommand}`
Still no success...

**Comment by jonaswikstrom** [comment]
Using conventional Binding in a Button and TextBlock outside the Controls:HamburgerMenu works directly. This proves that the problem lies in Template10 Controls:HamburgerMenu. 

What is happening here?!?! I can see that the Controls:HamburgerMenu inherit the DataContext properly as a UserControl, but Controls:HamburgerButtonInfo is not a FrameworkElement not containing DataContext.  Digging deeper the DataContext is obviously null for it childcontrols.  How can binding work for its childcontrols? 

Have one of you guys a working example of the Controls:HamburgerMenu in a MVVM fashion binding Command towards a ViewModel e.g. ShellViewModel? If not, have you ever got it to work?

**Comment by mvermef** [comment]
About half a dozen examples in samples folders, trade binding for x:bind, trade Datacontext for ViewModel in the `Command="{x:Bind ViewModel.ConnectCommand}"`

**Comment by jonaswikstrom** [comment]
"About half a dozen examples in samples folders"

Looked for any binding examples within the HamburgerMenu, not a single hit. Have you read the thread @mvermef ?

By the way, not interested in x:bind! Will not rewrite the app for that, using conventional binding {Binding ICommandPropertyName}

Is this working?!

**Comment by mvermef** [comment]
Ok I have been looking thru the source and stepping thru it and it appears to be a bug
`Command="{Binding SomeCommand, ElementName=ViewModel}"` never actually sets the Command it's always null and I can't seem to find where it ever would

**Comment by dg2k** [comment]
Here is a **OneWay** binding with **x:Bind** that works as a starter:

### XAML

```
<Controls:HamburgerButtonInfo ClearHistory="True" ButtonType="Command" Command="{x:Bind ConnectCommand, Mode=OneWay}">
    <StackPanel Orientation="Horizontal">
        <FontIcon Width="48"
                  Height="48"
                  Margin="0,-3,0,0"
                  FontFamily="Segoe MDL2 Assets"
                  FontSize="24"
                  Glyph="&#xEC27;" />
        <TextBlock  x:Uid="Connect"
                   Margin="12,0,0,0" Text="Connect"
                   VerticalAlignment="Center" />
    </StackPanel>
</Controls:HamburgerButtonInfo>
```
- x:Uid="Connect" assumes you define your string resource 'Connect' in resw file.
- ViewModel.ConnectCommand if using view-model datacontext ViewModel.

### Code-behind

```
DelegateCommand connectCommand;
public DelegateCommand ConnectCommand => connectCommand ?? (connectCommand = new DelegateCommand(async() => await Connect()));
private async Task Connect()
{
    // Do your connection stuff here...
}
```
- using Template10.Mvvm;   // for DelegateCommand

To do **TwoWay** binding, you obviously need to provide extra logic because a value that **ICommand** understands must be returned by a **Binding Converter**, otherwise you'll be greeted with _Invalid binding path 'ConnectCommand' ...Cannot bind  ... DelegateCommand' to ... .ICommand' without a converter_ but depending on what you want there may be an _easier_ workaround with another OneWay binding (such as using another property for button text color/opacity/background). Hope this helps.

**Comment by mvermef** [comment]
I can tell you it doesn't work with twoway delegatecommand  no binding errors, flat doesnt work, the command dependency property never passes its contents and he absolutely doesn't want to use x:bind.

**Comment by dg2k** [comment]
I know @jonaswikstrom doesn't want to use x:Bind, but somehow helps to have a working reference. The code I provided works. Contrary to what you say, if you change the binding to TwoWay an error will be emitted (I have checked this).

**Comment by mvermef** [comment]
Correct me then...

![shellveiw](https://cloud.githubusercontent.com/assets/2018777/18061920/3f3ef31c-6dea-11e6-81d6-50ef9ec3b660.png)

![shellviewmodel](https://cloud.githubusercontent.com/assets/2018777/18061919/3f3e14d8-6dea-11e6-9d2e-ffffd0c9c533.png)

![shellviewxaml-hbinfo](https://cloud.githubusercontent.com/assets/2018777/18061921/3f400f22-6dea-11e6-8745-082e5c87c142.png)

![commandinfo-null-command](https://cloud.githubusercontent.com/assets/2018777/18061922/3f456e54-6dea-11e6-890f-584dc9a6d578.png)

there are no binding errors... Not trying to be difficult trying to understand the dead end this is turning into and how to correct it.

**Comment by dg2k** [comment]
I get it. I suspect the difference is that you used ShellViewModel and I didn't. My x:Bind is just to the codebehind (Shell.xaml.cs). Does that explain?

**Comment by mvermef** [comment]
its what I feared this doesn't work in this case with a viewmodel on the datacontext of the ShellView

**Comment by dg2k** [comment]
Just so that you know:
I've also tested using ViewModel DataContext (command property in ShellViewModel.cs) and everything works as for the shell view. That is, I can hit the x:Bind bound Command property, and if Mode is changed to TwoWay the error is emitted.

Bottom line: works with x:Bind for view or view-model. Doesn't work with classical Binding as you indicate.
