### ISSUE TITLE
Can be a HamburgerButtonInfo checked in code behind?

### ISSUE THREAD

**Issue by marcinmarkiewicz** [Windows-XAML/Template10#1194]
Hi, I have a question about possibility of checking a HamburgerButtonInfo in menu by navigation to different page from code behind? When I'm trying to set my buton's IsChecked property to true, navigation acts ok, but HamburgerButtonInfo doesn't check itself. Has anybody an idea of best solution of this?

**Comment by dg2k** [comment]
**ButtonType** must be set to **Toggle** for the button to be checked. If **ButtonType** is **Command** or **Literal** the checked doesn't show.

**Comment by marcinmarkiewicz** [comment]
@dg2k my buton is Toggle. When I'm clicking on it - checked is shown, but when I'm trying to check it programmaticaly it isn't.

**Comment by JerryNixon** [comment]
Setting a ButtonTupe=Toggle checked state can only be accomplished by setting the HamburgerMenu.Selected value to the HamburgerInfo value that wr45aps the button. Otherwise, you must use Literal and set the Button explicitly.
