### ISSUE TITLE
Examining the BackStack?

### ISSUE THREAD

**Issue by pcolmer** [Windows-XAML/Template10#1195]
There is a section of code in my current WinRT (Windows 8.1/Windows Phone 8.1) app that goes:

```
// The number of pages we need to go back depends on how the user reached this page.
// The previous page will always be ViewRepository. The page before that could be
// DatabaseMainView, or it could be EditSourceRepositoryCitation. If the latter, we
// need to go back another page, to reach EditSourceRecord.
NavigationHelper.GoBack(); // Get rid of ViewRepository
if (this.Frame.BackStackDepth > 1)
{
    PageStackEntry current = this.Frame.BackStack[this.Frame.BackStackDepth - 1];
    if (current.SourcePageType == typeof(EditSourceRepositoryCitation))
        NavigationHelper.GoBack();
}
NavigationHelper.GoBack(); // Return to either EditSourceRecord or DatabaseMainView
```

That doesn't seem to be possible when using Template 10 because the BackStack doesn't seem to be accessible. Looking at https://github.com/PrismLibrary/Prism/issues/67, if T10 did inherit some of its origins from Prism, it suggests that this is one of the reasons why I can't reach BackStack - it is "hidden" inside FrameFacade.

FrameFacade exposes BackStackDepth but not BackStack. Any objections to doing that? Without it, I think I would struggle to see how I could resolve the above approach.

Thanks.

**Comment by mvermef** [comment]
NavigationService.Frame.BackStack

**Comment by pcolmer** [comment]
@mvermef Thank you! Not sure how I missed that!
