### ISSUE TITLE
Regression? Application not restored properly after suspension

### ISSUE THREAD

**Issue by devinfluencer** [Windows-XAML/Template10#1196]
Is this a regression (#871)? I created a new app based on the minimal template, started and entered a value, ended the app. Upon restart state was empty.
 I checked versions, upgraded template10 library to 1.1.11 and 1.1.12-preview, but to no avail.
 The main app I'm working on has the same problem.

**Comment by devinfluencer** [comment]
Were you able to reproduce it?

**Comment by JerryNixon** [comment]
I can confirm that the current code works properly.

![revert](https://cloud.githubusercontent.com/assets/1749983/18752611/2e7b6cae-80a0-11e6-97c1-4a54e812c52a.gif)
