### ISSUE TITLE
How to implement the bread crumbs in the UWP application whit this template?

### ISSUE THREAD

**Issue by dmitrydvm** [Windows-XAML/Template10#1197]
Where get steps navigation? How to do everything, if the control with crumbs will AppShell xaml.

**Comment by adiospl** [comment]
You can try to use Frame BackStack and ForwardStack. 

```
var frame = App.Current.NavigationService.Frame; // Get navigation Frame
var navParam = frame.BackStack.First().Parameter; // Navigation Parameter
var navPageType = frame.BackStack.First().SourcePageType; // typeof Destination Page
// frame.ForwardStack
```

**Comment by JerryNixon** [comment]
Let SO be the home for this question http://stackoverflow.com/questions/39139336/how-to-implement-the-bread-crumbs-in-the-uwp-application

**Comment by dmitrydvm** [comment]
@JerryNixon This is exactly what I was asking the question, just another nickname :-)
Can you help me?
