### ISSUE TITLE
Hamburger Template 10 have not login page without Hamburger menu

### ISSUE THREAD

**Issue by pawanvermadreamorbit** [Windows-XAML/Template10#1198]
Hi Sir,
I am using template 10 for my app and its good while I chose HamburgerTemplate. However there is lack of Login page without shell page. Which I am trying to create but its alway appear with shell page. Kindly help me in it so that I could be able to integrate it properly for my app.

Thanks & Regards

**Comment by mvermef** [comment]
there never has been a login page its coder fodder... It has always been up to the coder to add to the project what he needs.. Are you wanting to go to a Login page before loading the "Visible" shell with hamburgermenu visible.  The simplest thing to do is let it load check for "IsLoggedIn" flag (in your logic) then navigate to the Login page, while setting the IsFullScreen to true which "hides" the hamburger altogether.  Once login logic is satisfied navigate to your "dashboard" or main page, setting IsFullScreen to false. 

I do the logic on OnStartAsync to check for a Token from server then I check the token's age... If null or really old, I force a relog.

**Comment by pawanvermadreamorbit** [comment]
However @mvermef in OnInitializeAsync event there is following code which is impelmenting shell page if I made it comment then login page appear without shell.
if (Window.Current.Content as ModalDialog == null)
            {
                // create a new frame 
                var nav = NavigationServiceFactory(BackButton.Attach, ExistingContent.Include);  
                // create modal root
                Window.Current.Content = new ModalDialog
                {
                    DisableBackButtonWhenModal = true,
                    Content = new Views.Shell(nav),
                    ModalContent = new Views.Busy(),
                };
            }

and in  OnStartAsync have following page.  
public override async Task OnStartAsync(StartKind startKind, IActivatedEventArgs args)
        {
            await Task.Delay(5000);
            NavigationService.Navigate(typeof(Views.Login));
            await Task.CompletedTask;
        }

This login page every time appear with Shell.

**Comment by mvermef** [comment]
what version are you using?  That code is seriously old... OnInitAsync isn't used with Hamburger anymore.

https://github.com/Windows-XAML/Template10/blob/master/Templates%20(Project)/Hamburger/App.xaml.cs

**Comment by pawanvermadreamorbit** [comment]
I installed it from VisualStudio extension  V1.1.0

**Comment by pawanvermadreamorbit** [comment]
I am trying if its working I let you know. :)

**Comment by mvermef** [comment]
the current version is 1.18, actual version of the library is 1.1.11, with a "beta" release of 1.1.12.   The templates are the critical part of the "updated" source that you need for the stuff to make sense.  I suggest you look at the Projects folder with in the that folder is the HamburgerMenu Project it has the latest App.xaml.cs you need to look at to update your source.   Also update the Shell.xaml Shell.Xaml.cs

Its paramount that you update the source of the Template you are using was based on older code, make sure to make necessary changes to be in-line to understand the flow of the application.   Also reference SettingsService it has some update code as well for using IsFullScreen.  Basically, not logged in you want to navigate to the LoginPage, within StartupAsync you will set IsFullScreen to "true" either in the Loginpage OnNavigateToAsync or prior and then on the completion of a successful login you will then navigate to the MainPage or your DashBoard which ever direction you go with that "landing" page., IsFullScreen is then set to false

**Comment by pawanvermadreamorbit** [comment]
kindly update also the extension version over microsoft visual studio gallery

**Comment by pawanvermadreamorbit** [comment]
I have updated version of Template10 and login screen is appearing without shell. Thanks @mvermef. One thing I want to know How can I call 
await NavigationService.NavigateAsync(typeof(Views.Login)); on Button Click if  not in View Model.

**Comment by mvermef** [comment]
What context are you talking, Shell.xaml.cs? App.xaml.cs?

**Comment by pawanvermadreamorbit** [comment]
I am handling navigation on button click with View Model So after some action on form button click or listview itemseleciton change is going to happen on which I want to navigate the page with VIEWModel. Could you tell me how Can I use Command or Relaycommand in it.

**Comment by JerryNixon** [comment]
Good work @mvermef
