### ISSUE TITLE
Suggestions on Inheritance with multiple projects

### ISSUE THREAD

**Issue by tpspencer** [Windows-XAML/Template10#1200]
I am building a UWP/T10 app that will have a basic set of (base)functionality.
I will then have 3 real apps that will apply slightly different behavior.
For instance.  

The 3 'real' apps will use all of the views and view models of basic, but one of the forms will have additional text boxes and check boxes.  Probably have different styles and page headers etc.

I am trying to figure out the best way to structure this type of inheritance.

I am thinking the base functionality will go in a shared project that gets added to RealApp1 2 & 3.

Your suggestions?

**Comment by JerryNixon** [comment]
http://stackoverflow.com
