### ISSUE TITLE
Passing Complex Objects in Navigation

### ISSUE THREAD

**Issue by tpspencer** [Windows-XAML/Template10#1201]
Back in the 8.0 days we would only pass strings in the navigation methods. 

I am successfully passing complex objects with child collections without problem.....well at least I hope there is not a problem I am unaware of.

So has this issue been solved for a vanilla T10 project, or are there some gotcha's I don't know about that will end up causing issues after apps get in user's hands?

Thanks.

**Comment by AmitBhatnagar24** [comment]
https://github.com/Windows-XAML/Template10/wiki/Page-Parameters

**Comment by tpspencer** [comment]
Wow, I did not see that while researching.  Thanks for the link.

> Because the Template 10 NavigationService serializes all parameters, not all types can be successfully passed to a page
1. So what types can't be serialized?
2. Can I assume that if the object model I am passing now works, that it is not a fluke and that it will work going forward?

**Comment by JerryNixon** [comment]
Good work @AmitBhatnagar24
