### ISSUE TITLE
HamburgerMenu.IsOpen not working

### ISSUE THREAD

**Issue by Thaoden** [Windows-XAML/Template10#1204]
I have a HamburgerMenu in `DisplayMode = CompactOverlay` that I'd like to have open when the application starts. Simply setting `IsOpen = "true"` doesn't do the trick for me. Any other toggles that I should set?

```
<controls:HamburgerMenu x:Name="Menu" 
                        NavAreaBackground="Beige" 
                        IsOpen="True"
                        VisualStateNormalMinWidth="0"
                        VisualStateNormalDisplayMode="CompactOverlay"
                        />
```

**Comment by Thaoden** [comment]
Well, it gets more interesting:
When I don't define a secondary button, I don't see the primary:

```
<Page
    x:Class="Dandelion.Views.Shell"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:views="using:Dandelion.Views"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:controls="using:Template10.Controls"
    mc:Ignorable="d">

    <controls:HamburgerMenu x:Name="Menu"
                            IsOpen="True"
                            NavAreaBackground="Beige"
                            NavButtonBackground="Azure"
                            NavButtonForeground="Black"
                            VisualStateNormalMinWidth="0"
                            VisualStateNormalDisplayMode="CompactOverlay"
                            >

        <controls:HamburgerMenu.PrimaryButtons>

            <controls:HamburgerButtonInfo PageType="views:MainPage" ClearHistory="True">
                <StackPanel Orientation="Horizontal" VerticalAlignment="Center">
                    <SymbolIcon Symbol="Home" Width="48" Height="48" />
                    <TextBlock Text="Home" Margin="12,0,0,0" VerticalAlignment="Center"/>
                </StackPanel>
            </controls:HamburgerButtonInfo>

        </controls:HamburgerMenu.PrimaryButtons>

    </controls:HamburgerMenu>

</Page>
```

Results in (menu is closed on startup): 
![withoutsecondary](https://cloud.githubusercontent.com/assets/3832723/18231298/bb50dd00-72b6-11e6-935f-30b167c13b65.png)

When I define a secondary button, I get to see the primary - but not the secondary:

```
<Page
    x:Class="Dandelion.Views.Shell"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:views="using:Dandelion.Views"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:controls="using:Template10.Controls"
    mc:Ignorable="d">

    <controls:HamburgerMenu x:Name="Menu"
                            IsOpen="True"
                            NavAreaBackground="Beige"
                            NavButtonBackground="Azure"
                            NavButtonForeground="Black"
                            VisualStateNormalMinWidth="0"
                            VisualStateNormalDisplayMode="CompactOverlay"
                            >

        <controls:HamburgerMenu.PrimaryButtons>

            <controls:HamburgerButtonInfo PageType="views:MainPage" ClearHistory="True">
                <StackPanel Orientation="Horizontal" VerticalAlignment="Center">
                    <SymbolIcon Symbol="Home" Width="48" Height="48" />
                    <TextBlock Text="Home" Margin="12,0,0,0" VerticalAlignment="Center"/>
                </StackPanel>
            </controls:HamburgerButtonInfo>

        </controls:HamburgerMenu.PrimaryButtons>

        <controls:HamburgerMenu.SecondaryButtons>
            <controls:HamburgerButtonInfo PageType="views:MainPage">
                <StackPanel Orientation="Horizontal" VerticalAlignment="Center">
                    <SymbolIcon Symbol="Setting"  Width="48" Height="48"  />
                    <TextBlock Text="Settings" Margin="12, 0, 0, 0" VerticalAlignment="Center"/>
                </StackPanel>
            </controls:HamburgerButtonInfo>
        </controls:HamburgerMenu.SecondaryButtons>

    </controls:HamburgerMenu>

</Page>
```

Results in (menu closed again):
![withsecondary](https://cloud.githubusercontent.com/assets/3832723/18231302/e10a9270-72b6-11e6-90d0-6ad598736938.png)

What am I doing wrong?

**Comment by dg2k** [comment]
### To answer the first part:
- To start with, using `VisualStateNormalMinWidth="0"` is not the norm and I'm assuming that you know what you're doing here. I would nornally set VisualStateNormalMinWidth around 520 to 600 (with default setting of 521 in Styles\Custom.xaml). Set `VisualStateNormalMinWidth="521"` and note the difference. Probably this answers the question and the following could be redundant.
- If the above doesn't answer the question and still you want to do something with VisualStateNormalMinWidth set to 0 (acceptable as long as you know what you're doing), then to me `IsOpen = True` with `DisplayMode = CompactOverlay` makes no sense. When you set to CompactOverlay what you want is for the **pane** to open normally by user interaction. It would be odd for CompactOverlay to start with the pane open as if the HamburgerMenu button is tapped. If `IsOpen = True` is intended simply to show the **48px width compact part** of CompactOverlay, which by the way is missing due to `VisualStateNormalMinWidth="0"` (and `IsOpen = True` doesn't bring it back), then you now know the problem which is already answered above.  The **bold** is to emphasize the difference between the two.

### To answer the second part:

The secondary button is there but masked by the Beige color. Remove `NavAreaBackground="Beige"` and see the difference. Your theme definition is incomplete (there are a dozen color settings for HamburgerMenu theme) hence why you're having this problem. As a matter of style (no pun!) I would leave the task of color/theme definition to Styles\Custom.xaml rather than bring it out to Shell.xaml.

**Comment by Thaoden** [comment]
**Regarding `IsOpen`**

Ok, so I removed the `VisualStateNormalMinWidth` and `VisualStateWideDisplayMode` from the HamburgerMenu and also removed the `VisualStateNormalMinWidth` from the page header (that is not shown here). The general layout still looks the way I want - obviously I misunderstood the docs for the `VisualStateNormalMinWidth`s.

My intention for `IsOpen = true` was indeed to start the application with the complete menu expanded to show the button descriptions. But still, the secondary button is not shown and the primary one disappears when I remove the definition for the secondary button.

**Regarding the buttons** 

~~Btw, should I split these into two separate issues?~~ Moved into separate issue #1205

**Comment by dg2k** [comment]
> My intention for IsOpen = true was indeed to start the application with the complete menu expanded to show the button descriptions.

Then what you want is **CompactInline** mode rather than **CompactOverlay** mode.

**Comment by Thaoden** [comment]
> Then what you want is CompactInline mode rather than CompactOverlay mode.

Not exactly, as I don't want the content to be pushed to the right.

**Comment by IIARROWS** [comment]
I haven't checked the code, but maybe it doesn't works because it loses the "focus" when the main page is navigated to (it's not merely the control focus because it stays open if you change active window).

I tried writing this line of code inside `MainPageViewModel.OnNavigatedTo`

`Shell.HamburgerMenu.IsOpen = true`

And it works, the menu stays opened in overlay mode, until the user interacts.

**Comment by Thaoden** [comment]
In the `ViewModel`?
When I override `MainPage.OnNavigatedTo`, `Shell.Menu` is not accessible due to its protection level.

**Comment by IIARROWS** [comment]
In standard `Shell` code behind there is a static property `HamburgerMenu` that exposes the menu.

**Comment by Thaoden** [comment]
I added in App.xaml.cs:

```
protected override void OnNavigatedTo(NavigationEventArgs e)
{
    Shell.Menu.IsOpen = true;
}
```

but it is still closed on app start.

I think I'll go with @dg2k 's suggestion and use `CompactInlay` and have to live with the content being pushed to the right, if I want to have an open menu.

**Comment by IIARROWS** [comment]
Do you have these inside your Shell view?

```
public static Shell Instance { get; set; }
public static HamburgerMenu HamburgerMenu => Instance.MyHamburgerMenu;
```

It's called HamburgerMenu, not Menu... and it works for me.

**Comment by Thaoden** [comment]
Well it's called `Menu` in my Shell.xaml.cs:

```
public static Shell Instance { get; set; }
public static HamburgerMenu Menu => Instance.MainMenu;

public Shell(INavigationService navigationService)
{
    Instance = this;
    this.InitializeComponent();
    MainMenu.NavigationService = navigationService;
}
```

Sadly, doesn't work for me. But as I said, I'll go with `CompactInlay`...

**Comment by Thaoden** [comment]
Why has this been closed? While I can use the workaround, I'd really like the `CompactOverlay` to stay open :)

**Comment by IIARROWS** [comment]
Because with a new app, it works. Probably there is something with your configuration.

**Comment by IIARROWS** [comment]
Because with a new app, it works. Probably there is something with your configuration.

**Comment by IIARROWS** [comment]
Because with a new app, it works. Probably there is something with your configuration.

**Comment by IIARROWS** [comment]
Because with a new app, it works. Probably there is something with your configuration.

**Comment by IIARROWS** [comment]
Because with a new app, it works. Probably there is something with your configuration.

**Comment by IIARROWS** [comment]
Because with a new app, it works. Probably there is something with your configuration.

**Comment by IIARROWS** [comment]
Because with a new app, it works. Probably there is something with your configuration.

**Comment by IIARROWS** [comment]
Because with a new app, it works. Probably there is something with your configuration.

**Comment by IIARROWS** [comment]
Because with a new app, it works. Probably there is something with your configuration.

**Comment by IIARROWS** [comment]
Because with a new app, it works. Probably there is something with your configuration.

**Comment by IIARROWS** [comment]
Because with a new app, it works. Probably there is something with your configuration.

**Comment by Thaoden** [comment]
@IIARROWS If it was something with my configuration, I'd be happy to get some help here.
But in fact, it isn't. I used the Hamburger Template from Template10, changed the DisplayMode to `CompactOverlay` and added the line `Shell.HamburgerMenu.IsOpen = true;` to `MainPage.OnNavigatedTo()`. The pane is closed on startup.

Could you upload your working app solution to somewhere so I can take a look and figure out what I've done differently?

**Comment by IIARROWS** [comment]
Start with checking your version, if it's the last or not. That can help.
I have the latest preview.

From the code you posted, you also have `IsOpen="True"` in XAML, try removing that.

**Comment by mvermef** [comment]
I would also check that the template is 1.18, if it's not then you are not current and any code we suggest would be negative since the latest variant has significant changes from previous versions specifically how the Hamburger is started in code.

**Comment by Thaoden** [comment]
Removing `IsOpen="true"` from XAML didn't help.
I have the templates version 1.18 installed, also in `project.json`: 

```
"dependencies": {
    (...)
    "template10": "1.1.11"
},
```

which seems to be the current version according to [NuGet](https://www.nuget.org/packages/template10).

I just saw on [the wiki page for template10](https://github.com/Windows-XAML/Template10/wiki) that

> On initial load, the state of the HamburgerMenu can be incorrect (in some instances).

Curious what instances that might be. That's why I'd like to compare with other working examples.

**Comment by Thaoden** [comment]
Still struggling with it so I played around a bit more.
When I set `Shell.HamburgerMenu.IsOpen=true` in `MainPage.OnNavigatedTo`, navigate to a different page and then navigate again to `MainPage` (using the menu, not the back button), the menu is open for a split second before closing again. 
If I use the back button instead, it stays open as desired!
Any ideas as to why?

**Comment by IIARROWS** [comment]
You have to do that in the ViewModel, not in the View...

Also, do that on a new project before trying again for on your.

**Comment by Thaoden** [comment]
Slowly getting there - it is open on any navigation to the page, but still is closed on app startup...
