### ISSUE TITLE
HamburgerMenu Buttons not showing

### ISSUE THREAD

**Issue by Thaoden** [Windows-XAML/Template10#1205]
I moved this from #1204 into a separate issue.

When I define two primary buttons, the first one is not shown:

```
<Page
    x:Class="Dandelion.Views.Shell"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:views="using:Dandelion.Views"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:controls="using:Template10.Controls"
    mc:Ignorable="d">

    <controls:HamburgerMenu x:Name="Menu" IsOpen="True" NavAreaBackground="Beige" NavButtonBackground="Azure" NavButtonForeground="Black" SecondarySeparator="Red" DisplayMode="CompactOverlay" >

        <controls:HamburgerMenu.PrimaryButtons>

            <controls:HamburgerButtonInfo PageType="views:MainPage" ClearHistory="True">
                <StackPanel Orientation="Horizontal" VerticalAlignment="Center">
                    <SymbolIcon Symbol="Home" Width="48" Height="48" />
                    <TextBlock Text="Home" Margin="12,0,0,0" VerticalAlignment="Center"/>
                </StackPanel>
            </controls:HamburgerButtonInfo>
            <controls:HamburgerButtonInfo PageType="views:MainPage" ClearHistory="True">
                <StackPanel Orientation="Horizontal" VerticalAlignment="Center">
                    <SymbolIcon Symbol="Primary" Width="48" Height="48" />
                    <TextBlock Text="Second Primary" Margin="12,0,0,0" VerticalAlignment="Center"/>
                </StackPanel>
            </controls:HamburgerButtonInfo>

        </controls:HamburgerMenu.PrimaryButtons>
    </controls:HamburgerMenu>

</Page>
```

gives 

<img src="https://cloud.githubusercontent.com/assets/3832723/18232347/320a1062-72ce-11e6-80ae-4e7f7e1addbc.png" width="300" />

When I define additional secondary buttons, the primaries are shown, but the first secondary isn't, although there is space reserved for it:

```
<Page
    (omitted)

        <controls:HamburgerMenu.PrimaryButtons>

            <controls:HamburgerButtonInfo PageType="views:MainPage" ClearHistory="True">
                <StackPanel Orientation="Horizontal" VerticalAlignment="Center">
                    <SymbolIcon Symbol="Home" Width="48" Height="48" />
                    <TextBlock Text="Primary" Margin="12,0,0,0" VerticalAlignment="Center"/>
                </StackPanel>
            </controls:HamburgerButtonInfo>
            <controls:HamburgerButtonInfo PageType="views:MainPage" ClearHistory="True">
                <StackPanel Orientation="Horizontal" VerticalAlignment="Center">
                    <SymbolIcon Symbol="Mail" Width="48" Height="48" />
                    <TextBlock Text="Second Primary" Margin="12,0,0,0" VerticalAlignment="Center"/>
                </StackPanel>
            </controls:HamburgerButtonInfo>

      </controls:HamburgerMenu.PrimaryButtons>

        <controls:HamburgerMenu.SecondaryButtons>
            <controls:HamburgerButtonInfo PageType="views:MainPage">
                <StackPanel Orientation="Horizontal" VerticalAlignment="Center">
                    <SymbolIcon Symbol="Setting"  Width="48" Height="48"  />
                    <TextBlock Text="Secondary" Margin="12, 0, 0, 0" VerticalAlignment="Center"/>
                </StackPanel>
            </controls:HamburgerButtonInfo>
            <controls:HamburgerButtonInfo PageType="views:MainPage">
                <StackPanel Orientation="Horizontal" VerticalAlignment="Center">
                    <SymbolIcon Symbol="Shop"  Width="48" Height="48"  />
                    <TextBlock Text="Second Secondary" Margin="12, 0, 0, 0" VerticalAlignment="Center"/>
                </StackPanel>
            </controls:HamburgerButtonInfo>
        </controls:HamburgerMenu.SecondaryButtons>

    </controls:HamburgerMenu>

</Page>
```

gives 

<img src="https://cloud.githubusercontent.com/assets/3832723/18232362/808a7dc6-72ce-11e6-9aa5-75c09e3db548.png" width="300" />

When I define only a single primary button, it is not shown at all.

**Comment by dg2k** [comment]
To rule out a platform issue, just in in case you're targetting version Build14393, change it to 10586 and let me know if there is any difference.

**Comment by Thaoden** [comment]
I targeted 10586 originally, tried it with 10240, no changes there.

**Comment by dg2k** [comment]
So, you are not using the latest update of Windows 10 Build 14393 (or Anniversary Update). I just wanted to eliminate that possibility as I noticed some XAML issues on Build 14383 Platform (example #1202).

**Comment by Thaoden** [comment]
Exactly.

**Comment by dg2k** [comment]
- I still suspect your choice of color schemes for menu not showing up. When you say the first primary menu doesn't show, I checked your xaml on my system and the menu shows but faintly due to the Beige color masking out the white foreground for the menu. Remove all the color scheme definitions from **controls:HamburgerMenu** and see what I mean.  I am also curious as to what display type you're using. Desktop with high resolution? What display is the snapshots taken from?
- In my previous answer, I said the color scheme definition was incomplete. I also indicated better do the definitions via Styles\Custom.xaml. I have never defined color schemes as you did and therefore cannot comment if there is a timing issue doing this way. So better do it via Custom.xaml and see if that works. I know style definition works via Custom.xaml -- we did a lot of testing in the early days about a year ago.
- Put your xaml menu either in Grid or RelativePanel container. Not suggesting this was a problem, just an observation.

**Comment by Thaoden** [comment]
I moved the color definitions to `Custom.xaml`. I don't know what exactly that changed, but I can see all the buttons now. The color scheme is definitely not final, it was merely to get an idea of what is going on.
As for your questions, I'm using a Desktop machine with 1680x1050. Snapshots are taken with Alt+Print.

I followed the how-to for putting the Hamburger in a Shell. Should I still put it in a Grid?

Thanks for your help!

**Comment by dg2k** [comment]
Good you're on the right track. Fine with the display -- just wanted to make sure that poor display resolution is not playing some tricks in what you were describing.

Template 10 has a repository of [samples](https://github.com/Windows-XAML/Template10/tree/master/Samples) that provide an extensive learning resource.

Also, if you're using T10 templates (Visual Studio extension), create a new project with Hamburger Template and have a look what the Shell.xaml looks like. Yours is not far off, just for the Grid container, etc. With nearly two-dozen samples, you'll find almost everything to give you a head-start in UWP app dev.

Saying all that, the source code is of course at your disposal which you can download and explore.
