### ISSUE TITLE
Relaunching an app before OnInitializeAsync is completed causes NullReferenceException

### ISSUE THREAD

**Issue by pekspro** [Windows-XAML/Template10#1206]
Add this in the blank project app.xaml.cs-file in the current source:

```
public override async Task OnInitializeAsync(IActivatedEventArgs args)
{
    System.Diagnostics.Debug.WriteLine("*** Starts OnInitializeAsync...");

    await Task.Delay(30 * 1000);

    System.Diagnostics.Debug.WriteLine("*** OnInitializeAsync is completed.");

    await base.OnInitializeAsync(args);
}
```

Now launch the application from Visual Studio. Then before the 30 seconds timeout is completed launch the application again via the start menu. This will create a NullReferenceException.

This is because then the application is relaunched InternalLaunchAsync is called which calls CallOnStartAsync which then calls OnStartAsync which wants to use NavigationService that is null in that moment.

Yes, this is a really evil case :-). But this has caused me problems when running my app on the phone, which takes about 2 seconds two start. I have noticed that sometime I launch my app by mistake and goes back two start screen before it’s booted. And then when I launch it later it’s crashes.

**Comment by pekspro** [comment]
I’ve modified InternalLaunchAsync locally like this:

```
private bool InternalLaunchAsyncIsRunning = false;

private async Task InternalLaunchAsync(ILaunchActivatedEventArgs e)
{
    while (InternalLaunchAsyncIsRunning)
        await Task.Delay(100);

    InternalLaunchAsyncIsRunning = true;

    try
    {
        DebugWrite($"Previous:{e.PreviousExecutionState.ToString()}");

        //...original implementation...//
    }
    finally
    {
        InternalLaunchAsyncIsRunning = false;
    }
}
```

This is very ugly! I’m almost embarrassed :-) But it seems so solve my problem. 

I have tested this in my app in various ways and it seems to works well. In one case I started my app and then interrupted the launch. Then I launched it again with a secondary tile and interrupted the launch a second time. Then I launched it a third time with a different secondary tile and it launched the appropriate page. And when I navigated back the expected pages (based on the previous launches) was loaded.

**Comment by JerryNixon** [comment]
Okay @pekspro, I am testing this now. We'll see if it can be handled.

**Comment by pekspro** [comment]
I’m still having problem with this. Currently I have been able to reproduce this on a phone without a debugger attached with preview 1.1.12.preview-160922.

When this happens CurrentStateHistory has these values:

BeforeLaunch
BeforeInit
BeforeLaunch
BeforeInit

**Comment by pekspro** [comment]
Now I know how to reproduce this on a PC. First I modified OnInitializeAsync in the blank project app.xaml.cs-file:

```
    private bool OnInitializeAsyncRunning = false;
    public override async Task OnInitializeAsync(IActivatedEventArgs args)
    {
        if(OnInitializeAsyncRunning)
        {
            DebugWrite("*** OnInitializeAsync already running!");
            throw new Exception("OnInitializeAsync already running!");
        }

        OnInitializeAsyncRunning = true;

        DebugWrite("*** Starts OnInitializeAsync...");

        await Task.Delay(30 * 1000);

        DebugWrite("*** OnInitializeAsync is completed.");

        await base.OnInitializeAsync(args);

        OnInitializeAsyncRunning = false;
    }
```

Then I start the application in the debugger. Right after this I resume the application. Next step was to start the application from the start menu which will cause the application due the Exception in OnInitializeAsync. The log looks like this:

```
09:46:56.7435930 Template10 BootStrapper..ctor base.Constructor
09:46:57.2860123 Template10 BootStrapper.OnWindowCreated 
09:46:57.3550641 Template10 WindowWrapper.Static Constructor 
09:46:57.4881590 Template10 BootStrapper.Loaded 
09:46:57.5507041 Template10 DispatcherWrapper.Constructor 
09:46:57.6392664 Template10 BootStrapper.OnLaunched 
09:46:57.6622827 Template10 BootStrapper.CurrentState CurrenstState changed to BeforeLaunch
09:46:57.6833016 Template10 BootStrapper.InternalLaunchAsync Previous:NotRunning
09:46:57.7013144 Template10 BootStrapper.InitializeFrameAsync IActivatedEventArgs:Launch
09:46:57.7437698 Template10 BootStrapper.CallShowSplashScreen 
09:46:57.8203327 Template10 BootStrapper.ActivateWindow source:SplashScreen
09:46:57.8373444 Template10 BootStrapper.CallOnInitializeAsync 
09:46:57.8513543 Template10 BootStrapper.CurrentState CurrenstState changed to BeforeInit
09:46:57.8673697 Template10 BootStrapper.OnInitializeAsync *** Starts OnInitializeAsync...
09:47:02.9275442 Template10 BootStrapper.AutoSuspendAllFramesAsync autoExtendExecutionSession: True
09:47:02.9525434 Template10 BootStrapper.SuspendAllFramesAsync 
09:47:02.9795642 Template10 BootStrapper.OnSuspendingAsync Virtual SuspendingEventArgs:Windows.ApplicationModel.SuspendingOperation prelaunchActivated:False
09:47:08.5039936 Template10 BootStrapper.Resuming 
09:47:08.5300156 Template10 BootStrapper.OnResuming Virtual, previousExecutionState:Suspended
09:47:08.5490291 Template10 BootStrapper.OnLaunched 
09:47:08.5650401 Template10 BootStrapper.CurrentState CurrenstState changed to BeforeLaunch
09:47:08.5850543 Template10 BootStrapper.InternalLaunchAsync Previous:Suspended
09:47:08.6040710 Template10 BootStrapper.InitializeFrameAsync IActivatedEventArgs:Launch
09:47:08.6208624 Template10 BootStrapper.CallShowSplashScreen 
09:47:08.6378749 Template10 BootStrapper.ActivateWindow source:SplashScreen
09:47:08.6528851 Template10 BootStrapper.CallOnInitializeAsync 
09:47:08.7129294 Template10 BootStrapper.CurrentState CurrenstState changed to BeforeInit
09:47:12.8449383 Template10 BootStrapper.OnInitializeAsync *** OnInitializeAsync already running!
09:47:12.9303687 Template10 BootStrapper.OnResuming Virtual, previousExecutionState:Terminated
09:47:12.9488954 Template10 BootStrapper.DetermineStartCause IActivatedEventArgs:Launch
```

So it’s not the same problem with NullReferenceException as originally reported. But having concurrent calls to OnInitializeAsync should be avoided I think :-).

**Comment by pekspro** [comment]
@JerryNixon, can we please reopen this issue?

**Comment by JerryNixon** [comment]
Ah, I see.

**Comment by JerryNixon** [comment]
Looks like line 559 should be `await CallOnInitializeAsync(false, e);` instead of `await CallOnInitializeAsync(true, e);`. OnInitialize should not be repeated. I can't quite recall why that option was ever created. Remind me if you see why. Otherwise I think this resolves it.

**Comment by pekspro** [comment]
I don’t like to say this, but there is still an issues with this. I tried again with my test code above and:
- Launched the application in Visual Studio
- Suspended the application still in boot
- Started the application from the start menu
- Suspended the again application still in boot
- Started the application from the start menu
- The application will now be stuck and just showing the custom splash screen.

The problem seems to be that the custom splash screen is launched twice in this scenario. I tried to do a hack that makes sure that the splash screen is only launched once and that seems to solve this issue.

**Comment by JerryNixon** [comment]
What does "Suspended the application still in boot" mean?

**Comment by pekspro** [comment]
It means: I suspended the application while the application still was booting, or in either words it was still executing the delay of 30 seconds in OnInitializeAsync.

**Comment by marcinmarkiewicz** [comment]
@pekspro maybe it is connected with your issue  #1286

**Comment by JerryNixon** [comment]
Resolved
