### ISSUE TITLE
How Can I Use Delegate command in ListView of Template10

### ISSUE THREAD

**Issue by pawanvermadreamorbit** [Windows-XAML/Template10#1207]

**Comment by pawanvermadreamorbit** [comment]
Please help me in this,

**Comment by dg2k** [comment]
Look at [this snippet](https://github.com/Windows-XAML/Template10/issues/1193#issuecomment-243089629) or many similar ones in the [sample projects](https://github.com/Windows-XAML/Template10/tree/master/Samples).

In the snippet I referred to, do the x:Bind to your ListView event instead (such as ItemClick event) -- in snippet shown as bound to Command event for menu button.

**Comment by JerryNixon** [comment]
http://stackoverflow.com
