### ISSUE TITLE
Adjustable HaburgerMenu Primary Buttons and Navigation Parameter 

### ISSUE THREAD

**Issue by callMeJohn96** [Windows-XAML/Template10#1212]
I have the two following issues. 
I'm creating customly the primary buttons of the hamburger menu through c# in order to have an adjustable list and I'm trying to pass a parameter to the called page. 

I have two issues. 
1) Everytime I select one button after having selected another first it shows me on the left that both are selected. 

2)The e.Paramater the I get after using the HamburgerButtonInfo.PageParameter is of type System.String instead of ObservableCollection I initially set it.This causes a nullRefernce exception.

Any help?

**Comment by JerryNixon** [comment]
I don't understand issue 1. Issue two is by design, based on the limited information you are providing. Try simplifying your parameters and fetching complex objects from a shared or static variable. You can also use SessionState in BootStrapper or any ViewModel.

**Comment by JerryNixon** [comment]
It's also important to put one issue in an issue next time. Thanks for the question though.
