### ISSUE TITLE
Localization HambergerMenu at run Time

### ISSUE THREAD

**Issue by shahramSo** [Windows-XAML/Template10#1214]
Hi Jerry,
I have localized all the app and can change language at run time except shell.xaml. so hamburger menu is not changed at run time.
Is this a bug?  or do you have a solution?
Thanks

**Comment by JerryNixon** [comment]
Are you localizing with x:UID?

**Comment by shahramSo** [comment]
Yes, I do with x:UID, and all pages is localized at run time except shell.  so shell needs to restart for resolving this problem. and also I called the refresh() method of navigation but this problem is not solved.

**Comment by JerryNixon** [comment]
http://stackoverflow.com/questions/32715690/c-sharp-change-app-language-programmatically-uwp-realtime

I will assume you are doing it wrong. If not, open a new issue.

**Comment by shahramSo** [comment]
I did all the work Jerry as your reference link, but I did not get result, I think, it's a good idea if you create a sample with minimum 2 pages as multilingual support of hamburger menu.
Thanks

**Comment by ivanbottero** [comment]
Any news about this?
Is there an example to multilingual support of hamburger menu?
