### ISSUE TITLE
SessionState being loaded too late?

### ISSUE THREAD

**Issue by tpspencer** [Windows-XAML/Template10#1216]
I add values to SessionState in app.xaml.cs.

I have a TPSViewModelBase that is based on ViewModelBase.

In the constructor of my TPSViewModelBase I am trying access values from SessionState.

The SessionState object is null at this time in the flow.  I am having to use BootStrapper.Current to get SessionState.

`BootStrapper.Current.SessionState["DomainName"] as string;`

Can SessionState be loaded on ViewModelBase earlier so it is available to our VM constructors?

**Comment by AmitBhatnagar24** [comment]
Instead of fetching the session state in the VM's ctor, do it in the VM's OnNavigatedToAsync override.

**Comment by tpspencer** [comment]
I am fetching the session data in a baseviewmodel constructor where I am loading up many other things.  I would have to override the method in the base and that just clutters things up.

Unless there is a good reason for the framework not to load the sessionitems earlier, it seems like a good change to make.

**Comment by JerryNixon** [comment]
Since you are doing this in an abnormal way, you can access it in an abnormal way. `BootStrapper.Current().SessionState`. Then you can have it in your constructor. It's pretty standard that in OOP the value of properties has no value in the constructor of the class. Think about it.
