### ISSUE TITLE
Ability to use a custom serializer for navigation state?

### ISSUE THREAD

**Issue by FrayxRulez** [Windows-XAML/Template10#1217]
Hi, in my app I have to pass some big objects between pages and many times when tombstoning the JSON result is too big to be stored in settings and the app crashes.

In the other and my models are supporting de/serialization via BinaryReader/Writer so I will get many advantages serializing object > bytes > string > bytes > object than using JSON that is slower and heavier.

**Comment by tpspencer** [comment]
Have you tried using SessionState?  
Scroll down to the bottom where Jerry talks about it.
[Passing Page Parameters](https://github.com/Windows-XAML/Template10/wiki/Page-Parameters)

**Comment by JerryNixon** [comment]
Sounds like you need `FileIO.WriteText(JSON);`

**Comment by FrayxRulez** [comment]
Solved. Just discovered that SerializationService  property of NavigationService is settable :)
