### ISSUE TITLE
Can't show MainView when App has no HamburgerMenu in Shell.xaml

### ISSUE THREAD

**Issue by stalek71** [Windows-XAML/Template10#1218]
I'd like to create an app that has login page without HamburgerMenu and MainViewPage with hamburger menu. So from my shell I'd like to navigate to login page (without Hamburger) and after login operation to switch to main view. To achieve this goal I removed Hamburger menu definition from Shell.xaml (it's empty now). The following code (below) shows the current state of the code (trying to navigate to MainView from shell). It's fragment of App.cs (App derives from T10.Bootstrapper)

```
   public override async Task OnInitializeAsync(IActivatedEventArgs args)
    {
        // Construct dependency container
        CompositionRoot.ConstructContainer();

        if (Window.Current.Content as ModalDialog == null)
        {
            // Create a new frame 
            var navService = NavigationServiceFactory(BackButton.Attach, ExistingContent.Include);

            // Register navigation instance for injection (in DI container)
            CompositionRoot.Container.RegisterInstance<INavigationService>(navService);

            // Create modal root
            Window.Current.Content = new ModalDialog
            {
                DisableBackButtonWhenModal = true,
                Content = new Shell(navService),
                ModalContent = new Busy(),
            };
        }
        await Task.CompletedTask;
    }

    public override INavigable ResolveForPage(Page page, NavigationService navigationService)
    {
        Type pvmTypeFromAttribute = page.GetType().GetTypeInfo().GetCustomAttribute<ViewModelTypeAttribute>()?.ViewModelType;
        if (pvmTypeFromAttribute != null)
        {
            var pageViewModel = CompositionRoot.Container.GetInstance(pvmTypeFromAttribute);
            return pageViewModel as INavigable;
        }
        else
            return base.ResolveForPage(page, navigationService);
    }

    public override async Task OnStartAsync(StartKind startKind, IActivatedEventArgs args)
    {
        // long-running startup tasks go here
        //await Task.Delay(5000);

        NavigationService.Navigate(typeof(MainPage));
        await Task.CompletedTask;
    }
```

After navService creation in OnInitializeAsync the collection of nav services (NavigationServices in WindowsWrapper class) has one navigation service. When code hits breakpoint in OnStartAsync method the collection of nav services contains two instances already, because in InitializeFrameAsync (in Bootstraper class) the code constructed additional Frame because CurrentState has States.Splashing value. See below...

```
   private async Task InitializeFrameAsync(IActivatedEventArgs e)
    {
        /*
            InitializeFrameAsync creates a default Frame preceeded by the optional 
            splash screen, then OnInitialzieAsync, then the new frame (if necessary).
            This is private because there's no reason for the developer to call this.
        */

        DebugWrite($"{nameof(IActivatedEventArgs)}:{e.Kind}");

        ShowSplashScreen(e);
        await CallOnInitializeAsync(true, e);
        SetupCustomTitleBar();

        // if there's custom content then there's nothing to do
        if (CurrentState == States.Splashing)
        {
            Window.Current.Content = CreateRootElement(e);
        }
        else if (Window.Current.Content == null)
        {
            Window.Current.Content = CreateRootElement(e);
        }
        else
        {
            // nothing: custom content
        }
    }
```

The issue is probably because of the definition of NavigationService property in Bootstrapper class (it takes "FirstOrDefault" nav service). Currently it's defined as below: 

```
      public INavigationService NavigationService => WindowWrapper.Current().NavigationServices.FirstOrDefault();
```

What to do with it? 
How to fix the code to show MainView page using current version of T10?
Just to avoid creation of NavService in OnInitializeAsync (postponing shell initialization until OnStartAsync)  :) ?
The operation shown below succeeded, but app screen remains the same (navigation succeeded on invisible Frame)...

```
NavigationService.Navigate(typeof(Views.MainPage));
```

**Comment by mvermef** [comment]
First off that Hamburger app.xaml.cs code is really old that you pasted, it has been significantly updated... I suggest you reference the updated Project Templates.

**Comment by stalek71** [comment]
Thanks for the response :)
I have for sure latest version of templates installed as a bundle (Template 10 Template Pack, ver. 1.18).
Git repository has similar code also (synced yesterday with git repo of T10).
Could you help me to find the newer one version of it? Has it been moved to separate git repo?
The current one version of App.xaml.cs I see in T10 git repo is below...

```
[Bindable]
sealed partial class App : BootStrapper
{
    public App()
    {
        InitializeComponent();
        SplashFactory = (e) => new Views.Splash(e);

        #region app settings

        // some settings must be set in app.constructor
        var settings = SettingsService.Instance;
        RequestedTheme = settings.AppTheme;
        CacheMaxDuration = settings.CacheMaxDuration;
        ShowShellBackButton = settings.UseShellBackButton;

        #endregion
    }

    public override UIElement CreateRootElement(IActivatedEventArgs e)
    {
        var service = NavigationServiceFactory(BackButton.Attach, ExistingContent.Exclude);
        return new ModalDialog
        {
            DisableBackButtonWhenModal = true,
            Content = new Views.Shell(service),
            ModalContent = new Views.Busy(),
        };
    }

    public override async Task OnStartAsync(StartKind startKind, IActivatedEventArgs args)
    {
        // TODO: add your long-running task here
        await NavigationService.NavigateAsync(typeof(Views.MainPage));
    }
}
```

When I use CreateRootElement it behaves similar way (although I see one nav service now), so it still doesn't show content of MainViewPage. Navigate() method succeeded and  

```
page.Equals(Frame.Content?.GetType());   
```

after frame navigation returns true :(

**Comment by mvermef** [comment]
Oh wait you need to use resolveforpage not navigate now.... Since you're using ioc

**Comment by stalek71** [comment]
Yes, and it resolves page vm without any problems. I see working MainView when I have Hamburger directly in Shell xaml, but not when it's missing from def. Definitely Frame is behind visual tree ... :(
I can try to attach it manually, but in code of Hamburger I don't see any special code to embed Frame in Hamburger visual tree. I think I had to missed something yet ... :)

**Comment by mvermef** [comment]
#980 was the approximate time frame of some breaking changes

**Comment by mvermef** [comment]
I suspect some missing shell changes that were missed with actual template changes.

**Comment by stalek71** [comment]
I see in the code nav service instance I use from DI is the same I see in OnStartAsync. When I embedd Hamburger in shell xaml and pass nav serv to shell constructor it does navigation as it should, so the question is what "magic" is responsible for embedding Frame instance assigned to nav service in Hamburger visual tree. Probably some events subscribed from Hamburger NavigationService prop changes...

**Comment by stalek71** [comment]
Yes, I found it :)

```
 partial void InternalNavigationServiceChanged(ChangedEventArgs<INavigationService> e)
    {
        e.NewValue.AfterRestoreSavedNavigation += (s, args) => HighlightCorrectButton(NavigationService.CurrentPageType, NavigationService.CurrentPageParam);
        e.NewValue.FrameFacade.Navigated += (s, args) => HighlightCorrectButton(args.PageType, args.Parameter);
        ShellSplitView.Content = e.NewValue.Frame;
        UpdateFullScreenForSplashScreen(e);
    }
```

Shell split view content has Frame attached to so I'm on the way to resolve the issue finally :)

**Comment by stalek71** [comment]
I overlooked body of InternalVisualStateNormalMinWidthChanged method because it had "partial" declaration and I assumed it has been declared for custom versions of T10 (and has no body at all).
Unfortunately it had body in other file. Declaration of it is like below:

```
       partial void InternalVisualStateNormalMinWidthChanged(ChangedEventArgs<double> e);
```

The moral from the whole store is simple: dig dipper :)

**Comment by mvermef** [comment]
Great 🤗

**Comment by stalek71** [comment]
Thanks for your help Morgan :)

**Comment by JerryNixon** [comment]
Good work
