### ISSUE TITLE
Support MVVM scenarios for IsEnabled and Visibility properties of NavigationButtonInfo

### ISSUE THREAD

**Issue by MichaelPetrinolis** [Windows-XAML/Template10#122]
I made some changes to support MVVM for NavigationButtonInfo properties.
Here is the [Pull Request](https://github.com/Windows-XAML/Template10/pull/121)

Works with x:Bind Mode=OneWay bindings and probably with a Proxy of the page's DataContext, as the NavigationButtonInfo is not a UIElement and does not appear in the visual tree

**Comment by JerryNixon** [comment]
Okay
