### ISSUE TITLE
Extended splash image too low on phone

### ISSUE THREAD

**Issue by Mrtenz** [Windows-XAML/Template10#1220]
On my Lumia 950 the extended splash screen is too low compared to the normal splash screen. Here is a gif image showing the difference:

<img src="http://g2f.nl/04ldk9h" width="300" />

This happens with the default hamburger template on phone only. On desktop the image is in the correct position.

**Comment by Mrtenz** [comment]
I found the issue. It is caused by `<TranslateTransform Y="0" />` in Splash.xaml. Removing this will render the image in the correct location on both desktop and mobile.

**Comment by JerryNixon** [comment]
I look forward to you pull request, @Mrtenz
