### ISSUE TITLE
Problems with wiki Home page

### ISSUE THREAD

**Issue by pcolmer** [Windows-XAML/Template10#1226]
I've been reviewing the Home page and cannot fix the following points partly because I don't understand what they mean or where they came from in order to fix them.
- The heading "Why are you saying T10 is convention-based?" would seem to stem from an earlier version of the documentation since there is nothing else on this page making any suggestion that T10 is convention based. Not sure what this sub-heading should be changed to in order for it to make more sense to the first-time reader.
- Under the conventions, there are three occurrences of "(and ns)". It isn't clear to me what ns stands for.
- It might be helpful to link to something that explains what a façade pattern is.
- It might be helpful to link to something that explains what a Messenger is or does.
- It might be helpful to link to something that provides a primer (101) to Dependency Injection, plus clarification of where it is used in T10.

**Comment by JerryNixon** [comment]
I can see the lack of clarity. Thank you for your good eye here. 
1. Naw. That's okay.
2. I agree. (and ns) -> (and namespace) meaning that Views go in both the /Views folder and the VIews namespace. Is that unclear? Obviously. Yes. Good point, @pcolmer 
3. I agree
4. I agree
5. I agree

Great. I think we are in agreement that your plans to update the wiki so it is more readable and useful to the next developer is a good idea and a great plan. Thank you again for your contribution.
