### ISSUE TITLE
Issue on KeyboardHelper/KeyboardService

### ISSUE THREAD

**Issue by SimoneBWS** [Windows-XAML/Template10#123]
I have noticed a strange behavior in event handler Window.Current.CoreWindow.Dispatcher.AcceleratorKeyActivated used by KeyboardHelper/ KeyboardService
If you create a view with some TextBox controls, when you press Tab on keyboard, the TabNavigation doesn’t work correctly.
After some hours of debugging, I found that the param on CoreDispatcher_AcceleratorKeyActivated arg.Handle is True… I don’t undestand why… (is a bug???) and when you assign arg.Handle = false, TabNavigation stops working!!!
A simple workaround is:
if (args.VirtualKey == VirtualKey.Tab) return;

at the top of event handler, but I don’t like very much…

@JerryNixon what do you think?

**Comment by JerryNixon** [comment]
Let's solve this. Care to submit a pull req?

**Comment by janabimustafa** [comment]
The tab key is being invoked twice. If you add 

``` csharp
if(args.Handled)
    return;
```

it works normally.

**Comment by SimoneBWS** [comment]
I was testing this solution (although I don't understand why is being invoked twice)... I submit a pul req soon...

**Comment by janabimustafa** [comment]
https://social.msdn.microsoft.com/Forums/en-US/734d6c7a-8da2-48c6-9b3d-fa868b4dfb1d/c-textbox-keydown-triggered-twice-in-metro-applications?forum=winappswithcsharp
It seems to be a bug in the platform that they still haven't fixed.

**Comment by JerryNixon** [comment]
Thank you. This has been resolved.
