### ISSUE TITLE
Template10 1.1.11 - PageHeader back button

### ISSUE THREAD

**Issue by pinoelefante** [Windows-XAML/Template10#1238]
I have registered event on NavigationService.FrameFacade.BackRequested event. It is working fine with SystemNavigation back button and hardware button but when the application is in fullscreen mode and the software back button appear, when clicking on the soft button the event is not triggered (it just goes back, but i don't want it goes back). I tried to register even on SystemNavigationManager.GetForCurrentView().BackRequested but nothing.

**Comment by JerryNixon** [comment]
Thank you for reporting this. If you would like to submit a Pull Request to address it, that would be welcome. Otherwise it might take a bit for me to resolve the issue.
