### ISSUE TITLE
Style change of HamburgerMenu elements in Custom.xaml has no effect (Windows AU SDK)

### ISSUE THREAD

**Issue by jp-weber** [Windows-XAML/Template10#1239]
If I change for example 'NavAreaBackground' in Custom.xaml, it has no effect in the app because in HamburgerPublicMethods.cs the style will be curiously overwritten:

```
this.SetIfNotSet(NavAreaBackgroundProperty, Colors.DimGray.ToSolidColorBrush());
```

With the old Win10 TH2 and TH2 SDK there were no problems.
#1306

**Comment by JerryNixon** [comment]
Good catch @revan1199. Keep researching. I will be out of touch for a few days.

**Comment by jp-weber** [comment]
I tried to unterstand it, it seems that there are a problem with DependencyProperty. The DependencyProperty has the status "UnsetValue", even if it set in Custom.xaml via setter.

The DependencyPropertys at "HamburgerMenu.PublicProperties.xaml" looks right for me, under Win10 TH2 it works nice. Is this a AU Bug?
