### ISSUE TITLE
Inline Hamburger Menu

### ISSUE THREAD

**Issue by vinodshinde** [Windows-XAML/Template10#124]
Is there a way to set the Hamburger menu as Inline for full screen, then as width reduces it becomes CompactInline then finally Overlay.
This is exactly like the Mail app.

**Comment by JerryNixon** [comment]
This feature already exists. 

``` XAML
<x:Double x:Key="WideMinWidth">1200</x:Double>
<Setter Property="VisualStateWideMinWidth" Value="{StaticResource WideMinWidth}" />
```
