### ISSUE TITLE
Back button want is not setting permanent in PageHeader.

### ISSUE THREAD

**Issue by pawanvermadreamorbit** [Windows-XAML/Template10#1241]
Hi Sir,

I am using Template10 Hamburger menu template. In this we have setting page whic set page back button as per setting. But I want to set back button permanent in page header and if I click on logout then  backbutton should be collapsed over login page. Could You please help me this small issue.

**Comment by callummoffat** [comment]
Just remove the XAML markup for the back button location from
SettingsPage.xaml. That will prevent users from reconfiguring it.

On 9/26/16, Pawan Kumar Verma notifications@github.com wrote:

> Hi Sir,
> 
> I am using Template10 Hamburger menu template. In this we have setting page
> whic set page back button as per setting. But I want to set back button
> permanent in page header and if I click on logout then  backbutton should be
> collapsed over login page. Could You please help me this small issue.
> 
> ## 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Windows-XAML/Template10/issues/1241

## 

Thanks,

CJ

**Comment by pawanvermadreamorbit** [comment]
But I want to set it in always page header. I don't want to remove xaml markup.  there is no way to set it permanent in page header? Current I have set UseShellBackButton as false in app . now its working. Apart from this, one Issue is regarding see more button I am using custom icon for see more and want to hide default see more icon. Any way ?

**Comment by dg2k** [comment]
If I understand your question correctly, the **Back** button is set automatically for you when there is a back navigation. But when you land on your login page (I assume that this has a top menu link) you want it not to appear.

In that case, for the login page menu button (corresponding HamburgerButtonInfo control) set the `ClearHistory="True"` in login XAML page so that navigation history is cleared and the **Back** button doesn't show up.

Example:

```
<Controls:HamburgerButtonInfo x:Name="MyLoginPage" x:Uid="Login" ClearHistory="True" PageType="views:LoginPage" ...>
```

**Comment by pawanvermadreamorbit** [comment]
this way is fine if I am using Logout button in primary command then How can I do it.

**Comment by dg2k** [comment]
What's the question?

**Comment by pawanvermadreamorbit** [comment]
controls:PageHeader.PrimaryCommands
                <AppBarButton Name="LogOut" 
                              Click="{x:Bind ViewModel.GotoLoginPage}"
                              ClickMode="Press"
                              Content="Logout"
                              Foreground="White" />
            /controls:PageHeader.PrimaryCommands

I am using Logout button in this way, So how Can do on its click clear the history

**Comment by pawanvermadreamorbit** [comment]
I got answer :) :)  NavigationService.ClearHistory() I can use right ?

**Comment by dg2k** [comment]
I am assuming your Logout button is in HamburgerMenu rather than in PageHeader. Couldn't you move it to HamburgerMenu where it's done for you automatically?

In my opinion, Logout is more suited as a secondary menu in HamburgerMenu (that way the user can reach it from anywhere) and I don't understand why it ends up in the PageHeader.

I was going to add, if you do it in a different way, you may have to do it programmatically but again test this thoroughly for unintended effects. I would seriously consider moving it to HamburgerMenu control and let XAML do the job.

**Comment by pawanvermadreamorbit** [comment]
ok , its fine I have done it. Apart from this there was one issue also regarding elipsis button which on appear automatically when we use PrimaryCommands. I want to hide this elipssis icon and and wanto use custom icon. have any way?

**Comment by dg2k** [comment]
elipsis will be there as long as there is a AppBarButton in PageHeader. Tapping on elipsis will reveal the AppBarButton **caption** (in addition to revealing secondary menus hence why it's still there). No elipsis implies no AppBarButton in PageHeader.

**Comment by callummoffat** [comment]
No, I don't think the ellipsis can be disabled.

On 9/26/16, Pawan Kumar Verma notifications@github.com wrote:

> ok , its fine I have done it. Apart from this there was one issue also
> regarding elipsis button which on appear automatically when we use
> PrimaryCommands. I want to hide this elipssis icon and and wanto use custom
> icon. have any way?
> 
> ## 
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/Windows-XAML/Template10/issues/1241#issuecomment-249499159

## 

Thanks,

CJ

**Comment by pawanvermadreamorbit** [comment]
There should be any way.

**Comment by dg2k** [comment]
Nothing is impossible if you have the time and resources but it's much easier and sensible to use frameworks/tools like T10 as they were intended to be used. Yes, you can tweak here and there on the edge cases (and that's what the community help is for) but for most part, we have to **respect** how the framework is intended to be used.

Or you can re-write T10 as you like to create your own (why I say nothing is impossible) but pause and think before you do that.

**Comment by pawanvermadreamorbit** [comment]
if I use Appbar in that case I am able to hide the elipssis button with the following lines of code.
 <Style x:Key="EllipsisButton" TargetType="Button">
                <Setter Property="Width" Value="0" />
            </Style>

But this one is not working for template10 I am not getting why.

**Comment by callummoffat** [comment]
Because the PageHeader is not an AppBar - T10's creators decided that
the ellipsis button was useful in a high enough % of cases to warrant
making it non-toggleable. You happen to be one of that small % who
find that counter-productive.

On 9/26/16, Pawan Kumar Verma notifications@github.com wrote:

> if I use Appbar in that case I am able to hide the elipssis button with the
> following lines of code.
>  <Style x:Key="EllipsisButton" TargetType="Button">
>                 <Setter Property="Width" Value="0" />
>             </Style>
> 
> But this one is not working for template10 I am not getting why.
> 
> ## 
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/Windows-XAML/Template10/issues/1241#issuecomment-249503091

## 

Thanks,

CJ

**Comment by dg2k** [comment]
@pawanvermadreamorbit  This is a T10 anti-pattern if I can call it that.  Not sensible to seek help to _undo_ what T10 and the host platform _do_ for us.  Where disabling a feature is considered sensible, T10 (or platform) usually provide programmable options. In this case, the `...` button has a job to do -- to reveal caption and staying put.

If you move your login button to HamburgerMenu, chances are you may not have the elipsis (assuming logout is your only AppBarButton) so look for better alternative than going against T10 design.

Please re-read my comment above.

**Comment by pawanvermadreamorbit** [comment]
if I enhance the pageheader content then  its possible or not ?

**Comment by callummoffat** [comment]
Did we not spell it out for you? No. It isn't possible, and
considering the important function it serves, it shouldn't be
possible.

On 9/26/16, Pawan Kumar Verma notifications@github.com wrote:

> if I enhance the pageheader content then  its possible or not ?
> 
> ## 
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/Windows-XAML/Template10/issues/1241#issuecomment-249505055

## 

Thanks,

CJ

**Comment by pawanvermadreamorbit** [comment]
I am handling it with following lines of code.
 controls:PageHeader.Content
                <Grid HorizontalAlignment="Stretch" Background="Transparent">
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition Width="Auto" />
                        <ColumnDefinition Width="50" />
                    </Grid.ColumnDefinitions>
                    <TextBlock Grid.Column="0"
                               HorizontalAlignment="Stretch"
                               VerticalAlignment="Center"
                               FontFamily="Helvetica"
                               FontWeight="SemiBold"
                               Foreground="White"
                               Text="Select Database" />
                    <Button Grid.Column="1"
                            Background="Transparent"
                            BorderThickness="0"
                            Padding="0">
                        <Image Margin="5"
                               Source="ms-appx:///Assets/icon/more.png"
                               Stretch="None" />
                        <Button.Flyout>
                            <MenuFlyout>
                                <MenuFlyoutItem HorizontalAlignment="Center"
                                                FlowDirection="LeftToRight"
                                                Padding="80,8,80,8"
                                                Text="Refresh">
                                    <MenuFlyoutItem.Template>
                                        <ControlTemplate TargetType="MenuFlyoutItem">
                                            <StackPanel Orientation="Horizontal">
                                                <TextBlock Padding="{TemplateBinding Padding}" Text="{TemplateBinding Text}" />
                                            </StackPanel>
                                        </ControlTemplate>
                                    </MenuFlyoutItem.Template>
                                </MenuFlyoutItem>
                                <MenuFlyoutSeparator Margin="-15,0,0,0"
                                                     Background="#375eab"
                                                     BorderThickness="3" />
                                <MenuFlyoutItem x:Name="RoutesInProgress"
                                                HorizontalAlignment="Center"
                                                FlowDirection="LeftToRight"
                                                Padding="80,8,80,8"
                                                Text="Routes In Progress">
                                    <MenuFlyoutItem.Template>
                                        <ControlTemplate TargetType="MenuFlyoutItem">
                                            <StackPanel Orientation="Horizontal">
                                                <TextBlock Padding="{TemplateBinding Padding}" Text="{TemplateBinding Text}" />
                                            </StackPanel>
                                        </ControlTemplate>
                                    </MenuFlyoutItem.Template>
                                </MenuFlyoutItem>
                                <MenuFlyoutSeparator Margin="-15,0,0,0"
                                                     Background="#375eab"
                                                     BorderThickness="3" />
                                <MenuFlyoutItem x:Name="LogOut"
                                                HorizontalAlignment="Center"
                                                FlowDirection="LeftToRight"
                                                Padding="80,8,80,8"
                                                Text="Logout" />
                            </MenuFlyout>
                        </Button.Flyout>
                    </Button>
                </Grid>

```
        </controls:PageHeader.Content>
```

**Comment by callummoffat** [comment]
This is why T10 provides a default implementation which is perfect for
(almost) anything.

You've just blown the complexity factor of your code out of the
water... to remove ONE button (which is actually pretty useful).
Wouldn't it have been simpler to do it in a standard fashion using
PrimaryCommands?

On 9/26/16, Pawan Kumar Verma notifications@github.com wrote:

> I am handling it with following lines of code.
>  controls:PageHeader.Content
>                 <Grid HorizontalAlignment="Stretch"
> Background="Transparent">
>                     <Grid.ColumnDefinitions>
>                         <ColumnDefinition Width="Auto" />
>                         <ColumnDefinition Width="50" />
>                     </Grid.ColumnDefinitions>
>                     <TextBlock Grid.Column="0"
>                                HorizontalAlignment="Stretch"
>                                VerticalAlignment="Center"
>                                FontFamily="Helvetica"
>                                FontWeight="SemiBold"
>                                Foreground="White"
>                                Text="Select Database" />
>                     <Button Grid.Column="1"
>                             Background="Transparent"
>                             BorderThickness="0"
>                             Padding="0">
>                         <Image Margin="5"
>                                Source="ms-appx:///Assets/icon/more.png"
>                                Stretch="None" />
>                         <Button.Flyout>
>                             <MenuFlyout>
>                                 <MenuFlyoutItem
> HorizontalAlignment="Center"
>                                                 FlowDirection="LeftToRight"
>                                                 Padding="80,8,80,8"
>                                                 Text="Refresh">
>                                     <MenuFlyoutItem.Template>
>                                         <ControlTemplate
> TargetType="MenuFlyoutItem">
>                                             <StackPanel
> Orientation="Horizontal">
>                                                 <TextBlock
> Padding="{TemplateBinding Padding}" Text="{TemplateBinding Text}" />
>                                             </StackPanel>
>                                         </ControlTemplate>
>                                     </MenuFlyoutItem.Template>
>                                 </MenuFlyoutItem>
>                                 <MenuFlyoutSeparator Margin="-15,0,0,0"
>                                                      Background="#375eab"
>                                                      BorderThickness="3" />
>                                 <MenuFlyoutItem x:Name="RoutesInProgress"
> 
> HorizontalAlignment="Center"
>                                                 FlowDirection="LeftToRight"
>                                                 Padding="80,8,80,8"
>                                                 Text="Routes In Progress">
>                                     <MenuFlyoutItem.Template>
>                                         <ControlTemplate
> TargetType="MenuFlyoutItem">
>                                             <StackPanel
> Orientation="Horizontal">
>                                                 <TextBlock
> Padding="{TemplateBinding Padding}" Text="{TemplateBinding Text}" />
>                                             </StackPanel>
>                                         </ControlTemplate>
>                                     </MenuFlyoutItem.Template>
>                                 </MenuFlyoutItem>
>                                 <MenuFlyoutSeparator Margin="-15,0,0,0"
>                                                      Background="#375eab"
>                                                      BorderThickness="3" />
>                                 <MenuFlyoutItem x:Name="LogOut"
> 
> HorizontalAlignment="Center"
>                                                 FlowDirection="LeftToRight"
>                                                 Padding="80,8,80,8"
>                                                 Text="Logout" />
>                             </MenuFlyout>
>                         </Button.Flyout>
>                     </Button>
>                 </Grid>
> 
> ```
>         </controls:PageHeader.Content>
> ```
> 
> ## 
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/Windows-XAML/Template10/issues/1241#issuecomment-249505908

## 

Thanks,

CJ

**Comment by JerryNixon** [comment]
If the default implementation is not right for you, just use CommandBar and add your functionality to it. You can even copy our starter code if you want from source.
