### ISSUE TITLE
OnNavigatedToAsync problem

### ISSUE THREAD

**Issue by JurajPupak** [Windows-XAML/Template10#1243]
If I call `BootStrapper.Current.NavigationService.Navigate(Pages.ContentPage, result.Nick);` so OnNavigatedToAsync method in ContentViewModel is called twice, but I call Navigate only one time.

`public override Task OnNavigatedToAsync(object parameter, NavigationMode mode, IDictionary<string, object> state)
        {
            Nickname = parameter.ToString();
            BootStrapper.Current.NavigationService.ClearHistory();
            return Task.CompletedTask;
        }`

**Comment by JerryNixon** [comment]
If you create a new MINIMAL app and set a Debug.Write("Hello"); in the OnNavigatedTo of the view-model, does it write out once or twice? If only once, then something is special about your implementation. ClearHistory() should not do anything to cause this, I think. Maybe if you comment that out, does it change the behavior?

**Comment by JurajPupak** [comment]
i think that i found the problem. it was my fault :/.

Dňa 27.9.2016 17:31 používateľ "Jerry Nixon" notifications@github.com
napísal:
