### ISSUE TITLE
Cortana in Template 10

### ISSUE THREAD

**Issue by James-Toalu** [Windows-XAML/Template10#1246]
I have a question regarding the Cortana activation in my app.
When I run the app in the Debug mode (utilizing Visual Studio), the app will be opened by Cortana and the intended page of my app will be shown correctly.
When I run the app in the Release mode (without utilizing Visual Studio), the app will be opened by Cortana up to the Splash Screen and then the app crashed (the intended page is not rendered).
Do you know what causing the problem?
Thank you in advance for your help.

**Comment by JerryNixon** [comment]
Gonna need some code. Your start method and your main page. Perhaps you could share at least the error message?

**Comment by James-Toalu** [comment]
Looks like it failed in the **if (mode.Equals("voice"))** to be exactly the value of mode in **var mode = properties.First(x => x.Key.Equals("commandMode")).Value;** because the execution took the **else {   /\* not okay to speak */** path. Please see the attached screenshots.

Here is the code:

``` csharp
public override async Task OnStartAsync(StartKind startKind, IActivatedEventArgs args)
{
    if (args.Kind == ActivationKind.VoiceCommand)
    {
        var e = args as VoiceCommandActivatedEventArgs;
        if (e != null)
        {
            var result = e.Result;
            var properties = result.SemanticInterpretation.Properties
                .ToDictionary(x => x.Key, x => x.Value);

            var command = result.RulePath.First();
            if (command.Equals("showSection"))
            {
                // get spoken text 
                var text = properties.First(x => x.Key.Equals("textPhrase")).Value[0];

                // remember to handle response appropriately 
                var mode = properties.First(x => x.Key.Equals("commandMode")).Value;
                if (mode.Equals("voice"))
                {
                    /* okay to speak */
                    switch (command)
                    {
                        case "showSection":
                            if (text.Contains("Video"))
                            {
                                NavigationService.Navigate(typeof(Views.SettingsPage));
                            }
                            else if (text.Contains("Photo"))
                            {
                                NavigationService.Navigate(typeof(Views.CortanaPage));
                            }
                            break;

                        // Cases for other voice commands.

                        default:
                            // There is no match for the voice command name.

                            break;
                    }
                }
                else
                {
                    /* not okay to speak */
                    switch (command)
                    {
                        case "showSection":
                            if (text.Contains("Video"))
                            {
                                NavigationService.Navigate(typeof(Views.SettingsPage));
                            }
                            else if (text.Contains("Photo"))
                            {
                                NavigationService.Navigate(typeof(Views.CortanaPage));
                            }
                            break;

                        // Cases for other voice commands.

                        default:
                            // There is no match for the voice command name.

                            break;
                    }
                }

                await Task.Delay(5000);
            }
            else
            { /* unexpected command */
                await Task.Delay(5000);
                NavigationService.Navigate(typeof(Views.CortanaPage));
            }
        }
        else
        {
            await Task.Delay(5000);
            NavigationService.Navigate(typeof(Views.CortanaPage));
        }
        await Task.CompletedTask;
    }
    else
    {
        // long-running startup tasks go here
        await Task.Delay(5000);

        NavigationService.Navigate(typeof(Views.MainPage));
        await Task.CompletedTask;
    }
}
```

![command-mode](https://cloud.githubusercontent.com/assets/22484317/19005981/4c03cad2-8712-11e6-88dd-06533309d2db.png)
![cortana-open](https://cloud.githubusercontent.com/assets/22484317/19005984/4c08be34-8712-11e6-80ed-948191cf646b.png)
![mode-value](https://cloud.githubusercontent.com/assets/22484317/19005980/4c0026ca-8712-11e6-9664-bd56ab2c2ca6.png)
![not-okay-to-speak](https://cloud.githubusercontent.com/assets/22484317/19005982/4c065c52-8712-11e6-8ce3-96c19ed1c7d6.png)
![voice-commnd](https://cloud.githubusercontent.com/assets/22484317/19005983/4c06c840-8712-11e6-8fc5-64a8de9428d9.png)

`

**Comment by JerryNixon** [comment]
I may not completely understand. You may need to use `StartKind`. See it there in the args of the method? It will tell you if your application is launching, which means starting from scratch, or activating, which means already started just re-starting because of some outside caller. That might only be part of the situation, however. You may also need to assume a mode if none is passed, using the `.?` operator or `FirstOrDefault()` to ensure you don't get a null exception. That being said, @James-Toalu, I can't explain why mode would ever-ever-ever be null. Template 10 is certainly not changing Cortana's behavior on you, so let that ease your mind, but it is a mystery to me that I would assume you will solve in the next few cycles and I hope you share the solution here with us.

**Comment by James-Toalu** [comment]
Hi @JerryNixon! Sorry for the delay in responding to you. Anyway, I am back on working to solve this problem now. I opened the solution (the project) and finding three errors when trying to debug it. Is there any changing on Template 10 (especially the v1.1.12)? I encountered a problem in 

`private global::Windows.UI.Xaml.Markup.IXamlType CreateXamlType(int typeIndex)`

to be exactly in

`case 14:   //  Template10.Common.BootStrapper.States`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;           `userType = new global::Scattered_Seed_Template_10.Scattered_Seed_Template_10_XamlTypeInfo.XamlUserType(this, typeName, type, GetXamlTypeByName("System.Enum"));`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          `userType.AddEnumValue("Starting", global::Template10.Common.BootStrapper.States.Starting);`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          `userType.AddEnumValue("Splashing", global::Template10.Common.BootStrapper.States.Splashing);`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          `userType.AddEnumValue("ShowingContent", global::Template10.Common.BootStrapper.States.ShowingContent);`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          `xamlType = userType;`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          `break;`

I noticed the three values above (Starting, Splashing, and ShowingContent) are not listed in

`public enum States`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        `{`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            `None = 0,`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            `Running = 1,`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            `BeforeInit = 2,`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            `AfterInit = 3,`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            `BeforeLaunch = 4,`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            `AfterLaunch = 5,`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            `BeforeActivate = 6,`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            `AfterActivate = 7,`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            `BeforeStart = 8,`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            `AfterStart = 9`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        `}`

What do I need to modify, so the project can be compiled? Please see the image below for more information.

![error-list-template-10](https://cloud.githubusercontent.com/assets/22484317/19699475/54d14f8c-9aa8-11e6-824d-a9c09c4c6b2c.png)
