### ISSUE TITLE
x:Bind with ObservableDictionary won't update the view

### ISSUE THREAD

**Issue by rpedretti** [Windows-XAML/Template10#1248]
As described in https://msdn.microsoft.com/en-us/windows/uwp/xaml-platform/x-bind-markup-extension an implementation of IObservableMap should work with x:Bind, but dont :(

I've created a repo at https://github.com/rpedretti/Test.ObservableDictionariCompileBind to reproduce this issue.

BUT I'm confident that this bug is more related to the compiler than with T10.

I looked into the MainPage.g.cs and foud the binding itself but as I'm not so fluent in the generated code for binding and could not find any listeners to the MapChanged event.

**Comment by JerryNixon** [comment]
Okay. What should we do with this? If it is not Template 10, do we have any options?

**Comment by rpedretti** [comment]
Not really, but that's why I asked in twitter where to report it. It might be a Roslyn problem...i don't know. If only I knew who is responsible for this I could redirect to the right place.
