### ISSUE TITLE
System.AccessViolationException when setting ModalDialog.ModalTransitions

### ISSUE THREAD

**Issue by niels9001** [Windows-XAML/Template10#1252]
I keep getting weird exceptions when I try to set a transition in my XAML:

> An unhandled exception of type 'System.AccessViolationException' occurred in Huetro.exe
> 
> Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

My XAML:

` <Controls:ModalDialog x:Name="BusyModal" Grid.Row="1" CanBackButtonDismiss="True" ModalBackground="#CC2E2E2E">

```
        <Controls:ModalDialog.ModalContent>
            <Grid Background="#FF2E2E2E" MaxWidth="500" MaxHeight="610">
                <local:ColorPicker x:Name="ColorPickert" />
                <Button x:Name="CloseBtn" Width="30"  Height="30" HorizontalAlignment="Right" VerticalAlignment="Top" Click="CloseBtn_Click" Style="{StaticResource DialogCloseButtonStyle}" />

            </Grid>

        </Controls:ModalDialog.ModalContent>
        <Controls:ModalDialog.ModalTransitions>
            <PopupThemeTransition />

        </Controls:ModalDialog.ModalTransitions>

    </Controls:ModalDialog>`
```

**Comment by JerryNixon** [comment]
The validation sample does this successfully.

**Comment by niels9001** [comment]
Can you link to this @JerryNixon? I'm not seeing any samples with the Controls:ModalDialog.ModalTransitions enabled.

Am I using it in the right way (see code above)?

**Comment by mvermef** [comment]
```
        <Controls:ModalDialog.ModalTransitions>
            <PopupThemeTransition />

        </Controls:ModalDialog.ModalTransitions>
```

needs to be this even though ModalTransitions inherits TransitionCollections

```

        <Controls:ModalDialog.ModalTransitions>
          <TransitionCollections>      <!-- Required -->
            <PopupThemeTransition />
          </TransitionCollections>      <!-- Required -->
        </Controls:ModalDialog.ModalTransitions>       
```
