### ISSUE TITLE
Suddenly getting Xaml Internal Error error WMC9999: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ginomessmer** [Windows-XAML/Template10#1253]
I continued started working on one of my apps using Template10 with some changes in T10 settings service and reverted them back to T10's default, however, Visual Studio throws an exception without any further info.

```
1>------ Build started: Project: ****, Configuration: Debug x86 ------
1>C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\8.2\Microsoft.Windows.UI.Xaml.Common.targets(264,5): Xaml Internal Error error WMC9999: Object reference not set to an instance of an object.
========== Build: 0 succeeded, 1 failed, 3 up-to-date, 0 skipped ==========
========== Deploy: 0 succeeded, 0 failed, 0 skipped ==========
```

That's all I got, no further info. But when I open up `SettingsPage.xaml` it throws the following:

`The name "SettingsPageViewModel" does not exist in the namespace "using:****.Universal.ViewModels".`

Although it exists in my project and is referenced:

```
...
xmlns:vm="using:****.Universal.ViewModels" mc:Ignorable="d">

<Page.DataContext>
    <vm:SettingsPageViewModel />
</Page.DataContext>
```

**Comment by ginomessmer** [comment]
I reverted all minor changes I made in Git and it works somehow. I don't have a clue why Visual Studio didn't wanted to compile my solution, probably some caching issue.

**Comment by rubgithub** [comment]
This issue can be replicated referencing `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Xaml.dll`

http://stackoverflow.com/questions/39548289/xaml-internal-error-error-wmc9999/40199067#40199067

**Comment by mvermef** [comment]
You a static class reference were you shouldn't, probably a binding
