### ISSUE TITLE
Landscape issue on Windows 10 Mobile

### ISSUE THREAD

**Issue by myokeeh** [Windows-XAML/Template10#1255]
This is on a Lumia 950. In both landscape orientations, there's a blank area.

Blank white area on the left:
![wp_ss_20161002_0001](https://cloud.githubusercontent.com/assets/3663297/19024531/6d784306-88ba-11e6-920e-3d8c9f5f5799.png)
Blank white area on the right:
![wp_ss_20161002_0002](https://cloud.githubusercontent.com/assets/3663297/19024532/6d7917b8-88ba-11e6-9a80-72dd6b27e470.png)

**Comment by Hector47** [comment]
I have the same issue even in Portrait (Lumia 830, Template10 1.1.11) :
![wp_ss_20161003_0004](https://cloud.githubusercontent.com/assets/394671/19030706/e0c86ea4-894f-11e6-8dea-e7bf0e8aa94a.png)

If I put my phone in Light mode I can see the status bar
![wp_ss_20161003_0001](https://cloud.githubusercontent.com/assets/394671/19030700/d6bb4508-894f-11e6-8230-2a529e92c6d2.png)

**Comment by Hector47** [comment]
Duplicate of #710

**Comment by mvermef** [comment]
it is indeed a duplicate.... just have to set the background opacity.

**Comment by myokeeh** [comment]
Thanks!
