### ISSUE TITLE
Visual Studio 15 Preview

### ISSUE THREAD

**Issue by Weasy666** [Windows-XAML/Template10#1258]
It would be great if the Template10 would be installable in the Visual Studio 15 Preview.
Right now it doesn't even show up in the `Extensions and Updates` and downloading and installing it from the [Visual Studio Gallery](https://visualstudiogallery.msdn.microsoft.com/60bb885a-44e9-4cbf-a380-270803b3f6e5)  also doesn't work.

**Comment by JerryNixon** [comment]
Yeah. You have to create it in 2015 and move to 15. When RTM is here, we'll fix it @Weasy666. What you feel is what I feel. Thanks for your feedback.
