### ISSUE TITLE
Missing Custom.Dark and Light xaml from Styles

### ISSUE THREAD

**Issue by MichaelPetrinolis** [Windows-XAML/Template10#126]
In Minimal project the dark and light styles are missing from source

**Comment by RomeoPavoni** [comment]
it seems i cannot compile due to this, it's only me?

**Comment by MichaelPetrinolis** [comment]
https://github.com/Windows-XAML/Template10/issues/130 is opened for the same reason.

**Comment by JerryNixon** [comment]
This is a duplicate, but please verify the current commit works. I fixed this.
