### ISSUE TITLE
BootStrapper.<HandleResuming>d__99.MoveNext() NullReferenceException

### ISSUE THREAD

**Issue by dougmikus** [Windows-XAML/Template10#1260]
I've been getting the following exception on a tablet (I have yet to see this on a laptop):

System.NullReferenceException: Object reference not set to an instance of an object.
   at Template10.Common.BootStrapper.<HandleResuming>d__99.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()

This happens if the app was running and then is minimized for a long period of time or the tablet screen is locked for a long period (both approx. 30 minutes). It doesn't always happen which has made it difficult to track.

**Comment by JerryNixon** [comment]
Interesting. So when an app is minimized it is suspended. So the error has something to do with resuming, I would surmise, though I cannot be sure. Will you keep watching to see a pattern?

**Comment by dougmikus** [comment]
I've been watching this for months but finally got enough detail to start heading in a direction (here I am).  The main problem has been its been termination my app which no one likes to see.  I suspect something is getting GC'd or corrupt after a long period of suspension.

**Comment by dougmikus** [comment]
I think I found the issue.  Following a subsequent release I was having more issues when resuming, specifically if the user closed the app (X press) then resumed within the 10 second windows (not related to the new suspension updates). The app would start to become visible but then abort.  After much debugging it appears to come down to the "DebugWrite(caller: nameof(Resuming));" statement at the beginning of the method HandleResuming().  While the name of "Resuming" is defined within Windows.UI.Xaml.Application (the base class) I'm speculating that 'nameof' cannot find it within its context.  This in turn aborts out of HandleResuming() and the app just terminates. This is an intermittent issue but easily reproduced.

The fix appears to be simple; just change the offending line to DebugWrite(caller: nameof(HandleResuming));" (the method name).  I have yet to see the resume abort with this update.

**Comment by schuettecarsten** [comment]
I do have a different crash here:

`McgInterop.McgHelpers.ThrowFailed
Der RPC-Server ist nicht verfügbar. (Excep_FromHResult 0x800706BA)`

Callstack:

`McgInterop.McgHelpers.ThrowFailed(Int32 hr, RuntimeTypeHandle typeHnd) in c:\windows\ServiceProfiles\NetworkService\appdata\local\packages\appcompile-20161115-145537-11044\ac\Temp\Ilc121784463\Maxdome.Uap10.McgInterop\Helpers.g.cs at 6376:10
McgInterop.ComCallHelpers.ComCall__HRESULT($__ComObject __this, RuntimeTypeHandle __typeHnd, Int32 __targetIndex, Void* arg0) in c:\windows\ServiceProfiles\NetworkService\appdata\local\packages\appcompile-20161115-145537-11044\ac\Temp\Ilc121784463\Uap10.McgInterop\SharedStubs.g.cs at 113:5
McgInterop.ForwardComSharedStubs.Func_bool__<System.__Canon>(Void* InstParam, $__ComObject __this, Int32 __targetIndex) in c:\windows\ServiceProfiles\NetworkService\appdata\local\packages\appcompile-20161115-145537-11044\ac\Temp\Ilc121784463\Uap10.McgInterop\SharedStubs.g.cs at 5039:4
Windows.ApplicationModel.Activation.LaunchActivatedEventArgs.get_PrelaunchActivated() in c:\windows\ServiceProfiles\NetworkService\appdata\local\packages\appcompile-20161115-145537-11044\ac\Temp\Ilc121784463\Uap10.McgInterop\SafeTypes.g.cs at 5255:4
Template10.Common.BootStrapper.<HandleResuming>d__99.MoveNext() in E:\Build3\71cdfcbed6e20846\3rdParty\Template10\Template10 (Library)\Common\BootStrapper.cs at 678:13`

I am not using the most recent version of Template10 and for compatibility reasons, I cannot upgrade to latest commit, but I can see that this is the same location. Will try if modifying the DebugWrite line helps.
