### ISSUE TITLE
Support for master/detail pattern in T10 HamburgerMenu

### ISSUE THREAD

**Issue by callummoffat** [Windows-XAML/Template10#1264]
I'd like to see proper support for the master/detail pattern implemented in the T10 HamburgerMenu. By that, I mean having data models appear as items in the hamburger. I realize that this can already be done (I've implemented it myself), but at present, it is a problem with a kludgy solution. This functionality should be available by default, in my opinion. @JerryNixon, if you'd like to see my implementation, you can find it here:

https://github.com/callummoffat/Petrolhead/blob/master/Petrolhead.UWP/Views/Shell.xaml.cs

**Comment by JerryNixon** [comment]
Yeah, that's why we created Literal. Not today @callummoffat, too many other priorities.
