### ISSUE TITLE
MediaPlayerElement does not exist.

### ISSUE THREAD

**Issue by syaifulnizamyahya** [Windows-XAML/Template10#1265]
If I create new project without using Template10, I can use MediaPlayerElement. But if I use Template10, MediaPlayerElement is missing. I already add the required namespace and resources, but MediaPlayerElement is still missing.

How do I get MediaPlayerElement?

**Comment by darenm** [comment]
As I am sure you realize, T10 does not change what is available in the platform. MediaPlayerElement was introduced in 10.0.14393.0 so ensure you have set the MAX & MIN version of your project to at least 14393.

**Comment by JerryNixon** [comment]
Great point @darenm

**Comment by syaifulnizamyahya** [comment]
It was a problem on my side. I need to update my development rig. MediaPlayerElement only exist on newer version on windows.

Thanks and sorry for the hassle. T10 is an excellent lib.
