### ISSUE TITLE
After navigation back and forth from main to detail page, Dispatcher gets set to null

### ISSUE THREAD

**Issue by krisgustafson** [Windows-XAML/Template10#1266]
I'm learning UWA with Template10 and I started a minimal Template10 test project in VS2015 (latest) Community edition. In the VM for the DetailPage I access a model that creates objects on a non-UI thread. To add those items into my UI-thread ObservableCollection, I use Dispatcher.Dispatch(() => {//add to UI-thread collection});. This so far works as I want. Each time I navigate to the DetailPage, the model date refreshes and the ObservableCollection (on the UI-thread) is restocked with the "new" model data. The data shows correctly in the DetailPage.xaml.
Here's the problem:
If I repeatedly navigate from Main to Detail and back to Main about five times, for whatever reason, the Dispatcher for the DetailPage VM  (somewhere, not directly from my code) gets set to "null". With a null Dispatcher I cannot update the ObservableCollection. Since this is just a learning project, this is not critical, but it does concern me, especially if I'm doing something wrong. Any ideas why the Dispatcher gets corrupted just hitting the "back" and "next" buttons in succession?

**Comment by JerryNixon** [comment]
I have never seen that. I think the fix is likely to be changing the view-model so that it is no longer getting the dispatcher injected but instead using windowWrapper to get the current for view.

**Comment by krisgustafson** [comment]
Thanks very much for the reply. I'll try that, but it may be some time before I get to it. I'm starting a new job next week and I'll need time to settle in.

Date: Fri, 21 Oct 2016 07:34:23 -0700
