### ISSUE TITLE
How to have a Modal dialogue covering only a part of the window

### ISSUE THREAD

**Issue by LostLogic** [Windows-XAML/Template10#1267]
Hi.
I'm sure this is blatantly obvious on how to do, but I'm stuck.

How can I have a modal dialog cover only a part of the screen, leaving everything else interactable? 
In my case, I am trying to replicate the same effect that the Groove app use for their player control, that leaves a persistent modal window on top of everything stuck to the bottom of the window.

**Comment by milkinllc** [comment]
You need to put your content that needs to be blocked inside ModalDilaog.Content control tag and put ModalDialog control itself wherever that content is meant to be placed. The rest of the content, which is outside that control, will be available for interaction.

**Comment by LostLogic** [comment]
So, creating a ModalControl, like the Busy control included in the Hamburger template for instance will not be possible to have a limited height for instance? I need to call it from within a page?
Basically, I've replicated the busy page, but with a RelativePanel with a height of 68 and bottom alignment. I tried wrapping the content within the UserControl in a ModalDialog where the RelativePanel was placed within ModalDialog.Content, and calling it like this in App.xaml.cs:

```
public override async Task OnStartAsync(StartKind startKind, IActivatedEventArgs args)
        {
            // long-running startup tasks go here
            // await Task.Delay(5000);

            NavigationService.Navigate(typeof(MainPage));
            MyBottomModal.SetVisible(true);
            await Task.CompletedTask;
        }
```

. Am I just being daft?

**Comment by darenm** [comment]
I'm struggling a little with your concept here. Firstly - modals are "supposed" to be block interaction with the main Window - that's what modality is - [Modal Definition](https://en.wikipedia.org/wiki/Modal_window)

Re-reading what you are asking for - I think all you want is a CommandBar with a transparent background docked to the bottom of your view...

![image](https://cloud.githubusercontent.com/assets/1674843/19281491/c8776df6-8fa7-11e6-994a-3b47a389fdb1.png)

``` XAML
<Page x:Class="NavigationCacheDemo.Page1"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:controls="using:NavigationCacheDemo.Controls"
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
      xmlns:local="using:NavigationCacheDemo"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
      xmlns:viewModels="using:NavigationCacheDemo.ViewModels"
      NavigationCacheMode="Required"
      RequestedTheme="Dark"
      mc:Ignorable="d">
    <Page.DataContext>
        <viewModels:PostersViewModel x:Name="ViewModel" />
    </Page.DataContext>

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <Grid.RowDefinitions>
            <RowDefinition Height="60" />
            <RowDefinition />
        </Grid.RowDefinitions>
        <Image x:Name="BackgroundImage"
               Grid.RowSpan="2"
               Source="../Assets/blue-star-background-wallpaper-3.jpg"
               Stretch="UniformToFill" />

        <controls:NavigationControl HorizontalAlignment="Left"
                                    VerticalAlignment="Top"
                                    NavClick="NavigationControl_OnNavClick" />

        <TextBlock Grid.Row="0"
                   HorizontalAlignment="Center"
                   VerticalAlignment="Bottom"
                   Style="{StaticResource TitleTextBlockStyle}"
                   Text="{x:Bind ViewModel.Title}" />



        <GridView x:Name="Posters"
                  Grid.Row="1"
                  Margin="200,48, 200, 0"
                  ItemsSource="{x:Bind ViewModel.Posters, Mode=OneWay}">
            <GridView.Resources>
                <Style x:Key="PosterStyle" TargetType="Image">
                    <Setter Property="Stretch" Value="UniformToFill" />
                    <Setter Property="Width" Value="300" />
                    <Setter Property="Margin" Value="12" />
                </Style>
            </GridView.Resources>
            <GridView.ItemTemplate>
                <DataTemplate x:DataType="viewModels:Poster">
                    <Rectangle Width="300"
                               Height="400"
                               Margin="12"
                               Fill="LightGray" />
                </DataTemplate>
            </GridView.ItemTemplate>

        </GridView>

        <!-- Here's your overlay -->
        <CommandBar Background="#330000FF"
                    Grid.Row="1"
                    VerticalAlignment="Bottom">
            <AppBarButton Icon="Previous"/>
            <AppBarButton Icon="Play"/>
            <AppBarButton Icon="Next"/>
        </CommandBar>

    </Grid>
</Page>
```

**Comment by mvermef** [comment]
Look at the Search sample and specifically at the LoginPart/SearchPart, they use events from parts in conjunction with Viewmodel. The parts themselves do have viewmodals to react show open or close modal which are attached to the part with in call content of the Modal, structure to your needs. As the other poster indicated Modal may not be what is best.

**Comment by LostLogic** [comment]
Thanks guys! This helped a lot!
