### ISSUE TITLE
NavigationService and VOIP app

### ISSUE THREAD

**Issue by JurajPupak** [Windows-XAML/Template10#1268]
Hi there,
here is my problem:
I have VOIP, which has SocketActivityTrigger backgroundtask. When app is closed and someone is calling to me, so backgroundtask is fired and system call screen is displayed. After I accept the call, the app is launched and OnStartAsync method is invoked. Here I want to navigate to my call page. But NavigationService is null and the app crash. I don't know, why NavigationService is null. Is it a bug?

**EDIT:**
I found something in Boostrapper. When you have backgroundtask, which is in process (single process model) and OnBackgroundActivated is fired, so app process is activated (XY.exe). And when I accept incomming call, it crash because of non-existing NavigationService. Here is the logic in Bootstrapper:

`if (e.PreviousExecutionState != ApplicationExecutionState.Running)
            {
                try
                {
                    await InitializeFrameAsync(e);
                }
                catch (Exception)
                {
                    // nothing
                }
            }`
So you don't initialize frame, because previous state was running (backgroundtask activated the app process). I think, you didn't try this case, but the logic is not applicable in this situation.

**Comment by JurajPupak** [comment]
Guys, no one?

**Comment by JerryNixon** [comment]
I'm starting to wonder if NavigationService property is called and the getter detects null, if it should automatically call InitFrame for just such use cases.

**Comment by JerryNixon** [comment]
Of course that is not possible because InitFrame is async and you can't reliably call Async from a property getter. But the concept is still probably close to what we should finally do here.
