### ISSUE TITLE
Hamburger Menu Navigate with parameter

### ISSUE THREAD

**Issue by jerinjohnk** [Windows-XAML/Template10#1271]
On HamburgerButtonInfo Tap I want to navigate to a new page along with parameters but I am not able to access SessionState for the complex parameter that I am supposed to store and access using its key on navigated new page.
On **Shell.xaml.cs** I am able to access the **INavigationService** but I want **IStateItems** also to be passed from **App.xaml** so that I can access it on Shell.xaml.cs to make my code work

`public void GotoByBrand()
        {
            SearchFilter sfParam = new SearchFilter { SelectedOption = "ByBrand", SortBy = ViewHelper.sortPopularity };
            if (tempSessionState.ContainsKey(ViewHelper.NavList.ToSearchedCar.ToString()))
                tempSessionState.Remove(ViewHelper.NavList.ToSearchedCar.ToString());
            tempSessionState.Add(ViewHelper.NavList.ToSearchedCar.ToString(), sfParam);
            tempNav.Navigate(typeof(Views.NewCar.SearchedCar), ViewHelper.NavList.ToSearchedCar.ToString());
        }`

Where tempSessionState will hold a reference to SessionState.

Secondly I am building an app similar Master Detail Mail App and even though I have specified inside my submenuitem tap to **clear history** yet its not working will I have to add code to clear all backstack manually inside my tapped event.

`<Controls:HamburgerButtonInfo x:Name="MyHamburgerSearchCarsByBrandButtonInfo" Visibility="Collapsed"   ClearHistory="True" Tapped="GotoByBrand">
                    <StackPanel Orientation="Vertical" Background="{StaticResource Dark11}">                        
                        <TextBlock Margin="52,4,0,0"
                               VerticalAlignment="Center"
                               x:Uid="SearchCarsByBrand" />
                        <Rectangle Margin="52,4,0,4" Style="{StaticResource CDRectangleDarkGray}"/>
                    </StackPanel>
                </Controls:HamburgerButtonInfo>`

As just using `PageType="views:SearchedCar"` wont let me pass a navigation parameter.

**Comment by mvermef** [comment]
Ok I think I understand your use case...  

1) don't set the pagetype on the control - you don't need it in this case.
2) does each control use the same event handler for the tapped event? if so generalize the method as necessary to meet your needs.

  Lastly you can access Navigation from with in the shell by simply to going to the codebehind and using `MyHamburgerMenu.NavigationService.Navigate(typeof(pagename), parameter);`

now the tricky party complex types can't be passed as parameter.  A solution is to use SerializationService that can be used to pass serialized data of the object in question, deserialized on the other side, react to the parameter data.

As far as the SessionState that is mainly used for Resuming/Suspend state, to store values you may not want to disappear while suspended...

You can call ClearHistory() if you need to from with in the tapped event.

HTH?

**Comment by jerinjohnk** [comment]
@mvermef thanks for the prompt reply. Suggestion 1) and 2) are the ones I am following.
For navigationservice I was using the one passed from App.xaml will change it to your suggested one instead.
For tricky part you suggested the use of SerializationService instead of SessionState. But as per @JerryNixon 's [documentation](https://github.com/Windows-XAML/Template10/wiki/Page-Parameters#passing-complex-parameters-to-a-page) we are supposed to use SessionState for complex parameter. Regarding SerializationService what caught my eye was the comment in this [issue](https://github.com/Windows-XAML/Template10/issues/1161) where at the bottom Jerry says 

> One change in the future will no longer require deserialization in page.onnavto

So I was of the notion that using it would end up breaking my app later on.
Will now remove the SessionState usage for navparameter and use SerializationService instead for complex parameters and try it out.

For ClearHistory why setting it to true in XAML doesnt work with Tapped event but works with PageType?

**Comment by mvermef** [comment]
My bad in that case you can get to SessionState from App.SessionState since is part of the bootstrapper of the app.  There shouldn't be any issue with that... And since the SessionState is a dictionary you name the key anything and add it... `SessionState.Add("SomeKey", objValue);`, then pass the "SomeKey"... The docs absolutely correct.

**Comment by jerinjohnk** [comment]
Yes thats what I needed. So I updated my Shell constructor to pass SessionState from App.xaml.cs using

```
public override UIElement CreateRootElement(IActivatedEventArgs e)
        {
            var service = NavigationServiceFactory(BackButton.Attach, ExistingContent.Exclude);
            return new ModalDialog
            {
                DisableBackButtonWhenModal = true,
                Content = new Cardekho.Views.Shell(service, this.SessionState),
                ModalContent = new Cardekho.Views.UserControls.Busy(),
        };           
        }
```

My updated Shell Code

```
 public Shell(INavigationService navigationService, IStateItems sessionState) : this()
        {
            SetNavigationService(navigationService);
            tempNav = navigationService;
            tempSessionState = sessionState;
        }
```

Also calling`tempNav.ClearHistory();` inside tapped event was clearing history whereas specifying it inside XAML itself `ClearHistory="True"` along with tapped event wasnt working as mentioned earlier. Still dont know why.

Closing this issue. If anyone has any better suggestion to access SessionState pls feel free to comment.
