### ISSUE TITLE
StackOverflowException while trying to store an non-serializable data to settings

### ISSUE THREAD

**Issue by Jebarson** [Windows-XAML/Template10#1272]
I was trying to save SolidColorBrush (which is not serializable) to the application roaming settings and I was getting the error as 

> System.StackOverflowException was unhandled
> Message: An unhandled exception of type 'System.StackOverflowException' occurred in mscorlib.ni.dll

However when I try to use the SDK way of storing the data, I get the below data which is much explanatory 

> Exception thrown: 'System.Runtime.InteropServices.COMException' in mscorlib.ni.dll
> WinRT information: Error trying to serialize the value to be written to the application data store
> Additional information: Data of this type is not supported.
> Error trying to serialize the value to be written to the application data store
> If there is a handler for this exception, the program may be safely continued.

If you can include this underlying exception as an inner exception, it would be great and save some time. I almost wasted an hour to find out what I was doing wrong.

**Comment by mvermef** [comment]
Can you show us how you are doing it and where? Saying by SDK says nothing related to T10.

**Comment by mvermef** [comment]
Try something like this and serialize, convert data from brush to string

https://gist.github.com/blndev/2783019

**Comment by Jebarson** [comment]
Hey Morgan, Sorry I missed to mention the method.
The method is SettingsService.Write

The underlying issue I guess is with the JsonSerializer we are using inside, May be we can throw a notsupported exception or custom exception which will clearly mention the cause.

Thanks for the tip, I have already changed my property to use Color instead of brush.
