### ISSUE TITLE
Announcing Template 10 v1.1.12

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#1274]
I am pleased to announce the release of version 1.1.12. This was a long time coming. I feel it is also well tested. The next version of Template 10 will likely be version 2.0.0. There may be a maintenance update to 1.1.13, but right now there is no plan for that - but no code is perfect.  So many of you have contributed to this release. I would like to personally thank you for the many issues, the many comments, and the many pull requests that have made this long-time-coming version possible. Template 10 remains the premier framework for UWP apps, and remains popular both outside and inside Microsoft. This version is faster, smaller, richer, and most predictable. Thanks again. //Jerry

Learn more
http://aka.ms/Template10.1.1.12 

Get it
https://www.nuget.org/packages/Template10/1.1.12

Dependencies
Microsoft.NETCore.UniversalWindowsPlatform (>= 5.2.2) 
Microsoft.Xaml.Behaviors.Uwp.Managed (>= 1.1.0) 
Newtonsoft.Json (>= 8.0.3)

**Comment by JerryNixon** [comment]
Are you getting this exception?

> An exception of type 'System.IO.FileLoadException' occurred in WindowsApp2.exe but was not handled in user code. Additional information: Could not load file or assembly 'System.Runtime.WindowsRuntime, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

This means your app has not been updated to Microsoft.NETCore.UniversalWindowsPlatform version 5.2.2 which is required for Template 10 1.1.12 and it is 100% backwards compatible all the way down to 10240. So, upgrading to it should not break any existing application. There is no 15939 requirement in 1.1.12, but this is the last version of Template 10 that will claim that.

**Comment by tibitoth** [comment]
Please create tags into the git repo, to easily view the related code for each nuget packages and vs extensions.

**Comment by schuettecarsten** [comment]
It's a pity that v2 will not be backward compatible to 10240, because we have to make sure that our software works with all release versions of Windows 10 for 36 month....

**Comment by crussi** [comment]
I upgraded my Template 10 project to the latest NuGet (https://www.nuget.org/packages/Template10/1.1.12).   I see a new reference to  Microsoft.NETCore.UniversalWindowsPlatform version 5.2.2.  But, I'm still getting the error:
An exception of type 'System.IO.FileLoadException' occurred in WindowsApp2.exe but was not handled in user code. Additional information: Could not load file or assembly 'System.Runtime.WindowsRuntime, Version=4.0.11.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Steps to reproduce:
1) Create new Template 10 hamburger template.
2) Upgrade to latest NuGet package for Template 10
3) Try to run the solution 

Best regards,
Chris

**Comment by crussi** [comment]
I got it to work.  I noticed that Microsoft.NETCore.UniversalWindowsPlatform version 5.2.2 was being "downgraded" to an earlier version.  For some reason, I had to uninstall the older version of Microsoft.NETCore.UniversalWindowsPlatform and manually run NuGet to install the newer version.  This solved the problem.  I am not sure why it didn't just automatically upgrade the version.
