### ISSUE TITLE
ShowShellBackButton= false navigation error

### ISSUE THREAD

**Issue by jerinjohnk** [Windows-XAML/Template10#1276]
While have set ShowShellBackButton as True the back navigation works fine and it navigates back to previous pages in order.
![showshelltrue](https://cloud.githubusercontent.com/assets/11266456/19508180/5efe1c90-95f5-11e6-9ac5-2f527b6aafd9.gif)

But Now when inside my App.xaml file I set its value to false and on navigating back it starts skipping pages from backstack as here you can see it skipped Hyundai titled page.
![showshellfalse](https://cloud.githubusercontent.com/assets/11266456/19508235/aa627d7a-95f5-11e6-836b-25408493111e.gif)

**Code replaced**

```
 //ShowShellBackButton = settings.UseShellBackButton;
            ShowShellBackButton = false;
```

Am I missing something?

**Comment by JerryNixon** [comment]
Hi. I am not sure I understand what you are saying. Are you saying that when you set the property to `false` it _is_ working correctly? Do you have only one frame?

**Comment by jerinjohnk** [comment]
I have multiple pages. While I have property set to `true` its working fine as can be seen from first .gif image where I click on items to navigate to new page and using shellbutton navigate Back in order.
But as you can see in second .gif image while property is set as `false` it started skipping pages on back tap.
Navigation is
New Car-SearchByBrand(1Page)-> SearchBrand(2Page)->Hyundai(3rdPage)->HyundaiCreta(4thPage)
In Second Gif on back click you can find Hyundai(3rdPage) missing

**Comment by JerryNixon** [comment]
Might take a little bit to figure this one out. As an unrelated aside, I see you are using the DrillIn transition to load a page but not he DrillOut transition to unload. Are you causing that manually or is the out transition not automatically setting to DrillOut? This is not a Template 10 related issue, just a question when I was looking @ the gif.

**Comment by jerinjohnk** [comment]
Sorry for late rep. Yes the transition that you noticed isnt a Template10 related issue but its caused due to my tinkering with default animation to find one similar to current app's android counterpart.
Here is the code of transition causing the effect

```
 <Page.Transitions>
        <TransitionCollection>
            <NavigationThemeTransition>
                <NavigationThemeTransition.DefaultNavigationTransitionInfo>
                    <ContinuumNavigationTransitionInfo/>
                </NavigationThemeTransition.DefaultNavigationTransitionInfo>
            </NavigationThemeTransition>
        </TransitionCollection>
    </Page.Transitions>
```

Looking forward to the fix of ShellBackButton soon.
