### ISSUE TITLE
outline hamburger menu not correct

### ISSUE THREAD

**Issue by deRightDirection** [Windows-XAML/Template10#1281]
if you override some coloring properties of the hamburger menu like the border then it is not showing correctly in the small version

so attached pictures
![screenhunter_52 oct 20 17 07](https://cloud.githubusercontent.com/assets/3999790/19565793/6ddfcabc-96e8-11e6-847f-2bb528249f60.jpg)
![screenhunter_54 oct 20 17 13](https://cloud.githubusercontent.com/assets/3999790/19565843/9a9a2aa2-96e8-11e6-844e-047d7ddb3544.jpg)

**Comment by JerryNixon** [comment]
Yep. Thanks for using Template 10. A border adds to the size of any control. This is true with every XAML controls. If you want to add a border, changing the size of the menu, then you have to change the size of the PageHeader, too, if you want them to align. I hope this makes sense.

**Comment by deRightDirection** [comment]
yeah i can agree with it, but in the full version this is also true but the line appears... but i will try to fix it then on my own. thanks anyway for the response.
