### ISSUE TITLE
Cannot rebuild project after Template 10 update

### ISSUE THREAD

**Issue by devwisdom** [Windows-XAML/Template10#1284]
I had created a project with Template 10 a couple of months ago which was working fine.  Today, after making some changes to my code, when I went ahead to build the project I noticed that Template 10 was updated to the latest version, so now as a result I can no longer build my project.

I think users should have a better control over this to prevent any updates to something that is already working fine and that could potentially break your code.

The rule should be: if it's not broken, don't fix it, or at least, always ask the user before updating.

**Comment by dg2k** [comment]
> The rule should be: if it's not broken, don't fix it, or at least, always ask the user before updating.

Wow! that is a bit unkind if not rude. You are getting free service here and put proper arrangements in place to make use of this free service. When you download updates, test your app in isolation before changing your working system. Template 10 is in constant development and it's up to users to adapt to the developmental change, not the other way round. Besides, there is enough info on this website about the updates and what more do you expect? Do you expect @JerryNixon to ask YOU personally before making changes?

**Comment by JerryNixon** [comment]
It's okay. I checked in some broken bits. My fault.
