### ISSUE TITLE
Cant get started with Template10 - SDK Version 10586 missing?

### ISSUE THREAD

**Issue by welcometochristown** [Windows-XAML/Template10#1287]
I have a new install of Windows 10, and Visual Studio 2015 Professional and I am trying to get Template10 to install.

I have installed the UWP Universal Templates and I can see them in the New Project menu which I can start and run successfully.

I then installed Template10 Template Pack through the Tools->Extensions and Updates menu. 

These are the version options I get when I create a new Template10 project (e.g Hamburger).
![1](https://cloud.githubusercontent.com/assets/17158437/19646546/cc6a3cdc-99f1-11e6-8a9b-7957b2af8763.png)

However no matter which one I pick I get this error afterwards,

![2](https://cloud.githubusercontent.com/assets/17158437/19646672/6b1ddd70-99f2-11e6-8eed-837735c2e78c.png)

So I installed the latest Microsoft SDK.

![3](https://cloud.githubusercontent.com/assets/17158437/19646683/7a2c290c-99f2-11e6-8ec1-88488227d64f.PNG)

I still get the same error about missing the SDK though when I start a new project. Do I also need to install the 10586 version too? And if so, should I uninstall the other version first?

**Update:**
After removing that development kit, and adding the 10586 version, it now builds but exceptions out when I start the application.

![image](https://cloud.githubusercontent.com/assets/17158437/19648955/de812110-99fb-11e6-9eec-b4a3f54f7685.png)

The only thing that looks a bit wierd is in my references I have these

![image](https://cloud.githubusercontent.com/assets/17158437/19648958/e2d6d250-99fb-11e6-985e-5b111f0ec9a0.png)

**Comment by thunderbeans** [comment]
After removing that development kit, and adding the 10586 version, it now builds but exceptions out when I start the application.

![image](https://cloud.githubusercontent.com/assets/17158437/19647193/e817a2d2-99f4-11e6-8ec8-39876f7e91bf.png)

**Comment by kaki104** [comment]
Two SDK is all should be installed. (Build 14393, 10586)
Update Nuget packsges to the latest version. 
Microsoft.NETCore.UniversalWindowsPlatform -> 5.2.2

**Comment by welcometochristown** [comment]
You are a champ!! Thanks so much for that, I was pulling my hair out for a while haha.

For anyone else in the same boat, here is what I did.

Tools -> NuGet package manager -> Manage NuGet Packages for solution

![image](https://cloud.githubusercontent.com/assets/17158437/19650298/aed4fd42-9a00-11e6-8c35-fc72bb7bf183.png)

Ticked all of these and then clicked update, took a while but told me when it was finished.

I'm sure this can be done through the console too.
