### ISSUE TITLE
Regarding Integration with Zxing.Net.Mobile for barcode scanning 

### ISSUE THREAD

**Issue by MMalikKhan** [Windows-XAML/Template10#1288]
Hi @JerryNixon ,

I am currently having issues  to upgrade Zxing barcode api to the latest version. I am currently using Zxing  version 2.1.13 for barcode scanning in my UWP app and works in most of the cases but have some crashes at randomly, i wanted to update to the latest version 2.1.47. However, when i upgrade i cant make it work because of the following code. 

````
public override async Task<Result> Scan(MobileBarcodeScanningOptions options)
        {
            var rootFrame = RootFrame ?? Window.Current.Content as Frame ?? ((FrameworkElement) Window.Current.Content).GetFirstChildOfType<Frame>();
            var dispatcher = Dispatcher ?? Window.Current.Dispatcher;

```
        var tcsScanResult = new TaskCompletionSource<Result>();

        await dispatcher.RunAsync(CoreDispatcherPriority.Normal, () =>
        {
            rootFrame.Navigate(typeof(ScanPage), new ScanPageNavigationParameters
            {
                Options = options,
                ResultHandler = r =>
                {
                    tcsScanResult.SetResult(r);
                },
                Scanner = this,
                ContinuousScanning = false
            });
        });

        var result = await tcsScanResult.Task;

        await dispatcher.RunAsync(CoreDispatcherPriority.High, () =>
        {
            if (rootFrame.CanGoBack)
                rootFrame.GoBack();
        });

        return result;
    }
````

they have change the implementation since 2.1.13 and now passing a complex type as param to the page .. and this type cannot be serialized hence giving serialization error when i try to launch the barcode scanner .. While i know the reason why this is not working after digging into code, but i have no idea how i can make it work with template10. The above code actually reside in the windows universal project of Zxing library and has no access to Template10. 

Could you please suggest what i can do to integrate with this API.  

I am open to use any other barcode scanning API which allows to scan codes using the camera from Microsoft. 

Note: the one which is on windows samples page does not work, the older one was only for physical camera .. and the newly added camera barcode sample does not work for me when i run on my mobile.

Since this is keep crashing the app at random instances .. users are having lots of issues with dataloss and other usability issues.. could you please suggest what best i can do in this case. 

Thank You

**Comment by MMalikKhan** [comment]
@JerryNixon  any suggestions on the above issue ?

**Comment by JerryNixon** [comment]
I don't understand the issue.
