### ISSUE TITLE
OnNavigatedToAsync with x:Bind

### ISSUE THREAD

**Issue by tibitoth** [Windows-XAML/Template10#1289]
I have just faced a problem with the `INavigable.OnNavigatedToAsync` method. If I do multiple long running tasks in the `ViewModelBase.OnNavigatedToAsync` override the UI is not updated after the first one because the second awaited task blocks. For example:

``` C#
public override async Task OnNavigatedToAsync(object parameter, NavigationMode mode, IDictionary<string, object> suspensionState)
{
    Something1 = await _someService.FirstLongRunningTask();

    await SecondLongRunningTask();

    await OtherLongRunningTask();

    await base.OnNavigatedToAsync(parameter, mode, suspensionState);
}
```

I want to update the UI with the `Something1` property's changes. Also the `SecondLongRunningTask()` update some property whose updates I want to see in the UI before the method is fully awaited.

This problem is caused by the NavigationService's implementation (https://github.com/Windows-XAML/Template10/blob/337047cd1d66b083bf74c4087e2a2366ef997324/Template10%20(Library)/Services/NavigationService/NavigationService.cs#L180-L184)
The NavigationService initializes the compiled bindings after the OnNavigatedToAsync call. 

Please consider to provide a way to initialize compiled bindings before the OnNavigatedToAsync.

Maybe it's also related with the #1261 discussion.

**Comment by JerryNixon** [comment]
I think the error is that it should NOT Initialize(). What do you think?

**Comment by tibitoth** [comment]
I took further investigation and I found out that this bug only appears when we using dependency injection so when we do not set the `Page.DataContext` explicit in the XAML. I will dive into the code for the reason,

ps.: I'm using x:Bind and DI together with this helper property: 

``` cs
public sealed partial class DetailPage : Page
{
    public DetailPageViewModel ViewModel => (DetailPageViewModel) DataContext;

    public DetailPage()
    {
        InitializeComponent();
    }
}
```

**Comment by tibitoth** [comment]
What do you think? Do I create a PR for the 10.2 codebase or wait until the stabilization?
