### ISSUE TITLE
HamburgerButtonInfo NavToggleButtonTemplate Checked States broken

### ISSUE THREAD

**Issue by johanlindfors** [Windows-XAML/Template10#1292]
In the latest version of T10 there's something very broken with the HamburgerButtonInfo's NavToggleButtonTemplate's Checked states.

I can't figure out how to properly make the states available in the style to actually occur properly, it's easily reproduced by simply changing the states to something like

`<VisualState x:Name="Checked">
<VisualState.Setters>
        <Setter Target="ContentPresenter.Foreground" Value="{Binding NavButtonCheckedForeground, ElementName=ThisPage}" />
        
        <Setter Target="ContentPresenter.Background" Value="Blue" />
        <Setter Target="Indicator.Visibility" Value="Visible" />
    </VisualState.Setters>
</VisualState>
<VisualState x:Name="CheckedPointerOver">
    <VisualState.Setters>
        <Setter Target="ContentPresenter.Foreground" Value="{Binding NavButtonCheckedForeground, ElementName=ThisPage}" />
        
        <Setter Target="ContentPresenter.Background" Value="Red" />
        <Setter Target="Indicator.Visibility" Value="Visible" />
    </VisualState.Setters>
</VisualState>
<VisualState x:Name="CheckedPressed">
        <VisualState.Setters>
            <Setter Target="ContentPresenter.Foreground" Value="{Binding NavButtonCheckedForeground, ElementName=ThisPage}" />
            
            <Setter Target="ContentPresenter.Background" Value="Yellow" />
            <Setter Target="Indicator.Visibility" Value="Visible" />
        </VisualState.Setters>
</VisualState>`

The Yellow color (CheckedPressed) will never appear, the Blue (Checked) will only appear on first launch of page (in a simple shell example) and the red color will appear as checked (unless I click the button and release outside the button, in which the blue will appear again).

If you can't reproduce I can try to upload a sample but I've managed to reproduce in several tests with the latest repo.

**Comment by JerryNixon** [comment]
Checked can ONLY be changed by using HamMenu.Selected

**Comment by johanlindfors** [comment]
I'm sorry Jerry but I don't understand the checked states at all in the HamburgerMenu. It doesn't matter how I enforce the checked state (either by setting Menu.Selected to the specified button, or explicitly setting the toggle button to IsChecked), the behavior is not correct. The CheckedPointedOver state or the CheckedPressed state simply doesn't work. I get the CheckedPointerOver every time I select a button, and only get the actual Checked state when selecting the button, but making sure to release the pointer outside of the "hit area" of the actual button. The Pressed state never appears!

A simple proper sample on how to get the Checked states to work appropriately would really help!
