### ISSUE TITLE
Question issue: How to use suspensionState of OnNavigatedToAsync to restore data

### ISSUE THREAD

**Issue by Hamza54** [Windows-XAML/Template10#1293]
Here is the code for OnNavigatedToAsync and OnNavigatedFromAsync : 
**public override Task OnNavigatedToAsync(object parameter, NavigationMode mode, IDictionary<string, object> suspensionState)
{
    if (suspensionState.Any())
    {
        Value = suspensionState[nameof(Value)]?.ToString();
    }
    return Task.CompletedTask;
}**
**public override async Task OnNavigatedFromAsync(IDictionary<string, object> suspensionState, bool suspending)
        {
            if (suspending)
            {
                suspensionState[nameof(Value)] = Value;
            }
            await Task.CompletedTask;
        }**
I am looking for away to use the suspensionState to restore data if the app suspends, while suspending the MinimalTemplate app in the debug mode it does not go through the if statement of suspensionState.Any(). Actually the state is saved on the OnNavigatedFromAsync but not restored on the suspensionState of the OnNavigatedToAsync.
I would like to know when does the suspensionState fire some value? or which mechanism does allow me to restore data that I saved with OnNavigatedFromAsync during the suspension.

**Comment by NewBLife** [comment]
@Hamza54   this is my sample.maybe it can be help you!
[suspensionState demo](https://github.com/NewBLife/UWP/blob/master/MvvmDemo/FileOperationDemo/ViewModels/MainPageViewModel.cs#L115)

`
public override async Task OnNavigatedToAsync(object parameter, NavigationMode mode, IDictionary<string, object> suspensionState)
        {
            try
            {
                if (suspensionState.Any())
                {
                    FileList = SerializationService.Json.Deserialize<ObservableCollection<FileInfo>>(suspensionState[nameof(FileList)]?.ToString());
                }
                else
                {
                    await ApplicationData.Current.ClearAsync(ApplicationDataLocality.Temporary);
                }

```
            await Task.CompletedTask;
        }
        catch (Exception ex)
        {
            Debug.WriteLine(ex.Message);
        }
    }

    public override async Task OnNavigatedFromAsync(IDictionary<string, object> suspensionState, bool suspending)
    {
        try
        {
            if (suspending)
            {
                suspensionState[nameof(FileList)] = SerializationService.Json.Serialize(FileList);
            }
            await ApplicationData.Current.ClearAsync(ApplicationDataLocality.Temporary);

            await Task.CompletedTask;
        }
        catch (Exception ex)
        {
            Debug.WriteLine(ex.Message);
        }
    }`
```

**Comment by Hamza54** [comment]
@NewBLife Thank you for your answer,
Can you give a case where the application enters the if (suspensionState.Any()) and runs the lines inside. I can't figure out when does this part of code runs although I debugged in the suspension lifecycle event.

**Comment by NewBLife** [comment]
https://github.com/NewBLife/UWP/tree/master/MvvmDemo/FileOperationDemo

this demo i have created before can do it！please try it！add a photo in mainpage before do suspend event.

**Comment by JerryNixon** [comment]
Suspend occurs when the user closes the app without killing the process. You can test this in Visual Studio with the Debug Location toolbar and select Suspend+Terminate. I hope this makes sense.
