### ISSUE TITLE
Announcing Template 10 Template Pack v1.19

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#1295]
![image](https://cloud.githubusercontent.com/assets/1749983/19938312/1cd211c8-a0ea-11e6-9228-f4cfc107c974.png)

Can you believe it, I finally updated the thing.

**Comment by Rasetech** [comment]
HI Jerry, when will the template pack be available for VS 2017 RC?

**Comment by alexsorokoletov** [comment]
Is it possible to get a 2017 RC build while we are waiting for RTM?
