### ISSUE TITLE
Minimal doesn't compile (no dark and light

### ISSUE THREAD

**Issue by ncarandini** [Windows-XAML/Template10#130]
This is odd:
commit 428c48339bcc2dc7f0d04b0e571f937f25c600d8 
has only the Custom.Shared.xaml file while the Minimal.csproj has all the three ones:

```
<Page Include="Styles\Custom.Dark.xaml"> 
    <Generator>MSBuild:Compile</Generator> 
    <SubType>Designer</SubType> 
</Page> 
<Page Include="Styles\Custom.Light.xaml"> 
    <Generator>MSBuild:Compile</Generator> 
    <SubType>Designer</SubType> 
</Page> 
<Page Include="Styles\Custom.Shared.xaml"> 
    <Generator>MSBuild:Compile</Generator> 
    <SubType>Designer</SubType> 
</Page> 
```

Never mind I think is something that will be fixed ASAP, because the build fails so I don't want to clutter with a "dull" pull request.

I've raised this issue only to let you know, just in case someone else has problems on compiling this specific commit.

**Comment by JerryNixon** [comment]
I think you caught me in the middle of some updates. Can you verify it works now?

**Comment by ncarandini** [comment]
Yes now is ok.

**Comment by enzocontini** [comment]
I just updated Template10 to vers. 1.0.6 from NuGet Package Manager and I am experimenting errors on Styles in a project I am doing with the previous version of the Template10 (e.g.  in Custom.Dark.xaml => Unknown member 'NavButtonHoverOverlayBackground' on element 'HamburgerMenu')

... is the version that solves this issue not yet in NuGet?
I noticed that now there is a Custom.xaml in styles, not anymore Custom.Dark.xaml/Custom.Light.xaml/Custom.HighContrast.xaml/Custom.Shared.xaml ... How can I make the new Template10 new version work fine with a project that started from the minimal of the previous Template10 release?
How can be handled in an easy way a project using Template10 if new release can introduce compiling problems?

**Comment by MichaelPetrinolis** [comment]
hi, you could see the differences of custom.xaml from a newly minimal created project using the latest template and the one you currently have or check the source code on GitHub.
It should be better to open a new issue instead of commenting on a closed one.

**Comment by enzocontini** [comment]
Thank you also for the suggestion on how to use Issues in GitHub.
It is a pity that there is not a specific forum for discussing Template10 issues/problems other than this section in GitHub that personally I do not find very friendly to use (compared with Community forum, Codeplex forum, StackOverflow ...). I wonder if there is some other place where people, trying to use Template10, can discuss and point out problems/questions ... Let me know if so :-)
