### ISSUE TITLE
How does NavigationService.ClearCache() work?

### ISSUE THREAD

**Issue by pcolmer** [Windows-XAML/Template10#1303]
ClearCache seems to preserve the current size of the cache, set it to another value and then set it back to the previous value.

The intermediate value is one of the following:

- 0 if `removeCachedPagesInBackStack` is true
- 1 if `BackStackDepth` is 0
- `BackStackDepth` otherwise

Is there some magic (undocumented) behaviour of setting CacheSize to these values? According to https://www.jayway.com/2012/05/25/clearing-the-windows-8-page-cache/, setting it to 0 clears the cache of all pages but I'm struggling to understand how the other two values behave.

**Comment by JerryNixon** [comment]
This is a good question. What should it do?

**Comment by JerryNixon** [comment]
Here's where it was born. 

https://github.com/Windows-XAML/Template10/pull/974

**Comment by pcolmer** [comment]
That is where the code is being called from but I'm not sure it is the birth of it.

git blame breaks the changes down as follows:

    078dcd2b Template10 (Library)/Services/NavigationService/NavigationService.cs      (Brandon Hurlburt     2015-10-12 15:58:41 -0500 357)         public void ClearCache(bool removeCachedPagesInBackStack = false)
    4cd848d3 Template10 (Library)/Services/NavigationService/NavigationService.cs      (Jerry Nixon          2015-11-30 19:51:01 -0700 358)         {
    e25fa59a Template10 (Library)/Services/NavigationService/NavigationService.cs      (jerrynixon           2016-02-06 08:05:47 -0700 359)             DebugWrite($"Frame: {FrameFacadeInternal.FrameId}");
    8a5e5881 Template10 (Library)/Services/NavigationService/NavigationService.cs      (jerrynixon           2016-01-16 10:19:42 -0700 360)
    e25fa59a Template10 (Library)/Services/NavigationService/NavigationService.cs      (jerrynixon           2016-02-06 08:05:47 -0700 361)             int currentSize = FrameFacadeInternal.Frame.CacheSize;
    4cd848d3 Template10 (Library)/Services/NavigationService/NavigationService.cs      (Jerry Nixon          2015-11-30 19:51:01 -0700 362)
    4cd848d3 Template10 (Library)/Services/NavigationService/NavigationService.cs      (Jerry Nixon          2015-11-30 19:51:01 -0700 363)             if (removeCachedPagesInBackStack)
    4cd848d3 Template10 (Library)/Services/NavigationService/NavigationService.cs      (Jerry Nixon          2015-11-30 19:51:01 -0700 364)             {
    e25fa59a Template10 (Library)/Services/NavigationService/NavigationService.cs      (jerrynixon           2016-02-06 08:05:47 -0700 365)                 FrameFacadeInternal.Frame.CacheSize = 0;
    4cd848d3 Template10 (Library)/Services/NavigationService/NavigationService.cs      (Jerry Nixon          2015-11-30 19:51:01 -0700 366)             }
    4cd848d3 Template10 (Library)/Services/NavigationService/NavigationService.cs      (Jerry Nixon          2015-11-30 19:51:01 -0700 367)             else
    4cd848d3 Template10 (Library)/Services/NavigationService/NavigationService.cs      (Jerry Nixon          2015-11-30 19:51:01 -0700 368)             {
    e25fa59a Template10 (Library)/Services/NavigationService/NavigationService.cs      (jerrynixon           2016-02-06 08:05:47 -0700 369)                 if (FrameFacadeInternal.Frame.BackStackDepth == 0)
    e25fa59a Template10 (Library)/Services/NavigationService/NavigationService.cs      (jerrynixon           2016-02-06 08:05:47 -0700 370)                     FrameFacadeInternal.Frame.CacheSize = 1;
    4cd848d3 Template10 (Library)/Services/NavigationService/NavigationService.cs      (Jerry Nixon          2015-11-30 19:51:01 -0700 371)                 else
    e25fa59a Template10 (Library)/Services/NavigationService/NavigationService.cs      (jerrynixon           2016-02-06 08:05:47 -0700 372)                     FrameFacadeInternal.Frame.CacheSize = FrameFacadeInternal.Frame.BackStackDepth;
    4cd848d3 Template10 (Library)/Services/NavigationService/NavigationService.cs      (Jerry Nixon          2015-11-30 19:51:01 -0700 373)             }
    4cd848d3 Template10 (Library)/Services/NavigationService/NavigationService.cs      (Jerry Nixon          2015-11-30 19:51:01 -0700 374)
    e25fa59a Template10 (Library)/Services/NavigationService/NavigationService.cs      (jerrynixon           2016-02-06 08:05:47 -0700 375)             FrameFacadeInternal.Frame.CacheSize = currentSize;
    4cd848d3 Template10 (Library)/Services/NavigationService/NavigationService.cs      (Jerry Nixon          2015-11-30 19:51:01 -0700 376)         }

so it looks like the method was initially started on 12th October 2015 by Brandon Hulburt. I can't find this commit, though, nor the other commits in order to drill down further to understand what Brandon wrote or what you wrote, Jerry.

**Comment by pcolmer** [comment]
Seeking some clarification - what is this a duplicate of?
