### ISSUE TITLE
Encoding UTF8

### ISSUE THREAD

**Issue by Sbebo** [Windows-XAML/Template10#1305]
I use Hamburger Template 10
Where i insert the encoding UTF8 in my project?
When i debug my app all world  à ò ì ... are represented by a triangle error
![xx](https://cloud.githubusercontent.com/assets/22842679/20053849/b5d268c0-a4da-11e6-8efd-a773a396ed15.png)

**Comment by mvermef** [comment]
https://github.com/Windows-XAML/Template10/wiki/Document-Encoding

**Comment by Sbebo** [comment]
Thanks!
