### ISSUE TITLE
HamburgerMenu control doesn't respect colors

### ISSUE THREAD

**Issue by tibitoth** [Windows-XAML/Template10#1306]
In the Hamburger template I was unable to set the navigation pane's background color.
I tried to set the `HamburgerMenu.NavAreaBackground` property in the `Custom.xaml` or in the `Shell.xaml`, but it didn't work.

I have taken a look to the source code and I've saw some strange things:
- The hamburger menu doesn't use the implicit style from `Custom.xaml`. Do not we need the `DefaultStyleKey = typeof(HamburgerMenu);` statement somewhere in the `HamburgerMenu`?
- The hamburger menu overwrite the given colors with some hard coded values in this method: https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Controls/HamburgerMenu.PublicMethods.xaml.cs#L58-L114
- This overwrite happens in:
    - `Shell.xaml.cs` `SetNavigationService()` method: https://github.com/Windows-XAML/Template10/blob/master/Templates%20(Project)/Hamburger/Views/Shell.xaml.cs#L35
    - `SettingsService` `AppTheme` property's setter:  https://github.com/Windows-XAML/Template10/blob/master/Templates%20(Project)/Hamburger/Services/SettingsServices/SettingsService.cs#L43

**Comment by NEKIT-Boss** [comment]
Greetings @totht91 . I've ran into the same confusion. Actually, hamburger menu colors are overridden because of the AccentColor property being set in its style (if we are talking about hamburger template).

[Property is set here (Default - means Dark)](https://github.com/Windows-XAML/Template10/blob/master/Templates%20(Project)/Hamburger/Styles/Custom.xaml#L70)
[In light theme](https://github.com/Windows-XAML/Template10/blob/master/Templates%20(Project)/Hamburger/Styles/Custom.xaml#L23)
High contrast theme is not setting it. It is overriding each color setter separately.

If you put it out (AccentColor setter), you will see the changes of your setters regarding colors. And pay attention to themes because they are being applied by provided settings service(in hamburger template). 

Maybe if we simply switch the order of AccentColor setter and separate setters (AccentColor first and then separate) we can have expected behavior too, but I haven't tested that.
Hope it helps.

**Comment by JerryNixon** [comment]
@NEKIT-Boss is 100% correct.

**Comment by michaelhutchful** [comment]
``
        <ResourceDictionary x:Key="Light">

            <SolidColorBrush x:Key="CustomColorBrush" Color="{StaticResource CustomColor}" />
            <SolidColorBrush x:Key="ContrastColorBrush" Color="{StaticResource ContrastColor}" />
            <SolidColorBrush x:Key="ExtendedSplashBackground" Color="{StaticResource CustomColor}" />
            <SolidColorBrush x:Key="ExtendedSplashForeground" Color="{StaticResource ContrastColor}" />

            <Style TargetType="controls:HamburgerMenu">
                <Setter Property="AccentColor" Value="Crimson"/>
                <Setter Property="NavAreaBackground" Value="Firebrick"/>
                <Setter Property="VisualStateNarrowMinWidth" Value="{StaticResource NarrowMinWidth}" />
                <Setter Property="VisualStateNormalMinWidth" Value="{StaticResource NormalMinWidth}" />
                <Setter Property="VisualStateWideMinWidth" Value="{StaticResource WideMinWidth}" />
            </Style>

            <Style TargetType="controls:PageHeader">
                <Setter Property="Background" Value="#00000000" />
                <Setter Property="Foreground" Value="{ThemeResource ContrastColorBrush}" />
            </Style>

            <Style TargetType="controls:Resizer">
                <Setter Property="GrabberBrush" Value="{ThemeResource CustomColorBrush}" />
                <Setter Property="GrabberVisibility" Value="Visible" />
            </Style>

        </ResourceDictionary>

        <ResourceDictionary x:Key="Default">

            <SolidColorBrush x:Key="CustomColorBrush" Color="{StaticResource CustomColor}" />
            <SolidColorBrush x:Key="ContrastColorBrush" Color="{StaticResource ContrastColor}" />
            <SolidColorBrush x:Key="ExtendedSplashBackground" Color="{StaticResource CustomColor}" />
            <SolidColorBrush x:Key="ExtendedSplashForeground" Color="{StaticResource ContrastColor}" />

            <Style TargetType="controls:HamburgerMenu">

                

                <Setter Property="AccentColor" Value="RosyBrown"/>
                <Setter Property="NavAreaBackground" Value="Firebrick"/>
                <Setter Property="VisualStateNarrowMinWidth" Value="{StaticResource NarrowMinWidth}" />
                <Setter Property="VisualStateNormalMinWidth" Value="{StaticResource NormalMinWidth}" />
                <Setter Property="VisualStateWideMinWidth" Value="{StaticResource WideMinWidth}" />
            </Style>

            <Style TargetType="controls:PageHeader">
                <Setter Property="Background" Value="{ThemeResource CustomColorBrush}" />
                <Setter Property="Foreground" Value="{ThemeResource ContrastColorBrush}" />
                <Setter Property="VisualStateNarrowMinWidth" Value="{StaticResource NarrowMinWidth}" />
                <Setter Property="VisualStateNormalMinWidth" Value="{StaticResource NormalMinWidth}" />
            </Style>

            <Style TargetType="controls:Resizer">
                <Setter Property="GrabberBrush" Value="{ThemeResource CustomColorBrush}" />
                <Setter Property="GrabberVisibility" Value="Visible" />
            </Style>

        </ResourceDictionary>``

So this is what I have, however the splitview pane color doesnt change. When I change it whilst the program is running, then thats fine. But it doesnt change permanently
