### ISSUE TITLE
Overriding OnBackgroundActivated

### ISSUE THREAD

**Issue by KristofferBerge** [Windows-XAML/Template10#1308]
To handle background triggers within one process I need to override OnBackgroundActivated on the Application object. This doesn't seem to be possible due to the inheritance of bootstrapper instead of application directly in the app class. Can this be solved somehow?

https://blogs.windows.com/buildingapps/2016/06/07/background-activity-with-the-single-process-model/#zDx2wa4MimvkFk3v.97

**Comment by WieserSoftware** [comment]
You probably just need to target the correct API level, and then you can override in your application.

**Comment by KristofferBerge** [comment]
Thanks! 
Setting the target version to Anniversary Edition (10.0; Build 14393) solved the problem :)

**Comment by JerryNixon** [comment]
I can't think of a reason to override this with Template 10. Can you?

**Comment by tibitoth** [comment]
If you want to create an in-process background task implementation.

**Comment by WieserSoftware** [comment]
Yes.  If you want to handle background activity in the single process model, https://blogs.windows.com/buildingapps/2016/06/07/background-activity-with-the-single-process-model/#QFvcgkqBwIcz7ayW.97

or support project Rome scenarios
https://msdn.microsoft.com/windows/uwp/launch-resume/communicate-with-a-remote-app-service

**Comment by JerryNixon** [comment]
Sorry, I meant... can you think of a reason Template 10 should seal that overload and provide a Template 10-managed version of the same?

**Comment by tibitoth** [comment]
And what do we want to manage by the Template10?
