### ISSUE TITLE
aka.ms changes please

### ISSUE THREAD

**Issue by pcolmer** [Windows-XAML/Template10#1309]
Hi Jerry

Can you please arrange for the following aka.ms redirects to be changed?

http://aka.ms/T10-Blank to go to https://github.com/Windows-XAML/Template10/wiki/Blank-Template
http://aka.ms/T10-Minimal to go to https://github.com/Windows-XAML/Template10/wiki/Minimal-Template
http://aka.ms/T10-Hamburger to go to https://github.com/Windows-XAML/Template10/wiki/Hamburger-Template

Once that is done, can you please delete this page:

https://github.com/Windows-XAML/Template10/wiki/Welcome-%7C-Hamburger-Template

The current content is in a different page, but this URL is being referenced by the aka.ms shortcuts.

Thanks.

Philip

**Comment by JerryNixon** [comment]
Take long enough?
