### ISSUE TITLE
Using ViewModelBase from MVVMLight

### ISSUE THREAD

**Issue by ghost** [Windows-XAML/Template10#131]
Great project! Is it possible to use the ViewModelBase of Template10 and the ViewModelBase of MVVMLight at the same time for ViewModels ? I'd like to have access to the nice superset of MVVMLight (RelayCommand, ...) and also the cool template of Template10 (OnNavigatedTo, ...)

**Comment by qmatteoq** [comment]
Actually you can just install MVVM Light and use the MVVM Light classes and helpers and keep using the Template10 ViewModelBase class. All the MVVM Light features (like RelayCommand, Messenger or DispatcherHelper) don't have a dependency on its ViewModelBase implementation, so you can use them in combination with the Template10 base class.

**Comment by ghost** [comment]
Perfect! Thank you so much :+1:
