### ISSUE TITLE
Hamburger Menu equivalent  OpenPaneLength CompactPaneLength

### ISSUE THREAD

**Issue by Hamza54** [Windows-XAML/Template10#1312]
Hey,

I am using the HamburgerMenu control of Tem10. I know it has been built on top of a SplitView.
How can I access the OpenPaneLength and CompactPaneLength properties of the SplitView in this control?
or is there any equivalent properties?

Kindly

**Comment by JerryNixon** [comment]
There are no such properties in the Template 10 HamburgerMenu. The HamburgerMenu in Template 10 is intended to emulate the implementation of the menu used in the out-of-the-box News app. That's the reason it's like it is. That being said, you are the first to ask for this. Would you care to explain your scenario so we can triage the request?

**Comment by dg2k** [comment]
@Hamza54 - Can't be certain, but could it be that what you're looking for is **HamburgerMenu.PaneWidth** which is readily available in T10?

My guess is based on the fact that  **HamburgerMenu.PaneWidth** is one item of interest in adaptive design -- relatively narrow (arround 200px for Mobile) and a bit wider for tablets and desktop (around 300px or more depending on display width).
