### ISSUE TITLE
PopupService size does not match parent's size when resized

### ISSUE THREAD

**Issue by Monsok** [Windows-XAML/Template10#1313]
This is how I create my `Popup` control 

        PopupService popupService = new PopupService();
        CropControl myPopup = new CropControl();
        Popup popup = popupService.Create(PopupService.PopupSize.FullScreen, myPopup);
        var trans = new PaneThemeTransition() { Edge = EdgeTransitionLocation.Left } as Transition;
        popup.ChildTransitions = new TransitionCollection() { trans };

I noticed the popup only match the initial parent window's size. When the parent is resized and the popup is called again, its dimension does not adjust to the new parent size. Here's an example.

Initially the popup fill up its parent.

![untitled-1](https://cloud.githubusercontent.com/assets/21212986/20302537/a943cd86-ab62-11e6-90a6-87e4a93df363.jpg)

Then the popup is dismissed. The windows is resize, then the popup is called again. Notice that its size does not match the new size but the old one.

![untitled-2](https://cloud.githubusercontent.com/assets/21212986/20302593/d90ac524-ab62-11e6-95d7-65c9e48fbf74.jpg)

When I resize the window manually by dragging the corners, the popup is updated but I want this to happen automatically.

How do I make sure the popup is resized correctly next time when it is called again?

**Comment by JerryNixon** [comment]
Interesting problem. Let me make sure I understand. When you use the popup and resize the window the popup does not resize? Or when you use the popup, close the popup, then resize the window, then reopen the popup, it is not resized to the new window size?

**Comment by Monsok** [comment]
It's the later. When I use the popup, close the popup, then resize the window, then reopen the popup. It is not resized to the new window size.

**Comment by Monsok** [comment]
I should add that, this problem also appear on mobile devices. To reproduce
1. Make sure phone is in portrait mode
2. Call the popup
3. Dismiss the popup
4. Rotate the phone in landscape mode
5. Call the popup again

The popup is not resized to the landscape mode.
