### ISSUE TITLE
Using Template10 as Git Submodule

### ISSUE THREAD

**Issue by johanlindfors** [Windows-XAML/Template10#1315]
I would like to get some guidance on how to properly use Template10 as a submodule in Git when building apps. From my experience there are two things that makes this a bit difficult:

1. Cloning the repo with "git submodule add ..." uses the latest commits which currently doesn't build due to the work being done on the upcoming version. There's no "flow" on the project as I see it currently. You could use "develop" branch for new work, or "release" branches when doing actual releases. At least tagging commits when doing the releases to nuget would be great (the latest tag seems to be for 0.4 if I understand correctly).

2. The two commands in the build events for the Template 10 (Library) project also breaks the build. The nuget packaging requires Release configuration (and I'm building Debug when doing work) and the macro using SolutionDir breaks the file paths since the actual solution for a project leveraging Template10 as a submodule wouldn't physically be in the same directory as the Template10 directory. The first command seems however to not actually break the build, but the second does. Changing this:

call "$(SolutionDir)\Template10 (Installer)\InstallSnippets.cmd"

to this:

call "$(ProjectDir)\..\Template10 (Installer)\InstallSnippets.cmd"

seems to do the trick though.

Or am I doing it wrong?

**Comment by JerryNixon** [comment]
I would accept a pull request that removes that line completely.

**Comment by johanlindfors** [comment]
Sure thing, should I remove the nuget packaging line as well? Maybe an explicit script would be sufficient?
