### ISSUE TITLE
Can't set SelectedItem of ListView to null

### ISSUE THREAD

**Issue by rancor1223** [Windows-XAML/Template10#1319]
I've posted this question to [StackOverflow](https://stackoverflow.com/questions/40698963/cant-deselect-listview-item-in-mvvm-uwp), but noone was particularly familiar with T10, but suggested other (perhaps even nicer) ways to go about solving the problem. But it's rather unexpected behaviour as even they seem to think it *should* work. Maybe it's bug?

**Comment by mvermef** [comment]
Have you set a break point to check that it is being set to null on the event executing?

**Comment by mvermef** [comment]
The other place to check is the NavigateFromAsync override in your Viewmodel, you could also set it there to null...

**Comment by rancor1223** [comment]
Yes, after I assign the null value the a break point is reached and the null value seems to be asssigned.

```
public MyListItemClass mySelectedItem{
    get { return _mySelectedItem; }
    set { 
    *breakpoint* Set(ref _mySelectedItem, value); 
    }
}
```

But View doesn't update accordingly. SelectionChanged also doesn't fire when clicking the same item. 

I'm not looking for solution to the problem anymore, I've already solved it differently with help from people over at StackOverflow. But I thought maybe it's a bug?

**Comment by mvermef** [comment]
Not a bug a listview normal thing, it's related to the index

**Comment by rancor1223** [comment]
Well, good to know. Thanks.

**Comment by mvermef** [comment]
I see you decided to go with click helper, keep in mind that option was also available through the use of Behaviors, which is part of Interactivity package... Some behaviors were also prebuilt.
