### ISSUE TITLE
When cancelling navigation, HamburguerMenu shows incorrect selected icon

### ISSUE THREAD

**Issue by aline-almeida** [Windows-XAML/Template10#1320]
If navigation is cancelled in OnNavigatingFrom, HamburguerMenu still shows the clicked page icon as selected, instead of the current page, that didn't change, because navigation was cancelled.

**Comment by JerryNixon** [comment]
Ah. We can't have that.

**Comment by zakkar1** [comment]
Is there any work around ? Can we set the focus on the Settings Button for example and if we can how can we do it ?

thank you

**Comment by zakkar1** [comment]
Any update on this ?

**Comment by zakkar1** [comment]
Hi ,
I have managed the below.
I went to the Shell.XAML.cs and created a method

 public void ChangeFocus()
        {
            
           
           SettingsButton.IsChecked = true;
            
        }
In my SettingsPage the OnNavigatingFrom event which I'm doing the Cancel if the Validations are not successful I'm doing the below

Views.Shell.Instance.ChangeFocus();

It worked for me.
It all has to do with Business Logic.
In My case when my app starts for the first time I want the user to be navigating to the settings page to complete his user name and password. If he tries to login or navigate to a different page I want to stop him from doing that. So In the OnNavigatingFrom I'm stopping the user to leave the Settings page and I'm giving again the "FOCUS" in the settings button.
You can give a  try and see if it worked for you.

thank you

**Comment by JerryNixon** [comment]
I am sorry for the delay. There's going to be more. December is a difficult month to get stuff done.
