### ISSUE TITLE
PrimaryCommand icons in PageHeader get hidden when the header text is too long

### ISSUE THREAD

**Issue by Hsn723** [Windows-XAML/Template10#1323]
Mostly encountered on mobile, when I have an especially long header, on page load the PrimaryCommand icons are shown properly, but if I run any command that toggles their visibility they gradually get all hidden into the ellipsis.

Repro steps: load a page with a long header, a back, forward and home buttons. The visibility of the back and forward buttons are bound to whether there is a previous or next item, respectively. When I press next, the backing value is recomputed, and regardless of its value all or some icons get hidden.

I believe this is new in 1.1.12 as another project I had running on an older version of Template10 didn't exhibit that behavior.

**Comment by JerryNixon** [comment]
Could you post a screen cap of what you are talking about?

**Comment by Hsn723** [comment]
Thank you for your reply. The first screenshot (please ignore the non-English text) shows the Next arrow, and when I press it, the next content is loaded and a Previous and Next arrows should show, but they end up being pushed to inside the ellipsis. 

edit: I also just realized that there should also be a Home button to the right of the Previous and Next buttons, but it already got shoved into the ellipsis in the first screenshot.

![wp_ss_20161203_0002 1](https://cloud.githubusercontent.com/assets/1885220/20844867/5d71bbb0-b905-11e6-8dcc-1465812e4348.png)
![wp_ss_20161203_0003 1](https://cloud.githubusercontent.com/assets/1885220/20844879/67e69f66-b905-11e6-91e9-5bcb10588d51.png)

**Comment by JerryNixon** [comment]
I recommend you use Dynamic Overflow.  https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.xaml.controls.commandbar.isdynamicoverflowenabled

**Comment by Hsn723** [comment]
Thank you, that was exactly what I was looking for.
