### ISSUE TITLE
error CS0263: Partial declarations of 'App' must not specify different base classes

### ISSUE THREAD

**Issue by partmachine** [Windows-XAML/Template10#1324]
created new uap project
added template10 package (1.1.12)
changed App base class from Application to Template10.Common.BootStrapper
buid and get error: error CS0263: Partial declarations of 'App' must not specify different base classes
because generated partial app class (App.g.i.cs) derives from Windows.UI.Xaml.Application.

I have no clue why this happens, i was trying to recreate one of the samples.

Anyone any ideas?

**Comment by NEKIT-Boss** [comment]
@renevangeffen, it seems like you haven't changed the corresponding XAML file of your App class (App.xaml that is).
It should look like this: 
```XAML
<common:BootStrapper x:Class="{YourProjectNamespace}.App"
                     xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                     xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                     xmlns:common="using:Template10.Common">
    <!-- Your resources declarations or whatever  -->
</common:BootStrapper>
```
After the changes, clean and rebuild solution, the error will go away.

Hope it helps!

**Comment by partmachine** [comment]
@NEKIT-Boss,
Thanks for your reply, I already figured out it should like this, I think I was looking at the wrong sample code. Thanks anyway

**Comment by NEKIT-Boss** [comment]
@renevangeffen, close the issue then, if everything is OK.
