### ISSUE TITLE
No default styling for Hamburger menu

### ISSUE THREAD

**Issue by partmachine** [Windows-XAML/Template10#1325]
I'm trying out the Hamburger menu, I'm using the instructions from the documentation, when I run the project all I see is the Hamburger button left top, no flyout or buttons (1 primary and 1 secondary). To see the menu buttons and flyout I have to explicitly set the colors (taken from documentation) on the control but even then the control is not behaving properly (I gues I have to set all colors defined on the control to get proper hover and select behavior). When I use Blend for VS I can see that all brushes used by the control are null. I expected the control to have some default styling, do I need to define the style or a theme somewhere? Also the control does not show in the designer. My project builds without any errors.
What I'm I missing here? Thanks

**Comment by mvermef** [comment]
not sure what you are seeing out a screenshot it works fine here.

**Comment by partmachine** [comment]
@mvermef Thanks for your reply, Below a screenshot of the control without any colors set:
The button is in the mainpage.
![ss](https://cloud.githubusercontent.com/assets/10388192/20767250/c43ee5ac-b739-11e6-8092-06bccec27282.png)

Below the XAML for the control with colors:
![code](https://cloud.githubusercontent.com/assets/10388192/20767689/94ae8bba-b73b-11e6-8a8c-afcd38975671.png)

and the resulting page:

![ss2](https://cloud.githubusercontent.com/assets/10388192/20767526/d0b1e374-b73a-11e6-8b25-e2007b3e869a.png)
As you can see no buttons appear, when I click around a bit the buttons sometimes do appear.

**Comment by JerryNixon** [comment]
You must set `AccentColor` at a minimum to get any styling.

**Comment by partmachine** [comment]
@JerryNixon Thanks for your reply. I'm sorry to see you've invalidated this issue and I think your answer is wrong. You shouldn't have to set AccentColor to get any styling, AccentColor defaults to SystemAccentColor in the Style Resource defined in [HamburgerMenu.xaml](https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Themes/HamburgerMenu.xaml).
Unfortunately [HamburgerMenu.xaml](https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Themes/HamburgerMenu.xaml) is not included in [generic.xaml](https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Themes/Generic.xaml) and so never makes it into the library hence there is **No default styling for Hamburger menu**

**Comment by JerryNixon** [comment]
HamburgerMenu is not a custom control, it is not part of generic, it is a User Control.
