### ISSUE TITLE
Change EllipsisIcon Glyph

### ISSUE THREAD

**Issue by mjmeans** [Windows-XAML/Template10#1329]
Is there a way to change the EllipsisIcon Glyph while using the NuGet package (i.e. without rebuilding the library)?

**Comment by JerryNixon** [comment]
From where? The CommandBar?

**Comment by mjmeans** [comment]
Sorry, missed your question. I want the EllipseIcon that drops down the secondary commands to be a different icon instead of three dots. The secondary commands will be Shutdown and Restart. Since my app is a headed app for Windows 10 IoT that doesn't include a desktop; the user needs a way to shut down or reboot. The secondary commands on the title bar is the perfect place for it, but I don't see any way to set its glyph. I need the glyph to be the typical power icon instead of three dots.

**Comment by mvermef** [comment]
http://stackoverflow.com/questions/34342022/set-icon-on-secondarycommand-of-commandbar

This has nothing to do with this framework.  The usercontrol PageHeader is a commandbar with extra clothing to make it fit right.   The above link may help get you in the right direction, I think it is what you want but it requires making control Template changes which would be for those that want it for their app, not the framework.    CommandBar is a UWP control therefore the ellipsis is Microsoft default, it is customizable with deep control template monkey business, don't believe its scope is based in this project.  e.g. extreme use case.
