### ISSUE TITLE
Cannot find a Resource with the Name/Key ExtendedSplashBackground 

### ISSUE THREAD

**Issue by RomeoPavoni** [Windows-XAML/Template10#133]
in Splash.xaml there is an error on <Grid Background="{StaticResource ExtendedSplashBackground}">:

An exception of type 'Windows.UI.Xaml.Markup.XamlParseException' occurred in mscorlib.ni.dll but was not handled in user code

WinRT information: Cannot find a Resource with the Name/Key ExtendedSplashBackground [Line: 11 Position: 11]

Additional information: The text associated with this error code could not be found.

Cannot find a Resource with the Name/Key ExtendedSplashBackground [Line: 11 Position: 11]

If there is a handler for this exception, the program may be safely continued.

**Comment by JerryNixon** [comment]
Please get latest from GitHub and verify this error. I cannot reproduce it.
