### ISSUE TITLE
Template 10 for Visual Studio 2017 RC

### ISSUE THREAD

**Issue by julienshepherd** [Windows-XAML/Template10#1330]
![2016-12-03](https://cloud.githubusercontent.com/assets/20776298/20859788/fbe58ac6-b971-11e6-92ad-658bf5be7ca5.png)
I don't know if I did something wrong, yet I cannot find the Template 10 extension for Visual Studio 2017 RC.

Do you guys know if it's available or if it isn't, do you plan to release Template 10 for VS 2017? 

Thank you,
Julien

**Comment by mvermef** [comment]
Because it doesn't exist...

**Comment by JerryNixon** [comment]
Usually we wait for RTM, but I have it working 2017 here locally. I'll test a little more next week and publish. Here's the problem. They changed the structure of the projects in 2017. If I change the VSIX to the 2017 structure then it will be weird in 2015. If I leave it right for 2015 then it is weird in 2017. If I create a second VSIX then, now, I am splitting the thing up so it is harder for developers to find. My inclination is to always support the latest. And I'll likely make it right for 2017 and strange for 2015. 

But, if you have any opinions, I am open.

**Comment by dschmid** [comment]
Just found this within the release notes to VS 2017 RC [(https://www.visualstudio.com/en-us/news/releasenotes/vs2017-relnotes)]

> _Users will be warned when trying to install an extension that was not built using the new VSIX format. The old VSIX format does not specify prerequisites needed and may fail to work if those prerequisites are unavailable in Visual Studio 2017 RC. The new VSIX format is backwards compatible and can target past versions of Visual Studio up until Visual Studio 2012._

This would solve everything. It would take away the need to wait for RTM and it would make it possible to have only one development branch for all versions down to VS 2012. At least that is what I think this paragraph wants to tell us ;)

Hope MS can hold this claim...

**Comment by dxh9845** [comment]
Any updates on this? Starting my UWP development but downloaded VS2017 RC and now I can't get all the niceties of Template10. Thanks!

**Comment by mvermef** [comment]
Cut and paste?

**Comment by harvinders** [comment]
Any plan to release the extension for VS 2017, now that it is RTM?

**Comment by florianmonfort** [comment]
Any update?

**Comment by MrChilBoy** [comment]
C'mon @JerryNixon , help us ride the wave of enthusiasm here! Just release what you have and we'll let you know how good it is :)

**Comment by helmut-steiner** [comment]
I also jumped ship to VS 2017. Any news?

**Comment by QuentinSc** [comment]
Up?
