### ISSUE TITLE
Anyone care to help with this coding conundrum?

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#1331]
Please note this is not Master

https://github.com/Windows-XAML/Template10/blob/UpdateNav/Template10%20(Library)/Services/NavigationService/NavigationService.cs#L473

I can't seem to call async operations from the updated NavService.

Does anyone @Windows-XAML/contributors see what I am doing wrong?

Thanks.

**Comment by tibitoth** [comment]
My guess is something is not okay around the `NavigateAsync` method called with `ConfigureAwait(false)` in the `Navigate` method.

https://github.com/Windows-XAML/Template10/blob/UpdateNav/Template10%20(Library)/Services/NavigationService/NavigationService.cs#L184

**Comment by mvermef** [comment]
Will look tomorrow no computer close...

**Comment by JerryNixon** [comment]
Thank you @totht91. Problem solved.

**Comment by tibitoth** [comment]
How did you solve it? :)

**Comment by JerryNixon** [comment]
Changed the synchronous methods. 

`NavAsync().ConfigureAwait(false).GetAwaiter().GetResult();` 
to `NavAsync().ConfigureAwait(true);`
