### ISSUE TITLE
HamburgerMenu active for keyboard/controller navigation when in fullscreen mode

### ISSUE THREAD

**Issue by schuettecarsten** [Windows-XAML/Template10#1334]
Even when in fullscreen mode, the HamburgerMenu is still active for keyboard and controller navigation. This might cause strange behaviour when a hamburger button is focused, then then menu is hidden using fullscreen mode and user presses Space, Tab or Shift+Tab and then Space.

In fullscreen mode, HamburgerMenu should be removed from Tab navigation and not react on actions.
Merge request will follow soon.

**Comment by JerryNixon** [comment]
Test carefully. And if you hurry I will get it into 1.1.13

**Comment by schuettecarsten** [comment]
This needs lots of testing, it is more complex then expected. Removing it from tab navigation is not enough, buttons have to be set to Enabled=False in fullscreen mode. Need some more days for PR, sorry.

**Comment by darenm** [comment]
Have you tried it with the Xbox Controller...? That adds a lot of complexity too.

**Comment by schuettecarsten** [comment]
No, not yet. Xbox will be the next step for the application. I expect some updates to the HamburgerMenu to make it work in Xbox with deactivated Mouse mode.

**Comment by erossetto** [comment]
I sumbled upon this same problem.

@schuettecarsten: are you still working on this?

**Comment by schuettecarsten** [comment]
Yes, will add PR tonight.
