### ISSUE TITLE
Question: how to disable the Hamburger menu/shell on certain views?

### ISSUE THREAD

**Issue by darshanrampatel** [Windows-XAML/Template10#134]
I have a login page that I want to show upon App launch - this obviously should not have the hamburger menu. How can I hide this?

I have tried setting the following in App.xaml.cs
`Window.Current.Content = new Views.LoginPage();` 
but I can't figure out how to re-enable the shell.

I am unable to use the below, e.g. in my MainPage:
`var nav = NavigationServiceFactory(BackButton.Attach, ExistingContent.Include);
            Window.Current.Content = new Views.Shell(nav);`

Is this currently supported?

**Comment by mdtauk** [comment]
I know it doesn't address the issue directly, but what about replacing the split view pane contents with the login form, and open the split view pane when opening the app when the user is not already logged in

**Comment by dotnetnoobie** [comment]
If I understand your question/problem correctly.

NavigationServiceFactory is on the BootStrapper class, so you cannot access it like you have above from the MainPage class

you can access it from your MainPage class (or basically anywhere) like this

var nav = BootStrapper.Current.NavigationServiceFactory(BackButton.Attach, ExistingContent.Include);

But by the time your app has already showed the login screen etc there should already be a NavigationService created by the Bootstrapper 

so you can also get the existing NavigationService like this 

BootStrapper.Current.NavigationService

which returns is this property from the BootStrapper class 

```
    public NavigationService NavigationService
    {
        // because it is protected, we can safely assume it will ref the first view
        get { return WindowWrapper.ActiveWrappers.First().NavigationServices.First(); }
    }
```

**Comment by JerryNixon** [comment]
I am happy to tell you that there is a new sample in the Solution dedicated to Search and Login scenarios. This requires some significant enhancement to HamburgerMenu so what you find in Nuget today will not have this capability, you will need to use the source in NuGet.

**Comment by JerryNixon** [comment]
I also want to point out to you that changing the Window.Content is the right thing to do in your given scenario and approach. Just keep an in-memory reference to the original content. The new content (your login screen) should be a user control for simplicity sake. Don't use a Frame; that would be overkill for this scenario. That being said, the approach in the sample is the simpler, easier approach.

**Comment by JerryNixon** [comment]
The NavigationServiceFactory, by the way, is intended for similar scenarios - even if not exactly this one. It was actually created to support multiple window scenarios, but this one is fine, too. Creating a new Frame (and therefore a new NavigationService) can be done simply by calling Bootstrapper.Current.NavigationServiceFactory(). At that point, however, keeping track of the NavigationService is the responsibility of the developer. Again, this is just information and not what I recommend to create a Login screen.

**Comment by JerryNixon** [comment]
One final thing is that every HamburgerButtonInfo has an IsEnabled property.

**Comment by darshanrampatel** [comment]
Thanks all!
