### ISSUE TITLE
Clipped Image/Logo in Settings About Pivot on Windows 10 Mobile Only

### ISSUE THREAD

**Issue by myokeeh** [Windows-XAML/Template10#1340]
I can't figure this out. The image/logo shows up clipped/cropped to the top left portion of the image on Windows 10 Mobile. Lumia 950.

**Comment by JerryNixon** [comment]
Certainly, you should provide a screen capture, dude.

**Comment by myokeeh** [comment]
Sorry. This is a non-issue.
