### ISSUE TITLE
FrameFacade.ForwardStack?

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#1344]
@JerryNixon - I understand that **FrameFacade** is replacing **Frame**, but unlike Frame,  FrameFacade doesn't seem to ~have~ expose the **FrameFacade.ForwardStack** property. How to get to ForwardStack with Navigation, say you want to clear froward navigation -- a desirable feature when a task is done with some pages and not to be navigated to again? Am I missing something obvious?

[Later] Okay, I get it -- it's made [internal here](https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Services/NavigationService/FrameFacade.cs#L93). Is this intentional?

**Comment by JerryNixon** [comment]
Thanks. Well. Hmm. Should Back and ForwardStack both be public on FrameFacade? I don't see why not. If you wreck your own app, that's up to the developer, right?

**Comment by dg2k** [comment]
Wreck? ForwardStack, used responsibly, can bring order to chaos. Imagine navigating away from MainPage to do a one-off startup task (login, install config, etc with user interaction). Once this is done you'd want the forward nav history to disappear.

Yes, there are other workarounds but `nav.FrameFacade.ForwardStack?.Clear()` is a single-liner that does the job in a concise manner. Likewise, **BackStack** can come handy. Please make both **public**.

[Later] @JerryNixon -- made it a click away for you with PR #1345.

**Comment by JerryNixon** [comment]
Sorry @dg2k I didn't mean using the ForwardStack would wreck your app. I meant the reason I encapsulated it was to keep you from wrecking your app. But that was stupid. The developer is smart enough not to wreck their own app (or to do it). Template 10 does not care about the ForwardStack or the BackStack. So there was no good reason to keep it internal.
