### ISSUE TITLE
Introducing SecretService

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#1346]
I have documented it here: https://github.com/Windows-XAML/Template10/wiki/Services#secretservice

**Comment by dg2k** [comment]
@JerryNixon  -- I use PasswordVault() in the Windows.Security.Credentials ns a lot and this is a wonderful addition to T10 for security conscious folks. Thank you!
... sure the name SercretService doesn't cause some copyright infringement? Only kidding ;-)

**Comment by mvermef** [comment]
or the NSAs ears are twitching.... 😮

**Comment by tibitoth** [comment]
Where is this service's code?

**Comment by JerryNixon** [comment]
Hither https://github.com/Windows-XAML/Template10/tree/master/Template10%20(Library)/Services/SecretService

**Comment by JerryNixon** [comment]
There is a bug in the current version if you attempt to store string.Empty as a secret. I have fixed this in a branch and will merge it soon. Probably after my vacation.

**Comment by michaelhutchful** [comment]
I can't find the SecretService in the Nuget package. How can I use it?

**Comment by yanxiaodi** [comment]
Very cool! This function is helpful to store some sensitive values like token, etc.

**Comment by mikea314** [comment]
The SecretHelper class doesn't persist modified secrets due to a missing ' _vault.Add(credential) ' line:

    public void WriteSecret(string container, string key, string secret)
        {
            if (_vault.RetrieveAll().Any(x => x.Resource == container && x.UserName == key))
            {
                var credential = _vault.Retrieve(container, key);
                credential.RetrievePassword();
                credential.Password = secret;  
                _vault.Add(credential); <==== Required to persist change
            }
            else
            {
                var credential = new PasswordCredential(container, key, secret);
                _vault.Add(credential);
            }
        }

**Comment by dg2k** [comment]
You're correct. I thought I made a PR on this a while back and somehow fell thru the crack (see bottom of #1503 and can't figure out what really happened then). There was a lot changing at the time.
