### ISSUE TITLE
CustomTitleBar breaks UnitTest projects

### ISSUE THREAD

**Issue by erossetto** [Windows-XAML/Template10#1348]
Probably related to #464 and #1028. Can't figure out a fix.

I'm using the Hamburger template and everything is dandy until I use the custom titlebar.

Steps:
- Create new App with Hamburger template
- Add UWP UnitTest project, reference App
- Run app/tests, everything OK.
- [Add CustomTitleBar styles to App.xaml](https://github.com/Windows-XAML/Template10/wiki/Controls#customtitlebar)
- Run tests, runner blows up with:

> ------ Run test started ------
> Updating the layout...
> 
> Checking whether required frameworks are installed...
> 
> Registering the application to run from layout...
> 
> Deployment complete (0:00:01.086). Full package name: "b4a8dc98-4c0c-4642-aa28-24ae953fab8e_1.0.0.0_x86__9p85fwwdzb3vm"
> 
> A user callback threw an exception.  Check the exception stack and inner exception to determine the callback that failed.
> ========== Run test finished: 0 run (0:00:03.5759975) ==========

**Comment by JerryNixon** [comment]
I wonder if the code simply can't work in a test harness.

**Comment by erossetto** [comment]
@JerryNixon: it doesn't even reach the custom title bar code, the exception happens in the UnitTest App constructor.

I've managed to reproduce this same behavior without using T10, just creating an empty App with an empty Control and referencing it in App.xaml blows up the test runner.

```
namespace App1
{
    public class CustomControl : Control
    {
        public CustomControl()
        {

        }
    }
}
```

```
<Application.Resources>
    <Style TargetType="local:CustomControl">

    </Style>
</Application.Resources>
```

What a bummer

**Comment by erossetto** [comment]
Ok another update. I made it work without T10.

I think the problem is the Bootstrapper class.

Giving up for now :(

**Comment by JerryNixon** [comment]
Point me to what's the issue. Also, what version of T10 are you using in your project.json?

**Comment by erossetto** [comment]
@JerryNixon: I'm using 1.1.12

Following on my repro (without T10) adding:

```
<Application.Resources>
    <Style TargetType="local:CustomControl">

    </Style>
</Application.Resources>
```

to UnitTestApp.xaml fixes the test runner, however with T10 I see the same exception I posted initially.
