### ISSUE TITLE
PageHeader Improvements (Mark 2)

### ISSUE THREAD

**Issue by callummoffat** [Windows-XAML/Template10#135]
Would it be possible to improve PageHeader in the following ways:
1. PageHeader changes to different color set when window is inactive (similar to window title bar).

**Comment by mdtauk** [comment]
Would you declare the colour in the OnNavigate code?  What will the default be?

**Comment by JerryNixon** [comment]
This is an interesting idea. Pretty unusual. Before we continue, first give me the code to detect inactive. Then we can talk about updating the control.
