### ISSUE TITLE
KeyBehavior

### ISSUE THREAD

**Issue by sjb-sjb** [Windows-XAML/Template10#1350]
OK, I'll confess I didn't actually try this. I just read it and wept, after struggling with Escape and TextBox myself and then hoping that KeyBehavior would save me.

KeyBehavior uses KeyDown / KeyUp events, which will not work for Escape (and other system keys) on an AutoSuggestBox. The control absorbs these keys and the events don't fire. You have to use UIElement.AddHandler with true for the 3rd argument if you want to handle it all.

What I'd like to have is a compendium of all the system built-in handling and actions associated with Escape and Return. I'm trying to catch them on my page and use them for Revert and Save. It's giving me the dickens of a time. So if you know of anything existing on this I would certainly be interested. Otherwise I guess I'll just have to keep researching it one byte at a time ... 

sjb

**Comment by JerryNixon** [comment]
I think the trouble is that the escape key is not something an individual input element can sense. Instead, I think you need to listen to system-level events. Instead of an element behavior, try the keyboard service that listens at a significantly higher level. 

This might work. 

````
var helper = new Template10.Services.KeyboardService.KeyboardHelper();
helper.KeyDown = e =>
{
    if (e.VirtualKey == VirtualKey.Escape)
    {
        // do something
    }
};
````

**Comment by JerryNixon** [comment]
Worth pointing out now that if you want to use Windows Key + anything, it will never work. That is to say, I could never get it to work, and would love a pointer if you can.

**Comment by sjb-sjb** [comment]
Thanks for the tips. 
The uielement.addhandler does hear esc keys.

I can't comment about the windows key as I haven't tried it, but the code in your keyboard helper smelled pretty good.
