### ISSUE TITLE
Request for Code Review for new Service

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#1352]
Hi @Windows-XAML/template-10-developer-community 

I am working on a new service called TransferService which can either inline (using `HttpClient`) or queue (using `BackgroundTransfer`) the upload/download of a file (`StorageFile`). I have not been able to sufficiently test this service, and have put the source up on a Github gist so you guys might pull it down and include it in your projects to test. If there's enough consensus around this new service, I would very much like to include it in 1.1.13 before the end of the year. 

https://gist.github.com/JerryNixon/1d2265d9293cb268d90a479c968f37ea

// Jerry

**Comment by plettb** [comment]
Sounds like a good idea, though i don't know if I'll get any time to work on it.  Is it reasonable to assume that this service could be used, for example, to send log files back to the support team?  Do you have a server-side target in mind?

Brad.

**Comment by rpedretti** [comment]
I guess I'll be able to test it at my job since I'm building a app that needs uploading / downloading images. But I don't think I'll have a review by the end of the year

And I have to upload as a multipart form data with x-auth-token with a very specific boundry, so it might be TOO much specific.

**Comment by akshay2000** [comment]
If I'm not wrong, this service will be awesome for (Monocle Giraffe)[https://github.com/akshay2000/MonocleGiraffe] since it does a lot of downloading and uploading. I'll give it a spin soon.

**Comment by julienshepherd** [comment]
I think the service will add lots of value, unfortunately I'll not be able to test it since my only project uses OneDrive SDK.

**Comment by darshanrampatel** [comment]
I'm in a similar position to @rpedretti; this would be something I really could use in my apps but won't be able to test before the New Year sadly...
