### ISSUE TITLE
Question:  Version Points

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#1353]
@JerryNixon -- Not really an issue, rather a simple question.
I was hoping `git tag -l` would return info like release version points for T10 but only V0.04 and V0.05 show up. Is there any way to find out the released version points? If not available, can the release version points be tagged in (I think this is possible).  I wanted to go back and check something I did and in which version ... and needed the release version road map.

**Comment by tibitoth** [comment]
Please do this, because now we don't able to see a specific versions codebase.

**Comment by JerryNixon** [comment]
What are you even talking about?

**Comment by tibitoth** [comment]
In git you can tag commits (more specific you tag the codebase's actual state where the latest commit is the tagged). In the gitflow workflow the convention is that on every release you create a tag with the release version's name, so we are able to find the published codebase for every specific version.

**Comment by JerryNixon** [comment]
Still not sure. How do you do this?

**Comment by tibitoth** [comment]
Like this: https://help.github.com/articles/creating-releases/
