### ISSUE TITLE
OnNavigatedTO is called twice

### ISSUE THREAD

**Issue by hansenConsult** [Windows-XAML/Template10#1358]
This is a regression error from 1.1.12 to 1.1.13 Preview.

In a page I have the following:
                var nav = WindowWrapper.Current().NavigationServices.FirstOrDefault();
                nav.Navigate(typeof(FormsPage), parameter);

In the FormsPage OnNavigatedTo is called twice. The first time with the parameter. The second time with parameter=null. Obviously my action based one the parameter is cancelled.

I had no problems with 1.1.12

**Comment by dg2k** [comment]
If this is happening for the first page on startup (usually MainPage.xaml, then use `OnNavigatingFromAsync` as shown below and your problem will be gone. This is as a result of how OnNavigatingFromAsync cancellation works BUT the special case of first page on startup is not accounted for (hence shows up as a bug resulting in MainPage navigating away from itself and coming back to MainPage (hence two hits). If nav started from another page, all is well.

Here is the code for OnNavigatingFromAsync. If I have time, I can elaborate on this but @JerryNixon can tell a better story of what is going on here.
    
    public override async Task OnNavigatingFromAsync(NavigatingEventArgs args)
    {
            var selfNav = args.TargetPageType == typeof(Views.MainPage); // assumes first page type is MainPage
            if (selfNav)
            {
                args.Cancel = true;
            }

            // your code below.
    }

**Comment by hansenConsult** [comment]
Sorry, but your suggestion made no difference. 

OnNavigatingFromAsync is called twice. The first time at startup with selfNav true.

The second time at navigating to the FormsPage with selfNav false.

However I still get two calls to OnNavigated To in the FormsPage class

**Comment by dg2k** [comment]
My suggestion is to stop the unnecessary navigation from itself (which will happen only at startup), which otherwise will end up loading again. That is, the code in `OnNavigatingFromAsync` will stop the unnecessary navigation. Note that if your first page is Views.FormsPage, you must change the Views.MainPage to yours. In short, the page Type in question is one launched from App.xaml.cs which is usually MainPage but if different in your case change it in `OnNavigatingFromAsync` accordingly.

**Comment by JerryNixon** [comment]
I will have to look into this after I get back from vacation. Even if @dg2k is correct, it sounds like the current implementation is wrong and an easy stumbling block to developers trying to use T10. I would rather make this as fool proof as possible - not saying you are a fool @hansenConsult, just making a point.

**Comment by schuettecarsten** [comment]
I can confirm this behaviour with 1.1.13-preview20161207. It looks like the HamburgerMenu fires two navigation calls. In the past, there was a comparision if the current page/parameter is already active, so the second navigation request was ignored.
