### ISSUE TITLE
Validation 

### ISSUE THREAD

**Issue by sjb-sjb** [Windows-XAML/Template10#1361]
The index on the Template 10 documentation page fooled me into thinking that this otherwise fantastic library does not have any validation features. But it does, just in a separate library. 

I wonder if the omission might reflect the relative newness of the validation work. Is it fully ready for prime time? There are two areas where I have questions. 

One is how well does it play with Microsoft recommended data access technology, Entity Framework? It seems suspect to me that Value and OriginalValue are not kept in the entity. Will OriginalValue always match the original value in the entity? How is it updated on a save? And, how does this approach enable us to validate a Delete or Add?

A second question area is the need for context coordination. One way in which this is manifested is in the need for context information during validation -- for example to test the uniqueness of names. True, you can pass the context into the Validation delegate as a free local variable. But is there a more coherent / systematic way to do this? Another way the need for context coordination is manifested, is when editing multiple entities. IsValid and IsDirty are needed on an aggregate level so that a list save can be done (e.g. using the implicit transaction feature of EF Core). 

Another important context coordination feature is the ability to notify the set of entities saved or reverted, including add or delete. This is needed for flicker-free updating of ListView.   While this is not directly a validation step, it ties in closely given that reverting is implemented is T10 by the validation code and given the need for other context coordination in validation.

**Comment by sjb-sjb** [comment]
If I can add one other area for investigation, there needs to be a mechanism for converting to /from strings. Otherwise the binding of, for example, a text box to a number property will throw an exception that is silently dropped, resulting in an error that is not captures by the validation process. These conversion errors have to be dealt with and not mixed up with the "normal" errors. They hide rather than join the normal error list.

**Comment by sjb-sjb** [comment]
PS do you know of anything that does all this out-of-the-way?

**Comment by sjb-sjb** [comment]
... Box?

**Comment by mvermef** [comment]
This is actually a really nice feature placed out there, since out of the box UWP has no validation mechanisms, that wpf or Silverlight have (IDataErrorNotify).   As far as errors related to change of type there are converters in T10 for changing the type.  As for interop with underlying storage frameworks, they work, but doesn't mean they are attached at the hip.

**Comment by JerryNixon** [comment]
Hey @sjb-sjb thanks for checking in with validation. @mvermef is right that our validation library solves many problems not addressed by `IDataErrorNotify`. Most of what you are asking for, it sounds to me on initial read, should be accomplished by the view-model itself. Not the model. That being said, I might just need a little more information. I am yet to test it with EF Core. You can expect some delayed responses for the next week as I am about to travel. We'll look into what we can as soon as we can otherwise.

**Comment by sjb-sjb** [comment]
Thanks for your comments. I have been working on this the past little while. I agree philosophically this is a view-model question, and I would comment that the use of PropertyChanged in the T10 approach is a flag to me that there is some view-model work being done in the model. 

As a high-level description, the approach I have taken is to have view-model classes for the DbContext and for each entity. The entity view models are created by the context view model, which uses a hash table to look up and return any existing view model for the entity. The context view model implements save and revert commands (this is appropriate to centralize because these commands operate on all modified entities). The context view model  notifies the entity view models of the save or revert event (before and after each). The entity view models can then correctly notify the change in either original value or current value that results from the save or revert event. For efficiency, entity view models only listen for the SaveOrRevert event if they have been modified -- there can be a large number of entity view models when a ListView is used, for example. 

An additional refinement in this design is: the context view model disposes the entity view models when the context view model is disposed; and the entity view model notifies the context view model when the entity view model is disposed. In this way we can maintain and clean up the hash table as well as make sure that the entity view models are not orphaned when the context view model evaporates. I also have the entity view model dispose the entity (if it is disposable) but this is not essential to the view model design. 

I am also using T4 to generate a derived view model class which implements the calls to get or set the value. This is essential if you are implementing an entity view model because the entity view model should have properties corresponding to the properties of the entity. 

As relates to having a view model for DbSet, my approach is to wrap the DbSet.Local and add filtering and sorting. There are some limitations which you can read about in the issue I recently opened under EF Core.  

From your reply I understand this is in fact new work and there is nothing existing that covers all the above. 

My real question on the Property<T> approach with EF Core is the efficiency. You have an allocation for each property of the model, which takes time and burdens the garbage collector. Also the get / set results in a method call, and I am not sure that when loading data from the database it will be as efficient as blitting the bits from the database into the entity (which is what I hope that EF Core does when the get/set are defaults .... I don't know but I hope so).

**Comment by sjb-sjb** [comment]
PS, on mvermef's comment about converters for property values, I agree these are useful however I don't think they solve the problem of capturing the conversion error in the validation message. This is an aspect that can be dealt with in the approach that I outlined above.

**Comment by sjb-sjb** [comment]
I've seen the new work being done in your validation classes and I think it's great. 

I've also been doing some development on this and I wanted to give you a heads up on one point. 

The IsDirty state for an entity framework object is different from that for a normal object. Your design is for non-EF objects, where IsDirty relates to whether the value of a property is different from it's original value. But when you create a new object and attach it to an EF context, the entire object is dirty even though each property is the same as it's original value. By "dirty" what I mean is that saving changes will result in a change to the database. Same thing if you delete an object in the context -- all the property values are the same as the originals but the object is dirty. 

One other thing I found out in my research is that we can still use Validator.TryValidateObject to very good effect. 

Please let me know if this is helpful for you. 

sjb

P.S. My concerns about efficiency were allayed when I realized that the whole binding system only works with reference types, not value types. So, it's not very efficient to allocate a separate object for each property, but there is no way to get around it.

**Comment by sjb-sjb** [comment]
Looking back on my comments above, I feel that I've been blabbing away about this forever. It's been a journey for me but it is finally starting to come together. 

I now agree with having the view model combined with the entity, or at least attached to it. Otherwise it gets too complicated. Along with that I no longer feel that view models have to be connected to the context. 

One thing I found out is that it may be necessary to asynchronously load data needed for validation, such as a list of valid names. 

One way to deal with this is to have Validate be a fire and forget background method. One can also throttle the incoming Validate requests to keep the load reasonable. 

About validation in the Entity Framework, one can take advantage of two features. 

One is the change notification feature described in a great blog by Arthur Vickers, https://blog.oneunicorn.com/2016/11/16/notification-entities-in-ef-core-1-1 . It probably makes sense to use this feature since we are notifying properties anyway. 

The other is the ability to assign backing fields. This can be used to gain efficiency during materialization by keeping the property data in normal fields in the class instead of in separate objects, while still intercepting the property calls to do as you wish. 

Again, hoping this is useful. 

sjb
