### ISSUE TITLE
Ugprading to 1.1.13-preview-20161207 breaks Navigation events

### ISSUE THREAD

**Issue by apollyonbob** [Windows-XAML/Template10#1362]
I started in 1.1.12 and things were mostly working okay, ran into some issues with bindings after navigation. So I thought I'd upgrade to 1.1.13-preview-20161207 to see if that changed anything. This caused even more problems.

It doesn't throw any errors, but my OnNavigatedTo function never gets called.
`public async Task OnNavigatedToAsync(Object parameter, NavigationMode mode, IDictionary<String, Object> state)`

Am I missing something?

**Comment by JerryNixon** [comment]
Are you using a custom ViewModelBase?

**Comment by apollyonbob** [comment]
I'm not using ViewModelBase at all. They all implement INavigable at the moment. Is ViewModelBase required for Navigation in 1.1.13?

**Comment by JerryNixon** [comment]
Hi @apollyonbob no, not at all. When I open the solution and run one of the sample solutions, their OnNavTo is getting called correctly. THAT is what made me ask. Could you give me a few more details as to what is going on in your case?

**Comment by apollyonbob** [comment]
I'm using custom view models that implement INavigable. It almost works as expected in 1.1.12, but I've got an odd problem with the bindings (they sometimes seem to fail).

So! I thought I'd upgrade to 1.1.13. The upgrade seems to succeed as normal, but then the OnNavigatedTo function on the ViewModel never gets called. No error is thrown that I can see.

I don't know what else I can check. It goes from working on 1.1.12 to not working on 1.1.13. Is there anything in particular I can try to check, given that there's no errors?

**Comment by apollyonbob** [comment]
If I put it on Mixed mode, I do notice this in the output: 
Invalid parameter passed to C runtime function.
Invalid parameter passed to C runtime function.

But again, no exceptions, and no errors.
