### ISSUE TITLE
Template10.Mobile portable library

### ISSUE THREAD

**Issue by schuettecarsten** [Windows-XAML/Template10#1372]
Please change assembly type of Template10.Mobile from portable to "real" universal class library. Also define x64, x86 an ARM targets instead of AnyCPU. There is no need to use portable libraries here and these libraries cause some trouble when using VS2017RC yet.

Portable Library bug report:
https://developercommunity.visualstudio.com/content/problem/9418/portable-libraries-will-build-as-release-in-debug.html

**Comment by JerryNixon** [comment]
This will be deleted soon
