### ISSUE TITLE
Hamburger Menu DisplayMode

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#1381]
This does not work 

````
    <Controls:HamburgerMenu x:Name="MyHamburgerMenu"
                            VisualStateNormalDisplayMode="Inline"
                            VisualStateNarrowDisplayMode="Inline"
                            VisualStateWideDisplayMode="Inline"
                            >
````

And it should.

**Comment by edyg023** [comment]
I can verify that this isn't working.  Any idea when this will be fixed and when it will be pushed out into a new package?

**Comment by dg2k** [comment]
Unless we are working on a different codebase, the above works for me. Of course, you need to make PaneWidth adjustment in response to `DisplayModeChanged` event which was obvious when we were working on VisualStateXXXXDisplayMode and related DPs.

As an aside, I see no reason why **Inline** would be used with **VisualStateNarrowDisplayMode** when OverLay is more appropriate. I see **Inline** (or **CompactInline**) where screen space is not an issue (e.g., desktop) while Overlay where screen space is at a premium (e.g., mobile).

UPDATE: Checked with HamburgerMenu project and it works, even with a Mobile Emulator.

**Comment by JerryNixon** [comment]
@dg2k paste ges your HamMenu XAML for me, pls.
