### ISSUE TITLE
Issue installing NuGet package

### ISSUE THREAD

**Issue by aerostudios** [Windows-XAML/Template10#1383]
I'm creating a new project to separate out the view models.  I'm running into an issue when .NET versions.  What is the highest version compatibility supported by this package?  Do I need to take the source and update it to support newer versions of the platform?

Output from Package manager:

Restoring packages for xxx.ViewModels'.
Restoring packages for C:\Code\xxx\xxx.ViewModels\project.json...
Detected package downgrade: Microsoft.NETCore from 5.0.2 to 5.0.0 
 xxx.ViewModels (>= 1.0.0) -> Template10 (>= 1.1.12) -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.2.2) -> Microsoft.NETCore (>= 5.0.2) 
 xxx.ViewModels (>= 1.0.0) -> Microsoft.NETCore (>= 5.0.0)
Detected package downgrade: Microsoft.NETCore.Portable.Compatibility from 1.0.2 to 1.0.0 
 xxx.ViewModels (>= 1.0.0) -> Template10 (>= 1.1.12) -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.2.2) -> Microsoft.NETCore.Portable.Compatibility (>= 1.0.2) 
 xxx.ViewModels (>= 1.0.0) -> Microsoft.NETCore.Portable.Compatibility (>= 1.0.0)
Detected package downgrade: Microsoft.NETCore from 5.0.2 to 5.0.0 
 xxxApp.ViewModels (>= 1.0.0) -> Template10 (>= 1.1.12) -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.2.2) -> Microsoft.NETCore (>= 5.0.2) 
 xxxApp.ViewModels (>= 1.0.0) -> Microsoft.NETCore (>= 5.0.0)
Detected package downgrade: Microsoft.NETCore.Portable.Compatibility from 1.0.2 to 1.0.0 
 xxxApp.ViewModels (>= 1.0.0) -> Template10 (>= 1.1.12) -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.2.2) -> Microsoft.NETCore.Portable.Compatibility (>= 1.0.2) 
 xxxApp.ViewModels (>= 1.0.0) -> Microsoft.NETCore.Portable.Compatibility (>= 1.0.0)
Detected package downgrade: Microsoft.NETCore from 5.0.2 to 5.0.0 
 xxxApp.ViewModels (>= 1.0.0) -> Template10 (>= 1.1.12) -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.2.2) -> Microsoft.NETCore (>= 5.0.2) 
 xxxApp.ViewModels (>= 1.0.0) -> Microsoft.NETCore (>= 5.0.0)
Detected package downgrade: Microsoft.NETCore.Portable.Compatibility from 1.0.2 to 1.0.0 
 xxxApp.ViewModels (>= 1.0.0) -> Template10 (>= 1.1.12) -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.2.2) -> Microsoft.NETCore.Portable.Compatibility (>= 1.0.2) 
 xxxApp.ViewModels (>= 1.0.0) -> Microsoft.NETCore.Portable.Compatibility (>= 1.0.0)
Detected package downgrade: Microsoft.NETCore from 5.0.2 to 5.0.0 
 xxxApp.ViewModels (>= 1.0.0) -> Template10 (>= 1.1.12) -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.2.2) -> Microsoft.NETCore (>= 5.0.2) 
 xxxApp.ViewModels (>= 1.0.0) -> Microsoft.NETCore (>= 5.0.0)
Detected package downgrade: Microsoft.NETCore.Portable.Compatibility from 1.0.2 to 1.0.0 
 xxxApp.ViewModels (>= 1.0.0) -> Template10 (>= 1.1.12) -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.2.2) -> Microsoft.NETCore.Portable.Compatibility (>= 1.0.2) 
 xxxApp.ViewModels (>= 1.0.0) -> Microsoft.NETCore.Portable.Compatibility (>= 1.0.0)
Detected package downgrade: Microsoft.NETCore from 5.0.2 to 5.0.0 
 xxxApp.ViewModels (>= 1.0.0) -> Template10 (>= 1.1.12) -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.2.2) -> Microsoft.NETCore (>= 5.0.2) 
 xxxApp.ViewModels (>= 1.0.0) -> Microsoft.NETCore (>= 5.0.0)
Detected package downgrade: Microsoft.NETCore.Portable.Compatibility from 1.0.2 to 1.0.0 
 xxxApp.ViewModels (>= 1.0.0) -> Template10 (>= 1.1.12) -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.2.2) -> Microsoft.NETCore.Portable.Compatibility (>= 1.0.2) 
 xxxApp.ViewModels (>= 1.0.0) -> Microsoft.NETCore.Portable.Compatibility (>= 1.0.0)
Version conflict detected for System.Collections. 
 xxxApp.ViewModels (>= 1.0.0) -> Template10 (>= 1.1.12) -> Microsoft.NETCore.UniversalWindowsPlatform (>= 5.2.2) -> System.ServiceModel.NetTcp (>= 4.1.0) -> System.Net.Primitives (>= 4.0.11) -> runtime.win.System.Net.Primitives (>= 4.0.11) -> System.Collections (>= 4.0.11) 
 xxxApp.ViewModels (>= 1.0.0) -> Microsoft.NETCore.Portable.Compatibility (>= 1.0.0) -> Microsoft.NETCore.Runtime (>= 1.0.0) -> Microsoft.NETCore.Runtime.CoreCLR-x86 (>= 1.0.0) -> System.Collections (= 4.0.10).
Template10 1.1.12 is not compatible with .NETPlatform,Version=v5.0.
Microsoft.Xaml.Behaviors.Uwp.Managed 1.1.0 is not compatible with .NETPlatform,Version=v5.0.
Microsoft.NETCore.Targets 1.0.2 is not compatible with .NETPlatform,Version=v5.0.
Microsoft.Win32.Primitives 4.0.1 is not compatible with .NETPlatform,Version=v5.0.
System.Diagnostics.StackTrace 4.0.2 is not compatible with .NETPlatform,Version=v5.0.
System.IO.IsolatedStorage 4.0.1 is not compatible with .NETPlatform,Version=v5.0.
System.Net.Http.Rtc 4.0.1 is not compatible with .NETPlatform,Version=v5.0.
System.Net.NameResolution 4.0.0 is not compatible with .NETPlatform,Version=v5.0.
System.Net.Sockets 4.1.0 is not compatible with .NETPlatform,Version=v5.0.
System.Net.WebHeaderCollection 4.0.1 is not compatible with .NETPlatform,Version=v5.0.
System.Net.WebSockets 4.0.0 is not compatible with .NETPlatform,Version=v5.0.
System.Net.WebSockets.Client 4.0.0 is not compatible with .NETPlatform,Version=v5.0.
System.Numerics.Vectors.WindowsRuntime 4.0.1 is not compatible with .NETPlatform,Version=v5.0.
System.Runtime.WindowsRuntime 4.0.11 is not compatible with .NETPlatform,Version=v5.0.
System.Runtime.WindowsRuntime.UI.Xaml 4.0.1 is not compatible with .NETPlatform,Version=v5.0.
System.Text.Encoding.CodePages 4.0.1 is not compatible with .NETPlatform,Version=v5.0.
Some packages are not compatible with .NETPlatform,Version=v5.0.
Template10 1.1.12 is not compatible with .NETFramework,Version=v4.6.
Microsoft.Xaml.Behaviors.Uwp.Managed 1.1.0 is not compatible with .NETFramework,Version=v4.6.
System.IO.IsolatedStorage 4.0.1 is not compatible with .NETFramework,Version=v4.6.
System.Numerics.Vectors.WindowsRuntime 4.0.1 is not compatible with .NETFramework,Version=v4.6.
Some packages are not compatible with .NETFramework,Version=v4.6.
Template10 1.1.12 is not compatible with .NETFramework,Version=v4.6 (win-x86).
Microsoft.Xaml.Behaviors.Uwp.Managed 1.1.0 is not compatible with .NETFramework,Version=v4.6 (win-x86).
System.IO.IsolatedStorage 4.0.1 is not compatible with .NETFramework,Version=v4.6 (win-x86).
System.Numerics.Vectors.WindowsRuntime 4.0.1 is not compatible with .NETFramework,Version=v4.6 (win-x86).
System.Net.Http.Rtc 4.0.1 provides a compile-time reference assembly for System.Net.Http.Rtc on .NETFramework,Version=v4.6, but there is no run-time assembly compatible with win-x86.
System.Runtime.WindowsRuntime 4.0.11 provides a compile-time reference assembly for System.Runtime.WindowsRuntime on .NETFramework,Version=v4.6, but there is no run-time assembly compatible with win-x86.
System.Runtime.WindowsRuntime.UI.Xaml 4.0.1 provides a compile-time reference assembly for System.Runtime.WindowsRuntime.UI.Xaml on .NETFramework,Version=v4.6, but there is no run-time assembly compatible with win-x86.
Some packages are not compatible with .NETFramework,Version=v4.6 (win-x86).
Template10 1.1.12 is not compatible with .NETFramework,Version=v4.6 (win-x64).
Microsoft.Xaml.Behaviors.Uwp.Managed 1.1.0 is not compatible with .NETFramework,Version=v4.6 (win-x64).
System.IO.IsolatedStorage 4.0.1 is not compatible with .NETFramework,Version=v4.6 (win-x64).
System.Numerics.Vectors.WindowsRuntime 4.0.1 is not compatible with .NETFramework,Version=v4.6 (win-x64).
System.Net.Http.Rtc 4.0.1 provides a compile-time reference assembly for System.Net.Http.Rtc on .NETFramework,Version=v4.6, but there is no run-time assembly compatible with win-x64.
System.Runtime.WindowsRuntime 4.0.11 provides a compile-time reference assembly for System.Runtime.WindowsRuntime on .NETFramework,Version=v4.6, but there is no run-time assembly compatible with win-x64.
System.Runtime.WindowsRuntime.UI.Xaml 4.0.1 provides a compile-time reference assembly for System.Runtime.WindowsRuntime.UI.Xaml on .NETFramework,Version=v4.6, but there is no run-time assembly compatible with win-x64.
Some packages are not compatible with .NETFramework,Version=v4.6 (win-x64).
Package restore failed for xxx.ViewModels'.
Package restore failed. Rolling back package changes for xxx.ViewModels'.
========== Finished ==========

**Comment by JerryNixon** [comment]
This is for UWP applications not Desktop. If you have a Desktop app, then consider Prism.

**Comment by aerostudios** [comment]
Err, this is a UWP app...  Started w/ the hamburger template, now trying to move the view models from the UWP app to a portable class lib, is that not an ok thing to do?
