### ISSUE TITLE
Master-Detail control needed.

### ISSUE THREAD

**Issue by FrayxRulez** [Windows-XAML/Template10#139]
Hey, I think that Template10 needs some built-in control to handle Master-Detail situations.

I've built one by myself with animations and other cool features. It uses NavigationService to handle navigation. Maybe can I do a pull request?

**Comment by JerryNixon** [comment]
Need a little more information on what you mean. Maybe post a screenshot here.

**Comment by mdtauk** [comment]
Sounds like they are talking about the Mail app behaviour when you compare the Desktop UI to the Mobile UI.  Selecting an email from the list, populates the preview pane on desktop, but navigates/transitions between the email list and the single email view.

**Comment by startewho** [comment]
Yeah,Like the Mail app. In the desktop view, it have two clumns.one column show the list, and the other column show the detail. These two columns are in one page.
And in the mobile view, The listview shown on a page , and the detail shown on another page. The detail is navigated by listview.
Really need a example like the mail app.

**Comment by FrayxRulez** [comment]
Yes, exactly what I was talking about. I've already created it, and I use it about in every project.

**Comment by JerryNixon** [comment]
Could you give me some pointers? What types of properties would this have?

**Comment by FrayxRulez** [comment]
Actually it is a ContentControl (for the "master part", eg a list of elements) with an `Initialize(string frameId)` method that generates (or recycles) a NavigationService using `BootStrapper.Current.NavigationServiceFactory`. Frame of the new NavigationService is placed in the right side of the control.

Here's attached a demo video:
https://youtu.be/dRV-d1N7VY8

It handles automatically states and transitions between pages.

**Comment by startewho** [comment]
It  would be nice if include this control, the Master-Detail have A wide range of uses.

**Comment by JerryNixon** [comment]
I think this is a sample, not a control. I will write it for you. Maybe it will turn into a control. Maintaining controls is sort of a pain tho. Fewer is better for T10.

**Comment by dotnetnoobie** [comment]
Maybe you could create a new project/Repository like a "T10-ToolBox" and put controls in it?

**Comment by zhengbomo** [comment]
hey @startewho, I have try some practice for Mester-Detial, but it doesn't work well ,could you share your Master-Detail demo, I have no idea for it, thanks

**Comment by FrayxRulez** [comment]
@zhengbomo I'll create a repository in my GitHub account :)

**Comment by pawcz1** [comment]
There's a nice sample of master/detail. Everything is ok, but I can't figure out how to get back from detail to master in narrow state by pressing hardware back button. Can you Guys help me out?

**Comment by zhengbomo** [comment]
I place master and detail view in two frame, on small window size, hide detail frame, you can see my app https://www.microsoft.com/en-us/store/apps/%e7%89%87%e5%88%bbuwp/9nblggh5z7wn

**Comment by zhengbomo** [comment]
@pawcz I place master and detail view in two frame, on small window size, hide detail frame, you can see my app https://www.microsoft.com/en-us/store/apps/%e7%89%87%e5%88%bbuwp/9nblggh5z7wn
