### ISSUE TITLE
Sample MultipleViews failing to compile

### ISSUE THREAD

**Issue by davefxy** [Windows-XAML/Template10#1392]
The MultipleViews sample in the Template10 library fails to compile. One of the lines in error is in MainPageViewModel.cs:
line 21 private readonly WindowWrapper wrapper = WindowWrapper.Current();

**Comment by JerryNixon** [comment]
I am going to ask @Viachaslau-Zinkevich if he sees the same.

**Comment by Viachaslau-Zinkevich** [comment]
I will check this, perhaps some API change caused this

**Comment by JerryNixon** [comment]
Thanks for looking, @Viachaslau-Zinkevich any luck?

**Comment by Viachaslau-Zinkevich** [comment]
Sorry for not commenting, I'm currently looking into the issue. I personally can't reproduce the issue with the latest code base as I see that WindowWrapper.Current() exists in the Template10 (Library) project.

**Comment by xiler8** [comment]
I have the same issue.
![image](https://cloud.githubusercontent.com/assets/20427901/23463372/80a52e56-fe91-11e6-92f9-2ba608a1eafc.png)

**Comment by Viachaslau-Zinkevich** [comment]
I will check once more cloning repository from scratch

**Comment by Viachaslau-Zinkevich** [comment]
It seemed to be an issue with my fork that shoed everything as OK. 
now I can reproduce the issue, but it looks like something with original Template10 (Library) project prevents it from building.

Actually, did you try to compile any other sample project? I have issues with multiple of them and seems like they can't resolve basic types, which actually present. Seems to be issue with dependencies.

**Comment by davefxy** [comment]
The last time I tried with that build everything compiled except multiple sample.I will download the latest template10 library and try again. 

    On Wednesday, March 1, 2017 12:57 PM, Viachaslau-Zinkevich <notifications@github.com> wrote:
 

 It seemed to be an issue with my fork that shoed everything as OK.
now I can reproduce the issue, but it looks like something with original Tempalte 10 (Library) project prevents it from building.Actually, did you try to compile any other sample project? I have issues with multiple of them and seems like they can't resolve basic types, which actually present.—

**Comment by Viachaslau-Zinkevich** [comment]
@JerryNixon, I've added a PR that at least makes it's compilable and runnable for me. 

@davefxy  It seems like for x86 debug configuration examples are not compiled at all so you'd probably won't see any errors there after Solution compilation. For example MultiplePageHeaders doesn't compile with the same errors of not found types.
