### ISSUE TITLE
OnNavigatedFrom happens before PropertyChanged

### ISSUE THREAD

**Issue by devinfluencer** [Windows-XAML/Template10#1398]
Hi there,
am I missin' something? In my app the OnNavigatedFrom event happens before PropertyChanged if I push the back arrow on a page. The value in the last edited control is not saved to the viewmodel early enough and can't be saved when leaving the page.
Using T10 v. 1.1.12
-Thomas

**Comment by JerryNixon** [comment]
Can I assume you are talking about a `TextBox`? Can I assume you are using the default `UpdateSourceTrigger`? Can I recommend that you use `UpdateSourceTrigger`=`PropertyChanged`? If you are using `{x:bind}` there is no `UpdateSourceTrigger`, so for `TextBoxes` you should fall back to `{binding}` which is a known issue to the platform team. We're hoping RS2 will introduce it to `{x:bind}`. If you are not using `TextBox` then, please explain your problem more.

**Comment by devinfluencer** [comment]
Yes, Jerry, you're right. It's a `TextBox `and I'm using old-fashioned binding.
So you say on each `TextBox UpdateSourceTrigger=PropertyChanged `should be used? Because the chance exists that the back button is pressed immediately after the `TextBox `is edited. Depending on the `PropertyChanged `processing this might be a bit inefficient. Wouldn't it be better to assure that the focus action happens before `OnNavigatedFrom `is triggered?

**Comment by dg2k** [comment]
This has to do with TextBox control because by default TextBox updates itself when end of string is detected (for efficiency reason I suppose).  The `UpdateSourceTrigger` overrides this default behavior, meaning it gets updated for every char typed in. If you noted this problem with regard to TextBox, it means the issue has nothing to do with T10.
