### ISSUE TITLE
W10M Template 10 HamburgerMenu DetailPage disapears after resume

### ISSUE THREAD

**Issue by JoacimWall** [Windows-XAML/Template10#1399]
Visual Studio 2015 sp3.
 Template 10 version 1.1.12
1. Select new project template 10 (hamburger). 
2. build project to mobile device or emulator.
3. Stop debug.
4. Start the app from device. 
5. The text box label "Parameter to Pass" value Gas. 2. is showed.
6. Click windows button (home) on device.
7. Select "all apps ->" and Click on icon "Template10App" agin.
8. Now i only see the hamburger menu in the top left corner. label "Parameter to Pass" value Gas. 2 is gone.

//Joacim Wall

**Comment by JerryNixon** [comment]
I will investigate.

**Comment by dg2k** [comment]
All is fine.
Just change `ExistingContent.Exclude` to `ExistingContent.Include` for the following line in `public override UIElement CreateRootElement(IActivatedEventArgs e)` (**App.xaml.cs**).

    public override UIElement CreateRootElement(IActivatedEventArgs e)
    {
        ...
        
        var navService = NavigationServiceFactory(BackButton.Attach, ExistingContent.Include);
        
        ...
    }

**Comment by JoacimWall** [comment]
Thanks now it works perfect.
