### ISSUE TITLE
NavigationServices must be accessible via Dictionary

### ISSUE THREAD

**Issue by FrayxRulez** [Windows-XAML/Template10#140]
Hey, when an app has multiple frames and two or more of them are used simultaneously sometimes developer might need to access a specific NavigationService directly from WindowWrapper.Current().

Right now a query like this one is needed:
`var service = WindowWrapper.Current().NavigationServices.FirstOrDefault(x => x.FrameFacade.FrameId == "SomeFrame")`

That's not a crazy thing, with a collection of a couple of items, but I think that actually will be great if instead we can do simply

`var service = WindowWrapper.Current().NavigationServices["SomeFrame"]`

**Comment by JerryNixon** [comment]
Good idea. I just added it. See Template10.Services.NavigationService.NavigationServiceList.
