### ISSUE TITLE
MVA NewsApp not in Samples

### ISSUE THREAD

**Issue by jhalbrecht** [Windows-XAML/Template10#1400]
The Microsoft Virtual Academy ["Getting Started with Template 10"](https://mva.microsoft.com/en-us/training-courses/getting-started-with-template-10-16336?l=VHbph4LRC_6105918554) mentions that the NewsApp will be in the samples. I'm not seeing it there. I'd like to checkout a couple things, particularly the 'favorite' feature of the app.

**Comment by Pinox** [comment]
This perhaps what you looking for https://github.com/Windows-XAML/2016MVA-Template10

**Comment by jhalbrecht** [comment]
Doh!

Thanks!

It has some cool features. Might it be worth inclusion with the T10 samples?
