### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by aerostudios** [Windows-XAML/Template10#1401]
I don't see any tests in the projects, what are you using for a unit test framework / mock framework for this?

**Comment by aerostudios** [comment]
Doh!  Just found them, they were staring me in the face :).

**Comment by aerostudios** [comment]
But, I'm not seeing very many of them and no mocking :(.

**Comment by JerryNixon** [comment]
@aerostudios This is OSS :) I look forward to your PR.

**Comment by aerostudios** [comment]
Sorry, should have been clearer.  Was looking for some suggestions / pointers as to a good mocking framework for template 10 projects.
