### ISSUE TITLE
x:Bind to Events Causes Memory Leak

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#1404]
This is a follow-up to Issue #1403.

It's very tempting to use **x:Bind** for binding view events (such as **Click** or **Tapped** on **AppBarButton**) to view-model but this introduces memory leak. This, of course, doesn't stop you in streering the view events to view-model but you may have to do the event subscription and unsubscription in view code-behind (see also below with **Command** property) and call the view-model method from there (i.e., until the x:Bind memory leak is sorted out).

Interestingly, binding to the **Command** property of **AppBarButton**, as opposed to **Click** or **Tapped** events doesn't seem to be leaky, so this is an option to consider.

@JerryNixon Is there a recommended approach to using x:Bind ? Is there any scope with regard to **WeakReference** in this area? I haven't looked into this.

**Comment by darshanrampatel** [comment]
@dg2k, is there a similar issue with using **Binding**?

**Comment by dg2k** [comment]
I don't think the classical **Binding** is *inherently* leaky although I haven't tested this thoroughly, but the key issue is how to unsubscribe the events. Never thought of **Binding** in terms of event binding ... Also remember that **Binding** uses **Reflection** for run-time binding in sharp contrast to the compile-time binding **x:Bind**.

**Comment by JerryNixon** [comment]
Well, @dg2k, I've brought this to the team several times as you are not the first to report it. But, it doesn't seem to be reproducible. If you can reproduce it, you need to document it cleanly. You might even write a blog article on it and then let me show the team yet again. I am not saying you are wrong, it's just that it doesn't appear to be true in our testing. That being said, who knows.
