### ISSUE TITLE
Template10 good practice

### ISSUE THREAD

**Issue by ghost** [Windows-XAML/Template10#1406]
Sorry if it's not really an issue but I don't know where to ask this.

Is it ok for a model to inherit from BindableBase ?

My problem is one of my ViewModel have an ObservableCollection<Person> but when I update one "Person" attributes it doesn't refresh the ListView binded to that collection.

The workaround I found is to modify the "Person" model like this :

````
public class Person : BindableBase 
{
        [JsonProperty("name")]
        private string _Name;}
        public int Name { get { return _Name; } set { Set( ref _Name, value); } }
}
````

I don't know if it respect MVVM pattern but I have no idea how else I should do.

**Comment by JerryNixon** [comment]
For one, you definitely mean to do this instead:

````
public class Person : BindableBase 
{
        private string _Name;
        [JsonProperty("name")]
        public string Name { get { return _Name; } set { Set( ref _Name, value); } }
}
````

**Comment by JerryNixon** [comment]
I'm sorry, I do not understand what problem you solved.

**Comment by MatthiasNistl** [comment]
So your question is simply if it's ok for a model to inherit from BindableBase? IMHO: Sure, why not? Another solution would be to implement INotifiyPropertyChanged manually, but since you have BindableBase you don't need to do that.
I see no reason why you shouldn't use BindableBase here.

**Comment by sebfrie** [comment]
@JerryNixon Just for clarification purposes: I think the problem is that although the ObservableCollection gets refreshed if a "person" element was added or removed, it doesn't update after changing a property of one of the OC's elements, e.g. a person's name.
