### ISSUE TITLE
Horizontal Secondary Menu Buttons

### ISSUE THREAD

**Issue by vinodshinde** [Windows-XAML/Template10#141]
Is there a way to arrange the Secondary menu buttons horizontally without text, just use icons.
Example will be the Mail app which has Settings, Mail, Calendar and Feedback buttons arranged horizontally at the bottom.

**Comment by dotnetnoobie** [comment]
This is actually relatively easy to do, here is how I made the Secondary menu buttons horizontal in the minimal project, with just a few lines of code changed. 

first you need to change the ItemsPanelTemplate in the HamburgerMenu control. 

from the original 

``` Xaml
<ItemsControl Grid.Row="1" ItemTemplate="{StaticResource NavButtonTemplate}" ItemsSource="{Binding SecondaryButtons, ElementName=ThisPage}">
    <ItemsControl.ItemsPanel>
        <ItemsPanelTemplate>
            <StackPanel BorderBrush="{Binding SecondarySeparator, ElementName=ThisPage, FallbackValue=White}" BorderThickness="0,1,0,0" />
        </ItemsPanelTemplate>
    </ItemsControl.ItemsPanel>

    <!--  designtime  -->
    <local:HamburgerButtonInfo>
        <StackPanel Orientation="Horizontal">
            <SymbolIcon Width="48" Height="48" Symbol="Setting" />
            <TextBlock Margin="12,0,0,0" VerticalAlignment="Center" Text="Settings" />
        </StackPanel>
    </local:HamburgerButtonInfo>

</ItemsControl>
```

to this 

``` Xaml
<Border Grid.Row="1" BorderBrush="{Binding SecondarySeparator, ElementName=ThisPage, FallbackValue=White}" BorderThickness="0,1,0,0">
    <ItemsControl ItemTemplate="{StaticResource NavButtonTemplate}" ItemsSource="{Binding SecondaryButtons, ElementName=ThisPage}">
        <ItemsControl.ItemsPanel>
            <ItemsPanelTemplate>
                <WrapGrid Orientation="Horizontal"  ItemWidth="48"/>
            </ItemsPanelTemplate>
        </ItemsControl.ItemsPanel>

        <!--  designtime  -->
        <local:HamburgerButtonInfo>
            <SymbolIcon Width="48" Height="48" Symbol="Setting" />
        </local:HamburgerButtonInfo>

    </ItemsControl>
</Border>
```

Then in the Minimal project views folder I changed the SecondaryButtons like this

From the original button 

``` Xaml
<Controls:HamburgerButtonInfo PageType="views:SettingsPage">
    <StackPanel Orientation="Horizontal">
        <SymbolIcon Width="48" Height="48" Symbol="Setting" />
        <TextBlock Margin="12,0,0,0" VerticalAlignment="Center" Text="Settings" />
    </StackPanel>
</Controls:HamburgerButtonInfo>
```

to this 

``` Xaml
<Controls:HamburgerButtonInfo PageType="views:SettingsPage">
    <SymbolIcon Width="48" Height="48" Symbol="Setting" /> 
</Controls:HamburgerButtonInfo>
```

now you can add more buttons like this and they will be arranged horizontally 

But this it only one way, maybe not the best?

So I tried a second method, as described below, but don't have enough time to iron out all the bugs, but this is another way you should be able to achieve your desired result

The other method would be to create a new DataTemplate & Style for the SecondaryButtons (e.g. copy the NavButtonTemplate & NavButtonStyle) and set the widths to 48 to match the icon width, then set the StackPanel Orientation="Horizontal" in the SecondaryButtons ItemsControl...

But when I tried this the buttons were arranged horizontally, but they were not arranged next to each other, they were spread evenly across the SecondaryButtons section with gaps which I could not workout how to remove. 

Or you could do a combination of both e.g. make the new DataTemplate and Style for the SecondaryButtons and then change the StackPanel to a WrapGrid as in the above example

**Comment by dotnetnoobie** [comment]
I think this feature could actually be added into the HamburgerMenu as an option relatively easily?

With and extra Property to select the SecondaryButtons style e.g. Vertical or Horizontal and depending on that property the ItemsPanelTemplate could be set via a TemplateSelector class ???

**Comment by JerryNixon** [comment]
I have partially implemented this feature in "Search (and Login)" sample. But am struggling to figure out why the width of the button is not constrained by MaxWidth. Would you two get latest and take a look? I think we can add this feature if we can figure out that one thing.

**Comment by dotnetnoobie** [comment]
I had the same problem when I did it via creating a new DataTemplate and Style and manually setting all the Width values to 48, the buttons were still wide, I was not able to find out why.

Which is why I tried the WrapGrid and set the ItemWidth to 48 which worked 

I will try to take another look later when I have some spare time

**Comment by janabimustafa** [comment]
The default RadioButtonStyle defines a MinWidth of 120. Set it to zero in the NavButtonTemplate and it will work.

``` csharp
 <DataTemplate x:Name="NavButtonTemplate">
                <RadioButton Width="{Binding PaneWidth, ElementName=ThisPage}"
                              MaxWidth="{Binding MaxWidth}" VerticalAlignment="Stretch"
                             HorizontalAlignment="{Binding HorizontalAlignment}"
                             Command="{Binding NavCommand, ElementName=ThisPage}"
                             CommandParameter="{Binding}" GroupName="Nav"
                             IsChecked="{Binding IsChecked, Mode=TwoWay}"
                             MinWidth="0"
                             IsEnabled="{Binding IsEnabled, Mode=TwoWay}" Loaded="NavButton_Loaded"
                             Tag="{Binding Content}" Tapped="NavButton_Tapped"
                             Visibility="{Binding Visibility, Mode=TwoWay}">
                    <RadioButton.Template>
                        <ControlTemplate>
                            <ToggleButton
                                          MaxWidth="{Binding MaxWidth, Mode=TwoWay, RelativeSource={RelativeSource Mode=TemplatedParent}}"
                                          HorizontalAlignment="{Binding HorizontalAlignment, Mode=TwoWay, RelativeSource={RelativeSource Mode=TemplatedParent}}"
                                          Command="{Binding Command, Mode=TwoWay, RelativeSource={RelativeSource Mode=TemplatedParent}}"
                                          CommandParameter="{Binding CommandParameter, Mode=TwoWay, RelativeSource={RelativeSource Mode=TemplatedParent}}"
                                          Content="{Binding Tag, Mode=TwoWay, RelativeSource={RelativeSource Mode=TemplatedParent}}"
                                          IsChecked="{Binding IsChecked, Mode=TwoWay, RelativeSource={RelativeSource Mode=TemplatedParent}}"
                                          Style="{StaticResource NavButtonStyle}" />
                        </ControlTemplate>
                    </RadioButton.Template>
                </RadioButton>
            </DataTemplate>
```

**Comment by JerryNixon** [comment]
Perfect. Thanks. Done.

**Comment by vinodshinde** [comment]
Hello Friends, Thank you very much for such a fast implementation.
I spent almost 4-5 hours yesterday going through the Template 10 code to figure out how this can be done. Modified the NavButton template and style but faced the same issues as you guys described.
Finally posted this on GitHub and called off the day.
Today when I woke up and saw the emails that its already fixed. And it just worked in my project.
Appreciate your efforts in implementing this feature just in time.
Thanks Again. You Guys Rock!
