### ISSUE TITLE
Adding a custom shell in the background of the current frame

### ISSUE THREAD

**Issue by ImCarrot** [Windows-XAML/Template10#1414]
Hi, I have been using template 10 for quite a while now, great work, reduces my effort in many ways and I don't even have to work hard on the pluming. I have a quick question,
I want to put a Map control in the shell. So basically, in my shell instead of the hamburger control, I want to put in a map control, over which all my Frames (a.k.a Views/Pages) would render. The issue I face is that the shell is defined such that, the shell always remains on top of the visual tree, which means that if I add a full screen map to it and then make the NavigationService navigate, the map remains on top. Is there a way I can push it to the background, so that i can show all my View(s) on the shell while my map is on the background and all the places where there is no background, the map is viewable and I can interact with the map as well. Is it possible?

**Comment by mvermef** [comment]
If I remember correctly, I believe you can create named sub-Frames without compromising the pre-existing primary frame, then come up with a solution to have them overlay the map as you want with opacity changes, maybe .

follow this chain...
https://github.com/Windows-XAML/Template10/issues/4

**Comment by ImCarrot** [comment]
I am sorry for getting back this late. Yes, that's what I have been doing. But I was wondering if it could be done via the shell provided in the hamburger template. Thanks for the advise though. Much appreciated
