### ISSUE TITLE
Question: Saving user settings to LocalSharedFolder

### ISSUE THREAD

**Issue by NicoTiing** [Windows-XAML/Template10#1415]
This is not an issue ,

I'm using SettingsService, but how can I save user settings to LocalSharedFolder?
`_appSettings = new MyAppSettings(SettingsService.Create(SettingsStrategies.Local, nameof(MyAppSettings)));`
that interface settings have bool , string , int , etc. it stores the settings of my app , and it is stored in : C:\Users\%username%\AppData\Local\Packages\AppPackage\Settings\settings.dat

I want it to save in the app SharedFolder , how can i create my settings to my SharedFolder location?

NOTE: I want all machine users to have same settings on my app , there is a a thread how to do that , and I was able to do it on my db , different users shares one/same db , but not settings ,thread: [https://blogs.msdn.microsoft.com/notime/2016/03/04/sharing-data-between-users-of-a-universal-app/](url)

**Comment by mvermef** [comment]
At present the code you can't do what you are asking but a small change to the existing code would allow for it, best through extension (interfaces for the win) unless Jerry feels it would be a worth inclusion to the code base.

Keep in mind though that what is proposed by that post requires a policy change on the machine in question related to a registry key (something which the app is incapable of doing without an administrator physically intervening).  Not exactly the ideal solution.

I think this could open up a can of worms personally,  I would create another interface to extend the current code base, override what you need.

**Comment by NicoTiing** [comment]
@mvermef 

I hope Sir Jerry would consider it , ok , can you please give me an example of what you meant , Iam really new to this, hope you dont mind 

Thank You

**Comment by mvermef** [comment]
@NicoTiing  working on a rough attempt...

**Comment by NicoTiing** [comment]
@mvermef 
Thank You , I think the best way for this is , create my own 'SettingsService' 

here is the SettingsService : 
`public class SettingsService : ISettingsService {
        public static ISettingsService Local { get; }
        public static ISettingsService Roaming { get; }
        public IPropertyMapping Converters { get; set; }
        public IPropertySet Values { get; }
        protected ApplicationDataContainer Container { get; }

        public static ISettingsService Create(SettingsStrategies strategy, string folderName = null, bool createFolderIfNotExists = true);
        public void Clear(bool deleteSubContainers = true);
        public bool Exists(string key);
        public ISettingsService Open(string folderName, bool createFolderIfNotExists = true);
        public T Read<T>(string key, T fallback = default(T));
        public void Remove(string key);
        public void Write<T>(string key, T value);
    }`

here is the Interface: 
`public interface ISettingsService {
        IPropertyMapping Converters { get; set; }
        IPropertySet Values { get; }

        void Clear(bool deleteSubContainers = true);
        bool Exists(string key);
        ISettingsService Open(string folderName, bool createFolderIsNotExists = true);
        T Read<T>(string key, T fallback = default(T));
        void Remove(string key);
        void Write<T>(string key, T value);
    }`

and here is the SettingsStrategies:
`public enum SettingsStrategies
    {
        Local = 0,
        Roam = 1,
        Temp = 2
    }`

Think just needs to add LocalSharedFolder location on SettingsStrategies.

**Comment by mvermef** [comment]
Actually I was digging into this the implementation is completely different, reason being is that `ApplicationData.Current.SharedLocalFolder` isn't the same thing as you would expect, it not a Settings folder so it would require a completely different approach than what is present.   

the type of the `SharedLocalFolder` is as expect a `StorageFolder` type, where as `LocalSettings` for example is of type `ApplicationDataContainer`, very different beasts.

Pealing layers of this onion is gonna difficult at best especially with the security aspects of this change associated with the machine.  It can't be something the App can change on the machine, this is the nature of UWP, respect it.

**Comment by NicoTiing** [comment]
@mvermef 
yes, thats why I think i just need to create my own SettingsStrategies, and add shared location path, but is it possible and will it create settings.dat in that path?

**Comment by mvermef** [comment]
In theory yes but not sure why you want to have users share settings, just a little odd is all.. Almost better if you really need certain settings to propagate to each user that are identical hook it up to a DataSource (azure or webapi) and push the settings that way, storing it locally with SQLite.

**Comment by NicoTiing** [comment]
@mvermef 
uhhm ok ok , can you please let me know if you found out how? , funny but that's what the client wanted

Thanks

**Comment by mvermef** [comment]
This is going in the direction of more trouble that its honestly worth in the end.  The Client wanted to make it easier for UWP app to share settings,  I don't know that the App Store will even certify this in the end.  The only option for something of this nature might be a side load install..  I am not trying to deflect this but I think its going to turn into a nightmare for you.  

Don't forget the Customer is not always right...

**Comment by NicoTiing** [comment]
@mvermef 
Actually , they want it to be installed for all users too , but after searching found out that its not possible , may I know about Sideload apps? I followed this thread : https://technet.microsoft.com/itpro/windows/deploy/sideload-apps-in-windows-10?f=255&MSPPError=-2147217396

but cant install app on sideload mode

**Comment by mvermef** [comment]
the link you found is the only source of information for sideloading apps.

**Comment by NicoTiing** [comment]
@mvermef 
Actually , what I did is on my machine with 2 users , i manually installed the app package to each users , and they have the same database.

I read articles about that , Im a bit confused about the difference between 'Sideload apps' and 'developer mode' in Developer features , may I know the difference specifically?

Thanks

**Comment by mvermef** [comment]
Sideload app  = trusted with certificate
Developer mode = untrusted... etc.

**Comment by NicoTiing** [comment]
@mvermef 
Im confused yesterday , yeah youre right , what i need is a new ApplicationDataContainer that will create on my  SharedFolder location

**Comment by mvermef** [comment]
problem is you can't it doesn't exists for the type of `ApplicationData.Current.ShardLocalFolder`

**Comment by NicoTiing** [comment]
@mvermef 

What do you mean I can't? , even I create my own SettingsService or ApplicationData?

**Comment by mvermef** [comment]
No I mean SharedLocalFolder is not an ApplicationDataContainer type, it's StorageFolder!

**Comment by NicoTiing** [comment]
@mvermef 
Oh yes, I meant I will create a new ApplicationDataContainer and located to my SharedFolder.
What will you advice for me about this issue? What do you think is the best way ? except for creating config sql db

**Comment by mvermef** [comment]
It's such an extreme use case and I haven't really looked at much past the initial comment.  Reason it isn't something I would ever entertain
