### ISSUE TITLE
Sample applications can't compile

### ISSUE THREAD

**Issue by ChristophvanderFecht** [Windows-XAML/Template10#1416]
Hi,
I wanted to dig deeper into your HamburgerMenu since the implementation is really cool and I want to extend it be some features for our company. I wanted to debug the initialization process and navigation.
Sadly i can't compile any of the samples in the solution. Everyone is showing the following error

Error	CS0534	'App' does not implement inherited abstract member 'BootStrapper.OnStartAsync(StartKind, IActivatedEventArgs)'	MasterDetail (Mail App)	...\Template10\Samples\MasterDetail\App.xaml.cs	9

The method is implemented but the compiler won't find it in the base.

Any suggestions?
Sorry for the stupid question!

**Comment by mvermef** [comment]
I think this is an artifact of the refactoring.  what you could in theory do is grab the source of that sample and drop in the Nuget package to get it to compile (maybe).

**Comment by ChristophvanderFecht** [comment]
I tried it the other way around, created a project with the nuget pack and than replaced the pack with the sources. Same result... I will give your "theory" a try.
Thx

**Comment by mvermef** [comment]
also you might have to change the references...

**Comment by ChristophvanderFecht** [comment]
Your suggestion worked, but since the library is now loaded from the nuget package I am not able to dwell down into the code of the T10 library since it isn't loaded... I also tried to build the application with the package and than swap the libs again with the real code and start it, same errors as before... Seams that there relay is no workaround other than having the samples fixed...

**Comment by mvermef** [comment]
yea as I feared cause the code is in a such a state at the moment that I don't know when it will be correct with a samples build.  I was wading thru it most of the evening.

**Comment by ChristophvanderFecht** [comment]
OK, than I will just play the waiting game and monitor the repo :-D
BIG THX for your support!

**Comment by mvermef** [comment]
np.  the changes over the last couple weeks have been incremental and I haven't been watching it with other things going on.  Therefore the changes have caught me off guard as well.

**Comment by swisszeni** [comment]
Make sure you are referencing all the needed projects from within the sample Apps. Currently they only reference "Template10 (Library)". Adding "Template10.Portable" and "Template10.Services" (the two projects referenced by the Library itself) solves all compiling errors for me.

**Comment by ChristophvanderFecht** [comment]
I also referenced the Template10.Portable and .Service libs in the sample, but still no success. I haven't tried it since then, may be i give it a new shot. THX

**Comment by swisszeni** [comment]
Ok tested it with a fresh pull. You need to add `using Template10.Common;` in App.xaml.cs for the MasterDetail sample to work (additionally to adding the references). Then clean and build.
