### ISSUE TITLE
IPropertyMapping 

### ISSUE THREAD

**Issue by qzzf1w** [Windows-XAML/Template10#1417]
ISettingsService in Template10.2.Core.Services
references 
IPropertyMapping 

Which is contained in 

Template10.Services

but 

Template10.Services not refrenced 

Not sure wether IPropertyMapping  
should be in Template10.2.Core.Services
or
Template10.Services should be refenced.

Tried adding refrences, but seemed like
a ball of string.

public interface ISettingsService
    {
        IPropertyMapping Converters { get; set; }

**Comment by mvermef** [comment]
Nope sorry it appears we have spaghetti atm, it's only being used presently in Template10.Services.dll aka Template10 (Services) project, which is part of the "master" branch... As for the Template10.2 reference unsure.  When which is relative wording the Template10.2 branch shows that entire project being deleted with respect to Template10 (Services) project.

edit -- looks like it is work in progress part of the refactoring of the entire code base.
