### ISSUE TITLE
Hamburger Button Hover Color

### ISSUE THREAD

**Issue by Thaoden** [Windows-XAML/Template10#1420]
I'm trying to change the hover color of the Hamburger Button itself - however I can't seem to find a property for it. Any hints where to look?

**Comment by swisszeni** [comment]
There is none. The hover color is created by overlaying a white rectangle with 20% opacity.

Code can be found [here](https://github.com/Windows-XAML/Template10/blob/7467a680f4699a8be2b6dec5fe71e4daa3aff694/Template10.Controls/Template10.Controls.Hamburger/Controls.HamburgerMenu/HamburgerMenu.xaml#L66-L69).

**Comment by Thaoden** [comment]
Thanks
