### ISSUE TITLE
If put FocusAction on GridView on the first page, touch GridView area after start up will crash the app on Phone or emulator

### ISSUE THREAD

**Issue by TaoziDB** [Windows-XAML/Template10#1421]
To reproduce this bug, put a GridView in MainPage.xaml in Template10-Hamburger, and put FocusAction on GridView, run on phone or emulator, as soon as app starts to MainPage, touch GridView area, the app will crash, if upon start, touch hamburger button to go to other page and go back to MainPage, touch GridView will not crash the app.

Using Nuget 1.1.12 or using current github library leads to same crash.

**Comment by mvermef** [comment]
Does it happen on phone device..

**Comment by TaoziDB** [comment]
yes
