### ISSUE TITLE
Visual Studio 2017

### ISSUE THREAD

**Issue by StuRamsey** [Windows-XAML/Template10#1422]
Do you plan to update the templates to support VS2017

**Comment by StuRamsey** [comment]
Sorry, should have added a bit more info:
Extensions and Updates - Can't find it.
Download and run installer - This extension is not installable on any currntly installed products.
Just installed VS2017 so I can move from WPF to UWP and thought Template10 looked a great place to start. Seemes to only install on VS2015. I've got VS2013 Pro and now VS2017 Community, don't want VS2015 as well.
Any help please.

**Comment by mvermef** [comment]
It only exists for VS2015 at present...

**Comment by mvermef** [comment]
Doesn't mean you can't create a project and code it up with nuget and project code on the template you want (blank, minimal, of hamburger)

**Comment by StuRamsey** [comment]
I know I could code it up, but as this is my first step into UWP form WPF I was looking for a bit more of a helping hand to start,

**Comment by StuRamsey** [comment]
Closed and joined Issue #1330
