### ISSUE TITLE
Persisting Navigation History on Suspension is Better If the Responsibility of the Developer than T10

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#1423]
FAO: @JerryNixon 

One weak point of failure for UWP apps is not observing the limitation set by [ApplicationData.LocalSettings](https://msdn.microsoft.com/en-us/microsoft-r/windows.storage.applicationdata.localsettings?cs-save-lang=1&cs-lang=csharp).

> Each setting can be up to 8K bytes in size and each composite setting can be up to 64K bytes in size.

What happens if you exceed this limit? If you didn't take any precaution, your app would crash silently due to **UnhandledException** and if you managed to inspect the Stack Trace you would note the following useful error message.

> "The size of the state manager setting value has exceeded the limit."

How and where does this happen in T10?

This can happen when your app is entering the *suspended life cycle*. You can easily reproduce this in **Debug** mode by setting the **LifeCyle Eevents** to **Suspend**. This would trigger the navigation service to persist its states under three Settings keys: **CurrentPageType**, **CurrentPageParam**, and **NavigateState**. The first two cause no problem at all; it's the **NavigateState** that causes a problem ([this line](https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Services/NavigationService/NavigationService.cs#L333) in the source code) because the navigation history can grow with app's navigation usage history.

What is saved as NavigateState is a *string-form serialization* of navigation history (done for us by **Windows.UI.Xaml.Controls.Frame.GetNavigationState()**). The string-form serialization mainly depends, I would say proportionately, on app's *namespace string length* and *navigation stack depth*. As a result, this problem may go unnoticed by some developers for the following reasons:

- the app doesn't use intensive navigation, and for whatever reason some navigations' history may be cleared in the app, so the problem wouldn't surface.

- relatively short namespace is used for the app and, as for shallow navigation history, this may help keep the serialized string well below the 8K bytes.

Imagine developing an app, and testing it exhaustively, and just at the production phase changing the namespace from **MySuperDuperApp** to a domain-based namespace **MySuperDuperDomainName.Com.MySuperDuperApp** (why not indeed!) and hitting the problem. Because now the serialized string increases by about 2x to 3x, may be more -- also noting that the .Views and .ViewModels, etc., all get appended, and more so with deep folder based and/or longer page names -- and with about a dozen navigations you're almost guaranteed to hit that 8K limit. I always use a domain-based namespace as well as longer names for folders and page names (for better readability), hence I'm a good candidate for the issue described here (the 10% lucky ones;-).

How to deal with the issue of **ApplicationData.LocalSettings** limitation vis-à-vis **persisting navigation history**, specifically, the **NavigateState** that may not be bound under 8K bytes?

I think it's more sensible to move the task of persisting navigation history to the *developer domain*, than keep it within T10. If **SaveAync()** and **LoadAsync()** can be over-ridden by the developer, then the developer can provide an optimal solution that fits well with the app's parameters that impact the issue described. That way no one would *unfairly* level a blame against T10 for issues that arise from an app: navigation depth, namespace string length, page and folder names' length.

I part II of this, I will summarize one simple solution based on String Compression, the very reason why I would like persisting navigation history taken care of by the developer. Yes, you can also opt for the straight-forward saving of navigation history to a **LocalStorage**, like any file, but again, to do this **SaveAync()** and **LoadAsync()** must be accessible to developers.

**Comment by tibitoth** [comment]
Yes we need to persist the Navigation History and the Suspension State to a file like Prism does it.

**Comment by JerryNixon** [comment]
@totht91 is right

**Comment by JerryNixon** [comment]
10.2 does this, and we will need to test the scenario @dg2k
