### ISSUE TITLE
Build warnings 'BootStrapper.EnableAutoRestoreAfterTerminated' is obsolete 

### ISSUE THREAD

**Issue by martinsuchan** [Windows-XAML/Template10#1429]
When using the BootStrapper instead of Application and building the app, it throws two build warnings:

    1>c:\users\martin.suchan\documents\visual studio 2017\Projects\App1Temp\App1Temp\obj\x86\Debug\XamlTypeInfo.g.cs(532,20,532,57): warning CS0618: 'BootStrapper.EnableAutoRestoreAfterTerminated' is obsolete: 'Use AutoRestoreAfterTerminated'
    1>c:\users\martin.suchan\documents\visual studio 2017\Projects\App1Temp\App1Temp\obj\x86\Debug\XamlTypeInfo.g.cs(537,13,537,50): warning CS0618: 'BootStrapper.EnableAutoRestoreAfterTerminated' is obsolete: 'Use AutoRestoreAfterTerminated'

Any chance to get rid of these warnings? I like my build output clean.
Using "Template10": "1.1.12"

**Comment by mvermef** [comment]
affects only the project this is connected to couple of options

- place this in your app.cs  `#pragma warning disable 618` 
- project properties drop in a 618 into the "Suppress Compiler Warnings" 618; 2008
- pretty much nuclear option, change your warning level from 4 to a lower value, keep in mind this affects other things of course.

**Comment by martinsuchan** [comment]
Not possible to use #pragma warning disable because the error is in generated g.cs file. Globally disabling warnings is really not an option here.  
There should be no deprecated public properties in the Bootstrapper type, which is typically used only in XAML, that's all.

**Comment by ChrisProlls** [comment]
Any solution about that ?
Thanks !

**Comment by JerryNixon** [comment]
This should be a warning and not an error, right?

**Comment by JerryNixon** [comment]
Isn't it already?

**Comment by ChrisProlls** [comment]
Yes you're right it's a warning.
We were just wondering how to delete this warning because it's annoying into Visual Studio.

**Comment by antlhuede** [comment]
Who the hell leaves warnings in public libraries?
There are many developers who strictly try to keep their builds clean. On larger projects it is more important.

Just another reason why I'm dropping template10 entirely in the coming weeks

**Comment by MasterSkriptor** [comment]
Triggered much?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by JerryNixon** [comment]
Okay, we'll keep it in the backlog and see if we can remove it.
