### ISSUE TITLE
Using custom Frame UI Element for Navigation using the NavigationService

### ISSUE THREAD

**Issue by ImCarrot** [Windows-XAML/Template10#1434]
Hello, I am using T10 for a while now, and it's a great work. I am trying to use a Singleton `BaseMainPage.xaml` as a rootFrame. The `BaseMainPage` contains two parts
1. A Base Map Control (Common to all view's).
2. A Frame UIElement (named baseFrame) over the Base Map Control.
**What I want to achieve:**
When from the viewModel I use the `NavigationService.Navigate()` I want the navigation to occur from the `baseFrame` instead of the rootFrame or the Modal Dialog in this context.

**My Current Flow:**
The App starts, and heads to `OnStartAsync` in the `app.xaml.cs`. There I use `NavigationService.Navigate(typeof(BaseMainPage))` to navigate to my `BaseMainPage`. 
Now, the baseMapControl loads and the baseFrame is also loaded. In the `Loaded` event listener of the `baseFrame`, 
**Where I Need Help**
I want to use the `NavigationService` to navigate my other view's from the baseFrame and attach the shell back button to the back stack of the baseFrame and handle all navigations from the baseFrame for eg: if I use, `NavigationService.Navigate(typeof(MyContactsPage))` then the `MyContactsPage` must be loaded over the baseFrame keeping the `BaseMainPage` as is. Can this be done? I need help. Thanks in advance

**Comment by JerryNixon** [comment]
Have you tried using Frame.GetNavigationService().Navigate(...)?
