### ISSUE TITLE
Master branch doesn't reflect what's on NuGet?

### ISSUE THREAD

**Issue by villasv** [Windows-XAML/Template10#1435]
I've installed the `1.1.13-preview-20161207` version of Template10 from NuGet (could not find newer on MyGet either), yet the HamburgerMenu example uses some interfaces not recognized. The breaking feature seems to be in the `SettingsService` part, which has no `SettingsServiceBase` and some other differences.

So it appears that the `master` branch doesn't have builds, which makes following the docs kind of pointless unless I install from source. Is that really what's going on?

**Comment by JerryNixon** [comment]
@villasv let's be honest with each other. I forgot to branch before I started making a million changes to the code base and I am rather embarrassed by the whole thing.

**Comment by JerryNixon** [comment]
Having said that, I am not really sure how to create a branch that reflects the old values. I would LOVE LOVE LOVE to create a v13 branch in the repo to solve this, but I am not sure how to do it. As proficient as I am with git, I am really just a git hack and know just enough to get the job done. Nothing exotic. You?

**Comment by villasv** [comment]
I see that there's a (new?) 1.1.13p branch with a recent commit. Have you sorted it out? Still need help with it?

I'd say that it's better to always keep NuGet in sync with `master`, most people would like to use the newest version anyway instead of 1.1.13 or 1.1.12.

**Comment by JerryNixon** [comment]
https://github.com/Windows-XAML/Template10/tree/version_1.1.12
