### ISSUE TITLE
Cannot build MasterDetail sample project

### ISSUE THREAD

**Issue by zackpeterson** [Windows-XAML/Template10#1436]
I just downloaded the master branch.

I get 1 error when I open the solution with Visual Studio 2017:

- Template10.ArchValidation\ArchValidation.modelproj: The application which this project type is based on was not found.

I get 2 errors when I fail to build the MasterDetail sample project:

- Type universe cannot resolve assembly: Template10.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
- Cannot resolve Assembly or Windows Metadata file 'Template10.Shared.dll'

**Comment by JerryNixon** [comment]
Doesn't it seem like one big SLN is part of the problem. I think a Samples.sln would be a nice addition to the code base, huh? What you are referring to is a result of this needless complexity.

**Comment by JerryNixon** [comment]
I think the other problem is that I forgot to branch before I made a million changes, more of a confession than a brag in this case, and I need to get everything functional again - so, you aren't the only one.

**Comment by JerryNixon** [comment]
As a temporary work around I would suggest that you create a new SLN and load the individual csproj of the sample you want to work with. That should make it work okay for you.
