### ISSUE TITLE
Introducing Template10.Controls.ImageEx

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#1437]
https://github.com/Windows-XAML/Template10/tree/master/Template10.Controls/ImageEx

This new control is very specialized, but is a good example of the first of the Template 10 controls to be separated out and put up in Nuget as individual packages. I would appreciate anyone taking a look at the new control. You will find it to be very simple (my favorite attribute) but feedback is welcome. It's currently not at version 1.0.0, but I plan to do so in about a month if nothing comes up.

**Comment by mdtauk** [comment]
Is this the same control as ImageEx from the UWP Community Toolkit?
https://github.com/Microsoft/UWPCommunityToolkit/tree/dev/Microsoft.Toolkit.Uwp.UI.Controls/ImageEx

**Comment by syaifulnizamyahya** [comment]
> Is this the same control as ImageEx from the UWP Community Toolkit?
https://github.com/Microsoft/UWPCommunityToolkit/tree/dev/Microsoft.Toolkit.Uwp.UI.Controls/ImageEx

Was about to ask the same thing. 

I love that control are being separated out from main Template10 (makes t10 more lean).

**Comment by StuRamsey** [comment]
One thing that seem to have come up and scuppered a lot of us is VS2017. Can't even try Template10 (and cut and paste from VS2015 isn't 100% successfull)
