### ISSUE TITLE
Null Reference Exception from RaisePropertyChanged

### ISSUE THREAD

**Issue by HarleyRossetto** [Windows-XAML/Template10#1438]
Not an issue with Template10, I am just an amateur developer writing my own apps, but I feel that this is the best place to get help with this issue.

Firstly stacktrace: 
```
+ $exception	{System.NullReferenceException: Object reference not set to an instance of an object.
   at Template10.Mvvm.BindableBase.RaisePropertyChanged(String propertyName)
   at Template10.Mvvm.BindableBase.Set[T](T& storage, T value, String propertyName)
   at Serial_App.ViewModels.SerialViewModel.set_SerialDevice(SerialDevice2 value)
   at Serial_App.ViewModels.ConsoleViewModel.<<get_CommandCreateDevice>b__13_0>d.MoveNext()}	System.NullReferenceException
```

And the code:

```        private SerialDevice2 _serialDevice2 = new SerialDevice2();
        public SerialDevice2 SerialDevice
        {
            get { return _serialDevice2; }
            set {
                Set(ref _serialDevice2, value);   //Null Reference here & no, the 'value' is not null
                RaisePropertyChanged(nameof(IsActive));
                RaisePropertyChanged(nameof(DeviceId));
            }
        }
``` 

The command that the view executes that calls this property:

```
        private DelegateCommand<object> _commandCreateDevice;
        public DelegateCommand<object> CommandCreateDevice
            => _commandCreateDevice ?? (_commandCreateDevice = new DelegateCommand<object>(async (obj) =>
            {
                if (obj == null)
                    return;

                var serialDevTemp = await SerialService2.CreateDevice((obj as DeviceInfoViewModel).DeviceInfo.DeviceInfo);
                if (serialDevTemp != null) {
                    SerialViewModel.SerialDevice = serialDevTemp;
                }
            },
                (obj) => 
                {
                    return obj as DeviceInfoViewModel != null;
                }
                ));

```

And if it is of any relevance the `SerialService2.CreateDevice()` function:

```
public static async Task<SerialDevice2> CreateDevice(DeviceInformation deviceInfo, uint baudRate = 9600, SerialParity parity = SerialParity.None, SerialStopBitCount stopBitCount = SerialStopBitCount.One, ushort dataBits = 8)
        {
            SerialDevice localDev;
            try {
                localDev = await SerialDevice.FromIdAsync(deviceInfo.Id);
            } catch (NullReferenceException ex) {
                //Handle this
                throw ex;
            }

            if (localDev != null) {
                SerialDevice2 sd2 = new SerialDevice2();
                sd2.ID = deviceInfo.Id;
                localDev.BaudRate = baudRate;
                localDev.Parity = parity;
                localDev.StopBits = stopBitCount;
                localDev.DataBits = dataBits;
                sd2.SerialDevice = localDev;
                sd2.SerialReader = new DataReader(localDev.InputStream);
                sd2.SerialReader.InputStreamOptions = InputStreamOptions.ReadAhead;
                sd2.SerialWriter = new DataWriter(localDev.OutputStream);
                sd2.CancellationTokenSrc = new CancellationTokenSource();
                return sd2;
            }
            return null;
        }
```

I for the life of me cannot figure out the issue, which is extremely frustrating as this is stopping me from progressing on my app. Any assistance is greatly appreciated.

Regards

**Comment by mvermef** [comment]
`var serialDevTemp = await SerialService2.CreateDevice((obj as
     DeviceInfoViewModel).DeviceInfo.DeviceInfo);   //<<<< IS YOUR LINE OF ISSUE

Not sure if this a PI project or not but that DeviceInfoViewModel would probably be suspect if not everything is populated correctly.

**Comment by HarleyRossetto** [comment]
The aim is to eventually run on a Pi via IOT, but currently setup running as desktop UWP. Checking all locals when the exception breaks shows nothing as null. Away on a quick work trip for a few days so I'll double check again when I get back Tuesday.

**Comment by mvermef** [comment]
How do you mock that to represent data coming in over the serial bus? Pre-set data to those parts that are "pulling" data?

**Comment by HarleyRossetto** [comment]
At this stage I just have a microcontroller sending and incrementing counter over a usb connection. Once I have got reading/writing working I'll begin testing with the actual devices I need to interface with. Due to board a flight shortly, hopefully will be able to have an answer for your original question is 4 hours or so.

**Comment by HarleyRossetto** [comment]
Ok, finally had time to check this out.
Nothing in what I am assigning is null.
http://imgur.com/7E5Hn7I

However it looks like the dispatcher is null from within the viewmodel..
http://imgur.com/XpNn7WK

It must be that which is causing the issue, with the viewmodel unable to notify the UI thread because of that null reference.

But then I must ask the question, why is it null? Am i missing something? And how do I fix this?

Thanks

**Comment by darenm** [comment]
Are you using the full Template10 infrastructure to start up your application (using BootStrapper, etc.) or just leveraging ViewModelBase?

**Comment by mvermef** [comment]
yeah can you give some of your initialization code in the app.xaml.cs... assuming full template10 usage.

**Comment by HarleyRossetto** [comment]
Then that would be my mistake.
I have a rough understanding of bootstrappers etc but never used before. I'll read into it and see what I can do.

**Comment by HarleyRossetto** [comment]
Ok, checked it out, was originally quite unsure about bootstrapping process. Turned out to be easy with the help of Template 10 templates.. All good now, can move on with my work.

Thanks for you help, have a good one!

**Comment by NicoTiing** [comment]
@EspyingStar 

How did you fixed it?

**Comment by FlorisDevreese** [comment]
@NicoTiing 

I had the same issue. 
The source of the problem is that I use functionality from the Template10.Mvvm namespace (I use the ViewModelBase class) in a project that is not created by one of the template 10 templates. As a consequence the startup code (app.xaml.cs) does not initialize the necessary modules for the template10.Mvvm functionality.
The fix for this problem is:
 

1. Add the [template 10 templates extension](https://marketplace.visualstudio.com/items?itemName=jerry-nixon.Template10TemplatePack) to visual studio
2. Create a new project using one of those templates. (I used the blank template)
3. Move all your code to this new project.

In this newly created project the startup code is correct, so all Template10.Mvvm functionality will work correctly.

Hope this helps!
