### ISSUE TITLE
Asset/logo positioning is off on splash screen when switching from portrait to landscape

### ISSUE THREAD

**Issue by myokeeh** [Windows-XAML/Template10#1439]
In the screenshot below, the white block is the asset or logo I setup for the app's splash screen. Is there any way to prevent it from getting positioned like this (not centered horizontally, not above the progress circle).

This happens when the app runs and switching from portrait to landscape.

It's positioned as expected in portrait mode.

![wp_ss_20170407_0001](https://cloud.githubusercontent.com/assets/3663297/24874874/f088a74e-1dda-11e7-89ec-de0edf41b989.png)

**Comment by JerryNixon** [comment]
Bug in the platform! But maybe we can compensate.

**Comment by myokeeh** [comment]
Oooh. Where can I file a bug report about that? I know about the Windows 10 Feedback app, but that's probably not the appropriate or most direct way.
