### ISSUE TITLE
UWP Test doesn't work properly using ValueWhenConverter converters

### ISSUE THREAD

**Issue by juanluelguerre** [Windows-XAML/Template10#1440]
Hi,

I can not reopen #464, so I create a new one.

I've found the similar issue (#464), when I use converters "ValueWhenConverter" like this. 

`<ct10:ValueWhenConverter x:Name="BoolToVisibilityConverter">
    <ct10:ValueWhenConverter.When>
        <x:Boolean>True</x:Boolean>
    </ct10:ValueWhenConverter.When>
    <ct10:ValueWhenConverter.Value>
        <Visibility>Visible</Visibility>
    </ct10:ValueWhenConverter.Value>
    <ct10:ValueWhenConverter.Otherwise>
        <Visibility>Collapsed</Visibility>
    </ct10:ValueWhenConverter.Otherwise>
</ct10:ValueWhenConverter>`

I've to change all of those converters to use my owns converter and I've solved it.

Hope this help
Regards
Juanlu

**Comment by JerryNixon** [comment]
Acknowledged
