### ISSUE TITLE
Issue with the Navigation service

### ISSUE THREAD

**Issue by ImCarrot** [Windows-XAML/Template10#1441]
Hi, I am using T10 Stable v1.1.12 in a UWP app. The issue is: in one of my views, after navigation, the Override for `OnNavigatedTo` isn't fired becasuse of which the View does not load the content. To Solve this issue, I updated my nugget to `Pre-Release v1.1.13 preview 20161207` which solved the issue but in that release, there is an issue with the `GoBack()` Each time I go back or press the back button, it takes me 2 Views Back. Eg: MainPage>DevicePage>DeviceSettingsPage>ConfigureInitializationPage. Now when I press back button or programatically call `GoBack()` from the ConfigureInitializationPage, It goes directly to DevicePage. Is anyone else facing the same issue?

**Comment by JerryNixon** [comment]
Fixing 12 isn't a priority, fixing 13 is. What's the issue in 13?

**Comment by ImCarrot** [comment]
Hi, Jerry. In 13, using the navigation service (from viewmodelBase) navigates twice. So it skips a frame and goes back. Eg: from MainPage --> DeatilsPage --> SettingsPage --> updateSettingsPage that's my forward navigation stack and I am at updateSettingsPage currently. Now when I perform operations and then call Navigation.GoBack() it takes me directly to DetailsPage , skipping SettingsPage and the navigation parameter is used that of the settings page. Because of which back navigation fails. Please note: on back button press, the back stack works perfectly fine, but when I programmatically call GoBack() it goes two frames back. I am sorry for the formatting I am on a mobile device

**Comment by VagueGit** [comment]
I am experiencing a similar issue, only with the back button. [Back button always returns to start page in UWP Template10 App](https://stackoverflow.com/questions/50956816/back-button-always-returns-to-start-page-in-uwp-template10-app). The back button always goes back 2 pages. I have created a simple demo [here](https://1drv.ms/u/s!AiGVkyOWwr6JuGE1RmFnga4SZ1ax). The demo was based on Template 10 Blank Template using 1.1.13-preview-20161207
