### ISSUE TITLE
INFO: What's going on with the master branch?!

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#1444]
Yeah, it's a mess. I am working to break the framework into separate projects with isolated logic for the sake of maintenance. I am also removing every service, making that service ignorant of Template 10 and setting it up to be a separate Nuget package. Right now we have like 15 unique services, including Template10.XAML (our behaviors and converters) and Template10.Utilities (our custom types, WinRT utils and extensions (still in the works)). Count it all up and we're talking about a potential 19 (probably more in the end) Template 10 nuget packages. Many of which will never be updated. Making churn less and less of an issue, I hope. 

> One thing in your mind might be "Is this problematic to have so many packages?" and I would point you to the .NET framework which has done this EXACT same thing. Adding .NET today basically means you are adding like 40 Nuget packages. Merging packages isn't a runtime problem.

Another thing I have done is remove all the controls. Hamburger Control, Resizer, all of it the same treatment as Services. Take a look. They are also isolated and ignorant of Template 10 except for Hamburger Menu. I am looking forward to deprecating the Hamburger Menu in favor or a first-party solution. But until that exists, we have the best Hamburger control there is. And, it is strongly influencing internal platform decisions on new controls. **Trust me**. I am on those calls.  

If you get latest of Master right now you will find nothing builds; it's a little discouraging. But try to see through the fog. You can still at least browse the mess of it and see where we are heading. Notice that there is a VISIO diagram I am working off of in the root. **I am NOT trying to rewrite Template 10.** I will have to move some (all?) code around, I see that now. But the logic will be the same EXCEPT the navigation code will support BOTH Template10.INavigable and Prism.INavigationAware (and the many other interfaces that includes). This will give us the Xamarin support we need.

Once I have it building, I will delete this issue and enter another so all you in @Windows-XAML/template-10-developer-community can see. Trust me, there is so much to Template 10 that this is a royal pain the keyboard. So thank you for being patient with me. Meanwhile, I will release the 13p branch next to Nuget around Build timeframe, I think. If you have not checked that out, check that baby out. There are a few bugs but not much. 

It's a lot of work huh?

**Comment by RafaelPlantard** [comment]
Thanks @JerryNixon 👍

**Comment by brianobr** [comment]
Thanks, Jerry.

**Comment by calloncampbell** [comment]
Thanks @JerryNixon for the update. Looking forward to when the dust settles and everything is working again.

Callon

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by richardcastle** [comment]
Jerry - That's great news. I can see the work and effort that has gone into this great project and was getting concerned looking at the activity on GIT recent months. We've been building Podcast Lounge UWP using it, so looking forward to the refactoring process bearing fruit.

Thanks again to you and all the contributors who are working hard to make this easier for devs like ourselves.

**Comment by artfuldev** [comment]
@JerryNixon that's a good direction we're heading in, I'm sure most of us will be alright with the temporary pains. Thanks a lot for all the effort. Also good to hear our Hamburger is helping with internal platform decisions on new controls. Kudos! 👍
