### ISSUE TITLE
A value of type 'HamburgerButtonInfo' cannot be added to a collection or dictionary of type 'ObservableCollection'.

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#1449]
I get a [rather busy] blue squiggly lines in **Shell.xaml** with a [benign] error: **A value of type 'HamburgerButtonInfo' cannot be added to a collection or dictionary of type 'ObservableCollection'.** shown as tooltip.
 
Surely, **HamburgerButtonInfo** containers as `HamburgerMenu.PrimaryButtons` and `HamburgerMenu.SecondaryButtons` are both `ObservableCollection<HamburgerButtonInfo>`,  so the error makes no sense, and most importantly compiles and runs okay. Based on the error, the compiler seems to be hinting for **HamburgerButtonInfo** to be a **UIElement** rather than **DependencyObject**.

Does anybody know why VS2017 triggers this error?

**Comment by JerryNixon** [comment]
I do not. We might run into it when we start testing Template.Hamburger.
