### ISSUE TITLE
Resizer control doesn't seem to render from library

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#145]
I really hope someone can help me figure this out. The new Resizer control in Template10/Controls/Resizer.xaml works just fine when the user control is locally in a project. But referenced in the library it does not render the corner grabber. Any suggestions?

![snip_20150925142642](https://cloud.githubusercontent.com/assets/1749983/10111469/7e7ed402-6391-11e5-9d5c-cb92d864ac86.png)

Using this syntax:

``` XAML
<StackPanel>
    <jerry:Resizer xmlns:jerry="using:Template10.Controls">
        <TextBox Width="250" />
    </jerry:Resizer>
    <jerry:Resizer xmlns:jerry="using:WindowsApp5">
        <TextBox Width="250" />
    </jerry:Resizer>
</StackPanel>
```

The Resizer is already in source control. If you figure out the trick, a Pull request would be terrific. Otherwise, answer here and I will update the code myself.

**Comment by janabimustafa** [comment]
I am not sure if this is the approach that you were intending to take but you're not setting the element property of the resizer control.

``` xaml
       <controls:Resizer>
                <controls:Resizer.Element>
                    <TextBox Width="200" Margin="0"
                         AcceptsReturn="True" Header="Parameter to pass"
                         Text="{Binding Value, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"
                         TextWrapping="Wrap">
                        <Interactivity:Interaction.Behaviors>
                            <Behaviors:TextBoxEnterKeyBehavior>
                                <Core:CallMethodAction MethodName="GotoDetailsPage" TargetObject="{Binding}" />
                            </Behaviors:TextBoxEnterKeyBehavior>
                        </Interactivity:Interaction.Behaviors>
                    </TextBox>
                </controls:Resizer.Element>
            </controls:Resizer>
```

This fixed it for me.

**Comment by JerryNixon** [comment]
You solved it. Thanks. I had failed to copy this into the library:

``` csharp
[ContentProperty(Name = nameof(Element))]
```
