### ISSUE TITLE
ModalDialog overlay entire application when launched from page within splitview?

### ISSUE THREAD

**Issue by niels9001** [Windows-XAML/Template10#1450]
I'm using the Template10 ModalDialogs which is working great. However, my current setup is the following:

I have a MainPage with a Hamburger menu (= SplitView) and I set the content with specific pages. Within a page, I have defined a ModalDialog in the XAML and I hope in (ModalDialog.IsModal = true) from the code behind.

Now what happens is that the ModalDialog overlays the page where it belongs to just fine. However, hamburgermenu/SplitView stuff does not get overlayed (since the Page is part of its content, so that makes sense).

The native ContentDialog does not have this issue (it overlays the entire app even when launched the same way). Is there a way to achieve this with the Template10.ModalDialog?

**Comment by dg2k** [comment]
You should make **Shell.xaml** ModalDialog not **MainPage.xaml**. You can do this on startup in **App.xaml.cs** as:

    public override UIElement CreateRootElement(IActivatedEventArgs e)
    {
        ...
        var navService = NavigationServiceFactory(BackButton.Ignore, ExistingContent.Include);
        return new ModalDialog { Content = new Views.Shell(navService), DisableBackButtonWhenModal = true };
    }

**Comment by niels9001** [comment]
I see.. I'm not using the Template10 NavigationService for this. Basically mostly for the ModalDialog. Would this mean a major restructering if I'd use the NavigationService?

Does it make sense to make a function within MainPage (which is the 'highest level') that takes a Dialog as parameter and opens it from there?

**Comment by dg2k** [comment]
You're using HamburgerMenu without nav?
Well, pass **null** for `navService` as Shell ctor() and see what happens then.

**Comment by JerryNixon** [comment]
In addition we will resolve this with the new `PopupEx` we are building.
