### ISSUE TITLE
How to hook into suspension to save data outside of view model?

### ISSUE THREAD

**Issue by pcolmer** [Windows-XAML/Template10#1451]
I have some data being held in a static class that I want to be able to save away when the app is told to suspend but I'm not sure how to handle this when the Bootstrapper only appears to call the active view model(s).

To provide some clarity/background info regarding my approach here ...

I can't (easily) save the data when it is changed within the app because the saves would be triggered on textbox changes which would be every single character, which could result in an undesirable overhead on the system. So, I'm currently caching the data in memory and waiting to save it out at an opportune moment.

I don't want to have an explicit button for the user to click on because some of the data is being changed through the Settings feature and that doesn't have a Save button. The data *isn't* all being saved through the Settings Service because some of it is passwords, so that is going to the Credentials Locker.

So, what is the cleanest way to hooking into suspension activities so that I can explicitly save out my data?

Thanks.

**Comment by JerryNixon** [comment]
App.Suspending?
