### ISSUE TITLE
I think I found a bug Involving Newtonsoft.Json nuget Package

### ISSUE THREAD

**Issue by Quico20** [Windows-XAML/Template10#1452]
I've been exploring template 10 validation, to apply it to my app.

I think I found a bug reference to upgrading Newtonsoft.Json nuget package from 9.01 to any version above it.
The precise detail are at template 10 Validation but it also messed up Template 10 library once I began my detail investigation about what i did to break the designer at VS2017. so my advice do not update to newtonsoft.json version 10.0.1 or 10.0.2 I've already tested them and it break designer mode and template 10 validation and template 10 library.
Detail at template 10 validation or at stackoverflow: 
http://stackoverflow.com/questions/43729727/i-get-a-dependencyproperty-error-if-i-try-to-customize-error-validation-in-templ/43730452#43730452

**Comment by JerryNixon** [comment]
Good catch. Need to figure out why, though.

**Comment by Quico20** [comment]
Hey Jerry, If you could point me in the right direction I might be able to try to fix this bug. 
Or at least I could try.
