### ISSUE TITLE
Wow! I can see [99.99%] Template 10.2 in its full glory...

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#1453]
Thank you @JerryNixon for the hard work. I can clearly see what you've been up to these last few weeks ...

A quote from your posting #1444 from 11 days ago:

> Yeah, it's a mess. 

BUT it was a *beautiful* mess. See what's rising out of it. And thanks again.

**Comment by JerryNixon** [comment]
Thanks. Minimizing major changes at this point. We can start with Pull Requests again.
