### ISSUE TITLE
Attaching My custom Frame Element to the Navigation Service.

### ISSUE THREAD

**Issue by ImCarrot** [Windows-XAML/Template10#1457]
Hi, I've been working with T10 v1.1.12 and I had a quick fix solution to doing the subject. I shifted to T10 v1.1.13 and the issue I am facing is that the navigation is no longer happening from my Frame Control. How do I fix it? My code:
**In the app.xaml.cs**       

      `
       //I set it to "this" in the constructor
       public static App Instance;
       
       public override UIElement CreateRootElement(IActivatedEventArgs e)
       {
            var service = NavigationServiceFactory(BackButton.Attach, ExistingContent.Exclude);
            return new ModalDialog
            {
                DisableBackButtonWhenModal = true,
                Content = new Views.BaseViews.Shell(service),
                ModalContent = new Views.Busy(),
            };
        }
`

        public override async Task OnStartAsync(StartKind startKind, IActivatedEventArgs args)
        {
            var initializer = new SDKInitializer();
            initializer.InitializeSDK(new APIKeysModel(), PluggedIntoPlatform.UniversalWindows);

            await NavigationService.NavigateAsync(typeof(Views.BaseViews.ViewCore));
        }

        /// <summary>
        /// My Hacky way of setting the Frame Componenet Control attached to the Navigation Service.
        /// </summary>
        /// <param name="newNavigationFrame"></param>
        /// <returns></returns>
        public UIElement SetFrameElement(Windows.UI.Xaml.Controls.Frame newNavigationFrame)
        {
            var service = NavigationServiceFactory(BackButton.Attach, ExistingContent.Exclude, newNavigationFrame);
            return new ModalDialog
            {
                DisableBackButtonWhenModal = true,
                Content = new Views.BaseViews.Shell(service),
                ModalContent = new Views.Busy(),
            };
        }`

and on shell Loaded I just call ` App.Instance.SetFrameElement(AppRootFrame);` . I am using the Hamburger Template with T10 v1.1.13 now. It used to surprisingly work before I upgraded to the v1.1.13.
Can someone please guide me as to how can I do it?

**Comment by JerryNixon** [comment]
As an aside, do you like the Modal Dialog as the root?

**Comment by ImCarrot** [comment]
I am not sure how would the modal dialog help, I'll share what I am trying to do, 
I have a HomeView where I put down a map control and over the map control I put a Frame Control (with null background for the user tap to pass to the Map). Now all my subsequent page navigations I want to take place over the Frame Control and not the main Modal Dialog over which the T10 Navigation Service works (such that, at all times, the Map is always there in the background). Now what I want to do is use the navigation service in a way that when I do NavigationService.Navigate, it navigates over the Frame control on the HomeView instead of the Root Modal Dialog. 

Keeping the issue aside, I do like the Modal Dialog as the root especially with the flexibility it provides including the overlay extensibilities (like the busy screen) and the best part is it does contain the current  Frame in it so I have accessibility to the frame as well. The only drawback (almost negligible weightage) is that when I was trying to create a UWP library project (leveraging T10 as well) and yet wanting to be able to support the projects that do not use T10, I had to do an additional check if the currentWindow.Content was a ModalDialog or a Frame and if it was a Modal Dialog then go to the ModalDialog.Content. But then it's too small as compared it to the possibilities that Modal Dialog Offers. Bottom Line: I love the Modal Dialog and I love T10.
