### ISSUE TITLE
ANNOUNCING: Template10-Validation version 1.0.1

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#1462]
There are several improvements, nothing significant. Perhaps the biggest improvement was the REMOVAL of Template 10 from the validation library since there was no reference anyway. Ha! I think I had that referenced by mistake. Should reduce the footprint. I also updated it to the latest NetCore; this should allow apps using it to also update and gain the improvements without duplicating their footprint requirement for the framework. Finally, fixed two real bugs. Special thanks to @Quico20 for bringing this to my attention. If you were using the validation library before, the errors are actually real, but not likely to impact you. Even still, the changes should make upgrading invisible. 

> Version 1.0.1
Upgrade to NetCore 5.3.3
Removed Template 10 from library
Corrected Model.IsDirty bug #9
Corrected Model.ValidateAfter bug #5

Can we all just agree that the validation demo app is the coolest ever?

![lcars](https://cloud.githubusercontent.com/assets/1749983/25974171/ce88bf4c-3664-11e7-9346-5be2dd57a177.gif)

**Comment by Quico20** [comment]
Wow, i'm amazed you accepted my pull request, I feel so proud to have helped. Now we will have to fix the bug with Newtonsoft.Json
Thanks man!!! It is a pleasure to have helped a little bit!!!

**Comment by mvermef** [comment]
Most definitely best interface... LOL 😁
