### ISSUE TITLE
What is the future of Template10? How is it compared to Windows Template Studio (https://github.com/Microsoft/WindowsTemplateStudio)?

### ISSUE THREAD

**Issue by syaifulnizamyahya** [Windows-XAML/Template10#1463]
I'm a huge fan of Template10. Having used it in my project.

Windows Template Studio and Template10 both have Hamburger menu implementation. Which should I choose and why?

What is the future of Template10? Is it going to merge with WTS? Any plans for Cross platform support? Any popular MVVM library integration planned? 

Thanks.

**Comment by Quico20** [comment]
thanks to let me know about this other option, I found Template 10 has more time on the community than Windows Template Studio, I personally havent tried WTS but the documentation for WTS is poor compared to Template 10 and as far as I know Template10 is changing right now to support cross plataform in the future, that is the reason they are separating the library into many pieces.

**Comment by sayedihashimi** [comment]
FYI WTS is built on top of the [Template Engine](https://github.com/dotnet/templating). It's designed to be cross platform and cross editor/tools. When you author a template you can surface it in both `dotnet new` and `Visual Studio 2017`. I think it would be pretty straight forward to move to the Template Engine. If you're interested I'd love to help with that effort. Here is a post on how to author templates with the Template Engine https://blogs.msdn.microsoft.com/dotnet/2017/04/02/how-to-create-your-own-templates-for-dotnet-new/.

**Comment by JerryNixon** [comment]
All good comments
