### ISSUE TITLE
Issue with the Hamburger Menu

### ISSUE THREAD

**Issue by ImCarrot** [Windows-XAML/Template10#1466]
Hi, I am working with T10 v13 20161207 with a Minimal Template. I tried to add a hamburger control to my view, the issue is I get a `Null Reference exception` on opening the hamburger menu. My code is as below:

       `<T10Controls:HamburgerMenu x:Name="Hamburgermenu" DisplayMode="Overlay" NavAreaBackground="{ThemeResource DataCardBackground}" Grid.RowSpan="3">
            <T10Controls:HamburgerMenu.PrimaryButtons>
                <T10Controls:HamburgerButtonInfo ClearHistory="True">
                    <StackPanel Orientation="Horizontal">
                        <SymbolIcon Width="48"
                                Height="48"
                                Symbol="Home" />
                        <TextBlock Margin="12,0,0,0"
                               VerticalAlignment="Center"
                               Text="Home" />
                    </StackPanel>
                </T10Controls:HamburgerButtonInfo>
            </T10Controls:HamburgerMenu.PrimaryButtons>
            
            <T10Controls:HamburgerMenu.SecondaryButtons>
                
                <T10Controls:HamburgerButtonInfo>
                    <StackPanel Orientation="Horizontal">
                        <ToolTipService.ToolTip>
                            <TextBlock MaxWidth="225"
                                   Text="Show Profile "
                                   TextWrapping="Wrap" />
                        </ToolTipService.ToolTip>
                        <SymbolIcon Width="48"
                                Height="48"
                                Symbol="Contact" />
                        <TextBlock Margin="12,0,0,0"
                               VerticalAlignment="Center"
                               Text="User profile" />
                    </StackPanel>
                </T10Controls:HamburgerButtonInfo>

                <T10Controls:HamburgerButtonInfo x:Name="SettingsButton" >
                    <StackPanel Orientation="Horizontal">
                        <SymbolIcon Width="48"
                                Height="48"
                                Symbol="Setting" />
                        <TextBlock Margin="12,0,0,0"
                               VerticalAlignment="Center"
                               Text="Settings" />
                    </StackPanel>
                </T10Controls:HamburgerButtonInfo>
            </T10Controls:HamburgerMenu.SecondaryButtons>

        </T10Controls:HamburgerMenu>`

**Error [Information: here**](https://1drv.ms/f/s!AsbwVCO9nR4ogu0etZF1PvznrM0SQA) with screenshots.

Am I missing something?

**Comment by mvermef** [comment]
Can you show us you code behind for the page it is attached to?  Betting no navigationservice was set up for the control.

**Comment by mvermef** [comment]
Also the HamburgerButtonInfo require a pagetype to navigate to.

**Comment by ImCarrot** [comment]
The Navigation Service was the key there. I had linked it to my Frame Control's navigation service which was not being passed on App Launch. Thanks for the quick tip.
