### ISSUE TITLE
Template10.Validation - IsDirty property

### ISSUE THREAD

**Issue by wyepez** [Windows-XAML/Template10#1467]
Hi guys, I just started to use this amazing library but I have noticed in the last update in ValidatableModelBase that "IsDirty" property is defined in that way
`public bool IsDirty => !Properties.Any(x => x.Value.IsDirty);`
Maybe I have a wrong concept of IsDirty (to me it means that any property has changed) but shouldn't it be in the following way (without the negation operator at the begining):
`public bool IsDirty => Properties.Any(x => x.Value.IsDirty);`
Or perhaps some of you could give me some clarifications.

**Comment by JerryNixon** [comment]
... oh crap.

**Comment by mvermef** [comment]
lol

**Comment by JerryNixon** [comment]
PRs accepted!

**Comment by JerryNixon** [comment]
Commenting on this so it bumps up in my queue.

**Comment by JerryNixon** [comment]
Version 1.0.2 now in Nuget. Thank you so much.
