### ISSUE TITLE
Template always restore NuGet packages

### ISSUE THREAD

**Issue by ProH4Ck** [Windows-XAML/Template10#149]
With Template10 template (downloaded from Visual Studio Gallery) every time i Build project or solution, NuGet packages are restored:

![tpl10](https://cloud.githubusercontent.com/assets/8057670/10117293/9ff7969e-6451-11e5-9dc5-12371c7e06cf.png)

**Comment by dotnetnoobie** [comment]
That is normal, you can turn it off if you want, visual studio is doing it.

Tools >> Options >> NuGet Package Manager 

Uncheck the automatically check for missing packages during build... 
![nuget package manager options](https://cloud.githubusercontent.com/assets/5423598/10118529/5e0cc6b6-64a4-11e5-9321-caccf844d7be.jpg)

**Comment by JerryNixon** [comment]
I believe this is a NuGet issue.
