### ISSUE TITLE
FrameFacade.BackRequested is invoked in the wrong order.

### ISSUE THREAD

**Issue by FrayxRulez** [Windows-XAML/Template10#1490]
BackRequested is invoked from the first to the last subscriber.
Should be the opposite: the last to subscribe (at top of the navigation) should be able to handle the event to prevent previous subscribers to handle it too.

**Comment by tibitoth** [comment]
Prism has a good solution to this: https://github.com/PrismLibrary/Prism/blob/master/Source/Windows10/Prism.Windows/AppModel/DeviceGestureService.cs

**Comment by JerryNixon** [comment]
Which version of T10?
