### ISSUE TITLE
MessageDialogAction Styling

### ISSUE THREAD

**Issue by playitcool** [Windows-XAML/Template10#1491]
I was wondering how I could style the dialog that results from using the behavior? It's perfect for showing a ToS or Privacy Policy yet those are 100% of the time lengthy and require scrolling which this behavior doesn't allow. Am I missing something?

Ideal syntax would be:
```xaml
<Core:EventTriggerBehavior EventName="Tapped">
    <behaviors:MessageDialogAction 
        Title="Terms of Service" 
        Content="...super long text..." 
        Style="{StaticResource ScrollableDialogStyle}" />
</Core:EventTriggerBehavior>

**Comment by pingzing** [comment]
The MessageDialog control actually can't be styled at all. 

If you wanted something like this, you'd probably have to base it around a ContentDialog you create. Of course, there's no ContentDialogAction in Template10 so then you'd have to write that as well...

**Comment by playitcool** [comment]
That's what I've concluded as well. Thanks for the input.
