### ISSUE TITLE
Restore window navigates to MainPage

### ISSUE THREAD

**Issue by o-leary** [Windows-XAML/Template10#1492]
Hi there,

Running my app without debugging attached using 1.1.13-preview-20161207 if I have navigated to another page, then minimized the application, restored it (to refer to some information), minimized it again, then when I restore it a second time the app navigates back to the MainPage. This happens regardless of how long/short a time the app is minimized.

This is using the HamburgerMenu template

Is this common behavior, and is there anywhere obvious to look to prevent this?

**Comment by JerryNixon** [comment]
You think the app is navigating BACK or restarting to MAINPAGE?

**Comment by o-leary** [comment]
When I navigate again to the page I was on, the data is still there despite not being saved, so the app appears to be navigating. This doesn't appear to be happening with a new app from the same template, which means I should be able to move my code into a new project bit by bit, but it will be slow and difficult because the app is almost done and everything will be dependent on every other bit etc.
