### ISSUE TITLE
Menu attached to an AppBarButton in the PageHeader opens in the wrong place

### ISSUE THREAD

**Issue by pcolmer** [Windows-XAML/Template10#1493]
This is a UWP project, targetting Anniversary Edition but running on Creators Update.

The problem I've got is that if I try to have a menu displayed when someone clicks/taps on a button in the primary commands section of the page header, the menu opens in the wrong place:

![capture](https://cloud.githubusercontent.com/assets/1979931/26761153/5455cb2c-4922-11e7-81d1-5a0ba0c62629.PNG)

I've tried:

1. The straightforward/obvious approach:

            <controls:PageHeader.PrimaryCommands>
                <AppBarButton Icon="Find" Label="Find">
                    <AppBarButton.Flyout>
                        <MenuFlyout>
                            <MenuFlyoutItem Text="Option 1"/>
                            <MenuFlyoutItem Text="Option 2"/>
                        </MenuFlyout>
                    </AppBarButton.Flyout>
                </AppBarButton>
            </controls:PageHeader.PrimaryCommands>

2. The approach given in https://github.com/Windows-XAML/Template10/issues/275 but that didn't make any difference to the positioning.

3. The instructions from Tim Heuer in https://stackoverflow.com/questions/23326717/appbarbutton-flyout-bad-positioning. If I specify the page header as the "root", the menu appears centred on the page header bar. If I specify the AppBarButton. the menu appears below the button but in the same incorrect vertical position as the other approaches.

What am I doing wrong?

**Comment by dg2k** [comment]
When you say 'wrong place' I'm assuming that the 'right place' is as for **SecondaryCommands**; right?

Not an out-of-box perfect solution but you can acheive a better look (as for **SecondaryCommands** menu) by tweaking with **MenuFlyoutPresenterStyle** and setting **MinWidth** and **Margin** as follows. **MinWidth** of about 150-200 looks nice and I picked 180. Added **MenuFlyoutSeparator** for completeness.

	  <controls:PageHeader.PrimaryCommands>
		<AppBarButton Icon="Find" Label="Find">
			<AppBarButton.Flyout>
				<MenuFlyout>
					<MenuFlyout.MenuFlyoutPresenterStyle>
						<Style TargetType="MenuFlyoutPresenter">
							<Setter Property="Margin" Value="0,-16,0,0" />
							<Setter Property="MinWidth" Value="180" />
						</Style>
					</MenuFlyout.MenuFlyoutPresenterStyle>
					<MenuFlyoutItem Text="Option 1" />
					<MenuFlyoutItem Text="Option 2" />
					<MenuFlyoutSeparator />
					<MenuFlyoutItem Text="Option 3" />
				</MenuFlyout>
			</AppBarButton.Flyout>
		</AppBarButton>
	  </controls:PageHeader.PrimaryCommands>

- Tweaked for PageHeader PrimaryCommand Menu
![flyoutmenu3](https://cloud.githubusercontent.com/assets/14026786/26766456/15af310c-498a-11e7-8986-cadad359ed3a.PNG)

- Same menu when rendered as PageHeader SecondaryCommand Menu
![flyoutmenu4](https://cloud.githubusercontent.com/assets/14026786/26766460/2502ee28-498a-11e7-8a82-b8dc1d6645cb.PNG)

**Comment by JerryNixon** [comment]
Good solution. Not related to Template 10 though, I am afraid. Create a new issue if I am wrong.

**Comment by dg2k** [comment]
True, nothing to do with T10 indeed.
