### ISSUE TITLE
Template 10 crashes in High Contrast

### ISSUE THREAD

**Issue by zakkar1** [Windows-XAML/Template10#1497]
Hi ,
I'm using the Template 10 to built a UWP . When I raise the contrast on my laptop I have noticed that my app crashes.
I have the same exact problem with a previous post located here
https://github.com/Windows-XAML/Template10/issues/1413

But the thing is that the solution provided in not working.
Any ideas how to overcome this ?
Thank you

**Comment by dg2k** [comment]
Check that all the settings in the working theme (**Dark** or **Light**) match with **HighContrast** theme. In fact, the settings under **Light**, **Dark** (aka **Default**), and **HighContrast** bound to ThemeResource should match, but obviously different values to acheive the desired theme.

If there is a mismatch, ThemeResource fails to locate the value and XAML fails to render, hence the crash. Start from a **ThemeResource** binding in your XAML and look for a missing definition in **HighContrast**, I would assume in **\Styles\Custom.xaml** or wherever the Style is defined.

Also hard-wiring with **RequestedTheme** definition can complicate things, so look into that as well.

**Comment by zakkar1** [comment]
thank you dg2k. I will try it and revert

**Comment by zakkar1** [comment]
Thank you dg2k. It worked !!!! That was the case.

**Comment by zakkar1** [comment]
Unfortunately it worked in a single screen. If I have two screens with the resolution above the 1920 it stills crashes.
In the Custom.xaml i have the below.
Default and HighContrast are exactly the same. The Light IS NOT. Should I change it too ? Should I make it like the default ? 
Appreciate your help on this.

 <ResourceDictionary.ThemeDictionaries>

        <ResourceDictionary x:Key="Light">
           
            <SolidColorBrush x:Key="CustomColorBrush" Color="{StaticResource CustomColor}" />
            <SolidColorBrush x:Key="ContrastColorBrush" Color="{StaticResource ContrastColor}" />
            <SolidColorBrush x:Key="ExtendedSplashBackground" Color="{StaticResource CustomColor}" />
            <SolidColorBrush x:Key="ExtendedSplashForeground" Color="{StaticResource ContrastColor}" />


            <Style TargetType="controls:HamburgerMenu">
                <Setter Property="AccentColor" Value="{StaticResource CustomColor}" />
                <Setter Property="VisualStateNarrowMinWidth" Value="{StaticResource NarrowMinWidth}" />
                <Setter Property="VisualStateNormalMinWidth" Value="{StaticResource NormalMinWidth}" />
                <Setter Property="VisualStateWideMinWidth" Value="{StaticResource WideMinWidth}" />
            </Style>
            
            <Style TargetType="controls:PageHeader">
                <Setter Property="Background" Value="{ThemeResource CustomColorBrush}" />
                <Setter Property="Foreground" Value="{ThemeResource ContrastColorBrush}" />
               
            </Style>

            
            <Style TargetType="controls:Resizer">
                <Setter Property="GrabberBrush" Value="{ThemeResource CustomColorBrush}" />
                <Setter Property="GrabberVisibility" Value="Visible" />
            </Style>

        </ResourceDictionary>



       
        <ResourceDictionary x:Key="Default">


            <SolidColorBrush x:Key="CustomColorBrush" Color="Black" />
            <SolidColorBrush x:Key="ContrastColorBrush" Color="White" />
            <SolidColorBrush x:Key="ExtendedSplashBackground" Color="Black" />
            <SolidColorBrush x:Key="ExtendedSplashForeground" Color="White" />


            <Style TargetType="controls:HamburgerMenu">
                <Setter Property="PaneBorderThickness" Value="0" />
                <Setter Property="SecondarySeparator" Value="{ThemeResource ContrastColorBrush}" />
                <Setter Property="NavButtonBackground" Value="{ThemeResource CustomColorBrush}" />
                <Setter Property="NavButtonForeground" Value="{ThemeResource ContrastColorBrush}" />
                <Setter Property="NavButtonHoverForeground" Value="{ThemeResource CustomColorBrush}" />
                <Setter Property="NavButtonHoverBackground" Value="{ThemeResource ContrastColorBrush}" />
                <Setter Property="NavButtonPressedForeground" Value="{ThemeResource CustomColorBrush}" />
                <Setter Property="NavButtonPressedBackground" Value="{ThemeResource ContrastColorBrush}" />
                <Setter Property="NavButtonCheckedForeground" Value="{ThemeResource CustomColorBrush}" />
                <Setter Property="NavButtonCheckedBackground" Value="{ThemeResource ContrastColorBrush}" />
                <Setter Property="NavAreaBackground" Value="{ThemeResource CustomColorBrush}" />
                <Setter Property="HamburgerForeground" Value="{ThemeResource ContrastColorBrush}" />
                <Setter Property="HamburgerBackground" Value="{ThemeResource CustomColorBrush}" />
                <Setter Property="VisualStateNarrowMinWidth" Value="{ThemeResource NarrowMinWidth}" />
                <Setter Property="VisualStateNormalMinWidth" Value="{ThemeResource NormalMinWidth}" />
                <Setter Property="VisualStateWideMinWidth" Value="{ThemeResource WideMinWidth}" />
            </Style>


            


            <Style TargetType="controls:PageHeader">
                <Setter Property="Background" Value="{ThemeResource CustomColorBrush}" />
                <Setter Property="Foreground" Value="{ThemeResource ContrastColorBrush}" />
                <Setter Property="VisualStateNarrowMinWidth" Value="{StaticResource NarrowMinWidth}" />
                <Setter Property="VisualStateNormalMinWidth" Value="{StaticResource NormalMinWidth}" />
            </Style>

            <Style TargetType="controls:Resizer">
                <Setter Property="GrabberBrush" Value="{ThemeResource CustomColorBrush}" />
                <Setter Property="GrabberVisibility" Value="Visible" />
            </Style>

        </ResourceDictionary>

        <ResourceDictionary x:Key="HighContrast">

            <SolidColorBrush x:Key="CustomColorBrush" Color="Black" />
            <SolidColorBrush x:Key="ContrastColorBrush" Color="White" />
            <SolidColorBrush x:Key="ExtendedSplashBackground" Color="Black" />
            <SolidColorBrush x:Key="ExtendedSplashForeground" Color="White" />


            <Style TargetType="controls:HamburgerMenu">
                <Setter Property="PaneBorderThickness" Value="0" />
                <Setter Property="SecondarySeparator" Value="{ThemeResource ContrastColorBrush}" />
                <Setter Property="NavButtonBackground" Value="{ThemeResource CustomColorBrush}" />
                <Setter Property="NavButtonForeground" Value="{ThemeResource ContrastColorBrush}" />
                <Setter Property="NavButtonHoverForeground" Value="{ThemeResource CustomColorBrush}" />
                <Setter Property="NavButtonHoverBackground" Value="{ThemeResource ContrastColorBrush}" />
                <Setter Property="NavButtonPressedForeground" Value="{ThemeResource CustomColorBrush}" />
                <Setter Property="NavButtonPressedBackground" Value="{ThemeResource ContrastColorBrush}" />
                <Setter Property="NavButtonCheckedForeground" Value="{ThemeResource CustomColorBrush}" />
                <Setter Property="NavButtonCheckedBackground" Value="{ThemeResource ContrastColorBrush}" />
                <Setter Property="NavAreaBackground" Value="{ThemeResource CustomColorBrush}" />
                <Setter Property="HamburgerForeground" Value="{ThemeResource ContrastColorBrush}" />
                <Setter Property="HamburgerBackground" Value="{ThemeResource CustomColorBrush}" />
                <Setter Property="VisualStateNarrowMinWidth" Value="{ThemeResource NarrowMinWidth}" />
                <Setter Property="VisualStateNormalMinWidth" Value="{ThemeResource NormalMinWidth}" />
                <Setter Property="VisualStateWideMinWidth" Value="{ThemeResource WideMinWidth}" />
            </Style>


            

            
          


            <Style TargetType="controls:PageHeader">
                <Setter Property="Background" Value="{ThemeResource SystemColorWindowColor}" />
                <Setter Property="Foreground" Value="{ThemeResource SystemColorWindowTextColor}" />
                <Setter Property="VisualStateNarrowMinWidth" Value="{ThemeResource NarrowMinWidth}" />
                <Setter Property="VisualStateNormalMinWidth" Value="{ThemeResource NormalMinWidth}" />
            </Style>

        </ResourceDictionary>
    </ResourceDictionary.ThemeDictionaries>

**Comment by JerryNixon** [comment]
I will not be able to check on this for a little bit. What version of T10 are you using, please?

**Comment by zakkar1** [comment]
Hi Jerry , 
I'm using 1.1.12.
thank you

**Comment by JerryNixon** [comment]
I want to reiterate that this remains very important
