### ISSUE TITLE
NavigationService Binding in HamburguerMenu is failing

### ISSUE THREAD

**Issue by RafaelPlantard** [Windows-XAML/Template10#150]
Hi, first congrats for this awesomeeee work!
But, I work with Prism 6 and Mvvm, of course, but when I do it:

``` xaml
<controls:HamburgerMenu NavigationService="{Binding NavigationService}">
    <controls:HamburgerButtonInfo>
        <StackPanel Orientation="Horizontal" VerticalAlignment="Center">
            <SymbolIcon Height="48" Symbol="Home" Width="48" />
            <TextBlock Margin="12, 0, 0, 0" Text="Home" VerticalAlignment="Center" />
        </StackPanel>
    </controls:HamburgerButtonInfo>
</controls:HamburgerMenu>
```

This is my view model

``` cs
private readonly INavigationService _navigationService;

public INavigationService NavigationService
{
    get { return _navigationService; }
}

public MainPageViewModel(IUserRepository userRepository, INavigationService navigationService)
{
    _navigationService = navigationService;
}
```

When the page loads I just see this behavior:
![image](https://cloud.githubusercontent.com/assets/5968478/10118144/09b4729c-6447-11e5-92bf-d4bcd6eea107.png)

I am debugging the code to try to find the issue, but I just realize that the binding on navigation service not works, because the get accessor in NavigationService it is never called, but if I do this binding in a TextBlock for example it works, can you help me?

**Comment by JerryNixon** [comment]
Blank screen shot? Haha! Thanks.

**Comment by JerryNixon** [comment]
**First

Are you sure you want to put the HamburgerMenu in your MainPage? Could you please review the Minimal project and double-check you are doing this right?

**Second

Are you sure you want to NOT implement INavigable in your view-model? In Template10, this means the NavigationService is automatically injected for you. Again, see Minimal.

**Third

I have never considered this scenario, but I agree that it should work. Why it is not working is unclear to me, but I will not able to chase it for a while. If you discover the reason, I recommend you create a pull request I can handle for you. I hope you understand.

**Comment by RafaelPlantard** [comment]
The navigation service is injected by Unity Container.

**Comment by JerryNixon** [comment]
How are you ensuring that the Nav Service is the correct service for the frame?
