### ISSUE TITLE
Hamburger Button in Narrow State 

### ISSUE THREAD

**Issue by TheSETJ** [Windows-XAML/Template10#1504]
Hey

Hamburger Button's content seems to go invisible in Narrow Visual State when I open "more" menu. Here's a shot of what happens:

![capture](https://user-images.githubusercontent.com/10893088/27129601-51fb5ce0-5118-11e7-8551-a5b61016fe4d.PNG)

It's happening in Hamburger template completely untouched.

**Comment by TheSETJ** [comment]
@darenm @JerryNixon

**Comment by swisszeni** [comment]
Duplicate of #1349

**Comment by JerryNixon** [comment]
@swisszeni suggestions? @TheSETJ what version of T10 are you using?

**Comment by TheSETJ** [comment]
@JerryNixon v1.19.

**Comment by JerryNixon** [comment]
What does that mean?

**Comment by TheSETJ** [comment]
@JerryNixon version of T10 that I use.

**Comment by JerryNixon** [comment]
Hmm. Okay. Well, do you see the issue when you update to 1.1.13-preview?
