### ISSUE TITLE
Can validator be used to check for null without first initializing the property to null?

### ISSUE THREAD

**Issue by sbraswell** [Windows-XAML/Template10#1509]
We're using validation to check for required fields but have found that when the property is a complex type and might be null we get an exception when doing something like this:
`a.Properties[nameof(a.Country)].Errors.Add("Country is required.");`

Given that `a` above is an `Address` class with a `Country` property that is a complex type. That line is throwing a `NullReferenceException` when the property `Country` of my POCO class is null.

From looking at the source code of Template10.Validation the `Properties` dictionary won't have an entry for a property until the setter is called and invokes the `Write()` method.

One workaround is to initialize our nullable properties in the POCO constructor to null to facilitate the dictionary entry being created. Is this a good way to go about that?

Thanks!

**Comment by mvermef** [comment]
Its a work around, have you seen any adverse affects from the initialization that way?

**Comment by sbraswell** [comment]
No adverse affects observed. It's just a non-intuitive behavior for developers that need to create new Model objects in the project. I'm trying to avoid instituting a hard to remember rule for object developers to implement to support validating null property values. I can work with it if that's the best available option, I just wanted to make sure I hadn't missed anything. Thanks!

**Comment by mvermef** [comment]
I think it has to do with combination of Nullable & Complex type in your case...

**Comment by sbraswell** [comment]
@mvermef Thanks for working through it with me. I think we're going to stick with the workaround for now. Thanks!
