### ISSUE TITLE
Template 10 Shell with Prism 6

### ISSUE THREAD

**Issue by RafaelPlantard** [Windows-XAML/Template10#151]
Hey, it will be amazing if had in the wiki a sample of how to build a UWP app using Template10 + Prism6 using the concept of a shell.

**Comment by JerryNixon** [comment]
Prism for WPF?

**Comment by RafaelPlantard** [comment]
No Prism for UWP.

**Comment by JerryNixon** [comment]
You can't use the Prism Application abstract class. I can't be sure, but I wonder if that removes too much of the value from Prism to show it. Do you know?

**Comment by JerryNixon** [comment]
That being said, you could make a copy of the MVVM Light sample, call it Prism.StoreApps, implement it for me and submit a pull request.

**Comment by briannoyes** [comment]
FYI - Prism 6 for UWP is out and has everything Prism for Windows Store Apps had minus the SettingsPanel support (which is  deprecated in UWP). PrismApplication base class works fine, support both normal launch and other forms of activation and wires things up for ViewModel participation in navigation and state management.

**Comment by darenm** [comment]
Great to hear @briannoyes - congratulations.

**Comment by tpspencer** [comment]
Daren, is there any guidance for including Prism6 with T10?  A demo app or something?  Or, what do you recommend?

**Comment by RafaelPlantard** [comment]
Yep a great notice :100:
