### ISSUE TITLE
VS2017 - Extended Splash Screen issue

### ISSUE THREAD

**Issue by Aymeeeric** [Windows-XAML/Template10#1510]
Hi everyone,

I am currently working on a new project. Ideally the work base would have been Template 10.
However, it seems that the extended splash screen simply does not work .

I really do not understand why.  It seems that it is always the "default UWP" splash screen that takes over... 
I work with the Minimal template, and "SplashFactory = (e) => new Views.Splash(e);" is well defined on the App constructor.

Any help?

Thanks!

**Page code :** 
![2017-06-29 11_01_14-test_t10_new - microsoft visual studio](https://user-images.githubusercontent.com/15995376/27680837-6cb29e76-5cbd-11e7-8948-7d527383913b.png)

**Result :** 
![2017-06-29 11_20_57-sample](https://user-images.githubusercontent.com/15995376/27680845-70488f00-5cbd-11e7-83af-ed730f651ed2.png)

**Comment by porsove** [comment]
Did you try to add some time delay to simulate a long running initialization task in the file: App.xaml.cs ? 
For example:

 public override async Task OnStartAsync(StartKind startKind, IActivatedEventArgs args)
{
            // long-running task here
             await Task.Delay(TimeSpan.FromSeconds(3));

            await NavigationService.NavigateAsync(typeof(Views.StartupPage));
 }

**Comment by Aymeeeric** [comment]
After updating my whole solution : it works.
Sorry to have you bothered for so little!
