### ISSUE TITLE
Can't Install Template 10 in  Microsoft Visual Studio Community 2015 

### ISSUE THREAD

**Issue by Akshay2595** [Windows-XAML/Template10#1511]
I tried to search for template 10 in Microsoft Visual Studio Community 2015, but couldn't find it, then I downloaded .vsix file from website and tried to install it manually, and I got error with it stating " VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products."
I have attached log file here, can you please help with this.
[VSIXInstaller_f15052e5-4682-4f32-a52b-8648769e0fdc.txt](https://github.com/Windows-XAML/Template10/files/1114914/VSIXInstaller_f15052e5-4682-4f32-a52b-8648769e0fdc.txt)

**Comment by Yves-Be** [comment]
Support was dropped for 2015 a while ago, time to install Visual Studio 2017.

**Comment by JerryNixon** [comment]
True. I am sorry.
