### ISSUE TITLE
Problems with navigation and DataContextChangedHandler

### ISSUE THREAD

**Issue by miker1423** [Windows-XAML/Template10#1512]
I'm having trouble with the navigation inside my app, at first, when the app is opened, the DataContextChangedHandler is receiving the correct arguments but when navigating out and then returning to the page, the event is now receiving a ViewModel instead of the model, if I hit continue ignoring the exception, it then receives the correct params.

**Comment by callummoffat** [comment]
Can't help you if you don't give us any context, Miguel.

Thanks,

CJ

**Comment by JerryNixon** [comment]
Why aren't you navigating from within your view-model? And, I suppose, why aren't you navigating from within your NavTo and NavFrom overrides? Strange approach Mike. Tell me a little more what you are doing so I can help.

**Comment by miker1423** [comment]
Well, maybe I wasn't clear enough.
My View has a ViewModel which is the one that runs all code, data binding, etc., inside that page I have a MasterDetailsView, the source of the list view is a ObservableCollection inside the VM, I have separated templates for the master and the details section. when navigating for the first time to the page, I get the correct models, but then, If I navigate to another page and then get back to the page, I get the ViewModel as param to the template instead of the Model that is expected.

**Comment by JerryNixon** [comment]
I think you might be "Go Back to the page" and if that is what you mean then you can check the NavigationMode (a param in OnNavigatedTo) and detect the user is using Back, and alter your code. Right?

**Comment by JerryNixon** [comment]
I would bet a dollar your binding is wrong.

**Comment by miker1423** [comment]
Yes, I might be doing it the wrong way, can you help me checking it?
