### ISSUE TITLE
Ring segment Visual Bug

### ISSUE THREAD

**Issue by VladimirAkopyan** [Windows-XAML/Template10#1513]
If the start value is 0 and end it 0 - 360, the ring works fine. 
If the start is 300 and the end is 10 degrees, then the rings flip out really strangely. Essentially the ring flips out when values pass through zero. 
![image](https://user-images.githubusercontent.com/12278048/28030329-3731c33a-659b-11e7-843f-ff2c7c927bb6.png)

**Comment by JerryNixon** [comment]
You must keep the start and end angles within 360 degrees of each other
