### ISSUE TITLE
Hamburger menu - dynamic primary list 

### ISSUE THREAD

**Issue by VladimirAkopyan** [Windows-XAML/Template10#1514]
I am unclear if one can declare dynamic content for the Template10 hamburger menu the same way one  can for the classic ListView. 
`<ListView >  
  <ListView.ItemTemplate>
    <DataTemplate>
   </DataTemplate>
  </ListView.ItemTemplate>
</ListView>`
This is not a feature request but a question due to my misunderstanding

**Comment by JerryNixon** [comment]
There is no way to do this Vladimir.
