### ISSUE TITLE
Issue with HamburgerMenu when dynamically adding/removing buttons

### ISSUE THREAD

**Issue by arthurrump** [Windows-XAML/Template10#1516]
The problem occurs when dynamically adding a HamburgerButton, then removing it, then adding a new one with the same PageType and PageParameter. When navigating to that newly added page (with the correct parameter) a NullReferenceException gets thrown inside HamburgerMenu.NavButtonChecked(), for details on why, take a look at my research notes at https://github.com/arthurrump/Zermelo.App.UWP/issues/31. It comes down to the button still being in the LoadedNavButtons list, even though it's removed from the PrimaryButtons collection.

Here's a little demo-app: https://github.com/arthurrump/T10-1516

This could be solved by adding a NavButton unloaded event and removing unloaded buttons from the LoadedNavButtons list. I've fixed it for myself in the v1.1.12 branch (https://github.com/arthurrump/Template10/commit/c2f2b149c77ddf1676ebb8ae5d1ebaeb0d53452a), and it looks to work fine. Interested in a PR for master?

**Comment by JerryNixon** [comment]
Not master. Not master! That is 10.2. Look at the 13p branch for a PR.

**Comment by arthurrump** [comment]
There it is 😄
