### ISSUE TITLE
Template 10 project creation failed VS2017/Win10

### ISSUE THREAD

**Issue by Sybren-** [Windows-XAML/Template10#1517]
I just installed the Template 10 Template pack. Now I'm trying to create a Template 10 project. But it doesn't matter which option I choose (Blank, Hamburger, Minimal) I always get the project creation failed error. When I look in the Visual Studio 2017/Projects folder I see that the projects are created but they are completely empty. Maybe a VS update caused this problem? Because I installed a VS update yesterday. I cannot confirm if the update is the issue because I use Template 10 today for the first time.

Visual Studio Community 2017
Version 15.2 (26430.16) Release

**Comment by yehanny** [comment]
Hi, Same problem here with Windows 10/VS 2017 both latest versions, when I try to create a New Project > (Blank, Hamburguer, Minimal) then it says: The project requires a platform SDK (10.0.14393.0) I have installed these versions: 10.0.10586.212, 10.0.14393.33, 10.0.14393.795 and 10.0.15063.137. I also tried to change the required version inside the project file <TargetPlatformVersion>10.0.14393.0</TargetPlatformVersion>
 <TargetPlatformMinVersion>10.0.10586.212</TargetPlatformMinVersion> and this doesn't work neither, any suggestions? Thanks!

**Comment by yehanny** [comment]
Hi, the problem is solved d by doing this, I did it and it really works...

@DennisTycho

> I got the same error, but when looking in the activityLog for VS, I found that it was because I did not have the right WIndows SDK installed. You need the Windows SDK 10.0.14393.0. I got it by downloading the Template 10 sourcecode from github. When building this, I was prompted to install the needed version.
> 
> In the Code tab, you can choose to download in the upper right corner.Perhaps if you could get the specific version of the SDK in any other way, that would be preferable. But i do not know how.
>

**Comment by JerryNixon** [comment]
This is why we need to remove support for older UWP versions.
