### ISSUE TITLE
How can I change back button?

### ISSUE THREAD

**Issue by zakkar1** [Windows-XAML/Template10#1518]
Hi ,

I want to change the backbutton in my template 10 app and I'm wondering if I can do that.
For eg I want to change the width , the height , perhaps the arrow and put something else.
Is there any chance that I can do that by code ?
Where is this BackButton Location were I can apply a different style ?

thank you

**Comment by JerryNixon** [comment]
Do you mean in the PageHeader control? If that is what you mean, there is no option other than retemplating that control. If you mean in the shell, there is no option to change that.

**Comment by zakkar1** [comment]
thank you Jerry
