### ISSUE TITLE
REQUEST: move wiki to md

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#1522]
Does anyone know an easy way to grab all of the wiki and move it to one or more md files? I would like to create a Documentation folder off the root and put the current wiki in a Template10.1 subfolder. 

> /Documentation/Template10.1/{files}

Anyone in @Windows-XAML/template-10-developer-community care to take this on?

PS: my goal will be to disable wiki once we have this worked out. Moving the docs to a pull request-model is going to keep things simpler for me, even if it slows down updates a little.

**Comment by calloncampbell** [comment]
The wiki is already avail as MD files in a git repos located here https://github.com/Windows-XAML/Template10.wiki.git

It's simple enough to checkout and move to a folder structure.

**Comment by calloncampbell** [comment]
I can help with this, just let me know if you want anything else done apart from "create a Documentation folder off the root and put the current wiki in a Template10.1 subfolder".

Which branch do you want this done on?

**Comment by jhalbrecht** [comment]
I get a 404 error on that link. https://github.com/Windows-XAML/Template10.wiki

As a consumer of Template 10 I'd like to see the documentation remain in the Wiki. It seems easier to organize. And easier for a documentation maintainer. Hopefully there is a mechanism for maintaining the Wiki with pull requests.

And hopefully sometime in the future GitHub will make the Wiki searchable.

**Comment by calloncampbell** [comment]
Hi @jhalbrecht the link is provided from the wiki page below the right nav menu. I was able to clone it in VS.

**Comment by calloncampbell** [comment]
Having the docs in the wiki is nice but a lot of open source projects just put their docs in a GitHub repository as MD files and then have an external service that pulls the data and transforms it to HTML. They can then host their docs online in a more professional manner.

I'm all for moving the docs from wiki to source.

**Comment by JerryNixon** [comment]
Hi @calloncampbell, great info. I look forward to your Pull Request.

**Comment by jhalbrecht** [comment]
Guess I missed your point, I hear you now. I thought you were providing an answer to Jerry's question re pulling .md files for the wiki. I'm glad to know how to modify the wiki with a pull request rather than just editing for some other projects - thanks for sharing that.

**Comment by alexdresko** [comment]
I like https://readthedocs.org. It supports compiling markdown from source.
