### ISSUE TITLE
Customizing the Shell

### ISSUE THREAD

**Issue by HesamKashefi** [Windows-XAML/Template10#1525]
Hi,
  I want to know how can I Customize the Shell for my app?
Currently the way of shell creation is ambiguous , I can't understand how it creates the shell so I can't add any control to the Shell, I mean if you take a look at the Prism.Windows it sends us a frame in the bootstrapper  ,So we can put it anywhere in the Shell.
I'm not talking about Prism's Regions because it may be irrelevant to T10 , or at least won't be there soon , I just want to arrange the Shell myself not waiting for some magic to generate it for me.

  This way we can add controls and functionality to the application like adding a Toast Service (something like android Toasts which does not block other user interaction like MessageDialog in windows -which I don't know how to implement yet! otherwise I would implement it for being added to T10.2 ? Maybe? 😁- ) or a command bar present in all the app , ....

 and something else! is there anything that I can do to put a login page before the Shell? does it make any sense? currently I'm using Modal for Login but it's a little weird to me...

**Comment by mvermef** [comment]
First off which shell are you referring to?  Cause each has slight differences and one is pretty far from slight.

**Comment by HesamKashefi** [comment]
@mvermef the one in the default hambergurMenu T10 template ! I didn't know that there maybe another one! Is there?!

**Comment by mvermef** [comment]
That is the only one template with the hamburger there are 2 other templates minimal (pretty much bare bones) and blank.  As far as customizing, you can do just about anything.

I use the hamburger template for a couple of projects, login I created a page for that used built-in features to hide hamburger and do some backend checking to see if they are authenticated, if so I use navigate() to show mainpage and the hamburger, not then hamburger hidden and login page is shown.

**Comment by HesamKashefi** [comment]
@mvermef Oh, I had forgotten that we can hide Hamburger Menu ,Thanks it helps a lot!
Now how to add a banner ad below of the frame for pages inside the Shell (The HamburgerMenu should remain as it is now)

**Comment by callummoffat** [comment]
You should use the Microsoft Advertising SDK. I'd suggest using a separate AdControl for each page, I'm not sure how well the Shell supports footer elements.

**Comment by HesamKashefi** [comment]
@callummoffat I know that! I just used ads as an example! my main question is about manipulating the shell! besides adding an ad to each page make the ad useless cause the pages are navigated before the ad loads!

**Comment by callummoffat** [comment]
I don’t think there’s an inbuilt mechanism for this, but I could be wrong.

Sent from Mail for Windows 10

**Comment by JerryNixon** [comment]
@callummoffat  is right, if you want an ad on each page, then you put the ad on each page. Forget about the shell. Let the loading pipeline of each page handle itself individually an independently. If the page navigates before the page loads, then you are not putting the ad in the correct place or your app navigation is crazy sounding. If what you mean is to have each page update an ad you are placing in the shell, that is totally different. It's possible, but I am not sure it's a great approach. You can edit Shell.xaml and tap into the NavigationService's Navigated event to update the shell somehow, that might give you the most control and flexibility around navigation.

**Comment by HesamKashefi** [comment]
@JerryNixon please forget about the ads!!! just think I've never talked about the ads! I said ads are just an example! if you look at my question I was looking for customizing the shell for whatever reason! 
I said it may be advertisements or Toast or a command bar or maybe just a little Textblock ! WHATEVER not just the ads! 

But anyway, Thank you I think I must somehow try to do something with NavigationService, this doesn't sound right but seems to be the only way.

**Comment by callummoffat** [comment]
It is easily possible to customize the Shell, just not in the way you wish to. 

Sent from Mail for Windows 10
