### ISSUE TITLE
[feature request] Connected Animations Support

### ISSUE THREAD

**Issue by ImCarrot** [Windows-XAML/Template10#1529]
Hi, I've been using T10 for quite a while now and I quite love it. I wanted to know if there is any existing way to provide connected animations using T10 navigation service. 
As a work around currently I write up the connected animations in the OnNavigating to of the code behind and control it using a bool flag in the viewModel. But this approach leads to quite bit of code and serious animation performance issues. 
I was wondering if there are better ways of doing this using template 10.

**Comment by darenm** [comment]
Can you show us what you are doing? I'm interested in better incorporating composition into T10 so understanding your scenario would help.

**Comment by JerryNixon** [comment]
Just an FYI, this is a RS2/3 thing, and belongs in 10.2, not 10.1. You can make the case for it to be otherwise, and if you are only asking for technique advice, I understand. But we want to make sure 10.2 enables every scenario even those it does not implement for the developer.

**Comment by ImCarrot** [comment]
@JerryNixon Hi, I am not really asking for technique here, it's more of a feature request if I can request a feature, or probably make a case for it. @darenm , yes I do have a work around that I use to get connected animations. I'll post the code as a comment as well in a few moments. It'll be really cool to have it in T10 as well.

**Comment by ImCarrot** [comment]
@darenm , I've got a quick sample up on github for the workaround for Connected Animations using T10.
Link: [T10ConnectedAnimSample](https://github.com/ImCarrot/T10ConnectedAnimSample) . Hopefully it can be made a part of T10 samples. I've made a pull request for the same as well.

**Comment by michaelhutchful** [comment]
Very nice implementation

Sent from Mail for Windows 10

**Comment by ImCarrot** [comment]
@michaelhutchful  Thanks :)

**Comment by JerryNixon** [comment]
There's a pull request to demo this. If it is not for the 13p branch then hold off.
