### ISSUE TITLE
10.2 Ready! Let's start testing.

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#1530]
Hey @Windows-XAML/template-10-developer-community 

Great news. What you find in `Master` today is the near-finished version of 10.2. You read that right, we're close. There are some things I have not added yet because of RS3, but you can test this on Creators Update with Visual Studio 2017 v15.2 or v15.3 (which is brand new). 

What to test.

`Blank` and `Minimal` are all we have working at this point. But they should be working. We're defaulting to MvvmLight at this point, and you will see it's going to be simple to provide guidance to use any other DI, MVVM framework, or message aggregator for teams that need that.

Then what?

Getting this wrapped in Nuget packages and an updated VSIX will be no small trick. But we won't start toward that until we get testing in place. We're also, finally, setup for unit testing - though I have not added any of them yet. We're also setup to be portable to Xamarin.

Pull requests?

Yes. Be sure you are submitting for `Master` and be sure to flag your PR with `10.2` or something so I know that you know what you are fixing. And if you want to create an issue, use some type of `10.2` prefix in the name so I can keep those categorized correctly.

Excited?

I hope so. I know I am. It's been a lot of work, a lot of late nights, a lot of refactoring over and over. If we need to do some big fixes or some major refactoring, I am not afraid to do that at this point. In the meanwhile, I think what you see in the repo today is going to be close to the real thing.

**Comment by rpedretti** [comment]
That's great news! As soon as I get hands on my computer I'll try it. Are there any steps we have to follow to get started?

**Comment by HesamKashefi** [comment]
Well done! You mentioned Xamarin, does it mean we can use T10.2 in net Standard libraries? (specifically version 1.4 which is the highest version supported by UWP currently)

**Comment by Quico20** [comment]
I'm currently developing an app using T10.1 version.
once T10.2 gets to nuget will i be able to update to T10.2 without breaking the app or should I start a new app for it? (mostly refactor my app).

**Comment by rpedretti** [comment]
Just cloned the and got a version mismatch error
![version mismatch](https://user-images.githubusercontent.com/675601/29489698-4a0f789a-84fd-11e7-846b-005d19a67691.PNG)
easely fixed, but then the nuget downgrade warnings came. Checking the nuget packages I found diferences at Microsoft.NETCore.UniversalWindowsPlatform version, some projects targeting 5.23 and others 5.3.3. SOme other libs have this problem too. What's should we do in this case? Open a bug? Update the libs and make a PR?

**Comment by JerryNixon** [comment]
Hey @rpedretti  I think this is a PR.  My brain does not understand why this is not happening to me, though. That being said, if you are getting this, then others may also be getting them. 

### For UWP

Target: Creators
Minimum: Anniversary

### For NETCore

I see 5.4.0 is now available, those should be in sync.

### For .NET Standard (Template10.Portable)

It's currently 1.4, but we can discuss 2.0. Not sure about that.

**Comment by rpedretti** [comment]
Ok then. I'll double check my corrections tomorrow and make the PR. 

I might also start a thread on the DI approach as it does not handle an important aspect: Named registration/retrieval.

**Comment by JerryNixon** [comment]
I just pushed up the NETCore sync.

**Comment by akshay2000** [comment]
Hey @Quico20, I am in the same boat as you. I think we should hold on until there is a clear upgrade path. We also need to consider if it is worth the effort. Right now, my app is not in active development mode. So, cost of upgrading T10 outweighs the benefits.

**Comment by JerryNixon** [comment]
@Quico20 and @akshay2000 I wanted to say two quick things. The first is that 10.1 is awesome and there is no reason to upgrade except that work is turning toward 10.2. The second is that the purpose of 10.2 is that maintaining it in the future and meeting the needs of more sophisticated apps was getting hard with 10.1 and 10.2 resolves that in many ways. Right now, I am asking for help testing 10.2, but I am certainly not asking anyone to upgrade to it (at this point it's a little early). And, let's be clear, the upgrade path will not be trivial, the signature of many methods has changed. Having said that, I think it's possible to identify places where small nudges to the API before it is finalized can help simplify migrations for developers wanting the newer, leaner, faster, and more modular 10.2.

**Comment by Quico20** [comment]
@JerryNixon Thanks for your answer, I know you guys have been working hard on upgrading T10.1 to T10.2 I think I'll finish my app using T10.1 and once T10.2 had been tested I'll update it. I love to keep update and hate to be left behind.
Another thing I wanted to comment, please when you finish T10.2 could you check on T10 1.1.2 Validation.
Its annoying not being able to use design mode on x86 projects and also the bug with newtonsoft above verson 9. still there, and in my opinion its a great API for client side validation, I Love it, been using it with UWP and my Mobile Apps service for my app and its amazing, please Jerry dont forget about that great API.

**Comment by JerryNixon** [comment]
I look forward to your 10.2 pull requests!

**Comment by tpspencer** [comment]
Not many comments on 10.2 since August.  I am starting a new project and would like to test out 10.2.  What is the latest brain dump on where we sit?

**Comment by JerryNixon** [comment]
@tpspencer help out by looking into Master today.
