### ISSUE TITLE
10.2 Discussion: DI container override with MvvmLight Bootstrap

### ISSUE THREAD

**Issue by rpedretti** [Windows-XAML/Template10#1536]
Looking aroud the code I found that the navigation service takes care of getting the ViewModel for the page with **_ViewModelResolutionStrategy.ResolveViewModel_** and the BootStrapper class register the _**DefaultViewModelResolutionStrategy**_ resolver, wich does nothing.

With T10.1 I used to set a static container at the App class and register my ViewModels like:
`Container.register<INavigable, MainPageViewModel>(nameof(MainPage))` and get hold of then at the pages contructor like `DataContext = App.Current.Container.Resolve<INavigable>(nameof(MainPage))`. This raises the first question: In T10.2 do we need to create a specifc interface for every ViewModel?

I aks this because registering a type with a key is currently not supported by the **_IContainerService_**. And the closest ISimpleIoc gets is with
`Register<TClass>(Func<TClass> factory, string key) where TClass : class;`
wich needs a factory function, and there i loose all the ease the IoC provides to me: Resolving all dependencies for the object I want (IUnityContainer does that).

And setting a new DI container to the _**ContainerService.Default**_ will have the side effect of loosing all previous registration made by the BootStrapper.

As for now _**IViewModelResolutionStrategy**_ needs a Type or a Page to resolve so the container has to have a way to know how to discriminate the instance by the type and I can't do that with MvvmLight.

So what is the best approach to use the IViewModelResolutionStrategy? Copying the code from MvvmLight BootStrapper and change the DI container is not an option.

I think that the first step is to make _**IContainerService**_ to accept the keyed registration, but after that I'm kinda lost :(

**Comment by rpedretti** [comment]
Ok, after a good night of sleep I though of the Prism ViewModelLocator, so maybe a good way to achieve what I want is to use naming convention
```
public async Task<object> ResolveViewModel(Type type)
    => await Task.FromResult(ContainerService.Default.Resolve<ITemplate10ViewModel>($"{type.Name}ViewModel"));

public async Task<object> ResolveViewModel(Page page)
    => await ResolveViewModel(page.GetType());
```

But again the SimpleIoc lacks the ability to to resolve like that

**Comment by JerryNixon** [comment]
That's why we have IContainerService, I am sure we can abstract this within the IViewModelContainerAdapter, even if we need to extend the contract of the service. This will take some investigation, but handling like that seems like a sensible approach if we can make it work with SimpleIoT. This mismatch in functionality will continue, but we can overcome this, I am sure. I welcome your suggestion as I am looking into this.

**Comment by JerryNixon** [comment]
Okay, so I talked with Laurent (he wrote MVVMLight). Here's what he suggested.

````csharp
SimpleIoc.Default.Register<INavigable>(() => new SecondViewModel(), nameof(SecondPage));
SimpleIoc.Default.Register<INavigable>(() => new ThirdViewModel(), nameof(ThirdPage));
````
I will implement this right now. As an aside, Laurent said he will promote the syntax to be more direct in vnext. Let's call that a win-win. Look for my commit later today.

**Comment by JerryNixon** [comment]
You might be asking, do I see the problem? Yes. Rats...

**Comment by rpedretti** [comment]
The problem is exactly the factory....no DI there :(

For now I'll be commiting an example app at my fork using the Prism container, just to make na example with the proposed IContainerService. We don't have permission to create new branches here, do we?

**Comment by JerryNixon** [comment]
Here's where we are headed:

````csharp
public void Register<TInterface, TClass>(string key)
    where TInterface : class
    where TClass : class, TInterface
{
    // note: this is a workaround until SimpleIoT supports .Register<TInterface, TClass>(string key);
    _container.Register<TClass>();
}

public TInterface Resolve<TInterface, TClass>(string key)
    where TInterface : class
    where TClass : class, TInterface
{
    // note: this is a workaround until SimpleIoT supports .Register<TInterface, TClass>(string key);
    if (_container.IsRegistered<TClass>())
    {
        return _container.GetInstance<TClass>();
    }
    else
    {
        throw new Exception();
    }
}
````

Will need to test it.

**Comment by rpedretti** [comment]
What I have now is very similar to this. I'll make a PR of it. It will also contain a demo app.

I opted out to throw a NotImplementedException to make it explict that it does not work for now.

**Comment by JerryNixon** [comment]
Okay, check out the current Master. Please volunteer to test it for me.

**Comment by rpedretti** [comment]
I volunteer!

Just checked it out and it does not support ```ContainerService.Default.Resolve<ITemplate10ViewModel>(type.Name)``` because of the interface ```TInterface Resolve<TInterface, TClass>(string key) where TInterface : class where TClass : class, TInterface;```

So there is a nedd for a ```TInterface Resolve<TInterface>(string key) where TInterface : class where TClass : class, TInterface;``` so it can support resolving in runtime

**Comment by rpedretti** [comment]
Because the interface only accepts ```TInterface Resolve<TInterface, TClass>(string key)``` it's not possible to resolve keyed objects without a base class.

If I have a multiple classes implementing only a Interface i cannot resolve it like
```ContainerService.Default.Resolve<ITemplate10ViewModel>(type.Name))```
