### ISSUE TITLE
Updating the theme in the settings page does not reflect on the HamburgerMenu

### ISSUE THREAD

**Issue by janabimustafa** [Windows-XAML/Template10#154]
The HamburgerMenu or the splitview will stay on the theme they started with and will only change upon restart. Consider using ThemeResource instead of binding for the brushes.

**Comment by janabimustafa** [comment]
I fixed this issue locally:
1. Use ThemeResource instead of binding when setting brushes.
2. Use a single Custom.xaml style file. ThemeDictionaries merging causes unexpected behavior.

I am willing to submit a pull request, but I am afraid the changes I made are quite controversial and will need to be discussed.

**Comment by JerryNixon** [comment]
Don't merge the files though. I will not accept that pull request.

**Comment by JerryNixon** [comment]
Here's a design goal. To support Styles/Setters that allow the user to see auto-compelted intellisense properties so they know what they can actually change. Right now we are accomplishing that by using Dependency Properties on the control. Those are bound to the individual properties then. I think we might be able to get the best fo both worlds. But I will need to test it. Perhaps you could test it?

**Comment by JerryNixon** [comment]
Pretty curious of your solution. Care to email me a sample? jnixon@microsoft.com
