### ISSUE TITLE
Feature request: Template10.Service.Resources

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#1541]
This will include:

1. `ResourceService` : `IResourceService` which will wrap ResourceLoader

Why? So we can test this stuff.

Re: https://github.com/Windows-XAML/Template10/pull/1508/files#diff-8466366fbb4a3ae5206491a7510ea4d8

**Comment by JerryNixon** [comment]
Note that this will need to be deleted.

https://github.com/Windows-XAML/Template10/tree/master/Template10/Template10.Core.Shared/Services.Resources

**Comment by rpedretti** [comment]
I volunteer to implemente this one!

**Comment by rpedretti** [comment]
@JerryNixon what do you think of making the ResourceService a partial class so in a near future we can implemente a tool like https://reswcodegen.codeplex.com/ that generates an interface and partial class to give the user access to the localized resources?

**Comment by JerryNixon** [comment]
I think that is awesome, by the way. Thank you for pointing it out to me, I think it belongs in Template.Advanced, perhaps. As far as this service, no. This will remain a testable, generic, interface. I will introduce a few things n the Dialog service to account for "Ok" and "Cancel" in different languages, and need to sooner than later. Also, a partial will not work across assembly boundaries. I think to get what you want, @rpedretti, we need only make it so it can be inherited.

**Comment by rpedretti** [comment]
Ok, I'll try to get it done by the weekend then!

**Comment by rpedretti** [comment]
I came across an impasse. The service can be used in both ui and non-ui threads, correct? If run in UI thread ```ResourceLoader.GetForCurrentView()``` should be used, otherwise ```ResourceLoader.GetForViewIndependentUse()```

What's the drawback on using ```ResourceLoader.GetForViewIndependentUse()``` on both UI na non-UI threads? Or should I wrap all in a dispatcher? I've Always used  ```ResourceLoader.GetForCurrentView()```  because I knew i was going to call it mostly in UI threads and used a dispatcher where needed. But I'd like to avoid delegating this to the developper
