### ISSUE TITLE
How to include ExistingContent in 10.2?

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#1543]
@JerryNixon - am I missing something with ExistingContent.Include/ExistingContent.Exclude option? I can't see how to include **Window.Current.Content**. 

- 10.1
    
      public override UIElement CreateRootElement(IActivatedEventArgs e)
      {
          var navService = NavigationServiceFactory(BackButton.Ignore, ExistingContent.Include);        
          return new ModalDialog
          {
              Content = new Views.Shell(navService),
              DisableBackButtonWhenModal = true
          };
      }
   

- 10.2 equivalent (I think)

      public override UIElement CreateRootElement(IStartArgsEx e)
      {
          INavigationService navService = null;

           WindowEx.Current().Dispatcher.Dispatch(async () =>
           {
               navService = await Template10.Navigation.NavigationService.CreateAsync(BackButton.Ignore);
            });

            return new ModalDialog
            {
                Content = new Views.Shell(navService),
                DisableBackButtonWhenModal = true
            };
       }

**Comment by JerryNixon** [comment]
I feel like you are testing hamburger. Let's test Minimal first!
