### ISSUE TITLE
AppBarButton in PageHeader

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#1547]
@kfchengkf mentioned an issue with **AppBarButton** in PageHeader (see #1526). I noticed this problem for over a year with the **Anniversary Update** early August 2016. It was at the same time I also noticed another platform related issue with regard to a 4" Emulator -- see issue #1178.

## The Problem

The problem is with the **ContentControl** in a Grid control (with `x:Name="ContentRoot"`) in PageHeader's control template xaml. What is going on is that once the **ContentControl** expands (due to a collapsed element being visible), it will never shrink back to an Auto width/height required when one or more elements collapse. Interestingly, if you keep toggling visible/collapse, the ContentControl keeps on growing (sure, it recognizes visibility, but totally unaware of collapse) to the extent that Primary menu AppBarButton captions show up in Secondary menu.

Could this point to a solution within Template10, perhaps based on how *space-filler controls* and others are interacting? PageHeader is a relatively complex control and perhaps a close look could reveal something. I can't see anything obvious that forces the **ContentControl** behave this way, but @JerryNixon can comment on this one.

## A Solution, kinda...

- Define a Width DependencyProperty for the **ContentControl** in question. Call this **ContentWidth**.

- Bind the **ContentWidth** DP to **ContentControl**'s Width with `TemplateBinding`.

- In your design, play with the PageHeader.ContentWidth property to counteract the issue described. Typically you'd use a Setter in VisualStateManager, for example:

`<Setter Target="pageHeader.ContentWidth" Value="0" />` or
`<Setter Target="pageHeader.ContentWidth" Value="NaN" />`

I will do a PR on this (for 10.1 and 10.2)

**Comment by JerryNixon** [comment]
Okay, explain which PR is which?
