### ISSUE TITLE
HamburgerMenu Display Mode

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#155]
Don't know if I'm over-looking the obvious -- what's an easy way to find out the DisplayMode (Overlay, CompactOverlay, Inline)  for the HM in the Shell.xaml codebehind? I needed this 'cos I have a notification status bar at the bottom of screen that needs its left margin set conditionally (48 in CompactOverlay mode so as not to cover the Settings icon, 0 otherwise as in Mobile).

If this is not currently possible, do you see the need for this feature as I obviously do?

**Comment by youtoofan** [comment]
Why don't you use 'VisualStateGroups' ?

**Comment by dg2k** [comment]
Can you Q.E.D your statement please?

Although I can see the defined visual states quite easily, I cannot see an object that gives me the CurrentState of the VisualManager.

**Comment by JerryNixon** [comment]
Every VisualState is a child of a VisualStateGroup. The VisualStateGroup is an object with properties, including CurrentVisualState. Check it out. That being said, I think it makes sense to have a public, readonly property to let the developer test what the current display mode is. Let me think about it.

**Comment by JerryNixon** [comment]
Added the property. It is readonly. It is also a dependency property, so you can bind to it and listen to it.

**Comment by dg2k** [comment]
Thanks a lot Jerry.
