### ISSUE TITLE
Why is ModalDialog tagged as Deprecated?

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#1562]
@JerryNixon - I was about to make a PR on **ModalDialog** control (`IsModalChanged` event) and just noticed that you tagged it as **Deprecated**. Did I miss any background on this? Is there an equivalent control in the offing with new UWP version?

I find ModalDialog very useful indeed. Any clarification on the suggested deprecation would be appreciated.

**Comment by JerryNixon** [comment]
Yes, ModalDialog is deprecated because of a new control @darenm is working on. There's a possibility we won't be able to work out the new control, so we haven't talked about the new control yet.

**Comment by JerryNixon** [comment]
@dg2k you can add me to Skype if you want more info "mr.jerrynixon"
