### ISSUE TITLE
Right PaneBorder doesn't show in HamburgerMenu compact view

### ISSUE THREAD

**Issue by schnitty** [Windows-XAML/Template10#1563]
I'm trying to implement a design where the background colour of both panes are the same colour.
As such in the compact view I would like to have 1px border on the right that acts as the seperator.

I haven't been able to achieve that by setting the PaneBorderBrush or PaneBorderThickness properties.
I have also tried making the HamburgerButtonGridWidth property a bit wider but that had no effect.

The border does appear when the menu is expanded but not when compacted.

Is there a way I can make it show in the compacted view and im just not doing right?  Or will I have to customize the usercontrol to make it do what I want?

I see a similar issue has been discussed before #400

**Comment by dg2k** [comment]
<Style x:Key="HamburgerMenuStyle" TargetType="controls:HamburgerMenu">

          				
          
          <Setter Property="PaneBorderBrush" Value="Gray" />
          <Setter Property="PaneBorderThickness" Value="0,0,1,0" />
          
     </Style>

**Tested and works.**

**Important:** You need to define for Light, Dark, HighContrast themes, as shown in **Custom.xaml** style for the Hamburger project.
