### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by mvermef** [Windows-XAML/Template10#1567]
Does the Demo for ProfileService target XAML 2.0 since it has a different version of the Microsoft.NETCore.UWP not even beta.. It throws errors then getting warnings related to Conflicts with versioning on others...

**Comment by JerryNixon** [comment]
What are you talking about?

![image](https://user-images.githubusercontent.com/1749983/30087029-7a2a7d8e-925b-11e7-8460-14d5a6caf266.png)

![image](https://user-images.githubusercontent.com/1749983/30087052-8d6316c2-925b-11e7-9385-930822f00d65.png)

**Comment by JerryNixon** [comment]
My bad

![image](https://user-images.githubusercontent.com/1749983/30087068-a3f2130c-925b-11e7-8cb7-f9acbc4f0bd2.png)

**Comment by JerryNixon** [comment]
This better? 

![image](https://user-images.githubusercontent.com/1749983/30087078-b0699bfa-925b-11e7-99dc-a029d6fd1196.png)
