### ISSUE TITLE
Discussion: default version optional services

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#1568]
Template 10, internally, uses several services and, as a result, registers those in the default dependency container which can then be used by the consumer/developer if they like. These:

````
container.Register<ISessionState, SessionState>();
container.Register<ILoggingService, LoggingService>();
container.Register<ISerializationService, JsonSerializationService>();
container.Register<IBackButtonService, BackButtonService>();
container.Register<IKeyboardService, KeyboardService>();
container.Register<IGestureService, GestureService>();
container.Register<IResourceService, ResourceService>();
container.Register<INetworkAvailableService, NetworkAvailableService>();
container.Register<IDialogService, DialogService>();
````

However, there are some services which are not used internally in Template10, but are still relatively fundamental. At this time, this is the only example I can pull together:

````
container.Register<IMarketplaceService, MarketplaceService>();
````

The question really is, should Template 10 auto-register all of its services (adding them as we add services) or only the ones it uses internally? And, if your answer is only the ones we register internally, how do you recommend we inform the developer we have registered these services for him?

Make sense?

**Comment by tibitoth** [comment]
Make a call to in the tempalete's App.xaml.cs like `container.RegisterT10OptionalServices()` which is register these. Developers can easily delete this line is they don't want to register these.

**Comment by rpedretti** [comment]
As a developer i would like to have something like ```BootStrapper.RegisterDefault[ServiceName]()``` and maybe ```BootStrapper.RegisterFor[ServiceName](serviceImpl)``` for custom implementation
