### ISSUE TITLE
NavigationServiceFactory call in OnInitializeAsync hangs on resume (Mobile)

### ISSUE THREAD

**Issue by bc3tech** [Windows-XAML/Template10#157]
In Windows 10 Mobile, we're seeing the Splash page sit infinitely when we do the following:
1. Start up app with full network, get to the first page (which pulls data)
2. Leave the app. Turn on airplane mode. Restart app.
3. You will either see infinite progress ring, or a crash.

It is not reproducible in the debugger, so I had to add file writing calls, and read the content of the file on app restart to see what was happening.

In the case of a crash, here's the exception detail:

```
Exception:Value does not fall within the expected range.
   at Windows.UI.Xaml.Controls.ContentControl.put_Content(Object value)
   at Template10.Common.BootStrapper.NavigationServiceFactory(BackButton backButton, ExistingContent existingContent)
   at My.Application.<OnInitializeAsync>d__11.MoveNext()`
```

**Comment by JerryNixon** [comment]
We need to verify that this is not an OS bug before we chase it very far.

**Comment by darenm** [comment]
I have seen this manifesting as a timing issue previously where the Content that is being added already has a parent control... If you have a simple repro app we can use that saves us time when we investigate.

**Comment by DamMenGH** [comment]
In my case there's no need to turn on airplane mode, just suspend and resume the app.

**Comment by JerryNixon** [comment]
Guys, listen. I am closing this issue until Mobile is RTM (next month).

**Comment by francedot** [comment]
Reproduced the bug of Minimal also on Desktop by minimizing the app and launch it from main tile after a while.

**Comment by ryanzzff** [comment]
I can reproduce the issue using the Minimal Sample (on Win 10 Desktop) by adding a http call inside `OnInitializeAsync()`:

```
public override async Task OnInitializeAsync(IActivatedEventArgs args)
{
    try
    {
        WebRequest webRequest = HttpWebRequest.Create("http://www.google.com");
        await webRequest.GetResponseAsync();
    } catch (Exception) { }

    //setup hamburger shell
    // Exception thrown at assigning Splash (Window.Current.Content) to new Frame().Content
    var nav = NavigationServiceFactory(BackButton.Attach, ExistingContent.Include); 
    Window.Current.Content = new Views.Shell(nav);
}
```

**Comment by karl-barkmann** [comment]
use lifetime event can reproduce this bug easily(Both Desktop and Mobile)
