### ISSUE TITLE
Is it possible to use ReactiveUI with Template 10?

### ISSUE THREAD

**Issue by harvinders** [Windows-XAML/Template10#1571]
I read somewhere that instead of using the `ViewModelBase` we can use another base class from some other MVVM framework (in my case `ReactiveObject`). Is this correct? How would I go about it? Also, more importantly, would it continue to be supported with Template 10 2? 

Thanks
harvinder

**Comment by JerryNixon** [comment]
I do not think that would be possible, no.

**Comment by JerryNixon** [comment]
That being said, don't let me discourage you from trying.

**Comment by tibitoth** [comment]
Maybe if you create a descendant class of `ReactiveObject` and implement all `NavigationService` related interface? Also NavService need to depend on only interfaces in this case (I don't check this is the current state)

**Comment by harvinders** [comment]
@totht91 @JerryNixon I am able to do it. I derived a class from `ReactiveObject` and implemented the 3 odd methods of `NavigationService`. That said, the view model now have a different way and classes (`ReactiveCommand`) to handle `INotifyPropertyChanged` event and the commands.

**Comment by JerryNixon** [comment]
Good work @harvinders
