### ISSUE TITLE
AwaitableDelegateCommand CanExecuteChanged isn't updating

### ISSUE THREAD

**Issue by ShawnTheBeachy** [Windows-XAML/Template10#1577]
I have an `AwaitableDelegateCommand` which is bound to a button.

The XAML:

``` XAML
<AppBarButton Command="{x:Bind ViewModel.RefreshCommand, Mode=OneWay}" />
```

The command:

``` C#
private bool _isRefreshing = false;
private AwaitableDelegateCommand _refreshCommand;
public AwaitableDelegateCommand RefreshCommand =>
    _refreshCommand ?? (_refreshCommand = new AwaitableDelegateCommand(
        new Func<AwaitableDelegateCommandParameter, Task>(async (param) =>
        {
            _isRefreshing = true;
            RefreshCommand.RaiseCanExecuteChanged();
             
            await RefreshAsync();

            _isRefreshing = false;
            RefreshCommand.RaiseCanExecuteChanged();
        }), new Func<AwaitableDelegateCommandParameter, bool>((param) => !_isRefreshing)
    ));
```

However, even though my second `RaiseCanExecuteChanged()` is hit, the `canexecute` function isn't called. It's called when I raise it the first time (where `_isRefreshing` is `true`), but not the second time. This results in my button being permanently disabled.

Without any documentation on the `AwaitableDelegateCommand` I can't be sure I'm using it 100% correctly, but from what I can tell this seems to be a bug in Template10.

**Comment by darshanrampatel** [comment]
@TastesLikeTurkey, I tend to just use the regular `DelegateCommand` instead:

```csharp
DelegateCommand _RefreshCommand;
public DelegateCommand RefreshCommand => _RefreshCommand ?? (_RefreshCommand = new DelegateCommand(ExecuteRefresh, CanRefresh));

private async void ExecuteRefresh()
{
    if (IsLoading)
    {
        return;
    }
    IsLoading = true;
    await RefreshAsync();
    IsLoading = false;
}

private bool CanRefresh()
{
    return !IsLoading;
}

private bool _IsLoading = false;
public bool IsLoading
{
    get => _IsLoading;
    set
    {
        Set(ref _IsLoading, value);
        RefreshCommand.RaiseCanExecuteChanged();
    }
}
```

**Comment by ShawnTheBeachy** [comment]
@darshanrampatel Yes, that works for me. But I thought I'd report my problem with the `AwaitableDelegateCommand`, inasmuch as it seems to be a bug in Template10.

**Comment by darshanrampatel** [comment]
@TastesLikeTurkey Yes, just tested and I can replicate your issue. Seems like a bug with `AwaitableDelegateCommand`.

On a related note, what is the benefit with using `AwaitableDelegateCommand` over `DelegateCommand `?

**Comment by ShawnTheBeachy** [comment]
@darshanrampatel It would be nice to be able to do `await RefreshCommand.InvokeAsync()` when the page is navigated to.
