### ISSUE TITLE
CreateRootElement never called

### ISSUE THREAD

**Issue by nyx-lyb3ra** [Windows-XAML/Template10#1578]
The CreateRootElement method never runs because an exception occurs during the execution of the SetupCustomTitleBar method

Template10 v1.12
Visual Studio 2017
MinTarget: Creators Update 1703 (build 15063)
Target: Fall Creators Update 1709 (build 16299)

**Comment by JerryNixon** [comment]
This worked for everyone else. My guess is you must have figured it out. Can you share?
