### ISSUE TITLE
Roadmap for Template 10 v2 with new FallCreatorsUpdate

### ISSUE THREAD

**Issue by calloncampbell** [Windows-XAML/Template10#1579]
What is the new roadmap for Template 10 with the new features that are part of the Fall Creators Update like the NavigationView and Fluent Design?

**Comment by darenm** [comment]
If you look at 10.2 you will see that it is being "broken apart" into various packages to separate out the controls and the core services of Template10. As such, most of the Template10 library won't "care" about things like the `NavigationView` control and UI design. Of course, we intend to extend `NavigationView` such that there is a nice integration story with the Template10 `NavigationService`.

In terms of the templates, we will be revisiting the min/max versions and considering what capabilities of FCU to light up by default.

**Comment by ghost** [comment]
I would love to see a Messenger shipped with T10.
Adding a whole MVVM Framework (e.g.: MVVM Light or PRISM) to the project just to use their Messenger implementation is a bit much overhead.

**Comment by JerryNixon** [comment]
We now ship Messenger with it. Great suggestion. Take a look.
