### ISSUE TITLE
Library trying to navigate without using Template10

### ISSUE THREAD

**Issue by mjmeans** [Windows-XAML/Template10#1587]
I'm using a library that upon a certain call, tried to navigate tp it's own XAML UI views without any knowledge of Template10. I've tracked it to the following code "var rootFrame = Window.Current.Content as Frame; rootFrame.Navigate(typeof(SpecialPage), parms);" which of course fails. Window.Current.Content is returning a Template10.Control.ModalDialog which is a ContentControl, not a Frame, so it is failing. So this library needs to navigate away from Template10 and it needs to do it without any knowledge of Tempalte10.

Is this possible?

**Comment by darenm** [comment]
It sounds like you are using an API that makes assumptions about how the root content of an app is setup. Does that API allow you to supply a Frame instance? If so, you could pass in the T10 Frame for some level of integration. What is the library giving you?

**Comment by mjmeans** [comment]
No it doesn't. The API is HockeyApp-UWP with ported over UpdateManager code and XAML pages from HockeyApp-WP81.

Is there a way to tell Template10 to use a normal window frame (as a root frame) and host all Template10 content within that frame? If this were possible, then any library that tries to display a message using "var rootFrame = Window.Current.Content as Frame;" would succeed. With the caveat that such a library displaying a page would completely hide everything hosted by Template10 until they navigated back to is.

**Comment by darenm** [comment]
Ah this thorny issue. This is, in reality, a bug with that version of HockeyApp - it is an erroneous assumption that every app would have a root control that is a Frame (many do not - not just T10 based projects). That said, T10 provides the means to inject your own root element by overriding a method within `app.xaml.cs`... I'm not able to test this right now, but I think it is something like:

```csharp
        public override UIElement CreateRootElement(IActivatedEventArgs e)
        {
            var navigationService = NavigationServiceFactory(BackButton.Attach, ExistingContent.Include, new Frame());
            return navigationService.Frame;
        }
```

**Comment by mjmeans** [comment]
Wouldn't that disable the Busy page?

**Comment by opi-smccoole** [comment]
Is there a way to do this that doesn't disable the Hamburger menu/Shell?  If we do what @darenm suggested the Shell doesn't get created and set any longer?  I've tried to create a Frame and set its content as the Shell or ModalDialog but then the launch freezes forever.  I'm basically in the same state as the original poster.  I have a 3rd party component that needs the Window.Current.Content to be a Frame.
