### ISSUE TITLE
BootStrapper.Current.NavigationService.OpenAsync fails - not always

### ISSUE THREAD

**Issue by BuhTig4ever** [Windows-XAML/Template10#1589]
When we start the UWP Template10 App from an desktop app that send right after a command to build up a second view, that works.
When we start the App and then trigger from an desktop app to build up a second view, we get always exceptions (at least so far on one machine, but it works on others). Before this Exception Template10 does not log any error. Unfortunately also the location where the exceptions are thrown and re-thrown are 'obfuscated' and ... and log messages contain texts not found in current source code and .....
What could go wrong here and how to make it right?

Thank you
Ferdinand

I PUI 28BC 18:11:10.073  ShellViewModel UpdateNetworkData SuppressEmulatorWindow= False
V PUI 28BC 18:11:10.073  HasThreadAccess=True
V PUI 28BC 18:11:10.073  T10 Template10 NavigationService.OpenAsync Page: Uwp.Main.Views.NetworkEmulatorPage, Parameter: , Title: Vmb Emulator, Size: UseHalf
V PUI 28BC 18:11:10.073  T10 Info OpenAsync Page: Uwp.Main.Views.NetworkEmulatorPage, Parameter: , Title: Vmb Emulator, Size: UseHalf
V PUI 25B8 18:11:10.091  T10 Template10 BootStrapper.OnWindowCreated 
V PUI 25B8 18:11:10.091  T10 Template10 DispatcherWrapper.Constructor 
V PUI 25B8 18:11:10.091  T10 Info StartViewInUse Start:1
V PUI 28BC 18:11:10.095  T10 Template10 DispatcherWrapper.Constructor 
V PUI 25B8 18:11:10.096  T10 Template10 BootStrapper.NavigationServiceFactory backButton:Ignore ExistingContent:Exclude
V PUI 25B8 18:11:10.096  T10 Template10 BootStrapper.NavigationServiceFactory backButton:Ignore existingContent:Exclude frame:Windows.UI.Xaml.Controls.Frame
V PUI 25B8 18:11:10.096  T10 Template10 BootStrapper.CreateNavigationService Frame:Windows.UI.Xaml.Controls.Frame
V PUI 25B8 18:11:10.097  T10 Template10 NavigationService.Navigate Page: Uwp.Main.Views.NetworkEmulatorPage, Parameter: , NavigationTransitionInfo: 
V PUI 25B8 18:11:10.097  T10 Template10 NavigationService.NavigateAsync Page: Uwp.Main.Views.NetworkEmulatorPage, Parameter: , NavigationTransitionInfo: 
V PUI 25B8 18:11:10.097  T10 Template10 JsonSerializationService.Serialize Value 
V PUI 25B8 18:11:10.097  T10 Template10 FrameFacade.Navigate 
V PUI 25B8 18:11:10.097  T10 Info StartViewInUse Start:2
V PUI 25B8 18:11:10.097  T10 Info OperationStarted SecondaryViewSynchronizationContextDecorator : OperationStarted: 2
V PUI 25B8 18:11:10.097  T10 Template10 FrameFacade.FacadeNavigatingCancelEventHandler 
V PUI 25B8 18:11:10.097  T10 Template10 JsonSerializationService.Deserialize Value 
V PUI 25B8 18:11:10.097  T10 Info StartViewInUse Start:3
V PUI 25B8 18:11:10.097  T10 Info OperationStarted SecondaryViewSynchronizationContextDecorator : OperationStarted: 3
V PUI 25B8 18:11:10.097  T10 Info StopViewInUse Stop:2
V PUI 25B8 18:11:10.097  T10 Info OperationCompleted SecondaryViewSynchronizationContextDecorator : OperationCompleted: 2
V PUI 25B8 18:11:10.097  T10 Info StopViewInUse Stop:1
V PUI 25B8 18:11:10.097  T10 Info OperationCompleted SecondaryViewSynchronizationContextDecorator : OperationCompleted: 1
V PUI 25B8 18:11:10.097  XXX NetworkEmulatorPage before InitializeComponent
V PUI 25B8 18:11:10.099  UwpAppServiceClient.RegisterMessageReceiver: register UwpUpdateNetworkData.
V PUI 25B8 18:11:10.114  XXX NetworkEmulatorPage after InitializeComponent
V PUI 25B8 18:11:10.114  T10 Template10 FrameFacade.FacadeNavigatedEventHandler 
V PUI 25B8 18:11:10.114  T10 Template10 JsonSerializationService.Deserialize Value 
V PUI 25B8 18:11:10.114  T10 Info StartViewInUse Start:2
V PUI 25B8 18:11:10.114  T10 Info OperationStarted SecondaryViewSynchronizationContextDecorator : OperationStarted: 2
V PUI 25B8 18:11:10.114  T10 Template10 JsonSerializationService.Deserialize Value 
V PUI 25B8 18:11:10.114  T10 Template10 JsonSerializationService.Serialize Value 
V PUI 25B8 18:11:10.115  T10 Info StartViewInUse Start:3
V PUI 25B8 18:11:10.115  T10 Info OperationStarted SecondaryViewSynchronizationContextDecorator : OperationStarted: 3
V PUI 25B8 18:11:10.115  T10 Template10 NavigationService.NavigateToAsync Mode: New, Parameter:  FrameContent: Uwp.Main.Views.NetworkEmulatorPage
V PUI 25B8 18:11:10.116  T10 Info StartViewInUse Start:4
V PUI 25B8 18:11:10.116  T10 Info OperationStarted SecondaryViewSynchronizationContextDecorator : OperationStarted: 4
V PUI 25B8 18:11:10.116  T10 Info StartViewInUse Start:5
V PUI 25B8 18:11:10.116  T10 Info OperationStarted SecondaryViewSynchronizationContextDecorator : OperationStarted: 5
V PUI 25B8 18:11:10.116  AccSpeMod -> GetProductInfoAsync() -> productInfo=[Name=Vodafone Mobile Broadband;LogoPath=D:\src\trunk\Production\PmbOutput\x64Release\AppX\Configuration\Belgium_20601\ProductLogo.png]
V PUI 25B8 18:11:10.116  T10 Info StopViewInUse Stop:4
V PUI 25B8 18:11:10.116  T10 Info OperationCompleted SecondaryViewSynchronizationContextDecorator : OperationCompleted: 4
V PUI 25B8 18:11:10.116  T10 Info StopViewInUse Stop:3
V PUI 25B8 18:11:10.116  T10 Info OperationCompleted SecondaryViewSynchronizationContextDecorator : OperationCompleted: 3
V PUI 25B8 18:11:10.118  T10 Info StopViewInUse Stop:2
V PUI 25B8 18:11:10.118  T10 Info OperationCompleted SecondaryViewSynchronizationContextDecorator : OperationCompleted: 2
V PUI  B18 18:11:10.118  T10 Info StopViewInUse Stop:1
V PUI  B18 18:11:10.118  T10 Info OperationCompleted SecondaryViewSynchronizationContextDecorator : OperationCompleted: 1
E PUI 28BC 18:11:10.125  D:\src\trunk\Source\Uwp\Gui\UwpMain\ViewModels\ShellViewModel.cs.304.NetworkDataProvider_UpdateNetworkData
	System.Exception: Excep_FromHResult 0x87B20C16
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at SharedLibrary!<BaseAddress>+0x4d5ce0
	at SharedLibrary!<BaseAddress>+0x4d5c68
	at SharedLibrary!<BaseAddress>+0x4d5c27
	at SharedLibrary!<BaseAddress>+0x50931f
	at PmbMain!<BaseAddress>+0x9a1900
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at SharedLibrary!<BaseAddress>+0x4d5ce0
	at SharedLibrary!<BaseAddress>+0x4d5c68
	at SharedLibrary!<BaseAddress>+0x4d5c27
	at PmbMain!<BaseAddress>+0xa1532a
	--- End of stack trace from previous location where exception was thrown ---
	at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	at SharedLibrary!<BaseAddress>+0x4d5ce0
	at SharedLibrary!<BaseAddress>+0x4d5c68
	at SharedLibrary!<BaseAddress>+0x4d5c27
	at PmbMain!<BaseAddress>+0x9c53ca

When it works:
I PUI 2710 18:13:08.226  ShellViewModel UpdateNetworkData SuppressEmulatorWindow= False
V PUI 2710 18:13:08.226  HasThreadAccess=True
V PUI 2710 18:13:08.226  T10 Template10 NavigationService.OpenAsync Page: Uwp.Main.Views.NetworkEmulatorPage, Parameter: , Title: Vmb Emulator, Size: UseHalf
V PUI 2710 18:13:08.226  T10 Info OpenAsync Page: Uwp.Main.Views.NetworkEmulatorPage, Parameter: , Title: Vmb Emulator, Size: UseHalf
V PUI 339C 18:13:08.245  T10 Template10 BootStrapper.OnWindowCreated 
V PUI 339C 18:13:08.245  T10 Template10 DispatcherWrapper.Constructor 
V PUI 339C 18:13:08.246  T10 Info StartViewInUse Start:1
V PUI 2710 18:13:08.250  T10 Template10 DispatcherWrapper.Constructor 
V PUI 339C 18:13:08.250  T10 Template10 BootStrapper.NavigationServiceFactory backButton:Ignore ExistingContent:Exclude
V PUI 339C 18:13:08.250  T10 Template10 BootStrapper.NavigationServiceFactory backButton:Ignore existingContent:Exclude frame:Windows.UI.Xaml.Controls.Frame
V PUI 339C 18:13:08.250  T10 Template10 BootStrapper.CreateNavigationService Frame:Windows.UI.Xaml.Controls.Frame
V PUI 339C 18:13:08.251  T10 Template10 NavigationService.Navigate Page: Uwp.Main.Views.NetworkEmulatorPage, Parameter: , NavigationTransitionInfo: 
V PUI 339C 18:13:08.251  T10 Template10 NavigationService.NavigateAsync Page: Uwp.Main.Views.NetworkEmulatorPage, Parameter: , NavigationTransitionInfo: 
V PUI 339C 18:13:08.251  T10 Template10 JsonSerializationService.Serialize Value 
V PUI 339C 18:13:08.251  T10 Template10 FrameFacade.Navigate 
V PUI 339C 18:13:08.251  T10 Info StartViewInUse Start:2
V PUI 339C 18:13:08.251  T10 Info OperationStarted SecondaryViewSynchronizationContextDecorator : OperationStarted: 2
V PUI 339C 18:13:08.251  T10 Template10 FrameFacade.FacadeNavigatingCancelEventHandler 
V PUI 339C 18:13:08.251  T10 Template10 JsonSerializationService.Deserialize Value 
V PUI 339C 18:13:08.251  T10 Info StartViewInUse Start:3
V PUI 339C 18:13:08.251  T10 Info OperationStarted SecondaryViewSynchronizationContextDecorator : OperationStarted: 3
V PUI 339C 18:13:08.251  T10 Info StopViewInUse Stop:2
V PUI 339C 18:13:08.251  T10 Info OperationCompleted SecondaryViewSynchronizationContextDecorator : OperationCompleted: 2
V PUI 339C 18:13:08.251  T10 Info StopViewInUse Stop:1
V PUI 339C 18:13:08.251  T10 Info OperationCompleted SecondaryViewSynchronizationContextDecorator : OperationCompleted: 1
V PUI 339C 18:13:08.251  XXX NetworkEmulatorPage before InitializeComponent
V PUI 339C 18:13:08.252  UwpAppServiceClient.RegisterMessageReceiver: register UwpUpdateNetworkData.
V PUI 339C 18:13:08.261  XXX NetworkEmulatorPage after InitializeComponent
V PUI 339C 18:13:08.261  T10 Template10 FrameFacade.FacadeNavigatedEventHandler 
V PUI 339C 18:13:08.261  T10 Template10 JsonSerializationService.Deserialize Value 
V PUI 339C 18:13:08.261  T10 Info StartViewInUse Start:2
V PUI 339C 18:13:08.261  T10 Info OperationStarted SecondaryViewSynchronizationContextDecorator : OperationStarted: 2
V PUI 339C 18:13:08.261  T10 Template10 JsonSerializationService.Deserialize Value 
V PUI 339C 18:13:08.261  T10 Template10 JsonSerializationService.Serialize Value 
V PUI 339C 18:13:08.262  T10 Info StartViewInUse Start:3
V PUI 339C 18:13:08.262  T10 Info OperationStarted SecondaryViewSynchronizationContextDecorator : OperationStarted: 3
V PUI 339C 18:13:08.262  T10 Template10 NavigationService.NavigateToAsync Mode: New, Parameter:  FrameContent: Uwp.Main.Views.NetworkEmulatorPage
V PUI 2710 18:13:08.262  T10 Template10 NavigationService.NavigateToAsync Mode: New, Parameter:  FrameContent: Uwp.Main.Views.MainPage
V PUI 339C 18:13:08.262  T10 Info StartViewInUse Start:4
V PUI 339C 18:13:08.262  T10 Info OperationStarted SecondaryViewSynchronizationContextDecorator : OperationStarted: 4
V PUI 339C 18:13:08.262  T10 Info StartViewInUse Start:5
V PUI 339C 18:13:08.262  T10 Info OperationStarted SecondaryViewSynchronizationContextDecorator : OperationStarted: 5
V PUI 339C 18:13:08.262  AccSpeMod -> GetProductInfoAsync() -> productInfo=[Name=Vodafone Mobile Broadband;LogoPath=D:\src\trunk\Production\PmbOutput\x64Release\AppX\Configuration\Belgium_20601\ProductLogo.png]
V PUI 339C 18:13:08.262  T10 Info StopViewInUse Stop:4
V PUI 339C 18:13:08.262  T10 Info OperationCompleted SecondaryViewSynchronizationContextDecorator : OperationCompleted: 4
V PUI 339C 18:13:08.262  T10 Info StopViewInUse Stop:3
V PUI 339C 18:13:08.262  T10 Info OperationCompleted SecondaryViewSynchronizationContextDecorator : OperationCompleted: 3
I PUI 2710 18:13:08.262  MPVM: Navigated to Home Page
V PUI 2710 18:13:08.263  SendRequest: Tag=UwpUpdateNetworkData, To=AppServiceServer, Data=
V PUI 2710 18:13:08.263  SmsManager: GetUnreadMessageCount
V PUI 2710 18:13:08.263  AccSpeMod -> GetSimpleShortcutsInfoAsync() -> simpleShortcutInfo[0]=[Usable=False;Text=Online-Konto;ImageName=OnlineAccountSymbol;Url=https://admit.belgacom.be/;FilePath=;Index=0]
I PUI 2710 18:13:08.263  MSM: UpdateSimpleShortcuts Online-Konto added
V PUI 2710 18:13:08.263  AccSpeMod -> GetSmsDataBundleShortcutInfoAsync() -> smsDataBundleShortcutInfo=
V PUI 2710 18:13:08.263  AccSpeMod -> GetUssdDataBundleShortcutInfoAsync() -> ussdDataBundleShortcutInfo=
V PUI 2710 18:13:08.263  BalCheMod -> GetShortcutInfoAsync() -> balanceCheckShortcutInfo=[Exists=False;Usable=False;Text=Guthaben Ã¼berprÃ¼fen;ImageName=CheckBalanceSymbol]
V PUI 2710 18:13:08.263  VouTopMod -> GetShortcutInfoAsync() -> voucherTopupShortcutInfo=[Exists=False;Usable=False;Text=Aufladen;ImageName=VoucherChargingSymbol;Title=Gutschein-Code;CodeLabel=Code hier eingeben:;PasswordLabel=Kennwort:;CodeMinimumLength=16;CodeMaximumLength=16;PasswordExists=False;PasswordMinimumLength=16;PasswordMaximumLength=16]
V PUI 2710 18:13:08.263  MSM: FireUpdateCommandList
V PUI 2710 18:13:08.263  MSM: FireUpdateCommandList #shortcutButtons: 1
V PUI 2710 18:13:08.263  MSM: FireUpdateCommandList #sortedList count: 1
V PUI 2710 18:13:08.263  MPVM: MainPageViewModel_UpdateCommandList #Commands: 1; Usage True
V PUI 2710 18:13:08.263  SmsManager: GetUnreadMessageCount
V PUI 339C 18:13:08.265  T10 Info StopViewInUse Stop:2
V PUI 339C 18:13:08.265  T10 Info OperationCompleted SecondaryViewSynchronizationContextDecorator : OperationCompleted: 2
V PUI 35F8 18:13:08.265  T10 Info StopViewInUse Stop:1
V PUI 35F8 18:13:08.265  T10 Info OperationCompleted SecondaryViewSynchronizationContextDecorator : OperationCompleted: 1
V PUI 41D4 18:13:08.266  SendCompleted: result OK
I PBG  B70 18:13:08.267  BTEH: UpdateNetworkRequest UwpUpdateNetworkData
I PBG  B70 18:13:08.267  SendToAppAsync: send FAIL, EmulatorClient not registered
V PUI 2710 18:13:08.339  T10 Template10 HamburgerMenu.HamburgerMenu_Loaded 
V PUI 2710 18:13:08.339  T10 Template10 HamburgerMenu.RefreshStyles Theme: Default
V PUI 2710 18:13:08.339  T10 Template10 HamburgerMenu.RefreshStyles Color: #00000000
V PUI 2710 18:13:08.340  T10 Template10 HamburgerMenu.DisplayMode OldValue: Overlay NewValue: CompactOverlay
V PUI 2710 18:13:08.340  T10 Template10 HamburgerMenu.UpdateControl Manual: , IsFullScreen: False DisplayMode: CompactOverlay
V PUI 2710 18:13:08.341  T10 Template10 HamburgerMenu.UpdateControl Manual: , IsFullScreen: False DisplayMode: CompactOverlay
V PUI 2710 18:13:08.427  T10 Template10 HamburgerMenu.NavButton_Loaded 
V PUI 2710 18:13:08.427  T10 Template10 HamburgerMenu.NavButton_Loaded 
V PUI 2710 18:13:08.427  T10 Template10 HamburgerMenu.NavButton_Loaded 
V PUI 2710 18:13:08.428  T10 Template10 HamburgerMenu.NavButton_Loaded 
V PUI 2710 18:13:08.428  T10 Template10 HamburgerMenu.NavButton_Loaded 
V PUI 2710 18:13:08.429  T10 Template10 HamburgerMenu.NavButton_Loaded 
V PUI 2710 18:13:08.430  T10 Template10 HamburgerMenu.NavButton_Loaded 
V PUI 2710 18:13:08.430  T10 Template10 HamburgerMenu.NavButton_Loaded 
V PUI 2710 18:13:08.431  T10 Template10 HamburgerMenu.NavButton_Loaded 
V PUI 2710 18:13:08.431  T10 Template10 HamburgerMenu.HighlightCorrectButton PageType: Uwp.Main.Views.MainPage PageParam: 
V PUI 2710 18:13:08.431  T10 Template10 HamburgerMenu.Selected OldValue:  NewValue: IsChecked: False PageType: Uwp.Main.Views.MainPage, Parameter: 
V PUI 2710 18:13:08.431  T10 Template10 HamburgerMenu.UpdateSelectedAsync OldValue: , NewValue: IsChecked: False PageType: Uwp.Main.Views.MainPage, Parameter:

**Comment by BuhTig4ever** [comment]
Have had also another none-functioning. The debug-Build of the App closed right after starting before it has reached any of our code. Found in internet a handling for this:
Change account type to standard. try to run the app. change account type back to administrator. And due to some mysterious changes in Windows that handled it. So, now after about a week non-functional debug mode that works again and also starting the second view by an trigger from an desktop app works.

**Comment by JerryNixon** [comment]
Has anyone else encountered this? @Windows-XAML/template-10-developer-community

**Comment by BuhTig4ever** [comment]
Hi Jerry,
The later issue and maybe also the first came from Fall Creators Update. I went back to Creators Update and all worked fine again. After the next update to Fall Creators Update, this issues where back. In meantime, after last Windows 10 update, I have not seen it.
