### ISSUE TITLE
The IsEnabled property of HamburgerButtonInfos is reset on Navigation

### ISSUE THREAD

**Issue by MichaelPetrinolis** [Windows-XAML/Template10#159]
When you set the IsEnabled property of a HamburgerButtonInfo to false, when a Navigation is occurred the property value us reset to true. Created this quick fix [PR](https://github.com/Windows-XAML/Template10/pull/158)

**Comment by JerryNixon** [comment]
I can't accept your PR because there are so many changes to that file otherwise. But i will include your fix in the current code.

**Comment by JerryNixon** [comment]
This was by design, but looking at the News app, they do not disable theirs.
