### ISSUE TITLE
FlyoutBase within HamburgerMenu?

### ISSUE THREAD

**Issue by mjmeans** [Windows-XAML/Template10#1590]
So I want one of the hamburger menu items to display a list of subordinate commands similar to Windows 10's Start Menu > Power control. So I add this to Shell:
```
            <!--  power button  -->
            <Controls:HamburgerButtonInfo ButtonType="Command">
                <Interactivity:Interaction.Behaviors>
                    <Core:EventTriggerBehavior EventName="Tapped">
                        <behaviors:OpenFlyoutAction/>
                    </Core:EventTriggerBehavior>
                </Interactivity:Interaction.Behaviors>
                <StackPanel Orientation="Horizontal">
                    <ToolTipService.ToolTip>
                        <TextBlock MaxWidth="225"
                                    Text="Power"
                                    TextWrapping="Wrap" />
                    </ToolTipService.ToolTip>
                    <FontIcon Width="48" Height="48" FontFamily="Segoe MDL2 Assets" Glyph="&#xE7E8;"/>
                    <TextBlock Margin="12,0,0,0"
                                VerticalAlignment="Center"
                                Text="Power" />
                </StackPanel>
            </Controls:HamburgerButtonInfo>
```
So next I need a FlyoutBase so I try to ad it to HamburgerButtonInfo, but the property AttachedFlyout doesn't exist got HamburgerButtonInfo. So I add it to HamburgerMenu instead.
```
        <FlyoutBase.AttachedFlyout>
            <Flyout>
                <StackPanel>
                    <Button x:Name="Shutdown" Content="Shut down" Style="{StaticResource TextBlockStyle}" Click="Shutdown_Click"/>
                    <Button x:Name="Restart"  Content="Restart"   Style="{StaticResource TextBlockStyle}" Click="Restart_Click"/>
                </StackPanel>
            </Flyout>    
        </FlyoutBase.AttachedFlyout>
```
I get: Exception = {System.InvalidCastException: Unable to cast object of type 'Template10.Controls.HamburgerButtonInfo' to type 'Windows.UI.Xaml.FrameworkElement'.
   at Template10.Behaviors.OpenFlyoutAction.Execute(Object sender, Object parameter)
   at Microsoft.Xaml.Int...

**Comment by mvermef** [comment]
ButtonType="Literal", might be a solution to model the contents of the button the way you want.

**Comment by mjmeans** [comment]
The solves the exception, but the flyout doesn't appear.

**Comment by mvermef** [comment]
right so you're going to have to figure out the best solution to that flyout issue, I just knew that the ButtonType was part of the solution to the exception.

**Comment by mjmeans** [comment]
So almost doable. I put the flyout interaction inside the StackPanel inside HamburgerButtonInfo. The only problem is that clicking on the power icon causes the Hamburger menu to expand out. Is there a way to disable that for that HamburgerButtonInfo item only?
