### ISSUE TITLE
Not Keeping Permissions when using Template 10

### ISSUE THREAD

**Issue by zakkar1** [Windows-XAML/Template10#1592]
Hi ,
I have created a new app with my VS2017 using the Template 10.
In my app I want to use the camera and the microphone so I did the appropriate changes in the package manifest.
I run my app from inside VS to debug and see how things going.
If I try to use the mediacapture , initializeasync method I get prompted to give the permission access.(Let <app name> access your camera ? etc)
After accepting them with "YES" and close the app the next time I run it from inside the VS2017 I get prompted again !!!!!
Haven't tested if this is happening in the release mode but if this is happening then this is a huge problem.
I have uploaded a sample were this is happening
https://1drv.ms/u/s!Ago_ojiHjYhx5gMD11Ag3JEad85P

Just run it and press yes in the permission questions.
Close then the app and ran it again.
You will get prompted again. 
Somehow it ignores what you have selected.
Can anyone faced this problem ?

Appreciate your help on this

**Comment by zakkar1** [comment]
The files are attached also
[Hamburger1.zip](https://github.com/Windows-XAML/Template10/files/1501745/Hamburger1.zip)

**Comment by dg2k** [comment]
This has nothing to do with Template 10. It has to do with Windows 10 Apps. Asking the user for permission is part of the security built into UWP and I don't think users regard this as an inconvenience.

I haven't done camera and microphone programming, but I know access to some resources have the option of saving permission tokens by apps, so as to avoid asking for permission again and again (e.g accessing non local folders) or permission for time-limited sessions (e.g., OneDrive). So explore if there are ways to persist permission tokens so as to access that resource silently.

**Comment by darshanrampatel** [comment]
@zakkar1, like @dg2k says, this is a UWP issue. I have used the permissions for UWP successfully (in `Package.appxmanifest`):
```
    <DeviceCapability Name="microphone" />
    <DeviceCapability Name="webcam" />
```
You may find that, depending on your Visual Studio settings, your app is re-installed every time in debug mode, so would reset any permissions granted.

**Comment by zakkar1** [comment]
Hi Everyone ,
This problem appeared after the update and only in VS2017 UWP apps while doing debugging. 

It has nothing to do how to activate the permissions etc. I know how to do those things. I'm not asking about that.
If you want to reproduce the problem just create a Template 10 app with Hamburger menu and call the initializeasync method of the Media element. You will understand what I'm talking about when you debug it from your VS2017 ver 15.4.4.
All there were working fine with my VS2015 but something's broken in  the VS2017 and don't know if it is the Template's 10 fault or it comes from the UWP team.
If you create a **blank App without using the Template 10** the code works ( the initializeasync method) . It asks you the first time and then it stores the permissions.  The problem doesn't appear.
Of course if you deploy the app and call it from your start menu of your OS it doesn't ask you again but it is annoying when it is happening while debugging.
Does anyone else face the same issue or can have an idea how to resolve this ?

**Comment by JerryNixon** [comment]
Thanks for following-up with us
