### ISSUE TITLE
RaisePropertyChanged in different threads crashed

### ISSUE THREAD

**Issue by Florian-Haar** [Windows-XAML/Template10#1595]
I created an App with multiple Windows. If I open a new Window in a new thread and the RaisePropertyChanged event is called than I get this error message:
"**Unable to cast COM object of type 'System.ComponentModel.PropertyChangedEventHandler' to class type 'System.ComponentModel.PropertyChangedEventHandler'. Instances of types that represent COM components cannot be cast to types that do not represent COM components; however they can be cast to interfaces as long as the underlying COM component supports QueryInterface calls for the IID of the interface.**"
The exception stack Looks like this:

System.StubHelpers.StubHelpers.GetCOMIPFromRCW_WinRTDelegate(Object objSrc, IntPtr pCPCMD, IntPtr& ppTarget)
System.ComponentModel.PropertyChangedEventHandler.Invoke(Object sender, PropertyChangedEventArgs e)
Template10.Mvvm.BindableBase.<>c__DisplayClass4_1.<RaisePropertyChanged>b__0()
Template10.Common.DispatcherWrapper.<Dispatch>d__8.MoveNext()
System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
System.Threading.WinRTSynchronizationContext.Invoker.InvokeCore()
Windows.ApplicationModel.Core.UnhandledError.Propagate()
Microsoft.HockeyApp.Extensibility.Windows.UnhandledExceptionTelemetryModule.CoreApplication_UnhandledErrorDetected(Object sender, UnhandledErrorDetectedEventArgs e)

So it Looks like there is a Problem in the RaisePropertyChanged Event. 
Do you have an idea where the Problem is? Or is this an known issue?

**Comment by JerryNixon** [comment]
Are you using a single view-model across views? That will always cause this exception and there's really nothing you can do to change that, @Florian-Haar. It's not Template 10, here, it's just threading in XAML.
