### ISSUE TITLE
How to change only the HamburgerButton forground color in Custom.xaml

### ISSUE THREAD

**Issue by mjmeans** [Windows-XAML/Template10#1596]
I tried adding setter for HamburgerForeground or NavButtonForeground in Custom.xaml but that doesn't seem to have any effect. I want to change the foreground color of only the Hamburger button glyph to Green. How can this be done?

**Comment by JerryNixon** [comment]
Since you are adding the content yourself, you have the option of just setting your TextBox Foreground and you get what you want. That's not only the most straight forward, it's easiest to do.
