### ISSUE TITLE
Holy crap, Template 10.2 runs

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#1598]
I will be checking it in tomorrow. Some real, valuable changes. 

![image](https://user-images.githubusercontent.com/1749983/33745184-8b3c08c6-db72-11e7-87ae-d92b85669a05.png)

**Comment by mvermef** [comment]
🤗

**Comment by callummoffat** [comment]
Glorious.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by callummoffat** [comment]
How's this coming?

**Comment by JerryNixon** [comment]
Sync complete. Needs some work. View-model isn't wiring up. But close, I think. Resizer isn't rendering. Suspension isn't seeming to fire. Lots of issues. All probably tiny.

**Comment by mvermef** [comment]
Talk about refactor of the refactor, I like how condensed the assembly count has reached

**Comment by JerryNixon** [comment]
I think we needed to try the breakout of everything to see if it made sense. It didn't.

**Comment by rrogahn** [comment]
Looking forward to seeing the final bits for 10.2.  Any idea of a timeline?
