### ISSUE TITLE
Newtonsoft.Json v11.0.1 throws exception Method not found

### ISSUE THREAD

**Issue by Joebeazelman** [Windows-XAML/Template10#1599]
I thought you would like to know that v11.0.1 of Newtonsoft.JSON throws the following exception:
This is a fresh project. The error disappeared when I downgraded the version.

Method not found: 'Void Newtonsoft.Json.JsonSerializerSettings.set_TypeNameAssemblyFormat(System.Runtime.Serialization.Formatters.FormatterAssemblyStyle)'.

**Comment by mvermef** [comment]
Which makes sense since not all upgrades to libraries are without breaking changes.  The current version in nuget is not up to date with some of the external libraries

**Comment by JerryNixon** [comment]
You will need to downgrade until we release 13

**Comment by wdupree** [comment]
Is there any update on this issue? I updated a project to the latest (11.0.2) and have this issue as well.
