### ISSUE TITLE
WeakEvent Implementation error

### ISSUE THREAD

**Issue by Herdo** [Windows-XAML/Template10#16]
I'm currently reviewing the _WeakEvent_ class for my own purposes.
I came across an odd line in the [static Unsubscribe<THandler> method](https://github.com/Windows-XAML/Template10/blob/master/Experimental/Mvvm/WeakEvent.cs#L282-L285) on line 282-285:

```
static public void Unsubscribe<THandler> ...

if (reg == null)
{
    reg.Subscribe(handler as Delegate);
}
```

Two thoughts:
1. Is this really supposed to throw a _NullReferenceException_?
2. Is the _Unsubscribe<THandler>_ method really supposed to  call _Subscribe_?

**Comment by darenm** [comment]
Thanks for reporting - this source file is included in the experimental directory and isn't actually included in the Template10 solution. As the directory name suggests, the code in this directory is very much a work in progress and not yet ready for public consumption - I'm sure many such gremlins are likely to exist!

**Comment by JerryNixon** [comment]
This is important for the adaptive triggers we are adding to the library. Thanks for reporting this. We'll take your fix.

Best regards,
Jerry Nixon

Sent from my Windows Phone.
Please forgive typos and brevity.

**Comment by Herdo** [comment]
@darenm I understand that it's just experimental. I just wanted to point it out :)
@JerryNixon I hope my library (https://github.com/Herdo/AdaptiveTriggerLibrary) won't go to waste then ;)

**Comment by tibitoth** [comment]
@dotmorten has a good adaptive trigger library too: https://github.com/dotMorten/WindowsStateTriggers

**Comment by Herdo** [comment]
@totht91 Guess several developers had the same idea.

**Comment by JerryNixon** [comment]
Yeah. We need to reach out to each of them and see if we can consolidate. Ideally, into Template 10.

Best regards,
Jerry Nixon

Sent from my Windows Phone.
Please forgive typos and brevity.
