### ISSUE TITLE
Too few words in ListenFor element in Cortana XML

### ISSUE THREAD

**Issue by seesharprun** [Windows-XAML/Template10#160]
Before submitting a PR, I wanted to see if anyone else can reproduce this issue.  Essentially, on an unchanged copy of the Samples/Cortana project, the application fails to launch because of an error in the ListenFor element of the Cortana.xml file.

> WinRT information: The 'ListenFor' phrase does not contain sufficient phonetic content for the specified 'RequireAppName' value. Optional text in '[]' and PhraseLists in '{}' do not contribute to the phonetic content count. Try adding more words/characters to the ListenFor. 

```
<ListenFor RequireAppName="BeforeOrAfterPhrase"> [please] handle {textPhrase} [with] </ListenFor>
```

Essentially, you only have one word in the statement that's not optional or a phrase.  The error message shows that it's an issue.  It's resolved by simply adding another word to the ListenFor element:

```
<ListenFor RequireAppName="BeforeOrAfterPhrase"> [please] handle {textPhrase} [with] </ListenFor>
```

Now, my sentence "Hey Cortana, please add statement hello world" works.

Documentation about this can be found here: https://msdn.microsoft.com/en-us/library/windows/apps/xaml/dn997786.aspx
Go to Step 3 and the third bullet point.  

> There must be at least two words in the ListenFor string besides your app name and references to PhraseTopic elements. [...], you need to ensure your commands contain sufficient phonetic content to minimize the chances your app is launched unintentionally. 

Anyone else see this issue before I submit a PR?

**Comment by JerryNixon** [comment]
The {textPhrase} should count as a word. That works for me, but I would be willing to change it if you can confirm that "Handle Everything with Template 10" does not work for you. That being said, if you submit a pull request, you need to include in that pull request this file:

> https://github.com/Windows-XAML/Template10/blob/master/Samples/Cortana/readme.md

No kidding. That would be a big help.

**Comment by seesharprun** [comment]
I have a sample read me file in my fork based on my proposed phrase change.  I just submitted a PR for it.
