### ISSUE TITLE
MasterDetail and perhaps other Samples don't build

### ISSUE THREAD

**Issue by Joebeazelman** [Windows-XAML/Template10#1600]
I cloned the repo from GitHub version "1.1.13-preview-20161207" and Template10.Core couldn't be found.  I tried to reference the assembly directly from the main solution build artifacts, but it wasn't sufficient.  I finally resolved the errors and was able to launch the application by adding Template10 package from Nuget because your build system is utterly useless!

I must state emphatically, the performance of the sample App is appalling!  Clicking on the "Master/Details 2" took several seconds!   The Forward and Backwards button on that page took just as long and made the app unresponsive. My PC is no UNIVAC. It always performs in the top 1% of desktops according several benchmarks. What's going on here?  Are you nostalgic for 8-bit performance?  

This rabbit hole doesn't bode well as a solution.  Perhaps, this project is being curated for historical purposes? Not a lot of activity in comparison to Visual Template Studio, which unfortunately doesn't provide enough guidance.  Moreover, there's quite a bit of code duplication in the Template10's code base which worries me.  Master Detail is already a standard control, but it has its own implementation.  Perhaps, I should just build a traditional WPF application and forget supporting UWP.

I must state that Microsoft appears to be a leaning tower of babel ready to collapse on its victims. There are too many projects going on and they all appear to duplicate each others effort.  I've spent way too much time just  trying to find what API's and frameworks I should use.  Apple development facilities are nowhere as advanced, but they at least provide a consistent, concise, clear and organize development path.  I blame this on the stupid whiteboard interviews that weeds out truly talented and creative people in favor of obedient androids lacking the most basic of common sense.

**Comment by JerryNixon** [comment]
Thanks for your feedback
