### ISSUE TITLE
Discussion: using HamburgerMenu from UWP Community Toolkit 

### ISSUE THREAD

**Issue by jp-weber** [Windows-XAML/Template10#1601]
I saw that UWPCommunityToolkit have a great HamburgerMenu control with NavigationView. Why we don't build NavViewEx on this implementation?

https://github.com/Microsoft/UWPCommunityToolkit/tree/master/Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu

**Comment by tibitoth** [comment]
That's not correct because the UWPCommunityToolkit's HamburgerMenu is obsolate: [see](https://github.com/Microsoft/UWPCommunityToolkit/blob/master/Microsoft.Toolkit.Uwp.UI.Controls/HamburgerMenu/HamburgerMenu.cs#L30). 

They suggest to use NavigationView instead.
