### ISSUE TITLE
Real-world examples of T10 in Windows Store

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#1602]
Real-world examples/applications of T10 in Windows Store:

- [dataWallet app](https://www.microsoft.com/store/apps/9p32hsfjr401)

- [dataWallet Pro app](https://www.microsoft.com/store/apps/9n17k0l0jg2d)

**Comment by michaelhutchful** [comment]
I am not sure if you are asking for some apps, but here is mine

- [Slydepay](https://www.microsoft.com/en-gh/store/p/slydepay/9nblggh4rvpq)

**Comment by JerryNixon** [comment]
Thanks guys. There are so many more. I have Store telemetry to look at, so I have the advantage, but I can't share. Template 10 is the second-most popular library in all of the store.

**Comment by dg2k** [comment]
@JerryNixon - What's the no 1 library? Just curious.

**Comment by michaelhutchful** [comment]
Me too 

Sent from my Windows 10 phone
