### ISSUE TITLE
Template 10 Validation : Validation with Behaviours doesn't refresh style on subsequent page loads

### ISSUE THREAD

**Issue by ishrat9** [Windows-XAML/Template10#1610]
Everything works great for first time page load. When I load the page for second...the error style is not reflecting on UI. Though IsValid says its false. Now when I load same page third time it loads validation style of Second load. I know Iam missing something here. Appreciate if you point me in right direction. btw, I am using ViewModel Locators

```
 <TextBox
     x:Name="MinDuration"
     Style="{StaticResource TextBox}"
     Text="{x:Bind ViewModel.Pressure.MinDuration, Mode=TwoWay}">
               <Interactivity:Interaction.Behaviors>
                     <ValidationBehaviors:ValidationBehavior PropertyName="MinDuration">
                          <ValidationBehaviors:ValidationBehavior.WhenValidActions>
                               <Core:ChangePropertyAction PropertyName="Style" Value="{StaticResource TextBox}" />
                                        </ValidationBehaviors:ValidationBehavior.WhenValidActions>
                                        <ValidationBehaviors:ValidationBehavior.WhenInvalidActions>
                                            <Core:ChangePropertyAction PropertyName="Style" Value="{StaticResource ErrorTextBoxStyle}" />
                                        </ValidationBehaviors:ValidationBehavior.WhenInvalidActions>
                                    </ValidationBehaviors:ValidationBehavior>
                                </Interactivity:Interaction.Behaviors>
   </TextBox>

```

**Comment by JerryNixon** [comment]
Are you sure the object is correctly populated?

**Comment by ishrat9** [comment]
yes Jerry. I see values being changed on UI from one page load to another. Also IsValid does have correct value. its just not refreshing UI. Also I don't see this behavior with control wrapper. Control Wrapper just works fine.

**Comment by mvermef** [comment]
Sounds like INotifyPropertyChanged not getting fired on viewmodel property

**Comment by ishrat9** [comment]
Initially I thought so, whenever I change the value its hitting the break point and updating IsValid which is tied to my Save button.

**Comment by mvermef** [comment]
Can you show us the viewmodel and model if you can.?

**Comment by ishrat9** [comment]
Attached Sample below

**Comment by mvermef** [comment]
Ok where's the validator

**Comment by ishrat9** [comment]
oops Sorry updated now. I will create the sample tomorrow to reproduce. Please note I am using ViewModelLocator

**Comment by ishrat9** [comment]
Please find the attached [Sample.zip](https://github.com/Windows-XAML/Template10/files/1658041/Sample.zip). 

1. Run the application and click on submit. you will see the style changes on the textbox. 
2. Now enter some value and go back previous page by clicking back button.
3. Click the submit again. Now you don't see the error style changes.

Thanks,

**Comment by mvermef** [comment]
![image](https://user-images.githubusercontent.com/2018777/35308872-56a03f66-006f-11e8-95f8-5f02344eb069.png)

Something doesn't like the idea of setting the TextBox name to the ValidationBehavior's PropertyName

**Comment by ishrat9** [comment]
Just tried by removing Name no luck. Try playing around few times back and forth. you will be able to reproduce this,

**Comment by mvermef** [comment]
Yeah I know it won't work, already discovered this.  I don't see the answer to using the behaviors.  I have only used the control wrapper, that and I have never seen a working example of behaviors only.

**Comment by ishrat9** [comment]
Thanks. Will switch back to control wrapper for now and continue to debug the issue with behaviors only

**Comment by JerryNixon** [comment]
I am grateful you have a solution. I have had trouble with the behaviors myself. I think it's more about the behaviors and less about what you are doing. That being said, it deserves some more research. I wish your sample project worked for me. I load it fine, but I don't see ANYTHING happening when I type.

**Comment by ishrat9** [comment]
Thanks Jerry for checking it out.  Just click on submit and enter some value on Max Duration Field. Back and forth couple of times. you will see behaviors stop working.
