### ISSUE TITLE
Cursed be the day when I decided to use Template10 as the framework to build my app

### ISSUE THREAD

**Issue by FrayxRulez** [Windows-XAML/Template10#1613]

**Comment by michaelhutchful** [comment]
Hi could you detail the issues you are having? I use template 10 for a payment app been running for a year now and I haven't really had any app breaking issues. I feel @JerryNixon and team have done a great job here.

**Comment by dg2k** [comment]
Wow! That is quite strong and an unjustified statement by your title @FrayxRulez. I use Template 10 without any issues. 

Forgive the ad plugin but to substantiate my point more objectively, check out my apps [dataWallet](https://www.microsoft.com/store/apps/9p32hsfjr401) and [dataWallet Pro](https://www.microsoft.com/store/apps/9n17k0l0jg2d) at Microsoft Apps Store. Free trial there if you want to. They are all based on Template 10 with no issues.

If you get null NavigationService perhaps you are not creating it in App initialization before getting to your xaml pages. Before we blame a tool, we should know *how to use* the tool.

Yes, @JerryNixon's and his team contribution is First Class.

**Comment by mvermef** [comment]
Pretty wrong to be that negative here,  considering you just posted 2 other questions without code or even some code snippets to see what you are attempting to do. 

I suggest you rethink that rude tude

**Comment by FrayxRulez** [comment]
Sorry, I don't have any problem with the people that's contributing to this project, and I don't want to be rude.
It's just quite frustrating that this library never received any kind of quality update since 10/17/2016.
I'm using this library in a quite [big project](https://github.com/UnigramDev/Unigram) and #1612 #1611 aren't the first issues I've encountered for sure.
It's surely useless to open an issue like this, but I really needed to relieve this bad feeling :)

**Comment by michaelhutchful** [comment]
Now you have relieved this bad feeling let’s get to helping you. Please give us some sample code and steps to recreate your issue

Sent from my Windows 10 phone

**Comment by dg2k** [comment]
@FrayxRulez  - Again the statement you're making is incorrect re quality update. Please be reminded that this is free software made possible by community contribution as @JerryNixon's brainchild. The onus is on the developer to assess suitability and build around T10, at the same time never overlooking the noble intent of those who are working hard to contribute and share this wonderful UWP framework.

**Comment by FrayxRulez** [comment]
>  Again the statement you're making is incorrect re quality update.

The NuGet package doesn't get updated since 10/17/2016

> Please be reminded that this is free software

It might even be free software, but as someone stated this is the most used UWP library in the Microsoft Store.

**Comment by dg2k** [comment]
You can get the source code and compile it yourself. Is is not that difficult.

I am not saying everything is perfect (you have imperfections even with paid-for software), but considering what devs are expected to build around T10, your unkind criticisms are unwarranted.

- where NuGet lags behind, add you own and if you care to share, contribute your code.
- where T10 is inadequate, again enhance it, and share your code.

That's how we can make T10 better.

**Comment by mvermef** [comment]
@FrayxRulez right cause there hasn't been a reason to update the stuff in the nuget package since it's version hasn't changed.  As for the current source if that is what you are using its basically alpha mode and subject to change at any time.  I can say the source has changed dramatically and most will say this since its been refactor of the refactor.  The direction that is being seen with the refactor is towards that of xplatform (think xamarin).  

But to come and make a blanket post of this nature will get you some unnecessary flack since the project is actually coming along quite nicely, @JerryNixon has done some amazing stuff in the short existence of this framework, which is probably the most inclusive UWP framework in the open source community, getting more and more features with each iteration.  Bug fixes do occur and he will update when it needs to fend off some show stopping bug.  

As @dg2k has stated if there is a problem, grab the source dig in your heels, find out the reason.

**Comment by FrayxRulez** [comment]
I of course have my own fork of the project.
Can someone point me out why [this line of code](https://github.com/Windows-XAML/Template10/blob/version_1.1.12_vs2017/Template10%20(Library)/Services/NavigationService/NavigationService.cs#L65) even exists?

**Comment by tibitoth** [comment]
I completely understand the fustration of @FrayxRulez. This library was featured on many places like channel9, MVA courses but on a sudden day (nearly when Windows Template Studio and UWPCommunityToolkit were announced) the Template10 hype broke down to zero from the Microsoft official channels. I suspect some dissonance between @JerryNixon and the other side of the UWP community. I don't know what is it but I feel it. After that it's gonna be a really hard mission to maintain this library alone. I know that a huge refactor is in progress but it feels like a left behind pet project, with no proper support. So sadly I cannot recommend to use this library for production applications.

**Comment by JerryNixon** [comment]
All good points. We're still peddling though, get ready for what's next. No dissonance.
