### ISSUE TITLE
Template10 is supposed to be optimized to work with multiple windows, but it isn't

### ISSUE THREAD

**Issue by FrayxRulez** [Windows-XAML/Template10#1615]
Template10 supposed to be optimized to be used with multiple windows (syncronization context, OpenAsync and so on) but it isn't:
- `SystemNavigationManager` back button is handled only for the `Window` where `BootStrapper` has been initialized for the first time (_GetFor**Current**View_), so any additional window created won't handle it
- `KeyboardService` is a singleton, but still connected to the `Window` where the instance has been created (_Window.**Current**_)

**Comment by JerryNixon** [comment]
Yes, @FrayxRulez, what you have discovered is real. My best suggestion to you is that you copy the code for the service and invoke it on the correct view for your own use. I think as you continue to create a multi-window UWP you will find more problems. The truth is, until RS4 (coming in Spring) you might find these are not adequately addressed. The good news is, they will be addressed.

**Comment by JerryNixon** [comment]
One more thing I want to share with you is that the next version of Template 10 is very different and does account for what is available in FCU, which is not a lot more. But it also makes changing these implementations a simpler prospect.
