### ISSUE TITLE
Template10 trying to download GitV2 when install the template from vsix

### ISSUE THREAD

**Issue by yunusefendi52** [Windows-XAML/Template10#1618]
When I install Template10 from vsix file, it's trying to download GitV2, I know I can just download that but what I expect is I can install it without to download anything.

Thanks 😄

**Comment by mvermef** [comment]
What do you mean gitv2? The template that is vsix is version 1.1.13p, based source.  If you don't want starter templates, it's on nuget

**Comment by yunusefendi52** [comment]
I couldn't take the screenshot immediately (because I was eat and far enough from the keyboard), so I re-installed the template again and it says "Download complete": 

![screenshot 62](https://user-images.githubusercontent.com/19399214/36110202-691a0114-1054-11e8-8fb7-6cacc68d33dc.png)

**Comment by JerryNixon** [comment]
Hey guys. I will try installing the current version through the gallery and see. 
Out of curiosity, does this even matter?

**Comment by yunusefendi52** [comment]
Nope 😄, I just fill an issue because it's the first I found that it's happening
