### ISSUE TITLE
How to use MDL2 font instead of SymbolIcon.Symbol property in Hamburger?

### ISSUE THREAD

**Issue by bubblepipe** [Windows-XAML/Template10#1619]
For example, the icon E9D9 Diagnostic, is not included in SymbolIcon.Symbol. 
![screenshot 288](https://user-images.githubusercontent.com/30717258/36304567-aefbac3c-1342-11e8-907d-d814107eb636.png)
![screenshot 286](https://user-images.githubusercontent.com/30717258/36304489-6e0a0b7e-1342-11e8-9ec1-336f3ff9df16.png)
![screenshot 287](https://user-images.githubusercontent.com/30717258/36304490-70664a90-1342-11e8-8a55-deeed017da96.png)

**Comment by michaelhutchful** [comment]
You will have to use <FontIcon Margin="15,0,0,0" HorizontalAlignment="Left" Glyph="&#xE9D9;" >


Sent from Mail for Windows 10

From: AOIDUO
Sent: 16 February 2018 10:57
To: Windows-XAML/Template10
Cc: Subscribed
Subject: [Windows-XAML/Template10] How to use MDL2 font instead ofSymbolIcon.Symbol property in Hamburger? (#1619)

For example, the icon E9D9 Diagnostic, is not included in SymbolIcon.Symbol.

**Comment by bubblepipe** [comment]
Thanks michaelhutchful. The issue is solved.
