### ISSUE TITLE
Dumb question about Template 10! hope Jerry can answer it.

### ISSUE THREAD

**Issue by Quico20** [Windows-XAML/Template10#1621]
Jerry:

Firstable let me tell you, you and your collaborators have done a great job with T10.1 and a believe this new version will be awesome for sure.

I could understand in the email, If i'm using Visual Studio 2017 what nuget package should I be looking for since there are tons of Prism versions.

I'm close to finish my first T10.1 app so I wont try to use the newest T10 version on it, but I would like to know the newest version to apply it to my future apps.

Also are you gonna create a course on MVA like you did with Template 10.1??

And finally whats gonna happen with T10. Validation I use it a lot in my project and I found T10.Validation amazing!!!

**Comment by JerryNixon** [comment]
They. Thanks. Template 10 currently supports every version of Visual Studio 2017. I will certainly be creating a lot of training once we're settled. For sure. Also, Validation will either come into Template10.Extras or just get updated to FCU with .NET Core 2. Answer your question(s)?

**Comment by Quico20** [comment]
Kinda answer most of my questions, I still dont know want prism nuget package should I download??
I have an account from pluralsight and honestly i dont know anything about Prism, so I guess I'll take the course from brian lagunas to understand Prism. Unfortunately are old course for WPF and anything for UWP.

So here come my next question, will the T10 extras will be applyable to Xamarin.Forms??? (also T10.Validation included).

**Comment by JerryNixon** [comment]
Ah, ok, now I understand. This is the one you need: https://github.com/Windows-XAML/Template10/tree/master/Temporary

**Comment by JerryNixon** [comment]
As for XF, the quick answer is no. Right now, at least, most of the stuff in there relies on the Windows namespace which is not compat with XF. That being said, it's not unreasonable to consider what parts of the Extras might be moved to a .NET Standard library. But we have to be careful because that would make it Fall Creators Update or later on the UWP side of the game. You see?
