### ISSUE TITLE
Prim.dll => Prism.Core .423-CI?

### ISSUE THREAD

**Issue by mvermef** [Windows-XAML/Template10#1623]
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1102	Unable to find package Prism.Core with version (>= 7.0.0.423-ci)
  - Found 18 version(s) in nuget.org [ Nearest version: 7.0.0.396 ]

**Comment by mvermef** [comment]
its probably just easier to include this...
https://www.myget.org/F/prism/api/v3/index.json

**Comment by JerryNixon** [comment]
Agree
