### ISSUE TITLE
Update Nuget? 

### ISSUE THREAD

**Issue by VladimirAkopyan** [Windows-XAML/Template10#1625]
The current nuget seems to be like 2 years out of date, or am  I looking in the wrong place? 
https://www.nuget.org/packages/Template10

**Comment by mvermef** [comment]
You are probably correct, nuget represents v1, t10.v2 hasn't left beta yet

**Comment by VladimirAkopyan** [comment]
Could you release it as a beta nuget then? Or you recon that's not appropriate?

**Comment by mvermef** [comment]
Grab source, test it. I don't own the source.

**Comment by JerryNixon** [comment]
I think it's about time to release it as a beta, too, but I can't until Prism.Core (@brianlagunas) is in Nuget, too. It's egg and chicken, cart and horse, I am afraid. Maybe he'll chime in.

**Comment by brianlagunas** [comment]
We are in the process of moving modularity into the Prism.Core package which is a big effort. Once that is done we will release a preview to Nuget. We do not have a timeline for the preview release. Currently the Prism team has been swamp with our paying jobs.

**Comment by brianlagunas** [comment]
The Prism team has released the latest preview of Prism.Core to Nuget.

**Comment by jp-weber** [comment]
@JerryNixon 
When will the preview Nuget package updated?

**Comment by JerryNixon** [comment]
https://github.com/Windows-XAML/Template10/issues/1665
