### ISSUE TITLE
Navigation problems

### ISSUE THREAD

**Issue by jp-weber** [Windows-XAML/Template10#1626]
`t10v2`
I have tested the navigation and I saw, that **CanGoBack** and **CanGoForward** not changing the value from false and so the back button  not working?

To the ShellPage or rather said NavViewEx, why is SettingsNavigationUri a URI? 
https://github.com/Windows-XAML/Template10/blob/master/Source/Template10.Extras.16299/Controls/NavViewEx.cs#L180

With the parameter as URI the navigation doesn't work for me.  If I change it to string and set at the ShellPage parameter with "/SettingsPage", the navigation will works.

**Comment by JerryNixon** [comment]
I see, you mean, because it is a Uri it requires the leading forward slash?

**Comment by jp-weber** [comment]
Not exactly. If "SettingsNavigationUri" is a Uri and I set the value to "/SettingsPage", the value will be interpreted as default Uri. This is not how it works. In the specific case I just changed the type to a string and it works.

**Comment by jp-weber** [comment]
@JerryNixon 
The last PRs have solved the problem :)
