### ISSUE TITLE
How to solve: Back button disappear after using Controls:HamburgerMenu.PrimaryButtons or Controls:HamburgerMenu.SecondaryButtons for navigation

### ISSUE THREAD

**Issue by bubblepipe** [Windows-XAML/Template10#1629]
I am using T10 hamburger and I made a back button by using:  
`SystemNavigationManager.GetForCurrentView().AppViewBackButtonVisibility = AppViewBackButtonVisibility.Visible;
`

![screenshot 235](https://user-images.githubusercontent.com/30717258/37249457-c50e2a4e-2522-11e8-898a-2d59e292ba1e.png)

After I navigated to other pages through the left side bar buttons and navigate back, the button does not appear.

**Comment by jp-weber** [comment]
Why do you not use the BackButton function of T10 hamburger? See hamburger sample:
https://github.com/Windows-XAML/Template10/blob/version_1.1.12_vs2017/Templates%20(Project)/Hamburger/ViewModels/SettingsPageViewModel.cs#L56

**Comment by bubblepipe** [comment]
@jp-weber 
do you mean this?
![screenshot 246](https://user-images.githubusercontent.com/30717258/37252664-26a20dba-2560-11e8-8f08-a13ef51a48f6.png)

**Comment by michaelhutchful** [comment]
I don’t think that will solve your issue. What I have noticed is that this is normal behaviour. When you navigate to a page in the hamburger menu, you can’t go back hence the disappearance of the back button.

Sent from my Windows 10 phone

**Comment by jp-weber** [comment]
@UniverseObserver 
You don't need to manually display the BackButton with the t10 HamburgerMenu, because this will be shown automatically when a navigation back is possible and when not, the button is not visible.

**Comment by JerryNixon** [comment]
@UniverseObserver do you feel like your question was answered?

**Comment by bubblepipe** [comment]
I solved the problem, but i do not know what i did and why it works
