### ISSUE TITLE
SplitPaneView in HamburgerMenu doesn't render properly when Page.BottomBar has app/command

### ISSUE THREAD

**Issue by bc3tech** [Windows-XAML/Template10#163]
The bottom part of the hamburger is cut off by the height of the command/app bar in the app.

**Comment by JerryNixon** [comment]
Is the CommandBar in Shell or MainPage?

**Comment by bc3tech** [comment]
@JerryNixon MainPage

**Comment by JerryNixon** [comment]
You may have discovered a bug in the SplitView. 
I will need to investigate in a week after I return.

**Comment by dg2k** [comment]
Please see PR #233.

**Comment by JerryNixon** [comment]
I created issue #246 to correct this. You are welcome to try to implement.
