### ISSUE TITLE
Passing parameters back

### ISSUE THREAD

**Issue by ShawnTheBeachy** [Windows-XAML/Template10#1632]
I'm trying to understand how the new navigation works in 10.2. What I'm trying to do is this:

1. Navigate to ListPage.
2. Navigate to DetailPage.
3. Navigate to EditPage.
4. Navigate back to DetailPage.

From my `ListPageViewModel` I create my path and navigate:

```c#
public async void ViewItem(Item item)
{
    // _navigationService.GetNavigationPath(true) = "/ListPage".
    var path = PathBuilder.Create(nameof(DetailPage), ("itemId", item.Id)).ToString();
    await _navigationService.NavigateAsync(path, null, new DrillInNavigationTransitionInfo());
}
```

Then, to edit the item from my `DetailPageViewModel`:

```c#
public async void EditItem(Item item)
{
    // _navigationService.GetNavigationPath(true) = "/DetailPage?itemId=5cfb0eda-cdbd-4b08-b29b-dff2ef07ea77/ListPage?"
    var path = PathBuilder.Create(nameof(EditPage), ("itemId", item.Id)).ToString();
    await _navigationService.NavigateAsync(path);
}
```

First off, that path seems really strange to me. According to #1620, performing this nested navigation manually would look like "/ListPage/DetailPage?itemId=5cfb0eda-cdbd-4b08-b29b-dff2ef07ea77", so I don't understand why my url looks so weird here. But all the same, the navigation does work correctly.

However, when I go _back_, in my `DetailPageViewModel`...

```c#
public override void OnNavigatedTo(INavigationParameters parameters)
{
    // _navigationService.GetNavigationPath(true) = "/EditPage?itemId=5cfb0eda-cdbd-4b08-b29b-dff2ef07ea77/ListPage?"
    var itemId = parameters.GetValue<string>("itemId");    // parameters is empty.
}
```

Once again, that path seems extremely strange. "DetailPage" isn't even present. Also, I don't get my id parameter handed to my `DetailPageViewModel` again, as I would expect to. Of course, this means my app crashes or doesn't perform correctly since it can't find the necessary data.

Am I grossly misunderstanding how this is supposed to work, or is this broken?

**Comment by JerryNixon** [comment]
So far, I can't get what you are trying to do to fail.

When I put this in:

![image](https://user-images.githubusercontent.com/1749983/37693455-5b600b84-2c85-11e8-9113-f87acf03d0b2.png)

I got this out in the view-model:

![image](https://user-images.githubusercontent.com/1749983/37693471-6e8e16c4-2c85-11e8-8399-01f43a4ddf77.png)

**Comment by JerryNixon** [comment]
I updated the syntax for error catching:

![image](https://user-images.githubusercontent.com/1749983/37694241-2e988562-2c8b-11e8-9b66-d37194bd0bd2.png)

**Comment by ShawnTheBeachy** [comment]
@JerryNixon Is that on initial navigation? Because the first time that I navigate to the detail page, the parameter comes through fine. But when I navigate from there to the edit page, and then go back, the parameter is gone.

**Comment by JerryNixon** [comment]
Ah, yes. I understand. Let me test.

**Comment by JerryNixon** [comment]
Thank you. You were correct. This is an error with Forward, too. Fixing now.

**Comment by JerryNixon** [comment]
Thanks again @TastesLikeTurkey

**Comment by ShawnTheBeachy** [comment]
@JerryNixon Glad I could help!

**Comment by JerryNixon** [comment]
@TastesLikeTurkey Create a new issue if you see anything else.
