### ISSUE TITLE
How to use navigation service

### ISSUE THREAD

**Issue by bubblepipe** [Windows-XAML/Template10#1634]
The document told me: `NavigationService.Navigate(typeof(Views.MainPage));`
but visual studio told me that `An object reference is required for the non-static field, method, or property 'NavigationService.Navigate(Type, object, NavigationTransitionInfo)`
I attempted to create an instance but failed.

**Comment by mvermef** [comment]
what version? where are you using that Nav Service?

**Comment by bubblepipe** [comment]
T10 1.19 
@mvermef
