### ISSUE TITLE
System.ArgumentNullException in NavigationService

### ISSUE THREAD

**Issue by doxxine** [Windows-XAML/Template10#1636]
Sample Application breaks the Backwards-Navigation, if you are clicking backwards too fast. To reproduce: 

- search multiple pages (to have a long history / 10+ )
- klick like a tornado on the backbutton as fast as possible -> breaks 
![capture](https://user-images.githubusercontent.com/20218028/38422643-d48bcf06-39ab-11e8-9c30-0fbc5d142ed9.PNG)

- TEMPLATE 10 v2

**Comment by JerryNixon** [comment]
Thanks, @obscuresystems, let me take a look at this.

**Comment by JerryNixon** [comment]
I am positive this is fixed. 99% positive. ;-)
