### ISSUE TITLE
May I know if it is possible to make Template10 to support Xamarin?

### ISSUE THREAD

**Issue by yanxiaodi** [Windows-XAML/Template10#1638]
Hi, there, I would like to know if it is possible to support Xamarin? I hope I can find a project template like T10 that is really a best practice pattern for UWP platform. Thank you very much.

**Comment by JerryNixon** [comment]
I am excited to tell you that we are rewriting Template 10 right now for this purpose. There is no DIRECT way to support Xamarin with the current version of Template 10 without you creating some kind of shim. Here's a hint, if you start using Prism for Xamarin Forms, you will be setup for the next version of Template 10 as the next version of Template 10 will be Prism for Forms, Windows.

**Comment by yanxiaodi** [comment]
That's really a good news! Thank you very much.

**Comment by panoukos41** [comment]
Hey @JerryNixon so if i already support prism on my Xamarin.Forms i will be able to convert to template10.2 later ?

**Comment by Quico20** [comment]
I'm glad, to hear that, but I'm almost finishing my app with T10.1, I wished to have known about prism before, so I could have done prism right from the beginning. Now I'm having issues to raise the maximum build target for my app. 8 Months of solo work and I feel I wasted my time!!!
