### ISSUE TITLE
Multiple Issues found for Template 10.1

### ISSUE THREAD

**Issue by Quico20** [Windows-XAML/Template10#1643]
As you know, I had been working building an app for my fellows Air Traffic Controllers here in Mexico, so I began building the app using UWP to aim for Windows phones, tablets and Desktops or Laptops.
Using T10.1.

Its been nearly more than 9 months since then and now with the April Update or the Fall Creators Update, T10.1 its been showing issues, that doesn break build for the project but it breaks the designer, if you use Microsoft.Advertising Framework it show errors in the xaml, such as property not found, how ever it builds and works fine, just get a fake error message(error not warning).

Also if you update Newtonsoft to 11.0.2 in spite the program builds, it show a missing library error and won't let you open your app at all so I had to get back to Newtonsoff 10.0.3

After this experience I know you had been working with 10.2 but you shouldn't abandon 10.1 until you get 10.2 release version.

I mean you should keep supporting 10.1 to behave friendly with Microsoft Update which seem to me, are the cause of breaking in this case.

**Comment by JerryNixon** [comment]
Hi @Quico20, hit me on Skype. We can release this week, if you want. The code base is ready. Maybe just a few tweaks. Glad to work with you. And, dude, you are right, it's time.

**Comment by Quico20** [comment]
I've never used prism, but I'm might finish my project using T10.1 for now, I don't know If I'll be able to substitute the MVVM Navigation, the T10.Validation, I use session states to pass parameters from a List to a Master details page, I've read you guys got rid of Session States, I think I would have to change my code a lot.

And to be honest It scares me a bit to begin again or adapt the changes to my nearly end project. what do you suggest me to do??? Because I depended a lot from the T10 template of the hamburger menu, and I think you got rid of it a lot!!!

I'm glad to hear that you will be releasing T10.2 soon. its time!!!

**Comment by JerryNixon** [comment]
No no, I mean we can release 1.1.13 to Nuget this week if you want. Should be simple since most fo the work is done and I have basically just procrastinated the release.

**Comment by Quico20** [comment]
WOW, that would be more than great!!! I'll eagerly wait for the release, Thanks Jerry, you are a Lifesaver!!!! that would be great!!! you had no idea how glad I feel to read T10.1 version 1.1.13 its gonna be out!!! thanks a lot!!!

**Comment by Quico20** [comment]
Hey Jerry, when is T10.1 Version 1.1.13 is going to be release to Nuget??

**Comment by Quico20** [comment]
@JerryNixon when is T10.1 version 1.1.13 gonna be release to Nuget?? its a necessary update, what stopping it?

**Comment by Quico20** [comment]
Falls Creators Update is killing me!!! please release T10.1 V1.1.13 as soon as you are able. I really don't want to begin a new project!!! Its been almost a year of developing using T10.1

**Comment by Quico20** [comment]
@JerryNixon I was able to modified T10.1.1.13p enough to make it work without errors I don't think that it was the version you had in mind for it, because I got rid of the support of Creators Update and lower and just update to work from Falls Creators and Higher!!!.

Thanks great project It really boost UWP development using T10.1.

I know you proposed to get rid of the hamburger menu, but as a suggestion you should and an enhanced hamburger menu using a NavigationView control and tweak it preserving most of the great this of T10.1 Hamburger Menu.

I believe the philosophy of T10.1 was to boost the developing time and T10.1 really does it!!!

Hopefully you release a T10.1.1.13 release version soon!!! for those who haven't been able to use it for the newest Windows 10 versions!!!

**Comment by JerryNixon** [comment]
I really thought I would see a PR from you on this. No?
