### ISSUE TITLE
How can I set minheight of the App / template ?

### ISSUE THREAD

**Issue by famwmann** [Windows-XAML/Template10#1645]
When I resize the App, the minheight become too small for me

How/Where can I prevent this behavior ?

Setting the Minheight in the Shell.xaml-Page don't work.

**Comment by panoukos41** [comment]
I don't think this has anything to do with T10 better look at UWP forums next time, i believe this [here](https://stackoverflow.com/questions/32460737/how-to-set-the-minheight-of-the-window-of-a-win10-uwa) will help 😊
