### ISSUE TITLE
When tablet set to tablet mode the Back button disappears

### ISSUE THREAD

**Issue by zakkar1** [Windows-XAML/Template10#1648]
Hi ,
I'm using VS2017 , UWP , XAML C#
I have noticed a very strange behavior in my Windows PRO tablet where I have installed my app.
When I am in tablet mode the back button from my XAML page disappears.
If I 'm not in tablet mode then the back arrow appears.
What is going on?
Is it something that I need to change ? Something to fix? 
Where can I look for this problem ?
Appreciate your assistance on this
thank you

**Comment by darenm** [comment]
That's in line with the design guidelines for Windows 10. When you switch to tablet mode, there is  a global back button next to the start menu:

![image](https://user-images.githubusercontent.com/1674843/42383567-d0689aa4-80f4-11e8-9992-c0b42ba9a919.png)

**Comment by zakkar1** [comment]
Hi Darenm ,
Yes I know. And I tried to disable  this option , switched to off the Hide app icons on the task bar etc from the tablet mode settings.
I want inside my app no matter what to always display the back button. 
Can this be done ?
Or if it cannot be done any ideas to by pass it ?
Appreciate your thoughts on this

**Comment by zakkar1** [comment]
Although I set the boolean to true it doesn't seem to work

 public bool UseShellBackButton
        {
            get { return _helper.Read<bool>(nameof(UseShellBackButton), true); }
            set
            {
                _helper.Write(nameof(UseShellBackButton), value);
                BootStrapper.Current.NavigationService.GetDispatcherWrapper().Dispatch(() =>
                {
                    BootStrapper.Current.ShowShellBackButton = value;
                    BootStrapper.Current.UpdateShellBackButton();
                });
            }
        }

**Comment by zakkar1** [comment]
I have also tried the below code but it doesn't seem to work

SystemNavigationManager.GetForCurrentView().AppViewBackButtonVisibility = AppViewBackButtonVisibility.Visible;

**Comment by darenm** [comment]
Try setting `BootStrapper.Current.ForceShowShellBackButton = true`

Hmm - thinking about this - I just don't believe there is anyway for the system to show an alternative shell back button in tablet mode - the shell back button is moved down to the taskbar. I suspect you will have to manually manage your own button in this mode. As T10 was implemented to follow the design guidelines, I don't believe there is a simple way to get your desired behavior "for free" with T10 without downloading the source and refactoring to your needs.

**Comment by zakkar1** [comment]
Hi darenm ,
Tried that already in the weekend without success.
I have also tried  this.pageHeader.BackButtonVisibility = Visibility.Visible;

When I placed the above line of code in the OnNavigatedTo even a strange thing happened.
When I was in tablet mode for a second the Shell button appeared and then it disappeared again.
Which means for me that something after the OnNavigatedTo Event is running and disabling the button.

It is too much work for me right now to do this because I am launching my app and I'm trying to think a work around with less effort.
Thank you darenm.

**Comment by zakkar1** [comment]
Hi darenm ,
I have downloaded the sources , went to the Template10.Common, NavButtonsHelper.cs made some changes there (making visible were it should be non visible ) , recompiled and it worked.
But I don't want to make this change on my own if you know what I mean. I want to follow this project and update my app normally through Nuget.
Is it anyway for this case to give us another property so we can bypass this ?

**Comment by Quico20** [comment]
@zakkar I think if you have special needs for you project behavior, you should use your custom code in your project and update it and change it as windows keeps changing.
I think T10.1 is dying since we are close to T10.2 release version via prism.

**Comment by zakkar1** [comment]
Thanks Quico20... I will have to make a decision here .
