### ISSUE TITLE
Template 10.1.1.13 how to apply source code to my app?

### ISSUE THREAD

**Issue by Quico20** [Windows-XAML/Template10#1649]
I downloaded T10.1.1.13 I had compile it and it builds, after some tweaks.

Now what I want is to apply my custom code to my app.
but whenever I try to build it I get an InitializeComponent(); red line showing me that it does exist in the current context I had check my namespace for my App.Xaml and App.Xaml.cs and both are equals, I can't build my app just by that error.

Does anyone know how can I apply the source code successfully??

I honestly need it!!!!

`using Windows.ApplicationModel.Resources;
using Ceneam.Common.DTO;
using Windows.UI.ViewManagement;
using Windows.UI;
using Template10.Services.NavigationService;
using System.Runtime.CompilerServices;

namespace Ceneam
{
    /// Documentation on APIs used in this page:
    /// https://github.com/Windows-XAML/Template10/wiki
    /// 

    [Bindable]
    sealed partial class App : BootStrapper
    {
        public static ICloudService CloudService { get; set; }
        public static ResourceLoader Loader { get; set; }
        public static ProfileInfo Profile { get; set; }

        public App()
        {
            InitializeComponent();//This shows me error
            SplashFactory = (e) => new Views.Splash(e);

            ServiceLocator.Instance.Add<ICloudService, AzureCloudService>();
            CloudService = ServiceLocator.Instance.Resolve<ICloudService>();
            Loader = new ResourceLoader();
            Profile = new ProfileInfo();

            #region app settings
            // some settings must be set in app.constructor
            var settings = SettingsService.Instance;
            RequestedTheme = settings.AppTheme;
            CacheMaxDuration = settings.CacheMaxDuration;
            ShowShellBackButton = settings.UseShellBackButton;
            LoggingService.WriteLine = new DebugWriteDelegate(Log);
            #endregion
        }

        private void Log(string text, Severities severity, Targets target, string caller)
        {
            Debug.WriteLine($"{DateTime.Now.TimeOfDay.ToString()} {severity} {caller} {text}");
        }

        #region Methods

        public override UIElement CreateRootElement(IActivatedEventArgs e)
        {
            var service = NavigationServiceFactory(BackButton.Attach, ExistingContent.Exclude);
            return new ModalDialog
            {
                DisableBackButtonWhenModal = true,
                Content = new Views.Shell(service),
                ModalContent = new Views.Busy(),                
            };
        }
        #endregion

        public override async Task OnStartAsync(StartKind startKind, IActivatedEventArgs args)
        {
            if (startKind == StartKind.Activate)
            {
                ProtocolActivatedEventArgs protocolArgs = args as ProtocolActivatedEventArgs;
                if (protocolArgs != null)
                    CloudService.ResumeWithUrl(protocolArgs.Uri);
            }

            //Set StatusBar background and foreground colors
            if (Windows.Foundation.Metadata.ApiInformation.IsTypePresent("Windows.UI.ViewManagement.StatusBar"))
            {
                var statusBar = StatusBar.GetForCurrentView();
                if (statusBar != null)
                {
                    statusBar.BackgroundOpacity = 1;
                    statusBar.BackgroundColor = Colors.SteelBlue;
                    statusBar.ForegroundColor = Colors.White;
                }
            }

            // TODO: add your long-running task here
            await NavigationService.NavigateAsync(typeof(Views.LoginPage));
            //await NavigationService.NavigateAsync(typeof(Views.RegisterPage));
        }
    }
}`

`<common:BootStrapper x:Class="Ceneam.App"
                     xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                     xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                     xmlns:custconverter="using:Ceneam.Converters"
                     xmlns:converter="using:Template10.Converters"
                     xmlns:common="using:Template10.Common">

    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                
                
                
                
                <ResourceDictionary Source="ms-appx:///Styles/ValidateStyles.xaml"/>
                <ResourceDictionary Source="ms-appx:///ControlTemplates/ContentControls.xaml"/>
                <ResourceDictionary Source="Styles\Custom.xaml" />
            </ResourceDictionary.MergedDictionaries>
            
            <converter:ValueWhenConverter x:Key="VisibilityConverter">
                <converter:ValueWhenConverter.When>
                    <x:Boolean>True</x:Boolean>
                </converter:ValueWhenConverter.When>
                <converter:ValueWhenConverter.Value>
                    <Visibility>Collapsed</Visibility>
                </converter:ValueWhenConverter.Value>
                <converter:ValueWhenConverter.Otherwise>
                    <Visibility>Visible</Visibility>
                </converter:ValueWhenConverter.Otherwise>
            </converter:ValueWhenConverter>
            <converter:ValueWhenConverter x:Key="NegativeVisibilityConverter">
                <converter:ValueWhenConverter.When>
                    <x:Boolean>False</x:Boolean>
                </converter:ValueWhenConverter.When>
                <converter:ValueWhenConverter.Value>
                    <Visibility>Collapsed</Visibility>
                </converter:ValueWhenConverter.Value>
                <converter:ValueWhenConverter.Otherwise>
                    <Visibility>Visible</Visibility>
                </converter:ValueWhenConverter.Otherwise>
            </converter:ValueWhenConverter>
            <custconverter:EnumItemsConverter x:Key="EnumItemsConverter"/>
            <custconverter:StringFormatConverter x:Key="StringFormatConverter"/>
            <custconverter:EnumToStringConverter x:Key="EnumToStringConverter"/>
            <custconverter:DateToStringConverter x:Key="DateToStringConverter"/>
            <custconverter:DateToDatePickerConverter x:Key="DateToDatePickerConverter"/>
            <custconverter:EnumSexToBooleanConverter x:Key="EnumSexToBooleanConverter"/>
            <custconverter:ComboBoxItemConverter x:Key="ComboBoxItemConverter"/>
            <custconverter:CurrencyConverter x:Key="CurrencyConverter"/>
            <custconverter:DoubleToStringConverter x:Key="DoubleToStringConverter"/>
            <custconverter:IntToMonthConverter x:Key="IntToMonthConverter"/>
            <custconverter:DateToRtariDateConverter x:Key="DateToRtariDateStringConverter"/>
            <custconverter:NullStringToStringConverter x:Key="NullStringToStringConverter"/>
            <custconverter:DaysConverter x:Key="FloatToDaysConverter"/>
            <custconverter:DateToShortDateConverter x:Key="DateToShortDateConverter"/>
            <custconverter:BoolToAnswerConverter x:Key="BoolToAnswerConverter"/>
            <custconverter:EnumWorkPlaceToStringConverter x:Key="EnumWorkPlaceToStringConverter"/>
            <custconverter:PhoneNumberToWithoutNumberStringConverter x:Key="PhoneNumberToWithoutNumberStringConverter"/>
            <custconverter:EnumPaymentFactorToBooleanConverter x:Key="EnumPaymentFactorToBooleanConverter"/>
            
            <custconverter:EnumPaymentTimeToBooleanConverter x:Key="EnumPaymentTimeToBooleanConverter"/>
            <custconverter:DoubleToHoursConverter x:Key="DoubleToHoursConverter"/>
            <custconverter:TimeSpanToStringConverter x:Key="TimeSpanToStringConverter"/>
            <custconverter:PaymentFactorToStringConverter x:Key="PaymentFactorToStringConverter"/>
            <custconverter:EnumBooleanConverter x:Key="EnumBooleanConverter"/>
            <custconverter:DateToMonthYearConverter x:Key="DateToMonthYearConverter"/>
            <custconverter:IntToDaysConverter x:Key="IntToDaysConverter"/>
        </ResourceDictionary>
    </Application.Resources>
</common:BootStrapper>`

Hopefully somebody can guide me here, its the first time I try to apply the source code directly to my project!!

**Comment by panoukos41** [comment]
Did you add a reference to the project?

if not one way to do it is to add the projects to your solution and then add the references you want from

> References -> add reference -> projects -> solution

and you will see them there.

another way to do it  is to compile it into a dll (just build it i believe not sure I haven't tried it yet) and then go to

> References -> add reference -> browse (then click browse at the bottom right and find your dll).

I believe the second way is much better since you can update the project when it gets updated and just replace the dll (I haven't tried it myself yet).

**Comment by mvermef** [comment]
before the nuget invention the 1st & 2nd option was the standard, most used 1st for Dev /debug. 2nd was if the dll was black box and you couldn't see the private bits or it was obfuscated.

**Comment by Quico20** [comment]
There is no need I had just solved my issue!!!! I modified T10.1.13p and my project works great now for Falls Creators Update!!!
