### ISSUE TITLE
Is Jerry Nixon on Vacations??

### ISSUE THREAD

**Issue by Quico20** [Windows-XAML/Template10#1651]
Hi, 

I know Jerry is the owner of Template 10 and also a very busy man, but it has been weeks since we last heard of him.

Is he on vacations?

**Comment by JerryNixon** [comment]
Yes. Back now, though. Thanks @Quico20 for keeping track.

**Comment by Quico20** [comment]
Glad you are back!!!
Hopefully you release soon T10.1.1.13 for falls creators and higher!!!
