### ISSUE TITLE
[request] implement missing functions

### ISSUE THREAD

**Issue by jp-weber** [Windows-XAML/Template10#1656]
I noticed in my new app programming that it would be good if the following functions were still implemented:
- [x] OnNavigatingFrom

NavigationService
- [ ] ClearHistory (& available also with XAML like Template10.1)

**Comment by JerryNixon** [comment]
Well, `OnNavigatingFrom` is gone. Sort of. It is is now called `ConfirmNavigation/Async`. You can find their definitions in `IConfirmNavigationAsync` and IConfirmNavigation`.

As for `ClearHistory`, what's the use case?

**Comment by Quico20** [comment]
@JerryNixon ClearHistory I use it on my app, to don't go back to my login page.
That's the use case for me, but I don't know T10.2 V1, I ignore if there is a equivalent for it.

**Comment by jp-weber** [comment]
> Well, `OnNavigatingFrom` is gone. Sort of. It is is now called `ConfirmNavigation/Async`

Thank you Jerry, I didn't know that. As Quico20 already writes is ClearHistory interesting for login pages. 

I'm currently bringing a Template10 v1 app to v2. If I set the start page with /LoginPage, is only the queue reset in this case?

**Comment by JerryNixon** [comment]
Guys, don't put login in the Frame, just place it on the raw Window.Current.Content. It doesn't belong anywhere in the Frame, in Navigation, or anywhere a user might trick navigation.
