### ISSUE TITLE
IncrementalLoadingCollection not refreshing new data

### ISSUE THREAD

**Issue by ghost** [Windows-XAML/Template10#1659]
I am using the IncrementalLoadingCollection class. My source class looks like this:

public class RecipientSource : IIncrementalSource<RecipientDetail>
    {
        public readonly IEnumerable<RecipientDetail> _recipientData;

        /// <summary>
        /// Initializes a new instance of the <see cref="RecipientSource"/> class.
        /// </summary>
        public RecipientSource(IEnumerable<RecipientDetail> data)
        {
            _recipientData = data;
        }

        public async Task<IEnumerable<RecipientDetail>> GetPagedItemsAsync(int pageIndex, int pageSize, CancellationToken cancellationToken = default(CancellationToken))
        {
            return _recipientData.Skip(pageIndex * pageSize).Take(pageSize);
        }
    }

And I initially load it up like this:
            Recipients = new IncrementalLoadingCollection<RecipientSource, RecipientDetail>(
                new RecipientSource(_isTestMode ? _testRecipients : _allRecipients),
                20,
                () => LoadingStarted(),
                () => LoadingCompleted(),
                async (x) => await Functions.OkDialog("Error", "Error loading recipients").ShowAsync());

I have a Checkbox (IsTestMode) which determines what data is in my collection. When I check this after the initial call above, I can see the _recipientData collection chanes, but the UI is never updated with the new set, and the GetPagedItemsAsync is never hit when the collection is changed. 

Am I doing something daft, or using it wrong?

**Comment by mvermef** [comment]
define changes, normally this is a result of not using an `ObservableCollection<T>` with anything XAML that needs to reflect collection changes

**Comment by ghost** [comment]
I'm really just trying to implement this example into an MVVM pattern, and looked at the example in the code. However the example code is done in code behind

**Comment by mvermef** [comment]
I realized that you were using the collection from the UWP Community ToolKit.  which does implement `ObservableCollection<T>`.  How are you connecting it to your view?  How are you calling `RefreshAsync()`  Looks like you need to force a `RefreshAsync()` when you uncheck the box according to the docs.

https://docs.microsoft.com/en-us/dotnet/api/microsoft.toolkit.uwp.incrementalloadingcollection-2?view=win-comm-toolkit-dotnet-stable

**Comment by ghost** [comment]
I initially load my data like this:

           Recipients = new IncrementalLoadingCollection<RecipientSource, RecipientDetail>(
                new RecipientSource(_isTestMode ? _testRecipients : _allRecipients),
                StaticConstants.PageSize,
                () => LoadingStarted(),
                () => LoadingCompleted(),
                async (x) => await Functions.OkDialog("Error", "Error loading recipients").ShowAsync());

When I check my checkbox, I execute the same code as above. I have tried adding Recipients.RefreshAsync(), but the list never changes it's collection. My ListView ItemSource is bound to Recipients

**Comment by JerryNixon** [comment]
Gonna have to close this. Sorry. Off topic from Template 10
