### ISSUE TITLE
Publish a solution level Item Template to the Visual Studio Marketplace

### ISSUE THREAD

**Issue by GoFightNguyen** [Windows-XAML/Template10#1660]
How do I publish a solution-level Item Template to the Visual Studio Marketplace?

I created an Item Template. I want it to be in the __Add New Item__ dialog, under General, when choosing to add a new item at the solution level. I know how to do this on my local machine. The problem is, I want this Item Template to exist in the Marketplace so other devs can install it.

This doesn't feel like the correct place to ask this, but I was directed by the [Visual Studio](https://twitter.com/visualstudio
) twitter to do so. This has nothing to do with Template 10. I think the [Visual Studio](https://twitter.com/visualstudio
) twitter directed me here because this is the source for an extension in the Marketplace. From what I can tell though, these are project templates.

**Comment by JerryNixon** [comment]
ask this guy https://twitter.com/mkristensen

**Comment by GoFightNguyen** [comment]
Thanks @JerryNixon
