### ISSUE TITLE
Getting version_1.1.13[p] to market

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#1665]
Here's what needs to happen; I can't do it all alone, even if I do most of it.

> If you are willing to help **comment on this issue**; we can determine tasks later. If you do this I will add you as an assignee to this task. I'll ping you when work has started and we have enough interest.

## Get started
- [x] Let @Windows-XAML/template-10-developer-community know I'll do it
- [x] Decide we want to update version 1 (@Quico20 can check this one for me)
- [x] Determine there is enough interest (I'll act when we have **10 thumb-ups**)
## Admin kinda stuff
- [x] Label [issues ](https://github.com/Windows-XAML/Template10/issues?utf8=%E2%9C%93&q=is:open+is:issue+-label:T10-Version2+-label:T10-Validation+-label:bug+-label:backlog+) correctly (@darenm and @jerrynixon will do that)
- [ ] Triage Version 1 [Bugs](https://github.com/Windows-XAML/Template10/issues?q=is%3Aopen+is%3Aissue+label%3Abug+label%3AT10-Version1)  (@darenm and @jerrynixon will do that)
- [ ] Triage all Version 1 [Backlog](https://github.com/Windows-XAML/Template10/issues?utf8=%E2%9C%93&q=is:open+is:issue+label:backlog+label:T10-Version1+)  (@darenm and @jerrynixon will do that)
## Final coding
- [ ] Address all Version 1 [Bugs](https://github.com/Windows-XAML/Template10/issues?q=is%3Aopen+is%3Aissue+label%3Abug+label%3AT10-Version1)
- [ ] Address all Version 1 [Backlog](https://github.com/Windows-XAML/Template10/issues?utf8=%E2%9C%93&q=is:open+is:issue+label:backlog+label:T10-Version1+)
## Library
- [ ]  Update nuspec [Code](https://github.com/Windows-XAML/Template10/tree/version_1.1.13p/Template10%20(Library)/Nuget)
- [ ] Submit to Nuget as preview (@jerrynixon has to do this one)
- [ ] Verify the preview version of version 13.
- [ ] Re-submit to Nuget as non-preview version (@jerrynixon has to do this one)
## Template
- [ ] Validate [Hamburger](https://github.com/Windows-XAML/Template10/tree/version_1.1.13p/Templates%20(Project)/Hamburger) template.
- [ ] Validate [Minimal](https://github.com/Windows-XAML/Template10/tree/version_1.1.13p/Templates%20(Project)/Minimal) template.
- [ ] Validate [Blank](https://github.com/Windows-XAML/Template10/tree/version_1.1.13p/Templates%20(Project)/Blank) template.
- [ ] Update the [VSIX](https://github.com/Windows-XAML/Template10/tree/version_1.1.13p/Template10%20(Installer)/Template10.VSIX%20(Template%20Pack)) to support new Visual Studio
- [ ] Upload the VSIX in the VS Gallery (@jerrynixon will have to do that)
## Documentation
- [ ] Upload the Samples build and work
- [ ] Validate the [Wiki](https://github.com/Windows-XAML/Template10/wiki)
- [ ] Update the Wiki (if necessary)
- [ ] Update the home readme
- [ ] Announce on [Twitter](https://twitter.com/jerrynixon) 

And, then we'll have it.

**Comment by IIARROWS** [comment]
Well, giving I can't afford to rework the application around a new framework, and I need the updates... I'm in.

**Comment by Joebeazelman** [comment]
This is sad.  Very sad.  Microsoft just spent $7 billion on Github and doesn't see the value of a cross-platform, UI framework or at least a Windows only one?  They should be pouring money into it, not leaving it up to volunteers.  

At this point, it makes no sense to continue developing Windows only desktop applications.  The empty suits at Microsoft have no coherent stategy and have been consisently dropping the ball. Microsoft is no longer a leader, but a follower.  Soon, they will become irrelevant as more developers use Qt and browser based UI options. Eventually, they will see the wisdom in divorcing themselves from the entire Microsoft development stack.

**Comment by darenm** [comment]
@Joebeazelman You know that Template10 has always been volunteer based with no official support from Microsoft, right? You may not be confused, but I know others have mistakenly thought that the `Windows-XAML` repo is an official Microsoft repository and that Jerry was working in some official capacity. Although Jerry is a Microsoft employee, T10 is not and never has been his job - it's always been a voluntary activity for him and anyone else that contributed.

As to your other points - I share the frustration that this platform has not taken off in the way many hoped it would. That said, desktop development on Windows is far from dead - amazing as it may seem, there are many many Windows Forms and WPF applications being created by developers every day, let alone the countless apps that are being maintained. The way that the desktop development experience is continuing to evolve, you can think of a lot of the UWP features as the way to light up Windows 10 capabilities in apps. Where that app starts from is becoming increasingly open - WinForms, WPF, UWP, PWA and so on. A lot of what Template 10 has always been about was simplifying a rich and complex API footprint into high-level wrappers that illustrate "best practices" for configuring and utilizing the underlying features - that's probably just as useful today as it ever was.

So, if you plan to build apps that not only run on Windows 10, but also leverage some of the best features, then using UWP and T10 makes sense. If, however, you want to build apps that look and feel the same on multiple platforms, then Xamarin, Electron and other technologies are likely better suited for what you want to do.

**Comment by JerryNixon** [comment]
@Joebeazelman, dude, read the room. We're trying to do something here.

**Comment by Quico20** [comment]
I'll try to help with T10.V1 beginning by sharing my T10.v1 modified code. I don't consider myself very good, since I haven't ever worked in a team before.
So I'll try to adapt!!!
By the way I admire Microsoft and for me UWP its a great plataform, My app is being developed for Windows Phone, Tablets and Desktop and it has been a fun experience!!! then I'll do the same app for xamarin.forsms and aim android and ios.

**Comment by helmut-steiner** [comment]
I'm in, too.

**Comment by tibitoth** [comment]
10 thumbs-up ready

**Comment by panoukos41** [comment]
I could try and help with the wiki, i remember doing some things not in there or they had changed, i could give it a try and give examples when everything is ready :D, i would also love to try and do this on T10.V2 when its ready since i am moving my app on cross platform and i am thinking of using a lot of things from prism.

I am pretty new to Github and contributing on other projects so i hope i can do my best while i study!! 😄

**Comment by IIARROWS** [comment]
So... I guess I have to migrate my application to another framework?

**Comment by JerryNixon** [comment]
Yes. I am not going to do this. So many reasons. Look into Prism.Windows.
