### ISSUE TITLE
[Question] Template10.Extras.16299 and extensions

### ISSUE THREAD

**Issue by jp-weber** [Windows-XAML/Template10#1666]
What is the plan for newer implementations of the NavView? With RS4 the NavView get an BackButton and other little functions.

As at present only NavView is in the project, I have updated in my fork the target to the newest SDK and add to the NavViewEx an API query for the back button:
```
Loaded += (s, e) =>
{
    UpdateAppTitleVisibility();
    UpdatePaneHeadersVisibility();
    UpdatePageHeaderContent();

    if (!ApiInformation.IsApiContractPresent("Windows.Foundation.UniversalApiContract", 6))
    {
        SetupBackButton();
    }
};
```
Also an query to set SetupBackButton in context of the implementation of the Titlebar.AppViewBackButton would be nice.

**Comment by JerryNixon** [comment]
It's difficult to know what to do with controls like this while they keep changing out from under us. After talking with the team that owns the control, there are more changes coming. Significant improvements to the control, but certainly making it difficult for us to maintain wrappers like this. I am not sure what to do. Especially in light of the back-compat nature of WinUI. Suggestions?

**Comment by jp-weber** [comment]
That is very difficult. One way I thought of it at first was to work with conditional XAML. However, here is the problem that the conditional XAML with adaptive versionsnot work for wrapper or inheritance, only for the real control. Why work in this scenario not the conditional XAML? Would be a cool feature, if I can write this for custom controls:
`<controls:NavViewEx
            x:Name="ShellView"
            Windows10version1803:PaneTitle="PaneTitle"
            ...`

A second way, which wouldn't be very nice, but probably essential works, would be porting the code of NavViewEx directly to the ShellPage of the corresponding project. Not very optimal, but here you could apply the conditions of the XAML to the NavigationView and we would have given a compatibility to the different versions.

**Comment by darenm** [comment]
@JerryNixon As you say WinUI and the work being done in the Windows Community Toolkit makes me wonder if it is viable to try to keep pace with the changes, especially in the context of T10. Perhaps the controls should be spun out into separate packages with versions that align to snaps shots of the other dependencies. That way other contributors could help maintain the controls that they are using and increment those versions as necessary, without additional churn in T10 as a whole...
