### ISSUE TITLE
sample mediaplayback page

### ISSUE THREAD

**Issue by hieuvn** [Windows-XAML/Template10#1667]
Hi Jerry,
pls provide a sample with mediaplayback page. Thank you.

**Comment by JerryNixon** [comment]
What makes this a Template 10 issue?

**Comment by hieuvn** [comment]
no, Template10 is new for me, i just like to know the best way to navigate(with parameter)  to  page witch contain player, and best way to set source to player, control it from viewmodel.

**Comment by jp-weber** [comment]
Did you look at the official example of this? (with MVVM)
https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/BackgroundMediaPlayback

**Comment by hieuvn** [comment]
thanks jp-weber, it 's very good example!
i was stucked at OnNavigatedToAsync to get parameter, and now it's can be done by using SessionState.
