### ISSUE TITLE
Need some incremental loading samples.  

### ISSUE THREAD

**Issue by lyling** [Windows-XAML/Template10#167]
Incremental loading is a normal scenario at every project. 

I think it is good to add some enhancement about this.

I get some guides:
https://msdn.microsoft.com/en-us/vsto/dn535964?f=255&MSPPError=-2147217396
https://msdn.microsoft.com/en-us/vsto/mt204776#update_items_incrementally

**Comment by JerryNixon** [comment]
Agree. This will take some time. Not really T10 specific. Though the IncrementalCollection should be part of T10 now that I am thinking about it. One step at a time. I will leave this open.

**Comment by h82258652** [comment]
Agree, a base class Inherit ObservableCollection and implement ISupportIncrementalLoading is very useful for developer.

**Comment by startewho** [comment]
I have a similar class here:

```
public interface IIncrementalSource<T>
    {
        /// <summary>
        ///DataSource
        /// </summary>
        /// <param name="query">query</param>
        /// <param name="pageIndex">pageIndex</param>
        /// <param name="pageSize">pageSize</param>
        /// <returns></returns>
        Task<IEnumerable<T>> GetPagedItems(string query,int pageIndex, int pageSize);
    }

    public class IncrementalLoadingCollection<T, I> : ObservableCollection<I>,
         ISupportIncrementalLoading
         where T : IIncrementalSource<I>, new()
    {
        private T source;
        private int pageSize;
        private bool hasMoreItems;
        private int currentPage;
        private string query;

        public IncrementalLoadingCollection(string query,int pageSize )
        {
            source = new T();
            this.pageSize = pageSize;
            hasMoreItems = true;
            this.query = query;
        }

        public bool HasMoreItems
        {
            get { return hasMoreItems; }
        }

        public IAsyncOperation<LoadMoreItemsResult> LoadMoreItemsAsync(uint count)
        {

            var dispatcher = Window.Current.Dispatcher;

            return Task.Run(
                async () =>
                {
                    uint resultCount = 0;

                    var result = await source.GetPagedItems(query,currentPage++, pageSize);

                    if (result != null && dispatcher != null && result.Any())
                    {
                        resultCount = (uint) result.Count();

                            await dispatcher.RunAsync(
                                CoreDispatcherPriority.High,
                                () =>
                                {
                                    foreach (I item in result)
                                        Add(item);

                                });
                        if (resultCount < pageSize)
                        {
                            hasMoreItems = false;
                        }
                    }
                    else
                    {
                        hasMoreItems = false;
                    }


                    return new LoadMoreItemsResult { Count = resultCount };

                }).AsAsyncOperation();
        }
    }

```

**Comment by h82258652** [comment]
@startewho 
I also write a class and an interface like your code.
[IncrementalLoadingCollection](https://github.com/h82258652/SoftwareKobo.UniversalToolkit/blob/master/SoftwareKobo.UniversalToolkit/SoftwareKobo.UniversalToolkit/Mvvm/IncrementalLoadingCollection.cs)
[IIncrementalItemSource](https://github.com/h82258652/SoftwareKobo.UniversalToolkit/blob/master/SoftwareKobo.UniversalToolkit/SoftwareKobo.UniversalToolkit/Mvvm/IIncrementalItemSource.cs)

But I don't think my code is the best. While I use it in my project, I think it is necessary to add a method called "Refresh" to reload the network data.

**Comment by JerryNixon** [comment]
@h82258652 perhaps you want to submit a new sample project in a PR?

**Comment by h82258652** [comment]
demo is #232

**Comment by h82258652** [comment]
by the way, I still don't think the "Refresh" method is the best implement.
@waynebaby Do you have any suggestions about the "Refresh" method?

**Comment by JerryNixon** [comment]
Okay. What issue do you see?
