### ISSUE TITLE
Frame.Navigated not fire on Windows 10 1809/RS5 with T10.2

### ISSUE THREAD

**Issue by jp-weber** [Windows-XAML/Template10#1673]
I realized today that after the upgrade 1809 the navigation via NavigationView doesn't work anymore. I haven't installed RS5 sdk yet, this should be interesting, if it works again with the new target.

**Comment by JerryNixon** [comment]
I have not upgraded yet. I will probably this weekend. What's the error?

**Comment by jp-weber** [comment]
If I click on NavigationViewItem, the navigation is apparently not executed. But as I've seen through the debugging, the [navigated event](https://github.com/Windows-XAML/Template10/blob/master/Source/Template10.Extras.16299/Controls/NavViewEx.cs#L46) doesn't fire, it doesn't seem to matter which sdk you have as your target. The navigation itself seems to work fine, only the assignment of the new context in the navigation view does not work.
