### ISSUE TITLE
ViewModel for ShellPage?

### ISSUE THREAD

**Issue by Nexxkinn** [Windows-XAML/Template10#1675]
I saw the implementation in [App.xaml.cs ](https://github.com/Windows-XAML/Template10/blob/f1056eb6df7b6a7de722895c255b7708a60dc69b/Samples/Sample%20Project%20(16299)/App.xaml.cs) that the Page is not registered with a viewmodel. Is there a way to register the shell with a viewmodel in that case?

Just to be clear, It's possible(?) with `ViewModelLocator.AutowireViewModel="True"` but the upcoming Prism.Windows 7.1.0 somehow include nullable type, which is a no no in XAML.
![image](https://user-images.githubusercontent.com/7548170/47299527-9f16ec80-d644-11e8-8205-38eeb74ee2cf.png)

**Comment by JerryNixon** [comment]
Interesting. Let me think about this. I am working on it now.

**Comment by JerryNixon** [comment]
Nope. I don't see why this would be necessary.

````csharp
var shell = new ShellPage {  DataContext = new ShellViewModel() } ;
````

Or with injection

````csharp
var shell = Resolve<ShellPage>();
shell.DataContext = Resolve<ShellViewModel>();
````

Not sure why any of the navigation methods would be necessary. But if they are, call 'em:

````csharp
(shell.DataContext as ShellViewModel).OnNavigatedTo(null);
````
