### ISSUE TITLE
further development and modifications

### ISSUE THREAD

**Issue by jp-weber** [Windows-XAML/Template10#1680]
In the last time I think about the further development from T10, specifically Template10.Extras.16299.
With the new release of Prism.Windows we can switch from our Prism implementation to the official implementation and can set obsolete our Prism imlementation. The second minor point is the release of the WinUI library, it is now possible to get for older Win10 versions and sdks, the new versions of the controls.

I would therefore suggest to take the NavView through the nuget package, so we don't have to consider dependency properties on the SDKs anymore.

https://github.com/Microsoft/microsoft-ui-xaml

- [x] switch to Prism.Windows / Prism.Windows.Unity

- [x] rename Template10.Extras.16299 to Template10.NavView or NavigationView

- [x] add Windows UI Library to Template10.NavView

- [x] set min sdk target from Template10.NavView to 1703

- [x] update template sample to support Template10.NavView with Windows UI Library

**Comment by deRightDirection** [comment]
where can I find the template10.extras.16299 on nuget?

**Comment by jp-weber** [comment]
This is not yet available at nuget. Currently you must add the library to your project. 

I have adapted the Template10.Extras.16299 locally and already published an app with it. If there exists a request, I will upload it.

**Comment by JerryNixon** [comment]
I thought I would have seen your PR for this by now.

**Comment by jp-weber** [comment]
I will create a pull request in the next days for it👌
