### ISSUE TITLE
training videos in mva not available.

### ISSUE THREAD

**Issue by johnbnstx** [Windows-XAML/Template10#1685]
Hey I am a new for the UWP programming and found out that MVA was shutting down, so the Template 10 training videos are no longer available. anyone know where I can download them and watch?

**Comment by JerryNixon** [comment]
Cool, we're talking about what to do now.

**Comment by DickBaker** [comment]
MVA is gone. Does Template10 and/or PRISM have any future ? 5 months after johnbnstx comment and nearly 3 months after "we're talking about what to do now" ! TIA
