### ISSUE TITLE
Visual Studio 2019 Support

### ISSUE THREAD

**Issue by Dedecekhribecek** [Windows-XAML/Template10#1686]
Is some plan to give support to Visual studio 2019? Thanks for reply.

**Comment by Dedecekhribecek** [comment]
Is some plan to give support to Visual studio 2019? Thanks for reply.

**Comment by Moreno-Borsalino** [comment]
I would like to know that too

**Comment by JerryNixon** [comment]
We need to update the VSIX. I don't have plans to update this project right now. That being said, I have my own UWP apps that I want to use Template 10 with, too. So, maybe. Sorry to be unclear.
