### ISSUE TITLE
How can I access NotifyUser Method?

### ISSUE THREAD

**Issue by Quico20** [Windows-XAML/Template10#1687]
In Template10.1

I dont know how can i access to this line of code:

private MainPage rootPage = MainPage.Current;

rootPage.NotifyUser("Ad requested", NotifyType.StatusMessage);

I know that everything is handled by the bootstrapper, is it posible to access that method??

I'm trying to make ads work in my app.

**Comment by JerryNixon** [comment]
Sorry mate. Is this still a thing? Open a new one.
