### ISSUE TITLE
REQUEST FOR HELPERS / BRINGING BACK TEMPLATE 10

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#1688]
Hey @Windows-XAML/template-10-developer-community ,

As you recall, just before Christmas I ported Template 10 to Prism as Prism.Windows. The dream was that Template 10 would fade away but the code base would continue on in Prism.Windows.

**Spoiler alert**: that didn't work out. 

Unfortunately, the Prism volunteers have their own priorities and are NOT committed to update Prism.Windows. I am not upset, just seeing that something needs to happen. 

This is not acceptable. There is no better framework to build a UWP app than Template 10. None. I believe that. It's why I wrote it. As a result, without Prism.Windows, it is imperative Template 10 _come back to life_. I know you thought I had forgotten about it. I had. 

**Here's my plan over the next few months:**

 1. Clean the entire repo (not much to do there)
 1. Copy over the Prism.Windows code base
 1. Change the namespaces back to Template10
 1. Remove all the UI controls
 1. Keep the behaviors
 1. Keep the converters
 1. Minimize the services
 1. Update the Wiki (it's currently version 1)
 1. Automate the build pipeline
 1. Update the VSIX for VS 2019

## I am looking for volunteers. 
We'll create a simple sprint plan and get this done. Remember, most of the code is already written. I'll make sure collaborators get credit on the site. **Are you in?**

> If you want to contribute, then email me at jerry.nixon at microsoft.com. I will add you to the list and we'll get started next month sometime. You don't need to be a UWP expert to help. I will be the freaking expert. You just be the expert at closing tasks!

**Maybe**: If we get this done, I'll also talk @darenm into recreating the Template 10 training videos that made version 1 so easy to adopt for developers. 

// Jerry

**Comment by mdtauk** [comment]
A few questions that spring to mind.

Could Template 10 just become an app type, and content types for Windows Template Studio?

Should Template 10 use WinUI only and completely eschew the OS framework come WinUI 3,0?

Will Template 10 move beyond UWP when WinUI Desktop becomes the new thing next year?

**Comment by JerryNixon** [comment]
Sure.
 1. Honestly, I can't be sure of the future of WTS. Maybe, later.
 1. We'll consider WinUI when WinUI is an actual thing. It's not an actual thing.
 1. Doesn't seem to make sense right now. It's a UWP framework.

**Comment by akshay2000** [comment]
@JerryNixon It is good to see all this activity here. I have been out of loop with UWP for a bit. So, here's my question: Is there a demand for  UWP framework? I don't see many people writing apps. I don't see a huge UWP push from Microsoft either. It is kinda just... there.

I'm sorry if this sounds negative. I'm just making sure that our efforts are worthwhile. Whenever we start the work, I'm in.

**Comment by JerryNixon** [comment]
Thanks @akshay2000. The answer is yes. According to my inbox.

**Comment by Quico20** [comment]
@JerryNixon I would like to help, but only if you promise to never abandon Template10 again, in the end I had to drop out Template10 a adapt a custom version of template10 of my own.
I felt pretty disappointed that Microsoft abandoned UWP for Mobile, I bet on Microsoft for mobile development, and I still think UWP has potential to be even better than WPF and WF.
So I wish to help but I would love to keep working in a bootstrapper and also keep supporting the hamburger menu because that control can be available through all version of UWP.
And NavigationMenu isn't. Also I wish to create a drawer control to delete records from a list for tablet mode, that option is only available after fall creators update, I wish to make it available through all versions of UWP.
What do you think @JerryNixon?

**Comment by mitchcapper** [comment]
@Quico20 I think free open source software doesn't owe any of us anything.  I certainly hope for a strong T10 future, but Jerry is also not responsible for microsofts mobile choices or UWP in windows options.   As you did, even if further development is not continued in house you can always fork it yourself to continue work.  So the more people who can work on T10 for as long as possible the better, but I don't think anyone can guarantee the future.

**Comment by akshay2000** [comment]
@JerryNixon That is comforting to hear. I've been developing since the time of Windows Phone 7 Series and the feeling of abandonment is strong. I really do hope that UWP takes off. Because right now, silliest of my Google Assistant actions has way more users than my decent UWP app. :-(

**Comment by naweed** [comment]
Yes, I really hope that UWP takes off. I have been developing since Windows Phone 6.5 days, and even had my first Windows 8 app published to the store before Windows 8 official launch day. I have developed lot of UWP apps using Template10. I even used to evangelize UWP here in Bahrain on request from Microsoft Gulf (on their forums). I have given up UWP development since past 1.5-2 years, and moved on to Xamarin development for iOS and Android. I believe that UWP is a superior platform than iOS and Android, and hope that Microsoft starts treating it as a first-class citizen. I would be glad to come back to UWP development, and utilize Template10 for my future projects :).

**Comment by jp-weber** [comment]
>  [...]
> So I wish to help but I would love to keep working in a bootstrapper and also keep supporting the hamburger menu because that control can be available through all version of UWP.
> And NavigationMenu isn't. 

@Quico20
It is. With WinUI it is possible to use the NavigationView for all relevant versions and also great new controls are available.
https://github.com/microsoft/microsoft-ui-xaml

@JerryNixon 
I would also be very interested in participating in the project, but currently have very little time available.

**Comment by ArtjomP** [comment]
Let's think what do we need T10 for in 2k19?

1. Navigation. I use Prism for my Xamarin & UWP projects. I'm pretty satisfied with it.
2. Hamburger menu & shell page. It seems we have it in Windows Community Toolkit & in Xamarin 4.0 Shell.
3. Controls. There're a lot of controls from different vendors. But I agree it's never enough.
4. DI container. It's a lot on the market.
5. Validation & errors on a page. I think there is a gap in this area where T10 can shine even we can enhance it for Xamarin.

May be I missed something.

**Comment by HesamKashefi** [comment]
@ArtjomP how do you use Prism when it does not support UWP ?! Prism had a limited support for UWP and its team always said they are planning for it but they never did and eventually they removed UWP from prism a month ago...
UWP needs a good MVVM library and it doesn't have any right now!

**Comment by ArtjomP** [comment]
@HesamKashefi I use Prism for Navigation and BaseViewModel. It's a little bit different than for Xamarin but works pretty well

**Comment by JerryNixon** [comment]
Right, @ArtjomP . You've described Template 10.

**Comment by jhalbrecht** [comment]
> Right, @ArtjomP . You've described Template 10.

@JerryNixon I'm a bit confused. There is no UWP Shell in Xamarin Forms at this moment. Correct? See this [pull request](https://github.com/xamarin/Xamarin.Forms/pull/6015) from @dotMorten 

At one point in my life I had windows 8/10 desktop and a windows phone. Along with Template10 life was good. I could deploy from the same code base to desktop and mobile. Then a sad day; no more MS windows phone. So saddened. - Sad, sad, sad.

Then I took up Xamarin development in earnest. Life was better. No Template10 though, and no Shell aka hamburger menu? I've been writing my Xamarin apps with prism and liking it. What gives with Xamarin / UWP - shell?

I've been hoping Xamarin starts to support Linux but instead UWP appears to be a 2nd class citizen. It's not the UWP necessarily it's the ability to code for desktop and mobile in a single code base. If I only wanted desktop I'd choose WPF.

**Comment by panoukos41** [comment]
@JerryNixon I'm happy that template 10 is going to be revived,

I was in the process of building an SDK library with extensions for UWP and Android where I was going to have simple classes to get the job done like T10 and Prism.Windows (For android too). I have already ported the PrismAplication and the DeviceGestures. I was using the MVVMLight services for navigation and i have some groundwork for Android with navigation for fragments. I would be really happy to bring those in Template10 since Template10 for me had everything i wanted. This is my library  [OpenExtensions](https://github.com/panoukos41/OpenExtensions) please check it out.

With some guidance I believe it will be easy to bring the good parts (Mostly Android) to T10 :D

I am new to building SDK libraries for C# and I have been coding in C# for two years now I want to believe I am ready to help with stuff like these and I am eager to learn.

**Comment by ShawnTheBeachy** [comment]
Is this something that's still happening? I'm not sure where I got it, but I was under the impression that work was going to start on this towards the end of July, and here we are midway through September.

**Comment by JerryNixon** [comment]
Working now, @ShawnTheBeachy. You bet. Hi @Windows-XAML/template-10-developer-community! This is coming along nicely, though I have not included the many of you who have volunteered. I hope this note will indicate how you can contribute.

## Just published:

https://www.nuget.org/packages/Template10.Behaviors/

> This now includes ConditionalActions, try it out.

https://www.nuget.org/packages/Template10.ListHelpers/

> This supports both GriidView and ListView.

https://www.nuget.org/packages/Template10.Converters/

> The WhenValue Converter is the core to this package.

## Planning to pull down 

https://www.nuget.org/packages/Template10-SampleData/
https://www.nuget.org/packages/Template10-Validation/

> Will republish them with a dot instead of dash.

## Template 10 itself

I am pretty happy with it's current condition. Been using it a lot in different projects to put it through some of the paces. At least at its core, it seems great and I will be updating it on Nuget shortly (hopefully this month). 

 - [x] Template10.Core (I am considering leaving this unlisted)
 - [x] Template10.Core.Default (this will be published as Template10).

## Want to help?

I want to break apart the `Template10.Extras` project so that each service is in an independent project so I can publish it to Nuget individually. This is just a matter of doing it and an PR doing this for me would be very welcome. Very welcome. Then I will publish them all to Nuget. 

- [x]  Template10.Behaviors
- [x]  Template10.Converters
- [ ]  Template10.SampleData
- [ ]  Template10.Validation
- [ ]  Template10.Controls.Resizer
- [ ]  Template10.Controls.NavViewEx
- [x]  Template10.Controls.ImageEx
- [x]  Template10.Services.CompressionService
- [x]  Template10.Services.DialogService
- [x]  Template10.Services.FileService
- [x]  Template10.Services.MarketplaceService
- [x]  Template10.Services.NagService
- [x]  Template10.Services.NetworkService
- [x]  Template10.Services.ResourcesService
- [x]  Template10.Services.SecretsService
- [x]  Template10.Services.SerializationService
- [x]  Template10.Services.SettingsService
- [x]  Template10.Services.WebService

> We'll move the Utilities and Extensions, as appropriate, into Template 10 proper.

###  Documentation

We'll move everything out of the Wiki and into the local `readme.md` file.

## .NET Standard

Please look at the `Converters` and `Behaviors` csproj if you want to see how these should be setup. With these projects all broken apart, it should mean we can push back the supported version as far as possible for each - and not require they all be the same. 

## Controls

I am not sure the `Resizer` is all that important, bit I am willing to publish it as an individual control. I am also willing to leave/update the `ImageEx` control that is already published. Finally, I am not so sure what to do with `NavViewEx`. That's going to take some work to update. I am willing to do it, but I have not updated that code since I wrote the MSDN article about it. Help welcome there, too. 

## A real favor

Please keep your pull requests small. I have had some pull requests that change a zillion files at once, and it's untenable for me to review it. Just keep them small. That's all I ask.

## What about unit test?

Now that we will have so many small projects, we can tackle these as possible. If you are into writing UWP unit tests, I am game to look at your pull request.

**Comment by darenm** [comment]
On the services.

**Comment by JerryNixon** [comment]
I typed "Service" instead of "Services" above. Very sorry. Will have to fix some things.
