### ISSUE TITLE
Uno

### ISSUE THREAD

**Issue by weitzhandler** [Windows-XAML/Template10#1689]
Hi @JerryNixon and thanks for all of your amazing work!

Do I understand right that Template10 is mostly aimed for UWP apps?

I read your post on issue #1688.
Any chance to have Template10 support for the [Uno Platform](http://platform.uno)?
It's basically UWP code that is ported to Droid, iOS, and WASM!

I'm willing to contribute if feasible at all.

**Comment by JerryNixon** [comment]
I am not sure, yet, if that makes sense. Does it? Can navigation be made generic?
