### ISSUE TITLE
Template 10 and SQL

### ISSUE THREAD

**Issue by Dedecekhribecek** [Windows-XAML/Template10#1710]
I have problem to add some local SQL database support to app based on Template10. Adding Microsoft.Data.Sqlite.Core package to Hamburger template default project cause problems during translation. 

Updating Microsoft.NETCore.UniversalWindowsPlatform from 5.2.3 to 6.2.9, Microsoft.Xaml.Behaviors.Uwp.Managed from 1.1.0 to 2.0.1, Newtonsoft.Json from 9.0.1 to 12.0.2 in the same project cause runtime error. 

Please will you give me some recommendation how solve this situation? Thanks for help.

**Comment by jp-weber** [comment]
You are referring to the older version, which has not been updated for many years.

I recommend you to use the newer packages for a new app, which are almost ready.
https://github.com/Windows-XAML/Template10/issues/1697

See also https://github.com/Windows-XAML/Template10/tree/master/Samples/Template10.Nuget.Sample

**Comment by Dedecekhribecek** [comment]
> You are referring to the older version, which has not been updated for many years.
> I recommend you to use the newer packages for a new app, which are almost ready.
> #1697
> See also https://github.com/Windows-XAML/Template10/tree/master/Samples/Template10.Nuget.Sample

Thanks for help
