### ISSUE TITLE
Missing Templates(Zips) Folder?

### ISSUE THREAD

**Issue by toadlyBroodle** [Windows-XAML/Template10#172]
The documentation refers to a Templates(Zips) folder used to manually add templates to Visual Studio. But this folder is missing from the project?

**Comment by darenm** [comment]
This has been removed as we now have a better way to add to visual studio - an extension. If you go to the Visual Studio Gallery you can download it: https://visualstudiogallery.msdn.microsoft.com/60bb885a-44e9-4cbf-a380-270803b3f6e5

**Comment by darenm** [comment]
We just removed the misleading text file too.

**Comment by clankwright** [comment]
Right on
