### ISSUE TITLE
Misleading information about Prism

### ISSUE THREAD

**Issue by rpedretti** [Windows-XAML/Template10#1725]
Hi,

After a while away I noticed that, as per the `readme.md`, the core from T10 migrated to Prism. But I recently saw this [issue](https://github.com/PrismLibrary/Prism/issues/1745) at their repo dropping support for UWP, so I think the `About Template 10.2` section is outdated.

The big problem is that I used `Windows Template Studio` to create a prism app and noticed that T10 core, like NavigationService was not there! 

Also is Template10 new project Template still valid after all changes?

**Comment by JerryNixon** [comment]
It's only dropping UWP-specific support. We don't need that because T10 fills that gap.
