### ISSUE TITLE
Xaml exception (suddenly, without history)

### ISSUE THREAD

**Issue by TeguSolutions** [Windows-XAML/Template10#1727]
Hello,

From one moment to another I am receiving the following error messages:
When starting the UWP app:
One of the content dialog constructor -> InitializeComponent() throws the following exception:

Windows.UI.Xaml.Markup.XamlParseException: 'The text associated with this error code could not be found.
Cannot deserialize XBF metadata property list as 'Behaviors' was not found in type 'Microsoft.Xaml.Interactivity.Interaction'. [Line: 0 Position: 0]'

http://prntscr.com/rb8bdj

And I can't open the XAML Designer:
http://prntscr.com/rb8boo

Template10 version: 1.1.12
Microsoft.Xaml.Behaviors.Uwp.Managed: 2.0.1
So the latest.

There was no any previous sign, this error come up from one moment to another today, everything was working smoothly before.

Can you please suggest anything how can I fix it or debug it?

**Comment by JerryNixon** [comment]
Very sorry I missed this until now. Is this still an issue? How did you rexove?

**Comment by TeguSolutions** [comment]
No worries, I didn't even remember for this. :)
I am pretty sure about I solved it somehow, but I have no clue how.
Now the extension is working well.
