### ISSUE TITLE
How can I use Navigation Service without Template 10 Bootstrapper?

### ISSUE THREAD

**Issue by jaigak** [Windows-XAML/Template10#1734]

**Comment by jp-weber** [comment]
@Jaiganeshkumaran 
Is the question still open?

You can use the NavigationService relatively simple without the whole bootstrapper by creating the service in a page.

```csharp
NavigationService = NavigationFactory.Create(_frame).AttachGestures(Window.Current, Gesture.Back, Gesture.Forward, Gesture.Refresh);
```

You can see this in my app, in connection with the NavigationView.
https://github.com/2fast-team/2fast/blob/master/Project2FA.UWP/Views/ShellPage.xaml.cs#L55

**Comment by JerryNixon** [comment]
There really is considerable value in that service even without Template 10.
