### ISSUE TITLE
PageHeader Color Theme

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#175]
There is something different about PageHeader - you cannot change its background or foreground colors directly, and even the Darlk/Light theme setting has no effect on it. On the contrary the HamburgerMenu color changes behave as you'd expect.  Is this by design? Didn't think so. Just thought I should ask if there is a 'by-design' issue before I look into it.

Couple of weeks ago I tried to change the color theme programmatically, which is now done for us in the Minimal template, and that was when noticed PageHeader didn't change. The same issue exists with the theme setting already implemented and the question is still relevant.

**Comment by JerryNixon** [comment]
> On the contrary the HamburgerMenu color changes behave as you'd expect. Is this by design? 

Yes. :) The HamburgerMenu has gotten significantly more love. This is a good issue report. I am going to ask you to suggest the fix. I am about to step out on vacation for a week. The new AccentColor on the HamburgerButton is not relevant on the PageHeader (you didn't say it was) but implementing that caused the HamburgerMenu to get tested over and over until it worked as expected. PageHeader needs the same attention.

**Comment by dg2k** [comment]
Re-reading my posting, I note some ambiguity. The question "Is this by design? Didn't think so" was intended to refer to the PageHeader, not the HamburgerMenu. At any rate, no info was lost as we understand what needed fixing. Yes, HamburgerMenu behaves as expected, even when I was messing with it to change the theme dynamically.
Have a nice break Jerry!

**Comment by JerryNixon** [comment]
Can't wait to see your PR.

**Comment by dg2k** [comment]
See PR #195.
Update: See my comment in PR #202.
