### ISSUE TITLE
Custom Control in Hamburger Menu

### ISSUE THREAD

**Issue by vinodshinde** [Windows-XAML/Template10#180]
I wanted to add a custom control in Hamburger Menu. After looking at code, found out that its not possible through XAML as NavButtonTemplate is applied to added menus.
So I came up with following simple function to add and it works great.
The function is called on Loaded event of the page.

```
    private void AddCPFControl()
    {
        if (!isPivotAdded)
        {
            var grid = MyHamburgerMenu.FindName("PaneContent") as Grid;
            if (grid != null)
            {
                //add extra RowDefinition at start for top menu items
                grid.RowDefinitions.Insert(0, new RowDefinition() { Height = GridLength.Auto });

                //change the row number of Horizontal Buttons stack panel
                Grid.SetRow(grid.Children.Last() as FrameworkElement, 2);

                if (FilterPane == null)
                    FilterPane = new Controls.FilterPane();

                //set the row number for custom control to 1 so that its displayed in the middle.
                Grid.SetRow(FilterPane, 1);

                grid.Children.Add(FilterPane);
            }
        }
    }
```

Its impossible to meet every programmers unique need but I still feel that Hamburger menu should support adding Custom Controls into it.

Thanks,
Vinod

**Comment by JerryNixon** [comment]
Yeah, we'll convert it to a Content Control in a few versions so it can be completely retemplated. But I agree with you. We should figure out something. Maybe we could consider an ItemTemplate property. Then of course we would also need an ItemTemplate selector and probably change it to allow more than just HamburgerButonInfo objects. Not sure yet. You can see how it can get complex fast. How can we make it flexible and simple? We'll have to think about it, huh?
