### ISSUE TITLE
HamburgerMenu.Buttons Hover Bug

### ISSUE THREAD

**Issue by dcbaby** [Windows-XAML/Template10#183]
Minimal Template :
- background flickers while mouse moved slowly over button
- button hover don't work after busy state

**Comment by JerryNixon** [comment]
To be honest I suspect this is a localized problem that is more reflective of your graphics driver than anything in Template 10. In my tests (as a result of your q) I don't see this. Then to issue number 2. You are right. After busy state the menu appears to be disabled. Need to investigate I think. Maybe someone else can see what's happening here.

I wonder if anyone in @Windows-XAML/community has seen this?

**Comment by dcbaby** [comment]
i will figure out why i have those flickering backgrounds. Maybe someone else with windows 10 build 10537 / 10547  and latest nvidia driver can confirm this issue ? (Evga gtx660ti) I can also imagine a complete different reason but i will check 1st.

EDIT:
- seems those buttons have like 2 zones. If mouse is very close to icon or text they work fine, but if mouse is on edges or on open space i have that rapid fire like hover / not hover behavior. 
- marked flicker area red on snippet 

![capture20151005013813746](https://cloud.githubusercontent.com/assets/12536206/10270964/c95a8f26-6b01-11e5-97c5-526fe81c8e10.png)

The other issue i will investigate but i am mainly a java programmer and debugging in vs 2015 is to be honest unexpected uncomfortable compared to popular IDEs in Java or it`s just that those are unfamiliar to me :).

**Comment by darenm** [comment]
Confirmed I see it also when I move the mouse over the area in red above. Very annoying. As you suggest - could be a driver issue. I have another machine to test on and will update.
_confirmed_ Flicker occurs on 3 different machines I have tested on.

![flickeringregion](https://cloud.githubusercontent.com/assets/1674843/10271359/04e7e4a4-6aca-11e5-8398-4c092fd9ba54.gif)

**Comment by dcbaby** [comment]
i just took a quick look but can`t test it right now, 
solution could be a simple "container" for the button with like : 

``` C#
Width="{Binding ActualWidth, ElementName=itemsControl}"
Height="{Binding ActualHeight, ElementName=symbolIcon}"
```

?

**Comment by JerryNixon** [comment]
Um, @darenm, that might be the coolest comment of all times.

**Comment by JerryNixon** [comment]
Fixed it. Strange one, that.
