### ISSUE TITLE
Suspension problems in the Minimum template

### ISSUE THREAD

**Issue by pekspro** [Windows-XAML/Template10#184]
In MainPageViewModel this code is found:

```
    public override Task OnNavigatedFromAsync(IDictionary<string, object> state, bool suspending)
    {
        if (suspending)
        {
            // persist into cache
            state[nameof(Value)] = Value;
        }
        return base.OnNavigatedFromAsync(state, suspending);
    }
```

Why is the value saved only when going to suspended state? Shouldn’t the value also be saved when navigating to a new page?

I have tried to remove the if-statement so the value is saved if I navigate to a new page. But when I go back to this page the value isn’t restored. The dictionary used in OnNavigatedTo seems to be empty. Should it be like that?

**Comment by JerryNixon** [comment]
The idea is that navigation cache will preserve the page values for you on standard nav if that is your desired behavior, but in the case of suspend you need to manually persist. This would not work without a corresponding reading from the dict in the on nav to override. Make sense?

**Comment by pekspro** [comment]
Hmm… I'm sorry, but no I don’t get it :-(.

Run the Minimal template. Enter some text on the main page.

Then click on the settings button. Now OnNavigateFromAsync is executed and the current logic doesn’t save anything.

Then click the back button. Now OnNavigatedTo is executed but it doesn’t restore the text so the text box is empty which is not what I expected.

If I enable the NavigationCacheMode on the main page there is no difference.

**Comment by darenm** [comment]
Perhaps there is a misconception of what State is doing here and what the sample is expected to be doing. This State is for suspension activity. It is not replacing the implementation of normal business logic associated with entering data into a form and navigating around your app, etc. Your view model should be persisting data out to whatever store you the developer intend to use for storing. The minimal sample is not saving data out to a DB and the data that  is entered into the textbox is intentionally transient. If you want/need alternative behavior, you have all the tools to do so.

**Comment by pekspro** [comment]
Hmm… Maybe I should start from scratch trying to explain what I looking for :-).

I have a page with some business data (let’s say a list with todo-items). This is stored in a database, nothing strange with that. On the same page I have a search box. The text in this box is stored in the state dictionary when the app in suspended and then restored when the application is resumed. This works fine if the application is suspended when this page is visible.

But let’s say I navigate temporary to another page, like a settings view. When I go back to the main page (with the back button, just like the Minimal template) my expectation is that the text in the search box should be the same as when I left the page.

I was hoping to find an easy solution for this. If that’s not supported that’s fine :-). But I think this is a really nice thing to have. We had this support with the Load/SaveState events in the NavigationHelper that was created in Windows 8.1 projects.

**Comment by paxelpixel** [comment]
what are the requirements for OnNavigatedFromAsync and OnNavigatedTo to work? I install nuget from scratch. I only have one view and and viewmodel derive from base. suspension and shutdown or starting doesnt seem to call this two methods. why is that?

**Comment by paxelpixel** [comment]
Nevermind it worked when I set the datacontext in the code behind. I dont know why it didnt when it set it in xaml
