### ISSUE TITLE
Missing extension references in Visual Studio?

### ISSUE THREAD

**Issue by toadlyBroodle** [Windows-XAML/Template10#185]
After installing the Template10 extension in Visual Studio 2015, when trying to build the Template10 project, I get the following errors:

The type or namespace 'Template10' could not be found...
The referenced project '....\Template10 (Library)\Template10 (Library).csproj' does not exist
etc.

![2015-10-03 12-44-21 pm](https://cloud.githubusercontent.com/assets/13908213/10264592/bbd5aca8-69cd-11e5-877e-dfc4f0ad94ba.png)

**Comment by rickgregory1905** [comment]
I'm seeing the issue as well.

**Comment by darenm** [comment]
As we wish to have NuGet be the master version of Template10, you still need to install the Template10 NuGet package. The VSIX is _only_ the templates.

That said, there should not be a reference to the Template10 (Library),csproj left in the template, but there is an easy workaround for now - delete the reference and install the Template10 NuGet package.

**Comment by JerryNixon** [comment]
Template 10 is referenced in the project.json of the template and the best way I have found to make this work (again, I think this will be resolved in the forthcoming update to visual studio) is to "clean" the solution and then "rebuild" the solution. It's the only thing I can find to make it work. You should not have to install the library from NuGet. I don't when I use it. That being said, I have to clean/rebuild the solution (not the project) every time I use it. Sucks, but not our fault.

**Comment by JerryNixon** [comment]
I wanted to add that you need to make sure that you have enabled both checkboxes in the Package Manager Settings in Visual Studio which will be responsible to pull down the packages. Developers have the option to uncheck those boxes which will NOT result in bringing down the packages.

**Comment by clankwright** [comment]
Ok thanks, cleaning and rebuilding didn't work for me, but I'll keep fiddling around with it I guess and see if I can get it to work. For now, just copy/pasting the appropriate code into my other projects is working fine :)

**Comment by darenm** [comment]
I have noticed another issue - sometimes VS2015 does not update the references correctly - on the solution explorer, hit the refresh icon to update them
![image](https://cloud.githubusercontent.com/assets/1674843/10271121/88787222-6ac3-11e5-8791-4abe6ae16ea3.png)

**Comment by jhalbrecht** [comment]
Suggestion; Add a "Know Issues" section to the first page of the wiki / documentation. I bingled, stackoverrflowed and searched the docs several times before stumbling upon this issue.

As I read this issue anyone attempting to use Template10 from the vsix will experience this issue, therefor I feel it should be included in the Documentation not just the bug/issue tracker.

**Comment by jhalbrecht** [comment]
I checked that both NuGet restore options were selected in Options. I checked for updates to the template in tools, then I tried

Build->Clean Solution
Build->Solution

Did't fix. I checked the project.json file Template10 was not referenced. 

After checking project.json in one of the Template10 GitHub samples I added the following to project.json

```
    "Template10": "1.0.*"
```

I got a lot further but still have the following

![image](https://cloud.githubusercontent.com/assets/502208/10290125/232fdda8-6b57-11e5-8e27-91b49e4aafeb.png)

**Comment by jhalbrecht** [comment]
Note; My reporting above concerns the 'minimal' template. Repeated Clean, and Builds have not resolved the problem beyond the 6 errors and 3 warnings described in my previous comment.

However I was able to create a project from the 'blank' template10 project. It's project.json contained the proper Template10 reference, built and deployed successfully.

**Comment by darenm** [comment]
So - those errors are something that was missed in a  some property renames and will be addressed when a new Extension is made available (hopefully soon). The properties you list above have been renamed to exclude the 'Overlay' from the names so find them in the resource (double-click the error) and rename NavButtonCheckedOverlayBackground to NavButtonCheckedBackground  and so on. The guilty party has been flogged...

**Comment by jhalbrecht** [comment]
That worked. The 'minimal' template now compiles and runs after removing the '...Overlay...'. Thank you. 

FWIW I have these warnings.
![image](https://cloud.githubusercontent.com/assets/502208/10295533/16ee6928-6b76-11e5-84ab-11c3b4bf76b5.png)

**Comment by darenm** [comment]
I commented on how to address that reference earlier:
"That said, there should not be a reference to the Template10 (Library),csproj left in the template, but there is an easy workaround for now - delete the reference"

Open the minimal project references and you'll see  it - just delete that one and that'll fix a bunch (although the VCLibs one will probably remain).

**Comment by jhalbrecht** [comment]
Sorry, I didn't quite catch that delete. Yes that cleared all warnings including VCLibs.
