### ISSUE TITLE
Bootstrapper.NavigationService inaccessible due to its protection level

### ISSUE THREAD

**Issue by zangai** [Windows-XAML/Template10#19]
I am following Jerry's blog article (http://blog.jerrynixon.com/2015/04/implementing-hamburger-button-with.html) about implementing a hamburger menu.

I am aware there could have been some changes over time, but I don't know how to do it otherwise.

It occurs in Shell.xaml.cs

``` c#
// nav 
        Template10.Mvvm.Command<NavType> _navCommand; 
        public Template10.Mvvm.Command<NavType> NavCommand { get { return _navCommand ?? (_navCommand = new Mvvm.Command<NavType>(ExecuteNav)); } } 
        private void ExecuteNav(NavType navType)
        { 
            var type = navType.Type; 
            var nav = (App.Current as App).NavigationService;
```

**Comment by zangai** [comment]
I checked out the Template10 Project and added it to my solution, and then referenced it. Maybe that is what makes it treat the **protected** _NavigationService_ property as inaccessible?

**Comment by JerryNixon** [comment]
The revised SplitView implementation is getting a shake down right now. By the end of the day, the implementation of Template 10 Minimal will include an RTM-ready version of SplitView. The blog article you are referencing will still technically work, but it's not half as nice as it is here in Template 10. NavigationService, by the way, is passed in as a parameter to the Shell.cs constructor so its protection level in Bootstrapper will not matter anymore. 

That being said, I think we changed it back to public. The issue with it being public is that the NavigationService in Bootstrapper will only navigate the primary Frame created automatically by the app. Developers using Tempalte 10 with apps that have more than one frame will need to either keep a reference to the NavigationService they create for their second frame or reference is by way of WindowWrapper.Current(Frame). This doesn't sound relevant to you, but I thought I would mention it.
