### ISSUE TITLE
Microsoft .NET Native Runtime Package for Windows 1.1.0.0

### ISSUE THREAD

**Issue by DominikErnst** [Windows-XAML/Template10#198]
A Reference to "Microsoft .NET Native Runtime Package for Windows" Version 1.1.0.0 is missing in all Sample Projects. #BUG

**Comment by weikanglim** [comment]
I had similar issues my first time looking into the examples...
Try building the solution or right clicking the solution to 'Restore NuGet packages'. That should install the proper packages specified in packages.json (which includes the Runtime packages), and resolve the errors.

**Comment by DominikErnst** [comment]
Hi weikanglim, that's the trick. Well done. Thanks.

The Reference to "Microsoft .NET Native Runtime Package for Windows" is not needed!!!

**Comment by JerryNixon** [comment]
Please validate that, update the samples and submit a pull request.
