### ISSUE TITLE
Wiki on Hamburger menu out of date

### ISSUE THREAD

**Issue by MattRWallace** [Windows-XAML/Template10#199]
`NavigationButtonInfo` was renamed to `HamburgerButtonInfo` in commit c129aa98207c57513464bf2265fc02ddd8de80f0 but the wiki page still documents it as `NavigationButtonInfo`.

**Comment by darenm** [comment]
It's a wiki - if you spot an error, you are welcome to correct it. We are always looking for assistance with the documentation.

**Comment by MattRWallace** [comment]
Indeed.  For some reason I thought the wiki was private.  Done.
