### ISSUE TITLE
Template10.csproj not found

### ISSUE THREAD

**Issue by marcioqmaciel** [Windows-XAML/Template10#2]
The Project file "..\Template10\Template10.csproj" is missing.

**Comment by ghost** [comment]
I just used project "\Template10-master\Templates (Project)\Blank". Worked fine for me so far...

**Comment by marcioqmaciel** [comment]
I dont understand. The missing file is a feature?

**Comment by ghost** [comment]
No. I just meant to say that it won't stop you from using the template.

**Comment by JerryNixon** [comment]
This has been released in the most recent commit.
