### ISSUE TITLE
Fail to build Template10-master\Templates (Project)\Sample

### ISSUE THREAD

**Issue by Mitwpgm** [Windows-XAML/Template10#20]
Tried to build Template10-master\Templates (Project)\Sample , but failing to build with following error:

Severity    Code    Description Project File    Line
Error   CS0234  The type or namespace name 'SecondPage' does not exist in the namespace 'Template10.Views' (are you missing an assembly reference?) Sample  C:\Downloads\Template10-master\Template10-master\Templates (Project)\Sample\App.xaml.cs 23

The other samples apps like "Minimal" and "SecondaryTileActivation" are building and running fine.  Please help fix up the "Sample" app.

**Comment by JerryNixon** [comment]
This was the result in an error with how I was clicking around with Git. I would say the version on the web was broken for about two days thanks to my stupidity. I have not resolved the stupidity issue, but I have resolve the Git issue. Thanks for reporting this.
