### ISSUE TITLE
Validation?

### ISSUE THREAD

**Issue by plettb** [Windows-XAML/Template10#201]
I wish I could ask a question without it being called an "issue"!  I guess it is an issue since there is no documentation, but it's not what most developers think of as "an issue".

Anyway, I'm wondering if there has been any thought given to data validation in this template.  I realize that it's likely outside the scope of the template, but, for example, I have typically, in the past, included a "ValidateProperty" method in my base class for INotifyPropertyChanged.  (Of course, I also usually add "RaisePropertyChanged<T>(Expression<Func<T>> propertyExpression)", but again, it's probably outside the scope).

Thoughts?

Thanks!
Brad.

**Comment by waynebaby** [comment]
Hi I personally think we are all moved to MVVM world and we can implement INotifyDataErrorInfo in our viewmodel.  even in wpf it is a preferred solution.

see:https://msdn.microsoft.com/en-us/library/system.componentmodel.inotifydataerrorinfo(v=vs.110).aspx

Date: Fri, 9 Oct 2015 20:58:59 -0700

**Comment by plettb** [comment]
Right, but like it or not, Template10 is providing our MVVM foundation.  That's exactly why I was wondering if the validation belongs there.
For now I'm extending the "ViewModelBase", but this is so common that I wonder if it should be included in that base instead.

**Comment by paxelpixel** [comment]
Is it a good practice to put the header together with the hamburger inside the shell?
or header every view

**Comment by JerryNixon** [comment]
The best solution for validation is our Property<T> described in our Microsoft Virtual Academy course. We have updated it for Windows 10 and will re-teach it in an forthcoming MVA course. Meanwhile you can reference the old one which is 99.9% the same. I will write a validation sample someday, too. But in the meantime, there are some basic documentation gaps to fill.

Here's the link: https://channel9.msdn.com/series/Developing-Universal-Windows-Apps-with-C-and-XAML/05#time=32m02s

**Comment by AmitBhatnagar24** [comment]
Just wondering what the eta (if any) is on a validation sample?

**Comment by plettb** [comment]
I'm still waiting/hoping for a validation sample.  :-)

**Comment by plettb** [comment]
There appears to be a validation sample included now.  It's more complicated than I'd like as a sample, but you can wade your way through and hopefully glean what you need.  That's what I'm attempting to do.

**Comment by mvermef** [comment]
It has always been there you just didn't look hard enough 😋
