### ISSUE TITLE
Error: The type 'DependencyObject' is defined in an assembly that is not referenced

### ISSUE THREAD

**Issue by rsarieddine** [Windows-XAML/Template10#21]
Error   CS0012  
The type 'DependencyObject' is defined in an assembly that is not referenced. You must add a reference to assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'.    

But WindowsRuntime is already referenced. what's going on?

**Comment by JerryNixon** [comment]
That was a mess. Thank you for reporting it. It has been resolved.
