### ISSUE TITLE
Stable version of Template10

### ISSUE THREAD

**Issue by joshberry** [Windows-XAML/Template10#22]
Would you consider the current state of the template ready for use in real apps? I'm starting a new project and Template10 seems like a really good starting point - I like it a lot. I've been watching the progress and am wondering if the template is stable enough to start using or if I should hold off until it's ready.

**Comment by JerryNixon** [comment]
I would consider it stable by the end of today. Yes.

**Comment by joshberry** [comment]
Perfect timing! Thanks for putting this together!

**Comment by JerryNixon** [comment]
Just so you know, the project as a template is nearly perfect. It's the "project template" that is not ready. The heart of the work, obviously, is the library in the solution. That being said, if you used it today (by which I mean tomorrow), you should only need to update the library (which should be non-invasive to your project). If that makes sense?

**Comment by joshberry** [comment]
I think so. I was planning to reference the Template10Library project from my solution and copy in the Minimal template project as the starting point for my app. I'm hoping I can just replace the library reference with a nuget reference at some point in the future. Is that a good approach?

**Comment by JerryNixon** [comment]
Until this shows up as a new template in the Visual Studio gallery that is your only option. And until Tempalte10Library shows up in NuGet, copying it from the repo is your best bet, too. Both will be uploaded soon. We’re working hard on it now.

**Comment by joshberry** [comment]
@JerryNixon I'm seeing quite a few updates over the last couple days and many appear to be within the Minimal project template itself. Do you still think it's a good time to start with the template or would I be better to wait a while (hopefully not too long) until it stabilizes?

**Comment by JerryNixon** [comment]
Minimal is in great shape.

**Comment by AmitBhatnagar24** [comment]
I agree. I think the library may be ready for NuGet! 

Is there anyway to override the color set on the HamburgerAccentBrush to use the {ThemeResource SystemAccentColor}? When I add

<SolidColorBrush x:Key="HamburgerAccentBrush" Color="{ThemeResource SystemAccentColor}" />

to the MinimalProject's Custom.xaml, I see no change.

**Comment by JerryNixon** [comment]
I have added properties to allow this. Gonna close this discussion.
