### ISSUE TITLE
App Crashes When Scrolling in PageHeader

### ISSUE THREAD

**Issue by helmut-steiner** [Windows-XAML/Template10#223]
When opening the secondary command drop down list and scrolling down with either touch or the scrollbar down button the app crashes. Scrolling up is working. I added only two items to the secondary commands without any events for testing purposes.

**Comment by JerryNixon** [comment]
Hmm. We will chase this down. If you find the fix, please submit a PR.

**Comment by janabimustafa** [comment]
I am not able to reproduce this issue on Desktop/Mobile using both touch and mouse (scroll bars and buttons)

**Comment by JerryNixon** [comment]
Do you mean it only happens on Phone?

**Comment by janabimustafa** [comment]
No, sorry I meant I can't reproduce it on either.

**Comment by helmut-steiner** [comment]
This bug only happens on one particular desktop device (a 2in1 laptop) of a colleague. I'll see him tomorrow and try to hunt it down. Thanks for the quick reply!

**Comment by JerryNixon** [comment]
In this case, I am going to close this issue. You can re-open if you can repo it, okay?
