### ISSUE TITLE
HamburgerMenu.IsFullscreen does not work

### ISSUE THREAD

**Issue by teamneusta** [Windows-XAML/Template10#229]
On current implementation, the IsFullscreen property of the HamburgerMenu does not work, it has no effect.

**Comment by JerryNixon** [comment]
It was working in one scenario but not when set directly. Could you test the current code in GitHub? It appears to work for me, but your scenario might be special.

**Comment by schuettecarsten** [comment]
It does not work. Because you've already closed this issue, I will open new issues and describe the problem and possible fix.
