### ISSUE TITLE
Create new UI Control TabMenu

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#238]
![ic794191 1](https://cloud.githubusercontent.com/assets/1749983/10531233/8de63e9a-736c-11e5-911b-8bccfcdbc5e4.png)

Something like this. Refer to https://msdn.microsoft.com/en-us/library/windows/apps/dn997788.aspx

Classes might include:
1. TabMenu
2. TabMenuButtonInfo

TabMenu properties might include:
1. TabHorizontalAlignment
2. TabAreaHeight
3. TabAreaBackground
4. TabAreaForeground
5. TabAreaHeight
6. TabContentPadding
7. SelectionStyle { Underline | Highlight | Outline }
8. AccentColor
9. TabPressedBackground
10. TabPressedForeground
11. TabHoverBackground
12. TabHoverForeground
13. TabCheckedBackground
14. TabCheckedForeground
15. NarrowVisualStateMinWidth
16. NormalVisualStateMinWidth
17. WideVisualStateMinWidth

Since this would inherit from Pivot, it would not need many properties or methods.

TabMenuButtonInfo properties might include:
1. NormalContent
2. NarrowContent
3. IsChecked
4. Background
5. Foreground
6. IsEnabled
7. Width

Again, this is all prelim.

**Comment by JerryNixon** [comment]
Not sure this is a good idea to introduce a new control.

**Comment by lyling** [comment]
great control. is it finish?
