### ISSUE TITLE
Post 1.1 update namespace creation

### ISSUE THREAD

**Issue by jhalbrecht** [Windows-XAML/Template10#240]
After upgrading Template10 to 1.1 I did a new project named T10Minimal1.1 Note the namespaces created do not coincide with the project name. This holds true for all the .xaml pages in /Views I also checked SettingsService.cs and ViewModel*.cs they also have the Sample namespace rather than the expected T10Minimal1.1... namespace.

Tried it with the Blank Template10. Same behavior.

``` xaml
 x:Class="Sample.Views.MainPage"
```

``` Csharp
namespace Sample.Views
```

**Comment by JerryNixon** [comment]
Ack, this is a serious bug. Thanks.

**Comment by JerryNixon** [comment]
Jeff, you know how to fix it, right? Just rename your namespaces and set up the default namespace in the project properties/Application tab.

**Comment by JerryNixon** [comment]
Resolved

**Comment by jhalbrecht** [comment]
Should Assembly name: also be based on the name of the project your'e creating from a template?

I noticed during a failed deploy the assembly name of my project was 'Minimal' although I thought I had changed it it the app manifest. 

![template10assemblyname](https://cloud.githubusercontent.com/assets/502208/10717312/1b7d2b64-7b11-11e5-9337-fbb5b7aae744.png)
