### ISSUE TITLE
Build failed because of XamlUtils.AllChildren() overloads

### ISSUE THREAD

**Issue by saguiitay** [Windows-XAML/Template10#242]
Classes such as EllipsisBehavior call have calls such as:

```
var controls = XamlUtil.AllChildren<Control>(commandBar);
```

However, since the variable `commandBar` is of type `CommandBar`, it matches both overloads of XamlUtil.AllChildren (one which accepts a `Control`, and one that accepts a `DependecyObject`)

**Comment by MichaelPetrinolis** [comment]
I have created a PR https://github.com/Windows-XAML/Template10/pull/241 that includes a fix. I removed both overloads that return control
