### ISSUE TITLE
Post 1.1 Update - hamburger button missing

### ISSUE THREAD

**Issue by kompiuter** [Windows-XAML/Template10#243]
After creating a project using the Minimal template from the gallery the app seems to be missing the hamburger button (on local machine). I don't currently have an emulator installed to try it on a mobile device, I'll update issue when I do.

![2015-10-16 17_33_37-windowsapp5 app](https://cloud.githubusercontent.com/assets/10901325/10544444/1c697640-742c-11e5-98c8-a9a3d17ddf70.png)

**Comment by AmitBhatnagar24** [comment]
Try resizing your window - decrease the width and you'll see the hamburger button reappear (check the NarrowMinWidth, NormalMinWidth, and WideMinWidth values in your custom.xaml)

**Comment by JerryNixon** [comment]
Yep. This is normal behavior. You can set WideMinWidth to -1 and it will not do this, by the way.
