### ISSUE TITLE
Update HamMenu to react to Frame.Page.BottomAppBar close/open

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#246]
The bug right now is that if you use Page.BottomAppBar (or TopAppBar) instead of a page-level grid, then when it is rendered it hides the Pane portion of the HamMenu which, if it has secondary buttons, will make them either unusable or invisible.

> It is reasonable for some apps to use the BottomAppBar because it slides up with the SIP. I believe this is a very distant edge case, but still worth correcting for. 

The solution is to have the HamMenu listen for Page navs and when there is a new page, it should ask the page for its BottomAppBar and if it is set then handle either AppBar or CommandBar. In that handler we will adjust the top or bottom margin of the Ham.Pane. 

Note: it will be very important that the unwire occur so we don't have a memory leak. A better and possibly easier solution would be add WeakReference<T> to T10 library (pref in the Mvvm folder) and use that to attach so we don't have to un-attach later.

**Comment by dg2k** [comment]
See PR #252.

**Comment by JijoBose** [comment]
I have a workaround for this issue here.

https://github.com/Windows-XAML/Template10/issues/406#issuecomment-228585169
