### ISSUE TITLE
PageHeader.SecondaryCommands contents do not display

### ISSUE THREAD

**Issue by callummoffat** [Windows-XAML/Template10#247]
I can't get the AppBarButton controls inside PageHeader.SecondaryCommands to display as of Nuget version 1.0.6. No evidence of their existence appears at all in the running app. Does anybody have any ideas?

**Comment by SimoneBWS** [comment]
I have the same issue... also in MinimalTemplate

**Comment by SimoneBWS** [comment]
Why in Generic.xaml (line 861) Grid named "OverflowContentRoot" has Visibility="Collapsed" ???
If we remove Visibility="Collapsed" PageHeader works fine with SecondaryCommands!

**Comment by MichaelPetrinolis** [comment]
You are right @SimoneBWS , default should be Visible and on PrimaryCommandsOnly VisualState is set to Collapsed. Probably when I was testing it I set it to Collapsed and forgot to set it back. 
I will send a PR (if you have already fixed, you could send the PR)

**Comment by SimoneBWS** [comment]
@MichaelPetrinolis thanks for PR... This small bug stole 5 years of my life :)

**Comment by callummoffat** [comment]
A new pull request has solved this issue, so I'm going to close it.
