### ISSUE TITLE
PageHeader control does not support UTF-8 strings

### ISSUE THREAD

**Issue by michprev** [Windows-XAML/Template10#255]
E.g.:

``` XAML
<controls:PageHeader BackButtonVisibility="Collapsed" Content="Příliš žluťoucký kůň úpěl ďábelské ódy" Frame="{x:Bind Frame, Mode=OneWay}">
            <Interactivity:Interaction.Behaviors>
                <Behaviors:EllipsisBehavior Visibility="Collapsed" />
            </Interactivity:Interaction.Behaviors>
        </controls:PageHeader>
```

![pageheader](https://cloud.githubusercontent.com/assets/7281754/10564011/a63d0978-75a2-11e5-85e7-5c69033afb3a.png)

**Comment by MichaelPetrinolis** [comment]
Have you tried to change the font? Or set the content to a UI element?

**Comment by michprev** [comment]
Also tried with the same result.

However I found that all template files are saved with CP1250 encoding. Saving them with UTF-8 encoding solved the problem.
