### ISSUE TITLE
Error visualization of headerbar

### ISSUE THREAD

**Issue by andelby** [Windows-XAML/Template10#257]
upgraded my template to 1.1 and this error appeared, a blank space between the SplitView and the header bar:
![cattura](https://github-cloud.s3.amazonaws.com/assets/7497813/10565201/46e8ec52-75cb-11e5-8b0f-fac350d26313.PNG)

**Comment by JerryNixon** [comment]
This is not an error in the control. This is an error in your narrow visual state value. Could you take a look at the minimal custom dictionary in styles?

**Comment by andelby** [comment]
I'm sorry I thought that with the update there was this little bug, now all resolved.
Thank you
