### ISSUE TITLE
Comparing with LastNavigationParameter

### ISSUE THREAD

**Issue by pekspro** [Windows-XAML/Template10#258]
In NavigationService there is this method:

```
    public bool Navigate(Type page, object parameter = null, NavigationTransitionInfo infoOverride = null)
    {
        if (page == null)
            throw new ArgumentNullException(nameof(page));
        if (page.FullName.Equals(LastNavigationType)
            && parameter == LastNavigationParameter)
            return false;
        return FrameFacade.Navigate(page, parameter, infoOverride);
    }
```

I suggest to change this to:

```
    public bool Navigate(Type page, object parameter = null, NavigationTransitionInfo infoOverride = null)
    {
        if (page == null)
            throw new ArgumentNullException(nameof(page));
        if (page.FullName.Equals(LastNavigationType))
        {
            if (parameter == LastNavigationParameter)
                return false;

            if (parameter != null && parameter.Equals(LastNavigationParameter))
                return false;
        }

        return FrameFacade.Navigate(page, parameter, infoOverride);
    }
```

I had a problem with this in my application where I generated a new string every time I wanted to go to a page. Then the check (parameter == LastNavigationParameter) failed since it just checked the objects.

Normally I would do a pull request, but this time I’m lazy :-).

**Comment by JerryNixon** [comment]
Also parameter should check with isequals too right?

**Comment by pekspro** [comment]
Yes, didn’t I do that? Or am I missing something? :-)

**Comment by JerryNixon** [comment]
Isn't this your code?

```
if (parameter == LastNavigationParameter)
```

**Comment by pekspro** [comment]
Yes and no :-). It’s from the original code I just moved it.

That check is still needed in cases where both parameter and LastNavigationParameter is null or if they actually are equal. The other check should cover all other cases
