### ISSUE TITLE
Unknown member 'HeaderBackground' on element 'PageHeader' 

### ISSUE THREAD

**Issue by TechWatching** [Windows-XAML/Template10#259]
It seems that in the version 1.0.6 of Template 10 that are some issues with HeaderBackground and HeaderForeground resources in the Styles folder.

**Comment by dg2k** [comment]
HeaderBackground and HeaderForeground don't exist any more since the recent revamp of PageHeader UserControl. Just remove them from your Custom.xaml and all will be fine.

**Comment by TechWatching** [comment]
Ok thanks.
