### ISSUE TITLE
Localization Shell.xaml reDraw

### ISSUE THREAD

**Issue by jhalbrecht** [Windows-XAML/Template10#261]
I've made a good start at Localizing, while updating a win8.0 app to win10 UWP. As part of the learning experience for localizing, note the Earth button in the AppBar, It switches between en-US and fr-FR. I may or may not leave it in as a feature. In the view model when I change the culture I navigate to the current page to re-render the xaml which works fairly well except that a xaml user control on the page doesn't update until I do some more navigation. But my as yet unresolved dilemma and the subject of this question is how to get the Shell.xaml to re-render? Although I can toggle the culture and see those changes reflected into the pages I navigate to, the Shell.xaml culture displayed does not change. If I exit the app and restart then the Shell.xaml will reflect the selected culture at application start.

FWIW I started on this with a v1.0 Minimal template from the .vsix template. I've updated the NuGet, and the Custom.xaml chage.

``` CSharp
  private bool isEnglish = true;
        private void DoLanguageSelectionCommand()
        {
            if (isEnglish)
            {
                CultureInfo culture = CultureInfo.DefaultThreadCurrentUICulture = new CultureInfo("fr-FR");
                Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride = culture.Name;
            }
            else
            {
                CultureInfo culture = CultureInfo.DefaultThreadCurrentUICulture = new CultureInfo("en-US");
                Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride = culture.Name;
            }
            isEnglish = !isEnglish;
            this.NavigationService.Navigate(typeof(Views.MainPage), this.Value);
        }
```

![image](https://cloud.githubusercontent.com/assets/502208/10595275/fbefb382-768a-11e5-9e41-249c6c669fa6.png)

**Comment by jhalbrecht** [comment]
Hmm tried changing the navigation from MainPage to Shell got null reference exception

```
this.NavigationService.Navigate(typeof(Views.Shell), this.Value);
// resulted in:
{"Object reference not set to an instance of an object."}
```

**Comment by JerryNixon** [comment]
Shell does not have an empty constructor.

**Comment by JerryNixon** [comment]
Add a x:Uid to the TextBlock in your HamburgerButtonInfo content elements.

**Comment by jhalbrecht** [comment]
The x:Uid(s) have already been added. Note that in the original image above the Shell is displaying in fr-FR. Also as a visual aid to ensure I had made the changes I added a tilde ('~') to the Text properties. Inspection of these two images shows that the culture can be changed. Unfortunately I had to exit the program and restart to accomplish this for the Shell. Other pages render as desired by toggling the 'earth' app bar button.

I previously stated:

> "...the Shell.xaml culture displayed does not change. If I exit the app and restart then the Shell.xaml will reflect the selected culture at application start."

Here is the Shell.xaml rendered in en-US. I exited the program and restarted to get the change from fr to en. How can I do this programmatically? How can I get Shell.xaml to reflect the culture change from .cs code in my viewmodel?

![image](https://cloud.githubusercontent.com/assets/502208/10601647/d54cbde6-76c7-11e5-9078-83cfd15bdb0a.png)

```
        <Controls:HamburgerMenu x:Name="MyHamburgerMenu" IsEnabled="False">
            <Controls:HamburgerMenu.PrimaryButtons>
                <Controls:HamburgerButtonInfo ClearHistory="True"
                                              PageType="views:MainPage">
                    <StackPanel Orientation="Horizontal">
                        <SymbolIcon Width="48"
                                    Height="48"
                                    Symbol="Home" />
                        <TextBlock x:Uid="TextBlockHamburgerButtonHome" Margin="12,0,0,0"
                                   VerticalAlignment="Center"
                                   Text="~Home" />
                    </StackPanel>
                </Controls:HamburgerButtonInfo>
            </Controls:HamburgerMenu.PrimaryButtons>
            <Controls:HamburgerMenu.SecondaryButtons>
                <Controls:HamburgerButtonInfo PageType="views:ModifyPage">
                    <StackPanel Orientation="Horizontal">
                        <SymbolIcon Width="48" Height="48" Symbol="Keyboard" />
                        <TextBlock x:Uid="TextBlockHamburgerButtonModify" 
                                   Margin="12,0,0,0" VerticalAlignment="Center" Text="~Modify" />
                    </StackPanel>
                </Controls:HamburgerButtonInfo>

                <Controls:HamburgerButtonInfo PageType="views:SettingsPage">
                    <StackPanel Orientation="Horizontal">
                        <SymbolIcon Width="48"
                                    Height="48"
                                    Symbol="Setting" />
                        <TextBlock x:Uid="TextBlockHamburgerButtonSettings"
                                   Margin="12,0,0,0"
                                   VerticalAlignment="Center"
                                   Text="~Settings" />
                    </StackPanel>
                </Controls:HamburgerButtonInfo>
            </Controls:HamburgerMenu.SecondaryButtons>
        </Controls:HamburgerMenu>
```

**Comment by jhalbrecht** [comment]
@JerryNixon says 

> Shell does not have an empty constructor.

So I dug around a bit more and shotgunned this

``` Csharp
var nav = BootStrapper.Current.NavigationServiceFactory(
             BootStrapper.BackButton.Attach,
             BootStrapper.ExistingContent.Include);
Window.Current.Content = new Views.Shell(nav);
```

resulting in

```
An exception of type 'System.ArgumentException' occurred in Template10Library.dll but was not handled in user code

Additional information: Value does not fall within the expected range.
```

**Comment by dg2k** [comment]
Perhaps the question boils down to whether the HamburgerMenu UserControl can be re-rendered to pick up the updated Culture resources. Am I right?  Methods such as InvalidateArrange, InvalidateMeasure (in lieu of InvalidateVisual?) come to mind, and exist for a reason, but no idea if they can be used on HamburgerMenu control.

Jerry can comment on this as HamburgerMenu is his brainchild.

It would be ideal if localization resources update are picked up and refreshed by HamburgerMenu  as you're trying to do.

**Comment by jhalbrecht** [comment]
I haven't made any progress getting the shell.xaml to reflect the culture change when I invoke my  culture/language change toggle. bump? nudge?

However I noticed that I'm adding navigation additions to the navigationCache with the

``` csharp
this.NavigationService.Navigate(typeof(Views.MainPage), this.Value);
```

Although I don't particularly like this solution it is mostly working. How can I navigate to the page I'm on without adding navigation moves to the NavigationCache that are manifested as forward/back buttons? The following code is certainly not valid but might help communicate what I'm getting at.

``` csharp
NavigationTransitionInfo info = NavigationTransitionInfo.DoNotPutThisOnTheNavigationStack;
this.NavigationService.Navigate(typeof(Views.MainPage), this.Value, info);
```

**Comment by JerryNixon** [comment]
Have you tried NavigationService.Refresh()?

**Comment by jhalbrecht** [comment]
That's cool! Thank you, if fixes two issues. It doesn't put the navigation moves on the nav stack and It refreshes the .xaml with the culture change. Unfortunately it didn't reflect the culture change in the Shell.xaml.

``` csharp
            // this.NavigationService.Navigate(typeof(Views.MainPage), this.Value);
            this.NavigationService.Refresh();
```

**Comment by jhalbrecht** [comment]
The addition of 

``` csharp
CultureInfo.CurrentCulture = culture;
```

and

``` csharp
Windows.ApplicationModel.Resources.Core.ResourceContext.GetForCurrentView().Reset();
```

has really  cleared up about all of my localization / culture issues but the elusive Shell.xaml problem remains. It doesn't reflect my in app change of culture. ?Help?

``` csharp
// button toggles en / fr
private void DoLanguageSelectionCommand()
{
    _settings.IsEnglishLanguageCurrent = !_settings.IsEnglishLanguageCurrent;
    _utility.LanguageSelection();
    YeaNoAnswer = _loader.GetString("Flip"); // Update these strings on the ViewModel as they are not bound resources.
    CrystalBallSays = _loader.GetString("CrystalBallAskPrompt");
    this.NavigationService.Refresh();
}
```

``` csharp
public void LanguageSelection()
{
    // TODO The burger is still too rare! Shell.xaml not reflecting in app culture changes.
    if (_settings.IsEnglishLanguageCurrent)
    {/*
        "Gets or sets the default UI culture for threads in the current application domain.

        Type: System.Globalization.CultureInfo
        The default UI culture for threads in the current application domain, or null if the current system UI culture is the default thread UI culture in the application domain."
        */
        CultureInfo culture = CultureInfo.DefaultThreadCurrentUICulture = new CultureInfo("en-US"); // en-US fr-FR
        Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride = culture.Name;
        // "An object that represents the culture used by the current thread."
        CultureInfo.CurrentCulture = culture;
    }
    else
    {
        CultureInfo culture = CultureInfo.DefaultThreadCurrentUICulture = new CultureInfo("fr-FR");
        Windows.Globalization.ApplicationLanguages.PrimaryLanguageOverride = culture.Name;
        CultureInfo.CurrentCulture = culture;
    }
    // EllIfEyeKnow (Still groking), but it helps...  http://stackoverflow.com/questions/20883627/localization-on-the-fly-in-winrt-app
    Windows.ApplicationModel.Resources.Core.ResourceContext.GetForCurrentView().Reset();
    //var resourceContext = Windows.ApplicationModel.Resources.Core.ResourceContext.GetForCurrentView();
    //resourceContext.Reset();
}
```

**Comment by JerryNixon** [comment]
I added this to NavigationService.Refresh().

``` csharp
Windows.ApplicationModel.Resources.Core.ResourceContext.GetForCurrentView().Reset();
```

Hopefully this helps resolve your issues and others.

**Comment by jhalbrecht** [comment]
Hey @JerryNixon why did you close this? Also I thought that I, as a collaborator, could reopen? I have some additional input.

**Comment by jhalbrecht** [comment]
Odd. Before trying out @JerryNixon suggestion / fix I upgraded Template10 nuget from 1.0.6 to 1.0.7. which had the effect of breaking all my previously working language selection code (all was previously working except shell.xaml). Toggling my language selection button has no effect. Just stays in English. I reverted to Template10 nuget 1.0.6, cleaned project and rebuilt. Voilà language changes again with my toggle button.

**Comment by tmukalian** [comment]
@jhalbrecht Did you ever find a solution to translate the shell? I'm having the exact same problem now and have been working on it for a few days and I'm not getting anywhere. As far as I can tell Jerry's solution still won't work because the shell has to be navigated away from and back to see the resource update. Any info is appreciated.

**Comment by jhalbrecht** [comment]
Nope, sure haven't, I'd still like to see it. Considering my interest and yours perhaps @JerryNixon will reOpen this issue.

**Comment by vshengur** [comment]
## Hey @JerryNixon. Thank you for this template. I Like it very much. But...

Yes, there is a problem. When using this template, **you can not fully change the language on the fly**. All of the above methods resolve the issue by changing the content inside SplitView Content. But the language of the contents of a hamburger can not be any quick ways to solve without changing the contents could be for a specific string. Please look again this problem and help with the decision.

**Comment by NVRemoteDev** [comment]
Also interested in this. We have an app for in-house employees, and not all of them should be able to access all of the tools. We hide/enable things on the hamburger menu on startup, but it doesn't work well when we try to force update the security settings, and it requires an app restart.
