### ISSUE TITLE
Splash screen modal

### ISSUE THREAD

**Issue by youtoofan** [Windows-XAML/Template10#262]
I'm not sure if this is intentional, but while the splashscreen is loading the shell is loaded too.
You can test this by setting the Task.Delay value to >2500 ms in the Minimal sample.

After the initial splash logo, the splash screen shows up, immediatly followed by the Shell while the splash is still loading.

I want the splash screen to remain modal, because some background data is being transfered at that point from the azure service.

**Comment by JerryNixon** [comment]
I do too. Any suggestions?

**Comment by youtoofan** [comment]
Funny thing is, I don't think I had this behaviour with version 1.0.3 of the library.
I'm thinking of using the Shell.IsFullScreen property for this. #263 will have to be fixed first though.

**Comment by JerryNixon** [comment]
Fixed. You mean pushed to NuGet?

**Comment by callummoffat** [comment]
I developing a fix for this.

**Comment by callummoffat** [comment]
It involves adding a view model to Splash, which handles enabling the IsFullScreen property for Shell's HamburgerMenu instance via OnNavigatingTo & OnNavigatingFrom in the ViewModel. This is done by adding a SetFullScreen(bool) static method in Shell and activating it in the methods.

**Comment by callummoffat** [comment]
My implementation involves adding a static SetFullScreen(bool) to Shell, which toggles the property in MyHamburgerMenu. I then call this method as soon as the Shell object is initialized in App to enable full screen mode, and again when the main page is navigated to disable.

**Comment by JerryNixon** [comment]
If you remove IsFUllScreen=False from XAML does that do the same thing?

**Comment by callummoffat** [comment]
I'll look into that. Just testing now.

**Comment by callummoffat** [comment]
I can't tell. Splash screen flashes by too fast for me to tell.

**Comment by callummoffat** [comment]
I'll try adding a breakpoint, and test again.

**Comment by callummoffat** [comment]
I still can't tell. Splash doesn't seem to be displaying. Either that, or it's popping through the implementation too fast. I'll try with my app which uses Template 10.

**Comment by callummoffat** [comment]
Yeah, that doesn't work. Tested that in my app, and it stops the menu from displaying. However, it keeps the menu full screen after the splash has completed. So, it's probably necessary to use the method I developed.

**Comment by JerryNixon** [comment]
This is a different error. Full screen should be automatically toggled of if 1. The navigation service navigated and 2. Full screen has not been manually set. 

Hmm. Will need to review.
