### ISSUE TITLE
HamburgerMenu.IsFullScreen crashes

### ISSUE THREAD

**Issue by schuettecarsten** [Windows-XAML/Template10#263]
HamburgerMenu.IsFullScreen crashes when full screen is activated. This happens because the NavigationService.Frame is still assigned to ShellSplitView.Content when it's added to RootGrid.Children. This causes an Exception because the control already has a parent and cannot be added to a different child control list.

To fix this, add ShellSplitView.Content = null in UpdateFullScreen:

```
        private void UpdateFullScreen(bool? manual = null)
        {
            if (manual ?? IsFullScreen)
            {
                if (NavigationService == null || RootGrid.Children.Contains(NavigationService.Frame))
                    return;
                ShellSplitView.Content = null;
                NavigationService.Frame.SetValue(Grid.ColumnProperty, 0);
```

I've send a pull request here: https://github.com/Windows-XAML/Template10/pull/265

**Comment by carstenschuette** [comment]
Pull Request:
https://github.com/Windows-XAML/Template10/pull/265
