### ISSUE TITLE
HamburgerMenu and PageHeader control in "Narrow" mode

### ISSUE THREAD

**Issue by schuettecarsten** [Windows-XAML/Template10#264]
I've set the NarrowMinWidth value to 500. When the show site is smaller than 500 pixels, the menu is hidden, the Hamburger button is still shown in the header, but the header content is shown behind the button:

![2015-10-20 23_09_29-maxdome](https://cloud.githubusercontent.com/assets/1275166/10621235/ba762bc0-777f-11e5-8c2a-69f5bc162770.png)

![2015-10-20 23_09_38-maxdome](https://cloud.githubusercontent.com/assets/1275166/10621239/be0a07de-777f-11e5-8a94-59f304da9514.png)

**Comment by dg2k** [comment]
I cannot reproduce what you describe by setting the NarrowMinWidth in Custom.xaml as:
`<x:Double x:Key="NormalMinWidth">500</x:Double>`. Can you provide more info how you did it, and on which emulator your run it?

**Comment by schuettecarsten** [comment]
Are you using the latest version? Take a look at the PageHeader.cs file - there is no xaml for the PageHeader (or I cannot see it?). Where do you update the NarrowSpacer visibility?

**Comment by dg2k** [comment]
Hmmm... I don't exactly follow you, so forgive me if the following doesn't make sense to you.

 If you change NarrowMinWidth (I don't even see the need for this, as the visual state with NarrowMinWidth  is meant to cater for the upper bounds of mobile devices), I think, you should only do it from the customization file, which in this case is Custom.xaml. I changed NarrowMinWidth in Custom.xaml and didn't notice any anomaly.

**Correction:** In the above I was thinking of NormalMinWidth (see my initial answer) but copying and pasting NarrowMinWidth  from you text so read with NormalMinWidth substituted.

See the following comment.

**Comment by dg2k** [comment]
Wait a minute: I thought you're changing NormalMinWidth to 500 (from 521 that is).

Why do you want to change NarrowMinWidth sitting at 0 to 500? I am not surprised that you're getting some anomaly as you describe.

**Comment by schuettecarsten** [comment]
I have to change it because customer wants it at 500 :-)

I can see the properties in PageHeader.cs file and my value is set there correctly from Custom.xaml. But I cannot find the code or xaml where the value is set into any kind of adaptive trigger that will cause the page header to show or hide the NarrowSpacer.

In earlier versions of Template10 there was a PageHeader.xaml and a PageHeader.xaml.cs file. The xaml contained the VisualStateGroup and triggers to show and hide the NarrowSpacer. Current version only has a PageHeader.cs file.

Do I miss anything?

**Comment by MichaelPetrinolis** [comment]
have you checked themes/generic.xaml ?

**Comment by schuettecarsten** [comment]
Wow.... thanks.
