### ISSUE TITLE
PageHeader "more" button

### ISSUE THREAD

**Issue by dotnetmat90** [Windows-XAML/Template10#266]
How to change visibility of PageHeader "more" button to collapsed.
At the moment it is always visible

**Comment by dg2k** [comment]
In which Project do you see the "more" button on PageHeader? More info will help to answer your query.
OK; You mean the `...` ellipsis.

**Comment by MichaelPetrinolis** [comment]
```
        <i:Interaction.Behaviors>
            <t10behaviors:EllipsisBehavior/>
        </i:Interaction.Behaviors>
```

**Comment by dotnetmat90** [comment]
Ok, nevermind it is ok now, 
thanks to MichaelPetrinolis

**Comment by JerryNixon** [comment]
Nice work finding that behavior before I documented it!

**Comment by MichaelPetrinolis** [comment]
Thank you! I wanted to implement it for the page header control, but ι found that behavior as 'deus ex machina' which is derived from Greek literature, and means 'a machine god made his presence and solved a problem' :)
