### ISSUE TITLE
AppBarButton Label cut off

### ISSUE THREAD

**Issue by jhalbrecht** [Windows-XAML/Template10#267]
![decisivetemplate10appbarbuttoncutoff](https://cloud.githubusercontent.com/assets/502208/10652705/9a9d6898-780d-11e5-9270-992274ebfea3.png)

When I click the three '.' on the app bar to have the AppBarButtons Label text reveald then their Label text is cut off. Where might I investigate to correct this?

``` xaml
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="100"/>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>

        <!-- header -->
        <controls:PageHeader x:Uid="MainPagePageHeader" Text="~Decisions"
                             BackButtonVisibility="Collapsed"
                             Frame="{x:Bind Frame, Mode=OneWay}">
            <controls:PageHeader.PrimaryCommands>
                <AppBarButton Icon="Forward"
                              Label="Forward">
                    <Interactivity:Interaction.Behaviors>
                        <Behaviors:NavButtonBehavior Direction="Forward"
                                                     Frame="{x:Bind Frame, Mode=OneWay}" />
                    </Interactivity:Interaction.Behaviors>
                </AppBarButton>

                    <AppBarButton Label="~Language"
                                  Command="{x:Bind ViewModel.LanguageSelectionCommand, Mode=OneWay}"
                              Icon="World" />
                    <AppBarButton Label="Ball/Coin"
                                  Command="{x:Bind ViewModel.FlipingCoinCrystalBallVisibility, Mode=OneWay}"
                                  Icon="Shuffle" />

            </controls:PageHeader.PrimaryCommands>

            <controls:PageHeader.SecondaryCommands>
            </controls:PageHeader.SecondaryCommands>

        </controls:PageHeader>
```

**Comment by dg2k** [comment]
One way to reproduce your illustrated PageHeader is by setting its Height to around 48 (and yes 48 is not a random number looking at xaml files). Are you programmatically doing something to the PageHeader, such as testing something out and forgot to comment out?

I see no problem with the Grid container but ensure it's in Grid.Row="0" and gets the Auto height it needs. I don't see any explicit setting for PageHeader's Height, not even in generic.xaml (unless of course you set it there, assuming you're using T10 Library source code ;-)

**Comment by jhalbrecht** [comment]
I just noticed that apparently after updating from 1.0.5 to 1.0.6 the AppBarButton Label Text is not cut off anymore. Note however the intersection of Home button and the menu bar. I think I can live with that. Unless perhaps the home button should move down to align with the bottom of the menu bar? 

![t10-1 0 6_appbarbuttonlabelnotcutoff](https://cloud.githubusercontent.com/assets/502208/10687752/67fa65ea-7924-11e5-9676-77b7c90e59f5.png)
