### ISSUE TITLE
HamburgerMenu Refreshing buttons visibility 

### ISSUE THREAD

**Issue by dotnetmat90** [Windows-XAML/Template10#268]
I have HambugerMenu with primary buttons. They should be visible only if IsLoggedIn flag is set true in ViewModel. After changing flag to true nothing is changing

 <tempControls:HamburgerButtonInfo  PageType="views:StartPage" Visibility="{Binding IsLoggedIn, Converter={StaticResource BoolToVisibilityConverter}}">
                    <StackPanel Orientation="Horizontal">
                        <SymbolIcon Width="48" Height="48" Symbol="Library"  />
                        <TextBlock Margin="12,0,0,0" VerticalAlignment="Center" x:Uid="OrdersHistoryTextBlock"/>
                    </StackPanel>

The question is how to refresh primarybuttons collection?

**Comment by dg2k** [comment]
Use a method in Shell.xaml.cs that is called from a viewmodel. For instance, in Shell.xaml.cs:

`
public static void SetMenuAuthorized(bool isAuthenticated)
{

```
        WindowWrapper.Current().Dispatcher.Dispatch(() =>
        {
            Instance.MyMenuVisibleOnLogin.Visibility = (isAuthenticated) ? Visibility.Visible : Visibility.Collapsed;
        });
    }
```

`
Call it from viewmodel as`Views.Shell.SetMenuAuthorized(false)`on MainPage.xaml.cs startup
and`Views.Shell.SetMenuAuthorized(true)` after authentication. 

It works for me.

PS: MyMenuVisibleOnLogin is the x:Name for the menu you want to control visibility.

**Comment by dotnetmat90** [comment]
I am trying to decopule ViewModels and Views. So I don't have access to Pages from ViewModel

**Comment by JerryNixon** [comment]
Assuming that IsLoggedIn is a property exposed by your view-model, I would simply recommend the commands you place in your PageHeader have Visibility bound to that property with a converter (or don't use a converter if your property exposes Visibility, which is a very nice approach).

**Comment by dotnetmat90** [comment]
I already have done this, however still it looks like it works only for the first name, with x:Bind and not working with binding

```
 <tempControls:HamburgerButtonInfo  PageType="views:StartPage" 
Visibility="{x:Bind ViewModel.IsLoggedIn, Mode=TwoWay, Converter={StaticResource BoolToVisibilityConverter}}">
```
