### ISSUE TITLE
1.05 to 1.06 changes

### ISSUE THREAD

**Issue by jhalbrecht** [Windows-XAML/Template10#270]
When I updated from 1.05 to 1.06 I've made the following changes in ViewModelBase.cs and Stypes\Custom.xaml to get my project to compile. For developers out in the wild who aren't following this GitHub repository should we have some release notes that the NuGet package update would put in front of them?

I just copied and pasted the Custom.xaml from the repository into my project. However I noticed that the Custom.[Light|Dark|etc...].xaml is still in the [Template10/Templates (Project) / Minimal/Styles](https://github.com/Windows-XAML/Template10/tree/master/Templates%20%28Project%29/Minimal/Styles) directory. As a point of learning for me, Can/Should they be removed from the current branch of the repository? Weren't they dropped/merged with Custom.xaml?

I wonder if I've missed some changes I should make. The only thing I have is that it now compiles. I'm sure there could be changes made that modify/repair behavior that don't have to be incorporated just to compile, that I might miss. ??

In ViewModelBase.cs I commented out three and added three lines.

``` csharp
        [JsonIgnore]
        public INavigationService NavigationService { get; set; }
        [JsonIgnore]
        public IDispatcherWrapper Dispatcher { get; set; }
        [JsonIgnore]
        public IStateItems SessionState { get; set; }

        //[JsonIgnore]
        //public Template10.Services.NavigationService.NavigationService NavigationService { get; set; }

        //[JsonIgnore]
        //public Template10.Common.DispatcherWrapper Dispatcher { get { return Template10.Common.WindowWrapper.Current(NavigationService)?.Dispatcher; } }

        //[JsonIgnore]
        //public Template10.Common.StateItems SessionState { get { return Template10.Common.BootStrapper.Current.SessionState; } }

```

**Comment by JerryNixon** [comment]
Changes to Interfaces enable unit testing and object injection.
