### ISSUE TITLE
Binding Text in Page Header.

### ISSUE THREAD

**Issue by 9kon** [Windows-XAML/Template10#271]
In the old pageheader I was able to bind the text property in the pageheader to my viewmodel, i cannot get this to work anymore after the update.

Like this. 
Text="{Binding RecivedPosts.title}"

**Comment by 9kon** [comment]
Okay so i figured it out I just have to put a textblock in the content instead.

 controls:PageHeader.Content
                <TextBlock Text="{Binding RecivedPosts.title}"></TextBlock>  
            /controls:PageHeader.Content

**Comment by MichaelPetrinolis** [comment]
you could bind to content also.
