### ISSUE TITLE
Be able to toggle between showing the hamburger menu content in wide and narrow modes

### ISSUE THREAD

**Issue by calloncampbell** [Windows-XAML/Template10#274]
Provide option to be able to toggle between showing the hamburger menu content in wide mode regardless of the app being in full screen mode. I don't necessarily want the hamburger menu to show full content when in full screen mode. I would prefer option to toggle between narrow and wide modes at any time.

Examples are what we see in Groove and Movies & TV vs Weather. Currently Template10 mimics Groove and Movies & TV. I would like to see support for what we see in Weather.

**Comment by dg2k** [comment]
You can do this already with Template10 using the Minimal Template Project. In fact, I proposed the exact same thing a while back (see PR #171 ) only to discover that HamburgerMenu is actually configurable to do what you just described.

I have a sample project to post (I intended to do a week or so ago -- just lack of time), which will demo some interesting features including the compact display mode.

**Comment by JerryNixon** [comment]
Do you want to toggle this through a property or method like Toggle(Enum.Wide) or something like that? This is possible (not in the existing impl) but before we introduce it or even consider it, could you give me a compelling use case where the states are not enough?

**Comment by calloncampbell** [comment]
Either a property or a method will do. 

My reason for providing this feature is allow two implementations. Default is the current method where the app shows the menu based on a state change (size) of the application. If I'm in full screen or on a very large sized monitor and I resize it to the state where it will show the wide menu. The second option would be to not show the wide menu until the users clicks the menu to toggle it from min size to wide size. This provides the user the ability to toggle between min menu and wide menu, as we see on the apps Groove and Movies & TV. This also doesn't force the wide menu on the user when the size reaches the appropriate wide state. Finally the user might want the menu to be kept minimum and only changed to wide view from time to time. Think of the Office Ribbon, users can toggle the ribbon from minimized to full view as they see fit.

I do realize I can turn off the wide view by setting -1 value on the wide state, forcing the menu to stay min.

**Comment by JerryNixon** [comment]
Hmm, I like that use case. Let's put it on the list.

**Comment by JerryNixon** [comment]
The second use case is easiest handled with HamMenu.IsFullScreen

**Comment by JerryNixon** [comment]
Trying to think this through. I can create the property for this easy enough, but I am not sure how to combine the logic of this property and the adaptive trigger since the trigger operator is OR not AND. This might take some tweaking to get right and might be more diff than I thought because of that.

**Comment by dg2k** [comment]
As I indicated above, the very same idea came up in the past (PR #171) and I have done this already. Perhaps a sample project is in order to demo this together with the PageTitle hide/show implemented with Pane open/closed events.

**Comment by JerryNixon** [comment]
Just need to update the docs.
