### ISSUE TITLE
Issue using OpenFlyoutAction on AppBarButton?

### ISSUE THREAD

**Issue by Delaire** [Windows-XAML/Template10#275]
I dont know if i am doing something wrong but I am getting an error when I am trying to attach a FlyoutBase to the OpenFlyoutAction in Template 10.  Am I doing something wrong?

``` XAML
<AppBarButton Icon="Find" Label="Search">
                <FlyoutBase.AttachedFlyout>
                    <Flyout>
                        <AutoSuggestBox Grid.Column="1"
                                        Height="45"
                                        MinWidth="350"
                                        Margin="0"
                                        HorizontalAlignment="Left"
                                        VerticalAlignment="Top"
                                        Background="DarkRed"
                                        PlaceholderText="Search"
                                        QueryIcon="Find"
                                        />
                    </Flyout>
                </FlyoutBase.AttachedFlyout>
                <interactivity:Interaction.Behaviors>
                    <behaviors:OpenFlyoutAction />
                </interactivity:Interaction.Behaviors>
            </AppBarButton>
```

Error message:
The text associated with this error code could not be found.

Cannot add instance of type 'Template10.Behaviors.OpenFlyoutAction' to a collection of type 'Microsoft.Xaml.Interactivity.BehaviorCollection'. [Line: 81 Position: 22]

**Comment by dg2k** [comment]
Aren't you missing out `<Core:EventTriggerBehavior>` around `<behaviors:OpenFlyoutAction />` ?

It works if, for instance, you put `<Core:EventTriggerBehavior EventName="Tapped">` and  `</Core:EventTriggerBehavior>` around `<behaviors:OpenFlyoutAction />` with `xmlns:Core="using:Microsoft.Xaml.Interactions.Core"`

**Comment by MichaelPetrinolis** [comment]
Also you could use something like the following
`<AppBarButton Icon="Calendar" Label="Change Date" Flyout="{StaticResource SelectDateFlyout}"/>`
and define the flyout as a staticresource

**Comment by JerryNixon** [comment]
This is an unrelated comment. How hilarious and awesome it is to me that you guys are finding a using these behaviors I am adding to the library before I get a chance to document them. Kudos to you for being able to reverse-engineer my code. 

Finally, any volunteers to update the docs (now that you understand it) would be welcome.

See: https://github.com/Windows-XAML/Template10/wiki/Docs-%7C-Behaviors-(pre) 

If you take me up on that p[lease update #210

**Comment by Delaire** [comment]
Yes this works our perfectly! @MichaelPetrinolis thanks for the help, @JerryNixon ill add my small example to your documentation.

``` XAML
  <AppBarButton Icon="Find" Label="Search">
                <FlyoutBase.AttachedFlyout>
                    <Flyout>
                        <StackPanel>
                            <TextBlock Text="Awesome Flyout!" />
                        </StackPanel>
                    </Flyout>
                </FlyoutBase.AttachedFlyout>
                <interactivity:Interaction.Behaviors>
                    <core:EventTriggerBehavior EventName="Tapped">
                        <behaviors:OpenFlyoutAction />
                    </core:EventTriggerBehavior>
                </interactivity:Interaction.Behaviors>
            </AppBarButton>
```
