### ISSUE TITLE
Auto SuggestBox in PageHeader?

### ISSUE THREAD

**Issue by Delaire** [Windows-XAML/Template10#276]
![Image of news app](http://i.imgur.com/6qyXKoy.png)

is it possible to add an Auto SuggestBox in the PageHeader just like on the News app?

**Comment by MichaelPetrinolis** [comment]
It seems that in news app the autosuggestion box is right of the page header. So if you split the grid, you could put the autosuggest box to the second column. Otherwise you could put it in the page headers content

**Comment by JerryNixon** [comment]
I want to point you in a direction different than where you are likely headed. There is 0% value in putting this inside the CommandBar. There's no reason not to simply layout the control to the right of the CommandBar/PageHeader instead. I see, now, just like @MichaelPetrinolis said. 

Does this make sense?
