### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by dotnetmat90** [Windows-XAML/Template10#279]
Hi, I would like to change navigation behaviour. Let say I have CategoryPage, and CategoryViewModel. When I tap on category I am sended to another category. How to make possible to go back to root Categories when hitting BackButton without changing page, or viewModel?

**Comment by JerryNixon** [comment]
This would need some custom work. You would handle the BootStrapper.BackRequested, determine "where" the user should go and take care of business like that.

Make sense?

**Comment by dotnetmat90** [comment]
Ok, thanks for answer.
