### ISSUE TITLE
COM Exception when changing background color

### ISSUE THREAD

**Issue by mk0sojo** [Windows-XAML/Template10#281]
Hi,

I have an issue when I try to change the background color to a hex value on the spash screen using the minimal template. If I change <Grid Background="{StaticResource ExtendedSplashBackground}"> in Views/Splash.xaml (line 7) to <Grid Background="#FFFFFFFF"> I get the following exception when trying to run the app.

An exception of type 'System.Runtime.InteropServices.COMException' occurred in mscorlib.ni.dll but was not handled in user code

Additional information: Error HRESULT E_FAIL has been returned from a call to a COM component.

This seems to have started after upgrading to Template10 1.0.6. Is anyone else having this problem?

**Comment by NekitoSP** [comment]
I have COMException too.
And it's here: https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Common/BootStrapper.cs#L311

Exception details:
"System.Runtime.InteropServices.COMException" at mscorlib.ni.dll
Error HRESULT E_FAIL has been returned from a call to a COM component.

```
   at System.Runtime.InteropServices.WindowsRuntime.IIterator`1.MoveNext()
   at System.Runtime.InteropServices.WindowsRuntime.IteratorToEnumeratorAdapter`1.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Money.Common.BootStrapper.<>c__DisplayClass47_0.<InitializeFrameAsync>b__0()
```

I can't create custom color, it's brush and style in Custom.xaml

**Comment by JerryNixon** [comment]
Ack. I wonder if it just needs an OfType<>() filter.
I can't chase this for a little while. Windows 10 Tour events are about to start around the country - maybe I will see you at one of them - I'll try to debug this in the gaps.

**Comment by startewho** [comment]
If it's a platform bug, will be fixed when the windows 10 mobile rtm published?

**Comment by JerryNixon** [comment]
I do not have the answer to this question.
