### ISSUE TITLE
PageHeader's Command Buttons Don't honor the PageHeader's Foreground Color

### ISSUE THREAD

**Issue by AmitBhatnagar24** [Windows-XAML/Template10#303]
How can I get the Page header's command buttons to share the same color that is set for its Foreground color?

In light theme: 
![image](https://cloud.githubusercontent.com/assets/8731921/10956314/8338a43a-830f-11e5-8587-2f6cd53841d9.png)

In dark theme:
![image](https://cloud.githubusercontent.com/assets/8731921/10956323/98b0eb6a-830f-11e5-9b16-d5110ef3e5fe.png)

But should't both cases have the foreground of the command button set to the PageHeader's foreground brush

(Using Custom.xaml from minimal)

**Comment by MichaelPetrinolis** [comment]
The PageHeader inherits from the CommandBar. It just takes into account the HamburgerMenu. You should style the AppBarButton if you want to appear differently.
