### ISSUE TITLE
NavButtonBehavior Current_SizeChanged causes lags when resizing

### ISSUE THREAD

**Issue by ivesely** [Windows-XAML/Template10#304]
Resizing Application in Minimal Template after navigating to detail page is not fluent. it's caused by Calculate method. 
Resolved with #292

**Comment by JerryNixon** [comment]
Please try 

``` csharp
async void SizeChanged() { await Task.Run(() => Calculate()); }
```

A timer is a heavy approach to this problem.

**Comment by ivesely** [comment]
Hi, I have found that Calculate() method must run in Gui thread.
so I tried this

```
    await Task.Factory.StartNew(() =>
    {
      Calculate();
    }, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.FromCurrentSynchronizationContext())
```

Resizing is more fluent, but it is not so good as with the timer approach.
