### ISSUE TITLE
Back button in PageHeader not working if SplitView's pane is open.

### ISSUE THREAD

**Issue by AmitBhatnagar24** [Windows-XAML/Template10#31]
1: Launch Minimal application (initially, the Window comes up with the Pane as Compact)
2: Navigate to Settings 
3: Settings page appears with the Back button in the page header
4: Click HamburgerButton to expose the SplitView's pane.
5: Unable to click the back button in the Settng's page header

**Comment by JerryNixon** [comment]
Fixed.
