### ISSUE TITLE
Initial build fails

### ISSUE THREAD

**Issue by tpspencer** [Windows-XAML/Template10#313]
I have downloaded the latest build as of 11/09/2015 and all projects are red, showing about 1 million errors.  I must be doing something wrong.  Type or namespace "System" could not be found.  All other solutions I am working on are fine.

What is the trick to get the solution building?
![errors](https://cloud.githubusercontent.com/assets/15737661/11041469/a699b362-86d7-11e5-8263-cf2e37c8601c.PNG)

**Comment by darenm** [comment]
Make sure you have set you NuGet options to automatically download packages. 
Build the solution.
Then find the "Refresh" button in the top of your Solution Explorer windows and hit it... 
This should get you going.

**Comment by tpspencer** [comment]
Daren, thanks, that was what I was missing, somehow it got unchecked.

**Comment by darenm** [comment]
Great.
