### ISSUE TITLE
Can't build it, SettingsService missing from the project?

### ISSUE THREAD

**Issue by rikycaldeira** [Windows-XAML/Template10#315]
I can't build the solution, it claims that ISettingsService is missing. In the Solution Explorer there's a missing .cs as well

![image](https://cloud.githubusercontent.com/assets/6810465/11051939/bb670ee2-874b-11e5-9b31-bae08a78a3ff.png)

![image](https://cloud.githubusercontent.com/assets/6810465/11051950/e3bc06cc-874b-11e5-94bf-7e4879f35704.png)

![image](https://cloud.githubusercontent.com/assets/6810465/11051978/2d8226ec-874c-11e5-8123-d4a93972c276.png)

Any tips?
Thanks

**Comment by JerryNixon** [comment]
Get latest. Git error.
