### ISSUE TITLE
When you resume to a sub page, the nav buttons do not highlight

### ISSUE THREAD

**Issue by AmitBhatnagar24** [Windows-XAML/Template10#32]
1: Launch minimal and navigate to the settings page.
2: Close minimal.
3: Re-launch minimal - you are brought back to the Settings page automatically, however the Settings Nav button in the HamburgerMenu isn't highlighted.

(was also able to reproduce such that when relaunched, it would return me to the Main page, but the Home nav button wasn't selected. A Subsequent re-launch did then show the proper state on the Home nav button..)

**Comment by JerryNixon** [comment]
Fixed.
