### ISSUE TITLE
Full width Page header

### ISSUE THREAD

**Issue by youtoofan** [Windows-XAML/Template10#321]
Can the Page Header span the entire page width when the hamburger menu is in VisualStateWide mode?

I think it would look much nicer if only the hamburger icon would disappear, keeping the rectangle in place. The current version has the hamburgermenu slide up when the wide state is active.

**Comment by JerryNixon** [comment]
Now sure what is the best thing to do here. 
I would like other @Windows-XAML/contributors to weigh in on this.

**Comment by bc3tech** [comment]
@youtoofan can you provide some screenshots? having a hard time picturing what you're looking for.

**Comment by youtoofan** [comment]
Well, take a look at this :
<img src="http://www.wintellect.com/devcenter/wp-content/uploads/2015/07/image8.png"/>

If this were Wide Mode, the purple rectangle would disappear and the entire menu would shift one row up. What I suggest is to remove the purple rectangle, but have the pageheader (in light blue/purple) take up the entire width of the screen. And maybe have an app or company logo on the left?

**Comment by mdtauk** [comment]
Is that not what happens when the SplitView mode is set to Overlay?

**Comment by JerryNixon** [comment]
This does not occur in the current version of the hamburger button. I am torn what is the right thing to do here. I am also unsure what we should do if the user clicks the button when it is in this mode. Should it collapse to Compact or completely away?
