### ISSUE TITLE
Invalid Markup - The name "Interaction" does not exist in the namespace "using:Microsoft.Xaml.Interactivity".

### ISSUE THREAD

**Issue by DominikErnst** [Windows-XAML/Template10#324]
This BUGs/Errors drive me crazy:

Using VS 2015 Update1 RC and Template 10 V1.0.7:
Designer shows "Invalid Markup" and VS 2015 Enterprise shows 3 Errors:
2 x The name "Interaction" does not exist in the namespace "using:Microsoft.Xaml.Interactivity".
1 x The name "CallMethodAction" does not exist in the namespace "using:Microsoft.Xaml.Interactions.Core"

References:
- BehaviorsXamlSDKManaged, Version=12.0
- and others

<Page x:Class="Radio.Views.MainPage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:Behaviors="using:Template10.Behaviors"
      xmlns:Core="using:Microsoft.Xaml.Interactions.Core"
      xmlns:Interactivity="using:Microsoft.Xaml.Interactivity"
      xmlns:controls="using:Template10.Controls"
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
      xmlns:local="using:Radio.Views"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
      xmlns:vm="using:Radio.ViewModels" mc:Ignorable="d">

...

```
    <controls:PageHeader BackButtonVisibility="Collapsed" Content="Main Page" Frame="{x:Bind Frame}">
        <Interactivity:Interaction.Behaviors>
            <Behaviors:EllipsisBehavior Visibility="Collapsed" />
        </Interactivity:Interaction.Behaviors>
    </controls:PageHeader>
```

...

**Comment by MichaelPetrinolis** [comment]
Haven't tried it on rc1, but set any CPU and rebuild, and then reopen the designer

**Comment by DominikErnst** [comment]
I have only ARM, x86, x64.

**Comment by DominikErnst** [comment]
I created "Any CPU" with Configuration Manager

Couldn't find the required information in the lock file. Make sure you have UAP,Version=v10.0.10240/win10 mentioned in your targets.

**Comment by DominikErnst** [comment]
I created a new Project with Template 10, there is no "Any CPU".

**Comment by DominikErnst** [comment]
I created a new Project and entered "install-package template10", there is no "Any CPU".

**Comment by MichaelPetrinolis** [comment]
If you create a new UWP project, any CPU is an option? If so adding reference to behaviors and building, works? Maybe It is an issue with RC1

**Comment by MichaelPetrinolis** [comment]
Just saw that you already have done this. In vs2015 RTM , I encountered the same behavior when setting CPU to Arm. After setting it to any CPU and rebuilding, the issue was fixed

**Comment by DominikErnst** [comment]
When I create a blank app UWP, there is no Any CPU. I created the 4th time a new project and now the designer works, I don't know why? After debugging I have often to click in the designer to load the view correct. 
At the Moment there are so many BUGS in VS 2015 and AdMediator and other things, it is not so funny, I spend so much time to handle bugs from others, this annoys me so much!

Thank you.

**Comment by JerryNixon** [comment]
Hmm. We'll be updating to 2015.1 after RTM next week.
