### ISSUE TITLE
PaneWidth property not working

### ISSUE THREAD

**Issue by vinodshinde** [Windows-XAML/Template10#326]
I want to change the width of the split view pane. but setting the PaneWidth property on HamnurgerMenu is not having any effect.

I am trying to set the Pane width to 80% of the phone's width.
On Tablet/Laptop the current behavior is perfect.

**Comment by bc3tech** [comment]
I'm noticing that on the `SplitView` control we have:

``` html
        <SplitView x:Name="ShellSplitView"
                   Grid.Column="0"
                   Grid.ColumnSpan="2"
                   DisplayMode="Inline"
                   OpenPaneLength="220"
                   PaneBackground="Transparent">
```

which seems like changing `PaneWidth` wouldn't be affecting. might we change it to

``` html
        <SplitView x:Name="ShellSplitView"
                   Grid.Column="0"
                   Grid.ColumnSpan="2"
                   DisplayMode="Inline"
                   OpenPaneLength="{x:Bind PaneWidth, Mode=OneWay}"
                   PaneBackground="Transparent">
```

@JerryNixon ?

**Comment by JerryNixon** [comment]
@bc3tech You are right. The current width is hard-coded for desktop. That's the right fix.

**Comment by bc3tech** [comment]
rock on, i'll get a PR flowing for this as well.

**Comment by vinodshinde** [comment]
There is one more line to be fixed to work this properly. I have created a pull request from my fork.
Please check it.

**Comment by bc3tech** [comment]
if @JerryNixon agrees i'll dupe that change and update the PR.

**Comment by bc3tech** [comment]
@JerryNixon what was done about this issue? I don't see notification that a PR was merged, etc...
