### ISSUE TITLE
View model bindings not updating

### ISSUE THREAD

**Issue by joshberry** [Windows-XAML/Template10#33]
I'm not sure if I'm doing something wrong or not, but my view is not updating when the view model (based on ViewModelBase) properties they're bound to are updated. It worked fine on previous versions when BindableBase was directly in the minimal project, but not since it was moved to the library project. If I step through the code in the debugger, the PropertyChanged event is always null and prevents it from being invoked.

Any ideas?

**Comment by JerryNixon** [comment]
If you pull down a new version of the library, this bug was resolved this morning. Thanks Josh. To explain, though, it implemented INotifyPropertyChanged but did not specify the interface in in the class declaration. A simple mistake, really. The changed code inherits from BindableBase.

**Comment by joshberry** [comment]
You're right. Works fine on the latest version. Thanks!
