### ISSUE TITLE
Memory leak in Minimal?

### ISSUE THREAD

**Issue by danuw** [Windows-XAML/Template10#331]
Hi, Template10 is great, thanks!
Although when I launch Template10 with minimal template, it starts at 32mb usage of RAM. As I switch between settings, its pivot views and home alternatively, memory keeps on growing. Is there a possible optimisation for that please? Or an idea of the source of the issue? I do not recall a requirement for anything to be disposed when we switch between pages. Thanks

**Comment by arutkowski00** [comment]
Mine starts at 28 MB of RAM and after tens of times switching pages, it's using only 3-4 MB more, so it's not wasting memory too much. GC isn't collecting used memory, should he recover? Pages are, somehow, staying in memory after clearing navigation history. Maybe some unsubscribed events or bindings prevent dispose?

**Comment by mizzle-mo** [comment]
@JerryNixon With latest Master with 20 MB added in images to both Settings and MainPage views.  I also added a GC.Collect() to the OnNavigatedFromAsync on both ViewModels and then navigated from Settings to MainPage ~40 times.  I'm not seeing a memory leak.

![2015-11-18_18-30-25](https://cloud.githubusercontent.com/assets/6625993/11294564/2327d6de-8f2a-11e5-95c5-5b04aaff730a.png)

**Comment by mizzle-mo** [comment]
This was doing the GC.Collect() at the end.  Looks pretty close to ideal to me.

![2015-11-20_2-14-26](https://cloud.githubusercontent.com/assets/6625993/11294914/e11321ec-8f2c-11e5-9099-4cde4943c337.png)

**Comment by JerryNixon** [comment]
@Mike-Morrison great work. Thanks.
