### ISSUE TITLE
Support for HamburgerMenuInfo.IsChecked = false;

### ISSUE THREAD

**Issue by vinodshinde** [Windows-XAML/Template10#333]
I want to unselect the HamburgerButtonInfo. There should not be anything selected.
It is possible to have a state in which nothing is selected in Hamburger Menu.
I tried 
           MyHamburgerMenu.Selected = null;
            HamburgerButtonInfo.IsChecked = false;

but it does not work. Any suggestions?

**Comment by JerryNixon** [comment]
It works if you do it in the Tapped handler.
But I want this functionality, too.
I have written it like 3 times.
Always StackOverlfow.
Dang it all.

**Comment by JerryNixon** [comment]
I would like to see

``` csharp
Info.IsChecked = false;
Info.CanCheck = false;
```

This would effectively switch it to a standard button.

Maybe perhaps this could accomplish the same thing:

``` csharp
Info.ButtonType = Toggle | Command;
```

**Comment by JerryNixon** [comment]
I did it!

``` csharp
Info.ButtonType = Toggle | Command;
```
