### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by chadbrooks** [Windows-XAML/Template10#334]
It appears that some of the controls are not Accessible.  Specifically I don't see a way to mark the Hamburger Controls with any type of Accessible name.  I am thinking that maybe providing a way to create the "AutomationProperties.Name" property of the underlying Button control would be helpful.

Thanks!

**Comment by dg2k** [comment]
This point is well noted under Issue #26 which asks for help to work on this.

**Comment by JerryNixon** [comment]
Duplicate

**Comment by bc3tech** [comment]
@chadbrooks I went thru and was able to put `AutomationProperties.Name` on usages of `HamburgerButtonInfo` and `HamburgerMenu` - is there something more specific I could look for to ensure I knock this out as part of work on #26?

Specifically, remember that `HamburgerButtonInfo` is just a Content control (basically). Meaning you put whatever you want inside it. Looking at Minimal, you can go in to Shell and do:

``` xml
<Controls:HamburgerMenu x:Name="MyHamburgerMenu" AutomationProperties.Name="">
    <Controls:HamburgerMenu.PrimaryButtons>
        <!-- mainpage button -->
        <Controls:HamburgerButtonInfo ClearHistory="True"
                                      PageType="views:MainPage"
                                      AutomationProperties.Name="">
            <StackPanel Orientation="Horizontal"
                        AutomationProperties.Name="">
                <SymbolIcon Width="48"
                            Height="48"
                            Symbol="Home" />
                <TextBlock Margin="12,0,0,0"
                           VerticalAlignment="Center"
                           Text="Home" />
            </StackPanel>
        </Controls:HamburgerButtonInfo>
    </Controls:HamburgerMenu.PrimaryButtons>
</Controls:HamburgerMenu>
```

Notice how you are able to add `AutomationProperties.Name` to whatever you put _inside_ the `HamburgerButtonInfo` control

**Comment by lombo75** [comment]
Don't know if this can help?

http://stackoverflow.com/questions/33964066/how-do-i-make-a-uwp-custom-i-e-templated-button-control-with-accessibility-su

https://msdn.microsoft.com/en-us/library/windows/apps/xaml/windows.ui.xaml.automation.peers.radiobuttonautomationpeer.aspx

http://referencesource.microsoft.com/#PresentationFramework/src/Framework/System/Windows/Controls/RadioButton.cs
