### ISSUE TITLE
"Minimal" fails to build

### ISSUE THREAD

**Issue by sdrubenstein** [Windows-XAML/Template10#338]
Windows 10 build 10586
Visual Studio Community 14.0.23107
I added Template 10 in extensions
Checked  to make sure both checkboxes in pac man settings checked
Created a new solution using Template 10 (Minimal)
Clean, Rebuild
Error message says, Unable to resolve Template10 (≥ 1.0.8) for UAP,Version=v10.0.
followed by a long list of "type or namespace name XXX could not be found
where XXX = Uri, TimeSpan, Template10, etc.

I can build "Blank" but not "Minimal".  I'm inexperienced and this is probably something stupid, but it looks like something is missing from the "First things first, getting the T10 templates to build." instructions.

**Comment by dg2k** [comment]
In MainPage.xaml change the following:

`<AppBarButton Click="{x:Bind GotoPrivacy}" Label="Privacy" />`
`<AppBarButton Click="{x:Bind GotoAbout}" Label="About" />`

to:

`<AppBarButton Click="{x:Bind ViewModel.GotoPrivacy}" Label="Privacy" />`
`<AppBarButton Click="{x:Bind ViewModel.GotoAbout}" Label="About" />`

and try building.

**Comment by darenm** [comment]
Did someone publish a version 1.0.8 of the Nuget package and revert? The latest is 1.0.7... Or has someone updated the project.json in Minimal to require 1.0.8 instead of 1.0.\* ? (Hmm 8 is \* without the shift... typo?)

![snip_20151113162604](https://cloud.githubusercontent.com/assets/1674843/11160124/4be017d2-8a23-11e5-8382-78372e0d4d25.png)

**Comment by dg2k** [comment]
I got 3400+ errors and narrowed down by changing to x86, etc. and later prefixing GotoPrivacy and GotoAbout with ViewModel (because of couldn't locate error showed up) made it compile.I don't know why but it worked and I know this is not the right approach ...  Something somewhere is wrong.

**Comment by sdrubenstein** [comment]
I note that project.json in "Blank" is "1.0.*" while the one in Minimal is "1.0.8". Changing the 8 to a \* is an improvement, but there is something else wrong, as the ModalDialog control and the FocusAction Behavior are missing from the library.

**Comment by darenm** [comment]
Yes - it looks like some changes have been published either to the minimal template VSIX which has auto deployed or the changes have been made to the Nuget package without checking the template...
