### ISSUE TITLE
Disable tilt effect on navigation bar buttons

### ISSUE THREAD

**Issue by arutkowski00** [Windows-XAML/Template10#340]
Hi, I suggest removing tilt effect from buttons on navigation bar (hamburger menu), because it looks bad when bar is narrow, it doesn't match to behavior of hamburger button (3 stripes, no tilt) and embedded Windows apps (such as Weather or News) don't have this effect.

**Comment by mdtauk** [comment]
Or provide a SurpressTiltEffect property on the Hamburger Menu itself so developers can turn the effect off and on as they see fit

**Comment by arutkowski00** [comment]
Yep, good idea. Going further, maybe create SurpressTiltEffect as an attached property to any clickable/tappable object?

**Comment by JerryNixon** [comment]
Disable is enough. Submit a pull request?

**Comment by frostieDE** [comment]
How is the problem solved? I also want to disable the TiltEffect :)
