### ISSUE TITLE
empty null file created

### ISSUE THREAD

**Issue by SvenLauterbach** [Windows-XAML/Template10#343]
Hello,

the nuget targets file contains a command which create a empty "null" file in the project folder:

```
<Exec Command='xcopy "$(SourcePath)" "$(ObjPath)" /e/s/y >>null' />
```

I don't know what this >>null command should do, but if it should redirect stderr to 'null' then "2>nul" should be used.

**Comment by JerryNixon** [comment]
Please submit a pull request with this fix.
