### ISSUE TITLE
SplitView no longer collapses

### ISSUE THREAD

**Issue by ozzy1873** [Windows-XAML/Template10#344]
Just got the latest NuGet package and problems with spacing around the hamburger button have been fixed. However, a new problem has been introduced where the SplitView no longer collapses to 0 width when the window size is minimized.

**Comment by 9kon** [comment]
You just have to set your VisualStateNarrowMinWidth="0" and it works.

**Comment by 9kon** [comment]
actually after trying it out setting that brings back the spacing problems.

**Comment by ozzy1873** [comment]
Yep. And, while that collapses the SplitView, the SplitView no longer expands to normal width when sizing the window larger.

**Comment by JerryNixon** [comment]
Suggestions?

**Comment by JerryNixon** [comment]
#337 seems similar to this issue, too.

**Comment by vinodshinde** [comment]
This one is not reproducible.
Refer the Minimal example, it works perfectly.
