### ISSUE TITLE
HamburgerMenu.IsOpen binding doesn't work

### ISSUE THREAD

**Issue by arutkowski00** [Windows-XAML/Template10#345]
Everytime I try to bind IsOpen from HamburgerMenu to any other property (e.g. to IsEnabled from HamburgerButtonInfo) i see an error like this:
_The text associated with this error code could not be found.
Failed to assign to property 'Template10.Controls.HamburgerMenu.IsOpen'._

I tried setting different binding modes, binding to many other elements and properties and nothing works.

**Comment by ghost** [comment]
I can't seem to bind any property on the HamburgerMenu, or the buttons

**Comment by JerryNixon** [comment]
#337 is related to this and I would like to include it in the next version push.

**Comment by vinodshinde** [comment]
Hi Jerry,
I was trying to reproduce this issue. But was not able to.
The Hamburger open/closed is mostly controlled by Visual states and user clicking on the 3-line button.
Also, I was not able to find any relation of this bug with the #337  change.

Thanks

**Comment by JerryNixon** [comment]
Consider it a gremlin, then.
