### ISSUE TITLE
What are the plans about T10?

### ISSUE THREAD

**Issue by soeron** [Windows-XAML/Template10#347]
Is there some kind of roadmap or direction this project is heading to?
Are there any plans for IoC or incorporate new Prism goodies?

**Comment by MichaelPetrinolis** [comment]
"Template 10 is intended to remove the boilerplate garbage we all have to write over and over; it packs in as many time-saving lessons-learned as possible for app developers" (from http://aka.ms/template10) ,
so I don't see that the Library will integrate Prism or any IoC. Of course, we could add samples to demonstrate integration with Prism or our favorite DI container

**Comment by JerryNixon** [comment]
Like which Prism goodies?

**Comment by soeron** [comment]
Event aggregation, Regions ... I don't really know. Maybe I am missing IoC and that led me to this question.
@MichaelPetrinolis I think I can handle the IoC integration and no samples are needed, but thanks for your suggestion. I guess most of the developers can integrate IoC in their projects, but if there are plans for future integrations they can wait some time (like me) for example than refactoring the code when such feature is implemented.
A separate nu-get package introducing IoC integration like Prism is maybe a good idea. Since both packages (Template10 and Prism) are developed actively by Microsoft it seems natural for me that they can cooperate together flawlessly. But at the current state both provide 60% common functionality and mixing it together can lead to "dead" (unused) code or confusions.
I am closing this since I answered this question for myself. Keep up the good work.

**Comment by qmatteoq** [comment]
Hi @soeron , just a small correction: Prism isn't anymore developed by Microsoft. Now it's an open source project maintained by the community. You can read more on the official repository https://github.com/PrismLibrary/Prism
