### ISSUE TITLE
Template 10 wiki documentation pages need content

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#35]

**Comment by joshberry** [comment]
I'd be happy to help with the docs where I can. It would be really helpful if you could stub out one or two sections so there's a consistent format to follow your lead on.

**Comment by JerryNixon** [comment]
We'll get the first one written here shortly. Thanks Josh.

**Comment by JerryNixon** [comment]
Here's the first: https://github.com/Windows-XAML/Template10/wiki/Docs-%7C-Navigation-Cache

**Comment by rickgregory1905** [comment]
I'd be happy to help with the documentation. Since I'm walking through getting the template up and running perhaps I can add what I have been through.

**Comment by seesharprun** [comment]
I will try and see if I can write some documentation for the Converters.  I was intending to add an extra converter anyways using a PR.

**Comment by athrayee** [comment]
I would be happy to help with documentation. I am starting to explore the controls. I think the hamburger menu docs needs some update. The documentation talks about navigationserviceinfo but there is only buttonserviceinfo available unless i am missing anything.

**Comment by seesharprun** [comment]
Just added initial documentation for the converters.  More is coming after the DateTimeFormat and NumberFormat converters are merged.
