### ISSUE TITLE
HamburgerMenu Customization - NavButtonBackground should be NavButtonCheckedBackground

### ISSUE THREAD

**Issue by wleev** [Windows-XAML/Template10#352]
The current `HamburgerMenu` documentation is somewhat misleading when it comes to the customization options. The supplied customization example does not represent the resulting image.

The example style will look like the following rendering:
![capture](https://cloud.githubusercontent.com/assets/707932/11261599/83f752da-8eb9-11e5-9e35-ab1046130211.PNG)

This rendering is not in line with the example rendering or explanation in the documentation. To change the button background of the currently highlighted section you will need to change `NavButtonCheckedBackground` to the desired color.

On another note `NavButtonCheckedForeground` does not seem to be doing anything at this point.

If I missed anything please feel free to correct me.

**Comment by JerryNixon** [comment]
Please update the docs.
