### ISSUE TITLE
Unable to Bind Hamburger Menu to IsEnabled or Visibilty

### ISSUE THREAD

**Issue by ghost** [Windows-XAML/Template10#354]
I'm trying to bind my HamburgerMenu's IsEnabled property (because I need the user to login first), but it's just ignoring the binding. If I make the change using ViewStates, it crashes.

Any ideas how I can overcome this? I'm using MVVM

**Comment by JerryNixon** [comment]
Not sure. Perhaps they should be upgraded to dependency properties? Care to try?

**Comment by craigktreasure** [comment]
I am seeing the same, but i can only reproduce this when my Surface is docked in a multimon configuration. This does not occur undocked. If i remove my IsEnabled binding, the crash does not occur in the docked configuration.

System.NullReferenceException: Object reference not set to an instance of an object.
   at Template10.Controls.HamburgerMenu.<.ctor>b__6_1(DependencyObject d, DependencyProperty e)

As a workaround, i have changed my binding from {x:Bind to {Binding.

**Comment by JerryNixon** [comment]
I wish I could mark this one as gremlin.
