### ISSUE TITLE
Replace Sample NS With $safeprojname$

### ISSUE THREAD

**Issue by AntLaC** [Windows-XAML/Template10#357]
It would be nice to use the proper namespace within the project instead of having Sample as the namespace

**Comment by mizzle-mo** [comment]
Where are you seeing Sample instead of a proper namespace?  I just searched my entire solution for the word "Sample" in a new project created from the template and got 0 hits.

**Comment by darenm** [comment]
Early versions of the templates shipped with that error, so it could be you need to update your templates.

**Comment by Muhomorik** [comment]
@darenm , @JerryNixon 
I think he means the Blank and Mini templates that ships with Sample namespace.
Current [version](https://github.com/Windows-XAML/Template10/blob/master/Templates%20%28Project%29/Blank/Views/MainPage.xaml.cs) still uses it.

For example, when I create a new Template10 project called **UWP10_Blank3** I am expecting to see a UWP10_Blank3 workspace in my solution.
However, when I open my default MainPage.xaml I still see

```
<Page x:Class="Sample.Views.MainPage"
```

and MainPage.xaml.cs

```
 namespace Sample.Views
```

The code analysis tools complains that "Namespace doesn't correspond to file location...".

**Comment by darenm** [comment]
Ah - those aren't templates to use for creating new projects - install the visual studio extension for Template10: https://visualstudiogallery.msdn.microsoft.com/60bb885a-44e9-4cbf-a380-270803b3f6e5

This has the automation in place to replace the namespaces and app names, etc. using the new project wizard.

**Comment by Muhomorik** [comment]
@darenm 
Then the automation is broken, I've reproduced the problem in a short video below.
http://1drv.ms/1jcZ2xA

**Comment by LanceMcCarthy** [comment]
I can also confirm that "sample" and "sample.views" are the namespaces created by the VSIX's Blank app template.
