### ISSUE TITLE
ViewModelBase

### ISSUE THREAD

**Issue by luiscnsousa** [Windows-XAML/Template10#36]
As a suggestion, the ViewModelBase could inherit from abstract class BindableBase while also implementing INavigable.
from this:
public abstract class ViewModelBase : INavigable
to this:
public abstract class ViewModelBase : BindableBase, INavigable

And its INPC region could then be deleted.

**Comment by Nab0y** [comment]
In addition to BindableBase

public void Set<T>(ref T storage, T value, [CallerMemberName]string propertyName = null)
        {
            if (object.Equals(storage, value))
                return;
            storage = value;
            RaisePropertyChanged(propertyName);
        }

replace with

```
    public bool Set<T>(ref T storage, T value, [CallerMemberName]string propertyName = null)
    {
        if (object.Equals(storage, value))
            return false;
        storage = value;
        RaisePropertyChanged(propertyName);
        return true;
    }
```

This can be useful, for example in the ViewModel settings page

```
    private bool isSomeSettingOn;
    public bool IsSomeSettingOn
    {
        get { return isSomeSettingOn; }
        set
        {
            if (Set(ref isSomeSettingOn, value))
            {
                ApplicationData.Current.RoamingSettings.Values["SomeSetting"] = value;
            }
        }
    }
```

**Comment by JerryNixon** [comment]
Nice idea. I will commit it today.
