### ISSUE TITLE
Strange errors in VB project

### ISSUE THREAD

**Issue by MrWolfPST** [Windows-XAML/Template10#360]
In a simple VB UWP project, get Template 10 from Nuget, make necessary changes at app.xaml and app.xaml.vb.
Inside app.xaml add these resources:
&lt;Color x:Key="MyColor"&gt;Red&lt;/Color&gt;
&lt;SolidColorBrush x:Key="MyBrush" Color="{StaticResource MyColor}" /&gt;
Start application causes an unhandled exception with this message:
"Error HRESULT E_FAIL has been returned from a call to a COM component."
If I replace {StaticResource MyColor} with a color, in this case Red, all work fine.
I found a similar issue if I call my project "Universal".
I have a project ready for testing, but I can't attach zip file here.

**Comment by mizzle-mo** [comment]
Can you upload the project to your cloud file sharing provider and provide a link?

**Comment by JerryNixon** [comment]
Vb is not supported with T10. You can use it and it might work, but at your own risk.

**Comment by JerryNixon** [comment]
Sorry

**Comment by MrWolfPST** [comment]
There the zip of VB project.
I can understand missing support for the Visual Studio Template in VB.NET, but there isn't any valid technical reason because a compiled dll, then pcode, work fine with a language and not with other.
I think that there is a hidden issue here, but until it not occurs even in c #, I will continue to use the library in VB at my own risk.

Good life ;)

**Comment by MrWolfPST** [comment]
ops the link https://onedrive.live.com/redir?resid=80511E359E6ED3B7!782&authkey=!AL-t9dzFlshkq2Q&ithint=file%2czip

**Comment by artfuldev** [comment]
The same error occurs to me in a C# project with Universal being somewhere in the name of the project.
I am hence having to hardcode every color resource. :(

**Comment by JerryNixon** [comment]
The error occurs when "Universal" is in the Namespace or the Assembly file name?

**Comment by MrWolfPST** [comment]
I call my project Universal, than also rot namespace is universal, I have not try to change root namespace (sorry for my english)

**Comment by artfuldev** [comment]
My project's name is MyOrganisation.Universal so both the assembly name and the namespace 'contain' Universal

**Comment by JerryNixon** [comment]
I guess we can't have Universal in the name.
