### ISSUE TITLE
Continuum splash screen resolution seems incorrect scale

### ISSUE THREAD

**Issue by bc3tech** [Windows-XAML/Template10#363]
When hooking a device up to a large monitor (24") via Continuum, the Splash Screen's image is still using the `-100` version, which, when stretched to fill the launch window, pixelates very badly.

It seems that either
1. we need to check window sizes and make smart decisions to force `-200`, `-400` images (if they exist) or
2. the OS needs an update to make this work better

to get devs up & running _today_ i'm inclined to go for the first option. I'm not sure how the Office Apps are doing this so well, but it would be great to get some insight there if you can, @JerryNixon

**Comment by JerryNixon** [comment]
Continuum is a big issue we'll have to start testing.

**Comment by bc3tech** [comment]
Agreed. However it's good news that, for the most part, things seem to be working in my usage of Template10 (albeit heavily customized from early versions)

**Comment by JerryNixon** [comment]
I am not sure but that Template 10 cannot change the behavior you are seeing. Because the correct resource item should automatically be selected. But a phone has very high resolution, which means the issue should not be that the scaled image is not present, I think. The reason it is picking the wrong image seems, wrong. Do you think T10 could / should fix it?

**Comment by bc3tech** [comment]
This _seems_ like it might be fixed in Mobile build 10586.29. I'd like confirmation from others before closing, though.

**Comment by bc3tech** [comment]
From my MS contact:

```
we’ve now heard from the engineering team on this and they report that the expected behavior should be as follows:

1.       Before connecting to an external screen, only assets for the phone will actually be on the device – we only download necessary assets.
2.       User connects phone to external screen.
3.       The connection triggers app updates for any apps with available assets better suited for that screen.  The update takes place in the next ~24 hours.
```

So appears that after utilizing Continuum, we shouldn't rush to any judgement for 24hr after we've loaded the app on a target device.

**Comment by JerryNixon** [comment]
If this use case is important to you, I think you would be wise to ship a higher-quality splash image. Please remember, you can ship both the high and the low and the system will pick between them. You don't have to ship just one.

**Comment by bc3tech** [comment]
Yup the part that was alarming was that, although I **am** shipping all resolutions of splash screen imagery, it wasn't being picked up. We know now that this is because the app doesn't download that imagery w/ initial install on a mobile device. Instead it waits for a Continuum use of the app, then downloads those assets w/in the next 24 hours.
I don't like this (and have replied back to the MS rep) because the first impression of Continuum is then shoddy and not what a developer would ideally want his/her users to experience. Here's to hoping it's resolved in the future (eg: download high res assets all the time for Continuum _capable_ devices)
