### ISSUE TITLE
UWP app resizing Wide to Small  works a couple of times and start to act strangely

### ISSUE THREAD

**Issue by vRITHNER** [Windows-XAML/Template10#365]
Hi, we are using a Template10 UWP template to develop an Win10 UWP xaml app. 
One of our page view is a  Master Detail kind. 
We didn't add any fancy animation or anything else special to manage the adaptive UI to switch from desktop/small(phone) view.
When we resize the app on any Win10 desktop, it's basically working a couple of time but after, we are seeing some lags like if an animation loop start but was not ending correctly.
I recorded a small video to repro the issue. (More I resize the app, more the effects are bigger)
here is the OneDrive url: http://1drv.ms/1XxUSy0
Thanks for any help
-Vince

**Comment by JerryNixon** [comment]
First of all, yuck. That's just a terrible experience, huh? Without seeing any code, it's not going to be possible to help you. Are you seeing a similar behavior in the Master/Detail sample in GitHub? If not, then I would recommend you post your question on StackOverflow to get the most eyes on this and helping you.

**Comment by vRITHNER** [comment]
Hi, txs for your quick response. I'll try asap and I'll let you know...
Best Rgds
-Vince

**Comment by JerryNixon** [comment]
I just double checked the Master/Detail sample, and this is not happening. I don't think you are identifying a T10 issue, and it will be difficult to diag without any code at all.

**Comment by vRITHNER** [comment]
Hello Jerry, 
you absolutely right, After a deeper investigation, we found a event which was causing this pb.
Txs
-v
