### ISSUE TITLE
PageHeader SecondaryCommands

### ISSUE THREAD

**Issue by igorsky78** [Windows-XAML/Template10#368]
Is it possible to change the background color on the Secondary menu?
Also is it possible no to stretch the menu entire width of the screen?

![secondarycommands](https://cloud.githubusercontent.com/assets/8582700/11481096/fffa7ba2-974f-11e5-8110-87b5b68a6cef.png)

**Comment by JerryNixon** [comment]
Here's the solution for you.

``` XAML
        <CommandBar>
            <CommandBar.CommandBarOverflowPresenterStyle>
                <Style TargetType="CommandBarOverflowPresenter">
                    <Setter Property="Background" Value="Red"/>
                </Style>
            </CommandBar.CommandBarOverflowPresenterStyle>
        </CommandBar> 
```
