### ISSUE TITLE
Migrate Behaviors SDK to NuGet package

### ISSUE THREAD

**Issue by FrayxRulez** [Windows-XAML/Template10#370]
Microsoft just released new Behaviors SDK through NuGet.

Library must be updated to use it instead old SDK.

https://www.nuget.org/packages/Microsoft.Xaml.Behaviors.Uwp.Managed/

**Comment by JerryNixon** [comment]
Yep. Done.

**Comment by FrayxRulez** [comment]
Great, I'll sync my fork :) any eta for release on NuGet?
