### ISSUE TITLE
Back Button and Ellipsis only visible on hover

### ISSUE THREAD

**Issue by keneniah** [Windows-XAML/Template10#371]
The Back Button and the Ellipsis in the Top Bar are only visible if you hover over them.
Is this a settings issue (on my behalf) or a bug?

**Comment by JerryNixon** [comment]
Good question. Is this a theme issue? I mean, is it a light font until you hover or is it completely invisible? And by invisible is it collapsed (meaning there is no footprint) or is it just invisible (like opacity=0)?

**Comment by keneniah** [comment]
I'm very sorry, I made a stupid copy and paste mistake in custom.xaml which caused the behaviour. Everything is alright and there is no bug.
