### ISSUE TITLE
Rename ModalDialog.IsModal to IsOpen

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#379]

**Comment by JerryNixon** [comment]
I realize this is a breaking change, but this controls is brand new, too.

**Comment by JerryNixon** [comment]
Because this is a breaking change, this is saved to 1.1.0

**Comment by bc3tech** [comment]
could we `[Obsolete("Use IsOpen", false)]` the old way and put the new one in just so we can RTM it quicker?
