### ISSUE TITLE
Introduce empty constructor option to Shell.xaml.cs

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#380]
@ViktorBergman this is for you. For everyone else, this allows you to do this:

``` csharp
// runs even if restored from state
public override async Task OnInitializeAsync(IActivatedEventArgs args)
{
    // setup hamburger shell
    var frame = new Frame();
    Window.Current.Content = frame;
    if (frame.Navigate(typeof(Views.Shell)))
    {
        var nav = NavigationServiceFactory(BackButton.Attach, ExistingContent.Include);
        var page = frame.Content as Views.Shell;
        page.SetNavigationService(nav);
    }
    await Task.Yield();
}
```

Resulting visual tree looks like this:

![snip_20151202132006](https://cloud.githubusercontent.com/assets/1749983/11542997/83f94a0c-98f7-11e5-81e1-6e56548e6238.png)

Why would you want to do this? Because it is required for the MS Band SDK to work.

**Comment by ViktorBergman** [comment]
@JerryNixon Thanks for putting time and effort into finding a solution for this! You rock!
