### ISSUE TITLE
Replace await Task.Yield() with return Task.CompletedTask

### ISSUE THREAD

**Issue by pekspro** [Windows-XAML/Template10#382]
In the code I found a lot of `await Task.Yield()`. There is also code like `await Task.Delay(0)`. 

If the purpose of this code is just to remove compiler warnings - isn’t better to use return `Task.CompletedTask` instead? It’s suggested by this thread: http://stackoverflow.com/questions/4245968/create-a-completed-taskt.

**Comment by JerryNixon** [comment]
Good idea.

**Comment by schuettecarsten** [comment]
There is a difference between await Task.CompletedTask and await Task.Yield().

"await Task.Yield()" really switches the context and makes sure that other tasks have time to run on the underlying thread. Task.CompletedTask will simply return a completed task and the awaiter is able to optimize this. So, if you use "await Task.Yield()" to remove compiler warnings, it is okay to change to "await Task.CompletedTask". But if you really want to yield the current task and let other tasks run, for example if you have to wait/poll a queue or something like this, use "await Task.Yield()".

**Comment by pekspro** [comment]
Nice :-). But I think you should use `return Task.CompletedTask` instead of `await Task.CompletedTask` :-).

In `NetworkAvailableHelper.IsInternetAvailable` the `await` command should be removed completely (if this function needs to be async – doesn’t look like it).
