### ISSUE TITLE
Why is this happening can anyone suggest a reason

### ISSUE THREAD

**Issue by alanb6448** [Windows-XAML/Template10#384]
Two equally empty viewmodel files , one gets accepted as a datacontext the other does not?  I can see no difference  except the one that works I created before updateing visual studio today.The file properties seem the same for both. My apologies if this turns out to be a newbie error but I only recently tried Template 10.

Alan

![2015-12-03](https://cloud.githubusercontent.com/assets/16083975/11569172/5421d1fe-99e8-11e5-944f-fe1f392a23e3.png)
![2015-12-03 4](https://cloud.githubusercontent.com/assets/16083975/11569176/5ca7f7a4-99e8-11e5-8765-291785db17c5.png)

**Comment by alanb6448** [comment]
Remamed the file that was accepted and it is now no longer accepted. By the way I am using vs community.

**Comment by JerryNixon** [comment]
Community should not make a difference. In one screen shot you are using a custom ViewModelBase. Are you still doing that anywhere? If so, then I might assume it is in there.

**Comment by alanb6448** [comment]
Ok for some reason I know not why his problem has gone away
