### ISSUE TITLE
PageHeader has issues displaying secondary commands

### ISSUE THREAD

**Issue by oadugmore** [Windows-XAML/Template10#385]
When you expand the PageHeader control, it cuts off secondary commands if they take up a certain amount of screen space. I've only been able to reproduce on Mobile. I've confirmed with an unmodified Template10 Minimal project. Easiest to reproduce if you put your device in landscape orientation.

**Comment by MichaelPetrinolis** [comment]
Hi, if you replace the page header with a command bar, it has the same behavior? Page header is just a subclass of command bar.

**Comment by oadugmore** [comment]
No, regular command bar works fine.

**Comment by JerryNixon** [comment]
Hmm. Since `class PageHeader: CommandBar` this should not be happening.

**Comment by mvermef** [comment]
I have a screen shot of this from my mobile (920 running 10586).  It occurs if you navigate from one page back to the page with the secondary command bar and open the command bar while the cursor is in the text box without closing the keyboard first. It will also occur on the first navigation to MainPage
Subsequent menu activations do not yield the truncated menu.
![wp_ss_20151204_0002](https://cloud.githubusercontent.com/assets/2018777/11598351/0609c324-9a87-11e5-9812-f9a0accb4dfb.png)

**Comment by oadugmore** [comment]
Here's a screenshot from my Icon. I tried removing the Template 10 NuGet package and re-adding it but that didn't fix the problem.
![wp_ss_20151204_0001](https://cloud.githubusercontent.com/assets/13210085/11604089/3f39104e-9a9d-11e5-8e06-9a7ab99f0e65.png)

**Comment by HassanElZarkawy** [comment]
I also get the same issue that @mvermef and @oadugmore get! However if you close and reopen the menu it'll work just fine! weird

**Comment by callummoffat** [comment]
I am seeing this behavior as well.

**Comment by MichaelPetrinolis** [comment]
Please check if [this PR](#398) fixes the issue

**Comment by oadugmore** [comment]
~~#398 makes the PageHeader smoother, fixing a minor stuttering problem I was also noticing, but it does not fix the truncation issue for me.~~

**EDIT:** #398 fixes the issue

**Comment by MichaelPetrinolis** [comment]
In order to check the fix, please merge the latest from upstream in your fork and then merge the PR. Then run the minimal from the solution.

**Comment by oadugmore** [comment]
Oh, okay -- see, I barely know how to manage NuGet packages, much less any of this GitHub sorcery -- but eventually I figured out how to merge your changes into a fork and it does appear to fix the issue. I don't know how long it usually takes to approve changes, but for what it's worth, my opinion is that this fix should be approved quickly.
