### ISSUE TITLE
AdaptiveTriggers on Page after Navigated to

### ISSUE THREAD

**Issue by ghost** [Windows-XAML/Template10#389]
Maybe I'm being daft (probably), but I have a MainPage (using Template10 with `HamburgerMenu` and `ShellPage`) that has an `AdaptiveTrigger` that re-aligns my controls inside a `RelativePanel` depending on the size of the screen.

When I navigate to this page and resize, my `AdaptiveTrigger` is not firing on the MainPage. If I take my AdaptiveTrigger and `RelativePanel` into a blank (non-Template10) app, it works fine.

Is this because the MainPage is loaded into the `ShellPage` and therefore it doesn't resize when changing the size of the app? If so, how can I get my triggers to work?

**Comment by JerryNixon** [comment]
When you resize the page the adaptive trigger does not fire? There's no way to circumvent the window.sizechanged event raised by UWP, so I think you need to zip this up and email it to me. jerry@microsoft and I will take a look at it. Sounds like it might be a syntax thing, except you said you just copy/pasted the XAML from one to another. Sheesh. I'll take a look though.

**Comment by ghost** [comment]
Hi Jerry,

No problem, I've got a couple of projects zipped up. One works without Template10 (TestBed), one doesn't (AdaptiveTriggerTest)

Seems like I can't attach a zip file...could you drop me your email address at all?

Craig

**Comment by mvermef** [comment]
his email was embedded in last response.^^

**Comment by MichaelPetrinolis** [comment]
Hi @JerryNixon , I have a Size Changed trigger that I could contribute, but I don't know where I should add in in T10, and if T10 should provide adaptive triggers like behaviors.

**Comment by JerryNixon** [comment]
We do not have a trigger library. Not just that, adaptive triggers are far more sophisticated than you think. If you have three triggers, a 320, 500 and 1020 - and your screen size is 501, the 500 adaptive trigger and the 320 will not! Do you see why that is tricky? It's because the adaptive trigger has a way of determine its state group and assessing the best (meet the requirement). Does this make sense?

**Comment by MichaelPetrinolis** [comment]
Sure, no problem 😊
If in the future is decided to add a triggers lib, I will make a PR. 
What I am talking about is a ControlSizeTrigger which defines state triggers for the referenced control (example a UserControl that is used as an ItemTemplate) and applies them when the control's size is changed.

**Comment by ghost** [comment]
Ok - ignore my ramblings, apologies to everyone. I put my visualstates inside the grid the controls are located, and hey presto!
