### ISSUE TITLE
Build error when using Template10 version 1.0.9

### ISSUE THREAD

**Issue by keneniah** [Windows-XAML/Template10#390]
When I use the latest master of Template 10 (pull via GitHub, compile in VS, using local Nuget source) I get the following error message when I try to compile my project:
Der Typ "Interaction" ist in "Microsoft.Xaml.Interactivity, Version=12.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" und "Microsoft.Xaml.Interactivity, Version=1.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" vorhanden, 
meaning that a type is defined twice. Does anyone have an idea how to solve this issue?
Thank you for your help and time in advance.

**Comment by JerryNixon** [comment]
Thanks. T10 does not support 10586 yet.

**Comment by JerryNixon** [comment]
Please make sure you remove your reference to the Behaviors Extensions SDK.

**Comment by keneniah** [comment]
Thanks, that solved the issue.

**Comment by callummoffat** [comment]
Template10 looks to be compatible with the 10586 SDK as of the latest Git pulls. It certainly compiles in Release mode, and runs absolutely fine. I'm testing this with a production app, BTW.

**Comment by punkouter2021** [comment]
It doesn't compile for me.. I get a couple 1000s errors and this in the output (using latest everything) 

[Failure] Could not find file 'C:\Users\punko\Downloads\vsTemplate10-master\Template10-master\Samples\Converters\obj\x86\Debug\App.g.i.cs'.
[Failure] Could not find file 'C:\Users\punko\Downloads\vsTemplate10-master\Template10-master\Samples\IncrementalLoading\IncrementalLoading\obj\x86\Debug\App.g.i.cs'.
[Failure] Could not find file 'C:\Users\punko\Downloads\vsTemplate10-master\Template10-master\Samples\Settings\obj\x86\Debug\Views\MainPage.g.i.cs'.
[Failure] ....

**Comment by punkouter2021** [comment]
oops forgot to move it away from Any CPU.. Moved it to x86 and BusyIndicator project does not run but I deleted that
