### ISSUE TITLE
Blank Screen after resume on Windows Mobile 10

### ISSUE THREAD

**Issue by keneniah** [Windows-XAML/Template10#391]
When I start my app on my Mobile Phone running the latest Windows 10 Mobile Insider build, suspend it and resume it again, I only see a black screen and the hamburger button in the upper left corner. I can use the menu and navigate to all pages. All of them work except for the main page which shows just the black screen. Any suggestions how to fix this? Thank you for your help.

**Comment by keneniah** [comment]
I found out that the problem is that one of my methods is not being called. I placed it inside of OnNavigatedTo because I thought that thís method is always being called on resume. That does not seem to be true. Where can I place my method call so that I can be sure that it will always be called on resume? That would resolve my issues.

**Comment by HassanElZarkawy** [comment]
Try placing your code in Loaded event. OnNavigatedTo will always fire when an actual navigation happens between two pages inside a frame. In your case, the page has been activated not navigated to. hopefully that made sense.

**Comment by keneniah** [comment]
I found out that the reason for this was a different one. I put my code inside of 
                 if (State.Any()) 
in OnNavigatedTo and this code block is not being called. 
I close this thread because I have to investigate further. Thanks for your help, anyway.

**Comment by JerryNixon** [comment]
Thanks for the follow-up
