### ISSUE TITLE
Manually updating HamburgerMenu highlighted button #372

### ISSUE THREAD

**Issue by darshanrampatel** [Windows-XAML/Template10#395]
Following on from #372, I've not been able to get this to work using the IsChecked property.

Shell.xaml

```
                <Controls:HamburgerButtonInfo x:Name="MyAccountPageButton" ClearHistory="False" PageType="views:AccountPage">
                    <StackPanel Orientation="Horizontal">
                        <FontIcon Width="48" Height="48" FontFamily="Segoe MDL2 Assets" Glyph="&#xE82D;"/>
                        <TextBlock Margin="12,0,0,0" VerticalAlignment="Center" Text="Account" />
                    </StackPanel>
                </Controls:HamburgerButtonInfo>
```

Shell.xaml.cs

```
    public static Shell Instance { get; set; }
    public static HamburgerMenu HamburgerMenu { get { return Instance.MyHamburgerMenu; } set { } }
    public static HamburgerButtonInfo AccountPageButton { get { return Instance.MyAccountPageButton; } set { } }
    public void HighlightButton()
    {
        HamburgerMenu.NavAreaBackground = new Windows.UI.Xaml.Media.SolidColorBrush(Colors.Red);
        AccountPageButton.IsChecked = true;
    }
```

AnotherPage.xaml.cs

```
    public void ToggleButton() {
        Shell.Instance.HighlightButton();
    }
```

When the HighlightButton method is called, the NavAreaBackground successfully changes to red. When the IsChecked property is set to true, the active page switches back to the PageType, which takes you away from the page you are on.

I have also tried using the below

```
HamburgerMenu.PrimaryButtons[index].IsChecked = true;
```

but with no success.

**Comment by JerryNixon** [comment]
Yep. It does not work. Still working.

**Comment by JerryNixon** [comment]
Nope. Can't figure this one out. May not make it in time for 1.0.9.
Would love some help on this one, too.

**Comment by JerryNixon** [comment]
So far, I have added a AutoHighlightCorrectButton property to the HamMenu. Still no.

**Comment by mitkodi** [comment]
HamburgerMenu.Selected works fine for me to select a button in code.
To automate the processes I added: an attribute (NavigationGroupAttribute with property GroupName); a property (GroupName) to HamburgerButtonInfo; in HamburgerMenu.HighlightCorrectButton, if not button is found by page type and parameter, fallback to a button based on GroupName.

**Comment by mitkodi** [comment]
I found out why my scenario works, but not the original one. Setting HamburgerMenu.Selected (based on attached to the page attribute) in HamburgerMenu.HighlightCorrectButton happens before the current navigation is finished, so navigation to the page corresponding to the newly selected button doesn't actually happens.
Generally I think that it's better to set relation between navigation buttons and pages at view level rather than in viewmodel.

**Comment by mitkodi** [comment]
I posted pull request #434 
Test scenario. Set NavigationGroup for an existing HamburgerButtonInfo, add a page and attach to the class NavigationGroupAttribute with the same GroupName, navigate to this page manually (in code).

**Comment by JerryNixon** [comment]
We want a diff approach.

**Comment by JerryNixon** [comment]
Okay. The solution is to use HamburgerMenu.Selected. I have changed IsChecked to internal so developers don't attempt to set it this way anymore.

**Comment by mitkodi** [comment]
What about a small enhancement, that will allow to select a button from anywhere (not only from Page.OnNavigatedTo)? In addition it could be extended to make selection by some sort of string key, not only by passing an instance of button info.
