### ISSUE TITLE
Resuming app on Windows Phone 10 display infinite "please wait" ring 

### ISSUE THREAD

**Issue by vRITHNER** [Windows-XAML/Template10#397]
Hi, 
I was thinking this issue was in our code, but I just deploy the "Mimimal" template to both my Lumia 1520 and also a Lumia 950 both running latest WP10 insider preview version.
To repro it, 
-just launch once the app. 
-Press "Home"
-launch again the app.
the app just not display a white page containing the splash screen with a "please wait" ring running forever.
I have recorded with my web cam 2 videos (1 with minimal template and 1 with our apps doing same issue); both are copied in our OneDrive: http://1drv.ms/1YVpFY3
This is a show stopper for us
Thanks for any help
-Vince

**Comment by keneniah** [comment]
You will have to wait for version 1.0.9. In that version the issue is fixed. Otherwise you can download it here from GitHub and build it yourself.

**Comment by vRITHNER** [comment]
I just downloaded the latest source and added as libs rather than nuget in our project but this changes nothing. It works mabe 1 or 2 times in a row  (means app resume correctly) but then the splashscreen opens forever...

**Comment by vRITHNER** [comment]
We saw also another issue concerning the resuming of apps on the phone. On resume, apps restart on the first page like if it was not a resume. it should resume on last opened page like the way works with standard universal app template. This is not only in our project. I just tested with T10 BottomAppBar and Minimal sample; they both resume on start page.

**Comment by keneniah** [comment]
You're absolutely right. The app is always resuming on the start page and not on the last opened page and I also see the splashscreen forever after a few tries. Seems like the bug hasn't been fixed yet. I didn't notice that at first look. Hopefully someone can look into this...

**Comment by keneniah** [comment]
And the big problem is that this never happens in debug mode. When the device is connected and I run the application I can suspend and resume as often as I want, everything works just fine. When I unplug the cable the splash screen stays forever when I navigate to a page, suspend the app and resume it again.

**Comment by 9kon** [comment]
Yes it is still happening..
looking that output when having the app deployed as release on a device gives the following exceptions for me when i try to return to the app using the icon.

Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.Threading.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll

**Comment by 9kon** [comment]
I tried adding 

if (exception is TaskCanceledException)
                {
                    e.Handled = true;
                    return;
                }

To my void App_UnhandledException(object sender, UnhandledExceptionEventArgs e)
This fixes the problem for me, but is not really a solution.. :-)

**Comment by calloncampbell** [comment]
I'm also seeing this issue on Win10 Mobile and on occasion Win10 Desktop.

**Comment by JerryNixon** [comment]
Any @Windows-XAML/contributors have any help on this one?

**Comment by darenm** [comment]
So I have noticed some quirks coding on Windows 10 mobile especially with fast resume, etc. I'm working on shipping an app right now (not based on T10) - once I get that out of the door I'll see if I can track down the glitches with Mobile.

**Comment by chosenonehacks** [comment]
Add this two methods to your app.xaml.cs, and it should help, remove them when 1.0.9 will hit release.

```
public static void ClearNavigationServices(Window window)
        {
            var wrapperToRemove = WindowWrapper.ActiveWrappers.FirstOrDefault(wrapper => object.ReferenceEquals(wrapper.Window, window));
            if (wrapperToRemove != null)
            {
                wrapperToRemove.NavigationServices.Clear();
            }
        }

        public override Task OnSuspendingAsync(object s, SuspendingEventArgs e)
        {
            if (Windows.System.Profile.AnalyticsInfo.VersionInfo.DeviceFamily.Equals("Windows.Mobile"))
            {
                ClearNavigationServices(Window.Current);
            }
            return base.OnSuspendingAsync(s, e);
        }
```

**Comment by DominikErnst** [comment]
Thank you xorch ... made my day!

**Comment by JerryNixon** [comment]
I think this solution makes Resume not work anymore, right?

**Comment by JerryNixon** [comment]
@xorch, in the current code base I have removed WindowWrapper.ClearNavServices() which might be what you are relying on in your comment above. Could you help me understand the issue here?

**Comment by bc3tech** [comment]
note the relationship between the fix here and #457

**Comment by naweed** [comment]
I tried the suspend and resume on desktop and it works perfectly fine. I will try it on mobile as well. Hope the behavior will be same. Will update you after testing.

**Comment by luiscantero** [comment]
I've been doing some tests trying to fix this and so far this seems to work also when resuming (tested only on Desktop):
public override async Task OnStartAsync(StartKind startKind, IActivatedEventArgs args)
        {
            // navigate to first page
            var nav = WindowWrapper.ActiveWrappers.FirstOrDefault(wrapper => object.ReferenceEquals(wrapper.Window, Window.Current)).NavigationServices;
            if (nav.Count > 1)
            {
                nav.Remove(nav[0]);
            }

```
        NavigationService.Navigate(typeof(Views.MainPage));
        await Task.CompletedTask;
    }
```

**Comment by bc3tech** [comment]
What's the functional difference between this and the Clear logic in place today?

**Comment by luiscantero** [comment]
The clear logic doesn't let you resume to a page other than main (e.g. after being suspended in tablet mode). The logic that I posted lets you resume and also start new.

**Comment by bc3tech** [comment]
gotchya. how does it work on mobile?

**Comment by luiscantero** [comment]
I've only tested in using the mobile emulator (10586) and it behaves exactly as the desktop. To elaborate some more on what I ment by "it doesn't let you resume" if you use "Clear()":
- Let's say you have an app called ABC with 3 pages: Main, Categories and Products.
- In tablet mode, you navigate from Main to Categories and from there to Products and back again.
- Next, you switch to another app XYZ to put ABC in suspended state.
- When you return to ABC (e.g. using Alt or Windows + Tab), it resumes on Categories, but from there you cannot navigate to Products or anywhere else anymore because the navigation service has been cleared.

If you use my snippet, you can resume on Main, Categories or Products or even restart the app though the tile icon (even while being suspended) and everything behaves as expected.

**Comment by JerryNixon** [comment]
Resolved.
