### ISSUE TITLE
Does not support multiple frames

### ISSUE THREAD

**Issue by Chaotic-Limited** [Windows-XAML/Template10#4]
Template10 does not currently support having more than just the root frame for an app.  This means if you have a splitview or uniform menu control and sub-pages, you cannot save the state of any of those pages, nor can you use the viewmodel framework as the Navigation events do not fire.  This critically limits the usefulness of this framework.

Otherwise - awesome and huge potential.

**Comment by JerryNixon** [comment]
Are you requesting support for multiple Frames?

**Comment by Chaotic-Limited** [comment]
Hi Jerry!  Well, I was working to one of the project templates recommended/built by MS: “NavigationMenuSample” that uses an AppShell and then sub-pages for content all in another frame.  It seems a sensible approach, so yes support for multiple frames would be fantastic and make the Template10 very robust.  Thank you!

**Comment by JerryNixon** [comment]
Okay. Will just need a second invocation of the navigation service. Probably easiest to subclass the bootstrapper. Can you send me a link to the sample so I can understand the use case?

Best regards,
Jerry Nixon

Sent from my Windows Phone.
Please forgive typos and brevity.

**Comment by Chaotic-Limited** [comment]
Awesome, thanks very much Jerry!  Here is a link to the zipped sample, unedited, on my OneDrive.  This doesn’t implement Template10, it is just a navigation sample.

From memory of when I looked at this I think you’ll need to make sure the new Bootstrapper contains a collection of NavigationService, as I think currently it forces the app root frame for its single reference.  From there a suspend event can loop through the navigation services and save all the state just the same – except maybe with ID dependent keys to prevent accidental overwriting… you’re the pro, though! ☺

https://onedrive.live.com/redir?resid=256A7AAE20E85461!57906&authkey=!ALrhBZqulLbYDLY&ithint=folder%2czip

**Comment by darenm** [comment]
If additional windows are going to be created, you need multiple cached dispatchers too

**Comment by JerryNixon** [comment]
You're right. Well need to move Dispatch from Bootstrapper into Frame façade, I think. This is pretty much an edge case but I think it can be worked in without creating any new implementation complexity. Models that cross frames will potentially throw cross thread exceptions in their property changed events of both frames data bind to the same property. Developers will have to be responsible for that on their own. Synchronizing through messaging would likely be how I would solve that. But that's an edge case of an edge case. Still, it would work.

Best regards,
Jerry Nixon
