### ISSUE TITLE
Border on the right of the pane view

### ISSUE THREAD

**Issue by frostieDE** [Windows-XAML/Template10#400]
When opening the pane of the SplitView, there is a (almost) white border at the right.

Is there a reason, why this border exists? I do not like it as it does not match any official app made by MS.

I can (a) remove this border or (b) make it at least customisable (which includes reducing the border thickness to 0 to make it invisible)

**Comment by JerryNixon** [comment]
Hmm. I agree. Let me look into what to do.

**Comment by frostieDE** [comment]
I can also take a look at this at the weekend ;-) The colour of the seperator does not match the colour used by offical apps neither :P

**Comment by JerryNixon** [comment]
Okay. Added PaneBorderBrush and PaneBorderThickness. Defaults are as they are today. As a result, this should be a transparent change to developer who do not care about it, but enable those who do.

**Comment by JerryNixon** [comment]
What is the official sep color? Pull request that.

**Comment by frostieDE** [comment]
Thanks :)

I am not sure how those colours are computed (maybe they are registered as `ThemeResource`), but here they are:
- dark: #404040
- light: #d3d3d3
- high contrast: #ffffff

Taken from the Goove Music app ;-)
![wp_ss_20151211_0004](https://cloud.githubusercontent.com/assets/3764924/11732382/eafedf16-9fa3-11e5-9eb1-ca3a13df5e32.png)
![wp_ss_20151211_0003](https://cloud.githubusercontent.com/assets/3764924/11732383/eb0226e4-9fa3-11e5-8965-5f330455b324.png)
![wp_ss_20151211_0002](https://cloud.githubusercontent.com/assets/3764924/11732384/eb039038-9fa3-11e5-971e-88b94e849fda.png)

I will try to implement thouse colours tomorrow (GMT+2 :P)
