### ISSUE TITLE
Question regarding OnNavigatedFromAsync

### ISSUE THREAD

**Issue by keneniah** [Windows-XAML/Template10#401]
Hello,

shouldn't OnNavigatedFromAsync be called every time my app is being suspended? At least the parameter "suspending" is suggesting this. But when I set a breakpoint and change the state to suspended this method is not being called. Am I doing something wrong or is there another method which I can use to preserve my state. Thanks for your help and time.

**Comment by keneniah** [comment]
There must have been a flaw to my debugger last night, now OnNavigatedFromAsync is called every time I suspend the app. Don't know what happened last night, maybe I was too tired ;-)
But one more question: how can I achieve that the app navigates to the last open page on resume. There must be a method in App.xaml.cs for this but I can't figure out which.

**Comment by JerryNixon** [comment]
Terrific. Thanks.
