### ISSUE TITLE
Latest version throws compilation error

### ISSUE THREAD

**Issue by keneniah** [Windows-XAML/Template10#402]
When I try to compile the latest sources I get the following error message:
Assembly "Template10Library" with identity "Template10Library, Version=1.0.5822.17941, Culture=neutral, PublicKeyToken=d74e748b43bf937b" uses "Microsoft.Xaml.Interactivity, Version=1.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" with a higher version than the referenced assembly "Microsoft.Xaml.Interactivity" with identity "Microsoft.Xaml.Interactivity, Version=1.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35".  
I translated the error message so I hope it's understandable.
Does anybody know how to fix this? Thank you very much.

**Comment by callummoffat** [comment]
Don't forget to get the latest version of the Behaviors SDK from Nuget, and remove any old references to the original 8.1 SDK.

**Comment by Spencerooni** [comment]
Just had the same problem, thanks for posting the solution! Installing the new Behaviours SDK from nuget fixed it. Link here for anyone else:
https://www.nuget.org/packages/Microsoft.Xaml.Behaviors.Uwp.Managed/
