### ISSUE TITLE
Hiding HamburgerMenu buttons causes crash on navigation

### ISSUE THREAD

**Issue by callummoffat** [Windows-XAML/Template10#404]
I've discovered that hiding hamburger buttons (ie: during a setup wizard) will cause a NullReferenceException upon navigating to a page to which a hidden button is attached. HamburgerMenu attempts to activate the IsChecked method, but for some reason can't find the hidden button. It then chucks a wobbly.

**Comment by JerryNixon** [comment]
Hmm. IsChecked seems to have several issues. For example, setting IsChecked manually does not work anymore. I've looked into it. Nothing good yet. This might be related. Is this an error with 1.0.8 or GitHub?

**Comment by callummoffat** [comment]
This is an issue on Github, so it will likely affect 1.0.9.

_Callum Moffat_
App Developer
Windows 10 Enthusiast

---

Keep track of the costs of your vehicles with Petrolhead!
https://www.microsoft.com/en-us/store/apps/petrolhead/9nblggh1rjqt?cid=phmailsig

**Comment by JerryNixon** [comment]
Thanks @callummoffat Callum, I am chasing other enhancements. I would like to have this corrected in 1.0.9. Could you take a look and see what might be causing this?

**Comment by callummoffat** [comment]
OK then, will do.

**Comment by callummoffat** [comment]
This bug appears to have been fixed in the latest upstream version.
