### ISSUE TITLE
Page.BottomAppBar causing issues with hamburger

### ISSUE THREAD

**Issue by GJKuz** [Windows-XAML/Template10#406]
Replacing Page.BottomAppBar with below in BottomAppBar sample, results in weird hamburger menu behavior once state trigger fires for Wide width. The settings button gets buried under the command bar and the only way to bring it up is by clicking the "..." on command bar. 

``` XAML
<Page.BottomAppBar>
        <CommandBar x:Name="bottomBar" Visibility="Visible">
            <AppBarButton Label="Calculate" Icon="Calculator"/>
            <AppBarButton Label="Clear"  Icon="Clear"/>
            <AppBarButton Label="Home"  Icon="Home"/>
            <CommandBar.SecondaryCommands>
                <AppBarButton Label="Launch Settings"  />
            </CommandBar.SecondaryCommands>
        </CommandBar>
    </Page.BottomAppBar>
```

I also have another issue. I only want to display BottomAppBar for narrow state. When the state trigger fires for normal width, I want to switch BottomAppBar with TopAppBar. When I do that the hamburger control, doesn't stretch automatically and leaves a 48x48 area at the bottom which is in white. Really appreciate some guidance.

**Comment by JerryNixon** [comment]
There is a bug, this works with AppBar but not CommandBar.

**Comment by GJKuz** [comment]
Thanks Jerry for the update.

**Comment by JerryNixon** [comment]
Okay, the native functionality to hand the BottomAppBar has been removed from the library. Why? Because the work to handle it is so trivial, it did not make sense to include that complexity in the control. I have updated the BottomAppBar sample to help you implement it yourself.

**Comment by DanTheManSWE** [comment]
The "fix" in BottomAppBar sample is not working correctly on phones, or when the window is in VisualStateNarrow. Since the PaneWidth is hardcoded at 48 pixels, the BottomAppBar will always be 48 pixels shorter even when the menu is closed, and changing the code to 0 pixels would make the BottomAppBar overlap the HamburgerMenu when it's in VisualStateNormal. Wouldn't it be better to change the height of the HamburgerMenu instead?

**Comment by DanTheManSWE** [comment]
Not sure if you read this post when it's closed, but one way to solve it could be to expose PaneContent Margin property. I just tried to change that margin to 0,48,0,48, and it works fine.

**Comment by JijoBose** [comment]
I found a Workaround for the **BottomAppBar** issue.
Make sure you create another PageHeader Control and set the **PageHeader control** as **'AlignBottomWithPanel="True"**

Refer the Code Below.

``` sh
        <controls:PageHeader x:Name="pageFooter" RelativePanel.AlignLeftWithPanel="True"
            RelativePanel.AlignRightWithPanel="True"
            RelativePanel.AlignBottomWithPanel="True">
            <!--  primary commands  -->
            <controls:PageHeader.PrimaryCommands>
                <AppBarButton Icon="Accept" Label="Settings" />
            </controls:PageHeader.PrimaryCommands>
        </controls:PageHeader>
```

![untitled](https://cloud.githubusercontent.com/assets/13100108/16360758/d9397b32-3b8f-11e6-9ad3-3471e2a7fdd2.png)
