### ISSUE TITLE
Wildcarded nuget reference to Behaviors SDK causes build failure on some machines

### ISSUE THREAD

**Issue by schuettecarsten** [Windows-XAML/Template10#407]
One some machines, I get the exception since BehaviourSDK Nuget reference was changed from 1.0.2 to 1.0.*:

```
[...]\Template10\Template10 (Library)\project.json(0,0): Error:
Microsoft.Dnx.Runtime.FileFormatException: '1.0.*' is not a valid version string.
---> Microsoft.Dnx.Runtime.FileFormatException: '1.0.*' is not a valid version string.
---> System.ArgumentException: '1.0.*' is not a valid version string.
```

**Comment by JerryNixon** [comment]
Could you try changing it to "1.0.3" and seeing if the error continues? I can't imagine why this is happening for some and not for others (like me).

**Comment by schuettecarsten** [comment]
Yes, it works when using 1.0.3. Seems that specific versions of Nuget or dnu fail on "dnu restore" when runnding builds from command line.

**Comment by schuettecarsten** [comment]
Jerry, just to let you know: The problem occurs when building Apps from the command line. It does not happen when using Visual Studio. Unfortunately, this breaks all kind of continuous integration and automated testing that depend on nightly builds, automated deployment and so on.
