### ISSUE TITLE
How to solve "Known Issues with Template10"

### ISSUE THREAD

**Issue by stefanwil** [Windows-XAML/Template10#412]
I am not very familiar with handling different SDK versions in Visual studio.  In the end of the wiki page to Template10 it says

"Known Issues with Template10
1.Template10 is not currently compatible with UWP1.1 (SDK version 10586). It is necessary to target the older SDK version to build production apps using Template 10, at least for the moment.
"
What is the procedure for targeting the older SDK version but still have SDK version 10586(UWP1.1) installed. Do I need to install another SDK or do I need to uninstall UWP1.1 or? . Describe procedure please.

**Comment by callummoffat** [comment]
Just keep the default project settings. 10240 is the only targeted version by default.

**Comment by stefanwil** [comment]
Thank you, I did not fully explain my problem :
When I create a new project using the Template10 I get a message: The project requires a platform SDK(UAP, Verion=10.0.10240.0) that is not installed. Please visit.....". 
Is it possible to install this SDK but still keep the newer (or some other solution)?

**Comment by stefanwil** [comment]
I checked Visual studio installation setup and it was possible to select that both 10240 version of SDK and the new one should be included. I think this will solve problem. Thank you for your help
