### ISSUE TITLE
With Win10 Mobile, the setting for show Back Button in title should only be visible to Win10 Desktop

### ISSUE THREAD

**Issue by calloncampbell** [Windows-XAML/Template10#417]
Not sure if this should be part of Template10 or just something Win10 developers should be aware of and that is if you have specific settings that are not related to Win10 Mobile (like showing the back button in the title), this should be hidden for mobile and only shown when appropriate.

Right now if I use the Minimal template, there is an existing setting for toggling the back button in the title or header. This is great for Desktop but not appropriate for Mobile/Phone.

Now when I run the app on the phone, the back button is gone which makes sense. Now how do I do that for the setting and should this be part of Template10 or just something we DEV's use if needed?

**Comment by JerryNixon** [comment]
Cool idea. I will point you to `Utils.DeviceUtils.DeviceDisposition()` which could easily be interrogated in the Loaded event of the SettingsPage and result in GotoState(Phone) or something like that, right? Why don't you try it out and submit a Pull Request here on GitHub. You should have fun with it.

**Comment by calloncampbell** [comment]
Ok I have a working solution. When testing it on mobile emulator and physical device, I came across a null exception for WindowWrapper in DeviceUtils.cs, so I've included a fix for that too. 

What is the process for me creating a pull request? I'm not able (forbidden) to push my changes. Should I be forking the code or is this another way?

**Comment by calloncampbell** [comment]
I think I got this right. I forked, made my changes, committed and was able create a pull request, #418

**Comment by calloncampbell** [comment]
Going to close this issue since you can use the DeviceUtils class and determine the device disposition. You can see sample implementation in the following fork: https://github.com/calloncampbell/Template10-HideBackButtonInPhone
