### ISSUE TITLE
[T10.Validation] - ControlWrapper - Indicator 

### ISSUE THREAD

**Issue by mvermef** [Windows-XAML/Template10#420]
Just starting looking over this... `Rectangle Indicator`, located in the ControlWrapper should this be public property?  Get a few errors when built and throws squiggles about `Indicator` in the usage of the wrapper.  Even code generator complains about inaccessible.  Yet it still works...

**Comment by JerryNixon** [comment]
Not sure what you are talking about here. I cannot duplicate this. If you want to provide more information, create a fresh issue on this topic. Otherwise, I really did look into it and didn't find this occurring. Output window was clean. Thanks for the note, though.
