### ISSUE TITLE
The type or namespace name 'ApplicationInsights' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by pcolmer** [Windows-XAML/Template10#426]
Just added Template10 to my installation of VS2015. Tried to build an empty project based off the Minimal template.
First error was complaining about System but that just requires a build and a refresh.
After that, however, I get the error in the title, complaining about ApplicationInsights missing.
As far as I can tell, this is an optional service running off Azure. Should we be forcing developers to use this?
Even if we are making it an optional feature of Template10, shouldn't there be some "getting started" documentation for developers so that they know the initial steps required to get going? I found http://dailydotnettips.com/2015/08/12/adding-application-insights-to-a-windows-10-universal-app/, for example, but all it starts with is "First, login to Azure Portal". Not very helpful if, as a developer, I've never done that before. Is there a cost for this?

**Comment by pcolmer** [comment]
Commenting out the calls to ApplicationInsights in App.xaml.xs/App() clears the build error, so it doesn't look like there are any other references to ApplicationInsights in the template.

**Comment by luiscantero** [comment]
@JerryNixon  This issue still exists in the library v1.12 for the Blank template. The same bunch of errors described above appear after creating a new app based on Blank. The issue does not happen with the Hamburger and Minimal templates because they reference the ApplicationInsights NuGet packages.
