### ISSUE TITLE
Enhancement: Make SettingsService support containers

### ISSUE THREAD

**Issue by bc3tech** [Windows-XAML/Template10#427]
Local & Roaming Settings objects have `CreateContainer()` on them so devs can keep their settings organized (way easier to store collections of related objects, for example). We should support using these in our `SettingsService` so as not to _remove_ functionality devs find useful.
I, for one, don't use `SettingsService` for exactly this reason.

**Comment by JerryNixon** [comment]
Give me a sample change to the ISettingsService interface.

**Comment by bc3tech** [comment]
Sure thing. I'm feeling githubby today anyway :)
