### ISSUE TITLE
Enhancement: HamburgerButtonInfo Indicator

### ISSUE THREAD

**Issue by ozzy1873** [Windows-XAML/Template10#428]
It would be nice to have an indicator on the HamburgerButtonInfo. For example, to show the number of unread messages. When only the icon is showing, it could overlay the upper right corner of the SymbolIcon. In the wide visual state, it could be to the right of the text.

**Comment by lyling** [comment]
good idea. please implement it.

**Comment by SimoneBWS** [comment]
nice feature

**Comment by JerryNixon** [comment]
Hmm, I like it. Like the badge on a live tile. Do you have a visual example?

**Comment by JerryNixon** [comment]
Closed, create a new if you get interested in this again.
