### ISSUE TITLE
Bug: Cannot select button more than once

### ISSUE THREAD

**Issue by ozzy1873** [Windows-XAML/Template10#429]
If you select a button once, you cannot select it again unless you select a different one first. This comes into play when navigating deeper into the app and you want to go back to the beginning without using the back button.

**Comment by lyling** [comment]
maybe need a "up"-sytle back button, like android

**Comment by JerryNixon** [comment]
What button are we talking about? Is this BROKEN behavior (are you doing the right thing labeling this as a bug) or is this an enhancement of the existing functionality?

**Comment by JerryNixon** [comment]
Closing for lack of info.
