### ISSUE TITLE
Memory management question

### ISSUE THREAD

**Issue by ozzy1873** [Windows-XAML/Template10#430]
In porting my phone app to template10, I have to deal with the user not being required to use the back button to navigate the app. The user can just jump back using the hamburger menu without using the back button, which causes the NavigationMode to be set to "New" instead of "Back". My phone app often does memory management (unhooking event handlers, etc.) when navigating back. Do you have any suggestions on how to do this in template10?

**Comment by frostieDE** [comment]
You could use the `Loaded`/`Unloaded` events of the corresponding pages to register/unregister events.

BTW: why do you need the `NavigationMode` when registering/unregistering events? Shouldn't you always register/unregister events when navigating to or from a page? If you need to subscribe to events event when a page is not the current one, you might use the `ViewModel` to subscribe to those events (in case you use MVVM pattern).

**Comment by JerryNixon** [comment]
My answer is this. If you are unsure of the nav path the user will take, then you need to unwire events every time OnNavigatedFrom is called in your view-mode and re-wire events every time OnNavigatedTo is called. Again, this is only true if you are using navigation cache, which is an edge case.
