### ISSUE TITLE
Make the HamburgerMenu open when you swipe from the left

### ISSUE THREAD

**Issue by oadugmore** [Windows-XAML/Template10#431]
In an update a week or two ago, Groove Music now opens the HamburgerMenu if you swipe from the left. It's smooth too -- it follows along with your finger until you let go. I've never developed for Android but I believe this behavior is built-in to their split view control and it's really nice. Microsoft might be testing this behavior with Groove to see how people react, and then perhaps they will officially add it to SplitView? However, if they are not planning on adding it themselves, I would suggest that this be added to Template 10's HamburgerMenu. Thoughts?

**Comment by lyling** [comment]
It is a great feature. hope template10 will add it. 

And here is one implementaion. maybe @JerryNixon consider it.
https://github.com/JustinXinLiu/SwipeableSplitView

**Comment by ghost** [comment]
This would be great.

**Comment by jp-weber** [comment]
This feature would be make sense only optional because it would destroy the operation of Pivot/HubControl/Flipview.

**Comment by oadugmore** [comment]
Good point, it should definitely be optional.

**Comment by JerryNixon** [comment]
Maybe. We'll see.

**Comment by JerryNixon** [comment]
I added TapToOpenCloseEnabled (default = false)
I added SwipeToOpenCloseEnabled (default = true)
