### ISSUE TITLE
Bug: Null reference exception when IsFullScreen == True

### ISSUE THREAD

**Issue by ozzy1873** [Windows-XAML/Template10#432]
Set IsFullScreen to true and resize the window. A null reference exception is thrown in the HamburgerMenu constructor because _SecondaryButtonStackPanel is null.

Also, resizing to minimum width when IsFullScreen is true causes a space to appear where the hamburger button would normally appear. You can close the space by setting VisualStateNarrowMinWidth="-1", but it seems you should not have to do this.

**Comment by JerryNixon** [comment]
IsFullScreen was not working properly but I have resolved that in the most recent commit. I would have mentioned this issue in the commit, but I didn't see it until now. I resolved this while correcting the layout of the Splash on the Phone. The implementation of IsFullScreen in the current code is completely different. Much better, too. I cannot reproduce your issue with the current code.
