### ISSUE TITLE
Font problems

### ISSUE THREAD

**Issue by heribertofilho** [Windows-XAML/Template10#435]
If i set some text via XAML, like: textblock text="Versão"
I'll see the text in the app like: Vers?o. Worst than that, every text of the application have this bug, but if i set the text via C#: versao.Text = "Versão";
The text'll be displayed correctly.

**Comment by MichaelPetrinolis** [comment]
You could check the encoding of the xaml file.

**Comment by heribertofilho** [comment]
I never checked this on the XAMLs, cause i never had trouble. I'll check this right now... You mean the XAMLs with content or any in particular?

**Comment by heribertofilho** [comment]
Oh man... it worked! I had to open the files on Notepad and change the encoding from "ANSI" to "UTF-8", thank you!

**Comment by MichaelPetrinolis** [comment]
You are welcome 😊
