### ISSUE TITLE
PageHeader SecondaryCommands flicker when opening each time

### ISSUE THREAD

**Issue by shaggygi** [Windows-XAML/Template10#436]
The menu flickers when opening, especially the first time.  It also seems to cut off the bottom part of the menu on first time, as well.

**Comment by MichaelPetrinolis** [comment]
Check PR #398 which fixes the issue.

**Comment by shaggygi** [comment]
Thanks for the info @MichaelPetrinolis.  I'm using the templates from the gallery.  Does this mean i need to download from github to get this fix?

**Comment by MichaelPetrinolis** [comment]
Correct, or you could wait for the 1.0.9 version on NuGet.
