### ISSUE TITLE
Should ViewModelBase have a OnNavigatedToAsync method?

### ISSUE THREAD

**Issue by shaggygi** [Windows-XAML/Template10#437]
Seems like the class would have this similar to having a OnNavigatedFromAsync.  Am I overlooking this?

**Comment by JerryNixon** [comment]
I understand the question. Let me ask you a question back. What would we be waiting for? Once the async operation is complete, there is nothing less to do, navigation is already complete. Make sense? I will leave this issue open just in case you do not understand my question. Remember you can do this:

``` csharp
async void OnNavTo() {
  // await something
}
```

**Comment by shaggygi** [comment]
That makes sense.  Thx
