### ISSUE TITLE
Isn't INavigable problematic?

### ISSUE THREAD

**Issue by frostieDE** [Windows-XAML/Template10#439]
Isn't the `INavigable` problematic for ViewModels as it references the `Windows.UI.Xaml.Navigation` namespace? It makes the ViewModel kind of dependent of the View which makes it hard to both reuse and unit-test ViewModels.

As a result, I would consider removing the `Windows.UI.Xaml.Navigation` namespace and create a copy of needed enums and classes which live in a different namespace than `Windows.UI.Xaml.Navigation`.

**Comment by JerryNixon** [comment]
This would only be true if you were attempting to write a Xamarin app. Using XAML namespaces in a view-model does not tie the view-model to the view. It just ties it to XAML. Which is acceptable.
