### ISSUE TITLE
Warning when creating store packages

### ISSUE THREAD

**Issue by bc3tech** [Windows-XAML/Template10#44]
Always met with this warning:

```
6>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\IlcInternals.targets(791,7): warning : Type 'Windows.UI.Xaml.Controls.Button' was not included in compilation, but was referenced in type 'Template10.Behaviors.NavButtonBehavior'. There may have been a missing assembly.
6>C:\Program Files (x86)\MSBuild\Microsoft\.NetNative\x86\ilc\IlcInternals.targets(791,7): warning : Type 'Windows.UI.Xaml.Controls.TextBox' was not included in compilation, but was referenced in type 'Template10.Behaviors.TextBoxEnterKeyBehavior'. There may have been a missing assembly.
```

**Comment by JerryNixon** [comment]
I don't get this warning. Could you get latest/clean and verify?

**Comment by bc3tech** [comment]
Seems like it has to do w/ the BehaviorsSDK which, in my References window, as a yellow exclamation next to it (as if to indicate not compatible w/ some/all packages)... but no tooltip to get more info...

**Comment by JerryNixon** [comment]
Still. Strange I don't get them. It is also (warning) yellow in my References. I am going to close this because, I am not sure this is a bug in the library. We can always address this more, later.

**Comment by klzig** [comment]
FWIW I'm seeing the same problem.  In addition to the aforementioned warnings, I get errors when I build for ARM, and any xaml that references the missing names fails to render in Visual Studio (Invalid Markup).   But after all of this, the build succeeds and I'm able to deploy the app to a phone. I don't see any of these problems when I target x86 and deploy to an emulator. 

```
Error       The name "Interaction" does not exist in the namespace "using:Microsoft.Xaml.Interactivity".
Error       The name "EventTriggerBehavior" does not exist in the namespace "using:Microsoft.Xaml.Interactions.Core".
Error       The name "CallMethodAction" does not exist in the namespace "using:Microsoft.Xaml.Interactions.Core".
```

**Comment by artfuldev** [comment]
Some of you might need to add Behaviors SDK (XAML) to your project, after you reference Template 10 or use the NuGet package. Please right click References -> Add Reference... -> Universal Windows -> Extensions -> Behaviors SDK (XAML) Version 12.0.

There may also be cases where it was not installed.

**Comment by Predatorie** [comment]
I created a brand new Template10 project, cleaned and rebuilt and everything built fine and ran. However, when I go to edit MainPage.xaml I am getting an invalid markup error which is the same error klzip above mentioned, "Interaction" does not exist in the namespace "using:Microsoft.Xaml.Interactivity".

@kenshinthebattosai I did what you said even though I already had the reference, it seems to be a SDK compatibility issue for me. When I go to check the Behaviors SDK (XAML) reference in the reference manager I have a yellow exclamation against it. I am told to go to go.microsoft.com/fwlink/?LinkID=309181 which takes me to a windows 8.1 page regarding the Advertising SDK for Windows and Visual Studio Extensions for the Windows Library for JavaScript, not very helpful.

I am using the latest release of Template10 via nugget and the SDK is version 12.0

**Comment by bc3tech** [comment]
right @Predatorie, it has nothing to do with the lack of a reference @kenshinthebattosai. It's the face that ARM appears to barf while building it.

**Comment by bc3tech** [comment]
I'm thinking we might benefit from using [the new Behaviors stuff that was just released](http://blogs.windows.com/buildingapps/2015/11/30/xaml-behaviors-open-source-and-on-uwp/?utm_source=twitterfeed&utm_medium=twitter) since it expressly calls out UWP compatibility now.

cc @JerryNixon
