### ISSUE TITLE
Menu pane not behaving as expected in SplitViewDisplayMode.Overlay mode

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#440]
When HamburgerMenu.DisplayMode is set to SplitViewDisplayMode.Overlay (page in the most compact form as in Mobile device) tapping on a menu item for a page already open doesn't close the menu pane.

You can repro this with the Minimal project as follows:
- If on local machine, resize the page for SplitViewDisplayMode.Overlay by resizing the width to the narrowest; else, use any mobile emulator.
- Tap on the Settings menu.
- Tap on the Settings menu again.

The only way to close the open menu pane is either by tapping on the Hamburger button or tapping on another page menu.

Shouldn’t tapping on a page menu that is only navigated to have a toggle effect?
I have added some logic in Shell.xaml.cs to overcome this issue (remembers previously navigated to page via HamburgerButtonInfo Tapped event, and if the same as current page sets Shell.HamburgerMenu.IsOpen = false).
Not sure if I have missed something and reinventing that round thing.

**Comment by chrisleyva** [comment]
@dg2k  Does this also happen to you in CompactOverlay?

**Comment by dg2k** [comment]
The short answer is yes it happens in CompactOverlay as well. It is however less noticeable as page navigation can take place by tapping on the icons shown in the Compact margin and without the menu pane opening (in my implementation anyway).  Since the menu pane stays closed, clicking again does nothing (whereas for Overlay you would expect the pane to close).

**Comment by JerryNixon** [comment]
I struggled to think this was a good idea in the first place. Then I implemented and realized that this is a very good behavior. The code to implement it was added to the NavButtonunChecked handler in the HamMenu, and only is triggered when the focus state is Pointer.
