### ISSUE TITLE
HamburgerButtonInfo Visibility

### ISSUE THREAD

**Issue by jcmontoya** [Windows-XAML/Template10#441]
I am trying to bind the visibility property of the HamburgerButtonInfo control to a global property in the app.xaml.cs.

The binding works... I am binding both the visibility property of the HamburgerButtonInfo and the visibility of the TextBlock (inside HamburgerButtonInfo) to my variable. 

XAML code:

`<Controls:HamburgerButtonInfo x:Name="sqlData" PageType="views:SQLData" >
      <StackPanel  Orientation="Horizontal">
          <SymbolIcon  Width="48" Height="48" Symbol="Page2" />
          <TextBlock x:Name="abc" Margin="12,0,0,0" VerticalAlignment="Center" Text="SQL Data" />
      </StackPanel>
</Controls:HamburgerButtonInfo>`

When I change the value of the variable the TextBlock changes to visible or collapsed as expected. But the  HamburgerButtonInfo is always visible. It never gets collapsed.

The code to set the binding:

Binding myBinding = new Binding();
myBinding.Source = App.myValidator;
myBinding.Path = new PropertyPath("IsVerified");
myBinding.Mode = BindingMode.OneWay;
myBinding.UpdateSourceTrigger = UpdateSourceTrigger.PropertyChanged;
myBinding.Converter = App.myConverter;
BindingOperations.SetBinding(sqlData, HamburgerButtonInfo.VisibilityProperty, myBinding);
BindingOperations.SetBinding(abc, TextBlock.VisibilityProperty, myBinding);

Any ideas what can be the issue?

Thanks in advance

**Comment by jcmontoya** [comment]
I noticed the Visibility of the HamburgerButtonInfo was a read only property.  

I removed the read only property it in my local code but I still see the same behavior. Visibility does not change. 

Before:
 //public static **readonly** DependencyProperty VisibilityProperty =

After:
        public static DependencyProperty VisibilityProperty =
            DependencyProperty.Register(nameof(Visibility), typeof(Visibility),
                typeof(HamburgerButtonInfo), new PropertyMetadata(Visibility.Visible));

I could disable the button but I prefer to collapse it, if the user is not authorized.

**Comment by chrisleyva** [comment]
@jcmontoya,

Your Binding is actually working. The problem is that Visibility is a DependencyProperty that was added to HamburgerButtonInfo and the class itself does nothing with the Visibility property. Since HamburgerButtonInfo is not a control or FrameworkElement, it has no UI. So, setting Visibility to Collapsed or Visible does not hide or show it. You need to template the HamburgerButtonInfo class. 

Take a look at how it's been used in HamburgerMenu.xaml: 

```
<DataTemplate x:Name="NavButtonTemplate" x:DataType="local:HamburgerButtonInfo">
    <RadioButton ... Visibility="{x:Bind Visibility, Mode=TwoWay}">
```

You can find the rest of the code here:
https://github.com/Windows-XAML/Template10/blob/020ad482253ff245ee206cf64e36ececdd72c885/Template10%20(Library)/Controls/HamburgerMenu.xaml#L69

Hope this helps.

**Comment by jcmontoya** [comment]
I understand but I am not sure how to do it. Do I have to create
a HamburgerButtonInfo.XAML to make it an user control... is that what you
are suggesting?

Thanks for your help.

**Comment by chrisleyva** [comment]
Hello @jcmontoya , no you don't have to create a whole new UserControl. You will need to modify this code but try this code (I simplified it): 

```
<ItemsControl ItemTemplate="{StaticResource NavButtonTemplate}">
    <ItemsControl.ItemTemplate>
        <DataTemplate x:Name="NavButtonTemplate" x:DataType="Controls:HamburgerButtonInfo">
                <RadioButton MinWidth="48" 
                             GroupName="Nav"
                             IsChecked="{Binding IsChecked, Mode=TwoWay}"
                             IsEnabled="{Binding IsEnabled, Mode=TwoWay}"
                             Tag="{x:Bind Content}"
                             Visibility="{x:Bind Visibility, Mode=TwoWay}" />
        </DataTemplate>
    </ItemsControl.ItemTemplate>

    <Controls:HamburgerButtonInfo x:Name="sqlData" PageType="views:SQLData" > 
        <StackPanel Orientation="Horizontal"> 
            <SymbolIcon Width="48" Height="48" Symbol="Page2" /> 
            <TextBlock x:Name="abc" Margin="12,0,0,0" VerticalAlignment="Center" Text="SQL Data" /> 
        </StackPanel> 
    </Controls:HamburgerButtonInfo>
</ItemsControl>
```

**Comment by JerryNixon** [comment]
IsEnabled and Visibility both work in 1.0.9. Also, please note, IsChecked has been changed from { get; set; } to { get; } but using HamMenu.Selected you can still check a button in the menu manually.

**Comment by jcmontoya** [comment]
Jerry this is working now. Thank you very much!
