### ISSUE TITLE
remove tree dots from PageHeader with no secondarycommand

### ISSUE THREAD

**Issue by a-iafrate** [Windows-XAML/Template10#452]
Hi
i have a PageHeader without secondarycommand, but tree dots on the right is show.

Thank for your work!

**Comment by qmatteoq** [comment]
Hello, you can apply the included EllipsisBehavior (https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Behaviors/EllipsisBehavior.cs) to the PageHeader control to remove the 3 dots.

**Comment by a-iafrate** [comment]
Thank matteo, also here :+1:

**Comment by bc3tech** [comment]
I believe that will (and should) still show because you can always expand the header to see button texts, regardless of SecondaryCommand presence, yes?

**Comment by rado-r** [comment]
Yes but if you use it only as a header without buttons it is better to hide it.
