### ISSUE TITLE
Issue with back navigation

### ISSUE THREAD

**Issue by naweed** [Windows-XAML/Template10#456]
Hi,

I noticed when the user presses the back button on desktop or hardware back button on phone, the frame goes to previous page, but the viewmodel OnNavigatedTo code fires again.

The scenario I am presenting is this. In my app, I have a listview (on mobile) or gridview (on desktop) which displays list of shows on MainPage. The user can scroll up or down, and click on the show he/she likes. This takes him to ShowDetailsPage where the information about the show is displayed (in pivot form on mobile, or scrollviewer in desktop). There is list of actors on this show page, which when clicked on one of the actors, navigates to CastDetailsPage. 

Now, the problem happens is that is the user presses back button, it goes back to ShowDetailsPage and loads the last show that you were watching, but it tries to fetch the data again, and also the scroll position is lost (or in case of mobile, the first pivot item gets highlighted). Similarly, if back is clicked again, it correctly goes to the MainPage, but again the page data reloads (either from internet or local cache), and re-binds the list or gridview taking the user all the way to the top.

Any suggestion for fixing this?

The app I am referring to is: https://www.microsoft.com/en-us/store/apps/series-tracker/9nblggh3slj9

Thanks

**Comment by JerryNixon** [comment]
This is not a Template 10 issue, this is an issue around Page Cache. What is happening, in short, is your page is reloading every time you navigate to it. The behavior you are expecting is more like a browser, right? Where the page does not reload if it is in the back stack. This is not default behavior in Windows, but you can do it. I wrote a whole article on it here: https://github.com/Windows-XAML/Template10/wiki/Docs-%7C-Navigation-Cache

**Comment by naweed** [comment]
Thanks.

I tried and it worked fine for me. I definitely don't need this on every page (where fresh load is needed), but on one of the pages, it resolved the issue for me.

Thanks again.
