### ISSUE TITLE
Can the PrimaryButtons on the HamburgerMenu be filled via data binding?

### ISSUE THREAD

**Issue by NoleHealth** [Windows-XAML/Template10#46]
Can the PrimaryButtons on the HamburgerMenu be filled via data binding?

From Shell,xaml
Controls:HamburgerMenu.PrimaryButtons
            <Controls:NavigationButtonInfo PageType="views:MainPage" ClearHistory="True">
                <StackPanel Orientation="Horizontal">
                    <SymbolIcon Symbol="Home" Width="48" Height="48" />
                    <TextBlock Text="Home" VerticalAlignment="Center" Margin="12,0,0,0" />
                </StackPanel>
            /Controls:NavigationButtonInfo
        /Controls:HamburgerMenu.PrimaryButtons

**Comment by bc3tech** [comment]
Should be able to bind to an `ObservableCollection<NavigationButtonInfo>` and be off to the races! My approach was to set all "raw" information in my VM, then create `NavigationButtonInfo` elements from them upon set, and `Add` each of those to the `ObservableCollection` property bound to the `PrimaryButtons` listing.

**Comment by JerryNixon** [comment]
Did that work?

**Comment by NoleHealth** [comment]
That worked great.
&lt;Controls:HamburgerMenu x:Name="MyHamburgerMenu" PrimaryButtons="{x:Bind ViewModel.PrimaryButtons }"&gt;

```
        PrimaryButtons = new ObservableCollection<NavigationButtonInfo>();

        var navigationButtonInfo = new NavigationButtonInfo();
        navigationButtonInfo.ClearHistory = true;
        navigationButtonInfo.PageParameter = "";
        navigationButtonInfo.PageType = Type.GetType("Minimal.Views.MainPage");
        var stackPanel = new StackPanel { Orientation = Orientation.Horizontal };
        stackPanel.Children.Add(new SymbolIcon { Symbol = Symbol.Home, Width = 48, Height = 48 });
        stackPanel.Children.Add(new TextBlock { Text = "Main", VerticalAlignment = VerticalAlignment.Center, Margin = new Thickness(12,0,0,0) });
        navigationButtonInfo.Content = stackPanel;

        PrimaryButtons.Add(navigationButtonInfo);


        navigationButtonInfo = new NavigationButtonInfo();
        navigationButtonInfo.ClearHistory = true;
        navigationButtonInfo.PageParameter = "";
        navigationButtonInfo.PageType = Type.GetType("Minimal.Views.HomePage");
        stackPanel = new StackPanel { Orientation = Orientation.Horizontal };
        stackPanel.Children.Add(new SymbolIcon { Symbol = Symbol.Home, Width = 48, Height = 48 });
        stackPanel.Children.Add(new TextBlock { Text = "Home", VerticalAlignment = VerticalAlignment.Center, Margin = new Thickness(12, 0, 0, 0) });
        navigationButtonInfo.Content = stackPanel;

        PrimaryButtons.Add(navigationButtonInfo);
```

Thanks!

**Comment by wstaelens** [comment]
If my PrimaryButtons contain information from a database that need to load first. 
Should this data be loaded in  MyHamburgerMenu.PaneOpen += MyHamburgerMenu_PaneOpen ?

Maybe stupid question but why is there only a Shell and not a ShellViewModel ?

Note: Just started Template10 and UWP.

**Comment by NoleHealth** [comment]
I am not sure where that should be located but I did create a ShellViewMofel in my solution. I have not worked on it in a while. Maybe I can post something this weekend

**Comment by wstaelens** [comment]
would love to see a sample yes.

Lack of decent samples and documentation makes it hard for a beginner.

**Comment by bc3tech** [comment]
@wstaelens in @NoleHealth's post above, you'd simply use your DB information when inserting the `HamburgerButtonInfo` objects in to the `PrimaryButtons` collection, no?

**Comment by wstaelens** [comment]
Now I just do something like this in Shell.xaml.cs:

``` csharp
    public Shell(NavigationService navigationService)
    {
      Instance = this;
      InitializeComponent();
      _DataService = GalaSoft.MvvmLight.Ioc.SimpleIoc.Default.GetInstance<IDataService>();
      LoadGroupsInMenu();
      MyHamburgerMenu.NavigationService = navigationService;
    }
```

Where the LoadGroupsInMenu creates new HamburgerButtonInfo's, stores them in a collection in Shell.xaml.cs:

``` csharp
    private ObservableCollection<HamburgerButtonInfo> _NavButtonGroups = default(ObservableCollection<HamburgerButtonInfo>);
    public ObservableCollection<HamburgerButtonInfo> NavButtonGroups
    {
      get { return _NavButtonGroups; }
      set
      {
        if (Equals(_NavButtonGroups, value))
          return;

        _NavButtonGroups = value;
        Instance.PropertyChanged?.Invoke(Instance, new PropertyChangedEventArgs(nameof(NavButtonGroups)));
      }
    }
```

and Shell.xaml:

``` xml
<Controls:HamburgerMenu x:Name="MyHamburgerMenu" IsFullScreen="False" PrimaryButtons="{x:Bind NavButtonGroups, Mode=OneWay}">
```

Is this a correct way of working?

extra question: how come Shell.xaml does not have a viewmodel to work in an MVVM way? For this single Page I now need to add code in codebehind while other pages have a view and viewmodel.
