### ISSUE TITLE
Back button lose reference if app go to background in windows phone

### ISSUE THREAD

**Issue by a-iafrate** [Windows-XAML/Template10#460]
Steps to reproduce:
1.Open minimal template
2. Deploy the app to either an emulator or a device and start the app in debug mode from visual studio.
3. Go to settings
4. press back button
5. the app go to main page
6. stop debug
7 launch app from device
8 press windows button for hide app
9 press back button per reopen app (it's in settings page)
10 press back button again the app don't go to main page but exit!!

**Comment by schuettecarsten** [comment]
We have had similar issues when apps based on Template10 are suspended and then resumed. Take a look at my pull request, does this fix your issue? (It did on our devices): https://github.com/Windows-XAML/Template10/pull/448

**Comment by a-iafrate** [comment]
Hi,
i have already used your modification, but if you press windows button the app is not suspended and if you press button seems not all is reloaded. You can try with minimal template, the problem remain

**Comment by naweed** [comment]
I had a similar problem. I stopped using the code in "ClearNavigationServices" in WindowWrapper, and that resolved the issue for me.

But one thing to note, I am using a customized version of Template10. You may have some other issues if you comment out this code. But you can try.

**Comment by JerryNixon** [comment]
This has been resolved.
