### ISSUE TITLE
Error template attempted to load universal templateWizards

### ISSUE THREAD

**Issue by GeraudFabien** [Windows-XAML/Template10#470]
Hello,
When I try to get to create a new project after installing template 10. I get this message:
![image](https://cloud.githubusercontent.com/assets/13610689/12214649/7bd57cec-b69d-11e5-95bc-6941cdc7b59d.png)
I'm on 
- Windows 10 Pro (New install and update)
- VS Enterprise update 1 (New install and update)
- Developer mode enable

**Comment by JerryNixon** [comment]
Hmm. I have never seen this before. My first guess is that you do not have the 10240 SDK installed and T!) is 10240 only and not 10586 yet. But that is just a guess. Hmm.

**Comment by callummoffat** [comment]
Actually, T10 works fine with HEAD on 10586 now. I've tested on my current project, and it's fully functional on 10586 these days. None of those previous errors, at least for me.

**Comment by GeraudFabien** [comment]
Actually there was an network error during the installation and VS didn't install the Universal SDK. I'm sorry since it was the TemplateWizard that bug I didn't think to check that.

**Comment by Earbaj** [comment]
I have face this same problem so what can i do now please help

**Comment by mvermef** [comment]
What SDKs are installed?  Narrow down to the one that is missing

**Comment by Earbaj** [comment]
i try both SDK 10240 and 10586 but the problem wasn't fix

**Comment by mvermef** [comment]
Have you tried repair, on vs installer there is a hamburger button with uninstall and repair... This is next to the presently installed version indicated by the installer, it's in the start menu in the V's

**Comment by Earbaj** [comment]
Yeah i tried this but it did not work
