### ISSUE TITLE
Databound samples for Template10?

### ISSUE THREAD

**Issue by rickengle** [Windows-XAML/Template10#474]
Hi, I'd love to see some samples of Template10 that show examples of Databound Lists with binding to sample data.   This would be similar to the Databinding templates provided with Visual Studio for Windows Phone 8.1 projects.   I'm trying to get up to speed on Universal App coding and it seems like almost all of my apps leverage databound lists either being read in from XML or JSON sources.

Thanks!
  Rick

**Comment by janabimustafa** [comment]
Hi. Have you looked over the master/detail sample?

**Comment by rickengle** [comment]
I did but that only passes a simple parameter, it doesn't demonstrate a full implementation of databinding to a list.  I'm not as interested in a master/child page relationship as populating a List control using a datasource with styling that flows appropriately on a phone or desktop/tablet screen.

**Comment by JerryNixon** [comment]
Not sure what you want.
