### ISSUE TITLE
After changing code in UpdateFullScreen method, setting VisualStateWideMinWidth doesn't trigger visual state

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#479]
I haven't established the exact cause, but since the changes made to the UpdateFullScreen() method in HamburgerMenu.xaml.cs, setting page width to `Instance.MyHamburgerMenu.VisualStateWideMinWidth` doesn't trigger the expected visual state. In fact, all will be fine if you comment out the code block:

```
if (RootGrid.Children.Contains(ShellSplitView))
    RootGrid.Children.Remove(ShellSplitView);
if (RootGrid.Children.Contains(HamburgerButton))
    RootGrid.Children.Remove(HamburgerButton);
if (RootGrid.Children.Contains(Header))
    RootGrid.Children.Remove(Header);
```

To avoid null exceptions it is also necessary to add `ShellSplitView.Visibility = Visibility.Collapsed;` where `ShellSplitView.Content = null;` line appears and `ShellSplitView.Visibility = Visibility.Visible;` where `ShellSplitView.Content = frame;` line appears.

**Comment by JerryNixon** [comment]
Yep. Changed the code because of this issue. New code is like this:

```
private void UpdateFullScreen(bool? manual = null)
{
    var frame = NavigationService?.Frame;
    if (manual ?? IsFullScreen)
    {
        ShellSplitView.IsHitTestVisible = ShellSplitView.IsEnabled = false;
        ShellSplitView.Content = null;
        if (!RootGrid.Children.Contains(frame) && frame != null)
            RootGrid.Children.Add(frame);
    }
    else
    {
        ShellSplitView.IsHitTestVisible = ShellSplitView.IsEnabled = true;
        if (RootGrid.Children.Contains(frame) && frame != null)
            RootGrid.Children.Remove(frame);
        ShellSplitView.Content = frame;
    }
}
```
