### ISSUE TITLE
Hamburger and backnavigation issue.

### ISSUE THREAD

**Issue by jerinjohnk** [Windows-XAML/Template10#480]
Run minimal project->Click on settings of the lower left-> now click back button(top left)
We will find that we have returned to MainPage but settings button is still highlighted so clicking on settings button now doesn't work.

**Comment by JerryNixon** [comment]
I acknowledge that this has been an issue, but the current source in GitHub does not have this issue. When we release 1.0.9, this bug will be resolved.

**Comment by jerinjohnk** [comment]
Thank you. This library is pretty damn awesome.
