### ISSUE TITLE
How to create a horizontal Separator in the Pane

### ISSUE THREAD

**Issue by CodingOctocat** [Windows-XAML/Template10#481]
I created a separator, but is in portrait orientation, how to create a horizontal Separator in the Pane?

**Comment by JerryNixon** [comment]
What is a Pane? I'm sorry, I am not following your question.

**Comment by CodingOctocat** [comment]
Oh, I'm sorry, I come from non-English speaking countries, this is the result of Bing translation. In short, I want SplitView template is more like (animation and detail) Win10 native application (such as Groove App SpiltView)(●'◡'●)
---Thank you for your answer

**Comment by JerryNixon** [comment]
There is already a separator (set primary and secondary commands to see it)
