### ISSUE TITLE
I hope that when the item is selected in the Pane, the "Setting" don't display, and comes with more consistent application of the system!

### ISSUE THREAD

**Issue by CodingOctocat** [Windows-XAML/Template10#482]
I hope that when the item is selected in the Pane, the "Setting" don't display, and comes with more consistent application of the system!

**Comment by JerryNixon** [comment]
What?

**Comment by CodingOctocat** [comment]
Oh, I'm sorry, I come from non-English speaking countries, this is the result of Bing translation. In short, I want SplitView template is more like (animation and detail) Win10 native application (such as Groove App SpiltView)(●'◡'●)
---Thank you for your answer

**Comment by kenakamu** [comment]
If you are talking about "Groove music" then the current menu is pretty close to the app, and Groove also has "Settings". The speed of open/close or the place of humbergar icon is different though. When you see "news" app, it is actually more close.
