### ISSUE TITLE
Follow-up to #479 re UpdateFullScreen()

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#484]
The modified code fails for me but works when Visibility settings are added (on two lines).

```
private void UpdateFullScreen(bool? manual = null)
{
    var frame = NavigationService?.Frame;
    if (manual ?? IsFullScreen)
    {
        ShellSplitView.IsHitTestVisible = ShellSplitView.IsEnabled = false;
        ShellSplitView.Content = null;
         ShellSplitView.Visibility = Visibility.Collapsed;
        if (!RootGrid.Children.Contains(frame) && frame != null)
            RootGrid.Children.Add(frame);
    }
    else
    {
        ShellSplitView.IsHitTestVisible = ShellSplitView.IsEnabled = true;
        if (RootGrid.Children.Contains(frame) && frame != null)
            RootGrid.Children.Remove(frame);
        ShellSplitView.Content = frame;
         ShellSplitView.Visibility = Visibility.Visible;
    }
}
```

**Comment by JerryNixon** [comment]
Fails? In what way? I ask because I see it working. You are up to date with T10 on Git? Woth pointing out that I also tested this on Phone and "Inline". Looking forward to your reply.

**Comment by dg2k** [comment]
I am checking with the latest merge. For some reason it fails when I  attempt to set 'Instance.MyHamburgerMenu.VisualStateWideMinWidth' (say -1 or VisualStateWideMinWidth), in my case in Shell.xaml.cs.

If you leave out the Visibility.Visible setting, you get  `_SecondaryButtonStackPanel` null exception on line 52. If you leave out the Visibility.Collapsed, you get a weird error "Value does not fall within the expected range" -- I did trace the cause of this to some null value but sorry can't remember off the top of my head at the moment.

**Comment by JerryNixon** [comment]
I don't mind fixing something. But this doesn't seem to fail.

**Comment by dg2k** [comment]
Sorry you're right! I only tested by changing the UpdateFullScreen() method for the version  had before the latest merge (relating to #479). I should have tested with the whole library code(for there may be other code changed, not only UpdateFullScreen) so all is fine now. Phew!
