### ISSUE TITLE
Is there any way to stop annimation for PageHeader when back from previous page?

### ISSUE THREAD

**Issue by kenakamu** [Windows-XAML/Template10#486]
Is there any way to stop annimation for PageHeader when back from previous page?

**Comment by JerryNixon** [comment]
What animation?

**Comment by DarthPedro** [comment]
As the page loads, there is an animation where the page header slides up slightly from its bottom. Sounds like he wants to prevent that animation when the user goes back to that page.

**Comment by shaggygi** [comment]
I was wondering this too.  It appears it animates even when you navigate to another page, not just going back.

**Comment by kenakamu** [comment]
It was not just a header but entire content which animated.

https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Services/NavigationService/FrameFacade.cs#L23-L28

So Navigation service set Content animation above. To avoid the animation, you can clear it after NagivationService instantiated. For example, in App.xaml.cs

``` C#
// setup hamburger shell
var nav = NavigationServiceFactory(BackButton.Attach, ExistingContent.Include);
nav.Frame.ContentTransitions.Clear();
```

By doing this, entire framing in animation disabled. If you only want to stop animation just for header, then you can stop Frame.ContentTransitions like above then do animation for each element in your page.

``` xaml
<!--  page content  -->
<Grid x:Name="contentGrid" Grid.Row="1" Padding="12">
    <Grid.Transitions>
        <TransitionCollection>
            <EntranceThemeTransition />
        </TransitionCollection>
   </Grid.Transitions>
```

**Comment by JerryNixon** [comment]
Ah, yes.

Here I am doing it for Settings in Minimal.

``` XAML
<Controls:HamburgerMenu.SecondaryButtons>
    <!-- settingspage button -->
    <Controls:HamburgerButtonInfo x:Name="SettingsButton" PageType="views:SettingsPage">
        <Controls:HamburgerButtonInfo.NavigationTransitionInfo>
            <SuppressNavigationTransitionInfo />
        </Controls:HamburgerButtonInfo.NavigationTransitionInfo>
        <StackPanel Orientation="Horizontal">
            <SymbolIcon Width="48" Height="48" Symbol="Setting" />
            <TextBlock Margin="12,0,0,0" VerticalAlignment="Center" Text="Settings" />
        </StackPanel>
    </Controls:HamburgerButtonInfo>
</Controls:HamburgerMenu.SecondaryButtons>
```
