### ISSUE TITLE
Hide/Disable AppViewBackButtonVisibility on Constructor

### ISSUE THREAD

**Issue by prtdomingo** [Windows-XAML/Template10#487]
Is there any way to hide/disable the Built-In Back button of UWP in the Page or ViewModel Constructor? I'm using the following code in the constructor 

`SystemNavigationManager.GetForCurrentView().AppViewBackButtonVisibility = AppViewBackButtonVisibility.Collapsed;`

But it seems that T10 overrides the visibility that I've set in the AppViewBackButtonVisibility.

**Comment by JerryNixon** [comment]
Try `Bootstrapper.ShowShellBackButton;`

**Comment by prtdomingo** [comment]
I used `BootStrapper.Current.ShowShellBackButton = false;`, it works, though it now shows the BackButton in T10 PageHeader. I tried to set the BackButtonVisibility of PageHeader to Collapsed but it still shows the BackButton. 

I'll try to look for a solution to this one as well.

**Comment by kenakamu** [comment]
I don't know the way to hide it in constructor, but you can simply remove Frame binding for each header which loose back button

``` xaml
<controls:PageHeader x:Name="pageHeader" BackButtonVisibility="Collapsed" Content="Header" Frame="{x:Bind Frame}">
```

To

``` xaml
<controls:PageHeader x:Name="pageHeader" BackButtonVisibility="Collapsed" Content="Header">
```

**Comment by prtdomingo** [comment]
Cool, thanks
