### ISSUE TITLE
As soon as i changed the background color for Splash.xaml, it crashes at launch.

### ISSUE THREAD

**Issue by kenakamu** [Windows-XAML/Template10#488]
When I change 

``` xaml
<Grid Background="{StaticResource ExtendedSplashBackground}">
```

to

``` xaml
<Grid Background="Black">
```

It crashes at launch. Any idea?

**Comment by JerryNixon** [comment]
I think something is missing.

**Comment by dg2k** [comment]
I have tested with Local Machine, phone emulator and Windows 10 Mobile device with no issues of background color as you describe. Are you using an image for the splash page? Mine does and not sure if that makes any difference. Interesting to know what is causing this.

**Comment by JerryNixon** [comment]
I get this error, too. I don't understand. 

Temporarily, this works:

``` XAML
<UserControl x:Class="Sample.Views.Splash" xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml" xmlns:Core="using:Microsoft.Xaml.Interactions.Core"
             xmlns:Interactivity="using:Microsoft.Xaml.Interactivity" xmlns:Media="using:Microsoft.Xaml.Interactions.Media"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008" xmlns:local="using:Sample.Views"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" mc:Ignorable="d" 
             Background="{StaticResource ExtendedSplashBackground}">

    <Grid Background="Red">
```

Anyone understand this?

**Comment by JerryNixon** [comment]
@Windows-XAML/community Anyone else seeing this?

**Comment by JerryNixon** [comment]
@Windows-XAML/contributors Anyone else seeing this?

**Comment by chrisleyva** [comment]
Is there an Exception or error message?

**Comment by chrisleyva** [comment]
This is the problem right here:
https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Common/BootStrapper.cs#L401-L406

I tried:

```
try {
    foreach(var resource in Application.Current.Resources)
    {
    ...
    }
} catch { }
```

Setting some breakpoints, you'll see that while enumerating, after ContrastColorBrush, attempting to get the next resource will throw the ComException.

**Comment by chrisleyva** [comment]
Looking at Custom.xaml, after "ContrastColorBrush" comes the ThemeDictionaries. Maybe since there isn't a single reference to any of the Resources defined in the ThemeDictionaries at the point that we call the foreach loop, it crashes because the theme dictionary hasn't been loaded yet. 

I don't know. Just spit-balling.

**Comment by chrisleyva** [comment]
I was right. Add this right before the foreach loop and it works.

```
var unused = Application.Current.Resources["ExtendedSplashBackground"];
foreach( var resources in Application.Current.Resources......)
```

So, it seems that we can't enumerate Application.Current.Resources until one of it's Keys is referenced or something like that. Seems weird.

**Comment by kenakamu** [comment]
Thanks all, workaround confirmed. When I want to something new in Resource dictionary, then I have to reference it in theme, too. 

I added following to custom.xaml resource

<SolidColorBrush x:Key="SplushColorBrush" Color="#FF253D5D" />

Then I added following in each Theme
<Style x:Key="dummy" TargetType="Grid">
                <Setter Property="Background" Value="{StaticResource SplushColorBrush}" />
            </Style>

By doing this, if I use the SplashColorBrush in Splash like below, it works.

<Grid Background="{StaticResource SplushColorBrush}">

So the trick here is to reference the resource from theme

**Comment by kenakamu** [comment]
It seems all elements right under ResourceDictionary has to be referenced from any elements in ThemeDictionary.

If I simply do not use ExtendedSplashBackground by replacing it to my own in Splash.xaml, then it seems ContrastColor is not referenced from anywhere. Yet ContrastColorBrush referencing ContrastColor and controls:PageHeader referencing ContrastColorBrush though.

So current workaround I have is to reference ExtendedSplashBackground somewhere in Splash.xaml and I set it like this.

``` xml
<ProgressRing x:Name="progressRing" Width="50"
                      Height="50" HorizontalAlignment="Center"
                      VerticalAlignment="Center" Foreground="{StaticResource ExtendedSplashForeground}"
                      Background="{StaticResource ExtendedSplashBackground}"
                      IsActive="True" RenderTransformOrigin="0.5,0.5">
```

And it just works fine for now. A bit wired work around though.

**Comment by JerryNixon** [comment]
@chrisleyva your solution is pretty re-usable. I added it to BootStrapper. Thanks.

**Comment by kenakamu** [comment]
I don't think this is a good way to avoid issue.
The cause is that if there is a element which is not referenced from anywhere the issue occurs. So the correct solution should be "Do not put anything which is not referenced from anywhere"

If we hardcord that, and expose the ExtendedSplashForeground in custom.xaml., chances are some may remove it by thinking we don't need it and I causes the issue as there is no such resource anymore.

I do not have any issue without @chrisleyva workaround by reference all root elements from each Theme. Could you reopen this to re-consider it?

**Comment by pekspro** [comment]
I agree, this is not a good solution. It made my app crash because I didn’t have any resource named "ExtendedSplashBackground". Please at least check that this key exists before reading it.
