### ISSUE TITLE
Template10 vis-à-vis Build 10240 and 10586

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#490]
Could some one please tell me the differences Build 10586 makes to Template10?
I have seen some references that imply some kind of incompatibility with Build 10586 but not sure what. I might have missed something that's worth noting.

**Comment by callummoffat** [comment]
There is no incompatibility with 10586 itself, but there are some compatibility issues with the 10586 SDK. Currently, targeting your app to 10586, or even supporting only 10586 is fully supported. However, targeting the library to 10586 causes major issues. That's what @JerryNixon means, and that's what he intends to fix once 1.0.9 launches.

Oh, and you'll need to use the latest source code, NOT Nuget, to target 10586 SDK for your app.

**Comment by callummoffat** [comment]
For instance, my app is based on T10, and uses the latest Git sources. It doesn't support 10586 at all. It works perfectly fine, so long as the library still targets 10240.

**Comment by dg2k** [comment]
Thank you for that Callum. I get the SDK part (which I see on VS2015 UWP version targeting) but thought may be there are more subtle things. I have been testing with the source directly (rather than the Visual Studio T10 template) and may be that disguised things from me.

> Oh, and you'll need to use the latest source code, NOT Nuget, to target 10586 SDK for your app.

That's what I have been using and how I managed to miss the issues mentioned. That clarifies it all for me. Thanks.

**Comment by callummoffat** [comment]
It should be noted that targeting 10586 SDK at all (app or otherwise) isn't OFFICALLY supported, but I've found that it works just fine.
