### ISSUE TITLE
[Question] Messenger on Template 10

### ISSUE THREAD

**Issue by gsantopaolo** [Windows-XAML/Template10#491]
Hi,
     I'm at my 10th hour of non stop Template 10 coding cannot believe how awesome it is! :) 
Now I came around the need of making communication between ViewModels.
On the Template 10 WiKi page I read "We communicate with a Messenger" but I can't see any evidence on a sort of Event Aggregator pattern implementation (https://msdn.microsoft.com/en-us/library/ff921122.aspx).
Am I wrong? can you point it to me?
If I'm right why not implementing some sort of weak  Event Aggregator?

thank you
.g

**Comment by marcominerva** [comment]
Template10 doesn't provide a Messenger, but you can use the one included in MVVM Light: https://marcominerva.wordpress.com/2015/11/30/using-mvvm-light-messenger-with-template-10.

**Comment by JerryNixon** [comment]
I like the PubSubEvents messenger written by the Microsoft Patterns and Practices team. I created a course on how to use it. Here's the link: https://mva.microsoft.com/en-US/training-courses/developing-universal-windows-apps-with-c-and-xaml-8363?l=wmO3ZEGz_9704984382
