### ISSUE TITLE
App don't resume correctly on phone

### ISSUE THREAD

**Issue by a-iafrate** [Windows-XAML/Template10#492]
Hi,

i have again problem with resume on phone with last source code

Step to reproduce
1. launch minimal project on emulator
2. suspend app by vs lifecicle menu
3. launch app from app list, only menu is show, no app!!
Thanks to all!!
![er](https://cloud.githubusercontent.com/assets/8555750/12280628/bee1921a-b98f-11e5-9fad-09b920920c6e.png)

**Comment by JerryNixon** [comment]
Not sure your build. But I have seen this in the past. The current code on GitHub has the fix.

**Comment by a-iafrate** [comment]
Are you sure? i have update the latest code but now it remain on splashscreen. please try!

**Comment by JerryNixon** [comment]
Positive.
