### ISSUE TITLE
App don't resume stay on splash screen with last source code on default minimal project

### ISSUE THREAD

**Issue by a-iafrate** [Windows-XAML/Template10#493]
Hi,

i have again problem with resume on phone with last source code on default minimal code

Step to reproduce
1. launch minimal project on emulator
2. suspend app by vs lifecicle menu
3. launch app from app list, app stay on splash screen
   
   Thanks to all!!

**Comment by DanTheManSWE** [comment]
I have the same problem using the NuGet version, but only when I run on device. 
It works fine in emulator.

**Comment by a-iafrate** [comment]
i have the problem also in emulator
