### ISSUE TITLE
SecondaryCommands button bug

### ISSUE THREAD

**Issue by Greywing** [Windows-XAML/Template10#509]
I deploy app using Template10 (Minimal) on Lumia 640 with OS build 10.0.10586.63

If I open (or reopen) Main Page and tap on SecondaryCommands button, then I will see bug above

![wp_ss_20160114_0001](https://cloud.githubusercontent.com/assets/6736794/12334735/a30e3ab0-bb0c-11e5-97f7-4ebd58d4cc5d.png)

**Comment by MichaelPetrinolis** [comment]
This is already fixed. Try from git if you use latest NuGet version, otherwise wait for next version.

**Comment by Greywing** [comment]
@MichaelPetrinolis, thank you!
