### ISSUE TITLE
Noobie question about SplitView placement

### ISSUE THREAD

**Issue by florianmonfort** [Windows-XAML/Template10#513]
Hi,

Newbie developer here who is learning how to program. I wanted to try to do a bottom-level navigation with your Template but couldn't see through the wiki/documentation how to do this.

Also I have tried to find properties to do this but so far all I could find was the ability to put it right or left.

Can you guys make this an available option in the template?

Thanks

**Comment by JerryNixon** [comment]
Yeah, Right and Left are the only supported positions.

**Comment by florianmonfort** [comment]
Do you recommend any documentation or alternative solutions that have been used in the past to achieve this?
