### ISSUE TITLE
non-US charakters in x:key

### ISSUE THREAD

**Issue by ghost** [Windows-XAML/Template10#514]
I often use nation charakters (like Danish: æ, ø, å) when creating styles in resource files. This way I'm not conflicting with allready existing names. It works fine in VS2015 and UWP, but when using Template10, I get compilation errors having non-US characters in x:key

**Comment by JerryNixon** [comment]
Well, I just added `x:Name="åPage"` to MainPage and it worked okay. I wonder if this has to do with your file encoding? Sorry, I am going to close this issue because I cannot reproduce it.
