### ISSUE TITLE
Accessing LaunchActivatedEventArgs in App.xaml.cs?

### ISSUE THREAD

**Issue by SandipAhluwalia** [Windows-XAML/Template10#515]
I need to access the LaunchActivatedEventArgs class during app launch so that I can access properties like TileId and Arguments for deep linking use cases. How can I achieve this in Template10 as it seems the OnLaunched override is sealed within Template10.Common.BootStrapper?

**Comment by JerryNixon** [comment]
`OnStartedAsync` replaces `OnLaunched` and includes the args you are wanting.

**Comment by SandipAhluwalia** [comment]
That only gives me IActivatedEventArgs. So I am guessing I would have to cast it to the LaunchActivatedEventArgs class to access the properties of LaunchActivatedEventArgs? The same problem occurs when wanting to access SearchActivatedEventArgs via OnSearchActivated.
