### ISSUE TITLE
Question: Change image assets if App theme changed

### ISSUE THREAD

**Issue by ghost** [Windows-XAML/Template10#516]
Hello

I would like to ask that is there a way to change image assets?
I tried with theme qualifiers but it doesnt work for me.

I renamed contact.png to contact.scale-200_theme-light.png and contact.scale-200_theme-dark.png
and referenced ms-appx:///Assets/Shell/contact.png.

When Terminated the app and reload it the problem still appear.

Anyone has an idea?

thanks 
Lockness

**Comment by JerryNixon** [comment]
The first thing you can do is to define your image paths in a Theme. If you just have a few images, this is a simple approach. Otherwise, control your theme based on a setting and handle that changing. Not a lot of options, I know. If you come up with another one, share with me.
