### ISSUE TITLE
Question: how to keep selected pivotitem when navigating

### ISSUE THREAD

**Issue by wstaelens** [Windows-XAML/Template10#517]
FooPage with Pivot. I select PivotItem2.
Via some command I Navigate to BarPage.
From BarPage I click Return and go back to FooPage.

How can I select PivotItem2 again?

I tried via SessionState in the OnNavigatedTo and the OnNavigatingFrom, but this only works once, because SessionState.Remove doesn't seem clear the value.

What is also the difference between the SessionState and the state-parameter from OnNavigatedFromAsync / OnNavigatedTo ?

Looking forward to see some code on how to do this correctly.

**Comment by JerryNixon** [comment]
An easy way to do this is to set `NavigationCacheMode = Windows.UI.Xaml.Navigation.NavigationCacheMode.Enabled;` in the constructor of the page that contains the Pivot control.
