### ISSUE TITLE
App crash when clicking the down arrow on the right hand pane.

### ISSUE THREAD

**Issue by Pinox** [Windows-XAML/Template10#518]
![image](https://cloud.githubusercontent.com/assets/5297255/12361917/89e4d626-bbc9-11e5-9221-b59039ffec88.png)

When clicking the scroll down arrow the app crashes in the default template.

**Comment by JerryNixon** [comment]
I am not seeing the same behavior.

![screen](https://cloud.githubusercontent.com/assets/1749983/12362826/970b04b6-bb82-11e5-96c8-f4444d222c68.gif)

**Comment by Pinox** [comment]
Plse click on the red circle area - just checked on the minimal template and i still see the error.

![image](https://cloud.githubusercontent.com/assets/5297255/12363337/04694b64-bbd1-11e5-94aa-e13fa809abdf.png)

**Comment by Pinox** [comment]
Hi Jerry , I like your animated gif. Had to make one myself.

![verticalscrollbar_error](https://cloud.githubusercontent.com/assets/5297255/12373503/a1979104-bc83-11e5-8ce4-8ef6a79db011.gif)
