### ISSUE TITLE
[Question] Why are there two zip projects for both project templates?

### ISSUE THREAD

**Issue by shaggygi** [Windows-XAML/Template10#522]
Here are the paths in the Installer directory:

ProjectTemplates\Windows\Universal\Template10\Template10Blank.zip
ProjectTemplates\Windows\Universal\Template10\Template10Minimal.zip
ProjectTemplates\Windows\Template10Blank.zip
ProjectTemplates\Windows\Template10Minimal.zip

**Comment by JerryNixon** [comment]
They are part of the VSIX When we create it. You can ignore them.
