### ISSUE TITLE
AppBarToggleButton doesn't appear to bind

### ISSUE THREAD

**Issue by shaggygi** [Windows-XAML/Template10#527]
I can't seem to get the field to update when checking/unchecking the control.  Any thoughts?

AppBarToggleButton IsChecked="{x:Bind ViewModel.IncludeValue}"

bool? includeValue

```
    public bool? IncludeValue
    {
        get { return includeValue; }

        set { Set(ref includeValue, value); }
    }
```

**Comment by janabimustafa** [comment]
IsChecked="{x:Bind ViewModel.IncludeValue, Mode=TwoWay}"

**Comment by shaggygi** [comment]
That's it!  I tried no Mode and OneWay, but not TwoWay.  Thx, I'll close.
