### ISSUE TITLE
Back button not visible when in Tablet mode.

### ISSUE THREAD

**Issue by AmitBhatnagar24** [Windows-XAML/Template10#53]
1: Put Windows in Tablet mode.
2: Launch Minimal
3: Enter text on Main page and click submit
4: You are brought to the details page, but no back button is visible.

(the above occurs regardless of the type of back button used (shell drawn vs in page header)

If you turn off tablet mode, the back button re-appears.

**Comment by AmitBhatnagar24** [comment]
Further.. 

if in tablet mode and you use the back button on the Details page that is beside the Windows button in the taskbar, the Minimal app exits.

**Comment by Nab0y** [comment]
In tablet mode, use the software back button, it is located on the taskbar next to the Start button

**Comment by AmitBhatnagar24** [comment]
(in response to Dmitry's comment)

Well that goes against what the "News" app does.

If launched in tablet mode, News does present the back button in the page header.

Also, if I do use the back button in the taskbar in Minimal on the Details page, the app exits instead of returning to the Main page.

**Comment by JerryNixon** [comment]
Did you look in the TaskBar? 
![clipboard01](https://cloud.githubusercontent.com/assets/1749983/9555047/e370366e-4d87-11e5-82f4-0ff95ab40096.png)

**Comment by AmitBhatnagar24** [comment]
No. I mean page header.

It is removed when in tablet mode.

News / Money app show back button in page header when in tablet mode.

Should T10 do the same (?)

**Comment by JerryNixon** [comment]
The T10 on-canvas back button will automatically hide itself in tablet mode only if the shell-drawn back button is visible in the taskbar. News does not do this. It has two back buttons. I think that is an error, actually. Two back buttons? Is that what you are asking for?

**Comment by AmitBhatnagar24** [comment]
No, two back buttons doesn't sound correct. 

Close issue.
