### ISSUE TITLE
Validation Sample - Recommendation for Add and Delete Capability

### ISSUE THREAD

**Issue by rickgregory1905** [Windows-XAML/Template10#532]
I've been playing with the Validation sample and was looking for recommendations for an add and delete capability. I'm currently using a secondaryCommand on the pageHeader to first add a default item to the collection and then editing that default item. The user experience is less than great. I have yet to find a way to implement a delete. Any ideas would be greatly appreciated. Thank you.

**Comment by rickgregory1905** [comment]
I managed the delete. There is most likely a better way. But I added a delete event to my ModelBase implementation and then a handler in the viewModel when I loaded the collection. Then the xaml in the delete button looks like:  

```
<Button Content="Delete" Margin="8" >
    <Interactivity:Interaction.Behaviors>
      <Core:EventTriggerBehavior EventName="Click">
         <Core:CallMethodAction MethodName="DeleteThisItem" TargetObject="{Binding}"/>
         <Core:ChangePropertyAction PropertyName="SelectedItem" TargetObject="{Binding ElementName=List}" Value="{x:Null}" />
         <Core:ChangePropertyAction PropertyName="IsModal" TargetObject="{Binding ElementName=modalDialog}" Value="False" />
      </Core:EventTriggerBehavior>
   </Interactivity:Interaction.Behaviors>            
</Button>
```

I appreciate any feedback on the implementation.

**Comment by JerryNixon** [comment]
Don't be afraid to use code-behind. Just because my example does it all declaratively doesn't mean you have to. Sometimes it's easier in Csharp, that's all I am saying.

**Comment by JerryNixon** [comment]
Hey @rickgregory1905, I hate to say this, but I am not sure what you are asking. You wonder how to add and delete in the sample? I don't understand what you mean. I tell you what, I will add an Add and Delete feature to the sample and see if the diff strikes me.

**Comment by rickgregory1905** [comment]
Adding and removing from the User collection is where I was.

**Comment by JerryNixon** [comment]
Done

**Comment by rickgregory1905** [comment]
Nicely done. Thank you.
