### ISSUE TITLE
all Samples Error

### ISSUE THREAD

**Issue by lombo75** [Windows-XAML/Template10#538]
An exception of type 'System.Runtime.InteropServices.COMException' occurred in mscorlib.ni.dll but was not handled in user code

WinRT information: Cannot find a resource with the given key.

Additional information: Unspecified error

Error occures in bootstrapper.cs

var unused = Application.Current.Resources["ExtendedSplashBackground"];

**Comment by JerryNixon** [comment]
Thank you for this report. I see the error. Fixed in recent commit.
