### ISSUE TITLE
Mobile: hitting 'back' button after going to second page ('Minimal' template) causes app to exit

### ISSUE THREAD

**Issue by bc3tech** [Windows-XAML/Template10#54]
The same thing happens when using Template10Library's latest code in my own app as well. You can see the app quickly load the previous page, then exit out. Trapping all exceptions in VS halts on nothing so I'm at a loss at what the cause or solution could be...

To be clear I blew away my local repo, pulled down master, deployed `Minimal` to emulator _and_ device, and could produce this issue.

**Comment by JerryNixon** [comment]
I just committed the fix. There was a pull request that amended the navigation events. What I didn't notice was that it failed to navigate if it was unhandled. Now it works by default unless handled elsewhere. https://github.com/Windows-XAML/Template10/commit/fa8c57ed4cb71fdf2084ac43fa216b17460ef20e

**Comment by bc3tech** [comment]
'tis fixed! thanks.
