### ISSUE TITLE
PrelaunchActivated

### ISSUE THREAD

**Issue by MasterSkriptor** [Windows-XAML/Template10#540]
I am failing the store tests because my app does not handle the PrelaunchActivated Event. As far as I can tell this is something that should be handled in InternalLaunchAsync in the bootstrapper, or passed to OnStartAsync perhaps. Has anyone else had this issue, if it is posted already I apologize. I couldn't find any other references to it.

**Comment by callummoffat** [comment]
Have you tried submitting the package to the Store? My app fails the prelaunch activation test on my development PC every time, but it doesn't affect the Store submission. I should know, one passed certification about 3 minutes ago.

**Comment by MasterSkriptor** [comment]
No, I haven't. I have other more important issues with my app. The test pretty much says I should hire a developer... lol. It failed the crash and hangs test and I have to fix my badge logo that isn't white. For some reason I cant reproduce the crash or hang, and the minidump is useless.

**Comment by callummoffat** [comment]
You wouldn't believe the trouble I had getting my app working right. It's the never-ending cycle of frustration. Fix bug, break stuff, add feature, break stuff, change UI, break stuff, and so on...

**Comment by MasterSkriptor** [comment]
I made this app and put it on the store right when 10 hit market. Then I met Template10 at the MSAcademy. I skipped fixing the bugs and uglies on the app in order to build it with Template10 and use the MVVM pattern. I started months ago and the end result is I feel like a total noob.

**Comment by DarthPedro** [comment]
I've posed two apps built with Template10 without any certification issues. Are you doing something special in OnStartAsync?

**Comment by SiMoStro** [comment]
I'm using t10 for a very basic app - same certification issue with "App prelaunch" here; I don't need to submit it to the store but I need to release it internally.
The "App" class has been copy/pasted from the t10 documentation:

sealed partial class App : BootStrapper
{
    public App() { InitializeComponent(); }

```
public override Task OnStartAsync(StartKind startKind, IActivatedEventArgs args)
{
    NavigationService.Navigate(typeof(MainPage));
    return Task.FromResult<object>(null);
}

public override Task OnInitializeAsync(IActivatedEventArgs args)
{
    var nav = NavigationServiceFactory(BackButton.Attach, ExistingContent.Include);
    Window.Current.Content = new Shell(nav);
    return Task.FromResult<object>(null);
}
```

}

The error is:

App prelaunch

•Error Found: The app prelaunch validation detected the following errors:◦The app failed prelaunch test - 4d95fd40-b38d-4d1a-bf54-952297959786_1.0.3.0_x64__a47mn75dp5pfm.

•Impact if not fixed:  The app will take a longer time to launch, even when prelaunch is enabled. 

•How to fix: In the OnLaunched method implementation of the app, ensure you handle the LaunchActivatedEventArgs.PreLaunch option to be prelaunch event aware.

**Comment by MasterSkriptor** [comment]
I'm not at my machine currently, but my error is pretty much the same as above.

**Comment by MasterSkriptor** [comment]
I have not changed OnStartAsync. I pull my data in the MainPageViewModel, and have a background task that refreshes data from the web.

**Comment by MatthiasNistl** [comment]
Are you using the SplashFactory like in the minimal template? Implementing a splash fixed this for me. Without the splash my app failed the prelaunch-test, too.

```
public App()
{
        InitializeComponent();
        SplashFactory = (e) => new Views.Splash(e);
}
```

**Comment by MasterSkriptor** [comment]
Thanks, Matthias, I'll check that out.

**Comment by JerryNixon** [comment]
Crazy, we used to have Prelaunch support and I removed it. After talking with the team about this, their guidance was to ignore the state. Now I see WACK requires it. I will re-implement it.

**Comment by MasterSkriptor** [comment]
Thanks Jerry.

**Comment by diogorolo** [comment]
I'm still having the same problem with my app.
Did this fix your problem @MasterSkriptor ?

**Comment by diogorolo** [comment]
If I comment out the following code in the InternalLaunchAsync, it starts working again.

```
if ((e as LaunchActivatedEventArgs).PrelaunchActivated)
            {
                var continueStartup = false;
                await OnPrelaunchAsync(e, out continueStartup);
                if (!continueStartup)
                    return;
            }
```
