### ISSUE TITLE
XamlBehavior make navigation back stack repeat while NavigationCacheMode is Required or Enable

### ISSUE THREAD

**Issue by lyling** [Windows-XAML/Template10#541]
After update my template10 source code. 
I have found it need reference XamlBehavoir dll. 
And this will  cause an issue problem: 
make navigation back stack repeat while NavigationCacheMode is Required/Enable.

The lastest version of XamlBehavior 1.0.3 have still not update(someone have pull a  request to fix it ). 
https://github.com/Microsoft/XamlBehaviors/issues/52

any other solution to fix it before XamlBehavior release new verion ?

**Comment by pedrolamas** [comment]
Well, you can always take the code for the `EventTriggerBehavior` from here, copy to your project, and use that instead of the one provided by the NuGet package until someone actually pushes an update on the package!

**Comment by JerryNixon** [comment]
Would you please test with `Template10.Behaviors.NavToPageAction`?

**Comment by JerryNixon** [comment]
Assuming it works.
