### ISSUE TITLE
Correct way to show/hide HamburgerMenu at all (or what else?)

### ISSUE THREAD

**Issue by marcominerva** [Windows-XAML/Template10#543]
Hi!

In my app, I wuold like to show the entire hamburger menu only when the user arrives to a certain page (before that, the menu doesn't make sense). What it the correct way to do this? Is there a recommended approach?

**Comment by JerryNixon** [comment]
You want to hide/show the HamMenu on command? Not automatically?

**Comment by marcominerva** [comment]
Yes. When the user enters the app, the menu should be hidden. Then, after doing some actions and reaching a certain page (by normal navigation via NavigationService), the menu should be shown.

**Comment by JerryNixon** [comment]
This was not possible. I have added HamburgerMenu.HamburgerButtonVisibility and made HamburgerMenu.DisplayMode so that it can be written, not just read. Now you can do it, and I updated the BottomAppBar sample project to demonstrate how to do it.

**Comment by marcominerva** [comment]
Great! Thank you very much!
