### ISSUE TITLE
StringFormatConverter is not supporting custom language in Template10library

### ISSUE THREAD

**Issue by ganbayaru** [Windows-XAML/Template10#545]
I'm using your template10 library. Currently StringFormatConverter is not supporting my own language. Can you implement this one, Please?

**Comment by JerryNixon** [comment]
Tell me how to do it, and I will. Or, do you want to submit a PR?

**Comment by ganbayaru** [comment]
I'm using your convert function with below change. It is nice to me if it is implemented in template10Library

public object Convert(object value, Type targetType, object parameter, string language)
        {
            CultureInfo culture = new CultureInfo(language);
            string format = (parameter as string) ?? Format;
            if (format == null)
                return value;
            return string.Format(culture, format, value);
        }

**Comment by JerryNixon** [comment]
Terrific upgrade
