### ISSUE TITLE
Update Template10 .vsix

### ISSUE THREAD

**Issue by jhalbrecht** [Windows-XAML/Template10#548]
The Template Template10 1.5 vsix is not compatible with Template10 NuGet 1.1.0.

While attempting to upgrade a project I've been working on since on or about v 1 of Template10 to 1.1.0 I encountered a problem with 

``` csharp
        public override async Task OnInitializeAsync(IActivatedEventArgs args)
        {
            DispatcherHelper.Initialize();
            DispatcherHelper.CheckBeginInvokeOnUI(() => _utility.LanguageSelection()); // jha 
            // Task.Delay(500); // jha kludge while debugging to figure out culture nonUnderstandings
            // setup hamburger shell
            var nav = NavigationServiceFactory(BackButton.Attach, ExistingContent.Include);
                ^^^
            Window.Current.Content = new Views.Shell(nav);
            await Task.Yield();
        }
```

I receive error

```
Error   CS1503  Argument 1: cannot convert from 'Template10.Services.NavigationService.INavigationService' to 'Template10.Services.NavigationService.NavigationService' Decisive.Uwp.T10    
```

So I built a minimal Template10 project from the 1.5 version of the template installed in VS 2015 to help me debug. Inspecting the project.json I note that an earlier version of Template10 is called for. I change that to 1.1.0 and get the same error as my app. Also the Template10 Template 1.5 is using the BehaviorsXamlSDKManaged rather than the NuGet Microsoft.Xaml.Behaviors.Uwp.Managed

```
  // "Template10": "1.0.*",
    "Template10": "1.1.0"
```

**Comment by byrialsen** [comment]
Hi.
I had similar problems when upgrading my existing project to v1.1.0. From my findings I think you can do something like this to make it work:
1. Use NuGet to uninstall previous version of Template10 (v1.0.8 in my case)
2. Remove reference to "BehaviorsXamlSDKManaged".
3. Use NuGet to install Template10 (v1.1.0)
4. Use NuGet to install NuGet Microsoft.Xaml.Behaviors.Uwp.Managed
5. In the Shell.Xaml.cs code change the constructor header to:

``` csharp
public Shell(INavigationService navigationService)
```

I might have forgotten something in the above description, but hopefully it will help.

**Comment by jhalbrecht** [comment]
Thanks. That ctor change fixed it.

Template .vsix does need update though.

**Comment by MichaelPetrinolis** [comment]
Maybe the vsix is not uploaded to vs extensions yet. As @jerryNixon mentioned, will also be updated @jerrynixon
Template 10 is skipping v1.0.9, we're jumping to 1.1.0.
Templates will be updated. 10240 &amp; 10586 are both supported. https://t.co/EBNEbTSjb1

https://twitter.com/jerrynixon/status/690052952183169024

**Comment by jhalbrecht** [comment]
Oops, sorry Jerry I forgot you mentioned that the Template10 .vsix would be updated.
