### ISSUE TITLE
Navigate with page key and parameter throws JsonSerializationException

### ISSUE THREAD

**Issue by craigktreasure** [Windows-XAML/Template10#549]
I updated to 1.1.0 today and am still trying to get my app back up.

I use page keys in my navigations:

```
NavigationService.Navigate(Pages.Settings, /* Pivot index */ 2);
```

After calling this, a JsonSerializationException is thrown:

```
Newtonsoft.Json.JsonSerializationException: Error converting value 2 to type 'Template10.Services.SerializationService.JsonSerializationService+Container'. Path '', line 1, position 1. ---> System.ArgumentException: Could not cast or convert from System.Int64 to Template10.Services.SerializationService.JsonSerializationService+Container.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrC
```

Out of curiosity, I changed my navigation method to:

```
NavigationService.Navigate(typeof(Views.SettingsPage), /* Pivot index */ 2);
```

Now, my page navigates, but the parameter i receive in the view is a string that looks like the following:

```
{"Type":"System.Int32, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e","Data":"2"}
```

Neither navigation method with a parameter seems to work properly at this point. Am i missing something? Anything else i need to do in the 1.1.0 upgrade?

**Comment by JerryNixon** [comment]
I'll check into this. We'll fix this right away if it is a bug.

**Comment by JerryNixon** [comment]
Okay, navigation by key was broken. I will release Nuget 1.1.1 with this correction. As for OnNavigateTo, you are clearly talking about Page.OnNavigatedTo not ViewModel.OnNavigatedTo. I think you will find ViewModel.OnNavigatedTo works perfectly. This has to do with how Suspend/Resume works with Template 10. Using Page.OnNavigated is not a best practice, but you can still do it with this code:

``` csharp
var p = Template10.Services.SerializationService.SerializationService
    .Json.Deserialize<int>(e.Parameter?.ToString());
```

**Comment by craigktreasure** [comment]
@JerryNixon The Minimal template SettingsPage.xaml.cs uses Page.OnNavigatedTo in the same way i am, so i assume that needs to be updated as well.
https://github.com/Windows-XAML/Template10/blob/f0dcaaaf477f73cae48ed2a7be5e4c753ed6461e/Templates%20(Project)/Minimal/Views/SettingsPage.xaml.cs
