### ISSUE TITLE
Mobile: Splash page isn't functional

### ISSUE THREAD

**Issue by bc3tech** [Windows-XAML/Template10#55]
1. blows image way up and offsets nearly out of view
2. progress icon doesn't show

I'm playing with a couple of changes to possibly fix this, but they'll be targeted at Mobile.

**Comment by bc3tech** [comment]
Looks like the `resize()` action/wireup is the problem. If I take that out, the image looks good on the screen. and the progress ring sits in the right spot as well.

**Comment by JerryNixon** [comment]
Possible error, one we observed in pre-release, was that splashscreen.Bounds was 0,0 all the time. A work around will be to not use resize() when it is detected as 0,0. A little bit of a hack, though. Even still, it might be the only thing we could do. Will you check?

**Comment by bc3tech** [comment]
will do.

**Comment by nguyenquyhy** [comment]
I have filed the same issue in the SplashScreen sample of Windows-Universal-Samples repo. Basically the reported splash screen size on mobile is the raw size without applying scale factor while on PC, the reported size is the scaled size. I would really like to know if this behavior will be fixed before RTM or not.

**Comment by bc3tech** [comment]
@JerryNixon I'm mostly blocked by the issue I mentioned on twitter; I think the splash screen's got something going on with it.

For example, when I change this line in Minimal's App.xaml.cs:
`await Task.Delay(50);`
(which waits for only 50ms)

to
`await Task.Delay(50000);`
(wait for 50 **seconds**)

it doesn't make a bit of a difference in how long the splash is shown... Looks like it might be something that was caused by a recent code change. commits I pulled this weekend have the delay working...

**Comment by bc3tech** [comment]
I can, however, confirm that

```
                if (splashScreen.ImageLocation.Left != 0 || splashScreen.ImageLocation.Top != 0)
                {   // https://github.com/Windows-XAML/Template10/issues/55
                    MyImage.Height = splashScreen.ImageLocation.Height;
                    MyImage.Width = splashScreen.ImageLocation.Width;
                    MyImage.SetValue(Canvas.TopProperty, splashScreen.ImageLocation.Top);
                    MyImage.SetValue(Canvas.LeftProperty, splashScreen.ImageLocation.Left);
                    ProgressTransform.TranslateY = MyImage.Height / 2;
                }
```

causes the image to not be resized out of view on mobile and lets everything look nice.

**Comment by JerryNixon** [comment]
Fixed it.
