### ISSUE TITLE
Minimal Template: Settings navigation parameter isn't handled properly anymore

### ISSUE THREAD

**Issue by craigktreasure** [Windows-XAML/Template10#551]
The Minimal template SettingsPage.xaml.cs uses Page.OnNavigatedTo to get the pivot index. It appears that 1.1.0 changes have caused the parameter to be serialized when passed to the Page.OnNavigatedTo parameter value. This means the parameter will never be parse correctly. Jerry noted in #549 that you can use the following to handle the parameter:

``` C#
var p = Template10.Services.SerializationService.SerializationService
    .Json.Deserialize<int>(e.Parameter?.ToString());
```

**Comment by calloncampbell** [comment]
+1. Getting this issue with existing Minimal projects and also for new Minimal projects.

**Comment by schuettecarsten** [comment]
That's why I liked the "DefaultSerializationService" ;)
