### ISSUE TITLE
Minimal Template - cannot convert from 'Template10.Services.NavigationService.INavigationService' to 'Template10.Services.NavigationService.NavigationService'

### ISSUE THREAD

**Issue by calloncampbell** [Windows-XAML/Template10#556]
Getting the following error after upgrading to v1.1.0 from v1.0.8:

Error   CS1503  Argument 1: cannot convert from 'Template10.Services.NavigationService.INavigationService' to 'Template10.Services.NavigationService.NavigationService' Template10App3  C:\Users\ccampbell\Documents\Visual Studio 2015\Projects\Template10App3\App.xaml.cs 39  Active

I can replicate this issue with a brand new Minimal template project.

**Comment by callummoffat** [comment]
This is a known issue. The Minimal template in the Gallery has not yet been updated so that 1.1.0 is supported. The problem is that in 1.1.0 the references to NavigationService (look in App.xaml.cs & Shell.xaml.cs) need to be replaced with references to INavigationService. Once the templates have been updated with the latest code, this won't be a problem anymore.

**Comment by calloncampbell** [comment]
I manually updated the reference to INavigationService and this initially showed no issues in the project. However when I rebuild the project I get 23 errors similar to this. Now maybe I'm missing something or perhaps I just need to wait for the Minimal Template to be updated.

Error   CS0433  The type 'Interaction' exists in both 'Microsoft.Xaml.Interactivity, Version=12.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Microsoft.Xaml.Interactivity, Version=1.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'  

I'm running Visual Studio 2015 with Update 1. I've tried rebooting and I've tried cleaning the project.

**Comment by callummoffat** [comment]
Ah, there's the other thing. You need to remove the references to the Behaviors SDK (XAML). Then, clean the project and rebuild it. Then, that should do it. Also, there are a few references to NavigationService that will definitely  need replacing in your app, as I recall. Check for them.

**Comment by calloncampbell** [comment]
Ok thanks, I'll try this out. 

Any idea when the templates in the gallery will be updated to v1.1.0?

**Comment by callummoffat** [comment]
No clue. You'd have to ask @JerryNixon.

**Comment by calloncampbell** [comment]
Hey @JerryNixon, thanks for releasing v1.1.0. Now that it's out, when can we expect the template projects to be updated to support it? After updating to the latest my app is broken (see above).

**Comment by callummoffat** [comment]
I'd expect them to be updated fairly quickly. Not sure exactly how quickly, but I'd expect them within two weeks at the most, and almost certainly less.

**Comment by calloncampbell** [comment]
Thanks @callummoffat for your help. I'll probably rollback to v1.0.8 over the weekend to continue my development and wait for v1.1.0 to be fully released.

**Comment by angusbreno** [comment]
Same thing here @calloncampbell... Don't need to rollback... Just workarround with this 

```
...NavigationService = (NavigationService)navigationService;
```

**Comment by byrialsen** [comment]
Hi. I think this can help you for now: https://github.com/Windows-XAML/Template10/issues/548

**Comment by calloncampbell** [comment]
Thanks @byrialsen that helped.

**Comment by JerryNixon** [comment]
Terrific help @callummoffat 

This might also help: https://github.com/Windows-XAML/Template10/wiki/Upgrading-from-Template-10-Nuget-1.0-to-1.1

The templates will be updated today if I can get the VSIX to build with Update 1 (not yet) :(

**Comment by jhalbrecht** [comment]
@JerryNixon  Any objections to adding 'Upgrading from previous versions' to the main wiki page?

Markdown:

``` Markdown
## Upgrading from a previous version of Template 10
*[Upgrading from Template 10 Nuget 1.0 to 1.1]

[Upgrading from Template 10 Nuget 1.0 to 1.1]:https://github.com/Windows-XAML/Template10/wiki/Upgrading-from-Template-10-Nuget-1.0-to-1.1
```
