### ISSUE TITLE
Hamburger Menu problem when using the HamburgerButtonVisibility property

### ISSUE THREAD

**Issue by marcominerva** [Windows-XAML/Template10#559]
I'm using the HamburgerButtonVisibility property to initially hide the Hambuger Menu at app startup. Then, when I navigate to a certain page, I set this property to Visible and the button menu correctly appears. However, if at this point I tap on the button, it slides in for less than a microsecond and then automatically closes. The second time I tap on it, it's content is shown correctly.

**Comment by JerryNixon** [comment]
The hamburger menu appears to raise its loaded event considerably earlier than the internal behaviors are wired up to watch for property changes. Would you test for me if this helps your situation?

```
WindowWrapper.Current().Dispatcher.Dispatch(() => 
{ 
    Views.Shell.HamburgerMenu.HamburgerButtonVisibility = Windows.UI.Xaml.Visibility.Collapsed; 
}, 1000);
```

**Comment by marcominerva** [comment]
Unfortunately this doesn't help me. I have made a small video to better explain the situation: http://1drv.ms/1nrnNtd. In particular, I change the HamburgerMenuButtonVisibility property to Visible in the OnNavigatedTo method of the Main page.

**Comment by JerryNixon** [comment]
Video missing.
