### ISSUE TITLE
BREAKING CHANGE in Nuget version 1.1.1

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#560]
Dear @Windows-XAML/community and @Windows-XAML/contributors,

Yes, the following changes have been introduced. We intended to introduce these changes in 1.1.0 but the commit completely flew under our radar. Yes, this is annoying, but, yes, this is important. Forgive your volunteer development team for this mistake. Best regards, Jerry Nixon

The signature of `INavigable` has changed

``` csharp
Task OnNavigatedToAsync(object parameter, NavigationMode mode, IDictionary<string, object> state);
Task OnNavigatedFromAsync(IDictionary<string, object> state, bool suspending);
Task OnNavigatingFromAsync(NavigatingEventArgs args);
INavigationService NavigationService { get; set; }
IDispatcherWrapper Dispatcher { get; set; }
IStateItems SessionState { get; set; }
```

The changes are:
1. `void OnNavigatedTo` -> `Task OnNavigatedToAsync`
2. `void OnNavigatingFrom` -> `Task OnNavigatingFromAsync`

This will impact your view-models. Many view-models whose overrides are not `async` will need to add `return Task.CompletedTask;` to the end of their method blocks. 

Changes relating to Prelaunch:
1. Bootstrapper changed `void OnPrelaunch` to `Task OnPrelaunchAsync`.
2. `BootStrapper.OnResuming(s, e, ApplicationExecutionState)` has been changed to `OnResuming(s, e, AppExecutionState)` - a custom enum.

Please believe me, these should have been introduced in version 1.1.0 released three days ago. Many of you are aggressive adopters of Template 10. Thank you. I'm sorry these changes will impact you. If anyone sees reference to the old approach in the wiki, please make those changes. I will work through the docs next week to see what might need to be updated, too.

Listen, breaking changes like this are not taken lightly - introducing breaking changes without incrementing the middle version number is not our policy. But if we had not done it now, we would have either had to have waited until late June (limiting the future direction of Template 10) or it would have only been painful to even more apps upgrading next week or so. Thanks again for understanding, testing Template 10, and contributing so many great pull requests. It's a team effort.

Best regards,
Jerry

PS: Project template updates are delayed because the VSIX proj in VS 2015 update 1 has changed. We'll get it worked out, but our existing mechanisms aren't working. (See, even MSFT releases breaking changes :)) I should have the new templates ready early next week - even though I planned on last week. Again, thanks for your patience.  

Also, have you run the Validation project lately? I'm pretty proud of it. :)

**Comment by johanlindfors** [comment]
I noticed when installing the nuget v1.1.1 packages of Template 10 that it requires Newtonsoft.Json (crashes when trying to run without it), but that hasn't been specified as a nuget dependency, isn't that a bug?

**Comment by jp-weber** [comment]
I have seen that issue #410 / https://github.com/Windows-XAML/Template10/issues/410#issuecomment-170153834 was not fixed.

**Comment by robertmuehsig** [comment]
I have a pretty basic application and just updated to v1.1.1 and get this error

Error	CS1503	Argument 1: cannot convert from 'Template10.Services.NavigationService.INavigationService' to 'Template10.Services.NavigationService.NavigationService'	ExpensiveMeeting.WinApp	C:\Dev\GitHub\ExpensiveMeeting\ExpensiveMeeting.WinApp\App.xaml.cs	36	Active

Line 36 is "new Views.Shell(nav)". Any hints?

        // runs even if restored from state
        public override async Task OnInitializeAsync(IActivatedEventArgs args)
        {
            // setup hamburger shell
            var nav = NavigationServiceFactory(BackButton.Attach, ExistingContent.Include);
            Window.Current.Content = new Views.Shell(nav);
            await Task.Yield();
        }

**Comment by robertmuehsig** [comment]
Another problem: I got this strange exception:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'Interaction' exists in both 'Microsoft.Xaml.Interactivity, Version=1.0.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' and 'Microsoft.Xaml.Interactivity, Version=12.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'	ExpensiveMeeting.WinApp	C:\Dev\GitHub\ExpensiveMeeting\ExpensiveMeeting.WinApp\obj\x86\Debug\XamlTypeInfo.g.cs	292	Active

**Comment by ScottIsAFool** [comment]
@robertmuehsig for the Microsoft.Xaml.Interactivity error, you need to remove the Behaviours SDK reference and add the Nuget Package, as per the notes here https://github.com/Windows-XAML/Template10/wiki/Upgrading-from-Template-10-Nuget-Nuget-1.0-to-1.1

**Comment by robertmuehsig** [comment]
Ok, my application runs. One last minor issue that I found is 0that the StringConverter now doesn't return what I expect:

```
                <TextBlock Margin="0,8,0,8" HorizontalAlignment="Center" FontSize="42" FontWeight="Bold" Text="{Binding MoneyBurndownCounter, Converter={StaticResource StringFormatConverter}, ConverterParameter='{}{0:C2}'}" />
```

This should return something like "$50.00" (depending on the region setting)

But I get this:
![image](https://cloud.githubusercontent.com/assets/756703/12532457/098e8e0c-c215-11e5-8cc0-97ab682e2eba.png)

Any idea?

Sorry for my previous questions, didn't know that there was a wiki page that describes the update.

**Comment by callummoffat** [comment]
Hey @JerryNixon, I have a question. What makes these changes so good? What's the reasoning behind them? As far as I can tell, there isn't much difference. What are the benefits?

**Comment by JerryNixon** [comment]
@callummoffat, there's no way your app runs slower. Send me your diagnostics output that shows me that. Otherwise, don't post that your app runs slower. The benefits are for future changes. The only current benefit is calling Bindings.Initialize after ViewModel.OnNavigatedTo. Without a reference to the page in your view-mode there is no way for developers to accomplish this same important step.

**Comment by JerryNixon** [comment]
@johanlindfors, what new requirement for Newtonsoft?

**Comment by callummoffat** [comment]
Whoops! Problem appears to be that my development PC was bogged down at the time. Sorry. So, the view model changes are for the benefit of future updates. What about the change from void OnPrelaunch(...) to Task OnPrelaunchAsync(...)? What are the benefits of that?

**Comment by johanlindfors** [comment]
@JerryNixon I created a new Universal App (standard template, not Template10) and added the nuget-package for v1.1.1. Changed the App to inherit from BootStrapper and implemented a simple OnStartAsync navigating to MainPage. The application crashes in runtime complaining about missing the Newtonsoft dll's. 

If Newtonsoft is a requirement for Template10, shouldn't it's package then be added when I add the Template10 package?

**Comment by kenakamu** [comment]
After v1.1.1, when I pass non-string parameter, passed object type is different from original.
For example, if I pass int, then it becomes long, and if I pass Guid, It becomes string,
I am passing parameter as List<object> as I need to pass multiple values. Any idea where the value has been casted or did I miss anything?

``` C#
List<object> parameters = new List<object>();
// passing int value
parameters.Add(objectTypeCode);
// Passing Guid
parameters.Add(record.Id);
// Go to EntityRecord page.
NavigationService.Navigate(typeof(EntityRecordPage), parameters);
```

When I get the parameter in the target viewmodel, 

``` C#
public override async System.Threading.Tasks.Task OnNavigatedToAsync(object parameter, NavigationMode mode, IDictionary<string, object> state)
{
   List<object> parameterList = (List<object>)parameter;
   // this is now long
   var objecttypecode = parameterList[0];
   // this is string now
   var id = parameterList[1];
}
```

**Comment by schuettecarsten** [comment]
@JerryNixon Maybe it's time to bring back the "DefaultSerializationService" as defaultas suggested in my original Pull Request? Json as default is a great idea, but I think there are too many issues with this breaking change.

**Comment by robertmuehsig** [comment]
BTW: We use the JsonSerializer from Json.NET heavily in our own app and don't face such issues. You can set plenty of serialization options (like full type names etc.) - I don't know which are used here.

**Comment by schuettecarsten** [comment]
@robertmuehsig Take a look into JsonSerializationService. Any ideas how to improve it?

**Comment by robertmuehsig** [comment]
@carstenschuette One one would be to use the [TypeNameHandling.Auto](http://www.newtonsoft.com/json/help/html/SerializeTypeNameHandling.htm). With this in place JSON.NET will store type information. The problem is, that the receiving List<object> is hard to guess for JSON.NET, thats why the GUID will be served as a string. WIth the Type stored, JSON.NET can create the correct type.
But this may lead to other problems, e.g. refactorings will "destroy" any state from V1 to VNext.

**Comment by rickengle** [comment]
Hi, where is the bootstrapper code that needs to be fixed up?  I don't see this anywhere in my Minimal project:
Changes relating to Prelaunch:
1.Bootstrapper changed  void OnPrelaunch  to  Task OnPrelaunchAsync .
2.  BootStrapper.OnResuming(s, e, ApplicationExecutionState)  has been changed to  OnResuming(s, e, AppExecutionState)  - a custom enum.

Thanks,
  Rick

**Comment by robertmuehsig** [comment]
I found another breaking change: The current StringConverter might use InvariantCulture instead of the system culture. See here: https://github.com/Windows-XAML/Template10/pull/568

**Comment by wstaelens** [comment]
oh boy, all these changes... :( #monday

**Comment by mattiascibien** [comment]
It seems that pageheader class does not work:

```
An exception of type 'Windows.UI.Xaml.Markup.XamlParseException' occurred in App.exe but was not handled in user code

WinRT information: Cannot create instance of type 'Template10.Controls.PageHeader' [Line: 17 Position: 30]
```

The xaml is just 

```
 <controls:PageHeader Text="Mp3 Tag Editor" Frame="{x:Bind Frame, Mode=OneWay}">

        </controls:PageHeader>
```

Exception:

```
Additional information: Cannot find the text associated to this error code (translated from Italian)
```

**Comment by schuettecarsten** [comment]
@robertmuehsig For JsonSerializerSettings, what do you think of https://github.com/Windows-XAML/Template10/pull/571 and the default settings there?

**Comment by robertmuehsig** [comment]
@carstenschuette Mhh... could work. Would this fix the problem (https://github.com/Windows-XAML/Template10/issues/560#issuecomment-174304038)? Didn't tried it - I'm just guessing ;)

**Comment by schuettecarsten** [comment]
@robertmuehsig I also did not test the specific case, but I hope so :)
