### ISSUE TITLE
HamburgerMenu requires two clicks to open on phone

### ISSUE THREAD

**Issue by mikaelp74** [Windows-XAML/Template10#561]
I have an issue on Phone that the HamburgerMenu seams to be open but not visible when I start the app. When I click the HamburgerButton the first time I can see the animation for closing the menu and it close instead of open.

I have the issue both on emulator and my device running lates version of W10. To make sure it wasn't anything I have done in my app I downloaded the Template10 solution and I get this behavior when running the minimal project with no code changes. 

Is there something I should change or do differently to not get this?

**Comment by DarthPedro** [comment]
I've seen this as well. It always happens after first launch on the emulator, and I can repro it on a physical device too. It happens all of the time on one my apps, and inconsistently on the other.

**Comment by luiscantero** [comment]
I can repro on a physical device using v1.1.1 as well.

**Comment by JerryNixon** [comment]
Isn't this a repeat of another issue? This was already resolved, but I can't find the old issue to see how I resolved it. Anybody find it?

**Comment by JustinXinLiu** [comment]
#410 This one?

**Comment by jp-weber** [comment]
Yes it is #410, and the fix is: 

private void SetSelected(HamburgerButtonInfo previous, HamburgerButtonInfo value)
{
    if (previous != null)
        IsOpen = false;
...

but not implemented:
https://github.com/Windows-XAML/Template10/blob/master/Template10%20%28Library%29/Controls/HamburgerMenu.xaml.cs#L432

**Comment by JerryNixon** [comment]
@JustinXinLiu  and @revan1199 thanks for your help. I have returned this if statement. I can't be the first developer to remove code that when he looks at it months later without remembering why it is there, removes it only to recreate a bug that it fixed! :) 1.1.2 will have it in it.
