### ISSUE TITLE
CommandBar with IsOpen=True hides SettingsButton in v1.1.1

### ISSUE THREAD

**Issue by luiscantero** [Windows-XAML/Template10#562]
In v1.0.8, the following code displays a bottom command bar that is open when the app loads:
&lt;Page.BottomAppBar&gt;
        &lt;CommandBar IsOpen=&quot;True&quot;&gt;
            &lt;CommandBar.PrimaryCommands&gt;
                &lt;AppBarButton Icon=&quot;Accept&quot; Label=&quot;Accept&quot;/&gt;
                &lt;AppBarButton Icon=&quot;Account&quot; Label=&quot;Account&quot;/&gt;
            &lt;/CommandBar.PrimaryCommands&gt;
        &lt;/CommandBar&gt;
    &lt;/Page.BottomAppBar&gt;

After upgrading to 1.1.1, the settings button is no longer visible when IsOpen="True".

**Comment by JerryNixon** [comment]
Please review the BottomAppBar sample project for how to handle this.
