### ISSUE TITLE
Designer issues with Template10 in Blend/VS 2015

### ISSUE THREAD

**Issue by rickengle** [Windows-XAML/Template10#563]
I ran into some issues with the Minimal Template 10 template.   On the shell.xaml page there is no design preview of the symbols on the hamburger menu.  It doesn't show the Home or Settings symbol.
I tried loading the project in Blend ( i am using Visual Studio 2015) but while there were no errors in VS 2015, in Blend I get all of these errors:
Severity    Code    Description Project File    Line    Suppression State
Error       The name "Interaction" does not exist in the namespace "using:Microsoft.Xaml.Interactivity".    i3RemoteWP_Universal2   C:\Users\ricke\Documents\files\dev\i3\i3RemoteWP_Silverlight\i3RemoteWP_Universal2\i3RemoteWP_Universal2\Views\MainPage.xaml    60  
Error       Property 'Behaviors' is not attachable to elements of type 'PageHeader'.    i3RemoteWP_Universal2   C:\Users\ricke\Documents\files\dev\i3\i3RemoteWP_Silverlight\i3RemoteWP_Universal2\i3RemoteWP_Universal2\Views\MainPage.xaml    60  
Error       The name "Interaction" does not exist in the namespace "using:Microsoft.Xaml.Interactivity".    i3RemoteWP_Universal2   C:\Users\ricke\Documents\files\dev\i3\i3RemoteWP_Silverlight\i3RemoteWP_Universal2\i3RemoteWP_Universal2\Views\MainPage.xaml    80  
Error       Property 'Behaviors' is not attachable to elements of type 'TextBox'.   i3RemoteWP_Universal2   C:\Users\ricke\Documents\files\dev\i3\i3RemoteWP_Silverlight\i3RemoteWP_Universal2\i3RemoteWP_Universal2\Views\MainPage.xaml    80  
Error       The name "CallMethodAction" does not exist in the namespace "using:Microsoft.Xaml.Interactions.Core".   i3RemoteWP_Universal2   C:\Users\ricke\Documents\files\dev\i3\i3RemoteWP_Silverlight\i3RemoteWP_Universal2\i3RemoteWP_Universal2\Views\MainPage.xaml    82  
Error       The name "EventTriggerBehavior" does not exist in the namespace "using:Microsoft.Xaml.Interactions.Core".   i3RemoteWP_Universal2   C:\Users\ricke\Documents\files\dev\i3\i3RemoteWP_Silverlight\i3RemoteWP_Universal2\i3RemoteWP_Universal2\Views\MainPage.xaml    84  

Why would these errors show up in Blend but not in VS 2015?
Also in VS 2015 the design surface crashes often with this error:
System.Runtime.Remoting.RemotingException
[13540] Designer process terminated unexpectedly!

Any idea what the causes of all of these issues are?

Thanks,
  Rick

**Comment by JerryNixon** [comment]
Please read the Wiki on upgrading to 1.1
