### ISSUE TITLE
Separate OnNavigatedFromAsync into SaveStateAsync and OnNavigatedFromAsync

### ISSUE THREAD

**Issue by mitkodi** [Windows-XAML/Template10#565]
If we wrote something into state in **OnNavigatedFromAsync** when we're navigating to a new page:
- it would be waste of time/resources to write something that would be followed by its deletion.
- it's a misleading to provide a parameter (state) that actually would be cleared by the caller.

Proposal.
Separate the current **OnNavigatedFromAsync** into two methods:
- **SaveStateAsync(IDictionary<string, object> state, bool suspending)**, which will be called only when the state will be preserved.
- **OnNavigatedFromAsync()**

**Comment by JerryNixon** [comment]
How will state get cleared?

**Comment by mitkodi** [comment]
As at the moment (on navigating to a new page), but in this case SaveSateAsync won't be called.

**Comment by JerryNixon** [comment]
Okay, here's what I have done. When Navigating to a New page, that page type's state is cleared. This is different from what was before, clearing every page's state. Good catch. Check that this helps you.

**Comment by mitkodi** [comment]
Thanks @JerryNixon
