### ISSUE TITLE
Isn't source code on GitHub updated?

### ISSUE THREAD

**Issue by marcominerva** [Windows-XAML/Template10#566]
Hi!

If I go to https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Services/NavigationService/INavigable.cs, I see the old version of the INavigable interface, while if I download the 1.1.1 version from NuGet, I get the new version with async methods.

Am I missing something, or the source code on GitHub doesn't correspond to the NuGet bits?

**Comment by JerryNixon** [comment]
I have sync'ed now. Sorry. Rebuilt my desk, machine has been off for a while. Forgot to sync before starting. Thanks, @marcominerva
