### ISSUE TITLE
Post-Build-Step

### ISSUE THREAD

**Issue by schuettecarsten** [Windows-XAML/Template10#569]
Please remove the Post-Build step from Template10 (Library) or make sure that it only runs when NuGet packages are build:

``` csharp
call "$(ProjectDir)\Nuget\Build.cmd" "$(TargetDir)" "$(TargetName)" "$(ProjectDir)"
call "$(SolutionDir)\Snippets\InstallSnippets.cmd"
```

**Comment by JerryNixon** [comment]
What's the problem you are solving?

**Comment by schuettecarsten** [comment]
I am including T10 source code from GitHub into my projects and do not want to have Nuget packages created and snippets installed on each (debug) build.

**Comment by gsantopaolo** [comment]
+1 same here. If you add a reference directly to the source of t10 library you will be able to reproduce the issue

**Comment by JerryNixon** [comment]
Well. This is pretty helpful to me. But I am willing to consider alternatives. Suggestions?

**Comment by schuettecarsten** [comment]
Will add a PR with a nice solution soon :)
