### ISSUE TITLE
ISupportIncrementalLoading: Pivot and Navigations

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [Windows-XAML/Template10#570]
Hi everyone,
I understand this is not a T10 issue, but would be nice to have a solution and may be provide default implementation in T10.
The issue I get is with using multiple GridView/ListViews in different Pivots and pages. I've watched the following behavior:
1) Loading is started in one collection by GridView.
2) You change pivot item before loading is completed
Expected behavior: the ISuportIncrementalLoading doesn't get called by not visible GridView
Result: the collection loads infinitely unless you navigate back to it or it has HasMore == false.
And that is a real pain.
With page navigation I know to forcefully stop loading, but with pivot I literally don't want to have code behind for each PivotItem to stop loading it's collection when I navigate from it.
May be someone has a solution suggestion for this?

**Comment by JerryNixon** [comment]
Would it work if you simply handled the Pivot.SelectedIndexChanged, keeping a reference to the previous selected index (PivotItem) and if it is your list item then you cancel loading?

**Comment by Viachaslau-Zinkevich** [comment]
@JerryNixon I believe this would help, but would mean couple UI implementation details with VM, which I hoped I could avoid..

**Comment by JerryNixon** [comment]
Use messaging if it bothers you too much.
