### ISSUE TITLE
HamburgerMenu - Visibility issue

### ISSUE THREAD

**Issue by mvermef** [Windows-XAML/Template10#577]
My setup initial Window.Current.Content = Views.LoginPage(nav) where nav == INavigationService (even before the release of 1.1.1), this worked as desired. Which was to prevent from showing the Hamburger menu (split content) until the user was authenticated.

 Now when I show the window, work thru the login process, it does not sure the HamburgerMenu at all, it will show the Location when you resize down to where you would expect it at a really small screen size.  The location is just a 48x48 box nothing more with background its as if the control doesn't want to show up or never existed.

The login page also facilitated account creation and a potential for password reset flows.

Would there be a better way...  btw figured out the validation after finally paying attention to the DataContext :(

**Comment by JerryNixon** [comment]
How can I repro this to test?

**Comment by mvermef** [comment]
Here ya go... This is using current source (not nuget) since I needed Services and Validation.  This http://1drv.ms/1OTOBsv  is still work in progress.  One thing I did notice was a flash of the HamburgerMenu and it disappearing.  For the UserName as long as it starts with 70 and 5 more digits following you will satisfy the Regex..

**Comment by mvermef** [comment]
I did test out whether or not that the Shell being the starting content would make a different and it does!

**Comment by schuettecarsten** [comment]
@mvermef Have you tried the IsFullScreen property of the HamburgerMenu?

**Comment by mvermef** [comment]
It wasn't present but it shouldn't make any difference related to this situation since shell vs login shouldn't cause a difference whether I was going to shell directly or login. This is the case of login > shell content assignment for current window, hamburgermenu should've worked correctly on Shell being assigned to the current content once login logic was satisfied.

**Comment by mvermef** [comment]
Deeper look via the debugger and WindowWrapper.Current() still shows LoginPage as the main content even after assignment of the Shell() to the current content.  This is actually correct, ironically :(.  Based on logic in the BootStrapper for the Inclusion of "Existing Content" the developer wins, so by starting off with LoginPage and trying to "inject" Shell as the new content, I lose.  Something changed from version 1.0x to 1.1x where it worked previously.

**Comment by JerryNixon** [comment]
I am only following your problem 90% here. But hey, could you take a look at the Search and Login sample and see if that approach would help you? It's far simpler than swapping content.

**Comment by mvermef** [comment]
I have started to converted over to this, actually but came across a little confusion with how to handle initial startup and how to handle if user was already logged in.. getting closer every minute I play with the logic...  But I still see the previous code setup with Content swapping a bug.
