### ISSUE TITLE
TextBoxEnterKeyBehavior - When binding to a command in the viewmodel Text bindings aren't updated

### ISSUE THREAD

**Issue by eshy** [Windows-XAML/Template10#578]
The Text property is only updated once the control loses focus, which happens after the enter key command is executed. 

I've solved this in the past by adding a Text property to the behavior itself (to get the text property updated in the view model on every keystroke)

Here's the change I've made. 
https://github.com/eshy/Template10/commit/74a802e0503f3abc2f941c418962bd2399e67867

All you need to do is move the Text binding from the TextBox to the behavior:

```
                <TextBox >
                    <interactivity:Interaction.Behaviors>
                        <behaviors:TextBoxEnterKeyBehavior Text="{Binding ViewModelProperty, Mode=TwoWay}">
                            <core:InvokeCommandAction Command="{Binding ViewModelCommand}"/>
                        </behaviors:TextBoxEnterKeyBehavior>
                    </interactivity:Interaction.Behaviors>
                </TextBox>
```

Is there a better way of doing it?

**Comment by janabimustafa** [comment]
Text={Binding ViewModelProperty, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}

**Comment by eshy** [comment]
Thanks, that's much better
