### ISSUE TITLE
Messenger missing doc/sample

### ISSUE THREAD

**Issue by JurajPupak** [Windows-XAML/Template10#579]
Hi,
I've started to use Template10 for our UWP application. I read, it supports messaging, but I dont see any sample how to use it. I need to communicate between 2 ViewModels and messenger is good solution for it.
thanks for answer

**Comment by JerryNixon** [comment]
Yeah, I was thinking the same thing. I added a sample.

**Comment by AuroraDysis** [comment]
https://github.com/waynebaby/MVVM-Sidekick/blob/master/MVVMSidekick/MVVMSidekick.Shared/EventRouting.cs
