### ISSUE TITLE
Sample Universal App: DueDate property not handled correctly

### ISSUE THREAD

**Issue by IdeaScripter** [Windows-XAML/Template10#58]
1. DueDate not stored in TodoItemRepository.Factory-Method:
   something like "DueDate = dueDate ?? DateTime.Today" is missed there
2. Notification about property changes on DateTime seems not to work correctly:
   Changes made on DueDate via TodoItemEditor.xaml is not stored. After opening edit dialog again old DueDate appears again.

**Comment by JerryNixon** [comment]
We're deleting Sample until we finish the Templates.
