### ISSUE TITLE
How can I access the currently visible page when using HamburgerMenu

### ISSUE THREAD

**Issue by realworld666** [Windows-XAML/Template10#581]
When I was rolling my own HamburgerMenu I was able to get the current page with this dodgy bit of code. 

```
internal static T GetCurrentPage<T>()
{
    var shell = Window.Current.Content as Shell;
    var split = shell.Content as SplitView;
    var frame = split.Content as Frame;
    var page = (T)frame.Content;
    Debug.Assert(page != null);

    return page;
}
```

Now I've switched to Template10 it doesnt work. shell.Content contains "HamburgerMenu" and from there I cant find a way to access the current page. Am I missing something?
Thanks

**Comment by JerryNixon** [comment]
That's because the content of the frame is not guaranteed to be a Page in Template 10. So your Assert should sometimes fail (mostly, only in the case of SplashScreen). That being said your code should work, but do it this way. Shell.HamburgerMenu.Content.
