### ISSUE TITLE
Messaging namespace

### ISSUE THREAD

**Issue by MauRiEEZZZ** [Windows-XAML/Template10#585]
I stumble upon the fact that every page I create seems to be created in the wrong namespace.
I found out that every page already in the template use the namespace Messaging regardless of the name of the application.

For example: 
I create a new application using the template 10 template with the name example.
I open MainPage.xaml and the Page starts with:
`<Page x:Class="Messaging.Views.MainPage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:Core="using:Microsoft.Xaml.Interactions.Core"
      xmlns:Interactivity="using:Microsoft.Xaml.Interactivity"
      xmlns:controls="using:Template10.Controls"
      xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
      xmlns:local="using:Messaging.Views"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
      mc:Ignorable="d">
`
If I create a second Page named MainPage1.xaml the page starts with:
`<Page
    x:Class="Example.MainPage1"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:Example"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d">

Am I missing knowledge of a design patern here? Can someone please guide me into the right direction with this issue?
Thank you!

**Comment by JerryNixon** [comment]
Please upgrade the T10 extension to version 1.7, and Nuget library to 1.1.3.
