### ISSUE TITLE
NavigationMode arg in OnNavigatingFromAsync is always New due to a race condition

### ISSUE THREAD

**Issue by craigktreasure** [Windows-XAML/Template10#588]
The FrameFacade resets the value of the NavigationModeHint before the NavigationService is notified of the navigation. The NavigationService is referring to the NavigationModeHint after it has changed to construct the arguments. The correct value is in the event arguments. Fix should be simple. I'll send a PR.

**Comment by JerryNixon** [comment]
Could you verify you are using 1.1.3?

**Comment by craigktreasure** [comment]
@JerryNixon From what i see, there is still no 1.1.3. The latest release is 1.1.2. :-) https://www.nuget.org/packages/Template10/
