### ISSUE TITLE
OnNavigatedToAsync triggered twice if HamburgerMenu in narrow state

### ISSUE THREAD

**Issue by MatthiasNistl** [Windows-XAML/Template10#591]
In my app I'm using a Hamburger Menu with VisualStateNarrowMinWidth=0 and VisualStateNormalMinWidth=600, so if the app window width gets smaller than 600 the HamburgerMenu vanishes. Everything works fine and as expected.

If I close the app while window width is smaller than VisualStateNormalMinWidth and then start it again, the HamburgerMenu is not shown. Again, as expected. But in this case in my MainPageViewModel OnNavigatedToAsync gets triggered twice. If the window width is > VisualStateNormalMinWidth at app start, then OnNavigatedToAsync is triggered only once.

Case 1: Width > VisualStateNormalMinWidth, HamburgerMenu visible, OnNavigatedToAsync triggered once
Case 2: Width < VisualStateNormalMinWidth: HamburgerMenu not visible, OnNavigatedToAsync triggered twice

This only occurs when starting the app. If I go back to the MainPage later, then OnNavigatedToAsync is only triggered once, too.
It seems like FrameFacade.Navigate is called twice in any case when starting the app:

```
public bool Navigate(Type page, object parameter, NavigationTransitionInfo infoOverride)
{
    if (Frame.Navigate(page, parameter, infoOverride))
    {
        // Case 1: First call
        // Case 2: Both calls
        return page.Equals(Frame.Content?.GetType());
    }
    else
    {
        // Case 1: Second call
        return false;
    }
}
```

Can anyone reproduce this?

**Comment by JerryNixon** [comment]
I cannot get Navigate() to fire two times.

**Comment by MatthiasNistl** [comment]
Ok, after some more digging I found what was causing this behaviour. In OnInitializeAsync I've been installing command definitions for Cortana:

```
var nav = NavigationServiceFactory(BackButton.Attach, ExistingContent.Include);
Window.Current.Content = new Shell(nav);

try
{
    var commandFile = await StorageFile.GetFileFromApplicationUriAsync(new Uri("ms-appx:///Resources/VoiceCommands.xml"));
    await Windows.ApplicationModel.VoiceCommands.VoiceCommandDefinitionManager.InstallCommandDefinitionsFromStorageFileAsync(commandFile);
}
catch (Exception ex)
{
    Debug.WriteLine($"There was an error registering the Voice Command Definitions: {ex}");
}
```

This caused some stuff to happen before NavigationService.Navigate(typeof (MainPage)) got called. So I moved the try-catch-block into OnStartAsync, AFTER NavigationService.Navigate(). Now FrameFacade.Navigate() gets only fired one time instead of two times, as expected.
I dont understand what exactly is happening here, since other async methods in OnInitializeAsync are working just fine. But as soon as I put the voice command installation before NavigationService.Navigate, FrameFacade.Navigate gets fired again twice.

Anyway, this doesn't seem to be related to Template 10.

**Comment by JerryNixon** [comment]
Thank you very much for your follow-up.
