### ISSUE TITLE
Share target

### ISSUE THREAD

**Issue by rafakwolf** [Windows-XAML/Template10#593]
When i try to open an app as Share target, a serialization error occurs:

**An exception of type 'Newtonsoft.Json.JsonSerializationException' occurred in Template10Library.dll but was not handled in user code

Additional information: Unable to find a constructor to use for type Windows.ApplicationModel.DataTransfer.ShareTarget.ShareOperation. A class should either have a default constructor, one constructor with arguments or a constructor marked with the JsonConstructor attribute. Path 'Data', line 1, position 18.**

My code:

```
        // runs only when not restored from state
        public override Task OnStartAsync(StartKind startKind, IActivatedEventArgs args)
        {
            ShareTargetActivatedEventArgs parameters = null;

            if (startKind == StartKind.Activate)
            {
                if (args.Kind == ActivationKind.ShareTarget)
                {
                    parameters = args as ShareTargetActivatedEventArgs;
                }
            }

            if (parameters != null)
                NavigationService.Navigate(typeof(Views.MainPage),parameters.ShareOperation); // this line error
            else
                NavigationService.Navigate(typeof(Views.MainPage));

            return Task.CompletedTask;
        }
```

Thanks

**Comment by heribertofilho** [comment]
I only change this and worked:
if (parameters != null)
            {
                ShareOperation shareOperation = parameters.ShareOperation;
                string text = await shareOperation.Data.GetTextAsync();
                NavigationService.Navigate(typeof(Views.DetailPage), text);
            }

**Comment by rafakwolf** [comment]
This code retrieve all data ? LIke WebLinks, images etc... i don't think so.

**Comment by heribertofilho** [comment]
You have to retrieve all data on this code, with: GetRichText, GetURI, GetHTML... You have to know what your source is giving to you, cause some apps(like Store) sends only Text(APP NAME + URL) or only the URL, other than that makes the app crash.

**Comment by JerryNixon** [comment]
Please ask this on StackOverflow and send me the link to the question.
