### ISSUE TITLE
Changes with SplashFactory

### ISSUE THREAD

**Issue by ghost** [Windows-XAML/Template10#594]
I was used to configure a custom splash screen, but with the latest release, SplashFactory property expects a func of type < SplashScreen, ExtendedSplash >
Am I expect to instanciate a SplashScreen and then call a method which returns an instance of my ExtendedSplash?

**Comment by ghost** [comment]
Oh, and RequestedTheme is not available anymore in bootstrap class...

**Comment by craigktreasure** [comment]
Yea. If you look in the T10 templates you'll see something like this in the constructor in App.xaml.cs:

``` C#
SplashFactory = (e) => new Views.Splash(e);
```

As far as i know, it has always been this way for Template10. You can always go around and do it yourself.

The RequestedTheme can be found here:

``` C#
BootStrapper.Current.NavigationService.Frame.RequestedTheme
```

Hope this helps.

**Comment by ghost** [comment]
Ok thanks!
