### ISSUE TITLE
Weird issue with Navigation

### ISSUE THREAD

**Issue by ghost** [Windows-XAML/Template10#596]
I have a very strange issue concerning OnNavigatedToAsync method. When I navigate to my page, everything works fine. But when I go back from the origin page (I use the back button of Windows Mobile), and I navigate again to my page, the app crash with this unhandled exception:

_Unable to cast COM object of type 'System.ComponentModel.PropertyChangedEventHandler' to class type 'System.ComponentModel.PropertyChangedEventHandler'. Instances of types that represent COM components cannot be cast to types that do not represent COM components; however they can be cast to interfaces as long as the underlying COM component supports QueryInterface calls for the IID of the interface._

The problem only occurs when the page is navigated on the second time, and if my Contacts property is reassigned (look at the last line of my code). If I remove the assignment, it's ok. The problem does not occur at all if I use the method Navigate instead of OpenAsync. 
The problem seems related to PropertyChanged event handler.

```
    public override async Task OnNavigatedToAsync(object parameter, NavigationMode mode,
        IDictionary<string, object> state)
    {
        var contacts = parameter as IEnumerable<Contact>;
        if (contacts == null)
        {
            ContactFound = false;
            await Task.CompletedTask;
        }

        var addressBooks = (from contact in contacts
            where contact.Phones.Count != 0 || contact.Emails.Count != 0
            let firstName = contact.FirstName
            let lastName = contact.LastName
            let address =
                contact.Addresses.Select(a => a.StreetAddress).FirstOrDefault() ??
                string.Empty
            let number =
                contact.Phones.Where(a => a.Kind == ContactPhoneKind.Mobile).Select(a => a.Number).FirstOrDefault()
            let mail = contact.Emails.Select(a => a.Address).FirstOrDefault()
            let image = contact.Thumbnail
            let capital =
                contact.FirstName.Substring(0, 1) +
                (!string.IsNullOrEmpty(contact.LastName) ? contact.LastName.Substring(0, 1) : string.Empty)
            select new AddressBook(firstName, lastName, address, number, mail, capital, image)).ToList();
        ContactFound = addressBooks.Any();

        var itemSource = AlphaKeyGroup<AddressBook>.CreateGroups(addressBooks,
            CultureInfo.CurrentUICulture,
            s => s.FirstName ?? s.LastName, true);
        Contacts = new ObservableCollection<AlphaKeyGroup<AddressBook>>(itemSource);
```

**Comment by craigktreasure** [comment]
This isn't specific to Template10. Are you using an EventTriggerBehavior in your view and binding to a property or command in your view model by any chance?
I had this issue and worked around it in my view model by changing the type of my command to be `DelegateCommand<object>` instead of `DelegateCommand<ItemType>` and then checking the type inside the setter. In my case, i was binding to a ListView and when the selected item was changed to null, the behavior would pass the event arguments of the event instead of null (seems like a bug in the behavior). Because the type was wrong, it throws. Looks similar to what your dealing with.

Make sense?

**Comment by ghost** [comment]
Thanks it worked! That was exactly my problem! Indeed, not related to Template10.
