### ISSUE TITLE
HamburgerMenu.IsFullScreen doesn't seem to do anything in 1.1.1?

### ISSUE THREAD

**Issue by johanlindfors** [Windows-XAML/Template10#598]
So I've been trying to find out if it's even possible to leverage Template10 if my initial requirement is to have a modal extended SplashScreen that's being displayed while the application loads (initializes) and when it's done the main shell should appear with a HamburgerMenu. I've found a couple of commits and issues discussing this scenario (which hopefully means I'm not alone in this requirement) but neither actually proposes a solution. It's suggested to leverage IsFullScreen on the HamburgerMenu but that property doesn't seem to do anything at all.

I'm using the Template10 assemblies from nuget.

Any ideas?

**Comment by JerryNixon** [comment]
No. I just verified. I also added a Full-screen button to the Hamburger template in GitHub if you want to see for yourself. It certainly appears to be working. If you know of some variables I might be overlooking, let me know. 

![fullscreen](https://cloud.githubusercontent.com/assets/1749983/12723511/ff5f72b2-c8c6-11e5-8182-f8d332ee0324.gif)

**Comment by johanlindfors** [comment]
I agree, thanks for taking the time. I've created a second sample to demonstrate this behavior and also get it to work, now I need to figure out why it doesn't work in my "main" application.

Keep up the great work!
