### ISSUE TITLE
How to pass FileActivatedEventArgs

### ISSUE THREAD

**Issue by luiscantero** [Windows-XAML/Template10#599]
I've been unable to find samples, docs or articles regarding file activation using T10. I tried this:
public override async Task OnStartAsync(StartKind startKind, IActivatedEventArgs args)
        {
            var fileArgs = args as FileActivatedEventArgs;

```
        if (fileArgs != null)
        {
                    NavigationService.Navigate(typeof(Views.MainPage), fileArgs);
        }
```

// ...
        }

But I'm getting this error when Navigate() is called:
"Error getting value from 'Folder' on Windows.Storage.Search.StorageFileQueryResults."

I think the serialization service is having problems with this data type...

**Comment by JerryNixon** [comment]
Please ask questions like this on StackOverflow with Template10 as a tag.
