### ISSUE TITLE
missing files from Template10Library

### ISSUE THREAD

**Issue by MichaelPetrinolis** [Windows-XAML/Template10#6]
Hi,
Controls/BackAppBarButton and Themes\Generic.xaml are missing from Project

**Comment by plettb** [comment]
Actually, it looks like there are quite a few other files missing as well.

**Comment by ShiroYacha** [comment]
Yeah, the pre-release seems to have things missing too.

**Comment by TiBall** [comment]
Yes, please commit the missing files

**Comment by zangai** [comment]
Also, please inform us how to get the XAML Behaviors Extension?

**Comment by MichaelPetrinolis** [comment]
Regarding the XAML Behaviors Extension, you should add Behaviors SDK (XAML) v12 from add reference->Universal Windows->Extensions (which targets windows 8.1 so you must install the windows 8.1 SDK)

**Comment by JerryNixon** [comment]
Correct, that is how you do it.

**Comment by marcominerva** [comment]
There are still some missing files, projects don't compile

**Comment by BuGGeH** [comment]
The original issue wasn't about XAML Behaviors Extensions, rather that was a digression.

The original issue still stands so this definitely isn't closed/solved.

Thanks :P

**Comment by zangai** [comment]
Sorry about hijacking your issue MichaelPetrinolis :)
What is the status about the missing files Jerry? The previous commit had missing files too.

**Comment by JerryNixon** [comment]
I will commit a new release today.

**Comment by marcoscheel** [comment]
Looks different noch :( Still not able to build the solution. A visual studio upgrade is needed. Are you running internet bit that will be released as RTM on 20.July? The blog posts regarding compatibility during the next weeks suggests that the solution is not compatible with current RC. Im on WIn 10 1024 (from this night) and latest public version of VS 2015 RC

**Comment by JerryNixon** [comment]
Hey Marco. The biggest thing is that I am using the SDK from last week. It's available publicly to all the Insiders so with that you should be able to open and build. That being said, could you tell me exactly which files are not present? I need to figure that out, can't be sure why. Not yet. Email me instead of this. jnixon@microsoft will work. (add the .com later, right?)

**Comment by julid29** [comment]
some of the errors (VS 2015, build 10240, SDK .10166)
![1](https://cloud.githubusercontent.com/assets/10983779/8736099/0d0b228a-2bec-11e5-9448-a2b4e4f9e7a4.png)
![2](https://cloud.githubusercontent.com/assets/10983779/8736100/0d0b54d0-2bec-11e5-9cb7-29feeefce508.png)
![3](https://cloud.githubusercontent.com/assets/10983779/8736098/0d0a8e92-2bec-11e5-9e34-fb46ef22c29b.png)

**Comment by JerryNixon** [comment]
Yeah, one in process file I forgot to include.

**Comment by JerryNixon** [comment]
Yeah, may not build for another day. Sorry.
