### ISSUE TITLE
Package restore failed for 'Template10'.

### ISSUE THREAD

**Issue by markhbrown** [Windows-XAML/Template10#60]
When trying to install the Template10 Nuget package to new Blank App (Universal Windows) project I get the following error:

Package restore failed for 'Template10'.

**Comment by JerryNixon** [comment]
I uploaded a new NuGet version. See if that makes a difference.

**Comment by markhbrown** [comment]
Hi Jerry, I'm afraid not - I still get the same error:

This is what's at the end of the console output:

All packages are compatible with UAP,Version=v10.0 (win10-x64-aot).
Package restore failed for 'Template10'.
Package restore failed. Rolling back package changes for 'Template10'.

**Comment by JerryNixon** [comment]
So far you are the only person to report this. I have just uploaded a new ver to NuGet again. I can't be sure this will work either. But, what's going on with your project?! Any suggestions?

**Comment by darenm** [comment]
I've had another report that's says the package only works targeting x86 - fails if you are targeting x64

**Comment by JerryNixon** [comment]
I am fixing the XAML parse error today in NuGet (took a while to track that one down) and I think the changes will also resolve this. But I will check after the update. If so, I will close this.

**Comment by JerryNixon** [comment]
Please try v1.0.4 now in NuGet

**Comment by markhbrown** [comment]
It's still not working for me.

Steps I've taken:

1) Visual Studio 2015 - New Project -> Blank App (Universal Windows)
2) Nuget 3.0 - install Template 10 1.04

When installing the error list shows:

"Package restore failed. Rolling back package changes for 'Template10'.

Don't know why I'm still having this issue... perhaps I'm being stupid?!
