### ISSUE TITLE
Question: Error when suspending

### ISSUE THREAD

**Issue by ghost** [Windows-XAML/Template10#600]
I want to serialize some properties when suspending the app and I got an exception:

```
Exception thrown: 'System.Runtime.InteropServices.COMException' in mscorlib.ni.dll

WinRT information: Error trying to serialize the value to be written to the application data store

Additional information: Data of this type is not supported.
```

the property eg:

```
private List<string> _PropName;
public List<string> PropName
{
    get { return _PropName; }
    set { Set(ref _PropName, value); }
}
```

Any idea how to serialize then?

thanks

**Comment by luiscantero** [comment]
I think the same limitations regarding data types outlined here apply:
https://msdn.microsoft.com/en-us/library/windows/apps/mt299098.aspx

You can use JSON: SerializationService.Json

**Comment by ghost** [comment]
Thanks
