### ISSUE TITLE
"Window.Current.Content as Frame" is null - OnStartAsync

### ISSUE THREAD

**Issue by nor0x** [Windows-XAML/Template10#601]
I just upgraded Template10 from version 1.0.8 to 1.1.2 and now I encounter the following problem. In `OnStartAsync()` I try to get the current Frame and check its BackStack.
`Frame rootFrame = Window.Current.Content as Frame;`

Apparently something has changed because when I was on 1.0.8 this worked fine, and now the `rootFrame` object is null.
My purpose on checking the `BackStack` is to insert the MainPage if the app was launched from a `ToastNotification` to a specific page.

I hope that somebody can help me with that.

**Comment by darenm** [comment]
Hi - please ask this question on StackOverflow using the tag Template10.

Thanks.

**Comment by nor0x** [comment]
Done - I will close it here!
Thanks!
