### ISSUE TITLE
Hamburger menu doesnt collapse after navigation from details/settings view

### ISSUE THREAD

**Issue by calloncampbell** [Windows-XAML/Template10#602]
After upgrading to latest nuget version and updating my project with all the changes that are now found in the Hamburger sample project...I've noticed the following which seems like a bug:
1. Create Template10 Hamburger sample project
2. Make sure you have Master and Detail pages
3. Update Master page with multiple hamburger menu items (call them tabs)
4. Run app. Drill down into the Details page (call it menu item 1 details). Now go to Hamburger menu and switch to Hamburger menu item 2 (take note that your currently in the details view)

Expected behavior:
Navigate to Menu 2 Master page and hamburger menu collapses

Actual behavior:
Navigates to Menu 2 Master page and the hamburger menu is still opened and overlayed

This behavior doesn't happen when changing Master pages from Menu 1 to Menu 2 and only occurs when your in the Detail view. Also happens with the Settings view.

Thoughts?

**Comment by JerryNixon** [comment]
Thank you. Resolved.
