### ISSUE TITLE
Question: Changing Busy background

### ISSUE THREAD

**Issue by LostLogic** [Windows-XAML/Template10#603]
Hi!

I can't seem to find an intuitive way to customize the background of the busy indicator (Currently turning into a full screen translucent blue overlay). Am I missing something or is this outside of scope of how the Busy indicator is intended to work? I'd like to change it to have a transparent image, so thus the question.

Thanks for Template 10. I've learned a tonne of good coding and structuring practices when using it on my current project!

Cheers!

**Comment by JerryNixon** [comment]
This is not intuitive? 
`ModalDialog.ModalBackground = new SolidColorBrush(Colors.Pink) { Opacity = .5 };`

**Comment by LostLogic** [comment]
Thanks Jerry! That's exactly what I needed!
