### ISSUE TITLE
BootStrapper - Attachble property not found in common & no InitializeComponent method

### ISSUE THREAD

**Issue by LanceEa** [Windows-XAML/Template10#604]
I seem to be having a very similar issue that was raised previously. The issue #5 is very similar to what I'am seeing. 

I started with a Blank Universal App and then started building out my solution based on the Hamburger\Minimal template. 

Setup:
Windows 10
Visual Studio 2015 Update 1
Template10 nuget package 1.1.2

![image](https://cloud.githubusercontent.com/assets/8103374/12754655/a68416ea-c991-11e5-96b3-cfc3d0c08bfa.png)

![image](https://cloud.githubusercontent.com/assets/8103374/12754663/b170f97e-c991-11e5-806f-0d907b0b5ab2.png)

I have tried re-installing Visual studio and also used a different Windows 10 machine and the same results occurred. I'm sure I could be missing something but maybe not an issue with Template10 but rather Visual Studio??

Any thoughts or anyone else seeing this type of error?

**Comment by JerryNixon** [comment]
@LanceEa here are options:
1. Ensure PacMan is enabled
2. Refresh your project

![getstarted](https://cloud.githubusercontent.com/assets/1749983/12756702/221d8962-c992-11e5-8517-5e6fca4ab2d6.gif)

**Comment by LanceEa** [comment]
Package manager was already enabled for restore on builds and I have tried to clean solution, rebuild and build solution but nothing seems to work. Also, closed out of Visual Studio and restarted computer but same error persists.  Other thoughts?

![image](https://cloud.githubusercontent.com/assets/8103374/12757484/d88dd016-c99d-11e5-886b-d57887b168f5.png)

**Comment by LanceEa** [comment]
@JerryNixon btw...forgot to say thanks for the initial ideas.

**Comment by SoftwareOnSailboats** [comment]
I am now having the EXACT same problem and any help is GREATLY appreciated...

**Here is how I encounter the problem:** I create a new or open a saved pristine, untouched Template 10 Hamburger project. I get the "stuff missing" alert and have 2 warning messages and no errors. I rebuild the project and the warning messages disappear, and there are no error messages. (Package Manager is enabled).

When I open this project's file App.xaml, two errors appear:
The name "BootStrapper" does not exist in the namespace "using:Template10.Common".
The member "Resources" is not recognized or is not accessible.  

**My system status**: Package Manager is enabled, and I have used it to reinstall Template 10, v1.18. Restarted my computer and VS2015. VS2015 Updates are pending for SQL {something) and ASP.NET {something}. I don't recall seeing this problem prior to installing Windows 10 SDK 10.0.26624 a day ago. Oddly, Control Panel now shows VS2015 with Update 2 installed on the same day. A bit odd, considering VS2016 reports itself as Update 3. Hmmmmm... 

**Here is what VS2015 reports about itself on my system**:
Microsoft Visual Studio Community 2015
Version 14.0.25424.00 Update 3
Microsoft .NET Framework
Version 4.6.01038
Visual C# 2015  
Microsoft Visual C# 2015
Visual C++ 2015  
Microsoft Visual C++ 2015
Windows Phone SDK 8.0 - ENU
Application Insights Tools for Visual Studio Package   7.1.00719.1
ASP.NET and Web Tools 2015 (RC1 Update 1)   14.1.20203.0
ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
Azure App Service Tools v2.9.1   14.0.20519.0
Azure Data Lake Node   1.0
Azure Data Lake Tools for Visual Studio   2.0.6000.0
Common Azure Tools   1.8
JavaScript Project System   2.0
Microsoft Azure HDInsight HQL Service   2.0.6000.0
Microsoft Azure HDInsight Tools for Visual Studio   2.0.6000.0
Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.40518.2
NuGet Package Manager   3.4.4
PreEmptive Analytics Visualizer   1.2
SQL Server Data Tools   14.0.60519.0
ToolWindowHostedEditor   1.0
TypeScript   1.8.35.0
Visual Studio Tools for Universal Windows Apps   14.0.25420.01

Thanks in advance for any thought or suggestions to resolve this matter...

**Comment by mvermef** [comment]
There are updates for VS only found when you go to Programs and Features and using Modify option after change has been clicked with VS selected...

**Comment by SoftwareOnSailboats** [comment]
Per mvermef, I upgraded from 1.4.0 to 1.4.1 of Universal Windows App Dev Tools and (for the moment) things seem to be working. Thank you for pointing me in the right direction...

At this point this still feels like not knowing if your car I going to start in the morning...hope it gets better...

**Comment by mvermef** [comment]
What really sucks is they are suppose to "use" notifications to tell you there is an update, most of the time they are weeks behind and you get it even after you have already updated to the latest SDK
