### ISSUE TITLE
Shortest Version Property?

### ISSUE THREAD

**Issue by DominikErnst** [Windows-XAML/Template10#606]
using Windows.ApplicationModel;

public string Version => $"{Package.Current.Id.Version.Major}.{Package.Current.Id.Version.Minor}.{Package.Current.Id.Version.Build}.{Package.Current.Id.Version.Revision}";

_Source: SettingsPageViewModel.cs_

**Comment by luiscantero** [comment]
Is this a question or what?

**Comment by DominikErnst** [comment]
Yes and No, some kind of competition. ;-)

**Comment by JerryNixon** [comment]
You should cache the object.
