### ISSUE TITLE
App prelaunch not passing WACK

### ISSUE THREAD

**Issue by robertmuehsig** [Windows-XAML/Template10#608]
I try to upload my app to the store, but it seems there is a nasty bug inside Template10 because it keeps failing on these two points:

App prelaunch
Error Found: The app prelaunch validation detected the following errors:◦The app failed prelaunch test - 29745Code-Inside.ExpensiveMeeting_1.1.2.0_x64__5mgty9mmywh40.

Crashes and hangs
Error Found: The crashes and hangs test detected the following errors:◦Executable C:\Program Files\WindowsApps\29745Code-Inside.ExpensiveMeeting_1.1.2.0_x64__5mgty9mmywh40\WindowsApp1.exe was detected by Windows Error Reporting and experienced a crash or hang.
◦Application 29745Code-Inside.ExpensiveMeeting_1.1.2.0_x64__5mgty9mmywh40 was detected by Windows Error Reporting and experienced a crash or hang.
◦Crash dump file C:\Users\muehsig\AppData\Local\Microsoft\AppCertKit\WindowsApp1.exe.24688.dmp was created by Windows Error Reporting and provides additional information.

There is an older [issue](https://github.com/Windows-XAML/Template10/issues/540) about that, but I created a brand new "Hamburger (Template 10)" project and updated to the most recent 1.1.2 Template10 NuGet package and it keeps failing.

I have no idea why it crashs - it never happens during debugging or actual running.

When I create a new "Default" UWP app, WACK has no problems (besides the logo stuff).

**Comment by robertmuehsig** [comment]
I think this is related to https://github.com/Windows-XAML/Template10/issues/595 & https://github.com/Windows-XAML/Template10/issues/612

**Comment by robertmuehsig** [comment]
Just to make sure it's not just a "empty project problem". This issue is currently a show stopper for my store submission :( @JerryNixon

**Comment by diogorolo** [comment]
@robertmuehsig in #540 I commented some lines of code in InternalLaunchAsync that made my app pass WACK. It is just a hack/workaround but it worked for me since I needed to push an update to my app ASAP.

**Comment by robertmuehsig** [comment]
Seems to be fixed in 1.1.3 - thanks!

**Comment by sayzenberg** [comment]
Upgraded my project to 1.1.3 but I'm still running into the issue. Were there any additional steps that needed to be taken to get around it?

**Comment by robertmuehsig** [comment]
Nope - just updated the NuGet package and done. With 1.1.2 I could reproduce it with a fresh project - maybe something during the NuGet update failed? 
Just try to create a new project - is it still failing?

**Comment by sayzenberg** [comment]
No, it's fine in a fresh project, but my existing one still has the problem
