### ISSUE TITLE
Template10 controls namespace not found in editor

### ISSUE THREAD

**Issue by djb12** [Windows-XAML/Template10#609]
Hello Co-Templaters,

when building my projects, the Visual Studio editor is no longer able to resolve references to Template10 controls and I get the error message: "The name "PageHeader/ModalDialog/HamburgerMenu/..." does not exist in the namespace using:Template10.Controls".

The issue first appeared today when my packages were restored from nuget. Updating from 1.1.1 to 1.1.2 unfortunately did not resolve the issue.

I'm running in Debug x64, targetting Build 10240.

**Comment by JerryNixon** [comment]
There is no design support in x64. Glad you added that detail. Switch to x86. This is not T10, this is VS.
