### ISSUE TITLE
TextBox KeyDown should not cause hamburger menu opened

### ISSUE THREAD

**Issue by hungys** [Windows-XAML/Template10#61]
When typing some words on TextBox in Minimal sample project and pressing Enter key, the app should only navigate to DetailPage but not open the hamburger menu simultaneously.

**Comment by JerryNixon** [comment]
I agree. We'll get it in there.

**Comment by JerryNixon** [comment]
Can you see what is causing the Pane to re-open? I'm looking at it and can't put my finger on why it's opening in the first place.

**Comment by hungys** [comment]
I've fixed it, will send a pull request and provide some explanation for this issue soon.

**Comment by hungys** [comment]
@JerryNixon I have submitted the pull request #81 for this issue.

This is an internal bug of WinRT, confirmed by MSFT on [MSDN forum](https://social.msdn.microsoft.com/Forums/en-US/734d6c7a-8da2-48c6-9b3d-fa868b4dfb1d/c-textbox-keydown-triggered-twice-in-metro-applications?forum=winappswithcsharp) **three years ago**. The KeyDown event of TextBox will be triggered twice. When the second time of KeyDown fired, the frame has been navigated to another page, but the event still propagates and then intercepted by other controls. In this case, the hamburger button handles it, so the pane is opened.

I replace KeyDown with KeyUp in this patch, and it works fine on both PC and phone :)

Anyway, please help to report this bug to RD team, it has been added to internal bug database for 3 years. It's easy to be reproduced with a simple application.

**Comment by JerryNixon** [comment]
Resolved in current pull.
