### ISSUE TITLE
T10_PropertySetting.snippet 

### ISSUE THREAD

**Issue by MauRiEEZZZ** [Windows-XAML/Template10#615]
Hi Jerry I see you are updating the snippets,
I think line 41 of T10_PropertySetting.snippet should be:
`get { return $helper$.Read<$type$>(nameof($name$), default($type$)); }`
instead of 
`get { return $helper$.Read<$type$>(nameof($name$), default()); }`

Thanks for this great template!

**Comment by JerryNixon** [comment]
What's the difference?

**Comment by MauRiEEZZZ** [comment]
Sorry I have been to hasty, I updated the sentence

**Comment by MauRiEEZZZ** [comment]
I'll change this into a pull req. it's much more convenient
