### ISSUE TITLE
search & login samples

### ISSUE THREAD

**Issue by mvermef** [Windows-XAML/Template10#620]
In the samples read.me you used visualstatemanager.goto(), but don't see the actual code in the sample or the location of the visual states themselves, are they MIA?  I am in a time crunch need to start working to push out my project with a few things missing and update over time, but login is a necessity. 
My previous implementation using login on a completely separate page will work but trying to figure a way around that content assignment after login logic is satisfied to show the shell is proving to be fruitless.

**Comment by JerryNixon** [comment]
You're right. The readme is out of date. We switched to the much simpler use of ModalDialog.

https://github.com/Windows-XAML/Template10/blob/master/Samples/Search/Views/Shell.xaml#L76

If you want to update the readme and submit a Pull Request, I would welcome it.
