### ISSUE TITLE
[Question] InkToTextBox and VoiceToTextBox 

### ISSUE THREAD

**Issue by gsantopaolo** [Windows-XAML/Template10#624]
Hi Jerry,
    with pull request #623 (still open) I'm comfortable in saying that InkToTextBox and VoiceToTextBox (at the moment in a sample project) ,even if some improvements can be added , are now ready for production.
I would love to hear your feedback on that.
Now my question is: do you want this controls in the T10 library? If yes who should move them? If you want this work get done just say.
After we will finish with this I've another MPC control for you to evaluate.

Thank you and all the best
Gian Paolo

**Comment by JerryNixon** [comment]
I will move them after I review them. Sorry, it's taking a while.

**Comment by gsantopaolo** [comment]
That's fine, thank you.
Please make sure to include #623 in your review.

LLAP
-g
