### ISSUE TITLE
Share Sample uses a class that doens't exist on Nuget Package

### ISSUE THREAD

**Issue by heribertofilho** [Windows-XAML/Template10#626]
I'm using the sample and adapting my app, but i noticed that the sample uses the class "StateItemKey" whereas the Nuget package library use a Struct with the same name, so basically the sample don't work if i just copy and paste.
`var key = parameter as StateItemKey;`

**Comment by JerryNixon** [comment]
Yes, the Nuget does not have this capability yet. It will later today.
