### ISSUE TITLE
Share target question.

### ISSUE THREAD

**Issue by rafakwolf** [Windows-XAML/Template10#627]
Investigating a little more, I found out where is the error.

```
        public object Deserialize(string value)
        {
            DebugWrite($"Value {value}");

            if (value == null)
                return null;

            if (value == string.Empty)
                return string.Empty;

            // Deserialize from json
            var container = JsonConvert.DeserializeObject<Container>(value);
            var type = Type.GetType(container.Type);
            return JsonConvert.DeserializeObject(container.Data, type, settings); // --> here the error
        }
```

This class "Windows.ApplicationModel.DataTransfer.ShareTarget.ShareOperation" do not contains default contructor, so the deserializer don't works.

I tried to add "ConstructorHandling = ConstructorHandling.AllowNonPublicDefaultConstructor" to the deserializer settings, no success.

Any help?

**Comment by heribertofilho** [comment]
First of all, i'm brazillian too, little weird talk english when you speak portuguese.
Can you show me from where you get that string "value"? This is the Json string generated when you uses the Share function? Other thing, i think that this is not a error caused via Template 10. I'm making a app that uses this function and i don't have any problem.

**Comment by JerryNixon** [comment]
Have you looked at the ShareTarget sample in GitHub? Previously I asked you to ask this on StackOverflow. Would you please do that?

**Comment by rafakwolf** [comment]
@JerryNixon yes, now i seen, thanks
