### ISSUE TITLE
HamburgerMenu designed only for shell page?

### ISSUE THREAD

**Issue by smozhaykin** [Windows-XAML/Template10#631]
I want to use HamburgerMenu on regular page (not Shell). How can I pass NavigationService in this case?

As I understand NavigationService should be injected before NavButton_Loaded, otherwise following exception occurs:

`System.NullReferenceException: Object reference not set to an instance of an object.
   at Template10.Controls.HamburgerMenu.HighlightCorrectButton(Type pageType, Object pageParam)
   at Template10.Controls.HamburgerMenu.NavButton_Loaded(Object sender, RoutedEventArgs e)`

Moreover, null can't be set, because in this case in this case NRE occurs [here](https://github.com/Windows-XAML/Template10/blob/master/Template10%20%28Library%29/Controls/HamburgerMenu.xaml.cs#L546).

I can't bind it to ViewModel.NavigationService, because during initial binding ViewModel.NavigationService is null and this property doesn't raise PropertyChanged event.

I can't get it from BootStrapper.Current.NavigationService:

```
<Page>
    <Page.DataContext>
        <local:MainPageViewModel x:Name="ViewModel" />
    </Page.DataContext>

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <controls:HamburgerMenu VisualStateNarrowMinWidth="0" x:Name="Menu">
        </controls:HamburgerMenu>
    </Grid>
</Page>

    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            //Menu.NavigationService = App.Current.NavigationService; //Neither here, because Menu is null
            this.InitializeComponent();
            //Menu.NavigationService = App.Current.NavigationService; //Nor here, because "Value does not fall within the expected range." exception is thrown earlier
        }
    }
```

Here is stack trace:

`at Windows.UI.Xaml.FrameworkElement.MeasureOverride(Size availableSize)`

Is it possible to overcome these issues somehow? I don't want to use shell, because menu should be shown only on two pages and these menus are different.

Sample project attached.

[App1.zip](https://github.com/Windows-XAML/Template10/files/121843/App1.zip)

**Comment by JerryNixon** [comment]
I am sure it is. Let me look into it.

**Comment by mvermef** [comment]
var nav = App.Current.NavigationServiceFactory(...); should create what is needed, then you can assign it to hamburgermen.navigationsevice property.  Assuming that it wasn't created already, without looking at your code, on mobile at present

**Comment by smozhaykin** [comment]
@mvermef NavigationService is already created and exists in both BootStrapper instance and ViewModel. The problem is how to inject it correctly into the HamburgerMenu.

**Comment by JerryNixon** [comment]
I think you are making some incorrect assumptions. The NavService is passed to the view-mode. The NavService is not a separate instance. Check out the code. NavService is a property of the view-model. You should be able to set HamMenu.NavService to ViewModel.NavService. Make sense?
