### ISSUE TITLE
When launching with Cortana, back button subscription never happens

### ISSUE THREAD

**Issue by bc3tech** [Windows-XAML/Template10#632]
For some crazy reason, when Cortana launches an app built w/ T10, it fires _only_ the `InternalActivatedAsync` method and **never** the `InternalLaunchAsync` method. This means our `SubscribeBackButton()` code never gets executed.

I'm thinking this just needs `SubscribeBackButton()` on or about line 180 of [Bootstrapper.cs](https://github.com/Windows-XAML/Template10/blob/master/Template10%20%28Library%29/Common/BootStrapper.cs), but haven't fully vetted that idea yet.

If/when I do I'll be sure to submit a pull request unless somebody else gets the chance to and beats me to it.

**Comment by JerryNixon** [comment]
I found the error. Resolved.
