### ISSUE TITLE
HamburgerMenu.HamburgerBackground does not respond to VisualState changes

### ISSUE THREAD

**Issue by Preecington** [Windows-XAML/Template10#634]
I've been trying to set the colour of `HamburgerMenu.HamburgerBackground` to change via a `VisualState` using `AdaptiveTrigger` - but no permutation of value setter seems able to change the colour. (In this use case, I am trying to set the background to Transparent when Min Width is 0)

**Comment by Preecington** [comment]
Sample visual state:

```
   <VisualStateManager.VisualStateGroups>
        <VisualStateGroup>
            <VisualState>
                <VisualState.StateTriggers>
                    <AdaptiveTrigger MinWindowWidth="0" />
                </VisualState.StateTriggers>
                <VisualState.Setters>
                    <Setter Target="Menu.HamburgerBackground" Value="Transparent"/>
                </VisualState.Setters>
            </VisualState>
        </VisualStateGroup>
    </VisualStateManager.VisualStateGroups>
```

**Comment by JerryNixon** [comment]
Does it work when you set the property directly on the control?

**Comment by Preecington** [comment]
@JerryNixon Do you mean without using a VisualState Setter? If I set the control to be Transparent in XAML control declaration, it works. It just doesn't seem to want to honour any Setters. I tried another experiment using GoToStateAction to change the Visual State that way, and still nothing.

**Comment by JerryNixon** [comment]
This is a known issue. And, it sucks. Maybe you could suggest a solution?

**Comment by Preecington** [comment]
@JerryNixon Known issue with UWP or the Hamburger control itself? I tried to search for an existing Template10 issue on this before I posted and couldn't find one. If it's an issue with the control, I'd be happy to take a look.

**Comment by JerryNixon** [comment]
Known issue of T10 HamMenu since we introduced the AccentColor property.

**Comment by JerryNixon** [comment]
Change your page structure to this, and try again.

Page > Grid (with Visual States) > HamMenu

**Comment by jerinjohnk** [comment]
I can confirm that adding a grid inside Shell to encase Control code and specifying the viewstates does fix the issue.

```
 <Grid>
        <VisualStateManager.VisualStateGroups>
            <VisualStateGroup>
                <VisualState>
                    <VisualState.StateTriggers>
                        <AdaptiveTrigger MinWindowWidth="0" />
                    </VisualState.StateTriggers>
                    <VisualState.Setters>
                        <Setter Target="MyHamburgerMenu.HamburgerBackground" Value="Transparent"/>
                    </VisualState.Setters>
                </VisualState>
                <VisualState>
                    <VisualState.StateTriggers>
                        <AdaptiveTrigger MinWindowWidth="{StaticResource NormalMinWidth}" />
                    </VisualState.StateTriggers>
                    <VisualState.Setters>
                        <Setter Target="MyHamburgerMenu.HamburgerBackground" Value="Black"/>
                    </VisualState.Setters>
                </VisualState>
            </VisualStateGroup>
        </VisualStateManager.VisualStateGroups>
 <Controls:ModalDialog IsModal="{x:Bind IsBusy, Mode=OneWay}">
            <Controls:ModalDialog.Content>
                <Controls:HamburgerMenu x:Name="MyHamburgerMenu" IsFullScreen="False" HamburgerBackground="Transparent">
....
</Grid>
```

But now question arises does this **hamper any other functionality** as grid wasnt added in any sample project.
Earlier I was adding a reference of T10 (Library) after making changes to Hamburger.xaml viewstate.

**Comment by clinton05** [comment]
How to use a shell hamburger menu in visual state setters?
