### ISSUE TITLE
Disable the HamburgerButton's transition on VisualStateWide

### ISSUE THREAD

**Issue by sebfrie** [Windows-XAML/Template10#635]
I'd like to tweak the visual states of the HamburgerMenu, for example the HamburgerButton's "down, up and away" animation when reaching the wide state. Please enable this.

**Comment by JerryNixon** [comment]
Let me think about it.

**Comment by JerryNixon** [comment]
Just remove the animation or change the position of the button?

**Comment by sebfrie** [comment]
Just removing the animation.

The button should always be visible. I try to mimic the wide state of the Groove app.

**Comment by JerryNixon** [comment]
Resolved in current ver.

**Comment by cloudcrypt** [comment]
Just to try to implement this change manually in an older version of Template10 that's in use in a project, which commit includes this change?

**Comment by sebfrie** [comment]
Simply, the state got removed. See 0949d9b4d23e6588657a2093851a0a33781d5b18

Btw, thanks, Jerry! Will there be an update for the nuget package soon?

**Comment by cloudcrypt** [comment]
Thanks!

**Comment by JerryNixon** [comment]
Yes
