### ISSUE TITLE
Template10.Utils.MonitorUtils.Current().Pixels.Width throw System.ArgumentNullException

### ISSUE THREAD

**Issue by deepak-rathi** [Windows-XAML/Template10#636]
> **var width = Template10.Utils.MonitorUtils.Current().Pixels.Width;**

I am not using Template10 Bootstrap class in **App.xaml.cs**, I just want to use Template 10 monitor utility. **But I get System.ArgumentNullException**. I see Template10.Utils.MonitorUtils.Current() takes "**WindowWrapper**" but I assume its optional parameter. If not how can I a set WindowWrapper and make use of it? 

I was using the below code to detect if resized size of app fit for mobile view or desktop view. Which works fine for laptop and desktop. But it does not give good results for **Surface Pro**.

> var bounds = ApplicationView.GetForCurrentView().VisibleBounds;
> var scaleFactors = DisplayInformation.GetForCurrentView().RawPixelsPerViewPixel;
> var size = new Size(bounds.Width \* scaleFactors, bounds.Height \* scaleFactors);
> if (size.Width > 720)
> {
>      IsMobileDevice = false;
> }
> else
> {
>      IsMobileDevice = true;
> }

**Comment by mvermef** [comment]
WindowWrapper is part of the bootstrapped, as are other parts that pass alot of information from system to template and as a result most everything is built around those features, separation may not play well.

**Comment by JerryNixon** [comment]
I think he's right. It's going to be difficult to use that without using Bootstrapper. You can steal the code, but here's a word of warning, this stuff changes. That utility was just rewritten last week. What I mean is, you can steal the code, but you better come back and check later that something hasn't gotten better.
