### ISSUE TITLE
I think it's necessary a complete tutorial for this template. 

### ISSUE THREAD

**Issue by gustavogavancho** [Windows-XAML/Template10#640]
Solved

**Comment by TavoxD** [comment]
Si podria haber un tutorial explicando su uso, that would be great

**Comment by diogorolo** [comment]
You have the wiki with some references: https://github.com/Windows-XAML/Template10/wiki
You also have the samples: https://github.com/Windows-XAML/Template10/tree/master/Samples
And some projects with basics: https://github.com/Windows-XAML/Template10/tree/master/Templates%20(Project)

**Comment by gustavogavancho** [comment]
Thank you, by the way do you know if entity framework supports uwp?.

**Comment by ViktorBergman** [comment]
@TavoxD Entity Framework 7 supports UWP but it is still a RC. I recommend using the RC2 builds.
http://ef.readthedocs.org/en/latest/platforms/uwp/getting-started.html

**Comment by AmitBhatnagar24** [comment]
While the wiki, samples, and projects do provide lots of great detail, I can't really disagree with TavoxD's original request for a tutorial. The wiki pages do a good job describing specific parts of T10, (i.e.: we have pages for Behaviors, Controls, Navigation Cache, Services, etc.), but perhaps something more general is needed? A short video or something? 

One area that I still quite don't understand fully is how and when to use SessionState vs the page parameter, vs the state parameter:

`public overrideTask OnNavigatedToAsync(object parameter, NavigationMode mode, IDictionary<string, object> state)`

I ended up having a quick chat with @JerryNixon  and it cleared up some stuff for me, however I think this is one area where a dedicated wiki page would be quite useful.

**Comment by AmitBhatnagar24** [comment]
I curious and wanted to see what other T10 resources were out there, and I came across a good blog series from @qmatteoq that talks about T10 (albeit an earlier release) at a high / tutorial level.

[http://blog.qmatteoq.com/tag/template10/](url)

**Comment by gustavogavancho** [comment]
Thanks @AmitBhatnagar24, english it's not my first language, so i couldn't explain it so well, I'll check that link, so far it's very detailed. Oh and there are some issues when you click that link from here
