### ISSUE TITLE
dynamic HamburgerButtonInfo navigate/highlighting bug

### ISSUE THREAD

**Issue by crazycreak** [Windows-XAML/Template10#641]
hey,

when i create the HamburgerButtonInfo items in code-behind file, then the navigation on tap navigates twice to the view and on back, the button is not marked correctly, example on github:

https://github.com/crazycreak/Template10Hamburger/compare/dynamic_navigation

build with nuget 1.1.3 Template10 Hamburger Template

is the usage correct or is there a better solution?

**Comment by crazycreak** [comment]
And i have a second question, is it possible to outsource the StackPanel/Template to an xaml file (for example as an Datatemplate) and bind it to the HamburgerButtonInfo (or as ItemTemplate for the MyHamburgerMenu.PrimaryButtons)?

**Comment by thepasto** [comment]
I think the second question is the same i reported [here](http://stackoverflow.com/questions/35231721/uwp-template-10-create-a-dynamic-hamburgermenu)
It would be nice if we could get HamburgerButtonInfo content bindig.
Thanks

**Comment by crazycreak** [comment]
my solution for the HamburgerButtonInfo Template is to use a usercontrol, for example
https://github.com/crazycreak/Template10Hamburger/tree/dynamic_navigation_workaround

**Comment by JerryNixon** [comment]
Sorry, I cannot reproduce this.

``` csharp
Template10.Services.LoggingService.LoggingService.Enabled = false;
var stackPanel = new StackPanel
{
    Orientation = Orientation.Horizontal
};
stackPanel.Children.Add(new SymbolIcon
{
    Width = 48,
    Height = 48,
    Symbol = Symbol.UnSyncFolder
});
stackPanel.Children.Add(new TextBlock
{
    Margin = new Thickness(12, 0, 0, 0),
    VerticalAlignment = VerticalAlignment.Center,
    Text = "UnSync Folder"
});
var button = new HamburgerButtonInfo
{
    Content = stackPanel,
    ButtonType = HamburgerButtonInfo.ButtonTypes.Toggle,
    ClearHistory = false,
    PageType = typeof(Views.DetailPage)
};
button.Tapped += (s, args) =>
{
    System.Diagnostics.Debug.WriteLine(">> Tapped <<");
};
MyHamburgerMenu.PrimaryButtons.Add(button);
```

**Comment by crazycreak** [comment]
@JerryNixon when you clone my example project, check out "dynamic_navigation" branch, run it and click on an "ItemPage" in the navigation, then the bug occurs (breack point in ViewModels/ItemPageViewModel -> OnNavigatedToAsync)

https://github.com/crazycreak/Template10Hamburger

**Comment by crazycreak** [comment]
and on back navigation, the button is not marked correctly
