### ISSUE TITLE
Questions: How to use a hamburger menu parameter and how to implement search bar in page header

### ISSUE THREAD

**Issue by MoPe123** [Windows-XAML/Template10#644]
Hi,

i am completely new to app development, XAML, C# and the UWP. I have two questions concerning the development:
1. I pass a parameter when a hamburgermenu item is clicked via the PageParameter property of the XAML control. The parameter contains the value "A" for example. On the page where the button redirects the user (in my example: view:MainPage) i override the OnNavigatedTo method and receive the parameter e of type NavigationEventArgs. In this method i just want to read the exact parameter i provided to the XAML property PageParameter. The value i want to extract in my example would be "A". When I look at e.Parameter i dont get just the "A" but an object of type string that looks like a dictionary to me (it contains something like {"Type":"System.String, ...", "Data":"\"A\""}. So there is my "A" value but i cant extract it properly and i really do not want to work with regular expressions. Casting it to any other type than string fails. Is there any easy and obvious solution i didnt get yet, to receive just this one parameter string?
2. I want to add a search bar (AutoSuggestBox) to the page header line. But i cant seem to find a Template10 Control of type AppBar that contains an AutoSuggestBox. I only get the possibility to add further buttons with specific icons. Is there no way to add a search bar based on an AutoSuggestBox like in Microsofts own apps like "News" in the Template10 page header controls?

Thank you very much in advance!

**Comment by ViktorBergman** [comment]
Hi Mope,

Template10 adds its own services on top of the XAML framework such as navigation, so that you don't need to worry about implementing your own state handling etc. What's "wrong" here is that you are using the Template10 navigation service from the HamburgerMenu to do the navigation, but when you are overriding the default OnNavigatedTo event in the view (i.e MainPage.xaml.cs) you are basically stepping out of the Template 10 zone. The correct way is to handle OnNavigatedTo in the corresponding view model as such:

```
public override Task OnNavigatedToAsync(object parameter, NavigationMode mode, IDictionary<string, object> state)
        {
            string ParameterPassed = parameter as string; // Here is your A value
        }
```

I suggest you have a look at the [template projects ](https://github.com/Windows-XAML/Template10/tree/master/Templates%20%28Project%29/Hamburger)to get the whole picture.

**This is how I implement the top searchbox, there might be other ways:**

```
<Grid.RowDefinitions>
    <RowDefinition Height="Auto" />
    <RowDefinition />
</Grid.RowDefinitions>

<controls:PageHeader Grid.Row="0" Content="Main Page">
    <controls:PageHeader.SecondaryCommands>
        <AppBarButton Click="{x:Bind ViewModel.GotoSettings}" Label="Settings" />
        <AppBarButton Click="{x:Bind ViewModel.GotoPrivacy}" Label="Privacy" />
        <AppBarButton Click="{x:Bind ViewModel.GotoAbout}" Label="About" />
    </controls:PageHeader.SecondaryCommands>
</controls:PageHeader>

<AutoSuggestBox Grid.Row="0" PlaceholderText="Click here to search..." QueryIcon="Find" Margin="12" HorizontalAlignment="Right" />
```

Both the PageHeader and the AutoSuggestBox is positioned on the first grid row so they will overlap. Thats the basics for it, I use VisualStateTriggers to adjust the positioning of the search box depending on the current screen size.

Hope it makes some sense to you.

**Comment by MoPe123** [comment]
Hey Viktor,

thank you for the detailed answer. The first part of it made the usage of the OnNavigatedToAsync() method quite clear now and it works. Now i just have to figure out how to reach back from the ViewModel of the MainPage (MainPageViewModel.cs) to the MainPage.xaml View and manipulate the title of that page based on the hamburgermenu button that I pressed. The title is actually being set in the PageHeader initially to "Title1":
`<controls:PageHeader Name="PageHeader" Content="Title1">
        </controls:PageHeader>`

Now i want to Change it for example to "Title2" when a user clicks on a specific button in the HamburgerMenu. I want to manipulate the title of the MainPage.xaml - i do not want to load and use separate pages for each HamburgerMenu button. How can i manipulate the PageHeader Content from within the method OnNavigatedToAsync() in the corresponding ViewModel? I gave it the Name "PageHeader" but cannot call it directly in the ViewModel. Could you please help me another time?

Concerning the search bar: The Approach you chose to implement it was also my initial approach. I just thoght there would be something more satisfying or even a Standard Control one can use for the AutoSuggestBox within the <controls> section of the PageHeader. Thank you. :)

**Comment by diogorolo** [comment]
You can put it in a Binding.

In the view model you can change a variable which controls the Page Header Title, which can be set in the OnNavigatedToAsync

``` C#
private bool _pageHeaderTitle = "Title1";
public bool PageHeaderTitle{ get { return _pageHeaderTitle ; } set { Set(ref _pageHeaderTitle , value); } }
```

And in the view, you get that value via Bindings:

``` XAML
<controls:PageHeader Name="PageHeader" Content="{Binding PageHeaderTitle}"/>
```

**Comment by MoPe123** [comment]
This is working perfect! Thanks. :)
