### ISSUE TITLE
Not change color of HamburgerMenu "NavAreaBackground"

### ISSUE THREAD

**Issue by Patxinho** [Windows-XAML/Template10#646]
Hi,

I had tried change the color of pane Background of HamburgerMenu, but i couldnt do it. 
When I try to change the parameter in both XAML control, such as the Custom style, always the same color appears.

`<Style TargetType="controls:HamburgerMenu">
                <Setter Property="AccentColor" Value="{ThemeResource CustomColor}" />
               ** <Setter Property="NavAreaBackground" Value="{ThemeResource CustomColor}" />**
                <Setter Property="VisualStateNarrowMinWidth" Value="{ThemeResource NarrowMinWidth}" />
                <Setter Property="VisualStateNormalMinWidth" Value="{ThemeResource NormalMinWidth}" />
                <Setter Property="VisualStateWideMinWidth" Value="{ThemeResource WideMinWidth}" />
            </Style>`

`<Controls:HamburgerMenu x:Name="MyHamburgerMenu" **NavAreaBackground="#FFD10707"**>`

The color always comes up is the Dim Grey.

Any Solution???

**Comment by diogorolo** [comment]
Is it related to #477 ?
JerryNixon said:

> If you want to set the NavAreaBackground, you cannot use AccentColor.

**Comment by Patxinho** [comment]
ohhh ok!!,

It would be great that you can add several parameters in styles for future releases.
Thanks for the reply.
I close the issues.
