### ISSUE TITLE
AccessViolationException in BootStrapper constructor

### ISSUE THREAD

**Issue by liptonbeer** [Windows-XAML/Template10#651]
Hi,
After last changes in BootStrapper class I'm getting AccessViolationException in contructor in this line of code:

`SystemNavigationManager.GetForCurrentView().BackRequested += BackHandler;`

The same problem occurs in Hamburger project template.

**Comment by JerryNixon** [comment]
This the NuGet version or the GitHub version? This x86 or ARM? This Debug or Release?

**Comment by JerryNixon** [comment]
I see this was the old GitHub version. Could you re-base and try again?

**Comment by liptonbeer** [comment]
Hi @JerryNixon 
Last changes in BootStrapper where events are wrapped in loaded method after window is created did the trick. I will check it later in my own project but it should be fixed now.

**Comment by liptonbeer** [comment]
New bootsrapper is working good in my project.
Thanks @JerryNixon
