### ISSUE TITLE
Shell Theme not updating when Theme switched in Settings

### ISSUE THREAD

**Issue by Stringer-C** [Windows-XAML/Template10#652]
In the Hamburger Template, when the Theme is switched from Light to Dark (or vice versa), the background of the Shell is not updated until the app is restarted. This causes an unpleasant flash of white when transitioning between pages.

Inserting the following at the end of the SettingsService.AppTheme property setter seems to fix the issue:
Views.Shell.Instance.RequestedTheme = value == ApplicationTheme.Dark ? ElementTheme.Dark : ElementTheme.Light;

**Comment by JerryNixon** [comment]
Fixed it with this

``` csharp
public ApplicationTheme AppTheme
{
    get
    {
        var theme = ApplicationTheme.Light;
        var value = _helper.Read<string>(nameof(AppTheme), theme.ToString());
        return Enum.TryParse<ApplicationTheme>(value, out theme) ? theme : ApplicationTheme.Dark;
    }
    set
    {
        _helper.Write(nameof(AppTheme), value.ToString());
        (Window.Current.Content as FrameworkElement).RequestedTheme = value.ToElementTheme();
        Views.Shell.HamburgerMenu.RefreshStyles(value);
    }
}
```
