### ISSUE TITLE
Page state should be also associated with backstack depth and frame.

### ISSUE THREAD

**Issue by LukasNeoproud** [Windows-XAML/Template10#655]
I noticed in FrameFacade class that PageStateSettingsService method uses only page type to retrieve a state dictionary. What about when I have more instances of a same page type in backstack? Is it correct to get the same state dictionary for all of them?

I think there should also be backstack depth to differentiate between multiple instances and frame ID so it also supports multiple frames/windows.

**Comment by JerryNixon** [comment]
I agree. I look forward to your pull request.
