### ISSUE TITLE
HamburgerMenu issues

### ISSUE THREAD

**Issue by Stusu** [Windows-XAML/Template10#661]
I want to have CompactOverlay menu for narrow state and CompactInline for normal and wide, also I wanted to have hamburger menu button always visible so I changed its visual state setters:
For narrow
`<Setter Target="ShellSplitView.DisplayMode" Value="CompactOverlay" />`
`<Setter Target="ShellSplitView.IsPaneOpen" Value="False" />`
`<Setter Target="HamburgerButton.Visibility" Value="Visible" />`

For wide:
`<Setter Target="ShellSplitView.DisplayMode" Value="CompactInline" />`
`<Setter Target="ShellSplitView.IsPaneOpen" Value="True" />`
`<Setter Target="HamburgerButton.Visibility" Value="Visible" />`

Such small change causes that on narrow and wide states next to button there is empty/white space and what is more on wide state hamburger button doesn't work. For some reason 
`IsOpen = !IsOpen;` doesn't change value from true to false.

Screenshots: http://1drv.ms/1SR4tme

**Comment by JerryNixon** [comment]
Fixed it with this

````csharp
public ApplicationTheme AppTheme
{
    get
    {
        var theme = ApplicationTheme.Light;
        var value = _helper.Read<string>(nameof(AppTheme), theme.ToString());
        return Enum.TryParse<ApplicationTheme>(value, out theme) ? theme : ApplicationTheme.Dark;
    }
    set
    {
        _helper.Write(nameof(AppTheme), value.ToString());
        (Window.Current.Content as FrameworkElement).RequestedTheme = value.ToElementTheme();
        Views.Shell.HamburgerMenu.RefreshStyles(value);
    }
}
````
