### ISSUE TITLE
Minimal App with Hamburger Shell fails WACK PreLaunch

### ISSUE THREAD

**Issue by ktd12** [Windows-XAML/Template10#668]
If you take the Minimal App, add a Hamburger Shell to it, and then try to submit the app to the store, the app will fail WACK with a Prelaunch violation.  If you do not add a Shell to the Minimal app, it will pass the Prelaunch test.  In all cases, the app runs fine when the Hamburger Shell is included (including the Visual Studio test of:  Debug > Other Debug Targets > Debug App Prelaunch > Suspend > Resume).   It just can't pass the WACK Prelaunch test.  It would be very helpful if the WACK folks would tell us how we should  test  our apps for Prelaunch in Visual Studio.

I used a copy of the Template 10 Library downloaded this morning 2/18/2016 at 8 am EST.
Here is what I changed in the Minimal App:
1. App.xaml.cs  - I set up the Hamburger Shell in OnInitializeAsync.  I added an empty override of OnPrelaunchAsync, OnResuming, OnSuspendingAsync.  App.xaml.cs is included in attached zip.
2. I Added a Shell.xaml and Shell.xaml.cs to the project.  Files are included in attached zip.

[Wack Prelaunch Failure Compressed (zipped) Folder.zip](https://github.com/Windows-XAML/Template10/files/136514/Wack.Prelaunch.Failure.Compressed.zipped.Folder.zip)

**Comment by artfuldev** [comment]
Facing similar issue

**Comment by ktd12** [comment]
Good news - I figured out what was wrong and now both the Minimal Project and my app pass the WACK prelaunch test!
I changed OnInitializeAsync to this (which is how it is done in the Hamburger sample):
This Works:

>  public override Task OnInitializeAsync (IActivatedEventArgs args)
>  {  
>     if ( (Window.Current.Content as ModalDialog) == null )  
>     {   // setup hamburger shell  
>         var nav = NavigationServiceFactory(BackButton.Attach, ExistingContent.Include);  
>         Window.Current.Content = new ModalDialog  
>         { DisableBackButtonWhenModal = true, Content = new Views.Shell(nav), ModalContent = new Views.Busy(), };  
>     }
>         return Task.CompletedTask;
>  }

This Does NOT work (this is a version of OnInitializeAsync from an older release of Template 10)

> public override Task OnInitializeAsync (IActivatedEventArgs args)
>         {
>             // setup hamburger shell
>             var nav = NavigationServiceFactory(BackButton.Attach, ExistingContent.Include);
>             Window.Current.Content = new Views.Shell(nav);
>             return Task.CompletedTask;
>         }

I have attached the 3 files  (App.xaml.cs, Shell.xaml.cs, Shell.xaml).  Replace these in the Minimal Project and you will be good to go (this will give you a Minimal project with a Hamburger).
[Wack Prelaunch Pass Compressed (zipped) Folder.zip](https://github.com/Windows-XAML/Template10/files/137257/Wack.Prelaunch.Pass.Compressed.zipped.Folder.zip)
