### ISSUE TITLE
HamburgerMenu Background property gets overwritten on Accent Color change

### ISSUE THREAD

**Issue by LostLogic** [Windows-XAML/Template10#670]
Hi,
If I set <HamburgerMenu HamburgerBackground="{x:Null}" the property is overwritten with "CustomColor" when the accent color in Windows changes. 

This, in my setup happens every 15 minutes due to rotating wallpapers and accent color generated from said wallpaper.

I am using the latest GIT code (Not NuGet package)

**Comment by JerryNixon** [comment]
Yes. This is true.

**Comment by JerryNixon** [comment]
You can set it directly in the HamMenu tag. Just not using a style.

**Comment by JerryNixon** [comment]
I will eventually fix this. Just not sure how yet. Suggestions?

**Comment by LostLogic** [comment]
I'll look into it and explore some ideas. If I come up with anything I'll post them here.

**Comment by JerryNixon** [comment]
Thanks
