### ISSUE TITLE
Cannot deserialize XBF metadata type list as 'DataTriggerBehavior'...

### ISSUE THREAD

**Issue by Asgardi** [Windows-XAML/Template10#671]
I get the following error at runtime:

"Cannot deserialize XBF metadata type list as 'DataTriggerBehavior' was not found in namespace 'Microsoft.Xaml.Interactions.Core'. [Line: 14 Position: 56]"

This is coming from Shell.xaml when using 
"
 <Controls:ModalDialog IsModal="{x:Bind IsBusy, Mode=OneWay}" CanBackButtonDismiss="False" DisableBackButtonWhenModal="True">
        Controls:ModalDialog.Content
            <Controls:HamburgerMenu x:Name="MyHamburgerMenu">
...
"
Designer works fine though, this comes at runtime only. Compiled with VS2015 Update 2 on W10 14267. Worked fine before updating to these betas.

**Comment by JerryNixon** [comment]
Is this Native or debug?

**Comment by Asgardi** [comment]
Debug. But release didnt work either. And it happens also on my phone (latest build too).

**Comment by DanoneKiD** [comment]
Same issue on Visual Studio 2015 Update 2 CTP Windows 10 10586.104

**Comment by Asgardi** [comment]
Any idea for workaround?

**Comment by JerryNixon** [comment]
You are not the first to tell me that Update 2 CTP does not work properly. We'll make it work, but I bet RTM will work remarkably better. Sorry for being in limbo.
