### ISSUE TITLE
Double navigation call with HamburgerButtonInfo.PageParameter

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [Windows-XAML/Template10#673]
Hi, 
when trying to set the parameter for the navigation page with x:Bind for some reason Navigation gets called twice.
<controls:HamburgerButtonInfo PageType="views:SearchResultsPage" PageParameter="{x:Bind ViewModel.UndiscoveredParams}">

**Comment by Viachaslau-Zinkevich** [comment]
Actually this happens whenever the parameter is present, event hardcoded in xaml. If I remove it -- the navigation happens once

**Comment by JerryNixon** [comment]
So this is only when there is a page parameter.

And you click the button and the page being navigated to gets OnNavigatedTo firing two times or is instantiated two times? The only variable here is page parameter in the button info?

**Comment by Viachaslau-Zinkevich** [comment]
1) Yes, this happens only when PageParameter is there
2) I click the button and the following events happen, assuming I navigate to SearchVM: SearchVM.OnNavigatedFromAsync->SearchVM.OnNavigatedToAsync->SearchVM.OnNavigatedToAsync
3) Each time VMs are new and the pages are new, too.  When I then click Back button, I get to the same previous page.
4)<controls:HamburgerButtonInfo PageType="views:SearchResultsPage" PageParameter="{x:Bind ViewModel.UndiscoveredParams}"> The example of button causing the issue. With UI content inside, of course

**Comment by mvermef** [comment]
Could you post your xaml of the affected event and VMs associated? Want to see how you wired x:bind call

**Comment by mltejera** [comment]
I can confirm this behavior as well, though it doesn't appear to be related to x:bind, as it also happened when I hard coded the page parameter in xaml. This manifested itself as having to hit the nav back button twice - removing the page parameter and I only had to hit it once.

Oddly enough though, when I created my own hamburger buttons programmatically and set the page parameter there in C#, I do not get the double navigation.

**Comment by crazycreak** [comment]
I think this is the same problem, as I have tried to describe here #641, when i remove the PageParameter from the HamburgerButtonInfo then it works (OnNavigatedToAsync is called only once)

**Comment by liptonbeer** [comment]
Hi,
The problem lies in method HighlightCorrectButton in the HamburgerMenu control. The pageParameter that is passed to the method is serialized, therefore this check is wrong:
`buttons = buttons
                .Where(x => Equals(x.Value.PageParameter, null) || Equals(x.Value.PageParameter, pageParam));`
because the button.PageParameter in not serialized and pageParam is serialized, so the matching returns 0 elements.

I suggest deserializing pageParameter before above expression like this:
`if (pageParam == null)
                pageParam = NavigationService.CurrentPageParam;
            else
                pageParam = NavigationService?.FrameFacade?.SerializationService?.Deserialize(pageParam.ToString());`

I don't know if this is a right way to access SerializationService from HamburgerMenu control.

**Comment by JerryNixon** [comment]
I confirm this is an issue.

**Comment by JerryNixon** [comment]
Fixed. Thanks @liptonbeer
