### ISSUE TITLE
Problem with hamburger menu with lastest nuget version

### ISSUE THREAD

**Issue by a-iafrate** [Windows-XAML/Template10#674]
Hi,
i have update nuget package from 1.1.3 to 1.1.4 and now i have a problem with hamburger menu

the first image is with previews version. i missing something to update?

Thanks!

![err1](https://cloud.githubusercontent.com/assets/8555750/13214309/22f4fbdc-d94f-11e5-888b-68fdd432bdf7.PNG)
![err2](https://cloud.githubusercontent.com/assets/8555750/13214310/22f6115c-d94f-11e5-9976-d17b2f5afeda.PNG)

**Comment by JerryNixon** [comment]
Not sure. How are you doing that?

**Comment by toituu** [comment]
I'm actually seeing this same issues. Happens every time if app is launched directly in wide mode.

**Comment by JerryNixon** [comment]
Hmm. Can't dupe.
