### ISSUE TITLE
System.UnauthorizedAccessException from Native app build

### ISSUE THREAD

**Issue by jaccus** [Windows-XAML/Template10#677]
Getting the following on my app insights for ARM app in store:

`System.UnauthorizedAccessException`

`Access is denied. (Excep_FromHResult 0x80070005)`

>    at SharedLibrary!<BaseAddress>+0x444609
>    at SharedLibrary!<BaseAddress>+0x446605
>    at SharedLibrary!<BaseAddress>+0x494f55
>    at SharedLibrary!<BaseAddress>+0x494f2f
>    at SharedLibrary!<BaseAddress>+0x494f19
>    at SharedLibrary!<BaseAddress>+0x55fb93
> --- End of stack trace from previous location where exception was thrown ---
>    at SharedLibrary!<BaseAddress>+0x329115
>    at SharedLibrary!<BaseAddress>+0x329207
>    at SharedLibrary!<BaseAddress>+0x34d603

App has the fix PRd in #630 so apparently it did not solve the issue completely.

**Comment by JerryNixon** [comment]
What version of T10 are you using?

**Comment by jaccus** [comment]
I'm on master from 19th Feb (285a8ce).

**Comment by JerryNixon** [comment]
Could you point to 1.1.4 in NuGet? And let me know?

**Comment by arpadbarta** [comment]
Hi there, I have been experiencing the same issue, updating to 1.1.4 indeed fixed it however now the app fails on WAC with the prelaunch test. Which I believe was fixed with version 1.1.3 but seems like it's back again...

**Comment by jaccus** [comment]
Switched to 1.1.4 package instead of source code referenced solution, included recent NETCore package update and so far did not get any crashes for the last 2 days.

Do you maybe somewhere track which versions get released in nuget packages (couldn't find tags/changelog)? Would love to know which commit I'm on when using packages.

Otherwise, I won't mind closing this issue.

**Comment by ghost** [comment]
Same thing here using 1.1.4!
Access is denied. (Excep_FromHResult 0x80070005)
