### ISSUE TITLE
PROPOSED: Redstone breaking changes

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#678]
Tracking/Planning changes and fixes targeting the Windows 10 Redstone 1 update this summer.

> This will include some breaking changes

Reference Prism for MVVM

Change Bootstrapper
- [ ] Throw exception if detect multiple TitleBar styles

Change ModalDialog control
- [ ] Rename ModalDialog > ModalHost
- [ ] Rename ModalDialog.ModalContent > ModalHost.OverlayContent
- [ ] Rename ModalDialog.IsModal > ModalHost.IsOpen
- [ ] Change ModalDialog.DisableBackButtonWhenModal default to true
- [ ] Rename DisableBackButtonWhenModal > DisableBackNavigationWhenOpen

Change NavigationService
- [ ] Make ClearCache() private
- [ ] Make SuspendingAsync() private
- [ ] Make Resuming() private
- [ ] Make SaveNavigationAsync() private
- [ ] Make RestoreSavedNavigationAsync() private
- [ ] Make AfterRestoreSavedNavigation internal
- [ ] Make Frame private
- [ ] Make FrameFacade private

Change KeyboardService
- [ ] Make KeyboardHelper internal
- [ ] Rename KeyboardService to KeyboardServiceBase
- [ ] Make KeyboardHelper a private, static field
- [ ] Create protected KeyDown event

Change SettingsService
- [ ] Make SettingHelper internal
- [ ] Rename SettingService to SettingServiceBase
- [ ] Make SettingHelper a private, static field
- [ ] Expose protected Read/Write methods
- [ ] Update template to SettingService : SettingServiceBase

Change hamburger
- [ ] Make layout RelativePanel
- [ ] Move templates to Generic.xaml

**Comment by petrolhead90ish** [comment]
The title should be Redstone breaking changes, not "Restone".

**Comment by Opiumtm** [comment]
Could you link to some information about redstone API changes?

**Comment by kenshinthebattosai** [comment]
If you create a new branch for this we could start contributing to it :+1:

**Comment by JerryNixon** [comment]
Thanks man, I am inspired by your enthusiasm.

**Comment by callummoffat** [comment]
I like that idea. That way, it'll be ready for you to launch prerelease packages by June/July when Redstone comes out. Then, bleeding-edge Nuget users can trial it, and help sort things out, before it launches in full a few months later.
