### ISSUE TITLE
Add additional colors as theme resources

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#68]
https://msdn.microsoft.com/en-us/library/windows/apps/windows.ui.viewmanagement.uicolortype

**Comment by ghost** [comment]
I can help out on this as I am already trying to do this

**Comment by JerryNixon** [comment]
Perfection. Update your code base, lots of changes.

**Comment by JerryNixon** [comment]
Have you made any progress?

**Comment by ghost** [comment]
Some will try and post something for you soon.

**Comment by JerryNixon** [comment]
Cool. Let me know.

**Comment by JerryNixon** [comment]
How's it coming?

**Comment by h82258652** [comment]
This is easy to use:

``` C#
new UISettings().GetColorValue(UIColorType.Accent);
```

But in mobile, the method "GetColorValue" will throw a InvalidCastException.
I think use:

``` C#
(Color)Application.Current.Resources["SystemAccentColor"];
```

It's better.
