### ISSUE TITLE
Animated/Extended splash does not show on Phone

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#680]

**Comment by JerryNixon** [comment]
I am closing this because I am now seeing the ex splash screen on my 950.

**Comment by jerinjohnk** [comment]
@JerryNixon I saw you closed this bug. Whereas its still occurring in VS emulator and windows 10.0.10586.107 lumia 630 testing device using nuget package. Is it fixed in different windows 10 version or do we have to download latest library.
