### ISSUE TITLE
[Question] Splash Screen

### ISSUE THREAD

**Issue by gsantopaolo** [Windows-XAML/Template10#683]
Hi there,
   I've created a new minimal 10 app, just changed the Splash.xaml to point to a correct image, but when I launch the app I don't see it.
I think I'm missing something but can't figure out what...

thank you for helping
-g

**Comment by JerryNixon** [comment]
Show me some code.

**Comment by sebfrie** [comment]
Maybe you mean an extended splash screen on phone? That's known, see issue #680.

**Comment by lyling** [comment]
i can`t see it on emulator, lumia 920 and desktop

**Comment by lyling** [comment]
@JerryNixon any idea?
