### ISSUE TITLE
Problem with Microsoft.Xaml.Behaviors.Wup.Managed 1.1.0

### ISSUE THREAD

**Issue by ghost** [Windows-XAML/Template10#685]
When upgrading the nuget package "Microsoft.Xaml.Behaviors.Wup.Managed" from 1.0.3 til 1.1.0 I cannot complie.
Error:
"The type 'ActionCollection' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Xaml.Interactivity, Version=1.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'."

Scott from Microsoft/XAMLBehaviors says: "Template10 needs updating to 1.1 so that it's not dependent on the version of xaml behaviours that has strong naming. I'll try and do a PR for that later, but will require @jerrynixon to push an update when it's in."

For now I have to use the nuget package version 1.0.3, But I hope this can be fixed :-)

**Comment by ghost** [comment]
Microsoft.Xaml.Behaviors.Uwp.Managed ...

**Comment by ScottIsAFool** [comment]
Not sure why this has been closed, but just about to submit a PR that addresses this issue.

**Comment by tolgabalci** [comment]
Yup, it shouldn't be closed, the issue still exists and now merged in.  Minimal and Hamburger Templates and about half the samples no longer compile without changing back the Behaviors to 1.0.3.

**Comment by ScottIsAFool** [comment]
The issue will continue to exist until the Template10 nuget package gets updated as the Template10 reference is still pointing to the old Behaviours package.

**Comment by tolgabalci** [comment]
Okay, I understand now.  I hadn't realized that the projects in the GitHub solution were pointing to the nuget package and not the Template10 libraries included in the solution.

Thanks for the clarification.

**Comment by CodingGorilla** [comment]
I'm assuming this is still an issue, since I'm running into it, is the only work around to change the reference back to 1.0.3 in your project.json?
