### ISSUE TITLE
Hamburger Buttons should fire commands too in addition to page navigation

### ISSUE THREAD

**Issue by mltejera** [Windows-XAML/Template10#688]
It would be great if we could fire commands to the current page in the shell from the hamburger buttons!

**Comment by JerryNixon** [comment]
What kind of commands? And, more importantly, why can't you?

**Comment by mltejera** [comment]
In a lot of our apps, we leverage a MainPageViewModel that uses delegate commands & parameters to filter groups in a hub.

I dug deeper into what we now get in T10 out of the box and saw this new fangled Event Binding with x:Bind. Having read up a little on the subject, I think it will really meet a lot of our needs. What I wasn't clear on was how to manage parameters?

**Comment by JerryNixon** [comment]
There is already a ButtonType.Command that can be used to raise a Tapped event. Can't you x:bind that to a view-model method?

**Comment by mltejera** [comment]
Great - thanks!
