### ISSUE TITLE
Services without Interfaces

### ISSUE THREAD

**Issue by romeop555** [Windows-XAML/Template10#69]
I see all the Services implementations in "Template10 (Services)" have not Interfaces implementation, unlike the great demo MVA (Oct 2014) Developing Universal Windows Apps with C# and XAML in which every Service has Service, Helper and Interface and from which they seem to be all stealed but the Interfaces

Is there a specific reason or are you planning to implement Interfaces in order to use Dependency Injection?

I can implement though with a pull request if you agree

**Comment by JerryNixon** [comment]
You are correct. There are no interfaces. What would be the downside of including interfaces? Better testing. Easier injection for services in sep. assemblies. I think they should all include matching interfaces. After all, it's how I have been teaching injection for years. Not all those services are "ready". Many of them are just getting written (converted) now. That being said, I would love to see a pull request with all their interfaces, and we will just set the expectation that the interfaces will be keep in sync.

**Comment by romeop555** [comment]
ok nice to know, i'm implementing inrerfaces for all services, in a couple of days i'll do a pull request

**Comment by RomeoPavoni** [comment]
ok i did it with this account it's always me
