### ISSUE TITLE
Cannot deserialize XBF metadata type list as 'BootStrapper'... after updating Microsoft.NETCore

### ISSUE THREAD

**Issue by toituu** [Windows-XAML/Template10#691]
After updating Microsoft.NETCore.UniversalWindowsPlatform 5.1.0 now available, running application based on Template10 will always fire Cannot deserialize XBF metadata type list as 'BootStrapper'... type of exception on runtime when launching the app.

**Comment by JerryNixon** [comment]
How do you repeat this err?

**Comment by toituu** [comment]
Well, just by launching the existing app after updating Microsoft.NETCore.UniversalWindowsPlatform. Launch fails every time. After rolling back the update, launching the app works fine. No other specific steps involved.

**Comment by toituu** [comment]
Apparently the update to the Microsoft.NETCore.UniversalWindowsPlatform has been withdrawn as no longer available through NuGet. Thus, this issue is invalid, at least for now.
