### ISSUE TITLE
Latest Master will not build

### ISSUE THREAD

**Issue by tolgabalci** [Windows-XAML/Template10#693]
Trying earlier versions seem to be fine.  But I wanted the version with the HamburgerTemplate so I got the head.

I tried blowing away my TemplateFolder and:
git clone https://github.com/Windows-XAML/Template10
Reload Template10.sln, Clean, Rebuild solution
Still get the below errors.

Tried on a different system.  Same exact results.
I'm using:
Visual Studio 2015 Enterprise update 1
Windows 10 Enterprise build 14267

I'm fairly new to Template10.  My apologies if I'm missing something obvious.

**Errors received on multiple machines, after solution level clean and rebuild:**
`Severity   Code    Description Project File    Line    Suppression State
Error   CS0103  The name 'InitializeComponent' does not exist in the current context    BottomAppBar    C:\git\Template10\Samples\BottomAppBar\App.xaml.cs  12  Active
Error   CS0103  The name 'InitializeComponent' does not exist in the current context    BottomAppBar    C:\git\Template10\Samples\BottomAppBar\Views\MainPage.xaml.cs   13  Active
Error   CS1061  'Shell' does not contain a definition for 'MyHamburgerMenu' and no extension method 'MyHamburgerMenu' accepting a first argument of type 'Shell' could be found (are you missing a using directive or an assembly reference?)   BottomAppBar    C:\git\Template10\Samples\BottomAppBar\Views\Shell.xaml.cs  14  Active
Error   CS0103  The name 'InitializeComponent' does not exist in the current context    BottomAppBar    C:\git\Template10\Samples\BottomAppBar\Views\Shell.xaml.cs  19  Active
Error   CS0012  The type 'ActionCollection' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Xaml.Interactivity, Version=1.0.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   Minimal C:\Git\Template10\Templates (Project)\Minimal\obj\x86\Debug\XamlTypeInfo.g.cs   1288    Active
Error       Could not copy "C:\git\Template10\Template10 (Installer)\Template10.MSBUILD\bin\Debug\Template10.MSBUILD.dll" to "C:\Git\Template10\Template10 (Installer)\Lib\Template10.MSBUILD.dll". Exceeded retry count of 10. Failed. Template10.MSBUILD  C:\git\Template10\Template10 (Installer)\Template10.MSBUILD\Template10.MSBUILD.csproj   77  
Error       Unable to copy file "C:\git\Template10\Template10 (Installer)\Template10.MSBUILD\bin\Debug\Template10.MSBUILD.dll" to "C:\Git\Template10\Template10 (Installer)\Lib\Template10.MSBUILD.dll". The process cannot access the file 'C:\Git\Template10\Template10 (Installer)\Lib\Template10.MSBUILD.dll' because it is being used by another process.  Template10.MSBUILD  C:\git\Template10\Template10 (Installer)\Template10.MSBUILD\Template10.MSBUILD.csproj   77  
Warning CS0105  The using directive for 'Messaging.Shared' appeared previously in this namespace    IncrementalLoading  C:\git\Template10\Samples\IncrementalLoading\IncrementalLoading\DataModels\RepositorySource.cs  4   Active
Warning CS0618  'BootStrapper.ResolveForPage(Type, NavigationService)' is obsolete: 'Use ResolveForPage(Page, NavigationService) instead'   Template10 (Library)    C:\git\Template10\Template10 (Library)\Common\BootStrapper.cs   52  Active
Warning CS0618  'StateItemKey.StateItemKey(Type, string)' is obsolete: 'Use string keys for StateItems.'    Template10 (Library)    C:\git\Template10\Template10 (Library)\Common\StateItems.cs 76  Active
Warning CS0618  'StateItemKey.StateItemKey(Type, string)' is obsolete: 'Use string keys for StateItems.'    Template10 (Library)    C:\git\Template10\Template10 (Library)\Common\StateItems.cs 91  Active
Warning     Referenced assembly 'Microsoft.Xaml.Interactions, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.   Template10 (Library)    C:\git\Template10\Template10 (Library)\CSC      
Warning     Referenced assembly 'Microsoft.Xaml.Interactivity, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.  Template10 (Library)    C:\git\Template10\Template10 (Library)\CSC      
Warning     Unknown member 'AutoHighlightCorrectButton' on element 'HamburgerMenu'  BottomAppBar    C:\git\Template10\Samples\BottomAppBar\Views\Shell.xaml 18  
Warning     Could not copy "C:\git\Template10\Template10 (Installer)\Template10.MSBUILD\bin\Debug\Template10.MSBUILD.dll" to "C:\Git\Template10\Template10 (Installer)\Lib\Template10.MSBUILD.dll". Beginning retry 1 in 1000ms. The process cannot access the file 'C:\Git\Template10\Template10 (Installer)\Lib\Template10.MSBUILD.dll' because it is being used by another process.  Template10.MSBUILD  C:\git\Template10\Template10 (Installer)\Template10.MSBUILD\Template10.MSBUILD.csproj   77  
Warning     Could not copy "C:\git\Template10\Template10 (Installer)\Template10.MSBUILD\bin\Debug\Template10.MSBUILD.dll" to "C:\Git\Template10\Template10 (Installer)\Lib\Template10.MSBUILD.dll". Beginning retry 2 in 1000ms. The process cannot access the file 'C:\Git\Template10\Template10 (Installer)\Lib\Template10.MSBUILD.dll' because it is being used by another process.  Template10.MSBUILD  C:\git\Template10\Template10 (Installer)\Template10.MSBUILD\Template10.MSBUILD.csproj   77  
Warning     Could not copy "C:\git\Template10\Template10 (Installer)\Template10.MSBUILD\bin\Debug\Template10.MSBUILD.dll" to "C:\Git\Template10\Template10 (Installer)\Lib\Template10.MSBUILD.dll". Beginning retry 3 in 1000ms. The process cannot access the file 'C:\Git\Template10\Template10 (Installer)\Lib\Template10.MSBUILD.dll' because it is being used by another process.  Template10.MSBUILD  C:\git\Template10\Template10 (Installer)\Template10.MSBUILD\Template10.MSBUILD.csproj   77  
Warning     Could not copy "C:\git\Template10\Template10 (Installer)\Template10.MSBUILD\bin\Debug\Template10.MSBUILD.dll" to "C:\Git\Template10\Template10 (Installer)\Lib\Template10.MSBUILD.dll". Beginning retry 4 in 1000ms. The process cannot access the file 'C:\Git\Template10\Template10 (Installer)\Lib\Template10.MSBUILD.dll' because it is being used by another process.  Template10.MSBUILD  C:\git\Template10\Template10 (Installer)\Template10.MSBUILD\Template10.MSBUILD.csproj   77  
Warning     Could not copy "C:\git\Template10\Template10 (Installer)\Template10.MSBUILD\bin\Debug\Template10.MSBUILD.dll" to "C:\Git\Template10\Template10 (Installer)\Lib\Template10.MSBUILD.dll". Beginning retry 5 in 1000ms. The process cannot access the file 'C:\Git\Template10\Template10 (Installer)\Lib\Template10.MSBUILD.dll' because it is being used by another process.  Template10.MSBUILD  C:\git\Template10\Template10 (Installer)\Template10.MSBUILD\Template10.MSBUILD.csproj   77  
Warning     Could not copy "C:\git\Template10\Template10 (Installer)\Template10.MSBUILD\bin\Debug\Template10.MSBUILD.dll" to "C:\Git\Template10\Template10 (Installer)\Lib\Template10.MSBUILD.dll". Beginning retry 6 in 1000ms. The process cannot access the file 'C:\Git\Template10\Template10 (Installer)\Lib\Template10.MSBUILD.dll' because it is being used by another process.  Template10.MSBUILD  C:\git\Template10\Template10 (Installer)\Template10.MSBUILD\Template10.MSBUILD.csproj   77  
Warning     Could not copy "C:\git\Template10\Template10 (Installer)\Template10.MSBUILD\bin\Debug\Template10.MSBUILD.dll" to "C:\Git\Template10\Template10 (Installer)\Lib\Template10.MSBUILD.dll". Beginning retry 7 in 1000ms. The process cannot access the file 'C:\Git\Template10\Template10 (Installer)\Lib\Template10.MSBUILD.dll' because it is being used by another process.  Template10.MSBUILD  C:\git\Template10\Template10 (Installer)\Template10.MSBUILD\Template10.MSBUILD.csproj   77  
Warning     Could not copy "C:\git\Template10\Template10 (Installer)\Template10.MSBUILD\bin\Debug\Template10.MSBUILD.dll" to "C:\Git\Template10\Template10 (Installer)\Lib\Template10.MSBUILD.dll". Beginning retry 8 in 1000ms. The process cannot access the file 'C:\Git\Template10\Template10 (Installer)\Lib\Template10.MSBUILD.dll' because it is being used by another process.  Template10.MSBUILD  C:\git\Template10\Template10 (Installer)\Template10.MSBUILD\Template10.MSBUILD.csproj   77  
Warning     Could not copy "C:\git\Template10\Template10 (Installer)\Template10.MSBUILD\bin\Debug\Template10.MSBUILD.dll" to "C:\Git\Template10\Template10 (Installer)\Lib\Template10.MSBUILD.dll". Beginning retry 9 in 1000ms. The process cannot access the file 'C:\Git\Template10\Template10 (Installer)\Lib\Template10.MSBUILD.dll' because it is being used by another process.  Template10.MSBUILD  C:\git\Template10\Template10 (Installer)\Template10.MSBUILD\Template10.MSBUILD.csproj   77  
Warning     Could not copy "C:\git\Template10\Template10 (Installer)\Template10.MSBUILD\bin\Debug\Template10.MSBUILD.dll" to "C:\Git\Template10\Template10 (Installer)\Lib\Template10.MSBUILD.dll". Beginning retry 10 in 1000ms. The process cannot access the file 'C:\Git\Template10\Template10 (Installer)\Lib\Template10.MSBUILD.dll' because it is being used by another process. Template10.MSBUILD  C:\git\Template10\Template10 (Installer)\Template10.MSBUILD\Template10.MSBUILD.csproj   77  
Warning     Dependency specified was Template10 (≥ 1.1.4-pre) but ended up with Template10 1.1.4.         0   
Warning     Dependency specified was Template10 (≥ 1.1.4-pre) but ended up with Template10 1.1.4.         0   
Warning     Dependency specified was Template10 (≥ 1.1.4-pre) but ended up with Template10 1.1.4.         0   
Warning     Dependency specified was Template10 (≥ 1.1.4-pre) but ended up with Template10 1.1.4.         0   
Warning     Dependency specified was Template10 (≥ 1.1.4-pre) but ended up with Template10 1.1.4.         0   
Warning     Dependency specified was Template10 (≥ 1.1.4-pre) but ended up with Template10 1.1.4.         0   
Warning     Dependency specified was Template10 (≥ 1.1.4-pre) but ended up with Template10 1.1.4.         0   
Warning     Dependency specified was Template10 (≥ 1.1.4-pre) but ended up with Template10 1.1.4.         0   
Warning     Dependency specified was Template10 (≥ 1.1.4-pre) but ended up with Template10 1.1.4.         0   
Warning     Dependency specified was Template10 (≥ 1.1.4-pre) but ended up with Template10 1.1.4.         0   
Warning     Dependency specified was Template10 (≥ 1.1.4-pre) but ended up with Template10 1.1.4.         0   
Warning     Dependency specified was Template10 (≥ 1.1.4-pre) but ended up with Template10 1.1.4.         0   
Warning     Dependency specified was Template10 (≥ 1.1.4-pre) but ended up with Template10 1.1.4.         0   
Warning     Dependency specified was Template10 (≥ 1.1.4-pre) but ended up with Template10 1.1.4.         0   
Warning     Dependency specified was Template10 (≥ 1.1.4-pre) but ended up with Template10 1.1.4.         0   
Warning     Dependency specified was Template10 (≥ 1.1.4-pre) but ended up with Template10 1.1.4.         0   
Warning     Dependency specified was Template10 (≥ 1.1.4-pre) but ended up with Template10 1.1.4.         0   
Warning     Dependency specified was Template10 (≥ 1.1.4-pre) but ended up with Template10 1.1.4.         0   
Warning     Dependency specified was Template10 (≥ 1.1.4-pre) but ended up with Template10 1.1.4.         0   
Warning     Dependency specified was Template10 (≥ 1.1.4-pre) but ended up with Template10 1.1.4.         0   
Warning     Dependency specified was Template10 (≥ 1.1.4-pre) but ended up with Template10 1.1.4.         0   
`

**Comment by mvermef** [comment]
Build 14267 might be part of the problem...

**Comment by tolgabalci** [comment]
Lot of the errors are in the form:
Error Unable to copy file 
"C:\git\Template10\Template10 (Installer)\Template10.MSBUILD\bin\Debug\Template10.MSBUILD.dll"
to 
"C:\Git\Template10\Template10 (Installer)\Lib\Template10.MSBUILD.dll".

The process cannot access the file 'C:\Git\Template10\Template10 (Installer)\Lib\Template10.MSBUILD.dll' because it is being used by another process.

But nothing else is using it and C:\Git\Template10 is a brand new folder.  I even rebooted just in case, and still no luck.

Anyone else on the fast insider build of Win10 which uses Build 14267 right now that can try this?

**Comment by tolgabalci** [comment]
Okay, looks like when the changes included in 040dfe5 are pushed to nuget this will be resolved.

**Comment by carlosrfernandez** [comment]
After updating to 1.1.8 nugget package, I'm getting this error:

`The type 'ActionCollection' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Xaml.Interactivity, Version=1.0.3.0,`

Can anyone point me in the right direction? I've tried cleaning up everything, short of re-creating the entire UWP project.

**Comment by darenm** [comment]
You need to roll back to an earlier version of the Behaviors NuGet package
I used "Microsoft.Xaml.Behaviors.Uwp.Managed": "1.0.3",

**Comment by carlosrfernandez** [comment]
Thank you, that did it :)

**Comment by gratitudepod** [comment]
@darenm :100: 
Thanks for your help. I rolled back to v1.0.3 and the error went away.

Cheers!

**Comment by pauldubois777** [comment]
Yes, thank you.  That fixed it for me.  Not sure why it started to show up, when it was working fine, and I didn't update anything.
