### ISSUE TITLE
It appears that the back button in detail and settings page header doesn't work

### ISSUE THREAD

**Issue by gustavogavancho** [Windows-XAML/Template10#694]
Perhaps it's my lack of knowledge.

**Comment by dubstylee** [comment]
Update to the newest version of the Nuget package. It is working now, as of version 1.1.5. You just need to do a clean/rebuild and refresh your project from the solution explorer after you have updated the Nuget package, and then you should be good to go.

**Comment by gustavogavancho** [comment]
Thanks. I'll do that
