### ISSUE TITLE
Hamburger menu's pane doesn't stay open in wide state

### ISSUE THREAD

**Issue by sebfrie** [Windows-XAML/Template10#696]
The implementation in nuget package 1.1.5 solving #689 is great (although I don't find any corresponding commit).

But unfortunately the hamburger menu's pane collapses after selecting a button. This shouldn't be the case.

**Comment by JerryNixon** [comment]
I agree, this is not the desired behavior. Thanks for reporting this.

**Comment by darshanrampatel** [comment]
@JerryNixon, was about to raise this! Thanks for fixing so quickly.

**Comment by kingmathers313** [comment]
I noticed that when pressing the same button twice the Hamburger Menu pane still collapses.

When the pane is in wide state (on a large screen as set by VisualStateWideMinWidth) I can use the buttons in the hamburger menu to switch to any page and the pane will stay in wide state as of 1.1.8, but when I press the button for the page on which I already am it still switches to normal state.
