### ISSUE TITLE
Many missing files

### ISSUE THREAD

**Issue by plettb** [Windows-XAML/Template10#7]
A clean download will not build due to numerous missing files!
This was raised as a previous issue, but closed.  It is still very much an issue.

**Comment by zangai** [comment]
Previous issue detailing the problem: #6

**Comment by JerryNixon** [comment]
![clipboard01](https://cloud.githubusercontent.com/assets/1749983/8734923/7eac61d2-2bca-11e5-9404-ccd141ef7398.jpg)

@zangai I am including an image showing how to add the Behaviors SDK.

**Comment by plettb** [comment]
It seems odd to me that this issue (and the one that preceded it that also spoke of missing files) would be closed while there are STILL files missing!  The very latest version, as of this writing, is still missing, for example, "Template10Library\Common\ViewWrapper.cs".
