### ISSUE TITLE
Template not working anymore after Microsoft Behavior update

### ISSUE THREAD

**Issue by QuentinSc** [Windows-XAML/Template10#700]
Hello,
Today I upgrade this package.

![image](https://cloud.githubusercontent.com/assets/16439299/13379742/6e69f43a-de2e-11e5-941d-2b1fd8a25146.png)

And this is the error with the Template (hamburger)

![image](https://cloud.githubusercontent.com/assets/16439299/13379752/b4e561ba-de2e-11e5-9ff0-968b259cf2b6.png)

Is it normal?

Thank you

**Comment by qmatteoq** [comment]
Hi, you need to use the last version directly from GitHub, which supports the latest version of the Behaviors SDK. The NuGet package doesn't support it yet.

**Comment by QuentinSc** [comment]
Ah okay thank you!
How of often the NuGet package is updated ?

**Comment by tolgabalci** [comment]
I have the latest version from GitHub (040dfe5 Merge pull request #686 from ScottIsAFool/feature/UpdateXamlBehaviours)

Both the Minimal and Hamburger templates give this error for me as well.

For now I just changed in the project.json the Behaviors from 1.1 to 1.0.3
"Microsoft.Xaml.Behaviors.Uwp.Managed": "1.0.3"

This seems to fix it.

**Comment by JerryNixon** [comment]
Yes, I have returned everything to 1.0.3. Something seems broken with the latest Behaviors.
