### ISSUE TITLE
Feature request: Different layout for PageHeader depending on window width (mimic Movies & TV app)

### ISSUE THREAD

**Issue by DecaTec** [Windows-XAML/Template10#701]
Hello,

I really like the hamburger navigation and the layout of the Movies & TV app which ships with Windows 10. I'm able to mimic the hamburger menu style (little bar on the left side and foreground color indicate an item as selected).
But the PageHeader control is pretty static: the only change depending on the window size is the space given to the hamburger menu button.
It would be great if the PageHeader would change its appearance on a wide window width:

Current behavior on NarrowMinWidth
Changed behavior on NormalMinWidth and WideMinWidth:
-  The background color should be the ApplicationPageBackgroundThemeBrush
-  The font should be changed

See the two screenshots of the Movies & TV app
Narrow mode:
![moviestvnarrow](https://cloud.githubusercontent.com/assets/9428899/13380274/16ccb972-de3f-11e5-892c-48b6699b5553.png)

Wide mode:
![moviestvwide](https://cloud.githubusercontent.com/assets/9428899/13380275/2349fc14-de3f-11e5-9269-9281fadbea72.png)

**Comment by JerryNixon** [comment]
Hopefully, you have already seen the VisualStateManager section in the template pages. In those, when you use Normal and Wide (similar to how Movies works) you will need to hide the PageHeader and reveal a custom PageHeader that performs this special look. It should not be a lot of work. But it does not belong in Template 10 at this point. Thanks for the suggestion.
