### ISSUE TITLE
http://aka.ms/T10-Hamburger link broken

### ISSUE THREAD

**Issue by tolgabalci** [Windows-XAML/Template10#703]
The Template10 installer specifies the link that will appear in help.htm when a new project is created:
https://github.com/Windows-XAML/Template10/blob/fc8b715cd26fe82d044990035d21a0fd999e03f6/Template10%20(Installer)/Template10.Installer/Template10.Installer.csproj

Currently there are three project templates and three links:
http://aka.ms/T10-Blank
http://aka.ms/T10-Minimal
http://aka.ms/T10-Hamburger

The top two point to:
https://github.com/Windows-XAML/Template10/wiki

I'm guessing the Hamburger template should point to the same location, but currently does not exists and ends up redirecting to Microsoft.com

Can someone working at Microsoft please point:
http://aka.ms/T10-Hamburger to https://github.com/Windows-XAML/Template10/wiki

**Comment by JerryNixon** [comment]
I will fix it. Yes.
