### ISSUE TITLE
Performance degradation because of NavButtonBehavior and possible memory leaks

### ISSUE THREAD

**Issue by Opiumtm** [Windows-XAML/Template10#705]
https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Behaviors/NavButtonBehavior.cs

After investigation with JetBrains DotTrace profiler it is revealed that `NavButtonBehavior` too often executes
`private void Calculate(bool allow = false)` method. And, this method adds a significant performance penalty. Issue show itself in a most terrible manner when Page contains ListView and user is scrolling.
Profiler trace show that it is caused by `private void LayoutUpdated(object sender, object e) { Calculate(true); }` line of code, which call `Calculate` method.

When user scrolls in a ListView, layout is updated too often (ListView is virtualizing items and so items are often recreated and repopulated). It cause major performance penalty to an application that use ListView in its layout. 

Also, NavButtonBehavior attach events to a global singleton Frame, which cause a certain memory leak and further performance degradation after user navigate between pages some time. `Frame.SizeChanged -= SizeChanged;` in a `Detach` method does not work because it is not called automatically on page unload.

`NavButtonBehavior` is used in a `PageHeader` control tempate
https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Themes/PageHeader.xaml
so it attach itself into every page and worse, it buried deep inside a control template and can not be detached by hand without a fragile tricks with visual tree 

In practice it cause a progressive performance degradation after navigations between pages. Scrolling in a ListView suffer a progressively violent lags and this lags get worse after each new page navigation, because already performance inefficient `NavButtonBehavior` does not detach from a global Frame `LayoutChanged` event and this performance cost is multiplied with each new page navigation.
Also it is need to be investigated with memory profiler if `NavButtonBehavior` can cause a global memory leak, preventing pages (which often contain view models and lots of other data inside) from be garbage collected.

Again, it do not much harm to an applications running x86 Desktop (because desktop environment have much more powerful CPU and do not constrained in free memory), but on a resource constrained ARM device it seems to be a disaster.

**Comment by Opiumtm** [comment]
I suggest use of some event throttling technique (or cease use Frame `LayoutUpdate` event) to reduce performance penalty. For global events I suggest use of WeakEvent pattern. It is generally  not wise to attach event handlers to a global singleton objects events and it is a most common cause of memory leaks in a .NET applications. To counter this risks WeakEvent pattern is strongly recommended when attaching to a global singleton object events.

**Comment by JerryNixon** [comment]
One thing at a time. You need to verify that Detach() is not called. I believe it is.

**Comment by JerryNixon** [comment]
Okay, throttled Calculate(), but I am going to ask you to test for me. I don't have the tool you are using. Do you mind? If you don't want to, I can find a way.

**Comment by Opiumtm** [comment]
@JerryNixon 

> Okay, throttled Calculate(), but I am going to ask you to test for me. I don't have the tool you are using. Do you mind? If you don't want to, I can find a way.

What kind of tests? I can do some test sometime after 12 hours. I can download latest source code, compile it, refrence in my app and use JetBrains DotTrace to measure performance penalty. For now i measured that after performance testing as in ListView created ~6000 templated items, `Calculate` was called at same ~6000 and performance report show that `Calculate` was one of a major sources of CPU load.

> One thing at a time. You need to verify that Detach() is not called. I believe it is.

I think there is no need to "believe". Attaching event handlers to a global singleton objects is **generally a bad idea** and this practice must be avoided at all costs, because it effectively eliminate automatic memory management (garbage collector can not collect objects, referenced by singleton global objects) and _manual memory management is required in this case_. To avoid this situation and to avoid high risk of memory leaks (because of _manual memory management_ such as relying on explicit call of `Detach` or `Dispose` or so on) using of WeakEvent coding pattern is strongly recommended to remove manual memory management requirement once and for all from a program written in language with automatic memory management.

**Comment by Opiumtm** [comment]
@JerryNixon and for performance penalties. I investigated this (not in a context of `NavButtonBehavior`, but it apply here anyway). Fundamental cause of performance degradation is a high cost of marshalling calls between .NET code and Windows Runtime APIs (which are plain old COM in disguise). So, I already complained about exceptionally bad performance of .NET/COM Interop to CoreRT team. .NET Native compilation do not help much. This performance issue forced me to rewrite some time critical  parts of my code in C++ language and it yields dramatic performance gain. So, this should be noted before CoreCLR team address fundamental performance problem. Calls of Windows Runtime APIs from C++ code have no runtime cost at all, but calls of same APIs from .NET managed code have a significant cost which is not eliminated even in a .NET Native compiled code. As `Calculate` calls Windows Runtime API many times, excessive `Calculate` execution cause a major performance degradation. If it will be written in C++ language there will be no performance issues, but to use C++ is too radical solution for Template10, I think :)

**Comment by Opiumtm** [comment]
@JerryNixon CoreRT team answered that .NET/COM interop improvements are coming soon in the next release of .NET Core runtime.

> Hello! Thanks for your interest in .NET Native. We've received similar feedback regarding the overhead due to interop calls and have made significant progress in the upcoming release. In particular, the amount of allocations that happen on any given interop call has been dramatically reduced. One partner application (a medium sized XAML application) sees a 90% reduction in allocations for their key scenarios. Less garbage, fewer collects.

But before they officially release next version of .NET Core tools, performance issues of .NET/COM interop should be noted.

**Comment by JerryNixon** [comment]
Yeah, okay. I wondered if you were reporting something real or not. So, just for the record, a Behavior's Detach method is called every single time. If it didn't, all hell would break loose. I am not sure why you said it didn't get called and events didn't get un-wired. So, for the sake of anyone reading this thread. The behaviors framework still functions as expected.

**Comment by JerryNixon** [comment]
Thanks @Opiumtm for your help with this error. After throttling this event, it makes sense that we might find other opportunities to throttle events throughout the framework. Thanks again for reporting this. I am closing this issue. If you discover another instance or a recurrence of this one, open a new one.
