### ISSUE TITLE
OnStartAsync not firing when lauching Template10 based app through secondary tile

### ISSUE THREAD

**Issue by toituu** [Windows-XAML/Template10#706]
I noticed that currently if one tries to launchTemplate10 based app already open in the background through pinned secondary tile, no events of any kind seem to be currently received.

The use case is such that there might be several secondary tile pointing to different views, and if user goes to home screen and tries to launch the app through secondary tile, the correct view would be opened no matter if the app was already running in the background.

Previously we were able to see this kind of launching in the OnStartAsync, but apparently some recent change has affected this as we are no longer able to see any secondary tile launching in the described scenario.

**Comment by JerryNixon** [comment]
Yes. Fixing now. Nuget update asap.
