### ISSUE TITLE
White space at top of page on W10M, NuGet 1.1.5

### ISSUE THREAD

**Issue by darshanrampatel** [Windows-XAML/Template10#710]
I'm seeing the below (unwanted) behaviour on W10M with NuGet 1.1.5 (excuse the poor pictures):

![20160301_164302](https://cloud.githubusercontent.com/assets/14162899/13434289/3e96542e-dfcd-11e5-98fb-978aaf4183d8.jpg)
![20160301_164251](https://cloud.githubusercontent.com/assets/14162899/13434290/3e9b9754-dfcd-11e5-808b-2b7853c3f57a.jpg)

This appears in both portrait and landscape mode, though it's at the top of the physical screen, not based on the device's orientation.

This doesn't happen on my W10 PC.

You can replicate this by creating a new Project with the Hamburger Template in VS2015.

**Comment by darenm** [comment]
That is the phone StatusBar with a White foreground. Add the following to your OnStartAsync method:

```
        // hide phone statusbar
        if (Windows.Foundation.Metadata.ApiInformation
            .IsTypePresent("Windows.UI.ViewManagement.StatusBar"))
        {
            await Windows.UI.ViewManagement.StatusBar.GetForCurrentView().HideAsync();
        }
```

**Comment by darshanrampatel** [comment]
@darenm, thanks! It didn't cross my mind that this was the status bar, but it's all sorted now (I'm actually using `Windows.UI.ViewManagement.StatusBar.GetForCurrentView().BackgroundOpacity = 1;` to show the StatusBar.
