### ISSUE TITLE
What is the PieSlice control?

### ISSUE THREAD

**Issue by gustavogavancho** [Windows-XAML/Template10#711]
![captura de pantalla 38](https://cloud.githubusercontent.com/assets/15368343/13436664/6df040c8-dfae-11e5-9357-6a71cb6c71b3.png)

**Comment by JerryNixon** [comment]
:) Thanks for the screen shot. I know what you mean. I plan to deprecate it and replace it with the RingSegment. I'll do that while I am thinking about it. Thanks for the reminder.

**Comment by JerryNixon** [comment]
But what is it? Here's a demo: http://blog.jerrynixon.com/2012/06/windows-8-animated-pie-slice.html
