### ISSUE TITLE
Throttling Affecting PageHeader

### ISSUE THREAD

**Issue by mvermef** [Windows-XAML/Template10#713]
Appears pageheader drawn back button arrow takes couple of seconds now to display each time a navigation occurs?  Even worse on mobile devices...

**Comment by JerryNixon** [comment]
Please check again. I resolve that this afternoon. I think you might have gotten latest in between my sync. :) Please close this issue if you find it to resolved.

**Comment by mvermef** [comment]
Meant to close sorry
