### ISSUE TITLE
Secondary commands ellipsis on pageheader when no secondary commands present

### ISSUE THREAD

**Issue by Vidyogamasta** [Windows-XAML/Template10#714]
I'm looking to have a pageheader with a single primary button with no secondary buttons. However upon adding the primary button, it looks like the EllipsisBehavior class is set to considering both primary AND secondary controls when determining whether or not to display the ellipses. 

Is this correct, or am I expected to explicitly override the behavior and set the ellipsis to be collapsed?

**Comment by JerryNixon** [comment]
In the Minimal template, if you nav to Settings, you will we have removed the ellipsis.

**Comment by JerryNixon** [comment]
Open a new issue if I misunderstood.
