### ISSUE TITLE
Hamburger Menu pane is closed when you select any page button in Wide Windows.

### ISSUE THREAD

**Issue by gustavogavancho** [Windows-XAML/Template10#717]
![captura de pantalla 39](https://cloud.githubusercontent.com/assets/15368343/13443372/c3ab86a6-dfce-11e5-909e-8013fd948557.png)
![captura de pantalla 40](https://cloud.githubusercontent.com/assets/15368343/13443383/d023d1f4-dfce-11e5-925f-8daf6fac4b56.png)

**Comment by JerryNixon** [comment]
This was reported this morning. I fixed it this afternoon. Will push it later today.
