### ISSUE TITLE
InvalidCastException within NavigationService when using NuGet package > 1.1.3

### ISSUE THREAD

**Issue by sayzenberg** [Windows-XAML/Template10#718]
I keep running into crashes involving an InvalidCastException when attempting to navigate to any page within my app. This started when I upgraded to the 1.1.5 package, but also applies to 1.1.4. The exception mentions that ShellViewModel (a view model I created for my shell) cannot be cast to an INavigable, but I'm not clear why that cast would be happening in the first place. Anyone have any idea why this might be happening?

**Comment by JerryNixon** [comment]
Your shell has a view-model?

**Comment by artfuldev** [comment]
Please make sure that your `ShellViewModel` derives from the `ViewModelBase` that comes with T10. I have a `ShellViewModel` in my solution, but this crash doesn't affect me on 1.1.4. Haven't tried with 1.1.5, so can't comment on that. But, we may need to look at some source...

**Comment by sayzenberg** [comment]
For whatever reason, this went away for me after installing 1.1.8. Going ahead and closing the issue.
