### ISSUE TITLE
Hamburger menu behaving weird in Wide View

### ISSUE THREAD

**Issue by darshanrampatel** [Windows-XAML/Template10#721]
I'm using Nuget 1.1.7, and am seeing weird behaviour when my app opens in wide mode:

![ham1](https://cloud.githubusercontent.com/assets/14162899/13456430/05f2e69e-e05b-11e5-8f0a-a4e64f8ba9e0.PNG)

If I manually resize the window to trigger medium width and then re-expand to wide width, I get the desired behaviour:

![ham2](https://cloud.githubusercontent.com/assets/14162899/13456431/05f69f5a-e05b-11e5-953f-ece81fb73656.PNG)

This only seems to happen on initial load - I thought it was that the Visual States aren't being applied for the wide view initially, but they are.

Opening the app in narrow or medium width works as intended.

**Comment by JerryNixon** [comment]
Well, that's no good. We definitely do not want that. I can't seem to repro it on my side. Could you confirm your shell looks something like this?

``` XAML
<Controls:HamburgerMenu x:Name="MyHamburgerMenu">

    <Controls:HamburgerMenu.PrimaryButtons>
        <!--  mainpage button  -->
        <Controls:HamburgerButtonInfo ClearHistory="True" PageType="views:MainPage">
            <StackPanel Orientation="Horizontal">
                <SymbolIcon Width="48" Height="48" Symbol="Home" />
                <TextBlock Margin="12,0,0,0" VerticalAlignment="Center" Text="Home" />
            </StackPanel>
        </Controls:HamburgerButtonInfo>
    </Controls:HamburgerMenu.PrimaryButtons>

    <Controls:HamburgerMenu.SecondaryButtons>
        <!--  settingspage button  -->
        <Controls:HamburgerButtonInfo x:Name="SettingsButton" PageParameter="0" PageType="views:SettingsPage">
            <Controls:HamburgerButtonInfo.NavigationTransitionInfo>
                <SuppressNavigationTransitionInfo />
            </Controls:HamburgerButtonInfo.NavigationTransitionInfo>
            <StackPanel Orientation="Horizontal">
                <SymbolIcon Width="48" Height="48" Symbol="Setting" />
                <TextBlock Margin="12,0,0,0" VerticalAlignment="Center" Text="Settings" />
            </StackPanel>
        </Controls:HamburgerButtonInfo>
    </Controls:HamburgerMenu.SecondaryButtons>

</Controls:HamburgerMenu>
```

You are not setting the Button visibility to Collapsed are you? Somewhere?

**Comment by darshanrampatel** [comment]
@JerryNixon, my Shell is:

```
        <Controls:HamburgerMenu x:Name="MyHamburgerMenu">

            <Controls:HamburgerMenu.PrimaryButtons>
                <Controls:HamburgerButtonInfo ClearHistory="False" PageType="views:MainPage">
                    <StackPanel Orientation="Horizontal">
                        <SymbolIcon Width="48" Height="48" Symbol="Home" />
                        <TextBlock Margin="12,0,0,0" VerticalAlignment="Center" Text="Home" />
                    </StackPanel>
                </Controls:HamburgerButtonInfo>
                <Controls:HamburgerButtonInfo ClearHistory="False" PageType="views:MessagesPage" Visibility="{x:Bind MessagesEnabled, Mode=OneWay, Converter={StaticResource BooleanToVisibilityConverter}}">
                    <StackPanel Orientation="Horizontal">
                        <FontIcon Width="48" Height="48" FontFamily="Segoe MDL2 Assets" Glyph="&#xE715;"/>
                        <TextBlock Margin="12,0,0,0" VerticalAlignment="Center" Text="Messages" />
                    </StackPanel>
                </Controls:HamburgerButtonInfo>
                <Controls:HamburgerButtonInfo ClearHistory="False" PageType="views:BookingsPage" Visibility="{x:Bind BookingsEnabled, Mode=OneWay, Converter={StaticResource BooleanToVisibilityConverter}}">
                    <StackPanel Orientation="Horizontal">
                        <FontIcon Width="48" Height="48" FontFamily="Segoe MDL2 Assets" Glyph="&#xE787;"/>
                        <TextBlock Margin="12,0,0,0" VerticalAlignment="Center" Text="Booking" />
                    </StackPanel>
                </Controls:HamburgerButtonInfo>
            </Controls:HamburgerMenu.PrimaryButtons>

            <Controls:HamburgerMenu.SecondaryButtons>
                <Controls:HamburgerButtonInfo PageType="views:SettingsPage">
                    <StackPanel Orientation="Horizontal">
                        <SymbolIcon Width="48" Height="48" Symbol="Setting" />
                        <TextBlock Margin="12,0,0,0" VerticalAlignment="Center" Text="Settings" />
                    </StackPanel>
                </Controls:HamburgerButtonInfo>
            </Controls:HamburgerMenu.SecondaryButtons>

        </Controls:HamburgerMenu>
```

Some of the primary buttons are initially set to Collapsed, but not the Hamburger Button.

I am setting `Views.Shell.HamburgerMenu.IsFullScreen = true;` initially, then to false on my MainPage after Login. Having tested this, the IsFullScreen is not changing the behaviour - I see the same without setting anything.

**Comment by JerryNixon** [comment]
Do you see the same behavior when you create a BRAND NEW hamburger project?

**Comment by darshanrampatel** [comment]
No, but I see the hamburger menu open on load, but then closing when I click on a page (which I thought was fixed?).

**Comment by darshanrampatel** [comment]
Testing this, I can get the desired behaviour if I don't set the IsFullScreen property.

As soon as I do set IsFullScreen=true on my first Page and then to false on my second page, I see the below initially:
![hamburg1](https://cloud.githubusercontent.com/assets/14162899/13503844/78b40604-e169-11e5-955f-9a931c4e0733.PNG)

And then the below once I resize the window to narrow then back to wide:
![hamburg2](https://cloud.githubusercontent.com/assets/14162899/13503847/79da3166-e169-11e5-95ba-0126d17b40c7.PNG)

I am trying to reproduce this on a new project as we speak.

**Comment by darshanrampatel** [comment]
Ah ha! Replicated this with a Brand New hamburger project.

Create a new project from the template, update to NuGet version 1.1.8 (from 1.1.6) and make the below changes to `MainPageViewModel.cs`:
![changes](https://cloud.githubusercontent.com/assets/14162899/13504205/60b082ce-e16b-11e5-9726-68d7b602969a.PNG)

Then run the app, starting with a Wide view. Press the Submit button and you should see the issue.

I have attached a video showing what I see.
[WindowsApp4.App 03_03_2016 06_10_54 PM.zip](https://github.com/Windows-XAML/Template10/files/157378/WindowsApp4.App.03_03_2016.06_10_54.PM.zip)

**Comment by JerryNixon** [comment]
Okay. This appears to be a bug. Thanks.

**Comment by pabermod** [comment]
Yeah, I'm getting this problem too.
I have a StartPage with the Hamburger hidden with the Views.Shell.HamburgerMenu.IsFullScreen
and then I navigate to another page where I show the Hamburger. The hamburger then is shown as @darshanrampatel pointed. When I resize the window then it works good

**Comment by toituu** [comment]
@kbronctjr I had the same exact problem in same scenario. Solved it by not setting the Shell.HamburgerMenu.IsFullScreen to true by default. Instead I hooked in to the Navigating event of NavigationService.Frame within Shell initialization, and set the IsFullScreen to true if the target page of the navigation was the page for which the menu was not to be shown. It seems to allow the menu to load properly and also show properly afterwards.

Doesn't work too well though if the screen size or orientation is changed while on page where the menu is hidden though. When the menu is shown again, it can be in kind of funky mode if the screen size has changed enough...

**Comment by pabermod** [comment]
@toituu Thanks, i'll give it a go when I can.

I tink I endend up having the same issue as you. I decided to lock the screen orientation on that specific page to avoid me a headache and also because it suited better.

**Comment by pabermod** [comment]
@toituu can you give an example code of how you achieved it? Cheers

**Comment by toituu** [comment]
I leave the IsFullScreen=False by default in Shell.xaml.

Then in Shell.xaml.cs, in the constructor I define:
            this.NavigationService.Frame.Navigating += ( s, e ) =>
            {
                if( e.SourcePageType == typeof( LoginPage ) || e.SourcePageType == typeof( AboutPage ) )
                {
                    this.MyHamburgerMenu.IsFullScreen = true;
                }
            }

For me this seemed to remove the mentioned issue (or then some other change and I just associated it with this change). I figured that this ways the menu is in fact visible when Shell is initialized, but the moment navigation is started to anywhere where the menu is not to be shown, it will be hidden.

**Comment by pabermod** [comment]
That doesn't work for me, Shell doesn't have a navigation service, at least for me.

```
        public Shell()
        {
            Instance = this;
            InitializeComponent();
        }

        public Shell(INavigationService navigationService) : this()
        {
            SetNavigationService(navigationService);

            this.MyHamburgerMenu.NavigationService.Frame.Navigating += (s, e) =>
            {
                if (e.SourcePageType == typeof(ConnectPage))
                {
                    this.MyHamburgerMenu.IsFullScreen = true;
                }
            };
        }

        public void SetNavigationService(INavigationService navigationService)
        {
            MyHamburgerMenu.NavigationService = navigationService;
        }
```

This is not working for me

**Comment by toituu** [comment]
Well, you can overload the Shell constructor and pass on the NavigationService earlier. At least that's how I do it. If that's non-option, in that case my approach will not work as such.

**Comment by pabermod** [comment]
The Shell is instantiated from the OnItnitializeAsync event of App.xaml.cs like

```
                Window.Current.Content = new ModalDialog
                {
                    DisableBackButtonWhenModal = true,
                    Content = new Views.Shell(nav),
                    ModalContent = new Views.Busy(),
                };
```

and I have

```
        public Shell(INavigationService navigationService) : this()
        {
            SetNavigationService(navigationService);
        }

        public void SetNavigationService(INavigationService navigationService)
        {
            MyHamburgerMenu.NavigationService = navigationService;

            MyHamburgerMenu.NavigationService.Frame.Navigating += (s, e) =>
            {
                if (e.SourcePageType == typeof(ConnectPage))
                {
                    this.MyHamburgerMenu.IsFullScreen = true;
                }
                else
                {
                    this.MyHamburgerMenu.IsFullScreen = false;
                }
            };
        }
```

While debugging I can see that the IsFullScreen gets set properly, but in fact the app is showing the hamburger in the ConnectPage

**Comment by SandipAhluwalia** [comment]
Hi everyone, I am not entirely sure how the problem described below that I am specifically seeing is related to this issue, but I get the following weird behavior when I add in a async start up task to OnStartAsync in a blank new Hamburger app:

```
public override async Task OnStartAsync(StartKind startKind, IActivatedEventArgs args)
        {
            // long-running startup tasks go here
            await Task.Delay(1000); // 1 secs

            NavigationService.Navigate(typeof(Views.MainPage));
            await Task.CompletedTask;
        }
```

![disortedhamburger](https://cloud.githubusercontent.com/assets/4387978/14379926/c090bf5e-fd74-11e5-92f8-1fb4d152d2a8.PNG)

Without my async startup task:

```
public override async Task OnStartAsync(StartKind startKind, IActivatedEventArgs args)
        {
            // long-running startup tasks go here

            NavigationService.Navigate(typeof(Views.MainPage));
            await Task.CompletedTask;
        }
```

![okayhamburger](https://cloud.githubusercontent.com/assets/4387978/14379995/352167a6-fd75-11e5-9095-09e0166cdc9b.PNG)

This problem is causing us a big issue in the UWP app that we are developing so @JerryNixon, is this the same problem as described above in this issue or is a different bug? Also, does anyone have any workarounds whilst we wait for a fix?

Warm regards,

Sandip.

**Comment by JerryNixon** [comment]
Fixed in 1.1.10

**Comment by Rasetech** [comment]
Hello,

I had the same issue described by SandipAhluwalia, after upgrading to 1.1.10 this got fixed but my hamburger menu looks likes this now. I manually upgraded Custom.xaml, is there anything else to do?

![snip_20160516203003](https://cloud.githubusercontent.com/assets/18215046/15299577/4c199e58-1ba5-11e6-856a-a31d8cc50dd1.png)

**Comment by SandipAhluwalia** [comment]
Hi @Rasetech, out of interest, what manual changes did you do to Custom.xaml to fix this?

**Comment by Rasetech** [comment]
Hello @SandipAhluwalia  I did nothing special just changed a few colors but the problem described in your post was gone after upgrading Template10 to 1.1.10 and the Behaviors Package to 1.1.0 (from 1.0.3). But now I have the problem described in my post, that the hamburger menu opens extended and is displaying a white are right of the toggle button.

**Comment by SandipAhluwalia** [comment]
Hi @Rasetech, ah yes, my problem went too when upgrading. Not seeing your specific issue at moment (Note: no changes done to Custom.xaml so far). However, I do see a white vertical selection bar left aligned when selecting a Hamburger menu item.

**Comment by Rasetech** [comment]
I think this white selection bar is the new design, it is expected to look like this. I will try it at home with the original Custom.xaml.

**Comment by tushargoyal1309** [comment]
@JerryNixon  How do i change the textblock color when the button is selected.Currently i am doing in the code behind but i am pretty much sure that there should be a way in xaml also for doing the same.
I have a feature to change the app theme at runtime so i have to find a way of doing this in xaml only.
Thanks.

**Comment by dg2k** [comment]
Look into the **Styles\Custom.xaml** file which is used to customize themes. You can add your custom Brushes and Styles under Light/Dark/HighContrast themes so that they would be applied as the app Theme changes (may be not 100% of the time). DynamicThemes sample project illustrates how to ensure Theme update 100% of the time based on Custom.xaml.

**Comment by tushargoyal1309** [comment]
@dg2k I have done it and the Theme change functionality is working also but i am asking in Shell.xaml inside every button info we have the textblock.I want to change the foreground of that. Since we do not have any VisualState for textblocks so how do i determine like which primary button has been selected and which is unselected. I came across events like Selected and Unselected on Primary button of Hamburger menu but the problem in code behind is it works only once. So the whole idea is how do i determine which button is selected and according to that i want to change the foreground of the textblock using xaml only.
