### ISSUE TITLE
Hamburger Button Menu disappeared at the time you run on mobile emulator

### ISSUE THREAD

**Issue by gustavogavancho** [Windows-XAML/Template10#728]
![captura de pantalla 46](https://cloud.githubusercontent.com/assets/15368343/13503482/9b0187d0-e13d-11e5-9508-a3aa3e353e4c.png)

**Comment by pabermod** [comment]
Try setting the property Views.Shell.HamburgerMenu.IsFullScreen = false;
Or: IsFullScreen="false" on the HamburgerMenu in Shell.xaml

**Comment by JerryNixon** [comment]
The IsFullScreen default is false. Isn't it? Why does that trick work?

**Comment by JerryNixon** [comment]
I want to point out that a new Ham template proj does not do this on my machine. May I ask @TavoGL, are you running Visual Studio 2015 Update 2 CTP?

**Comment by vlastimilmaca** [comment]
Hi, I can report exact same thing. Hamburger button disappears when template switches to Narrow Visual State. Tested on local machine and on device (Lumia 1020 with latest slow ring build). Visual Studio Community 2015 v14.0.24720.00 Update 1.
![hamburger missing](https://cloud.githubusercontent.com/assets/6502310/13540490/2d48a6ea-e257-11e5-96c5-1f7fab97b2c1.gif)

**Comment by gustavogavancho** [comment]
@JerryNixon. I'm running VS Community 2015 v14.0.24720.00 Update 1.

**Comment by gustavogavancho** [comment]
I'm using template 10 as an extension. I downloaded from visual studio gallery. I don't know if that can be an issue.

**Comment by gustavogavancho** [comment]
And if that it's not an issue. I think this may count as a bug. I was clicking the hamburger button and nothing happens
![animation](https://cloud.githubusercontent.com/assets/15368343/13542778/3a7e2e26-e233-11e5-8e4a-51aef3096b66.gif)

**Comment by vlastimilmaca** [comment]
@TavoGL Ok, I maybe found a way to fix missing Hamburger button.
Check References, Microsoft.Xaml.Behaviours.Uwp.Managed and try to update it (restore) back to version 1.0.3... it helped me .. but I think it is not correct way to fix this :)

**Comment by gustavogavancho** [comment]
@vlastimilmaca thanks, good tip

**Comment by vlastimilmaca** [comment]
@TavoGL Well ... it turns out that was not it ... Check References for Template 10 and make sure it is on 1.1.8 ... that was the trick that helped me (I had 1.1.6) ... I'm not sure why it is not updating Template10 automatically on build as it should. 
Edit: on Wide Visual State it is still hiding menu

**Comment by soydachi** [comment]
Hi folks! This two issues are happening on my machine too.

**Comment by JerryNixon** [comment]
Could you confirm this occurs when you create a new Hamburger proj from Template?

**Comment by JerryNixon** [comment]
Here's what I am seeing.

![hammenubutt](https://cloud.githubusercontent.com/assets/1749983/13593187/572b109a-e4b6-11e5-9321-2f5c0050abe8.gif)

**Comment by JerryNixon** [comment]
It appears perfect.

**Comment by vlastimilmaca** [comment]
@JerryNixon Indeed it appears perfect. Great work btw. 
But when I create new Hamburger project (I have latest template pack), it installs Template10 1.1.6 and then there is missing hamburger button. When I upgrade it to 1.1.8 it seems ok.
I recorded whole process ... hope gif will work .. it is quite long ... 
![missing_hamburger2](https://cloud.githubusercontent.com/assets/6502310/13599667/84be9be4-e524-11e5-9778-eb9c9bb25121.gif)

**Comment by gustavogavancho** [comment]
@JerryNixon Well I agree with @vlastimilmaca.Works perfect. I had to update

**Comment by soydachi** [comment]
Great work @vlastimilmaca! Thanks for recording the whole process. So everyone with the same issue are able to fix it.
