### ISSUE TITLE
MasterDetailsView control feature additions

### ISSUE THREAD

**Issue by artfuldev** [Windows-XAML/Template10#729]
In the sample, we have a MasterDetailsView control. In this issue, we will be tracking a wishlist of features to be added to it:
- [x] Secondary Commands
- [ ] Option to show bottom command bar for both panes, with commands and content, which will not be affected on mobile devices
- [ ] Option to hide Back Button optionally, but control Hardware Back Button behavior in Details view
- [ ] Option to hide Top CommandBars optionally in case of absence of both commands and content, especially for mobile.
- [ ] Option to add spacers to accommodate hamburger menu in top CommandBars if necessary (in narrow view and in mobile view)
- [x] Optional "no-content" content in master view
- [ ] Optional "no-content" content in details view
- [x] Details Template Selector
- [ ] In mobile and narrow views, hamburger menu button should be covered by back button in details view
- [ ] Add sample that uses Semantic Zoom in MasterView

**Comment by artfuldev** [comment]
Added Details Template Selector

**Comment by artfuldev** [comment]
Added "No Items" Template

**Comment by artfuldev** [comment]
Will submit a pull request when a bunch of todo's are ticked.

**Comment by artfuldev** [comment]
Added Secondary Commands

**Comment by artfuldev** [comment]
Added Command Bars Padding

**Comment by JerryNixon** [comment]
Anything on this?

**Comment by artfuldev** [comment]
Working. Will submit a pull request in a week or so.

**Comment by artfuldev** [comment]
@JerryNixon Sorry, a little tied up. Need to rebase with the changes to the project names and all. I'll update this in a week or so.

**Comment by mvermef** [comment]
Semantic Zoom for masterview as an option?  I am having a heck of a time getting this to play nice.

nvm figured it out...

**Comment by artfuldev** [comment]
Semantic Zoom on the MasterView is a great addition!

**Comment by artfuldev** [comment]
Need a bit more time

**Comment by JerryNixon** [comment]
You can put this as an issue on your repro clone.
