### ISSUE TITLE
Navigation default implementation improvements

### ISSUE THREAD

**Issue by callummoffat** [Windows-XAML/Template10#73]
I think that the default navigation implementation could be improved in the following ways. First, the titlebar back button functionality should be enabled on supported platforms with a simple Boolean property in the BootStrapper/NavigationService class (eg: "EnableTitleBarBackButtonOnDesktop"). This property would enable the title bar back button globally on Desktop devices only, by manipulating the nitty-gritty parts of the code. Much quicker to code for the developer, and allows them to easily pick and choose the implementation they want.

**Comment by JerryNixon** [comment]
1) this is already how it works 2) was there a second? ;)
