### ISSUE TITLE
Adding BasedOn Style on App.xaml is crashing on App() { InitializeComponent(); }

### ISSUE THREAD

**Issue by soydachi** [Windows-XAML/Template10#730]
Adapting an project to Template10, I go into inherited styles in App.xaml are crashing.

My App.xaml.cs
![captura](https://cloud.githubusercontent.com/assets/1771785/13547768/d6c35864-e2de-11e5-824f-c69792eb742e.PNG)

My App.xaml
![captura](https://cloud.githubusercontent.com/assets/1771785/13547769/f16e9b9c-e2de-11e5-9014-036b078fe9b3.PNG)

**Comment by JerryNixon** [comment]
Great question!, but it's the kind of question better served on [http://StackOverflow.com](http://StackOverflow.com). Use tag "Template10".
