### ISSUE TITLE
Ability to Edit Template of HamburgerMenu

### ISSUE THREAD

**Issue by soydachi** [Windows-XAML/Template10#731]
![captura](https://cloud.githubusercontent.com/assets/1771785/13549990/21b749d2-e313-11e5-99da-64bf812d5f27.PNG)

**Comment by JerryNixon** [comment]
Sure. Tell me why you want this, please.

**Comment by soydachi** [comment]
shure, a short description:

If I want to simply hide the title with the SplitView. Here is an illustration.

![hamburgermenutemplatefeature](https://cloud.githubusercontent.com/assets/1771785/13642965/f6685fdc-e61e-11e5-8850-c8f3c595bae3.png)

Is this now possible?

Greetings!

**Comment by rexobias** [comment]
I want to ask other thing that is more or less related (not opening a new Issue) ...

I need to change the HamburgerMenu default Icon (from the 3 bars to other Segoe MDL2 Symbol).

**Comment by JerryNixon** [comment]
Please see the Content property of the HamburgerMenu for this feature.
