### ISSUE TITLE
Can't get IActivatedEventArgs on running app

### ISSUE THREAD

**Issue by maxindahouze** [Windows-XAML/Template10#733]
I want to handle app protocol-activation even in running app.
But i can't because off this code in InternalActivatedAsync

```
            if (!_HasOnStartAsync)
            {
                _HasOnStartAsync = true;
                await OnStartAsync(StartKind.Activate, e);
            }

```

Is there a way to get the activation  parameters in the running application?

**Comment by JerryNixon** [comment]
you have identified an error that has already been resolved in the source and will be pushed to Nuget sometime this week. Thanks for your submission.

**Comment by maxindahouze** [comment]
I'm sorry. But can you show me the commit what fixes this behavior?
