### ISSUE TITLE
Hiding hamburger button doesn’t work

### ISSUE THREAD

**Issue by pekspro** [Windows-XAML/Template10#734]
I’m trying to hide the hamburger button and the pane like this:

```
    <Controls:HamburgerMenu x:Name="MyHamburgerMenu" HamburgerButtonVisibility="Collapsed" PaneWidth="0">
```

I’ve done this in the current source in the Hamburger template. When I do this the pane is still visible if the window is large enough. The hamburger button is hidden but the layout isn’t adopting to this. There is just a white box where the hamburger button used to be.

![hamburgerror1](https://cloud.githubusercontent.com/assets/3163293/13553485/be7831c8-e38b-11e5-9fb3-d7536e02ae67.png)

![hamburgererror2](https://cloud.githubusercontent.com/assets/3163293/13553486/bfebe31a-e38b-11e5-83fb-4a444337233c.png)

**Comment by pabermod** [comment]
Do you want to hide just the button or the whole hamburger?

If it is the whole hamburger:
Try setting the property Views.Shell.HamburgerMenu.IsFullScreen = true;
Or: IsFullScreen="true" on the HamburgerMenu in Shell.xaml

**Comment by pekspro** [comment]
I tried `IsFullScreen=”True”` but it didn’t have any impact in either my application or the Hamburger template project.

**Comment by JerryNixon** [comment]
Hi. Your PageHeader doesn't know you have hidden the HamburgerMenu. Those two controls are not connected in any way. So when you hide the HamMenu, you must tell the PageHeader. One way is to set the VisualStateMinWidth=-1 which will disable this behavior. That's prob what I would do.
