### ISSUE TITLE
HamburgerMenu & AppBar

### ISSUE THREAD

**Issue by QuentinSc** [Windows-XAML/Template10#736]
Hello,

Maybe it is my fault but I ask anyway.
When I use an AppBar in my App (Hamburger Template 10), the AppBar hides the HamburgerMenu.

Without
![capture2](https://cloud.githubusercontent.com/assets/16439299/13554930/7a31f818-e3b4-11e5-9cc6-2b9c97af5ba0.PNG)
With
![capture](https://cloud.githubusercontent.com/assets/16439299/13554929/7a304f72-e3b4-11e5-935b-925aa6da27e3.PNG)

Me or bug?

Thank you!

**Comment by JerryNixon** [comment]
Great question. Look at the BottomAppBar sample on GitHub that demonstrates it.
