### ISSUE TITLE
Show a Modal Dialog in OnNavigatingFromAsync

### ISSUE THREAD

**Issue by robertmuehsig** [Windows-XAML/Template10#737]
I struggle to find a answer and I'm not sure if this is Template10s fault or I'm just to stupid for async/await-ing stuff (\* which I am ;)).

My goal is to ask the user something like: "Do you really want to navigate to page XXX? Yes/No".

I tried something like this:

```
    public override async Task OnNavigatingFromAsync(NavigatingEventArgs args)
    {
        args.Cancel = true;

        ContentDialog dlg = new ContentDialog()
        {
            Title = "Bad",
            Content = "no no no!",
            PrimaryButtonText = "OK",
            SecondaryButtonText = "NO"
        };
        var test = await dlg.ShowAsync();

        if (test == ContentDialogResult.Primary)
        {
            args.Cancel = false;
        }

        await Task.Yield();
    }
```

I guess the method should not be "async", but without the async, how can I get access to the result of dlg.ShowAsync()?

**Comment by AmitBhatnagar24** [comment]
I asked this here and on stackoverflow (you're using my code example :). Check out the [StackOverflow question ](http://stackoverflow.com/questions/35561107/how-to-show-a-modal-dialog-and-cancel-navigation-in-onnavigatingfromasync)with the answer

**Comment by ivesely** [comment]
The problem here is that FacadeNavigatedEventHandler returns void and this causes that async methods are not awaited.

**Comment by robertmuehsig** [comment]
Yeah - I saw that answer, but how can I get the "result" of the dialog? With this code the dialog will stop the navigation, but will do nothing when I click the button:

```
    public override Task OnNavigatingFromAsync(NavigatingEventArgs args)
    {
        args.Cancel = true;

        ContentDialog dlg = new ContentDialog()
        {
            Title = "Bad",
            Content = "no no no!",
            PrimaryButtonText = "OK",
            SecondaryButtonText = "NO"
        };
        dlg.ShowAsync();

        return Task.CompletedTask;
    }
```

When I do something like (and mark the method as async):

```
var result = await dlg.ShowAsync() 
```

... the navigation will not be stopped.

**Comment by JerryNixon** [comment]
Guys, this is a bug. Let me fix it.

**Comment by EdAlexander** [comment]
not sure if this is related... but when I return from ContentDialog and the method that opened it completes I get a "Catastrophic Failure" with no stack trace...  try catch does not trap the error...

```
        private async void EnterExpenseButton_Tapped(object sender, Windows.UI.Xaml.Input.TappedRoutedEventArgs e)
        {
            try
            {
                var dialog = new NewExpenseEntryEdit(((Button)sender).DataContext as Account);
                dialog.DataContext = this.DataContext;
                var result = await dialog.ShowAsync();

                if (result == ContentDialogResult.Primary)
                {
                    ViewModel.RaisePropertyChanged("Entries");
                    this.Bindings.Update();
                    dialog.Hide();
                }
                else if (result == ContentDialogResult.Secondary) {
                    dialog.Hide();
                }
            }
            catch(Exception ex)
            {
                System.Diagnostics.Debug.WriteLine(ex.Message);
            }
        }

```

**Comment by JerryNixon** [comment]
Async in OnNavigatingFromAsync is not possible and requires you to be synchronous, for now. Fixing this will take a lot of work and you won't see a fix for a while.

**Comment by robertmuehsig** [comment]
Is there a example anywhere? I don't mind if this is async or not, because all I wanted is to display a warning like "unfinished work, are you sure you want to move on?"

**Comment by darenm** [comment]
Here's a sample I am using:

``` csharp

        public override async Task OnNavigatedToAsync(object parameter, NavigationMode mode,
            IDictionary<string, object> suspensionState)
        {
            NavigationService.FrameFacade.BackRequested += FrameFacadeBackRequested;
...
        }

        public override async Task OnNavigatingFromAsync(NavigatingEventArgs args)
        {
            NavigationService.FrameFacade.BackRequested -= FrameFacadeBackRequested;
        }

        private async void FrameFacadeBackRequested(object sender, HandledEventArgs e)
        {
            e.Handled = IsDirty;
            if (IsDirty)
            {
                var result =
                    await ContentDialogHelper.CreateOkCancelDialog("Navigating now will lose your changes - continue?")
                        .SafeShowAsync();
                if (result == ContentDialogResult.Primary)
                {
                    if (NavigationService.CanGoBack)
                    {
                        NavigationService.GoBack();
                    }
                }
            }
        }
```

**Comment by kfchengkf** [comment]
I used the sample code from darenm and was able to achieve the desire result.
However there is an issue that appear when deployed on a windows phone (not on desktop)
When the apps is suspended and then resumed and the hardware back button pressed,
the yes/no dialog show up, but at the same time, the apps quit (not sure if crashed or not).
The yes / no button was not pressed yet.

The dialog that I am using is a MessageDialog.

I am using version 1.1.11 of T10.

Any idea ?
