### ISSUE TITLE
Extend IStoreConverter for SettingsService for custom types

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [Windows-XAML/Template10#739]
Hi, I have a suggestion to make IStoreConverter be able to convert not only to/from strings, but from additional possible Types, like ApplicationDataCompositeValue. 

Sometimes I need to put only a few values from real object. 
Example: I have a number of User types, but no matter which type I use, I only need Id, IconUrl, and Name in settings. Would be nice to introduce custom converter to  ApplicationDataCompositeValue and save it directly to Settings without additional to string conversion.
Does it make sense?

PS
I understand that making it not only "string" values may introduce issues with saving complex types that are not savable to store..

**Comment by JerryNixon** [comment]
I look forward to your Pull Request.

**Comment by artfuldev** [comment]
Good one! :+1:

**Comment by JerryNixon** [comment]
No noise, for too long
