### ISSUE TITLE
PageHeader improvements

### ISSUE THREAD

**Issue by callummoffat** [Windows-XAML/Template10#74]
I really like Template10, but I did have some ideas for improving PageHeader, which is one of my favorite controls. PageHeader should use the system accent color by default, to provide a level of consistency for a default UI. The PageHeader back button should, by default, be enabled only when the title bar back button is disabled.

**Comment by h82258652** [comment]
I agree with you. PageHeader and other like AppBar should use accent color.

**Comment by JerryNixon** [comment]
The default color should be the system color? That's not a bad idea. The default color for the Hamburger should do the same, right? Accent colors don't imply the contrast color for the foreground, but we can assume white in most cases. If you are willing to demonstrate it, branch the library and demonstrate.

**Comment by callummoffat** [comment]
You can test the change in pull request #80 . It looks good! I also added some enhancements to the title bar to add consistency. What can I say? I'm a perfectionist.

**Comment by JerryNixon** [comment]
Thanks. Keep it up.
