### ISSUE TITLE
Issues with selecting and unselecting a hamburger button

### ISSUE THREAD

**Issue by sayzenberg** [Windows-XAML/Template10#742]
I have a button in my hamburger menu that points to an initial page, which then navigates to a different page for further actions. The page it navigates to isn't in the menu, so of course the original button gets unchecked. I hooked into the Unselected event handler to manually select, and then check, the button, but if my app launches directly into that button's page, the button will still get unchecked, even though the Unselected event fires.

If I use the menu to navigate to another page, and then come back to the original page, then it works. The button will remain selected even after the navigation happens. However, at that point, navigating via the menu no longer unselects the button, the event never fires, and the button stays checked.

To summarize:
1. App launches to Page 1, button is checked.
2. Page 1 navigates to Page 1.A, Unselected event handled, button still unchecked
3. Navigate to Page 2 via menu, Page 2 button is checked, Page 1 button is unchecked.
4. Navigate to Page 1 via menu, button is checked.
5. Page 1 navigates to Page 1.A, Unselected event handled, button remains checked
6. Navigate to Page 2 via menu, both Page 1 and Page 2 buttons are checked.

Here's the (simple) code I'm using in the shell code-behind for this.

```
private void Button1_Unchecked(object sender, RoutedEventArgs e)
{
     if (Menu.Selected == null) // this is the case when Page 1.A is active because it has no button
     {
          Menu.Selected = Button1;
          Menu.Selected.IsChecked = true;
     }
}
```

Any suggestions for what I can do here?

**Comment by marcinmarkiewicz** [comment]
Maybe it isn't beautifull solution but try create invisible buton in the menu witch will be hooked to page 1.A...

**Comment by JerryNixon** [comment]
I do not really understand your question. However, it sounds like you want to check a button even though another button is automatically checked. The menu will automatically check buttons when it finds a match, even overriding your Selection setting. The only way to unwind that is to remove the PageType value from the button and store it in a variable, then re-set it. 

Maybe you could re-state your question if I missed it.
