### ISSUE TITLE
Navigation within sub frame

### ISSUE THREAD

**Issue by JurajPupak** [Windows-XAML/Template10#748]
I just want to ask, if you support navigation within subframe. What I want to say: Normally we have RootFrame and some pages in it. But let's say I have another Frame, in which I navigate to other subpages. Can your NavigationService work with other frames? I want to use it in ViewModel - so no this way: MyCustomFrame.Navigate(...). It would violate MVVM.

**Comment by JerryNixon** [comment]
Yes, you can nav in a sub frame, but you cannot nav in multiple frames handle it custom.
