### ISSUE TITLE
Use Cortana to call a running app does not trigger OnStartAsync, OnInitializeAsync, OnPrelaunchAsync or OnResuming

### ISSUE THREAD

**Issue by brisebois** [Windows-XAML/Template10#749]
When the app is already running and I use Cortana to call into the app, I am unable to find the place where I can intercept the IActivatedEventArgs I looked at the OnStartAsync, OnInitializeAsync, OnPrelaunchAsync, OnResuming. Nothing seems to get triggered. 

How can I react to this event?

**Comment by darenm** [comment]
How are you using Cortana? If you are showing multiple results in Cortana and the user is selecting one from many, then the app is protocol activated but you must also add the Personal Assistant capability as well, otherwise Cortana does not activate or launch your app.

**Comment by brisebois** [comment]
I am currently using with the VoiceCommandActivatedEventArgs. I did not activate the Personal Assistant since I thought that was only for Cortana inside the app

**Comment by darenm** [comment]
OK - have you looked at the cortana sample?

https://github.com/Windows-XAML/Template10/tree/master/Samples/Cortana

**Comment by brisebois** [comment]
Yes, this works when the application is shutdown before the ask is made to Cortana.

**Comment by darenm** [comment]
I don't quite follow the your last comment. The app has to be run once to install the voice commands (as I am sure you know). Are you saying that the sample does not support responding to a voicecommand if it is running, only when it is not running? (as a general rule - please be as expansive as possible with your comments, say what you did, what errors, etc.)

**Comment by brisebois** [comment]
Sure, the app runs one to install the 
`var storageFile =
                await StorageFile.GetFileFromApplicationUriAsync(new Uri("ms-appx:///Assets/AskAlexCommandSet.xml"));
            await VoiceCommandDefinitionManager.InstallCommandDefinitionsFromStorageFileAsync(storageFile);
`
Then I close the app and use Cortana to launch and react to the VoiceCommandActivatedEventArgs

This first scenario works. If the Application is already running and I use Cortana to issue the same VoiceCommandActivatedEventArgs the app comes into focus but nothing else is triggered.

**Comment by JerryNixon** [comment]
What version of T10 are you running?

**Comment by brisebois** [comment]
Currently on 1.1.8

**Comment by brisebois** [comment]
I'm seeing the same kind of behavior if, the app is already running and that I share to it from a browser, no event is sent through the OnStartAsync.

**Comment by JerryNixon** [comment]
Would you please use the code in GitHub and test? I believe this was resolved.

**Comment by brisebois** [comment]
Using the code from the repo, I found in the BootStrapper under InternalActivatedAsync that line 216 makes sur that we have an activate or launch mode. the previous state for this call is running. This results _HasOnStartAsync being True because it is not reset and causes OnStartAsync to be bypassed.

**Comment by brisebois** [comment]
Thought, should Template 10 automatically hide the main Window like the way Mail app behaves when we activate the share contract, then once the share is complete show the main window? This would solve both windows navigating to the page, that handles each IActivatedEventArgs Kind. It would also help with managing multiple windows and static references/instances.

**Comment by toituu** [comment]
I have run into this same issue. Fixed it by removing the  'if(!_HasOnStartAsync)' check on the mentioned line 216. Haven't noticed any major side effect with the change and Cortana commands now work fine.

**Comment by brisebois** [comment]
I added the condition when 'running' is the previous state and found that if the app is running, and that the share contract is triggered, the app shows up un the side windows. When the share is set to completed, both windows close. I have to figure out why.

**Comment by brisebois** [comment]
I wonder if there's a way to get rid of statics by way of using constructor injection. This would make sure that multiple windows have independent states and lifecycles. The service locator pattern/ singleton pattern works great when we don't have to worry about this type of scenario.

**Comment by JerryNixon** [comment]
Resolved
