### ISSUE TITLE
Can't set HamburgerForeground

### ISSUE THREAD

**Issue by DanTheManSWE** [Windows-XAML/Template10#750]
I'm trying to set HamburgerForeground in the HamburgerMenu tag, it works fine in DesignMode, but it's always white when running the app. 

Edit:
I had some time to investigate a bit further, and the issue I'm experiencing is related to setting Light or Dark Theme. If I set HamburgerForeground in the HamburgerMenu it works fine until changing theme. Both Dark and Light themes have White as default color for HamburgerForground, evertime you switch theme it will reset to white.

**Comment by kdowswell** [comment]
I've set this in an existing app I have in the store. 

I set it like this:

`<Controls:HamburgerMenu x:Name="MyHamburgerMenu"
                                NavAreaBackground="{ThemeResource SystemControlBackgroundChromeMediumLowBrush}" 
                                NavButtonCheckedBackground="{ThemeResource SystemControlHighlightAltListAccentLowBrush}" 
                                HamburgerBackground="{ThemeResource AppBarBackgroundThemeBrush}" 
                                HamburgerForeground="#FFCDCDCD"
                                  >`

Maybe you aren't using a valid color code? Try using the property window to set the color using the brush section.

**Comment by DanTheManSWE** [comment]
Hmm, I just created a new project based on the Hamburger Template, and it works fine. 
So, must be something related to my app.

**Comment by DanTheManSWE** [comment]
Ok, 
I had some time to investigate a bit further, and the issue I'm experiencing is related to setting Light or Dark Theme. If I set HamburgerForeground in the HamburgerMenu it works fine until changing theme. Both Dark and Light themes have White as default color for HamburgerForground, evertime you switch theme it will reset to white.

**Comment by JerryNixon** [comment]
This is a known issue. Sorry. Choose different colors. :(
