### ISSUE TITLE
Samples/PageKeys crash without debugger attached

### ISSUE THREAD

**Issue by crazycreak** [Windows-XAML/Template10#753]
Hey, i found the following bug: (using current master #b6c9e73 or current nuget 1.1.8)
1. deploy/build "PageKeys" project
2. run on mobile emulator (for example 10586.0 720p 5 inch 1GB)
3. app starts and navigate to main page (ok)
4. click back and open the app from the menu again **(ok -> working!)**
5. stop the debugger
6. start the app on the emulator again (without the debugger attached)
7. app starts and navigate to main page (ok)
8. click back and open the app from the menu again **(not ok -> not working! app crash)**

the bug only happens when you use "PageKeys" for navigation and only when no debugger attached

**Comment by crazycreak** [comment]
maybe it's the same problem as described in #744?

**Comment by bc3tech** [comment]
@crazycreak do you have any analytics/logging you can attach to this to verify if it is indeed linked to 744? Even putting a `File.WriteText` call in to `App_UnhandledException` then reading that next launch w/ the debugger and pasting the content here would be good.

I'd love to know if it's the same exception type and the same method causing the problem. Though in 744 it happens on launch (doesn't even navigate to the first page) as that exception is occurring in `InternalLaunchAsync` which wouldn't be getting hit after the app's done initial nav (as in your case).

Still, getting us a log/stack trace would be tremendously helpful.

**Comment by crazycreak** [comment]
the exeption occures befor "NavigationService.Navigate" is called in "OnStartAsync" (i comment out the line)

Exception.Message is "An item with the same key has already been added."

when i check with "keys.ContainsKey(Pages.MainPage)" if the key exists before i add it, the app doesn't crash, for example:

``` c#
        public override Task OnInitializeAsync(IActivatedEventArgs args)
        {
            var keys = PageKeys<Pages>();
            if(!keys.ContainsKey(Pages.MainPage)) keys.Add(Pages.MainPage, typeof(Views.MainPage));
            return Task.CompletedTask;
        }
```

is this a bug in the library or a failure in the sample and i should check every key before i add it in "OnInitializeAsync"?

**Comment by bc3tech** [comment]
What's the reason for adding something to `PageKeys` in On Init? I'm not aware of such a requirement of the framework.....

The good/bad news is that this definitely separates it from the issue in 744.

**Comment by crazycreak** [comment]
it's demonstratat in Samples/PageKeys, to use enum for navigation instead of type

**Comment by JerryNixon** [comment]
I'm very sorry @crazycreak , I simply cannot repro this. I've tried Release mode, local, emulator, debug, deployed. The app loads fine in every scenario. The app never crashes.

**Comment by crazycreak** [comment]
@JerryNixon here a short video/gif, hope this helps

![pagekeys](https://cloud.githubusercontent.com/assets/16294164/13884602/f83089fe-ed2e-11e5-93c5-8ee584c6bbce.gif)

**Comment by JerryNixon** [comment]
Okay, now I see it.

**Comment by JerryNixon** [comment]
I updated the sample with the fix. You were right.
