### ISSUE TITLE
Why does changing the light/dark theme, set the HamburgerMenu.IsOpen to true?

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#754]
I thought I did something wrong in my code as changing the light/dark theme will always open a closed menu pane (in DisplayMode = CompactInline). Now I've tried with the Hamburger Template 10 version 1.15 (as well as Hamburger project in the latest merge) and I notice the same thing, so it is not with my code.

To reproduce (on desktop):
- Run the Hamburger Template 10 extension or the project in the source code
- Tap on the HamburgerMenu button to close the menu pane.
- Tap on settings
- Tap on the 'Color theme' toggle switch.

You'll notice that while the theme is changing, the closed menu pane also opens. But, why?

I have checked that any one of the following code, on its own, will cause this:

`(Window.Current.Content as FrameworkElement).RequestedTheme = theme.ToElementTheme();  // ApplicationTheme theme`

`Instance.RequestedTheme = theme.ToElementTheme();      // ApplicationTheme theme`

`Views.Shell.HamburgerMenu.RefreshStyles(theme);            // ApplicationTheme theme`

Is this a bug? I cannot figure out at what point theme changing event interacts with HamburgerMenu visual state or IsOpen property. Explanation as to why this happens is kindly appreciated.

**Comment by JerryNixon** [comment]
no kidding when I ask this. Who cares?
