### ISSUE TITLE
Template10 runtime localization

### ISSUE THREAD

**Issue by marcinmarkiewicz** [Windows-XAML/Template10#759]
I set polish language as default for my app using Template10, but in runtime there is problem with polish national characters. Problem exists only in runtime - designer is OK.

**Comment by Opiumtm** [comment]
@marcinmarkiewicz Just check XAML file encoding. It may not UTF-8, but ANSI instead. It is not T10 problem, it is Visual Studio 2015 Git client implementation issue. To fix this problem, change encoding of XAML file to unicode and your problems will gone away. Sometimes Visual Studio 2015 create new files with ANSI encoding and it should be checked to avoid errors. If XAML file created as ANSI, you probably will face non-english character problems. I already got this problems with russian language and fixed it by change XAML file encoding to unicode.

**Comment by JerryNixon** [comment]
@Opiumtm would you add this guidance to the wiki? We get this question a lot.
