### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by JurajPupak** [Windows-XAML/Template10#760]
Do you plan to extend your documentation? Now I miss explanations of some functions, or descriptions for functions. Now I have to study the implementation.

**Comment by JerryNixon** [comment]
I will give you two options for this. First, tell me what method needs to be described and we will add them one at a time. Second, the Wiki is open, you can contribute, too. (or both options).

**Comment by JurajPupak** [comment]
So, I needed to create navigation service for my frame. Template10 provides NavigationServiceFactory, but I didn't know, what parameters should I have used, unless I checked the definition of method in source code. But now I know :)

**Comment by Salihe** [comment]
Hi, I have started working on a project by using the Hamburger template. It looks great but I am finding it hard to understand how to add any of more complex data to it. I am a beginner with the techniques that are used in the template, and would also appreciate some additional documentation. 

It would be fantastic if there was an example of an app that is based on Template 10 and works with different types of the user data locally and also syncs the data with Azure. That would be a dream.

**Comment by disklosr** [comment]
For my case, i need to understand how i can intergrate my IoC of choice with template 10 and inject dependencies in my viewmodels during navigation. The documentation does't help explaining how this is done.

**Comment by callummoffat** [comment]
Try look at Petrolhead. It's a full, open-source app; the UWP client is based on Template10. You can take a look here: https://github.com/SupernovaApps/Petrolhead

I develop it. :-)

**Comment by JerryNixon** [comment]
Have you reviewed the samples?

**Comment by kdowswell** [comment]
Hey @JerryNixon I was listening to dotnetrocks when Seth Juarez talking about his library Numl. He discussed using http://dotnet.github.io/docfx/index.html for his documentation. It seems pretty cool! I tried this out on some sample code last night and it is pretty straight forward. Is this something you would want help with? Let me know!

**Comment by JerryNixon** [comment]
@JurajPupak you did see the wiki? https://github.com/Windows-XAML/Template10/wiki/Docs-%7C-Bootstrapper#properties-methods-and-overrides

**Comment by JerryNixon** [comment]
@kdowswell you don't like the Wiki?

**Comment by JerryNixon** [comment]
@disklosr Template 10 is not an IoT framework.

**Comment by kdowswell** [comment]
@JerryNixon Hey, yes I do, actually! I just hadn't seen all of the internal pages until now. Nice work on those!

**Comment by disklosr** [comment]
@JerryNixon that link was really helpful. But since it's not referenced from the wiki's main page, I think a lot of people like me will miss it thinking that all documentation can be accessed from wiki's main page.

**Comment by disklosr** [comment]
@JerryNixon who said IoT? I said IoC not IoT.

**Comment by darenm** [comment]
@disklosr I added a list of links to the other documentation on the main page to aid discoverability.

**Comment by gustavogavancho** [comment]
well some time ago I did the same question, and to be honest I'm new at this so it took me a while to know how to work with this template, perhaps more info in the wiki could be used.

**Comment by AmitBhatnagar24** [comment]
@disklosr I use Unity for my IOC and MVVM Light. I have zero issues and it was pretty simple to set up.

a: I created my own NavagableViewModelBase that derrives from MVVMLight's ViewModelBase and implements INavigable

b) I register my Container in app.xaml.cs and adjust my ViewModelLocator to pull from the container as normal.

Then you are done. T10 won't attempt to set a page's DataContext if one already exists.

**Comment by JurajPupak** [comment]
Let me ask you something. Template10 is very helpful, but is good for UWP beginners? Template10 hides everything, whole logic. Template10 does everything for you - navigation, different services, validators, converters.

**Comment by darenm** [comment]
@JurajPupak To be honest, that's kind of the point. Why should developers have to worry about the details of navigation, state persistence, etc.? It doesn't seem unreasonable that there should be services that take care of the common scenarios for the developer, so the developer can focus on building an app that achieves specific functionality, as opposed to reinventing the plumbing for their app to run. Template10 exists to accelerate the process of creating a working application. Most of the problems that Template10 solves have to be solved in some form in non-trivial apps. 

Of course, there's going to be a learning curve, especially if the developer wishes to add features such as IoC, etc. - but the assumption made there is if a developer is sufficiently experienced to desire IoC, Service Injection, etc. then the T10 codebase wouldn't be too intimidating. Equally, once someone has learnt how to do something, the Wiki is accessible to anyone and so the feature can be documented (everyone wants to add features - few want to document them...)
