### ISSUE TITLE
Hiting Shift+Alt+A brings message dialog

### ISSUE THREAD

**Issue by konradkalemba** [Windows-XAML/Template10#763]
Title says it. It shows also on mobile, when trying write 'Ą'.
http://i.imgur.com/pVTScga.png

**Comment by JerryNixon** [comment]
Why disturbing? I'm open to new verbiage.

**Comment by konradkalemba** [comment]
Sorry, I am not native English speaker and I couldn't find any right word to describe it. I meant that it can be annoying when trying to write big letter 'Ą' (which shortcut is Shift+Alt+A) in TextBox.

**Comment by darenm** [comment]
@konradkalemba so you keyboard requires you to hold SHIFT+ALT+A to enter 'A'? Most keyboards require just SHIFT+A for 'A' - I am curious what is the language and keyboard layout you are using?

**Comment by konradkalemba** [comment]
@darenm In Polish language there is letter [ą](https://en.wikipedia.org/wiki/%C4%84), which requires to hit Shift+A (so Shift+Alt+A for uppercase). I'm using [Polish (Programmers)](https://www.microsoft.com/resources/msdn/goglobal/keyboards/kbdpl1.html) keyboard layout.

**Comment by JerryNixon** [comment]
I will change this in the next Nuget package. Sorry, I didn't realize that combination was important.

**Comment by konradkalemba** [comment]
No problem. Thank you. :+1:
