### ISSUE TITLE
Add tooltip to NavMenu Item for hover in collapsed state

### ISSUE THREAD

**Issue by darenm** [Windows-XAML/Template10#766]
The News app and others show a tooltip when hovering over a nav menu item. Adding a tooltip to the content in the existing implementation does not show (probably blocked by mouse over states in the control). Needs to be added to HamburgerButtonInfo as a property and added to the template.

**Comment by dg2k** [comment]
@darenm - the property **ToolTipService.ToolTip="tooltip"** can be  readily used with HamburgerButtonInfo (it works fine for me just adding the property). The only caveat is that it should show only when **HamburgerMenu.IsOpen** is **false** (pane closed), else the tooltip would be redundant with the menu text visible. As important, it should, if possible, also show for disabled menu items which by default is suppressed if menu item is disabled. The design is therefore how to temper **ToolTipService.ToolTip="tooltip"**, I think. Saying that there may be a shortcut?

**Comment by darenm** [comment]
Interesting - I must have added it in the wrong place in my haste. Regarding whether it should be shown when the menu is open - right now the 1st part apps show the tooltip regardless of open or closed, but I certainly agree it is redundant in the expanded state if the tooltip displays the same information as the label..

**Comment by darenm** [comment]
Yup - sure enough - adding to the content doesn't work (I was trying to add it just to the icon), but adding it to the HamburgerButtonInfo works like a charm. I'll close this then as fundamentally we're aiming for 1st party app alignment.
