### ISSUE TITLE
Discussion: Is it necessary to add some helper class?

### ISSUE THREAD

**Issue by h82258652** [Windows-XAML/Template10#77]
Just like:
ScreenResolutionHelper https://raw.githubusercontent.com/h82258652/SoftwareKobo.UniversalToolkit3/master/SoftwareKobo.UniversalToolkit/SoftwareKobo.UniversalToolkit/Utils/ScreenResolution.cs
T4 for resw
https://raw.githubusercontent.com/h82258652/SoftwareKobo.UniversalToolkit3/master/SoftwareKobo.UniversalToolkit/SoftwareKobo.UniversalToolkit.T4/LocalizedStrings.tt

I don't know what's the goal of Template10. A small library just like handle navigation, or a big library include all things about UWP developing.
@JerryNixon 
At last, sorry for my terrible English.

**Comment by JerryNixon** [comment]
These are great additions. I will add the resolution helper in the Utils namespace. As for the T4. This would not be appropriate to ship with T10, but it's very valuable and I think we should include it in a dedicated sample. Building a sample project based on Blank demonstrating the T4 accessing string resources like Silverlight would be a welcome pull request.

**Comment by h82258652** [comment]
Thanks for response.
How about also add a unix timestamp to DateTime converter?
And change Mdl2.cs static method to const string.

**Comment by JerryNixon** [comment]
I am not sure those methods are accurate.

**Comment by JerryNixon** [comment]
Review this for me: http://dwcares.com/actual-size/

**Comment by h82258652** [comment]
I got the ScreenResolution code from a Chinese forum.
I test it in desktop and mobile emulator, both works.
Maybe need more test.

**Comment by JerryNixon** [comment]
If you test it and trust it, submit it again. Are you testing the physical resolution of your monitor or the effective resolution of your device?

**Comment by vmahadev** [comment]
Desperately looking forward to it...i did my research I was almost there to figure it  out. I might have documented in source let me check and revert back on it. 

My app which uses Template10 need it. I did customize Template10 library for my app(the early release) I guess June or July...the app basic edition is live(windows store)

The app titled Visual Acuity Pro ...in beta testing...

-----Original Message-----

**Comment by vmahadev** [comment]
Hi Jerry/Andy

Add me as a member I will start contributing in my free time.

First one to use Template 10. I have customized it for my requirement...i did fork but got busy with a client xaml app.

Thanks

-----Original Message-----

**Comment by h82258652** [comment]
Screen Resolution Test Result：
Desktop（device Win10 10240）
Correct Value：1920x1080
Test Result：1920x1080

Mobile（emulator W10M 10240 WXGA 4.5 inch）
Correct Value：768x1280
Test Result：768x1280

Mobile（emulator W10M 10240 WVGA 4 inch）
Correct Value：480x800
Test Result：480x854
PS：This seems wrong. But I think the reason is the virtual navigation bar. So I think it is still useable.

---

Get screen resolution is very necessary for a wallpaper app. I hope Jerry can add it into Template10 or find a better way to get the screen resolution.
By the way, I don't have a IoT device. So I don't know if it works on the IoT device.

**Comment by h82258652** [comment]
And I'm coding some classes to access the Package.appxmanifest file when the application is running. But not finished now. Maybe this idea is useful for Template10.
https://github.com/h82258652/SoftwareKobo.UniversalToolkit3/blob/master/SoftwareKobo.UniversalToolkit/SoftwareKobo.UniversalToolkit/Utils/AppxManifest/PackageManifest.cs
https://github.com/h82258652/SoftwareKobo.UniversalToolkit3/blob/master/SoftwareKobo.UniversalToolkit/SoftwareKobo.UniversalToolkit/Extensions/PackageExtensions.cs

**Comment by JerryNixon** [comment]
We had a ManifestService in the Template10.Services early on and I would love one there again. If you are doing it so it's all strongly typed, you can submit it. Make it defensive, man!
