### ISSUE TITLE
Need Continuous Integration / Build with unit tests

### ISSUE THREAD

**Issue by artfuldev** [Windows-XAML/Template10#770]
I just pulled latest and my T10 repo doesn't build anymore. Maybe there's some problem with my fork, but a github hook for continuous integration / building / testing would help. Anyone seconding me on this?

**Comment by rcbevans** [comment]
+1, several of the samples and even the project templates don't seem to build or run

**Comment by JerryNixon** [comment]
@artfuldev and @o0rebelious0o, I look forward to your Pull Requests on this.

**Comment by artfuldev** [comment]
@JerryNixon This needs some work by the repo owner. You need to get to settings and add AppVeyor Webhook. (https://github.com/integrations/appveyor)

I think they have UWP app CI. I'll look into this a bit more but just adding a hook won't create any problems for now. We need to create an appveyor.yml file to configure the builds to get things going. UWP being a new platform we may face initial hiccups but CI is well worth it, we can know if pull requests will fail to build even before attempting to merge. I would humbly request you to reopen this issue till this is done.
