### ISSUE TITLE
Shift+Alt+A message dialog crashing app

### ISSUE THREAD

**Issue by angusbreno** [Windows-XAML/Template10#771]
Shift+Alt+A brings message dialog. Ok. 

With the dialog open, press Shift+Alt+A again. App crash.

**Comment by JerryNixon** [comment]
Hmm. What language?

**Comment by angusbreno** [comment]
en-US

But it's related to language (i think). Unhandled Exception is:

"An asynchronous operation was not started properly.

Only a single ContentDialog can be opened at a time."

**Comment by rcbevans** [comment]
I'm assuming this is the same issue as you see in the KeyboardService, where hitting Shift+Ctrl+Alt+F12 with a ContentDialog already showing will crash the app with a COMException thrown?  I've submitted a full request catching the exception and logging it #778

**Comment by angusbreno** [comment]
Yes.

**Comment by JerryNixon** [comment]
@o0rebelious0o are you saying Shift+Ctrl+Alt+F12 causes a problem?

**Comment by angusbreno** [comment]
@JerryNixon It's not related to Shift+Ctrl+Alt+F12. The problem is when there is a ContentDialog  opened and we try to open another/again.

**Comment by rcbevans** [comment]
@JerryNixon that combo did, but as @angusbreno says, the exception is when you try and show a platform dialog when one is already showing.  #778 catches the exception for the shift+alt+ctrl+f12 case, but I didn't look for other cases where this might be thrown in the library.  I'll go take another look and update the PR accordingly
