### ISSUE TITLE
Hamburger menu layout distorted when orientation is changed while menu is hidden

### ISSUE THREAD

**Issue by toituu** [Windows-XAML/Template10#776]
Consider application that has specific page without the menu used for landing. When user navigates away from this page the hamburger menu is shown. Now, if user navigates back to the landing page and orientation switch occurs, the menu layout is distorted when user again navigates back to page where the menu is shown.

So in summary:
1. Show hamburger menu
2. Hide menu by setting IsFullScreen to True (happens when user navigates to specific page in this scenario)
3. Change orientation (with mobile device, probably valid if changing the screen orientation on desktop too)
4. Show menu (again, happens due to user navigation in this scenario)
5. Observe the hamburger menu. Depending on if you switch from landscape to portrait orientation, or vice versa, and whether the navigation in the steps is initialized via the hamburger menu or not, the menu is shown distorted in different ways. In best case scenario, the menu is still very easily shown in wrong display mode.

**Comment by JerryNixon** [comment]
Thanks for reporting this.

**Comment by schuettecarsten** [comment]
I think this happens because HamburgerMenu splitview is removed from visual tree in Fullscreen mode and does not see the orientation change.

**Comment by angusbreno** [comment]
@carstenschuette @toituu I've tested my changes for this problem and worked. Take a look there and see is working so i can make a PR.

**Comment by JerryNixon** [comment]
I believe this is resolved in 1.1.10
