### ISSUE TITLE
Perhaps this counts as an issue. When you click multiple times the page buttons sooner or later it gets stuck.

### ISSUE THREAD

**Issue by gustavogavancho** [Windows-XAML/Template10#783]
![animation](https://cloud.githubusercontent.com/assets/15368343/14005000/87125a5c-f12c-11e5-8d0d-ae793eb1caef.gif)

**Comment by JerryNixon** [comment]
If you click slowly do the results change?

**Comment by JerryNixon** [comment]
Dup of #777
