### ISSUE TITLE
NavigationFrame return null for a given Frame

### ISSUE THREAD

**Issue by aminaramoon** [Windows-XAML/Template10#784]
I have a frame inside my mainpage, I would like to get the navigation service for this Frame, my code looks like this at the moment, but it will return null. any solution ?

```
private void OnLoaded(object sender, RoutedEventArgs routedEventArgs)
        {
            MainFrameNavigationService = NavigationService.GetForFrame(MainFrame);
        }

        public INavigationService MainFrameNavigationService;
```

**Comment by JerryNixon** [comment]
Could you confirm that you have ever created a NavigationService for that Frame? If you have not then you need to use the Navigation Service Factory in the Bootstrapper.
