### ISSUE TITLE
Toast clicked event does not fire any event from bootstrapper

### ISSUE THREAD

**Issue by tapiolindqvist** [Windows-XAML/Template10#786]
From the documentation OnInitialize event should be fired, when application is running and toast event is launched. Without Template10 Bootstrapper, OnActivated fires when toast is clicked while application is running. But when using Template10 (I tested on versions 1.1.5 or 1.1.8) no events are fired. Quick fix would be to "unseal" OnActivated event. But better would be new toast clicked event, which would fire only once regardless wheter application is launghing or activating.

**Comment by JerryNixon** [comment]
OnInitialized will not be called if the application is already running. It will only be called when the application is launched. Whatever wiki you read that made you think otherwise, would you help us by updating it?

**Comment by tapiolindqvist** [comment]
Hi,

Sorry about the delay…

I deducted that OnInitialization is called always from 3 assumptions. Firstly, start of the chapter Activation paths says that bootstrapper overrides standard UWP OnActivated() and OnLaunched().  Secondly in 2. OnInitializeAsync there is “…it executes every time, even if the application is coming out of suspension…”. Thirdly, because I needed to use OnActivated() I hoped that I would launch something which I can access.

My problem is that I launch several toasts from application and I need to know which one of those toasts the user has clicked. I am using toast “Action->Arguments” to achieve that. And the way to capture them is OnActivated -> ToastNotificationActivatedEventArgs (https://msdn.microsoft.com/en-us/windows/uwp/controls-and-patterns/tiles-and-notifications-adaptive-interactive-toasts Activation Samples -> Foreground).

Tapio Lindqvist

PS. My native tongue is Finnish, so if you can’t understand my explanation and you have some Finns in your team. Let me know.
