### ISSUE TITLE
MasterDetail sample not working

### ISSUE THREAD

**Issue by Pinox** [Windows-XAML/Template10#787]
I was checking out the samples of template 10. The MasterDetails sample does not run correctly. I get the following errors.

![image](https://cloud.githubusercontent.com/assets/5297255/14042634/6ee405f8-f284-11e5-81e0-de6f1ad49a83.png)

**Comment by SamuelLioult** [comment]
Hi Pinox,
It's right, but all is in the error message. Simply, in the MainPage.xaml, remove the grid row definition and the grid column definition blocks that are below the VisualStateManager block. Also, replace the CommandBar block by this which is above the VisualStateManager block. I hope this help.

Also, sorry for my broken English ;-)

**Comment by vlastimilmaca** [comment]
Hi,
I think that pull request #779 solves this.
