### ISSUE TITLE
OnInitializeAsync not executed after resuming from suspension (mobile)

### ISSUE THREAD

**Issue by Gh0s7** [Windows-XAML/Template10#790]
Reading Template10's docs it says that

> `OnInitializeAsync` executes first. And it executes every time, even if the application is coming out of suspension

and MSDN docs say that

> The system suspends your app whenever the user switches to another app or to the desktop or Start screen.

so I'm expecting this method to be ran even after coming back to the app using back button from Start screen.
However it doesn't happen, as I added a `Debug.WriteLine` and it's only printed once.

**Comment by JerryNixon** [comment]
You are reading Windows 8 documentation. In Windows 10, neither the Start screen or other apps cause a desktop application to be suspended. In Windows 10 desktop, the only event to cause suspension is to minimize the app. I hope this helps. In Windows 10 mobile, I think you will discover the Start menu does not invoke suspension. That being said, I am suddenly unsure. Have you tested?

**Comment by JerryNixon** [comment]
Leave a comment

**Comment by Gh0s7** [comment]
Actually my source for the suspension docs is UWP related, not Windows 8 ([https://msdn.microsoft.com/en-us/windows/uwp/launch-resume/app-lifecycle](App Lifecycle)), which starts with 

> [ Updated for UWP apps on Windows 10. For Windows 8.x articles, see the archive ]

and that's why I asked.

Now you're saying that 

> In Windows 10 desktop, the only event to cause suspension is to minimize the app

so I've tested it on desktop and the line doesn't get printed even after restoring the app from a minimized state.

Basically what I'm trying to do is to ask a PIN everytime the app is opened, and I want to ask it even if the app has been resumed from suspension like some sort of "lock the app for inactivity", since it will store sensitive data.

**Comment by JerryNixon** [comment]
Sorry. I think I misunderstood your original question. And, I think you misunderstand activation. Unfortunately, when your app is suspended/resumed with a simple fast-memory swap, you will not get any events raised. You only get events when you are terminated and restored. 

I think what you want might be accomplished using `Window.Current.Activated`.
