### ISSUE TITLE
Windows Datagrid Alternative

### ISSUE THREAD

**Issue by Pinox** [Windows-XAML/Template10#794]
I would like to suggest a new feature that is probably complimentary to the Master-Details Sample. 
As an absolute beginner on UWP it would be a really cool feature to add the functionality as in the gif attached. I took the screenshot from Microsoft Money app.   If someone is aware of an good example on the net plse post the link. Thanks.

![animation 0](https://cloud.githubusercontent.com/assets/5297255/14134286/5e40b5f4-f656-11e5-9fb8-9d349b05a472.gif)

**Comment by JerryNixon** [comment]
Sure, check out the BottomAppBar sample

**Comment by Pinox** [comment]
Thank you for the update.
