### ISSUE TITLE
System.Exception during navigation

### ISSUE THREAD

**Issue by Gh0s7** [Windows-XAML/Template10#795]
> System.Exception: Your parameter must be serializable. If it isn't, then use SessionState.

I added `DataContract` to my model classes to make them serializable and now it doesn't throw the exception, the problem is that it doesn't even navigate and nothing happens.

To make things easier, here's a quick stripped-out version of my project: [Repro.zip on Dropbox](https://www.dropbox.com/s/e18tq47xat8cdq1/Repro.zip?dl=0)

**Comment by JerryNixon** [comment]
It sounds to me that whatever you as passing cannot be serialized. The Json serializer should not require DataMember. In cases like this, I would recommend you try something like `SessionState.Add("MyKey", myObject);` and then fetch it form SessionState in the OnNavTo() in your view-model. Make sense?

**Comment by Gh0s7** [comment]
It makes sense, still I think that there's an issue with serialization.
My data classes are `Category` and `Entry`.

`Category` has just a `string` and a `List<Entry>` while `Entry` has just a `string` property so I'd expect them to be serializable without any issue.

EDIT:

Added

```
var str1 = JsonConvert.SerializeObject(Category); // NewtonSoft.Json
var str2 = new JsonConverter().ToStore(Category, typeof (Category)); // Template10.Services.SettingsService
```

before 

`NavigationService.Navigate(typeof (CategoryPage), Category);`

and `Category` is serialized correctly in both cases, still the last line throws the exception about serialization.
