### ISSUE TITLE
Add more controls to PageHeader

### ISSUE THREAD

**Issue by Dawid93** [Windows-XAML/Template10#796]
Is it possible to add a few TextBlock control or something like that to the PageHeader?

**Comment by JerryNixon** [comment]
The `PageHeader.Controls` property allows that. However, it only places things in the left area. If you want more, you can always put control s next to the PageHeader control. You don't _have_ to put them inside, do you?

**Comment by JerryNixon** [comment]
Please as this question on StackOverflow with Template10 tag
