### ISSUE TITLE
Issues with nuget restore after updating to Visual Studio 2015 Update 2

### ISSUE THREAD

**Issue by polarapfel** [Windows-XAML/Template10#798]
If you are running into issues with restoring nuget packages in a Template10 based app after upgrading Visual Studio 2015 to Update 2, specify a specific version of Template 10 in project.json:

"Template10": "1.1.**8**"
rather than using
"Template10": "1.1.*"

You might have to reload the project to have Visual Studio show the references correctly. Weirdly, the build works without reloading the project, but Intellisense fails seeing the references after restoring without reloading the project.

**Comment by Rasetech** [comment]
Sry was my fault, had another project that wasn't updated to 1.1.8 but referenced from my updated project.
