### ISSUE TITLE
Design Pattern -  Blades

### ISSUE THREAD

**Issue by Pinox** [Windows-XAML/Template10#800]
I would like to suggest a really cool feature that I saw on a Build 2016 screencast.  Blades is used extensively in Windows Azure Dashboard for sequential entry of data especially on a desktop PC. This is probably another variation of the master-details sample.  Plse see gif attached.  Thanks.

![blade-demo](https://cloud.githubusercontent.com/assets/5297255/14225081/d2ce3c32-f8b5-11e5-97db-419ee8c53a9a.gif)

**Comment by Pinox** [comment]
I forgot to add the source code for this feature - http://liftcodeplay.com/2016/01/18/code-sample-for-the-blade-design-pattern/

It would be nice for everyone if you can include it part of the samples in template 10

**Comment by angusbreno** [comment]
Hey @Pinox 

I have a approach different that let u take control of the content of your blades, customize it and modularize it.

Take a look at:
http://breno.me/blades-control-for-uwp/

![Blade Controls1](http://breno.me/wp-content/uploads/2016/02/qwe2.gif)
![Blade Controls2](http://breno.me/wp-content/uploads/2016/02/qwe3.gif)
_And works for mobile too._

You can...
...contribute here: https://github.com/NaylahProject/Naylah.Toolkit.UWP#blade-controls-bladestack-and-blade
...nuget it here: https://www.nuget.org/packages/Naylah.Toolkit.UWP/

A demo: https://www.youtube.com/watch?v=RrwUKMwVBuU&feature=youtu.be

**Comment by JerryNixon** [comment]
Looks cool.
