### ISSUE TITLE
BootStrapper.OnStartAsync is not called on protocol activation if the app is already running.

### ISSUE THREAD

**Issue by mitkodi** [Windows-XAML/Template10#802]
As I see calling OnStartAsync only once during app's lifetime is by design but what if the app is running and another application has to send something to it through protocol activation?

**Comment by Viachaslau-Zinkevich** [comment]
Agree on this, and also when any Toast action is performed? It won't allow you to respond to this. And you can't override default OnActivated as it was sealed...

**Comment by JerryNixon** [comment]
This is fixed on GitHub, will update NuGet pack this week to 9.
