### ISSUE TITLE
Update nuget package

### ISSUE THREAD

**Issue by Opiumtm** [Windows-XAML/Template10#804]
There are many valuable bug fixes including #725, but current nuget package version is still 1.1.8

**Comment by angusbreno** [comment]
I am currently setting up CI build and nuget publication in for the project.

**Comment by JerryNixon** [comment]
Will do this this week.

**Comment by Opiumtm** [comment]
@JerryNixon still no new package on nuget

**Comment by Opiumtm** [comment]
@JerryNixon https://www.nuget.org/packages/template10
No package still...
