### ISSUE TITLE
PageHeader xaml error Cannot add instance of type 'Template10.Behaviors.NavButtonBehavior' 

### ISSUE THREAD

**Issue by MudzNZ** [Windows-XAML/Template10#805]
Hello,

Receiving the below error with the PageHeader control

Cannot add instance of type 'Template10.Behaviors.NavButtonBehavior' to a collection of type 'Microsoft.Xaml.Interactivity.BehaviorCollection'.

This is my xaml mainpage

<Page
    x:Class="App1.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App1"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:controls="using:Template10.Controls"
    mc:Ignorable="d">

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <controls:PageHeader x:Name="MainHeader" Text="Test" />
    </Grid>
</Page>

**Comment by JerryNixon** [comment]
Dup #801
