### ISSUE TITLE
hamburger menu keyboard control doesn't work

### ISSUE THREAD

**Issue by mitchcapper** [Windows-XAML/Template10#806]
Navigation using the keyboard does not go well for the hamburger menu.  Even if you focus over to it using tab stops up and down do not move between the items.  This is a minor annoyance on desktop but for a keyboard only interface (Xbox controller)  its not very usable.

**Comment by JerryNixon** [comment]
I've noticed the same thing. The focus seems to stay either in the Pane or in the Content. I think this has to do withTabScope, but it will take a little investigation. If you figure it out, please share.

**Comment by mitchcapper** [comment]
I went through and created XYFocusDown/up/left/right properties on HamburgerButtonInfo and bound them into the ToggleButton thinking this could be used.  This creates problems however as even if you allow binding through of a name for them referencing them doesn't work well.  The only real option there is to make the info items actually controls instead which didn't seem like a great way to go.

Instead I altered your outer container to a container that would more naturally lend itself to controls.

**Comment by mitchcapper** [comment]
I think it is more than tabscope/kb order.

Alright so we should work to find a solution for this (and with UWP options on the xbox now maybe sooner the better).
The main problem is the navigation flow cannot be detected by the default xbox scoping, and doesn't work with a keyboard either (arrow keys).

There are a few obvious options to go about this:
-Change the outer container to something that UWP naturally provides navigation controls for (GridView/ListBox for example).  This also gives a nice visible selection box as you navigate between the items.  Main downside is you need a bit of hackery to make sure the togglebutton gets selected inside the content for the element.

-XYFocus - this allows you to specifically specify what elements are above/below the current element in navigation.  This works by specifying the element above/or below on the item property itself.  This may or may not crash when used on a framework below the supported framework (14295), which is probably a bug but seems to be the current issue. In addition this is most likely an xbox-only solution, so you would still only have tab stops for xbox.  As the user doesn't specify actual user controls however they cannot 

-Event Handler key binding manual focus setting(detect up key and focus on the right item) this is fairly hacky and probably the wrong way to go

-Rather than having the user specify info objects (HamburgerButtonInfo) that get converted by templates to real objects, users could specify a usercontrol (so instead just make a HamburgerButton control).  This has the benefit things like XYFocus and name would end up on the direct controls (so a user could specify them as an XYFocus target for example, so you could left arrow onto the correct item into a hamburger menu).   

-We could try to solve why the native focus tool doesn't figure out the proper controls for navigation for the xbox focus manager, there isn't a whole lot of documentation on how it works however so I am not sure how easy this would be.  In addition it doesn't solve the keyboard issue.

In addition there are some minor changes that should happen either way (removal of the header tabstop, and focus on the first togglebutton when the control itself gets focus).

In the short term is there a reason the class is sealed? I am not sure what problem allowing 3rd party inheriting could cause. It would at-least allow for a temporary work around for the template10 nuget package.

Open to other suggestions, or you can say you don't want to figure it out right now and I will just probably dupe the control for my own use.

**Comment by mitchcapper** [comment]
64c419a made some nice improvements here and was elegant at the same time. Ironically focus moving to the secondary buttons fails, and its because of 
`BorderBrush="{Binding SecondarySeparator, ElementName=ThisPage, FallbackValue=White}"`

why a border brush prevents tab or focus navigation I am not sure (with the border brush focus shifts to the secondarybuttoncontainer rather than the buttons themselves). Putting this simply into the ItemsControl itself  resolved this focus problem.  Of course later I found that having the primary/secondary button containers being tab stops at all was actually a bad idea (no need to allow focus on them) and simply removing them as a tabstop also fixed the problem.

This does cause keyboard navigation to be possible on the entire app, which may or may not be desired. At a minimum a setting controlling if this is enabled may be good, but a better solution may be to do a parent lookup to make sure the items we are about to adjust focus on are within the shell UI and not the content itself.

Using up/down for tab/shift tab however I think is a mistake (especially as this affects the apps native navigation).

We only have one case where tabbing forward or reverse gets screwed up with the minor changes I made and that was the HamburgerButton itself to the primarycommands. At first I figured solve this case directly:

```
if (!focus(FocusNavigationDirection.Next) && (focusedItem as Control) == HamburgerButton)
                            PrimaryButtonContainer.Focus(FocusState.Programmatic);
```

This worked but I figured a more generic solution might be better.  So if next/previous fails then it falls back to up/down.   I thought about doing the same for up/down/left/right failing (using next/prev as fallback) but couldn't find a use case this was good for yet (it didn't do any harm that I found however).   

The PageHeader control(CommandBar) runs into issues where it absorbs the key presses (even trying KeyDown on PageHeader doesn't get fired) for arrow keys. Arrow keys work within the commandbar but don't allow cycling out of it. I did find KeyUp however would be reliably fired so hooking that with:

```
private void PageHeader_KeyUp(object sender, KeyRoutedEventArgs e) {
            if (e.Key == VirtualKey.Up)
                FocusManager.TryMoveFocus(FocusNavigationDirection.Previous);
            if (e.Key == VirtualKey.Down)
                FocusManager.TryMoveFocus(FocusNavigationDirection.Next);
        }
```

fixes this.  This code however could be implemented by a user if they wanted it, so for the sake of simplicity I left it out of the PR.

**Comment by JerryNixon** [comment]
Okay, am I reading two issues? The first is the HamMenu and the second is PageHeader? The HamMenu is getting this and more logic to get nav with keyboard better. But I am not following you with PageHeader yet. Could you open a dedicated issue?

**Comment by mitchcapper** [comment]
Yeah HamMenu is in really good shape with what you did yesterday in 64c419a and if you made similar minor changes to my PR navigation should be quite fluid without stops on elements that shouldn't be and work well with keyboard.   

PageHeader (CommandBars in general) absorb keydown's and don't allow arrow key events to bubble up (to which your 64c419a code would fix).  Once inside you can arrow around, the control no problem but you can't arrow out (it behaves like TabNavigation=Contained for arrow keys). Technically if 64c419a did keyup rather than keydown it would probably also resolve.

Fixing pageheader I am not sure if it is the job of the library to do or not.  Its jarring currently as arrow keys can get completely stuck on the control right now. The user can use code like above to fix it.  With that said I am not sure if there is any downside to the library fixing it for pageheader, as it provides a better experience.  I can do a PR with the above on PageHeader if you think its worth changing at a library level.
