### ISSUE TITLE
HoloLens device detection is incorrect

### ISSUE THREAD

**Issue by craigktreasure** [Windows-XAML/Template10#807]
DeviceUtils checks for "Windows.HoloLens" when it should be "Windows.Holographic":

``` C#
case "Windows.HoloLens": return DeviceFamilies.HoloLens;
```

**Comment by JerryNixon** [comment]
Are you going to submit a Pull Request to correct this?

**Comment by craigktreasure** [comment]
@JerryNixon I can do it, but it won't be until later this evening. If you've got bandwidth, don't wait for me.

**Comment by JerryNixon** [comment]
This is not my season for bandwidth, unfortunately. I can wait. I plan to release a NuGet update on Friday, so try to get it in before Thursday.
