### ISSUE TITLE
Hamburger Menu starts with wrong "breakpoint"

### ISSUE THREAD

**Issue by schuettecarsten** [Windows-XAML/Template10#811]
When HamburgerMenu is set to "FullScreen=true" in XAML, adaptive triggers for normal/wide/narrow state are not applied when then HamburgerMenu is shown for the first time because UpdateFullScreen() removed the splitview from visual tree.

**Comment by darenm** [comment]
@carstenschuette  Can you check something for me? I've noticed that if we actually do async work in OnStartAsync we get a similar visual state issue with the Hamburger. Just adding `await Task.Delay(3000);` simulates the issue quite effectively. Can you test your fix in that scenario also?
