### ISSUE TITLE
ModalDialog not hiding AppBar on page behind Shell/ModalDialog?

### ISSUE THREAD

**Issue by 1iveowl** [Windows-XAML/Template10#817]
I have an App with a Hambugermenu. 

I'm using the ModalDialog in Shell.xaml. When a user is not logged into the App the user will be presented with the ModalDialog, which basically is just as a full screen pin login page. The user logged in state is controlled by an observable IsLoggedIn state boolean. This all Works fine. So far so good. 

On one of my pages that can navigated to using the Hambuger menu I have an AppBar. Now the issues begin: 

If I suspend my app and then resume it again, the app logic dictates that the user must login again with the pin code. This Works but for some reason the AppBar from the page (behind) is now also showing up as part of the ModalDialog?! 

Why is the AppBar from the page showing and more importantly, how do I remove it? 

To make matters a more complicated the App is adaptive and the AppBar is using a Trigger making sure that the AppBar is only shown on Phone devices and not desktop devices. Hence I cannot just bind the Visibility of the AppBar to the observable IsLoggedIn boolean.

**Comment by darenm** [comment]
Are you using `Page.BottomAppBar`? Due how UWP composes the Top/Bottom app bars, they often appear on top of other UI elements (for example, if you open the hamburger, the bottom part of the menu is obscured by the AppBar). The current workaround is to place the AppBar in a row of a Grid on your page.

**Comment by 1iveowl** [comment]
That is exactly it. Thank you!

**Comment by darenm** [comment]
Great!
