### ISSUE TITLE
Template 10 Crashing when PC runs under 125% Magnification

### ISSUE THREAD

**Issue by Pinox** [Windows-XAML/Template10#820]
I have posted this bug before , but Jerry closed it because he probably could not produce the same error.  Can someone else plse check and give feedback.  I managed to figure out that this error is only happening under magnification of system settings.

In the first image you will simply see the dropdown items listed without a vertical scrollbar (100% magnification setting on PC)

![image](https://cloud.githubusercontent.com/assets/5297255/14363022/6dd9753e-fd02-11e5-916b-b3717e4d788e.png)

I will now change the magnification on the system to 125%

![image](https://cloud.githubusercontent.com/assets/5297255/14363044/89ef7a5c-fd02-11e5-883d-4151782cb5ab.png)

Dropdown will now change to one that has a vertical scrollbar - clicking on the down button of the vertical scrollbar will produce the error.

![image](https://cloud.githubusercontent.com/assets/5297255/14363071/b3e9d79e-fd02-11e5-80ff-b6f623c0ca30.png)

Click here to produce error
![image](https://cloud.githubusercontent.com/assets/5297255/14363429/7fa4ddce-fd04-11e5-8482-326f77d101d7.png)

**Comment by Pinox** [comment]
Click here to produce error.

![image](https://cloud.githubusercontent.com/assets/5297255/14363259/9c7c34d4-fd03-11e5-9666-c2e2fda74563.png)

**Comment by darenm** [comment]
Hey Pinox - does the same behavior happen if you just use a `CommandBar` instead of the Header control?

**Comment by JerryNixon** [comment]
I think @darenm may be onto something. There is nothing custom about the secondary menu in the PageHeader. I think what you may have discovered is an artifact of the CommanBar, which the PageHeader is sub-classing. Please confirm.

**Comment by Pinox** [comment]
Hi Guys, the error above happens in the standard "hamburger" template of template 10.

The template code is as follows 
![image](https://cloud.githubusercontent.com/assets/5297255/14376962/4d7e5168-fd6d-11e5-8e43-6c465e1620e2.png)

Changing the above code to a commandbar I still get the error
![image](https://cloud.githubusercontent.com/assets/5297255/14376975/5f943660-fd6d-11e5-8532-6f06bb6968f3.png)

Therefor in both pageheader and commandbar i see the same error on the MainPage.xaml

**Comment by Pinox** [comment]
I checked Microsoft People UWP app and the same error occurs. A platform bug it is indeed.

![image](https://cloud.githubusercontent.com/assets/5297255/14377601/ddb38f2a-fd70-11e5-953e-d1f12ebf2f6e.png)

**Comment by darenm** [comment]
So it appears you have found an issue with the Windows platform as opposed to Template10 - I strongly suggest you report your findings using the windows feedback tool.
