### ISSUE TITLE
Long running tasks in OnStartAsync cause visual states to misfire

### ISSUE THREAD

**Issue by geoffmmorgan** [Windows-XAML/Template10#821]
If I have a long running task in the OnStartAsync the application will incorrectly determine the visual state. For example

```
public override async Task OnStartAsync(StartKind startKind, IActivatedEventArgs args)
       {
           // long-running startup tasks go here

           await Task.Delay(3000);

           NavigationService.Navigate(typeof(Views.MainPage));
           await Task.CompletedTask;
       }
```

will result in this
![pasted image at 2016_04_07 04_33 pm 1](https://cloud.githubusercontent.com/assets/4315558/14369001/be215a94-fcde-11e5-9f34-d33e72574904.png)

once you resize or move the window, the correct states will fire
![pasted image at 2016_04_07 04_33 pm](https://cloud.githubusercontent.com/assets/4315558/14369003/c414b3b0-fcde-11e5-94cd-8f589d1ef458.png)

**Comment by JerryNixon** [comment]
Fix on the way
