### ISSUE TITLE
Wrong app Globalization and Theme problems

### ISSUE THREAD

**Issue by pedrohex** [Windows-XAML/Template10#822]
Hi there,
After some testing using this template i've noticed that :
- Globalization is forced to en-US at runtime.
- Phone top information bar is not visible when theme is set to dark (it is not inverting colors).

I send some snapshots ,
Thank you all
![sample1](https://cloud.githubusercontent.com/assets/1288017/14372049/1b0a5796-fd35-11e5-8417-553b48b1c0ec.png)
![sample2](https://cloud.githubusercontent.com/assets/1288017/14372048/1b0a0534-fd35-11e5-8f3a-d00e4e243043.png)
![sample3](https://cloud.githubusercontent.com/assets/1288017/14372047/1b08ff40-fd35-11e5-96b7-2f2940de2dec.png)

**Comment by Pzaan** [comment]
+1 on the globalization problem - are there any workarounds?

**Comment by marcinmarkiewicz** [comment]
The problem is in encoding. Change encoding of your XAML file to UTF-8, then correct texts and save...

**Comment by JerryNixon** [comment]
@pedrohex did @marcinmarkiewicz  fix work for you?

**Comment by pedrohex** [comment]
@marcinmarkiewicz, thanks for your help!

@JerryNixon , indeed it solved but strangely only this template was with this problem.
I've activated the option at [ Options -> Environment -> Documents -> Save documents as Unicode when data cannot be saved in code page]. After this , everything is going smooth.. Thanks!

**Comment by Pzaan** [comment]
Yes, this worked.  Thanks @marcinmarkiewicz!

**Comment by marcinmarkiewicz** [comment]
I had earlier this problem... I got help from @Opiumtm :)

**Comment by JerryNixon** [comment]
https://github.com/Windows-XAML/Template10/wiki/Document-Encoding

![image](https://cloud.githubusercontent.com/assets/1749983/16405511/7ee8000e-3cc5-11e6-8460-021f6e1b60e2.png)
