### ISSUE TITLE
Backbutton in titlebar do not throw focus change when click ...

### ISSUE THREAD

**Issue by Kearsoft** [Windows-XAML/Template10#825]
When the back button is in titlebar, if I change text in textbox and without leaving the textbox i click back the binding are not set on the viewmodel ... so in OnNavigatingFromAsync I can't validate the good values before exiting ...
Thanks

**Comment by JerryNixon** [comment]
Well, this is a XAML question. This is for http://StackOverflow.com and not here. Send me your SO question on Twitter @jerrynixon and I'll make sure it gets answered.
