### ISSUE TITLE
When operating on a list, switching to a new item loses any changes to current textbox

### ISSUE THREAD

**Issue by MWaser** [Windows-XAML/Template10#826]
I have a list of people (name, age) and two data input textboxes, if I exit the textboxes in any fashion _except_ by  clicking on a person, the change takes effect.  If I click on a person, any change to the current textbox is lost.

The culprit is clearly using RaisePropertyChanged when the selected Index changes which updates the textboxes -- unexpectedly BEFORE the textbox's property change fires
        int _SelectedIndex = 0;
        public int SelectedIndex
        {
            get { return _SelectedIndex; }
            set { if (Set(ref _SelectedIndex, value)) 
                       { RaisePropertyChanged(nameof(SelectedPerson)); } 
               }
        }

I would have expected OnEnter property changes to be handled AFTER OnExit property changes.

Below is the XAML . . . .

```
    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}"
        RelativePanel.AlignLeftWithPanel="True" RelativePanel.Below="pageHeader" >
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="Auto"/>
            <ColumnDefinition Width="Auto"/>
        </Grid.ColumnDefinitions>
        <StackPanel Grid.Column="0" Orientation="Vertical">
            <ListView  x:Name="MainList" ItemsSource="{x:Bind People.List, Mode=OneWay}"  
        SelectedIndex="{x:Bind People.SelectedIndex, Mode=TwoWay}" MinWidth="250" Margin="5">
                <ListView.ItemTemplate>
                    <DataTemplate x:DataType="vm:PersonViewModel" >
                        <TextBlock Text="{x:Bind Name, Mode=OneWay}" />
                    </DataTemplate>
                </ListView.ItemTemplate>
            </ListView>
            <Button Content="Add" Click="{x:Bind People.Add}" Margin="5"/>
        </StackPanel>
        <StackPanel Grid.Column="2" Orientation="Vertical">
            <TextBox Text="{x:Bind People.SelectedPerson.Name, Mode=TwoWay, FallbackValue=''}" Margin="5" />
            <TextBox Text="{x:Bind People.SelectedPerson.Age, Mode=TwoWay, FallbackValue='0'}" Margin="5" />
            <Button Content="Delete" Click="{x:Bind People.Delete}" Margin="5" />
        </StackPanel>
    </Grid>
```

Thanks!

**Comment by JerryNixon** [comment]
What a bizarre timing issue. Do you have any suggestions?

**Comment by MWaser** [comment]
I solved it by using a CollectionViewSource to synch the Master List and the Details instead of effectively rolling my own by using SelectedIndex (using SelectedIndex was a bad idea now that I know about CollectionViewSources -- even if they are castrated versions of their WPF parents.  :-)

Thanks for replying!
