### ISSUE TITLE
Nested menu with Template 10

### ISSUE THREAD

**Issue by mostafa-elabady** [Windows-XAML/Template10#829]
I want to use the Hamburger menu from Template 10 and add dynamic sections,

for example

--Mail section (header)

------Inbox

------Sent Items

--Calendar (header)

-----etc..

list of headers, for each item, there is a list of clickable items.

Is there a way to bind the primary buttons and add a template for the items?
I've added a question on stackoverflow here: [http://stackoverflow.com/questions/36545559/nested-menu-with-template-10](http://stackoverflow.com/questions/36545559/nested-menu-with-template-10)

**Comment by JerryNixon** [comment]
There is no way to do this right now. That being said, there's nothing stopping you from adding a left margin to buttons under Inbox or whatever. That would give you the nesting. Make sense?
