### ISSUE TITLE
Problem with Navigation 

### ISSUE THREAD

**Issue by diogenesl** [Windows-XAML/Template10#835]
I'm not sure if I fully understood Navigation, but I'm having a problem with a page that contains a GridView, every item have a delete button, when pressed it simple removes an item from an ObservableCollection<>, but if after that I use the backbutton, the list gets restored to the previous state, it's like the delete button insert another page inside the NavigationStack or something like that.

This project was created using the minimal template

**Comment by dubstylee** [comment]
This sounds similar to a problem I have with Behaviors 1.0.3. The new version of Behaviors fixes this issue. The updates have been committed, but the new NuGet package isn't out yet. Once 1.1.9 comes out, hopefully your problem will be resolved.
