### ISSUE TITLE
Guidance requested for overriding OnBackKey

### ISSUE THREAD

**Issue by johanlindfors** [Windows-XAML/Template10#836]
I have an application with pages that leverages the WebView to render pages from server side. Naturally these web pages navigates back and forth and I need to be able to override the OnBackKey event to make sure the Frame doesn't navigate but instead lets the WebView GoBack if the BackStack of the webview allows it to.

Any suggestions?

**Comment by JerryNixon** [comment]
Have you tried handling Bootstrapper.Backrequested with e.Handled = true?

**Comment by johanlindfors** [comment]
Once again great support, that works just fine!!!
