### ISSUE TITLE
Hiding CommandBar inside PageHeader

### ISSUE THREAD

**Issue by Gh0s7** [Windows-XAML/Template10#837]
I need to be able to hide the `CommandBar`inside the `PageHeader`when on mobile, since I'm moving it to bottom of the page.
Setting `Visibility`for each button works, but some of them already have their `Visibility`bound for other purposes and so I really can't control them.
Can we have a `Visibility`property for the `CommandBar`?

**Comment by JerryNixon** [comment]
What an interesting idea.

**Comment by JerryNixon** [comment]
Added `PrimaryCommandsVisibility` as well as `EllipsisVisibility` which I think would likely be your secondary request. Setting it to Collapsed will hide your secondary menu, too.

**Comment by Gh0s7** [comment]
Great, thanks for the fast response!
