### ISSUE TITLE
Page.TopAppBar DataContext?

### ISSUE THREAD

**Issue by plettb** [Windows-XAML/Template10#84]
Page.TopAppBar doesn't seem to be affected by Page.DataContext.  Despite setting my DataContext for the page, bindings to commands from, for example, AppBarButton, try to find them on the view itself.

**Comment by JerryNixon** [comment]
Are you getting the same thing with the nuGet version?

**Comment by youtoofan** [comment]
This is an extract from one of my pages:
<controls:PageHeader x:Uid="Header_Parts" Text="Parts" Frame="{x:Bind Frame}">

            <controls:PageHeader.PrimaryCommands>

                <AppBarButton x:Uid="UpButton" Label="Up" Icon="Up" Command="{x:Bind ViewModel.GoUpCommand}"/>

                <AppBarButton x:Uid="AddButton" Label="Add" Icon="Add" Command="{x:Bind ViewModel.AddPartCommand, Mode=OneWay}" IsEnabled="{x:Bind ViewModel.AllowNewPart, Mode=OneWay}"/>

            </controls:PageHeader.PrimaryCommands>

        </controls:PageHeader>

And the page context:


<Page.DataContext>

        <viewModels:PartsPageViewModel />

    </Page.DataContext>


My commands bind perfectly, as expected.

**Comment by JerryNixon** [comment]
Just noticed you said TopAppBar. Nothing to do with T10. Still, you can use this syntax:

``` XAML
<Page x:Name=ThisPage">
  <Page.TopAppBar>
    <CommandBar DataContext="{Binding DataContext, ElementName=ThisPage}" />
  </Page.TopAppBar>
</Page>
```
