### ISSUE TITLE
Multiple Views issue with Suspending

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [Windows-XAML/Template10#841]
Hi, while trying to implement multiple views to my app I faced and issue, when closing all views and app starts suspending if actually fails to save the state as ALL available NavigationServices for ALL WindowWrappers get called from same Thread and then they fail, trying to check Frame from wrong UI thread.

BootStrapper.Loaded.Suspending:

```
   foreach (var nav in WindowWrapper.ActiveWrappers.SelectMany(x => x.NavigationServices))
                        {
                            // date the cache (which marks the date/time it was suspended)
                            nav.FrameFacade.SetFrameState(CacheDateKey, DateTime.Now.ToString());
                            // call view model suspend (OnNavigatedfrom)
                            DebugWrite($"Nav:{nav}", caller: nameof(nav.SuspendingAsync));
                            await nav.SuspendingAsync();
                        }
```

 await nav.SuspendingAsync(); fails inside as tries to use Frame from wrong thread.

For myself I tried to modify NavigationService,SuspendingAsync()

```
public Task SuspendingAsync()
        {
            DebugWrite($"Frame: {FrameFacadeInternal.FrameId}");
            return Dispatcher.DispatchAsync(async () =>
            {
                await SaveNavigationAsync();
                await NavigateFromAsync(true);
            });
        }
```

But perhaps it's a better idea to call in correct thread initially from BottStrapper.

**Comment by JerryNixon** [comment]
Could you help by verifying your scenario is resolved with the current GitHub source?

**Comment by Viachaslau-Zinkevich** [comment]
As far as I can say, there's no exception on closing app, yes.
