### ISSUE TITLE
Brand new Hamburger application doesn't work

### ISSUE THREAD

**Issue by Rich-Hopkins** [Windows-XAML/Template10#842]
The type 'ActionCollection' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Xaml.Interactivity, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null'.

I have tried following this advice (https://github.com/Windows-XAML/Template10/issues/700), but the project.json is already set to use  "Microsoft.Xaml.Behaviors.Uwp.Managed": "1.0.3",

**Comment by mvermef** [comment]
Did you recently update the template?  if so there a requirement to start using 

```
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.1.0",
    "Microsoft.Xaml.Behaviors.Uwp.Managed": "1.1.0",
```

I take that back the update hasn't been pushed out yet to 1.1.9... shortly... The current code base does compile and doesn't complain about versioning...

**Comment by Rich-Hopkins** [comment]
I just installed today for the first time.

**Comment by pedrohex** [comment]
Rich-Hopkins , 
I solved by doing the following : 
1- Right Click Project
2- Select Manage NUGet Packages
3- Click on tab "Installed"
4- Select Microsoft.Xaml.Behaviors.Uwp.Managed
5- On the right pane change installed version from 1.1.0 to 1.0.3

I believe this can be a wrong reference in Template10Hamburger, maybe @JerryNixon can check this.

**Comment by Rich-Hopkins** [comment]
Thanks for the suggestion, @pedrohex. Unfortunately, it says my installed version is already 1.0.3. But while I was looking at it, I noticed that there were updates available to my installed packages, and T10 is one of the packages that there was an update for (to 1.1.8). I updated that, cleaned and rebuilt my project, and yes, it worked. ;)

Thanks to whomever updated the package!

**Comment by Rich-Hopkins** [comment]
Well, I guess I give up on this T10 thing. I can't get a unit test to give me anything other than 
Inconclusive: A user callback threw an exception..." I'm trying to learn test driven development, while I learn to do Windows 10 development, and I don't have the know-how to fix this problem.

**Comment by mvermef** [comment]
#464 
Try doing adding [Bindable] to the App.cs class object, reference that closed ticket, it might shed some light.

**Comment by NateRadebaugh** [comment]
I also had issues building a fresh "Template10 Hamburger" template from the newly installed Template10 extension.

I was able to get mine building by manually uninstalling the Template10 nuget package and re-installing the latest (1.1.8) nuget version.

**Comment by JerryNixon** [comment]
There are fresh templates and a new NuGet deployed. Please test. Open a new issue if found.
