### ISSUE TITLE
Directives.rd.xml

### ISSUE THREAD

**Issue by mvermef** [Windows-XAML/Template10#844]
Has anyone had issues with this one related to Template10?  I thought it was related EntityFramework but now not so sure, building source locally for T10 it appears to show up in the build for release... as a warning..  

I have a question related to this on SO, T10 is tagged but not sure at present.   This stuff can be beyond confusing... Since you have sit there and see what needs to be included and want isn't necessary

```
Resources.System.Linq.Expressions.rd.xml(35): warning : ILTransform_0027: Method 'CreateLambda' within 'System.Linq.Expressions.Expression' could not be found.
Resources.System.Linq.Expressions.rd.xml(91): warning : ILTransform_0027: Method 'ParameterIsAssignable' within 'System.Linq.Expressions.Expression' could not be found.
```

**Comment by mvermef** [comment]
Here straight from the build of Hamburger with in the Template folder....

2>------ Build started: Project: Hamburger, Configuration: Release x86 ------
2>  Hamburger -> C:\Users\mverm\Documents\Projects\Frameworks\Template10\Templates (Project)\Hamburger\bin\x86\Release\Sample.exe
2>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1908,5): warning APPX0104: Certificate file 'Minimal_TemporaryKey.pfx' not found.
2>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1908,5): warning APPX0107: The certificate specified is not valid for signing. For more information about valid certificates, see http://go.microsoft.com/fwlink/?LinkID=241478.
2>  Starting .NET Native compilation
2>  Processing application code
2>C:\Users\mverm\Documents\Projects\Frameworks\Template10\Templates (Project)\Hamburger\Resources.System.Linq.Expressions.rd.xml(35): warning : ILTransform_0027: Method 'CreateLambda' within 'System.Linq.Expressions.Expression' could not be found.
2>C:\Users\mverm\Documents\Projects\Frameworks\Template10\Templates (Project)\Hamburger\Resources.System.Linq.Expressions.rd.xml(91): warning : ILTransform_0027: Method 'ParameterIsAssignable' within 'System.Linq.Expressions.Expression' could not be found.
2>  Computing application closure and generating interop code
2>  Generating serialization code
2>  Compiling interop code
2>  Cleaning up unreferenced code
2>  Generating native code
2>  Generating fixups for native code
========== Build: 2 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by artfuldev** [comment]
@JerryNixon I think those 2 directives can be removed. Have a look at this: https://github.com/dotnet/corefx/issues/5088

**Comment by JerryNixon** [comment]
What two directives?
