### ISSUE TITLE
Exception on ConditionalAction

### ISSUE THREAD

**Issue by Gh0s7** [Windows-XAML/Template10#846]
I have a list with a click behavior in the `DataTemplate` and I'd like to disable that while in selection mode, but I'm receiving this exception:

>    System.InvalidCastException: Unable to cast object of type 'Template10.Behaviors.ConditionalAction' to type 'Windows.UI.Xaml.FrameworkElement'.
>    at Template10.Behaviors.OpenFlyoutAction.Execute(Object sender, Object parameter)
>    at Microsoft.Xaml.Interactivity.Interaction.ExecuteActions(Object sender, ActionCollection actions, Object parameter)
>    at Template10.Behaviors.ConditionalAction.Execute(Object sender, Object parameter)
>    at Microsoft.Xaml.Interactivity.Interaction.ExecuteActions(Object sender, ActionCollection actions, Object parameter)
>    at Microsoft.Xaml.Interactions.Core.EventTriggerBehavior.OnEvent(Object sender, Object eventArgs)

This is my code:

```
<interactivity:Interaction.Behaviors>
    <core:EventTriggerBehavior EventName="Tapped">
        <behaviors:ConditionalAction LeftValue="{Binding SelectionMode, ElementName=GridView}"
                                     RightValue="{Binding Converter={StaticResource NullToNoneSelectionModeConverter}}"
                                     Operator="EqualToRight">
            <core:InvokeCommandAction Command="{Binding CopyKeyCommand}" />
            <behaviors:OpenFlyoutAction />
            <behaviors:TimeoutAction Milliseconds="1000">
                <behaviors:CloseFlyoutAction />
            </behaviors:TimeoutAction>
        </behaviors:ConditionalAction>
    </core:EventTriggerBehavior>
</interactivity:Interaction.Behaviors>
```

Is this an issue on my end? How can I fix it?

**Comment by JerryNixon** [comment]
The problem is the Flyout action. In the current GitHub source, or the forthcoming NuGet version, a new TargetObject property has been added that allows you to specify the flyout or the flyout tree. In this case, it is attempting to navigate up the visual tree, and the Conditional action is invalid.

**Comment by Gh0s7** [comment]
Fine, I'll wait for the NuGet update then. Thanks.
