### ISSUE TITLE
How to ceate a SubPage without Hamburger Menu

### ISSUE THREAD

**Issue by DominikErnst** [Windows-XAML/Template10#848]
Hi,

I use a MainPage with Hamburger Menu, but on a SubPage I do not want any Menu or Statusbar, so the Page should be kind of Fullscreen in the App.

_Maybe something like this for the StatusBar:
                var statusbar = Windows.UI.ViewManagement.StatusBar.GetForCurrentView();
                await statusbar.HideAsync();_

Thanks
Regards
Dominik

**Comment by SWilkov** [comment]
Hi Dominik,
HamburgerMenu has just the property for fullscreen
`IsFullScreen = true;`

Cheers

**Comment by mvermef** [comment]
That would be the best option, and I am assuming that you are asking this in regard to windows 10 mobile.  Don't forgot you would have to have some sort of way for the user to get the menu(Hamburger) back.

**Comment by JerryNixon** [comment]
`Page.OnNavTo() => Shell.HamburgerMenu.IsFullScreen = true;`
`Page.OnNavFrom() => Shell.HamburgerMenu.IsFullScreen = false;`
That should do it for you.

**Comment by DominikErnst** [comment]
@SWilkov: Thanks a lot, 
@mvermef: I need this Option only on the Phone-App and there is a back Button. ;-)
@JerryNixon: Thank you, too. I try this today. T10 is really fantastic. I develop SW for over 25 years and learn a lot from your source code.

**Comment by ZingPow** [comment]
I wanted the StatusBar as is as well on the Windows Phone so in App.xaml.cs in OnInitializeAsync I did this and didn't have to make any other changes and get the StatusBar.  Comments on if this is a good or bad idea.

```
        if (ApiInformation.IsApiContractPresent("Windows.Phone.PhoneContract", 1, 0))
        {
            var statusBar = StatusBar.GetForCurrentView();

            statusBar.BackgroundOpacity = 1; 
        }
```
