### ISSUE TITLE
Doesn't build when you switch to x64 and ARM

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#85]
Doesn't build when you switch to x64.

**Comment by MichaelPetrinolis** [comment]
with [this](https://github.com/Windows-XAML/Template10/pull/110) PR and latest UWP tools for VS2015 I am able to run on Windows10 Insider preview (ARM) on mobile device

**Comment by hungys** [comment]
@MichaelPetrinolis  Great! It works for me now.

@JerryNixon  Why did the templates in Templates (Project) use the library on NuGet but not the source project now? In that way, the changes in library project cannot apply to template project immediately.

**Comment by callummoffat** [comment]
Is the compilation issue fixed in 1.0.1?

**Comment by JerryNixon** [comment]
Works.
