### ISSUE TITLE
HamburgerMenu missing binding

### ISSUE THREAD

**Issue by schuettecarsten** [Windows-XAML/Template10#850]
```
Error: Converter failed to convert value of type 'Windows.Foundation.IReference`1<Boolean>' to type 'IReference`1<Boolean>'; BindingExpression: Path='IsChecked' DataItem='Template10.Controls.HamburgerButtonInfo'; target element is 'Windows.UI.Xaml.Controls.Primitives.ToggleButton' (Name='null'); target property is 'IsChecked' (type 'Boolean').
```

**Comment by JerryNixon** [comment]
I believe this is resolved in 1.1.10+

**Comment by vlastimilmaca** [comment]
@JerryNixon Just updated to 1.1.10  and I'm seeing this error. Do I need to change something in my files? Like in shell, main or other xaml?

**Comment by JerryNixon** [comment]
Well, rats. You are still seeing it? I may have misdiagnosed it.

**Comment by vlastimilmaca** [comment]
~~My bad ... wrong template10 version in one project ... it's ok~~
Edit: Scratch that ... still there ... when switching from one menu item to other.
Edit2: Happens in new hamburger project too.

**Comment by callummoffat** [comment]
I'm seeing this on 1.1.10 too. No "real" issue, but there is a delay between the click and the page navigation. It's much worse the first time the hamburger is used.

**Comment by schuettecarsten** [comment]
I have no idea why this happens. :(

**Comment by callummoffat** [comment]
No, me neither. The delay is very noticable the first time you use the menu, but not as noticable on subsequent clicks. It's annoying; it offends my OCD. :-)

**Comment by vlastimilmaca** [comment]
Similar problem, and it's solution: [http://danrigby.com/2012/07/24/windows-8-dev-tip-nullable-dependency-properties-and-binding/](http://danrigby.com/2012/07/24/windows-8-dev-tip-nullable-dependency-properties-and-binding/) .... It's not that bad to use google sometimes guys :)

Edit: I noticed Jerry commented on that 2 years ago and says it doesn't work? ... can you try it anyway?

**Comment by JerryNixon** [comment]
How do you repro it?

**Comment by vlastimilmaca** [comment]
@JerryNixon Create new hamburger project, then just run it and switch between Home and Settings in hamburger menu like this: 
![missingbinding](https://cloud.githubusercontent.com/assets/6502310/14850822/0da2d35c-0c7c-11e6-9031-15c938f4049d.gif) 

Is that what you asked for :) ?

Can you try to change IsCheckedProperty = DependencyProperty.Register ( ... ,typeof(bool?), ...) to DependencyProperty.Register ( ... ,typeof(object), ...)? It might help (suggested workaround in link I mentioned before). [Link to concrete code line in HamburgerButtonInfo.cs](https://github.com/Windows-XAML/Template10/blob/master/Template10%20%28Library%29/Controls/HamburgerButtonInfo.cs#L131)

**Comment by JerryNixon** [comment]
Got it. Thanks.
