### ISSUE TITLE
Is there a new Nuget release pending?

### ISSUE THREAD

**Issue by 1iveowl** [Windows-XAML/Template10#851]
:-)

**Comment by JerryNixon** [comment]
Yes, with Visual Studio 2015 update 2 there was a change to the VSIX project type that caused our ability to create the new templates to be broken. I do not want to release a Nuget update without a template update. The next update will be Nuget 1.1.10 and Visual Studio Gallery version 1.17. 

Soon.

**Comment by JerryNixon** [comment]
Done.
