### ISSUE TITLE
EllipsisBehavior causes Layout Exception

### ISSUE THREAD

**Issue by darenm** [Windows-XAML/Template10#857]
If you use a `PageHeader` control with no `SecondaryCommands` (or all `AppBarButton` instances set to a `Visibility="Collapsed"`) and then add an `EllipsisBehavior` with a `Visibility="Visible", your app will close with an exception:

"A cycle occured while laying out the GUI"
{"Layout cycle detected.  Layout could not complete.\r\nLayout cycle detected.  Layout could not complete."}

You may come across this if you were using a version of T10 earlier than 1.1.10 and had to force the `PageHeader` ellipsis to be shown as you were programmatically adding secondary commands or changing the `Visibility` and these changes were not detected.

``` xaml
        <controls:PageHeader x:Name="pageHeader" RelativePanel.AlignLeftWithPanel="True"
                             RelativePanel.AlignRightWithPanel="True"
                             RelativePanel.AlignTopWithPanel="True" Text="Main Page">
            <Interactivity:Interaction.Behaviors>
                <Behaviors:EllipsisBehavior Visibility="Visible" />
            </Interactivity:Interaction.Behaviors>


            <!--  secondary commands  --><!--
            <controls:PageHeader.SecondaryCommands>
                <AppBarButton Click="{x:Bind ViewModel.GotoSettings}" Label="Settings" />
                <AppBarButton Click="{x:Bind ViewModel.GotoPrivacy}" Label="Privacy" />
                <AppBarButton Click="{x:Bind ViewModel.GotoAbout}" Label="About" />
            </controls:PageHeader.SecondaryCommands>-->

        </controls:PageHeader>
```

**Comment by darenm** [comment]
Fortunately, this workaround is no longer needed in T10 1.1.10 (and presumably higher) - PageHeader now handles changes to the SecondaryCommands and will show the Ellipsis as needed.

**Comment by vlastimilmaca** [comment]
That's cool :) Good job.

**Comment by wleev** [comment]
On the other hand, setting `EllipsisBehavior Visibility="Collapsed"` will also cause the same LayoutCycle exception.

How should one now go about hiding the ellipsis?

**Comment by JerryNixon** [comment]
Leave a comment
