### ISSUE TITLE
Is it possible to remove PointerUpThemeAnimation from HamburgerButtonInfo?

### ISSUE THREAD

**Issue by ryanzzff** [Windows-XAML/Template10#861]

**Comment by JerryNixon** [comment]
At this time the only option for you is to use Literal.

**Comment by JerryNixon** [comment]
Curious... Why?

**Comment by ryanzzff** [comment]
It wasn't a big deal for me personally, but my client don't want that animation. As they said the News/Weather/Money apps that comes with the OS don't have that animation too.

**Comment by JerryNixon** [comment]
I didn't realize that until you pointed it out. Removed.
