### ISSUE TITLE
Still not able to use OpenFlyoutAction inside a ConditionalAction

### ISSUE THREAD

**Issue by Gh0s7** [Windows-XAML/Template10#862]
Following #846 I updated to the latest NuGet package but I'm still having issues, even with the new `TargetObject` property.

To add more context, I'm using this action inside a `Grid` which is inside a `DataTemplate` in `Custom.xaml` style page, so it's a little bit complicate to find the target object.

This is the code:

```
<DataTemplate x:Key="EntryDataTemplate">
    <Grid Padding="5,10,10,10"
              BorderThickness="0,0,0,1"
              Background="{ThemeResource EntryBackground}"
              BorderBrush="Black"
              x:Name="EntryGrid">
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="Auto" />
        </Grid.RowDefinitions>
        <Grid.ColumnDefinitions>
            <ColumnDefinition Width="Auto" />
            <ColumnDefinition Width="*" />
            <ColumnDefinition Width="Auto" />
        </Grid.ColumnDefinitions>

        <FlyoutBase.AttachedFlyout>
            <Flyout>
                <TextBlock Text="copied to clipboard"
                                  x:Uid="CopiedToClipboard" />
            </Flyout>
        </FlyoutBase.AttachedFlyout>

        <interactivity:Interaction.Behaviors>
            <core:EventTriggerBehavior EventName="Tapped">
                <behaviors:ConditionalAction LeftValue="{Binding SelectionMode, ElementName=GridView}"
                                             RightValue="{Binding Converter={StaticResource NullToNoneSelectionModeConverter}}"
                                             Operator="EqualToRight">
                    <core:InvokeCommandAction Command="{Binding CopyKeyCommand}" />
                    <behaviors:OpenFlyoutActionEdited/>
                    <behaviors:TimeoutAction Milliseconds="1000">
                        <behaviors:CloseFlyoutAction/>
                    </behaviors:TimeoutAction>
                </behaviors:ConditionalAction>
            </core:EventTriggerBehavior>
        </interactivity:Interaction.Behaviors>

    </Grid>
</DataTemplate>
```

The problem here is that the `Flyout` should be shown near the element grid, so near the `EntryGrid` element, but I can't seem to be able to set that one as `TargetObject`.
i also have the same issue on the `CloseFlyoutAction` since I need to set the same `TargetObject`.

**Comment by JerryNixon** [comment]
Funny, but I corrected the error in the standard scenario. A template in a disconnected dictionary isn't going to be able to reference another element outside of it's immediate scope. Though your original question was a good one, I think you're a little stuck now if you leave your templates in a dictionary. That being said, you might be able to accomplish what you are wanting in some other way. Try setting the TargetObject to the TextBlock inside the Flyout.

**Comment by Gh0s7** [comment]
I can't really move from the dictionary because it's a shared style used on multiple pages, so I can't edit all the pages everytime I need to modify it.

By the way, I might be wrong but I'm failing in setting `TargetObject` to the `TextBlock`.
I've given the `TextBlock` a name and I'm trying to bind it using `ElementName` but it throws an exception saying 

> Unable to cast object of type 'Windows.UI.Xaml.Data.Binding' to type 'Windows.UI.Xaml.Controls.Control'.

**Comment by Gh0s7** [comment]
I think I've found another way to solve this:
in `ConditionalAction` you call `Interaction.ExecuteActions(this, Actions, parameter);` to execute each sub-action, but this line passes the `ConditionalAction` as sender, giving a "wrong" sender to all the sub-actions.

I've changed it to `Interaction.ExecuteActions(sender, Actions, parameter);` and now it works, the sub-actions receive the correct sender and I don't need to use the `TargetObject` property.

**Comment by JerryNixon** [comment]
This was a global error. Thank you for identifying it.
