### ISSUE TITLE
v1.1.10 - HamburgerMenu is closed when it should be opened

### ISSUE THREAD

**Issue by mitkodi** [Windows-XAML/Template10#864]
After upgrading to v1.1.10 the HamburgerMenu is not always open when the window's width is greater than VisualStateWideMinWidth.

(I have the same behavior with "Search (and Login)" sample from GitHub.)

**Comment by JerryNixon** [comment]
Confirmed.

**Comment by mitkodi** [comment]
I think that in **VisualStateWide** **ShellSplitView.DisplayMode** should be set to **Inline** instead of **CompactInline**.

**Comment by JerryNixon** [comment]
We'll get this fixed. Should you figure it out, a PR is welcome.

**Comment by dg2k** [comment]
Just delete Line 322 of [HamburgerMenu.xaml.cs](https://github.com/Windows-XAML/Template10/blob/master/Template10%20%28Library%29/Controls/HamburgerMenu.xaml.cs#L322).

~~Can do PR if required~~ -- which I've just done as PR #869.
