### ISSUE TITLE
HamburgerButtonInfo.Visibility doesn't work if ButtonType=Command

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [Windows-XAML/Template10#865]
When setting ButtonType to Command visibility isn't changed depending on Binding.
When removing ButtonType -- everything works. Unfortunately, it's essential for Command to be removed when needed.

**Comment by JerryNixon** [comment]
Not good. Not at all.

**Comment by Viachaslau-Zinkevich** [comment]
Added repro, just tap primary buttons to see that Secondary toggle appears, and secondary command doesn't.
[HumburgerButtonInfoTest.zip](https://github.com/Windows-XAML/Template10/files/233011/HumburgerButtonInfoTest.zip)

**Comment by schuettecarsten** [comment]
Just an **untested** idea, maybe there is a Mode=OneWay missing in HamburgerMenu.xaml.cs, line 218, at the binding for Visibility of the Button in NavCommandButtonTemplate.

```
Visibility="{x:Bind Visibility}">
```

should be

```
Visibility="{x:Bind Visibility, Mode=OneWay}">
```

**Comment by Viachaslau-Zinkevich** [comment]
Thanks, @carstenschuette !
@JerryNixon It looks like that was the reason. I changed it to test and it worked.

**Comment by JerryNixon** [comment]
Resolved in NuGet preview package. Can you test?

**Comment by Viachaslau-Zinkevich** [comment]
@JerryNixon it seams to be working correctly
