### ISSUE TITLE
HamburgerMenu and custom style

### ISSUE THREAD

**Issue by mitkodi** [Windows-XAML/Template10#866]
I'm binding **HamburgerMenu.NavButtonCheckedIndicatorBrush** in xaml but it doesn't have effect because of **HamburgerMenu.RefreshStyles** which overrides it. What about setting properties in RefreshStyles only if **ReadLocalValue** is **DependencyProperty.UnsetValue**?

**Comment by JerryNixon** [comment]
Another great PR. Test it carefully though. :)
