### ISSUE TITLE
Why dependency for Newtonsoft.Json?

### ISSUE THREAD

**Issue by johanlindfors** [Windows-XAML/Template10#87]
Because of the dependency on Newtonsoft.Json this library can't be used from a Universal XAML application built with C++. Wouldn't a solution leveraging the Windows.Data.Json namespace be sufficient?

**Comment by JerryNixon** [comment]
There's no goal for Template 10 to support, C++, to be honest. After all, the T10 library is a .NET assembly, not a Windows Runtime Component - nothing about the T10 library is ready for C++. A WinMD would considerably dilute the capabilities of the library, too. I am not arguing that a C++/CX app is viable. It's just that Template 10 is really targeting the 80% of developers. C++ is certainly the top 10% of developers. It's going to be a lot of sacrifice and discipline to keep T10 focused on _most_ solutions and not all of them. I am open to discuss this, so I will not close your question just yet. But does what I am saying make sense? At least at this moment, T10 is a library for _most_ XAML+.NET apps.

**Comment by nguyenquyhy** [comment]
@JerryNixon I am really happy that Template10 is a C# library, not a WinMD component. We have several projects with UWP; not all of them can use Template10 as some need extensive customization on many areas, but all of them can utilize parts of Template10 C# code. We have also learned a lot from the way Template10 handles things. Making it a WinMD component would alienate lots of developers using the good old Windows 8.1 C#/XAML templates.

**Comment by JerryNixon** [comment]
Not only that, it would make it harder to build T10. That being said, I could see in the future a secondary library called something like Template10.WinMD but that's only a dream at this point.

Thanks for your comment. I hope it makes sense the direction we are going. And I hope you jump in and contribute/test the library. The more the merrier!
