### ISSUE TITLE
XYFocus support on HamMenu

### ISSUE THREAD

**Issue by mitchcapper** [Windows-XAML/Template10#870]
#678 is locked but for that target but you may want to add to the list XYFocus obedience. I am fairly sure what the library does right now with just calling FocusRight for example doesn't obey it (from the build talks I believe XYFocus handling essentially handles any unhandled key events so it would not be obeyed with the key handling code in there now).

The fix for this would be pretty simple all we need to do is check on the outer UserControl and if XYFocusRight is set and we are escaping we just move to that element (its a direct element binding so calling focus should do it).

Of course we should do it for focus left also but otherwise it should be pretty simple.  Happy to put a PR in for it. One item to note, it seems binding to XYFocus\* elements on builds < 14295 will crash (so an app with a maximal target of 14295 and minimum of 10420) will allow specifying XYFocus\* in the xaml, but then if run on < 14295 will crash. Of course as long as the user doesn't bind XYFocus\* I would assume we can do it at a library level without it crashing on < 14295 so it should be no different than other controls.

**Comment by JerryNixon** [comment]
You might want to verify this first. I was concerned about this in the context of Xbox and was chatting with the platform team. They pulled up the internal implementation and verified the previously-private XY logic referenced by Template 10 correctly maps to the underlying API. This doesn't mean you are wrong, but I'm already using the XY logic in the current code base for Template 10. Is there a specific change you are considering? Do you know something I do not know?

**Comment by mitchcapper** [comment]
Yeah the T10 focus direction is just fine.  The problem is the new XYFocus variables allow the user to specify the next element to get focus in that direction, and I don't think the T10 code would take this override into account (so FindNextFocusableElement I don't think returns the override if XFFocus is set).  I will test on the xbox to confirm this.

**Comment by mitchcapper** [comment]
This is low priority but should probably be re-opened.
I have tested this on an xbox and can confirm that setting XYFocus is ignored by HamMenu.  
For example on MainPage.xaml.cs you could do something like:
Shell.HamburgerMenu.XYFocusRight = btn_test;
expecting that when someone hits right on the HamMenu it will send them to btn_test next.

This would be relatively easy to fix, if the user hits left or right,  then we should just check main control to see if XYFocusLeft/Right is set, if so we move to that rather than the item in that direction that has focus (assuming not in horizontal secondary buttons not at the end). 

This obviously can wait to be a part of #678

**Comment by JerryNixon** [comment]
Let's verify this again.

**Comment by JerryNixon** [comment]
I will add this to Anniversary updates.

**Comment by JerryNixon** [comment]
@mitchcapper have you tested on Xbox at all?

**Comment by mitchcapper** [comment]
Sorry I am in Europe for several weeks I will re-test when I get back and have access to a dev-xbox.  It is pretty easy to test with the case I mention above however.

**Comment by JerryNixon** [comment]
Xbox will need to be a v-next otherwise we'll wait too long to deliver

**Comment by JerryNixon** [comment]
Out of scope
