### ISSUE TITLE
Application not restored properly after suspension

### ISSUE THREAD

**Issue by pekspro** [Windows-XAML/Template10#871]
I created a new projected based on the Minimal Template 10 template (version 1.1.10). Then I run the application (without any changes), clicks on the submit button to navigate to the detailed page.

Then in Visual Studio I use Lifecycle events -> Suspend and shutdown to emulate termination. Next time when I run the application I expect it be back on the detailed page, but instead is launch the ordinary start page. Is this intended? I’m pretty sure it has worked like this in some older version.

**Comment by codeashoby** [comment]
It seems to me as well that something is not working with state restoration. The parameter on the main page if changed is supposed to be restored as well, but it is not. The value is stored in Dictionary `suspensionState`in `OnNavigatedFromAsync`, but by some reason the dictionary is passed empty to `OnNavigatedToAsync`when resuming from termination.

**Comment by devinfluencer** [comment]
Is this a regression? I created a new app based on the minimal template, started and entered a value, ended the app. Upon restart state was empty.
I checked versions, upgraded template10 library to 1.1.11 and 1.1.12-preview, but to no avail.
The main app I'm working on has the same problem.
