### ISSUE TITLE
Disable Template 10 default resume-behavior

### ISSUE THREAD

**Issue by 1iveowl** [Windows-XAML/Template10#876]
I'd like to send the user back to an Overview Page if the user have been away from the App more than 10 minuttes. 

My code in App.cs looks something like this:

``` csharp
public override void OnResuming(object s, object e, AppExecutionState previousExecutionState)
{
    base.OnResuming(s, e, previousExecutionState);
    if (previousExecutionState == AppExecutionState.Terminated)
    {
        var hasBeenAwayForSomeWhile = (DateTime.UtcNow - RetrieveDateTimeLocal("StartAwayTimer")).TotalMinutes > 10;

        if (hasBeenAwayForSomeWhile)
        {
            NavigationService.Navigate(Pages.OverviewPage);
        }
    }
}
```

Except that it doesn't work. Instead of going to the Overview Page after a suspend/terminate the user is returned to whatever page they where at before the suspend/terminate???

I've been spending the past three days on this and it's driving me nuts. What am I missing? 

And yes `hasBeenAwayForSomeWhile` is returning true after ten minutes and `NavigationService.Navigate(Pages.OverviewPage)` is being executed, it just doesn't seem to do anything?!

I've also tried to Control the flow from ShellViewModel.cs. Same negative result.

**Comment by 1iveowl** [comment]
This seems to do the trick: `NavigationService.FrameFacade.ClearFrameState();` 

Probably because Overview Page is the default landing page for the App. Is this the "right" way to do it, or?

``` csharp
public override void OnResuming(object s, object e, AppExecutionState previousExecutionState)
{
    base.OnResuming(s, e, previousExecutionState);
    if (previousExecutionState == AppExecutionState.Terminated)
    {
        var hasBeenAwayForSomeWhile = (DateTime.UtcNow - RetrieveDateTimeLocal("StartAwayTimer")).TotalMinutes > 10;

        if (hasBeenAwayForSomeWhile)
        {
            NavigationService.FrameFacade.ClearFrameState();
        }
    }
}
```

**Comment by JerryNixon** [comment]
That is the right way to do it. But I can see that it is not very intuitive. I wonder if we should have an e.Handled passed to that method that would make it so resume does not continue. Something like that. What do you think?

**Comment by JerryNixon** [comment]
Planning on something like:

```
bool BootStrapper.EnableAutoRestore (default = true)
```
