### ISSUE TITLE
Creating a new Hamburger app has missing ApplicationInsights NuGet packages

### ISSUE THREAD

**Issue by SandipAhluwalia** [Windows-XAML/Template10#879]
When I create a new Hamburger app using Template 10 Template Pack version 1.17, it has missing Microsoft Application NuGet packages:

The project.json file looks like:

```
{
  "dependencies": {
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.1.0",
    "Microsoft.Xaml.Behaviors.Uwp.Managed": "1.1.0",
    "Newtonsoft.Json": "8.0.3",
    "Template10": "1.1.*"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```

The above cause build errors like:

> Error CS0234  The type or namespace name 'ApplicationInsights' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)   T10HamburgerApp2    c:\users\win10builduser\documents\visual studio 2015\Projects\T10HamburgerApp2\T10HamburgerApp2\App.xaml.cs 21  Active

Has anyone else seen this issue? I suspect I can modify the project.json file to restore what I need, but I don't know which versions of the required NuGet packages work together.

I wanted to do this to inspect the new version of the Template10 library (1.1.10) in a fresh clean app. Note: the above action installs 1.1.0 out of the box, which I guess can be manually updated in the NuGet Package Manager, but why doesn't it install 1.1.10?

**Comment by mitchcapper** [comment]
Yeah I would assume Microsoft.NETCore.UniversalWindowsPlatform or Microsoft.Xaml.Behaviors.Uwp.Managed (I forget which has that dependency) should have that properly flagged so it installs next to it.  But for some reason it does not.   It (I believe) is a bug with those packages not template10 as template10 doesn't use ApplicationInsights.

**Comment by SandipAhluwalia** [comment]
So in the Template10 project templates, it uses ApplicationInsights in the App constructor, so my understanding is that it should include those NuGet packages its project.json file?

**Comment by mitchcapper** [comment]
Can you point to exactly what code you are looking at?
I searched all the code from master and couldn't find ApplicationInsights mentioned in any of it minus the installer, and looking at App.xaml.cs for a few of the templates I don't see anything that looks telemetry related?

I don't use AppInsights much so maybe I am missing the accessor but I am missing it.

**Comment by SandipAhluwalia** [comment]
When you create a new Template 10 Hamburger app as a example (and have the "Show telemetry in the Windows Dev Center" checked), it adds the following to the App.xaml.cs constructor:

```
Microsoft.ApplicationInsights.WindowsAppInitializer.InitializeAsync(
                Microsoft.ApplicationInsights.WindowsCollectors.Metadata |
                Microsoft.ApplicationInsights.WindowsCollectors.Session);
```

Now, I am not sure if this is a Template10 issue with the project templates or not because when I create a blank UWP app with the check box ticked, it correctly adds the NuGet ApplicationInsights packages.

**Comment by mvermef** [comment]
Yep I see this.. It's a "configuration feature" of the new -> project  wizard-> "Show Telemetry" is an optional item.  I can see how this would frustrate when the option selected doesn't force the necessary project.json references into the dependency collection.  I would chalk this up as T10 not reacting to a configuration

**Comment by JerryNixon** [comment]
You have to un-check Telemetry when you create the project. Otherwise, you get that injected - which is pretty stupid, huh? Because Application Insights no longer supports UWP apps. This will almost certainly come up again.
