### ISSUE TITLE
SettingsPage created twice if open via ellipses menu

### ISSUE THREAD

**Issue by TrevorBarstowTT** [Windows-XAML/Template10#880]
Using the Hamburger template unchanged, there is a behaviour discrepancy in navigation to SettingsPage. 

When click on Hambuger Settings a single SettingsPage is created. 
When click on Settings from ellipses menu i.e. PageHeader.SecondaryCommands the SettingsPage constructor is called twice.

project.json dependencies:
  "dependencies": {
    "Microsoft.ApplicationInsights": "1.0.0",
    "Microsoft.ApplicationInsights.PersistenceChannel": "1.0.0",
    "Microsoft.ApplicationInsights.WindowsApps": "1.0.0",
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.0.0",
    "Microsoft.Xaml.Behaviors.Uwp.Managed": "1.0.3",
    "Newtonsoft.Json": "8.0.2",
    "Template10": "1.1.8"
  },

**Comment by JerryNixon** [comment]
Yes. Yes, it is. Who cares?

**Comment by JerryNixon** [comment]
Nothing more?

**Comment by TrevorBarstowTT** [comment]
Looks like it is fixed now in latest version. Thanks

  "dependencies": {
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.1.0",
    "Microsoft.Xaml.Behaviors.Uwp.Managed": "1.1.0",
    "Newtonsoft.Json": "8.0.3",
    "Template10": "1.1.*"
  },
