### ISSUE TITLE
Upgrading from 1.1.4 to 1.1.10 fails with duplicate value error

### ISSUE THREAD

**Issue by SindreSB** [Windows-XAML/Template10#881]
After updating to 1.1.10 from 1.1.4 I get this(see picture) error. No clue what is causing it, but reverting to 1.1.4 fixes it. 

<img width="397" alt="makepir error" src="https://cloud.githubusercontent.com/assets/11072936/14827103/1662874e-0be1-11e6-9738-e0a6b11696ac.PNG">

**Comment by mitchcapper** [comment]
did you try a complete clean rebuild after upgrading?

**Comment by SindreSB** [comment]
yes, clean and complete rebuild of the solution.

**Comment by JerryNixon** [comment]
Not sure why we aren't getting the same error as you.

**Comment by JerryNixon** [comment]
Nothing more?
