### ISSUE TITLE
PR #857 should revert

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#882]
@JerryNixon - I think PR #867 just merged should revert. The display mode should stay **CompactInline** rather than **Inline**. I suspect **Inline** was suggested as a workround for a problem that seem to go away with Inline display mode but this is not the case. In fact, this introduces a new host of problems. My own PR #869 solves the problem #867 refers to. HM never used Inline, so why use now?

**Comment by JerryNixon** [comment]
Stupid thing to do.
