### ISSUE TITLE
Windows 10 Mobile - HM Flash, first use.

### ISSUE THREAD

**Issue by mvermef** [Windows-XAML/Template10#885]
Visible HM flash on first click attempt... I am not sure were to begin on this one..  It might be related to the Binding issue, but doubt that since it is not on the actual HM but the HMButtonInfo inside the Primary causing that...

**Comment by alexdresko** [comment]
I see this as well when I set the first page to anything other than MainPage. If I set the first page to SettingsPage, clicking on the HM the first time flashes the HM and keeps me on the SettingsPage. The second time I click on the HM, it opens properly. Happens every time I start the app.

**Comment by mvermef** [comment]
1.1.11-beta package appears to correct this issue.
