### ISSUE TITLE
T10_PageContent.snippet: Missing or unspecified Language attribute

### ISSUE THREAD

**Issue by schuettecarsten** [Windows-XAML/Template10#893]
The error "T10_PageContent.snippet: Missing or unspecified Language attribute" is shown in Output window when VS2015 starts.

![2016-04-28 12_25_49-maxdome uap10 - microsoft visual studio administrator](https://cloud.githubusercontent.com/assets/1275166/14883069/6265fffc-0d3c-11e6-8b14-4b49f7b9035d.png)

**Comment by JerryNixon** [comment]
Care to submit a pr?
