### ISSUE TITLE
Snippets not working

### ISSUE THREAD

**Issue by alexdresko** [Windows-XAML/Template10#894]
Okay, I'm finally tired of copy/pasting my existing code and the T10 snippets aren't working. 

Proof I've got the extension installed... Is there anything else I need to do? How can I validate the snippets are installed or manually install them? 

![image](https://cloud.githubusercontent.com/assets/333022/14897959/5bd73f50-0d52-11e6-8380-403c8b842504.png)

**Comment by alexdresko** [comment]
Ah, I found the snippets in the repo, as well as InstallSnippets.cmd.. running that manually installed the snippets. Is that the correct process? I'll be happy to update the wiki with instructions if so.

**Comment by JerryNixon** [comment]
Thank you for offering, please do. It would be a help.
