### ISSUE TITLE
Progress with  PR #781

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#895]
@o0rebelious0o - don't know if I missed the progress with #781, whatever happened with the proposed PR? I'm really keen to see the proposed tooltip implementation. Sorry if I missed something obvious as I wasn't following up as much as I liked to couple of weeks ago.

**Comment by rcbevans** [comment]
Yeah, sorry, I'm not really sure what happened on it, been a bit distracted the past couple of weeks.  I'm older and wiser now, so will take a look at it with fresh eyes, and with the current state of the code and see what we can do :)

**Comment by dg2k** [comment]
Thank you.
