### ISSUE TITLE
The Road to 1.1.11

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#896]
Hey, @Windows-XAML/contributors 

Announcing the release of  1.1.11-preview-160428 into NuGet.
If you use the preview and report a bug, please indicate the Preview number.
Small comments on the preview can be appended to this issue.

// Jerry

**Comment by mvermef** [comment]
so far so good... still working on behaviors and triggers... no more runtime binding errors at present

**Comment by mvermef** [comment]
Having an issue with MasterDetail and nested ListView inside of a SematicZoom, unless I am not sure of binding for this VisualState, throws an absolute fit about not having the requested state on the ListView, it is a global to the page, exactly as the sample is, guessing this is more of an SO style question but no one seems to have anwwer yet.
