### ISSUE TITLE
Does TargetObject on FocusAction really work?

### ISSUE THREAD

**Issue by devinfluencer** [Windows-XAML/Template10#900]
Jerry,
using ver. 1.1.10 from Nuget, I get an InvalidCastException running the following XAML:
`<PasswordBox Grid.Row="1" x:Name="pb" Password="{Binding Password1, Mode=OneWay}" PasswordRevealMode="Peek">
         <Interactivity:Interaction.Behaviors>
            <Behaviors:KeyBehavior Key="Enter">
                  <Behaviors:FocusAction TargetObject="{Binding ElementName=pb2}"/>
            </Behaviors:KeyBehavior>
         </Interactivity:Interaction.Behaviors>
      </PasswordBox>
`
I get 

> Unable to cast object of type 'Windows.UI.Xaml.Data.Binding' to type 'Windows.UI.Xaml.Controls.Control'

Is there a bug in my XAML or is you TargetObject implementation faulty? Do I misunderstand usage?
-Thomas

**Comment by dg2k** [comment]
Sorry what I suggested earlier was from memory which I think is wrong. I did use this to focus to a textbox ... let me check ...

Sorry I couldn't help - I never used with TargetObject; just nested in TextBox and it worked. I can see putting somewhere else and referring to the target.

Update:
@devinfluencer - I have checked this, and 'TargetObject' needs to be a Dependency Property. When I made this correction it works with the Binding as you attempted. I will post a pull request for this.

**Comment by devinfluencer** [comment]
XamlCompiler error WMC0055: Cannot assign text value 'pb2' into property 'TargetObject' of type 'Control'

**Comment by dg2k** [comment]
See my latest comment.
If TargetObject is changed to a DP, your first code with binding works. I have tested it.

**Comment by devinfluencer** [comment]
Yes, I assume that. That's what my pull request #773 proposed.

**Comment by dg2k** [comment]
I didn't know you made a PR as we're discussing under Issues category rather than pull-request.  I will have a look at PR #773.

Okay, I see now. What you proposed in PR #773 was correct.

Your hyperlink above is wrong and please correct it. Just type **#** followed by **773** in plain text and the editor will take care of it, rather than type in the URL.

**Comment by devinfluencer** [comment]
Thanks, I didn't know that.
So what are we doing now?

**Comment by JerryNixon** [comment]
To support certain binding scenarios, I have changed them to propdp. Thanks for the report.
