### ISSUE TITLE
Define setter in Styles/Custom.xaml for themes not working properly for HamburgerButtonInfo item?

### ISSUE THREAD

**Issue by jp-weber** [Windows-XAML/Template10#901]
If I define in Custom.xaml different colors for themes of HamburgerMenu(HamburgerButtonInfo ->NavButtonForeground etc.), they will not change after theme change.

Only when hovering over the elements, the color is displayed correctly.

For testing I define the foregrounds of the elements in dark theme red and in light theme green. You see, the HamburgerForeground works in the test.

![colorchange](https://cloud.githubusercontent.com/assets/10946850/14941922/e6f54778-0fad-11e6-91e7-97579dc861f5.png)

**Comment by dg2k** [comment]
PR #897 will fix this problem.

**Comment by jp-weber** [comment]
But the changes of the three file changes are not all? I saw in your sample a lot of changes in Shell.xaml.cs etc. In total it is to comprehensive?
And so more a big great workaround?

**Comment by dg2k** [comment]
What is done in Shell.xaml.cs is up to the developer and that is not a fix, rather theme updating during runtime. That is, if you change themes in Shell.xaml.cs, the fix proposed in this PR allows it to work. What I showed in Shell.xaml.cs is simply a complete theme programming based on \Styles\Custom.xaml. You can do a subset of it or none at all.

**Comment by JerryNixon** [comment]
Can you recreate with the current NuGet preview?

**Comment by jp-weber** [comment]
The issue still exist in preview-160506. After theme change, the HamburgerButtonInfo don't change the color, except for the interaction(hover over, click, etc), after interaction the color is applied correctly.

After my tests I think the problem Is the way how we Bind the color in VisualState. The complete solution works from dg2k, but if we change the "NavToggleButtonTemplate" how in the past etc.it should be work wonderful, and that without a lot of code changes.

current HamburgerMenu.xaml:

```
<VisualState x:Name="Normal">
  <VisualState.Setters>
        <Setter Target="ContentPresenter.Foreground" Value="{Binding NavButtonForeground, ElementName=ThisPage}" />
        <Setter Target="ContentPresenter.Background" Value="{Binding NavButtonBackground, ElementName=ThisPage}" />
   </VisualState.Setters>
</VisualState>
```
