### ISSUE TITLE
HamburgerMenu.IsFullScreen resets media element position

### ISSUE THREAD

**Issue by mitchcapper** [Windows-XAML/Template10#903]
Not sure if related to #735 or not but add a mediaelement to page, set the source to a file and have it playing.  set IsFullScreen and the position will go back to 0 (and rebuffering).

For example a sample toggle button of:

```
        private void Btn1_OnClick(object sender, RoutedEventArgs e) {
            var view = ApplicationView.GetForCurrentView();
            bool go_fs =! view.IsFullScreen;
            if (go_fs)
                view.TryEnterFullScreenMode();
            else
                view.ExitFullScreenMode();
            Shell.HamburgerMenu.IsFullScreen = go_fs;
        }
```

settings just visibility does not cause the issue.

**Comment by mitchcapper** [comment]
Given the fact the frame detaching is probably not avoidable creating a way to just Hide the menu is probably the best option (MenuVisibility)? interested in thoughts.

**Comment by mitchcapper** [comment]
MediaElement itself however is able to transition to its new root item FullWindowMediaRoot without the issue, so it should be possible.

**Comment by JerryNixon** [comment]
We want to resolve this. But I will not chase the solution for some time as this is an edge case. It's still important. @mitchcapper can you suggest a solution?

**Comment by mitchcapper** [comment]
Well I see two solutions:
A) The easy solution is to just hide away the menu by allowing the user to control the visibility of the entire pane.
B) Figure out how the heck MediaElement does it;0 (harder as its a native control)

One other slightly interesting thing,  If you use the MediaElement native FS button and then toggle the T10 isFullscreen state when it changes, it actually can cause an issue causing mediaelement to not be able to exit fullscreen (I am guessing a race condition where on re-attach mediaelement sees if its FS and re-fullscreens before it completed exiting fullscreen mode).

**Comment by mitchcapper** [comment]
If A is of interest I can probably put together a PR with the additional binding, would need to make sure the visual states don't override the width.

**Comment by JerryNixon** [comment]
Okay. Resolved in current GitHub code. I will update a preview NuGet package.

**Comment by mitchcapper** [comment]
I'm curious which commit?

**Comment by mitchcapper** [comment]
nevermind it must not have pushed before.

**Comment by mitchcapper** [comment]
Sadly does not actually seem fixed. To repro just add a mediaelement to a page and start playing a file, then have a button (or intermediate window) set `Shell.HamburgerMenu.IsFullScreen = true;` and it will reset the entire stream (if the stream is buffering from a remote source it will have to rebuffer).
