### ISSUE TITLE
Theme not selecting on startup

### ISSUE THREAD

**Issue by WozSoftware** [Windows-XAML/Template10#905]
I have created the default burger menu app, no changes to source and the theme does not appear to work correctly.

I selected dark in the settings then close the app. When I re-open dark is loaded from the settings but the app displays light until you toggle back to light then dark again

**Comment by mvermef** [comment]
What is the RequestedTheme in the App.xaml?

**Comment by WozSoftware** [comment]
The theme in question is Dark. I can see the theme name load from the settings and get pushed into place at startup but it does not take. To recreate:

1) Run app (Starts in default Light theme)
2) Select Dark (Theme takes as expected)
3) Exit app
4) Run app (Dark is loaded from settings and appears selected in settings but app is using Light)

I am on latest release build of Win 10 (Not insider) and latest updates to VS.

The only code I chopped was the initial Azure setup as I do not have that SDK loaded. If you cant reproduce let me know and will e mail a zip of the code when I get home later tonight

**Comment by WozSoftware** [comment]
Out of interest, the code I chopped was the Insight stuff at the start of app. 

This relates to the following issue in the issues list "Error CS0234 when building Template 10 templates"

I will re-create the template tonight and try this workaround and see if this has any effect

**Comment by MichaelPetrinolis** [comment]
Just remove the requestedtheme from app.xaml, as @mvermef mentioned.

**Comment by WozSoftware** [comment]
Only ref to it is in code behind

RequestedTheme = _settings.AppTheme;

No change if commented. I assume this should trigger the change to last settings theme?

**Comment by MichaelPetrinolis** [comment]
If there is a RequestedTheme setting in App.xaml , it overrides your RequestedTheme = _settings.AppTheme; line in the constructor. 
If there is no RequestedTheme="Light" in your app.xaml file declaration, then you have another issue.

**Comment by WozSoftware** [comment]
Right, just created a new project for hamburger and pulled in the insight stuff to json file so that builds correctly

Have not touched the source at all and run the same test. Same issue. Went into settings and selected Dark, it goes dark. Close app and run again and Dark loads from settings and set into Requested but display is light.

This is clean just generated code with 0 changes. Are you saying if you do the same the issue is not present?

**Comment by MichaelPetrinolis** [comment]
By default the app.xaml file is created like this
<common:BootStrapper x:Class="WindowsApp2.App"
                     xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                     xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                     xmlns:common="using:Template10.Common"
                     RequestedTheme="Light">

just remove the RequestedTheme="Light" from xaml and try to reproduce

**Comment by WozSoftware** [comment]
aaaarrgh, how did I miss that :(

Sorry for that, I will close this down now
