### ISSUE TITLE
Making T10 more Design Time Safe

### ISSUE THREAD

**Issue by mitchcapper** [Windows-XAML/Template10#907]
#904 brought this up a bit, so I figured I would create a separate issue.

Right now there are several T10 calls that are not design time safe (will crash the designer).   These largely resolve around the window wrapper, dispatacher, and some of the sample codepaths.  In addition methods like onnavigatedto never fire in design time (which VM may be expecting).    The question is how far do we want to go to try and fix this, and where should the hacks be put.  For example, as there is no window / dispatcher to grab in design time anything trying to access these things fails.   The isbusy setter in the template for example if called (say by a VM) will crash as it uses dispatcher.   

Most things could probably be worked around at an app level rather than a library level for example (although that's more painful for the developer).  It does keep the library much cleaner.    

On the otherhand should a dispatcher call detecting its running in the designer just avoid trying to check the thread and run the action as is (as it could be forced onto the background thread and people may not expect that code to just run it).

Tracking most issues down is fairly doable but debugging the designer, some at launch things are not as easy but most of the on launch code is also not run in the designer.

**Comment by callummoffat** [comment]
I like this idea. T10's job is to make the developer's life easier, and I find that design time data is a godsend. Definitely much of this should be considered.

Configuring the Dispatcher to run methods as is when in design mode doesn't seem too costly. It wouldn't have much of an impact on the complexity of the code (to my knowledge), and it makes life easier.

**Comment by JerryNixon** [comment]
@mitchcapper let's get a list of calls and let's resolve them. Start a new issue.
