### ISSUE TITLE
Convert templates to use x:bind instead of Binding?

### ISSUE THREAD

**Issue by alexdresko** [Windows-XAML/Template10#910]
Any reason not to create a PR that converts the templates to use `x:bind` instead of `Binding`? There are 15 instances of `Binding` in the HM template, for example. I've successfully converted all of them to `x:bind` except for the two in `splash.xaml`, but I'm not smart enough to figure those out.

**Comment by alexdresko** [comment]
Regarding splash.xaml... I don't know if those bindings are wired up properly as is. If you search the repo for `mycanvas`, this is what it finds..  

![image](https://cloud.githubusercontent.com/assets/333022/14987764/c992cee0-111e-11e6-9c83-b2354de181cc.png)

Check out the splash.xaml files in the templates, specifically. There's no element named `mycanvas`. 

That's potentially a different issue altogether, but it might mean that we can do away with those bindings at least.

**Comment by dg2k** [comment]
One limitation of **x:Bind** is that it doesn't support binding attributes such as **ElementName** which the binding in **Splash.xaml** is using, hence why x:Bind doesn't work in this case.

See comparison between dynamic and classical binding [here on stackoverflow](http://stackoverflow.com/questions/33848334/how-does-xbind-compare-with-the-classical-binding-put-as-concisely-as-possible).

**Comment by darenm** [comment]
Don't forget though that x:Name creates an instance variable in the View which is in scope for x:Bind:

```
    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
        <Canvas x:Name="MyCanvas"
                HorizontalAlignment="Stretch"
                VerticalAlignment="Stretch">
            <Viewbox x:Name="MyImage"
                     Width="{x:Bind MyCanvas.ActualWidth, Mode=OneWay}"
                     Height="{x:Bind MyCanvas.ActualHeight, Mode=OneWay}">
                <Image Source="/Assets/SplashScreen.png"/>
            </Viewbox>
        </Canvas>
    </Grid>
```

**Comment by JerryNixon** [comment]
How has nobody discovered this yet?

![snip_20160505122510](https://cloud.githubusercontent.com/assets/1749983/15052774/751cb8e0-12bc-11e6-91af-880ac7234fae.png)

That certainly has legacy code errors. This is better:

![snip_20160505122446](https://cloud.githubusercontent.com/assets/1749983/15052773/751b2098-12bc-11e6-8af5-97bcc9f46396.png)

**Comment by JerryNixon** [comment]
As for the errors in the Samples, those just need to be cleaned up over time.

**Comment by JerryNixon** [comment]
Splash has been corrected.
