### ISSUE TITLE
Fullscreen Hamburger Menu shows incorrectly on Narrow state

### ISSUE THREAD

**Issue by Gh0s7** [Windows-XAML/Template10#915]
Space left by the hidden hamburger button is not filled by the `PageHeader` like in the other states, so it's just left empty while still keeping its space.

I'm on version 1.1.10, latest NuGet available today.

**Comment by mvermef** [comment]
working as expect I would suspect you are missing this VisualStateNarrowMinWidth="-1" on the page in question inside the PageHeader

**Comment by JerryNixon** [comment]
@Gh0s7 you're going to need to submit some code and a screenshot so we understand.

**Comment by JerryNixon** [comment]
Nothing more? Perhaps this is resolved with NuGet preview.
