### ISSUE TITLE
Error CS0234 when building Template 10 templates.

### ISSUE THREAD

**Issue by syaifulnizamyahya** [Windows-XAML/Template10#916]
I tried create a new project using Template 10 templates that i install in my visual studio 2015. When i try to build the template, i get this errors.

1>c:\Users\iJam\Documents\Visual Studio 2015\Projects\Template10Hamburger\Template10Hamburger\App.xaml.cs(23,17,23,46): error CS0234: The type or namespace name 'ApplicationInsights' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?)

The same error has been reported in stackoverflow, but not here(afaik).
http://stackoverflow.com/questions/35832195/template-10-error-during-setup-application-insight-does-not-exist-in-namespace

The workaround for this problem is described in the mentioned stackoverflow page.

Add this in project.json file

```
 "Microsoft.ApplicationInsights": "1.0.0", 
 "Microsoft.ApplicationInsights.PersistenceChannel": "1.0.0", 
 "Microsoft.ApplicationInsights.WindowsApps": "1.0.0", 

```

The whole project.json should look something like this

```
{
  "dependencies": {
    "Microsoft.ApplicationInsights": "1.0.0", 
    "Microsoft.ApplicationInsights.PersistenceChannel": "1.0.0", 
    "Microsoft.ApplicationInsights.WindowsApps": "1.0.0", 
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.0.0", 
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.0.0",
    "Microsoft.Xaml.Behaviors.Uwp.Managed": "1.0.3",
    "Newtonsoft.Json": "8.0.2",
    "Template10": "1.1.*"
  },
  "frameworks": {
    "uap10.0": {}
  },
  "runtimes": {
    "win10-arm": {},
    "win10-arm-aot": {},
    "win10-x86": {},
    "win10-x86-aot": {},
    "win10-x64": {},
    "win10-x64-aot": {}
  }
}
```

**Comment by JerryNixon** [comment]
See StackOverflow

**Comment by ileto** [comment]
Can we just add this dependency into Template？Today is my first day on Win dev and spend lots of time on the same issue. Can you explain a little bit why we have this issue and if manually install 2.0 also failed.

**Comment by mvermef** [comment]
its because the checkbox isn't recognized by Template10 during its project generation...
