### ISSUE TITLE
WindowWrapper.Default() suggestion

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [Windows-XAML/Template10#918]
Hi, implementing ShareTarget in my app I found that basically WindowWrapper.Default() may not mean the same everyone expects: it returns just the first window. In case when the first operation was ShareTarget (which is a Hosted, not Main window), calling Default() will return those hosted, probably hidden window. And this will result in problems as such Windows do not allow calling nothing from them when hidden, resulting in ComException with "A COM call to an ASTA was blocked because the call chain originated in or passed through another ASTA. This call pattern is deadlock-prone and disallowed by apartment call control.".
I would suggest to retrieve Default windows as something like this:

`ActiveWrappers.FirstOrDefault(w=>w.Window.CoreWindow == CoreApplication.MainView?.CoreWindow) ?? ActiveWrappers.FirstOrDefault();`

This will at least try to get the MainWindows by default.
Does it make sense?

**Comment by JerryNixon** [comment]
I will close this so you can "suggest" it with a Pull Request.
