### ISSUE TITLE
Setting HamburgerMenu.DisplayMode to Overlay after startup doesn't work

### ISSUE THREAD

**Issue by mitchcapper** [Windows-XAML/Template10#919]
In an effort to work on a work around for #903 I figured setting the menu to overlay would hide it from view, however it seems that adjusting this after startup doesn't work (ie having a button that sets this has no affect).

**Comment by JerryNixon** [comment]
Could you explain more?

**Comment by mitchcapper** [comment]
Doing HamburgerMenu.DisplayMode = SplitViewDisplayMode.Overlay;  for example at runtime wasn't really working, it was part of an attempt to work around the FS bug (although I switched to just a margin solution temporarily) but the new version has this fixed which makes this less of an issue.  Instead of trying to set the display mode should probably have just altered visual states.
