### ISSUE TITLE
Microsoft.Xaml.Interactivity - strongly-named assembly

### ISSUE THREAD

**Issue by bdollerup** [Windows-XAML/Template10#920]
At the risk of exposing my self as a complete and utter noob, what do I need to do in order to install the template 10 version that does not give me the "strongly-named assembly" error with the "Microsoft.Xaml.Interactivity" assembly?

Thanks,
Bjarne

**Comment by mvermef** [comment]
At the moment the only way to get this without strong name is to get the source, turn off strong name and compile your self, and not rely on nuget for the package at all.  Also requires you to add the reference manually to your project

**Comment by bdollerup** [comment]
Ouch.. When will we see a nugget package?

**Comment by JerryNixon** [comment]
Next week.

**Comment by JerryNixon** [comment]
The current NuGet preview resolves this. Please help by testing.
