### ISSUE TITLE
NavigationService DI resolver creates new viewmodel instances on all nav events

### ISSUE THREAD

**Issue by dpakpaul** [Windows-XAML/Template10#921]
In the NavigationService, the Navigate\* and Navigating\* methods call ResolveForPage(). The code for that method I think is missing the following line after calling BootStrapper.Current.ResolveForPage() 

`page.DataContext = viewModel;`

Since the page DataContext isn't set, all the navigation "events" on a given page will create a new viewmodel instance from the overridden Bootstrapper ResolveForPage() if you're using that to DI your viewmodel.

I know one can set the page.DataContext in the Bootstrapper ResolveForPage() override to workaround this, but the NavigationService is probably the right place for this.

**Comment by JerryNixon** [comment]
You are right. Do you want to submit a Pull Request?

**Comment by dpakpaul** [comment]
I can. I'll get to it Monday PST although if there are weekend warriors who
want to do the one line fix, they're welcome to .
