### ISSUE TITLE
Released Template10.1.1.11-preview-160506 to NuGet

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#922]
Hey @Windows-XAML/community 

So, we've updated the preview package. This, primarily, fixes two issues: 1) IsFullScreen now uses PopupRoot so it no longer conflicts with any existing visual tree. And, 2) The package is not strongly-named. Issues specific to the preview can be included here, in this thread. 

Thanks for taking the time to help test this release. Before the final release, we will need to fix 
- [x] 1) Ensure Resume after Suspend+Terminate https://github.com/Windows-XAML/Template10/issues/871 
- [x] 2) Something's wrong with PageHeader in Narrow state. 
- [x] 3) I'm also wanting to resolve https://github.com/Windows-XAML/Template10/issues/921
- [x] 4) Work to make IsFullScreen work with a playing MediaElement

// Jerry

**Comment by Gh0s7** [comment]
Issue number 2 is the one I was talking about in #915 but I didn't have enough time to post a screenshot and I thought it was related to the hamburger since I never tried anything without it.
I've just created a new empty template and the `PageHeader` shifts to right on narrow state.

EDIT: can't test it now, but it may be related to [this line](https://github.com/Windows-XAML/Template10/blob/master/Template10%20%28Library%29/Themes/PageHeader.xaml#L849)

**Comment by mitchcapper** [comment]
Unfortunately this doesn't resolve the media player resetting when changing isFullscreen playback still resets the entire media stream. Running 160506.

**Comment by JerryNixon** [comment]
Well, freaking crap @mitchcapper. Maybe what you need to do is before you change to FullScreen, you remember the position, and after it moves to FullScreen, you set the position again. Not perfect, but changing its position in the visual tree appears to reset the position and we might not have another option.

**Comment by mitchcapper** [comment]
Sorry @JerryNixon.
Two things for thought:
*) The native control creates a new root and re-parents itself without this (and its not faking it either)
*) If we simply create an ability to "hide" the ham-menu (toggle its visibility for that pane) one could implement their own FS easier.

For now I am just using a margin change to shift it over by the width of the nav pane and hide it.  

Storing and restoring the position is what I first thought of but:
*) its fairly disruptive. Audio obviously stops. In addition you see the flash jerk of the position changing.
*) For remote files its fairly devastating.  MediaElement completely re-opens the file, so must re-buffer. To properly do this one must hook the media loaded then update the position and again not super smooth.

I have a work around that works with the margin adjustment, but adding visibility toggle support on HamMenu might be a better option.
