### ISSUE TITLE
Occasional COM Exception E_FAIL when loading HumburgerMenu

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [Windows-XAML/Template10#923]
Hi, just got an exception while loading HumburgerMenu. Don't know if it's a known one, but it's occasional.

System.Runtime.InteropServices.COMException: Error HRESULT E_FAIL has been returned from a call to a COM component.
   at Windows.UI.Xaml.VisualStateChangedEventArgs.get_Control()
   at Template10.Controls.HamburgerMenu.NavButton_VisualStateChanged(Object sender, VisualStateChangedEventArgs e)

**Comment by JerryNixon** [comment]
Hilarious that the event has no logic in it. I wonder if the casting of the control is somehow the culprit. I don't get this error myself, by the way, but I believe you. I will remove the unused method. :)

**Comment by Viachaslau-Zinkevich** [comment]
Thanks, @JerryNixon  :) I can't say it's connected, but I've started seeing a bunch of similar exceptions on production from users after upgrading to v 1.1.10. Perhaps, the reason is the same.

Application Specific Information:
Unspecified error (Excep_FromHResult 0x80004005)

DeviantArt.UWP!<BaseAddress>+0xac461b
DeviantArt.UWP!<BaseAddress>+0xac4fc9
DeviantArt.UWP!<BaseAddress>+0xaccf73
Template10.Controls.HamburgerMenu.NavButton_VisualStateChanged(Object sender, UI.Xaml.VisualStateChangedEventArgs e)
System.Reactive.Concurrency.Scheduler.<ScheduleLongRunning>b__72(Action<System.Reactive.Disposables.ICancelable> a, Reactive.Disposables.ICancelable c)
DeviantArt.UWP!<BaseAddress>+0xbc0543
DeviantArt.UWP!<BaseAddress>+0xac461b
DeviantArt.UWP!<BaseAddress>+0xaccccd
DeviantArt.UWP!<BaseAddress>+0xaccc1f
Microsoft.HockeyApp.Extensibility.Windows.UnhandledExceptionTelemetryModule.CoreApplication_UnhandledErrorDetected(Object sender, ApplicationModel.Core.UnhandledErrorDetectedEventArgs e)

**Comment by Delaire** [comment]
I have the same issue, thanks @JerryNixon
