### ISSUE TITLE
Event for loading ViewModel data on startup?

### ISSUE THREAD

**Issue by Onjay** [Windows-XAML/Template10#925]
What event should I use in my viewmodel to load persistent data when my mainpage initially loads? Both the PageLoaded and OnNavigatedToAsync events will continue to reload the data if the page is navigated away and then back again, and the OnLauched and OnActivated events cannot be used. I have a json file containing some data which the user inputted, and is saved when the user closes the app, but need to be loaded just once when the app is started again.

**Comment by mvermef** [comment]
I have been using a static object that saves and loads from the SettingsService... I then created a baseclass for my viewmodels which also inherits from ViewModelBase from T10, and created a Property which holds a reference to that SettingService property, it is hydrated on startup.  Works quite well..  I am sure there are better ways but for the moment that is how I am doing it... SessionState property might be another solution to this as well..  It is located in the ViewModelBase within T10

**Comment by JerryNixon** [comment]
You should abstract the logic surrounding your data to a dedicated class, something like Services/DataService.cs and in your ViewModel.OnNavigatedTo() call this.Data = service.GetData() every single time, no matter what. Then implement caching inside the DataService.GetData() method, not inside the view-model. Then, you can call and get the data over and over without special logic, and you can call it from other view-models without worrying about caching inside a one (or more) view-model. You were already doing it right with ViewModel.OnNavigatedTo(), but the best pproach is with a repository service like DataService to handle the hard work. The caching, @mvermef is correct, is most easily handled in a static variable/field/property. Doing it this will also allow you to properly handle Resume when you cannot rely on the cache being there, but the DataService can check for that and simply repopulate it. When you navigate to pages in your app, navigate then with only the key that you will feed to the DataService, this also simplifies your workflow and increases your success rate to handle suspending/resume. It's all so easy. I should make some training videos, I see that now.

**Comment by Onjay** [comment]
Thank you for your help. I've used a Setting Service with a singleton before, but this time I was trying to keep it a little simpler and I don't anticipate needing to reuse the data in other viewmodels, so I just used a bool and the OnNavigatedToAsync method to call my Deserializer method. You can find the complete inelegant solution here: http://stackoverflow.com/questions/36994792/how-to-save-and-load-an-observablecollection-on-app-suspend-and-start/37096217#37096217

Next time I'll try abstracting the data out using a Dataservice class like you suggest.

**Comment by JerryNixon** [comment]
Inelegant solutions are still solutions. :)
