### ISSUE TITLE
Settings page doesn't load on new HM project upgraded to 1.1.11-preview-160506 

### ISSUE THREAD

**Issue by alexdresko** [Windows-XAML/Template10#926]
1. Create a new HM project
2. Upgrade to 1.1.11-preview-160506 
3. Run the project
4. Click Settings on the HM
5. Nothing happens.. 

Incidentally, the settings option works if clicked from the header.. 

gif.. 

![settings not working](https://cloud.githubusercontent.com/assets/333022/15098475/d7bdea94-150c-11e6-8aac-ff31a873a2d3.gif)

**Comment by callummoffat** [comment]
I'm seeing this as well. Very annoying.

**Comment by callummoffat** [comment]
I tried to workaround this issue using the Tapped and Selected events of the HamburgerButton's, with the same result. Something is very wrong...

**Comment by MudzNZ** [comment]
I get same with any added primary buttons nothing happens

**Comment by darshanrampatel** [comment]
I can workaround this by doing the following on Tapped (and removing PageType):

```
        private void SettingsPageButton_Tapped(object sender, RoutedEventArgs e)
        {
            MyHamburgerMenu.NavigationService.Navigate(typeof(Views.SettingsPage));
        }
        public static void HighlightSettingsPageButton()
        {
            if (HamburgerMenu.Selected != Instance.SettingsPageButton)
            {
                HamburgerMenu.Selected = Instance.SettingsPageButton;
            }
        }
```

**Comment by JerryNixon** [comment]
Don't workaround, this is resolved and I will have a new preview today.

**Comment by alexdresko** [comment]
Still happening after the update. Also recorded something I've never seen with the splash screen.. the white screen with the blue box is new to me. 

![plus odd splash](https://cloud.githubusercontent.com/assets/333022/15145752/75634838-1685-11e6-81ae-d05c9b0ae564.gif)

**Comment by JerryNixon** [comment]
Thank you everyone, both of these have been resolved.

**Comment by alexdresko** [comment]
It's fixed! https://github.com/Windows-XAML/Template10/issues/947
