### ISSUE TITLE
Question: adding possible solution for multiple views

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [Windows-XAML/Template10#928]
Hi,
while implementing in my app multiple views I faced an issue with async/await operations and window closing.
As you know, when user closes secondary view it gets consolidated, not closed. This results in preserving resources, dedicated for the view in memory: like window, dispatcher, frames, caches and other things.  I guess there are situations when developer may need to reuse this view so he may not necessarily close it but keep hidden. But in cases when you dev needs to close the window once and for all, he must manually call Window.Close() after consolidation.
This may (and very easily will) end in failure of main thread when any operation on UI thread of those view happens. This is especially hard to identify, if long-running async operation returns to UI thread for further execution. Such cases cause crash.

I personally didn't see any existing solutions for this, would be glad if anyone could suggest. But for myself I found it useful to utilize provided by Microsoft [https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/MultipleViews](example) *_ViewLifetimeControl *_ class. I modified it a bit and with custom SynchronizationContext façade the problem for at least "manually created secondary views" was solved.
Here "manually created secondary views" - views that actually FIRE Consolidated event, as Hosted windows like ShareTarget window -- don't.

So, I wonder, if it's a worth addition to Template10, or there are easier existing ways of preventing this kind of issues, which I simply don't know about?

**Comment by JerryNixon** [comment]
Yes, let put it in Services/ViewService/ViewService.cs and let's implement it in OpenAsync(). I look forward to your Pull Request so I can see the work you have done. and I think T10 will benefit from it.
