### ISSUE TITLE
Error = "The name 'x' does not exist in the namespace 'x'."

### ISSUE THREAD

**Issue by yiyoMX** [Windows-XAML/Template10#935]
Hi, I've been using Template10 to develop a new app, today I encountered a new problem, when I updated the Nuget from 1.1.8 to 1.1.10 I get an error on each of the Views xaml, that says:
i.e. The name "SettingsPageViewModel" does not exist in the namespace "using:AppName.ViewModels".
This happens whith every reference to the ViewModels or to Template10.Behaviors.
It compiles well but the designer view doesn't work.
Its wass working just fine after the update.(I went back to 1.1.8 and its still broken).

UPDATE-The error went away after I closed  VS completely and reopened the project.

**Comment by cgt** [comment]
I am experiencing the same error, except restarting Visual Studio does not resolve the problem. It occurs in brand new projects based on the hamburger template (I have not tested others). I am using the latest version of Template10 from the VS extension gallery. Upgrading the Template10 nuget package in the solution to 1.1.11-preview-160509 does not fix the problem.

@JerryNixon or @inv4der: Would you reopen this issue?

Edit: Never mind... running the application seems to resolve the problem. Just cleaning and rebuilding, which I tried, did not.

**Comment by MrChilBoy** [comment]
I had the same problem with a page that I copied and then renamed. Had to rename and add a few bits (VM class for example) to make all the references correct and had already added the binding to the VM. Commented out the binding and ran it and it came good. Sorry, didn't check if just commenting out the binding was enough. Is there some weird behind the scenes references to the bindings? I remember something like that from my original XAML course.
