### ISSUE TITLE
PR #897 code doesn't exist any more

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#936]
@JerryNixon - PR #897 merged 3 days ago doesn't exist anymore in the current source code.
Is this intentional?

**Comment by callummoffat** [comment]
Looks like the change was reverted for whatever reason.

**Comment by JerryNixon** [comment]
I was not happy with the implementation, I'll have you take a look at the commit associated here and see I it helps. It is not in the NuGet preview package, it is in the GitHub source. Hopefully, this implementation will cause the refresh to occur automatically, without any interaction from the developer. I'll let you guys tell me what you think, but I think we're close if we are not there.

**Comment by dg2k** [comment]
@JerryNixon - It would help if you let me know, by way of feedback, what you're not happy about the implementation. The problem is there and need to be solved. I am quite happy to follow a different approach than I proposed for what appears to be a platform bug. I should add I spent a number of days to get to the root of the problem (visual state not resetting) and suggest a fix.

I should also point out that the fix has no side-effects, even if visual state bug is fixed. The suggested code kicks in (i)  **automatically** to correct NavButtonChecked's visual state, and (ii) when changing the theme during runtime by **dev code** to force VisualStateManager to "normal" for an all-theme-refresh. If the visual state anomaly is corrected, this fix should have no side effects.

Look forward to your feedback on this.

P.S.
In your comment above, you said the following and not clear to me. Is some link missing?

>  I'll have you take a look at the commit associated here and see I it helps.

**Comment by JerryNixon** [comment]
Here
https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Controls/HamburgerMenu.PublicMethods.xaml.cs#L118
And here
https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Controls/HamburgerMenu.xaml.cs#L488

**Comment by JerryNixon** [comment]
Here's where the Visual State otherwise handles the DisplayMode for the developer:

https://github.com/Windows-XAML/Template10/blob/master/Template10%20(Library)/Controls/HamburgerMenu.xaml#L285

**Comment by dg2k** [comment]
Okay, codebehind it is, instead of part xaml. I have tested it and it works.

Now I would like my 'Dynamic Themes' Sample Project -- PR #892 -- not to go to waste as it demonstrates the issues discussed here in action. It has since been simplified with more clarity expected of a sample project.

Would you like me to resubmit a revised #892 ?

**Comment by JerryNixon** [comment]
I understand. Sure. I like clarity and I like simplified. When you submit the sample, do be a favor and please do not include in the PR changes to the library or base templates. Know what I mean? If you have library or template changes you can submit separate PR. Otherwise, since there are so many files with new samples, it's a pain in the neck to vet the PR.
