### ISSUE TITLE
Released Template10.1.1.11-preview-160509 to NuGet

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#938]
This closes #922 
There are several improvements in this build. 
I believe that if this is stable, this can be released.
Thanks @Windows-XAML/community for helping test.
// Jerry

**Comment by callummoffat** [comment]
I'm still seeing #926 in this release. I thought it was fixed?

**Comment by MudzNZ** [comment]
Yea same still getting same behavior #926

**Comment by aline-almeida** [comment]
The same for me. Still get  #926.

**Comment by iamianvs** [comment]
At the risk of being redundant, I also get #926.

**Comment by callummoffat** [comment]
@JerryNixon, are you hearing this? Apparently, #926 is still causing issues. I'm definitely seeing it.

**Comment by JerryNixon** [comment]
Great. Resolved.

**Comment by callummoffat** [comment]
Cool. When will there be a new package with this fix?

**Comment by JerryNixon** [comment]
New preview in a few minutes.

**Comment by callummoffat** [comment]
Cool. Thanks! Can't wait to test!

Can I just say that Template 10 (and it's community) are awesome?
