### ISSUE TITLE
New header section breaks existing page layouts

### ISSUE THREAD

**Issue by teamneusta** [Windows-XAML/Template10#94]
Some commits ago you've added an itemscontrol to the header section. Unfortunately, this new control cannot be hidden and breaks existing pages which have their own header controls.

**Comment by JerryNixon** [comment]
Yes, it was a first approach. Latest commit fixes. HamburgerButton now has HeaderContent which is optional. If you set it, you have to manually add Margin="0,48,0,0" to your Pages to make room for the header and show your content. The idea is good - allows for constant menu. New approach is better.

**Comment by ryanwinter** [comment]
The hamburger button is not visible in narrow mode anymore.
