### ISSUE TITLE
Code Fragments

### ISSUE THREAD

**Issue by mvermef** [Windows-XAML/Template10#943]
Do we have a place to drop code fragments that folks might be interested in, where a whole sample isn't warranted?

**Comment by JerryNixon** [comment]
Let's do it here
https://github.com/Windows-XAML/Template10/wiki/Techniques

**Comment by mvermef** [comment]
Awesome.

**Comment by JerryNixon** [comment]
Are you proud of that?

**Comment by mvermef** [comment]
for now yes I will add more,  that one blocked me for awhile, hybrid of the master/detail (not the control) with SemanticZoom , really had me scratching my head and no one on SO seemed have answer, blend ftw
