### ISSUE TITLE
Mimicing common Windows 10 apps with Template10

### ISSUE THREAD

**Issue by johanlindfors** [Windows-XAML/Template10#945]
I'm trying to mimic appearance and behavior from some of the most common apps in Windows 10 by leveraging Template10 and now I'm stumbled upon how to add SecondaryButton's that doesn't trigger "normal" navigation behavior to pages, but instead triggers commands similar to the Secondary Buttons in the Mail app (the calendar, feedback and settings buttons). I'm currently using Template10 as a nuget package but I'm ready to go back to use it as a "git submodule" instead if it's required...

While I'm thinking about it, maybe a section on this wiki with "How to do that..." which could provide guidance on mimicking great (it's naturally very individual on what's great) appearances and behaviors from common apps would be a very interesting section. Mail, Facebook, Groove, News, Finance...

**Comment by JerryNixon** [comment]
I understand. The trick, by the way, is demonstrated in the Search (and Login) sample. But to give you a quick answer, the HamburgerButtonInfo has a property called ButtonType that you can select "Command" and then handle the Tapped event of the button. If that is too limiting, as I do not understand your scenario, you can also try ButtonType=Literal, which no longer will use the Button template, but will render in the Hamburger Menu only what you put in the content of the Info object.
