### ISSUE TITLE
Can't install template 10 on Visual Studio Express 2015 for Windows 10

### ISSUE THREAD

**Issue by rteshnizi** [Windows-XAML/Template10#946]
I can't install Template 10 on Visual Studio Express 2015 for Windows 10. I believe it is because of the manifest file for the .vsix installer. This [line in the vsixmanifest](https://github.com/Windows-XAML/Template10/blob/master/Template10%20%28Installer%29/Template10.Installer/source.extension.vsixmanifest#L15), I think, is the culprit to be specific.

Please guide.

**Comment by JerryNixon** [comment]
Express is currently not supported. Can you explain why you can't use Community?

**Comment by rteshnizi** [comment]
Because of licensing issues. I am planning to take advantage of the templates for a commercial product. Template 10 itself is under Apache license terms. However, Only Visual Studio Express edition is available for use in commercial products. If Template 10 is used as a main repository for common UWP resources, it would be much more beneficial if it is available for commercial purposes.

**Comment by JerryNixon** [comment]
Well, just great. An honest developer. We don't have a contingency plan in place for that.

**Comment by callummoffat** [comment]
They say honesty is the best policy, but sadly, it often causes more problems than it solves... 

(Not that I endorse lying.)

**Comment by JerryNixon** [comment]
Well, I tell you what @rht1369. You're going to need to solve this problem for yourself by figuring out the correct syntax in the VSIX to support Express, then submitting a Pull Request. And, I promise, that if you promise to test the freaking crap out of it first, I will merge it. But, I don't plan on installing Express and testing it myself. Don't break Community/Enterprise in your efforts. But now you at least have an option.

Sound okay?

**Comment by qmatteoq** [comment]
If you are a single developer, you can use Visual Studio community for commercial products. Limitations in Visual Studio Community applies to enterprises or non enterprises organizations with more than 200 PC or with more than 1 million $ of revenue. Read more here: https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx

**Comment by rteshnizi** [comment]
Thanks for all the suggestions.

@qmatteoq @callummoffat I found it my duty to notify the maintainers of this project before it happens to other enterprise developers.

@JerryNixon That does sound good. I can't promise "testing the crap out of it" but I probably can do some testing.

**Comment by Akshay2595** [comment]
@JerryNixon I tried to search for template 10 in Microsoft Visual Studio Community 2015, but couldn't find it, then I downloaded .vsix file from website and tried to install it manually, and I got error with it stating " VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products."
I have attached log file here, can you please help with this.
[VSIXInstaller_f15052e5-4682-4f32-a52b-8648769e0fdc.txt](https://github.com/Windows-XAML/Template10/files/1114903/VSIXInstaller_f15052e5-4682-4f32-a52b-8648769e0fdc.txt)

**Comment by callummoffat** [comment]
Because T10 support for VS15 has ended. You need to get VS2017.




CJ




This message was brought to you via my Nexus 5X.







On Fri, Jun 30, 2017 at 11:07 PM +1200, "Akshay2595" <notifications@github.com> wrote:












@JerryNixon I tried to search for template 10 in Microsoft Visual Studio Community 2015, but couldn't find it, then I downloaded .vsix file from website and tried to install it manually, and I got error with it stating " VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products."

I have attached log file here, can you please help with this.

VSIXInstaller_f15052e5-4682-4f32-a52b-8648769e0fdc.txt
