### ISSUE TITLE
Shell is being loaded along with Splashscreen loading.

### ISSUE THREAD

**Issue by jerinjohnk** [Windows-XAML/Template10#948]
#262 issue was fixed earlier ref(Splash screen modal #262). But with the new 1.1.10 the same error is occurring once again. In 1.1.8 its was working fine.

As it says inside `App.xaml`->`OnStartAsync` once we add delay say `await Task.Delay(2000);` for viewing the extended SplashScreen animation we can see Hamburger icon due to Shell being loaded.

**Comment by JerryNixon** [comment]
Resolved. Thanks for reporting.
