### ISSUE TITLE
How can I create a multi level Menu with this Template ??

### ISSUE THREAD

**Issue by dnxit** [Windows-XAML/Template10#949]
How can I create a multi level Menu with this Template ??

**Comment by JerryNixon** [comment]
It depends on what you really want. Do you mean multi-level like blades, or multi-level like a tree view? Blades are super-simple. Just create the blade and control its visibility. If you mean a tree view, if you are not talking too complex, then you can take advantage of the HamburgerButtonInfo.ButtonType=Literal property and create a parent element that hides and shows children. The children can still be simple buttons.

**Comment by JerryNixon** [comment]
You'd have better luck on StackOverflow
