### ISSUE TITLE
HamburgerMenu to support wide mode

### ISSUE THREAD

**Issue by ryanwinter** [Windows-XAML/Template10#95]
I think a wide mode would be very useful for this control. Basically at a certain width, the splitview would change to CompactInline mode, with the ability to collapse to an icon bar (similar to CompactOverlay mode). Also we should save the expanded/collapsed state.

This would be consistent with applications like Groove Music.

**Comment by JerryNixon** [comment]
Yeah, we should consider putting that back.

**Comment by JerryNixon** [comment]
There's a new Wide state and property in the current branch. I setup the Custom.xaml styles to include it but default it to off by setting it to -1.

**Comment by ryanwinter** [comment]
That was quick!

**Comment by mdtauk** [comment]
Is the width for the SplitView Pane hardcoded, or a variable/StaticReference you can set on the control?

**Comment by ncarandini** [comment]
Please don't ask on closed issue, open a new one :-)
