### ISSUE TITLE
VSIX type has changed (important)

### ISSUE THREAD

**Issue by JerryNixon** [Windows-XAML/Template10#955]
Okay @alexdresko, I'll do it, or you can submit an update for me. There needs to be two VSIX packages. One is the "Template 10 Template Pack" and the second is the "Template 10 Snippets Pack". This is required because we cannot include snippets in a template VSIX without changing its type and the Visual Studio Gallery will give the package a new ID which will not allow developers to upgrade existing. Make sense?

**Comment by alexdresko** [comment]
Doh! Sorry about that. I'll be happy to look at it. Might take me a couple of days tho.

Man, that bums me out...

**Comment by JerryNixon** [comment]
Sure. Want to release on Friday, though. Do what you can.

**Comment by alexdresko** [comment]
@JerryNixon Where are you seeing this change?

**Comment by JerryNixon** [comment]
In the Gallery, it's enforced there.

**Comment by callummoffat** [comment]
Any updates on this issue? I really want the new templates!

**Comment by JerryNixon** [comment]
I've created the VSIX

**Comment by alexdresko** [comment]
Sorry I wasn't able to get to this @JerryNixon. I got into a car accident the other day and haven't really been able to get to my computer very much since.
