### ISSUE TITLE
Four Good Reasons for Providing DisplayModeChanged Event in T10

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#958]
Re: PR #952
1. No code bloat; only two lines in T10!
2. DisplayModeChanged's event argument provides complete info as previous display mode **e.OldValue** and new display mode **e.NewValue**. Such info is useful in the new _Adaptive UI_ programming (now becoming pervasive). If an event tells me that the display mode is changing from, say, **Overlay** to **CompactInline**, I can take a more proactive action than otherwise be the case. Bottom line: more info does no harm. With the alternative **HamburgerMenu.RegisterPropertyChangedCallback(...)**, as far as I can establish, you only get to know a new display mode. Yes, you can save the current display mode, and use as old value when a new one arrives, but with display mode (i) change registration, (ii) event handling, and (iii) house-keeping for old value, the dev code ends up with relatively several lines. In contrast, only two lines needed in T10.
3. There is already a compelling reason for using DisplayModeChanged event. Suppose you decide to hide the Hamburger button  --  see demo of this already in the Hamburger Sample Project. You need to override this setting for Overlay display mode as hiding Hamburger button is a no-no in the Overlay mode (check this with the Hamburger Sample project). What better place than in the event handler for such use case? If the setting for `HideHamburgerButton` is true, we override this to false for Overlay. Where is the logical place for such code?
4. Reason No. 4: Developers would love T10 (and Jerry Nixon) _even more_ ;-)

**Comment by JerryNixon** [comment]
Okay.
