### ISSUE TITLE
Indeterminate progress indicators should not be active when collapsed

### ISSUE THREAD

**Issue by timheuer** [Windows-XAML/Template10#96]
Template10 / Templates (Project) / Minimal / Views / Shell.xaml 

Things like ProgressRing and indeterminate progress bars should not be IsActive="True" unless they are visible.  Unless _they_ are specifically collapsed, then the animations actually are still running, causing potential perf issues.  Collapsing a parent container (e.g., grid, panel, etc.) isn't enough as that doesn't trigger turning activity off for them.

**Comment by JerryNixon** [comment]
Daniel warned me of this, too. We'll fix it asap.

**Comment by darenm** [comment]
The code-behind implemented this - alas we forgot to update the XAML. Fixed.

**Comment by JerryNixon** [comment]
Now that's asap!
