### ISSUE TITLE
BackButton on tablet odd behavior

### ISSUE THREAD

**Issue by dubstylee** [Windows-XAML/Template10#961]
I finally installed my Template10 app on my Windows 10 tablet, and began testing. One thing I noticed is that regardless of the back button setting (shell back button or not), the back button doesn't display in the PageHeader, and I have to use the shell back button no matter what.

Is this something that is related to T10, or is it something intentional with Windows 10?

**Comment by dg2k** [comment]
Setting `ShowShellBackButton = false` should do the trick. 
If the value is persisted with settings, as in sample project,  such as
`ShowShellBackButton = settings.UseShellBackButton`;
do this from Settings (simply guessing here as I have no idea of your test prog). If not, just set it `false` in the App ctor().
And on the PageHeader control in a xaml page add the attribute:
BackButtonVisibility="Collapsed"

**Comment by dubstylee** [comment]
It is based on the Minimal sample project. I will try your suggestions once I get home and have my tablet handy. The app works correctly on both my desktop and laptop, but not on the tablet.

What is the `BackButtonVisibility="Collapsed"` for? The idea is for the back button to be visible (when CanGoBack = true). The shell back button is always visible on my tablet, so I was thinking maybe the version of Windows 10 might play a part in this issue.

**Comment by dg2k** [comment]
Sorry, please ignore the last sentence - I don't know how cutting and pasting brought in that text. BackButtonVisibility is automatically set  in PageHeader when ShowShellBackButton is false.

**Comment by JerryNixon** [comment]
This is by design. In Tablet mode, Windows 10 shows the back button in the system TaskBar every single time, and this cannot be changed. In this case, the Header automatically hides the back button so it is not duplicated.
