### ISSUE TITLE
Page / PageHeader jumps when changing pages

### ISSUE THREAD

**Issue by klm1** [Windows-XAML/Template10#963]
Using Template 10, v1.17 with Visual Studio 2015, update 2. Notice that just building an empty Template 10 Hamburger app (same with a Template 10 Minimal app) that the PageHeader and content below it visibly moves down then back up with every page change.

See video for a demonstration of this.

http://screencast.com/t/AbDk6FIoqanH

**Comment by JerryNixon** [comment]
This behavior is due to the animation of the page. You can disable this yourself with code like this:

``` XAML
<Controls:HamburgerButtonInfo x:Name="SettingsButton"
                    PageParameter="0"
                    PageType="views:SettingsPage">
    <Controls:HamburgerButtonInfo.NavigationTransitionInfo>
        <SuppressNavigationTransitionInfo />
    </Controls:HamburgerButtonInfo.NavigationTransitionInfo>
    <StackPanel Orientation="Horizontal">
        <SymbolIcon Width="48"
        Height="48"
        Symbol="Setting" />
        <TextBlock Margin="12,0,0,0"
        VerticalAlignment="Center"
        Text="Settings" />
    </StackPanel>
</Controls:HamburgerButtonInfo>
```

Please note this part

``` XAML
    <Controls:HamburgerButtonInfo.NavigationTransitionInfo>
        <SuppressNavigationTransitionInfo />
    </Controls:HamburgerButtonInfo.NavigationTransitionInfo>
```

**Comment by klm1** [comment]
Ah, thanks Jerry -- I didn't see the "real" News app behaving this way so made the (incorrect) assumption that there was a problem. Thanks for straightening me out!
