### ISSUE TITLE
Declaring viewmodellocator get error Cannot load assembly Template10Library

### ISSUE THREAD

**Issue by MudzNZ** [Windows-XAML/Template10#965]
Hi,

I'm on the latest preview build, I am trying to declare my v=ViewModelLocator in App.xaml where it keeps throwing the below error. 

Error		Could not load file or assembly 'Template10Library, Version=1.0.5976.38151, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The bound assembly has a version that is lower than that of the request. (Exception from HRESULT: 0x80132000)

I'm not sure how to resolve this issue?

**Comment by JerryNixon** [comment]
![image](https://cloud.githubusercontent.com/assets/1749983/15274655/fdbd198c-1a74-11e6-9177-23f3da8af148.png)

Since you left no code and very few details, I have to guess what your problem is. I assume you have looked at the sample project with the code above? Does that help at all?

**Comment by MudzNZ** [comment]
Hi sorry, there's not much to show in the way of code except for the above.  I have it set up exactly the you have but I still get the same error on the <vm:ViewModelLocal... line.  I have installed the MvvmLightLibs package could that be affecting it?

I will try reproduce the issue when I am home later with a new project and see how I go.

**Comment by MudzNZ** [comment]
Cant seem to reproduce the error with a new project.  I still get it on my current project but it builds ok now so I can progress.
