### ISSUE TITLE
Bad layout when opening menu in Hamburger project

### ISSUE THREAD

**Issue by pekspro** [Windows-XAML/Template10#966]
If you start the Hamburger template project in a small window and then open the menu it looks like this:

![badburger](https://cloud.githubusercontent.com/assets/3163293/15272992/24c965d8-1a8b-11e6-876b-324ea3590907.png)

If you make the window larger and then small again it looks alright.

Tested with current source code.

**Comment by JerryNixon** [comment]
Hey @dg2k, I think you will be able to spot the issue around this with me. Since DisplayMode, et al, are now two-way bindings, there' something happening with timing. Any bright ideas?

**Comment by dg2k** [comment]
@JerryNixon - I know what it's. PR coming up (may not be bright idea but works).

**Comment by dg2k** [comment]
@pekspro -- The following may help you go past the Inline DisplayMode problem. In Shell.xaml.cs ...

```
public Shell()
{
    Instance = this;
    InitializeComponent();
    ...
    Loaded += Shell_Loaded;
}

private void Shell_Loaded(object sender, RoutedEventArgs e)
{
    //  set to display mode other than Inline, e.g., CompactOverlay below
    HamburgerMenu.DisplayMode = SplitViewDisplayMode.CompactOverlay;
}
```

Just in case it helps ...

**Comment by pekspro** [comment]
I just downloaded the latest source and now the menu button doesn’t open anything in the Hamburger project. I added your code also @dg2k but still the same.

Either way, personally I don’t use the hamburger yet in my projects to no issue for – yet :)

**Comment by dg2k** [comment]
I can only comment after the PR is merged but before that difficult in what state you'd find my code in yours.

I noticed a similar problem yesterday (the stack-overflow problem which freezes HamburgerMenu) and PR #978 solved the problem. Let's wait and see.
