### ISSUE TITLE
Debug configuration error

### ISSUE THREAD

**Issue by callummoffat** [Windows-XAML/Template10#97]
When I try to submit an application to the Windows Store, I fail certification, because apparently Template10Library.dll is built using debug configuration. Windows App Certification kit does not show this, just the Store submission process. Any ideas?

**Comment by JerryNixon** [comment]
Yes, that is a problem. Sheesh. It also does not compile to ARM in v1.0.0.
This will be fixed asap. That being said, if you are in a hurry, then you should download the source from GitHub that doesn't have any of these problems. It is just the current NuGet PACK.

**Comment by callummoffat** [comment]
How would I use that? Just reference the Library in my project?

_Callum Moffat_
App Developer
Windows 10 Enthusiast

---

Wanna (calculate a) date? Use Advanced Duration Calculator, a free app for
Windows 10!
https://www.microsoft.com/store/apps/9WZDNCRCSFL2?cid=mailsigcampaign

**Comment by darenm** [comment]
Yes - you would pull down the source from GitHub, Add Existing project to your solution and reference the Template10 Library project.
