### ISSUE TITLE
No UI with 1.1.11-preview-160512

### ISSUE THREAD

**Issue by alexdresko** [Windows-XAML/Template10#970]
I've been pulling my hair out trying to figure out what kind of stupid thing I did to make my app only show a blank white screen after the splash screen disappears, but it appears to be a problem with the latest build.. 

gif.. 

![blank screen](https://cloud.githubusercontent.com/assets/333022/15275787/d49a191e-1aa2-11e6-8ab6-c6db3bcc6165.gif)

**Comment by dg2k** [comment]
Look at #956.

**Comment by alexdresko** [comment]
Thanks. Now if I could just stop watching that gif repeat over and over again...
