### ISSUE TITLE
HamburgerMenu DisplayMode by default is Inline

### ISSUE THREAD

**Issue by Viachaslau-Zinkevich** [Windows-XAML/Template10#972]
Hi, I fetched latest git version and got the following issue:
When app starts it's for some reason doesn't take into account any Narrow/Medium/Wide width and just uses Inline. 
When I at least once change style to any other (Narrow/Medium) -- then it starts behaving normally.

**Comment by dg2k** [comment]
PR #971 will correct this, I think.

**Comment by Viachaslau-Zinkevich** [comment]
@dg2k thanks, I'll check when merged. Is it also due to not triggering VisualStateGroup_CurrentStateChanged on start?

**Comment by dg2k** [comment]
VisualStateGroup_CurrentStateChanged too but there is more.
In principle, the developer/user should be able to choose the appropriate display mode. There was no particular reason for setting the initial to Inline, except that it was set to be overridden by the visual state. When the visual state failed, the Inline problem cropped up. It's funny that Inline did not even feature as a candidate mode (see throughout the code and Inline doesn't show up as a display mode of interest). 

I personally like **CompactOverlay** for screen size >= **VisualStateNormalMinWidth** (same as the **News** app on **Windows 10**). T10 automatically sets to CompactOverlay for screen size >= VisualStateNormalMinWidth and < VisualStateWideMinWidth at which point it moves to the CompactInline display mode. Of course, for small screens ( < VisualStateNormalMinWidth ) **Overlay** is the one we can't do without and in my PR I even made this setting to override any other setting (and hope @JerryNixon will approve this).

For screen size >= VisualStateNormalMinWidth I think the developer (perhaps user??) should be able to choose any of the display modes. While this can be done, there is more room to make this much easier. Think of _preferred display modes_ that you can set to influence how the visual states make transition.

**Comment by dg2k** [comment]
_Update:_  @Viachaslau-Zinkevich -- Set the display mode in **Shell.xaml.cs**'s _Loaded_ event handler and the problem with the Inline DisplayMode will not affect you.

```
public Shell()
{
    Instance = this;
    InitializeComponent();
    ...
    Loaded += Shell_Loaded;
}

private void Shell_Loaded(object sender, RoutedEventArgs e)
{
    //  set to display mode other than Inline, e.g., CompactOverlay below
    HamburgerMenu.DisplayMode = SplitViewDisplayMode.CompactOverlay;
}
```

**Comment by Viachaslau-Zinkevich** [comment]
@dg2k this actually won't help as I need Display mode depending on screen size, like what VisualStates should initially do. This affects the app depending in which size it starts and I personally don't want to duplicate the same code from HamburgerMenu inside my app

**Comment by dg2k** [comment]
@Viachaslau-Zinkevich I understand, I meant as a temp measure, just in case.

**Comment by Viachaslau-Zinkevich** [comment]
@dg2k oh, I see. Actually it works even if specific value us set directly from XAML for HamburgerMenu. It will be then the starting value
