### ISSUE TITLE
Hamburger menu items on hover are wiped out.

### ISSUE THREAD

**Issue by MMalikKhan** [Windows-XAML/Template10#977]
Hi, I just upgraded from 1.1.3 to 1.1.10 and i am having this wired issue with the hamburger menu items which are Black text with white background and when i hover it i see nothing .. i believe its applying some hover or doing some toggle due to which the buttons just look invisible. ? could you please guide me how can i let them not change anything on mouse hover on windows 10?

**Comment by dg2k** [comment]
See if #980 helps.

**Comment by JerryNixon** [comment]
Leave a comment

**Comment by MMalikKhan** [comment]
Hi @JerryNixon  i still have the issue with the black color text in the menu item is not visible once you hover the menu item .. do you think is there any specific hoverStyle can set it not to apply any changes?
