### ISSUE TITLE
Hamburger icon is gone

### ISSUE THREAD

**Issue by youtoofan** [Windows-XAML/Template10#98]
Icon disappears in compact mode

**Comment by ProH4Ck** [comment]
Same here. Hamburger icon is covered by PageHeader on mobile view.

**Comment by janabimustafa** [comment]
I'm not 100% sure, but It seems like the old "airspace" issue still applies today with rendering things on top of the Frame. https://msdn.microsoft.com/en-us/library/aa970688(v=vs.100).aspx

nvm, that's not it.

**Comment by janabimustafa** [comment]
This issue should be closed. The minimal project and the rest of the templates, by default reference the nuget Template10 package (v1.0.0), which has this issue. Changing the reference to the Template10 (Library) project with the most current code fixed it.

**Comment by JerryNixon** [comment]
Thanks
