### ISSUE TITLE
When updating Template10 it's easy to overlook updating App and Shell as well.

### ISSUE THREAD

**Issue by dg2k** [Windows-XAML/Template10#980]
When you update Template10 via NuGet and get compilation errors, you know what to do; something must have changed from the last version of Template10 you had, so you'd look for what might have changed and correct them, in effect updating the dev side of the code.

In a very rare case you may not get any compilation errors but get HamburgerMenu's (or your app's) visual display in an unexpected way. This is possible when things in the App BootStrapper have changed, with an impact on how the splash screen is displayed and/or how the App is initialized and the view page frame is called into action.

The morale of the story: make sure that when Template10 Nuget is updated, you check if new changes are reflected in your developer code (App and Shell files). This can be easily and quickly done by inspecting App and Shell files under the **Templates(Projects)** as these files always sync with Template10 changes.

**Comment by MMalikKhan** [comment]
thanks @dg2k i drilled further and it looks like it is inverting the black color text into white and that is the reason it is not visible on hover.. i have other color test like gray in one of the menu item and i see that stays and anything which is in Black just goes invisible once the mouse enter the menu item..

**Comment by dg2k** [comment]
I might? know the problem you're referring to. A sample project I will upload soon may shed some light if what I think is right. There is a subtle thing about theme refresh. It's is possible that this is unrelated but you can judge for yourself with a PR coming up.

**Comment by MMalikKhan** [comment]
thanks @dg2k i look forward for your suggestion

**Comment by dg2k** [comment]
@MMalikKhan -- almost forgot to follow up this -- sorry. The PR I was referring to above was PR #998 which deals with the visual problems which I suspect may be what you were experiencing. Sorry this comes a bit late but if you've any feedback to make (even if the sample didn't help), that would be appreciated.

**Comment by MMalikKhan** [comment]
@dg2k thanks, is this already available in the current release on nuget? I am back to give my second chance in upgrading from 1.0.2 to latest. the last time i tried, i had so many issues.. i cant move forward. not particularly with Template 10. I have issues with EF7 upgrade from Rc1 to RC2. they almost rewrote that EF lots of braking changes. I have released there final version i am hoping this should be better then there RC2.
