### ISSUE TITLE
UWP Tooling SDK Versions...

### ISSUE THREAD

**Issue by mvermef** [Windows-XAML/Template10#986]
which versions of the sdk do you presently have installed?  1.3.1 or 1.3.2, reason I ask is I am not getting execution past the Splashscreen. Yet logging and settings file show it did navigate to the appropriate screen, due to logic present in my application.  Got any ideas?

**Comment by callummoffat** [comment]
What SDK? There are lots of SDK's.

**Comment by mvermef** [comment]
UWP, sorry was specific when I posted it...

**Comment by callummoffat** [comment]
UWP SDK versions (non-preview) are 10240, and 10586. Template 10 supports both, so this issue is something else.

**Comment by callummoffat** [comment]
Actually, this sounds like an issue with the Nuget preview build 1.1.11-preview-160511. Should be fixed in the latest version, which was released today. Try updating your app to support the new version, and see if that solves your problem.

**Comment by mvermef** [comment]
I use hard references for the most part, will pull the latest source in a few and see.. I had gone back and actually updated all code items to reflect changes recently to the actual shell/app.cs, hoping the latest fix i saw merged would solve this issue...

**Comment by mvermef** [comment]
no change in application status... Just chills at the SplashScreen, no idea what caused this...

**Comment by callummoffat** [comment]
Well, it's not something I've seen or heard about. It's not the UWP version, I use both SDK versions without any problems. It's not a known issue. I'd check through your app's code. Might be something related to that.

**Comment by mvermef** [comment]
almost feels like an async/await stuck somewhere

**Comment by callummoffat** [comment]
Do you have any of those in your App.xaml.cs (before navigation)? I've found that some async calls stall, and leave you at the splash-screen forever.

**Comment by mvermef** [comment]
shitty ass logic is what caused this, problem solved...
