### ISSUE TITLE
Hamburger manu button will be blank when toggle it to fullscreen in Narrow mode.

### ISSUE THREAD

**Issue by lyling** [Windows-XAML/Template10#987]
sorry, I can`t upload any pics from my network.

**Comment by JerryNixon** [comment]
I can't be sure if you are reporting the current NuGet production pack or the preview pack. I have just tested the preview pack and this is NOT the behavior. And the preview will be promoted sometime today after we are finished testing it. If it's the preview, please submit the repro steps asap.

**Comment by lyling** [comment]
i am using the newest source code from the time i submit this issue.

please check my attachment, a gif.

![issue_hammenu_toggle](https://cloud.githubusercontent.com/assets/485493/15414349/6af13f60-1e6c-11e6-83e0-126f1d1d9202.gif)

**Comment by lyling** [comment]
@JerryNixon can u see my gif?
