### ISSUE TITLE
"More" button in PageHeader command bar when command bar button was not visible on start

### ISSUE THREAD

**Issue by SamuelLioult** [Windows-XAML/Template10#989]
The button "more" does not appear when the command bar buttons was not visible from the start.
For example my app starts in VisualStateWide. For any reason, I don't want to display command bar buttons in this state (in XAML the default button visibility is Collapsed).
When my window switches to VisualStateNarrow, I display my buttons. But in this case, my buttons appear but not the "more" button (to show labels).
I hope it is clear.

**Comment by JerryNixon** [comment]
Sure. What is the technique you are using to hide and show buttons?

**Comment by SamuelLioult** [comment]
Okay, it seems the problem appear just with the 1.1.11-preview-160512 version. I updated to the last preview and it works well.
Otherwise my technique is using visual states directly in XAML.
