### ISSUE TITLE
Core:NavigateToPageAction in XAML with Behavior don't work in Template10

### ISSUE THREAD

**Issue by freestyle88** [Windows-XAML/Template10#991]
If i try to Navigate to a Page with NavigateToPageAction in XAML in Template 10 App it throws an Exception.

> ```
>     <Button x:Name="button" Content="Klick">
>         <Interactivity:Interaction.Behaviors>
>             <Core:EventTriggerBehavior EventName="Click" SourceObject="{Binding ElementName=button}">
>                 <Core:NavigateToPageAction TargetPage="WindowsApp1.Views.BlankPage1" />
>             </Core:EventTriggerBehavior>
>         </Interactivity:Interaction.Behaviors>
>     </Button>
> ```

If i do the same with normal Blank App thats Navigate

**Comment by JerryNixon** [comment]
Template 10 navigates using the NavigationService. Your best bet is to create a method that navigates for you. Using an action that doesn't understand Template 10 just won't work. By the way, there's a Nav action in Template 10, but it is incomplete.
