### ISSUE TITLE
NavigationService.Reload method

### ISSUE THREAD

**Issue by mitkodi** [Windows-XAML/Template10#995]
What about adding a **NavigationService.Reload(object param)** method?

**Comment by JerryNixon** [comment]
Good idea. You know `NavigationService.Refresh()` already exists, though, right?

**Comment by mitkodi** [comment]
Yes, but it doesn't have parameter, so we cannot reload it using different/modified parameter. At the moment I just navigate to the same page type, followed by removing the last BackStack entry, but thought it could be helpful if we have it out of the box.

**Comment by callummoffat** [comment]
I have a suggestion. Why not create an overload of NavigationService.Refresh which takes an argument?

**Comment by schuettecarsten** [comment]
Should be possible to add a parameter with default value=null to the method...

**Comment by callummoffat** [comment]
Give me a few days - I'll implement this and submit a pull request. Sound good?

**Comment by callummoffat** [comment]
I've submitted a PR (#1002).

**Comment by callummoffat** [comment]
It should be noted that my implementation of this actually navigates to the current page with new parameters. This does call OnNavigatedToAsync, which some developers may find annoying. However, my logic is that the new parameters need to be processed, which necessitates this.

**Comment by schloempe** [comment]
I use Template10 v1.1.12. Method Refresh with Parameter is there, but with Parameter it throws an exception.  Without (no exception), but OnNavigatedToAsync is not called. Why?

**Comment by Raamakrishnan** [comment]
I am also getting an exception on using Refresh with parameter on Template10 1.1.12, same as @schloempe. Are there any workarounds?
